### ISSUE TITLE
自定义主题 全局引入 报错

### ISSUE THREAD

**Issue by yangzhaoguo** [jdf2e/nutui#100]
![微信截图_20190517151442](https://user-images.githubusercontent.com/27938016/57909926-9b83d500-78b6-11e9-9739-c18baa892d6b.png)

**Comment by yangzhaoguo** [comment]
![123](https://user-images.githubusercontent.com/27938016/57910748-97f14d80-78b8-11e9-80ef-7e3e973dbd13.png)
webpack.config.js 代码

**Comment by richard1015** [comment]
vue cli3 NutUI 按需加载、 定制化主题 请参考 https://github.com/richard1015/nutui-demo
vuecli2 请参考 http://nutui.jd.com/#/theme

如果还报错，请附上最小可复现仓库地址
