### ISSUE TITLE
[bug]Popup 组件 destroy-on-close属性无效

### ISSUE THREAD

**Issue by EdivenH** [jdf2e/nutui#1010]
## 问题描述
Popup 组件 destroy-on-close属性无效，设置为true 关闭后，组件不会销毁

## 相关环境信息
- **操作系统**：
- **Node 版本**：v16.13.0
- **NutUI 版本**： @nutui/nutui-taro@3.1.16
- **Vue 版本**：3.0.0
- **引用方式**：  NPM

**Comment by szg2008** [comment]
这个属性的含义是弹层关闭之后，slot内容会不会被清空，更新下文档。
