### ISSUE TITLE
[bug] “Menu 菜单”组件，当显示内容没有超过设置的高度，滚动的时候会穿透滚动页面

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#1015]
## 问题描述

页面内容高度大于显示区域高度。将菜单组件“.nut-menu-item__content”的max-height设置大一点，点击菜单后显示内容，然后滚动/滑动页面，导致body滚动(穿透滚动)
![image](https://user-images.githubusercontent.com/40783535/154618542-5531ee28-50a9-4091-97f6-f6348ce89cda.png)

![image](https://user-images.githubusercontent.com/40783535/154618251-79ac9ca5-4ef3-437e-b882-7929f494bbb5.png)

**Comment by wangyongxiong** [comment]
NutUi已更新至3.1.16

**Comment by yangjinjun3** [comment]
感谢反馈，我这里无法复现，您方便提供最小复现仓库吗？

**Comment by yangjinjun3** [comment]
感谢反馈，我这里没有复现，方便提供最小的复现仓库吗？
