### ISSUE TITLE
[bug]进度条百分比内显示 100% 时有样式问题

### ISSUE THREAD

**Issue by bigpigOne** [jdf2e/nutui#1016]
官方示例中，进度条百分比内显示 100% 时有样式问题
`<template> <nut-cell> <nut-progress percentage="100" :text-inside="true" /> </nut-cell> </template>`

**Comment by bigpigOne** [comment]
<template>
     <nut-cell>
        <nut-progress percentage="100" :text-inside="true" />
      </nut-cell>
</template>

**Comment by bigpigOne** [comment]
`<template>
     <nut-cell>
        <nut-progress percentage="100" :text-inside="true" />
      </nut-cell>
</template>`

**Comment by Drjingfubo** [comment]
描述一下具体问题

**Comment by bigpigOne** [comment]
100%时 右边溢出了，效果用官网在线调试看一下就知道了。

![image](https://user-images.githubusercontent.com/92560015/154892351-6a98a93a-9cd2-49eb-b2da-5a609078f293.png)
![image](https://user-images.githubusercontent.com/92560015/154892393-fd83fd94-896e-462e-9215-995a2e7d6b69.png)

**Comment by bigpigOne** [comment]
@Drjingfubo 我用的 left 和 transform 百分比解决的，不知道有没有其他更好的方案。
![image](https://user-images.githubusercontent.com/92560015/154891461-db070aeb-969f-4131-814d-6a8935999b58.png)
![image](https://user-images.githubusercontent.com/92560015/154892301-7063c140-80d3-48a6-9196-2f41b8ceb757.png)
![image](https://user-images.githubusercontent.com/92560015/154892871-6cd5c884-b080-4e8d-9be7-9551a4c5f6a3.png)

**Comment by Drjingfubo** [comment]
把整个进度条宽度缩小就可以了  百分比内显还要占据一些宽度

**Comment by bigpigOne** [comment]
@Drjingfubo 缩小肯定也不行，得让百分比內显 x方向偏移对应的百分比  transformX(-processTran %)
这样100%时候內显右侧正好在进度条右内侧，0%的时候內显左侧在进度条左内侧

**Comment by Drjingfubo** [comment]
那样会占据太多进度条的长度

**Comment by bigpigOne** [comment]
@Drjingfubo 看见我实现的那个了吗？

**Comment by bigpigOne** [comment]
![image](https://user-images.githubusercontent.com/92560015/154901587-bd0ad132-26b4-4c3c-850e-71ded5b09e9f.png)
这是缩小之后 还是溢出

**Comment by bigpigOne** [comment]
如果100%的时候內显溢出了，那还叫內显吗

**Comment by Drjingfubo** [comment]
百分比内显是占据进度条一点宽度 然后在进度条后边的

**Comment by Drjingfubo** [comment]
我优化一下
