### ISSUE TITLE
[bug] BackTop复制官方文档中的代码无法显示

### ISSUE THREAD

**Issue by programfault** [jdf2e/nutui#1019]
## 问题描述

使用Taro Vue3, 从官网复制代码https://nutui.jd.com/#/backtop 到主页面, 按钮不显示
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by shijunti19** [comment]
@szg2008 
我晕
你们小程序版本方法不一样文档写下啊
 <template #content>
要包在里面的
