### ISSUE TITLE
微信小程序端使用Menu 菜单组件，给默认值不会展示

### ISSUE THREAD

**Issue by Rxiaoyi** [jdf2e/nutui#1023]
## 问题描述
微信小程序端使用Menu 菜单组件，给默认值不会展示

<template>
  <nut-menu>
    <nut-menu-item v-model="state.value1" :options="state.options1" />
    <nut-menu-item v-model="state.value2" @change="handleChange" :options="state.options2" />
  </nut-menu>
</template>

<script>
import { reactive, ref } from 'vue';

export default {
  setup() {
    const state = reactive({
      options1: [
        { text: '全部商品', value: 0 },
        { text: '新款商品', value: 1 },
        { text: '活动商品', value: 2 }
      ],
      options2: [
        { text: '默认排序', value: 'a' },
        { text: '好评排序', value: 'b' },
        { text: '销量排序', value: 'c' },
      ],
      value1: 0,
      value2: 'a'
    });

    const handleChange = val => {
      console.log('val', val);
    }

    return {
      state,
      handleChange
    };
  }
}
</script>

## 相关环境信息
- **NutUI 版本**： @nutui/nutui@3.0

**Comment by Rxiaoyi** [comment]
请问这个问题修复了吗

**Comment by yangjinjun3** [comment]
谢谢您的反馈，烦请提供下最小复现包，只保留搭建框架（比如Taro）和引入menu组件，谢谢！

**Comment by yangjinjun3** [comment]
感谢您的反馈，升级到最新版再试下看看呢！

**Comment by Rxiaoyi** [comment]
非常感谢，已经处理好了，就是版本的问题
