### ISSUE TITLE
[bug]ImagePreview引用时报错

### ISSUE THREAD

**Issue by Bowencn** [jdf2e/nutui#1024]
## 问题描述

taro使用vue3开发时 在app.tsx引入ImagePreview后 app.use(ImagePreview) 会在终端报错
Module not found: Can't resolve '@nutui/nutui-taro/dist/packages/_es/ImagePreview'
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
app.ts文件下
import { ImagePreview } from '@nutui/nutui-taro';
App.use(ImagePreview)
![image](https://user-images.githubusercontent.com/37268865/155270683-a88fd89f-de5d-4be2-bbb4-17e2609b65ef.png)

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：14.17.5
- **NutUI 版本**： @nutui/nutui-taro@3.1.16
- **Vue 版本**：3.0.0
- **引用方式**：  NPM

**Comment by SHJuny** [comment]
我引用了v3.1.17版本的  也是出现了这个问题，需要怎么解决呢？

**Comment by zarkin404** [comment]
babel.config.js 内容改一下应该就可以了

```
// babel-preset-taro 更多选项和默认值：
// https://github.com/NervJS/taro/blob/next/packages/babel-preset-taro/README.md
module.exports = {
  presets: [
    [
      'taro',
      {
        framework: 'vue3',
        ts: true,
      },
    ],
  ],
  plugins: [
    [
      'import',
      {
        libraryName: '@nutui/nutui-taro',
        libraryDirectory: 'dist/packages',
        customName: (name, file) => {
          if (name == 'Locale') {
            return '@nutui/nutui-taro/dist/packages/locale/lang';
          } else {
            return `@nutui/nutui-taro/dist/packages/${name}`;
          }
        },
        style: (name, file) => name.toLowerCase() + '/index.scss',
        camel2DashComponentName: true,
      },
      'nutui3-taro',
    ],
  ],
};
```
