### ISSUE TITLE
[bug] SearchBar 搜索栏 的search 事件 在H5中会刷新当前页面

### ISSUE THREAD

**Issue by tqn911024** [jdf2e/nutui#1025]
## 问题描述
在使用搜索栏的时候，使用了search事件，在敲击回车或者使用手机软键盘的确认时候，触发的是页面刷新而非搜索事件

## 最小可复现仓库
<nut-searchbar v-model="searchValue" @submit="search">
        <template v-slot:leftin>
          <nut-icon size="14" name="search2"></nut-icon>
        </template>
        <template v-slot:rightout >
          <view >
            搜索
          </view>
        </template>
      </nut-searchbar>

## 预期的行为和实际行为
预期的行为 :敲击回车或者手机软键盘中的确定键，回调我输入的值
实际行为:   敲击回车或者手机软键盘中国的确定键,当前页面刷新

## 复现步骤，具体代码
H5中运行
<nut-searchbar v-model="searchValue" @submit="search">
        <template v-slot:leftin>
          <nut-icon size="14" name="search2"></nut-icon>
        </template>
        <template v-slot:rightout >
          <view >
            搜索
          </view>
        </template>
      </nut-searchbar>

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：@nutui/nutui-taro@3.1.16
- **Vue 版本**：   3.0
- **引用方式**： npm ？

**Comment by bigpigOne** [comment]
@submit 改成 @search试试

**Comment by szg2008** [comment]
已修复v3.1.17
