### ISSUE TITLE
在form使用uploader组件在h5中会触发提交事件[bug]

### ISSUE THREAD

**Issue by huangxiaonian93** [jdf2e/nutui#1038]
## 问题描述
@nutui/nutui-taro 在form使用uploader组件在h5中会触发提交事件

## 最小可复现仓库
```
<nut-form>
   <nut-uploader url="http://服务地址"></nut-uploader>
</nut-form>
```

## 预期的行为和实际行为
希望正常显示，可是无反应

## 相关环境信息
@nutui/nutui-taro 3.1.16版本

**Comment by richard1015** [comment]
已修复  等待3.1.18 发布

**Comment by richard1015** [comment]
v3.1.18 已发布
