### ISSUE TITLE
nut-popup  页面数据多的话 反应慢

### ISSUE THREAD

**Issue by pupillxy** [jdf2e/nutui#1040]
## 你想知道什么？

nut-popup 这个组件 页面数据多的话 打开或者关闭  会卡个一秒左右 才打开 动画是流畅的 反应慢 这个数据少的情况下 用着很舒服 

## 描述你考虑过的替代方案

有没有什么解决办法   这个功能是不错的  加上那个选地址 

## 其它

无

**Comment by szg2008** [comment]
这个是H5还是小程序环境呢，可以详细描述一下么

**Comment by iblilife** [comment]
小程序环境下所有的涉及popup都会慢，https://nutui.jd.com/#/zh-CN/guide/intro  往下拉一点点扫示例菊花码（微信小程序），只要涉及弹出层的都会有明显卡顿。@szg2008  @pupillxy

**Comment by yuanxin42** [comment]
我也遇到这个问题了，请问是如何解决的

**Comment by StavinLi** [comment]
怎么解决，沉了么
