### ISSUE TITLE
[bug]H5中 Form里有提交按钮，点击时页面刷新

### ISSUE THREAD

**Issue by bigpigOne** [jdf2e/nutui#1041]
## 问题描述

TaroH5中 Form里有提交按钮，点击提交按钮时页面刷新
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by shijunti19** [comment]
这个还没解决吗！！挺坑的

**Comment by richard1015** [comment]
nutui-taro 启动h5 模式吗 @shijunti19 @bigpigOne 

具体版本提供一下

**Comment by richard1015** [comment]
v3.1.18 已发布
