### ISSUE TITLE
[bug] nut-form-item作为子组件的时候无法触发表单校验

### ISSUE THREAD

**Issue by xyz13** [jdf2e/nutui#1042]
## 问题描述

将 nut-form-item 封装为独立的业务组件，然后在nut-form中使用，此种情况下无法触发设置的表单规则校验，比如：

比如文件：NameInput.vue

``` 
<template>
  <nut-form-item label="姓名" prop="name" required :rules="[{ required: true, message: '请填写姓名' }]">
    <input class="nut-input-text" v-model="model" placeholder="请输入姓名，blur 事件校验" type="text" />
  </nut-form-item>
</template>
``` 

在其他的表单中引用上述NameInput，如下：
```
<nut-form :model-value="formData1" ref="ruleForm">
  <NameInput v-model="formData1.name" />
  <nut-cell>
    <nut-button block type="primary" size="small" style="margin-right: 10px" @click="submit1">提交</nut-button>
  </nut-cell>
</nut-form>
```

当提交校验的时候设置的规则无法触发。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：v16.13.2
- **NutUI 版本**："@nutui/nutui": "^3.1.16"
- **Vue 版本**："vue": "^3.2.31",
- **引用方式**：  NPM

**Comment by richard1015** [comment]
由于内部查询节点机制为 form-item 和 form 必须为父子关系，抱歉您这种方式暂时无法支持

https://github.com/jdf2e/nutui/blob/next/src/packages/__VUE/form/common.ts#L37
