### ISSUE TITLE
[bug] 通过render函数构建的表单，校验规则只能触发一次

### ISSUE THREAD

**Issue by xyz13** [jdf2e/nutui#1045]
## 问题描述

通过render函数创建一个具有表单校验的组件，当触发第一次校验后，第二次校验失效。跟踪代码 checkRule 函数中
const { required, validator, regex, message } = rules.shift(); 这一句似乎会将表单的规则清空，导致无法第二次触发。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： "@nutui/nutui": "^3.1.16"
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
已修复 #1053

**Comment by richard1015** [comment]
v3.1.18 已发布
