### ISSUE TITLE
BUG 通过render创建Tabs会触发告警

### ISSUE THREAD

**Issue by xyz13** [jdf2e/nutui#1049]
## 问题描述

通过render创建Tabs会触发告警，如下代码样例：
![image](https://user-images.githubusercontent.com/4339952/156103357-da7bda22-e6d9-49f6-b18a-de8c50505489.png)

会触发告警：
![image](https://user-images.githubusercontent.com/4339952/156103402-0cddd8c8-612f-44e0-8c1d-fd262437bc94.png)

具体触发告警的代码是这个地方：
![image](https://user-images.githubusercontent.com/4339952/156103484-c8d5e56f-c7f7-4aac-ad04-c6968ffb6672.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：  "@nutui/nutui": "^3.1.16",
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by wubiandaxian** [comment]
@richard1015 不是在render里调用了slot，而是在setup里，就触发这个warning，微信小程序可复现

**Comment by richard1015** [comment]
请提供一个最小的复现仓库
