### ISSUE TITLE
nut-dialog里面放一个nut-textinput ，将页面下拉到底部，出现点击输入区域，后面的内容会被扩大的情况。

### ISSUE THREAD

**Issue by benbenyao** [jdf2e/nutui#105]

**Comment by Franslee** [comment]
请上代码

**Comment by benbenyao** [comment]
<nut-dialog 
            :visible="showDialog1"
            @close="showDialog1=false"
            >
            <nut-textinput 
                v-model="passVal"
                placeholder="请输入内容"
            />
        </nut-dialog>
就是输入法定位输入框之后，背景类似被手势放大了，不知道为啥。

**Comment by linrufeng** [comment]
没发现，放大 uc浏览器测试，不过用手势确实可以放大整个页面
