### ISSUE TITLE
[bug] use in taro, NutUI is not undefined

### ISSUE THREAD

**Issue by FeSeason** [jdf2e/nutui#1052]
## 问题描述

使用 taro-cli 初始化 vue + nutui 按照官方使用引入

https://nutui.jd.com/#/starttaro

![image](https://user-images.githubusercontent.com/12840843/156117267-644291a2-ddd3-4d48-adaa-24447e772a61.png)

使用全量引入组件时会报错

![image](https://user-images.githubusercontent.com/12840843/156117362-52cab21f-0eed-4a98-a6f9-3245b87f0145.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：Mac
- **Node 版本**：v12.22.8
- **NutUI 版本**： "@nutui/nutui-taro": "^3.1.8"
- **Vue 版本**："vue": "^3.0.0",
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
![image](https://user-images.githubusercontent.com/13060263/157156775-f4ab59fb-e1fe-4a98-8aea-e9f5797e50f6.png)


如果引入全量需要将此  按需加载配置删掉 ，不推荐全量引入，小程序对 build 包大小控制很严格

具体可参考 https://github.com/jdf2e/nutui-demo/tree/master/taro
