### ISSUE TITLE
[bug]表单校验不支持动态规则配置

### ISSUE THREAD

**Issue by Azraelj** [jdf2e/nutui#1053]
## 问题描述

form-item组件的rules属性配置为字面量时可以正常工作，配置为变量时只有第一次调用validate方法能正产校验，后续调用返回的valid字段固定为false
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
rules属性配置变量时也能正常进行校验

## 复现步骤，具体代码
官网示例将字面量修改为变量即可
如：
```
<nut-form-item :rules="rule"></nut-form-item>
<script setup>
    const rule=[{required: true, message:''}]
</script>
```

可能的原因：
checkRule方法中使用了Array.shift方法，修改了vnode的props

## 相关环境信息
- **操作系统**：macOS
- **Node 版本**：10.23.0
- **NutUI 版本**： 3.1.16
- **Vue 版本**：3.2.31
- **引用方式**：  NPM

**Comment by LiCeline** [comment]
`<nut-form-item
          prop="phone"
          required
          :rules="rules.phone"
        >
</nut-form-item>`
const [, result] = await errorCatch(ruleForm.value.validate())
const { valid, errors }: any = result
第一次一定会校验valid 会为false
但是到了第二次，valid就会true, 校验异常了

**Comment by richard1015** [comment]
nutui 3.1.16 ? nutui-taro 3.1.16   哪个版本

**Comment by richard1015** [comment]
v3.1.18 已发布
