### ISSUE TITLE
[question]nut-video如何获取当前播放时间和视频的总共时间呀?

### ISSUE THREAD

**Issue by jinyuanqing** [jdf2e/nutui#1055]
使用nutui的nut-video视频播放器组件,如何获取当前播放时间和视频的总共时间呀?

https://nutui.jd.com/#/video

**Comment by Drjingfubo** [comment]
下周发版以后 3.2.6会新增一个time方法，提供两个参数一个当前时间，一个总时间

**Comment by Drjingfubo** [comment]
3.2.6已发布
