### ISSUE TITLE
[suggest] Tabs 选项卡切换时，不同标签根据内容设置高度

### ISSUE THREAD

**Issue by emorywang** [jdf2e/nutui#1066]
## Tabs 选项卡切换时，不同标签根据内容设置高度

现在（3.1.17），Tabs选项卡切换时，所有标签内容（tabpane）的高度都一样，看起来都是根据高度最高的标签一致，这样某个标签内容比较少，就会很空很难看。

希望可以将Tabs选项卡改为根据每个tabpane的内容不同激活该标签时拥有适合本标签内容的高度。

它将使tabs使用起来更优雅

## 其它
目前其他框架ant-design, material-ui, element-ui等都是根据内容自适应高度的逻辑。

谢谢

**Comment by Ymm0008** [comment]
+1

**Comment by 490626721** [comment]
+1
