### ISSUE TITLE
在dialog的这个方法，我想覆盖掉，请问怎么做呢，我还不是很懂，比如在自己写的vue里面怎么覆盖？请指导哦。

### ISSUE THREAD

**Issue by benbenyao** [jdf2e/nutui#107]
var lockMaskScroll = function (bodyCls) {
  var scrollTop;
  return {
    afterOpen: function afterOpen() {
      scrollTop = document.scrollingElement.scrollTop || document.body.scrollTop;
      document.body.classList.add(bodyCls);
      document.body.style.top = -scrollTop + "px";
    },
    beforeClose: function beforeClose() {
      if (document.body.classList.contains(bodyCls)) {
        document.body.classList.remove(bodyCls);
        document.scrollingElement.scrollTop = scrollTop;
      }
    }
  };
}("dialog-open");

**Comment by Franslee** [comment]
lockBgScroll设为false即可关闭此功能
