### ISSUE TITLE
[急！]cdn引入方式 ,提示Uncaught TypeError: Cannot read properties of undefined (reading 'useRouter')

### ISSUE THREAD

**Issue by vebin** [jdf2e/nutui#1070]
使用CDN引入方式，根据指引不需要加路由，我手动也加了路由，为何会提示这个错误：
Uncaught TypeError: Cannot read properties of undefined (reading 'useRouter')

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@nutui/nutui@next/dist/style.css" />
    
    <script src="https://cdn.jsdelivr.net/npm/vue@@next"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-router@@next"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/@@nutui/nutui@@next/dist/nutui.umd.js"></script>
    
    
    var vueRouter = VueRouter.createRouter({
                // 4. 内部提供了 history 模式的实现。为了简单起见，我们在这里使用 hash 模式。
                history: VueRouter.createWebHashHistory(),
                routes: []
            });
            
            
            var appJson = {
                data() {
                    return {
                    }
                  }  
             };
    
    
    var app = Vue.createApp(appJson)
      app.use(vueRouter);
      app.use(nutui);
      app.mount("#el");

**Comment by vebin** [comment]
如果只是一个按钮组件，可以正常，但是用了<nut-form>组件，就是这个错误？
<nut-form :model-value="model" ref="nutForm">
        <nut-form-item label="名称" prop="serviceName" required :rules="[{ required: true, message: '请填写名称' }]">
            <input class="nut-input-text" v-model="model.serviceName" placeholder="请输入名称" type="text" />
        </nut-form-item>
</nut-form>

<nut-button type="default">默认按钮</nut-button>

**Comment by vebin** [comment]
测试到：如果只是一个按钮组件，可以正常，但是用了表单组件，就是这个错误？
<nut-form :model-value="model" ref="nutForm">
        <nut-form-item label="名称" prop="serviceName" required :rules="[{ required: true, message: '请填写名称' }]">
            <input class="nut-input-text" v-model="model.serviceName" placeholder="请输入名称" type="text" />
        </nut-form-item>
</nut-form>

**Comment by richard1015** [comment]
[归档.zip](https://github.com/jdf2e/nutui/files/8197573/default.zip)

**Comment by richard1015** [comment]
暂时先用 <script src="https://cdn.jsdelivr.net/npm/@nutui/nutui@beta/dist/nutui.umd.js"></script>

月底会正式发布

**Comment by richard1015** [comment]
v3.1.18 已发布
