### ISSUE TITLE
[suggest]searchBar组件增加disabled、focus属性及clickInput事件

### ISSUE THREAD

**Issue by liuhp** [jdf2e/nutui#1082]
## 你建议我们做什么？

现在searchBar组件没有disabled、focus属性及clickInput事件

如果你能为searchBar组件增加disabled、focus属性及clickInput事件

props:
disabled:是否禁用输入框
focus：获取焦点（自动获取焦点）
event:
clickInput：点击搜索区域时触发

它将可以完成如下场景：
点击搜索框时跳转到新的页面并自动聚焦弹起键盘；

## 其它

无

**Comment by visionsky1986** [comment]
同样有这个需求～

**Comment by Ymm0008** [comment]
props及event已经补全，将在下个版本发布。 @visionsky1986 @liuhp
