### ISSUE TITLE
[suggest] 发现unplugin-vue-components 没有nutui的resolvers

### ISSUE THREAD

**Issue by HZZformGD** [jdf2e/nutui#1085]
## 你建议我们做什么？

Ant Design Vue
Arco Design Vue
Element Plus
Element UI
Headless UI
IDux
Inkline
Naive UI
Prime Vue
Vant
VEUI
Varlet UI
View UI
Vuetify
VueUse Components
Quasar
TDesign

这些都有相对应的 resolvers  nutui 真的不考虑搞一下？

## 其它

无

**Comment by richard1015** [comment]
感谢反馈，我们近期加一下

**Comment by jiangz153202** [comment]
你好 请问在ViteComponents中 customComponentResolvers ,如何想要自定义写一个Resolvers 应该如何配置？

**Comment by richard1015** [comment]
暂时先采用https://github.com/vbenjs/vite-plugin-style-import

**Comment by languanghao** [comment]
@richard1015 如果用webpack咋办？这个只能按需加载样式吧

**Comment by richard1015** [comment]
> @richard1015 如果用webpack咋办？这个只能按需加载样式吧

bable 可以配置

https://nutui.jd.com/#/guide/start

**Comment by FarAwayShe** [comment]
> 暂时先采用https://github.com/vbenjs/vite-plugin-style-import

这个只能自动按需加载样式，组件还是要手动导入是吗
