### ISSUE TITLE
Elevator 电梯楼层组件，安装了最新版本3.1.17，在线平台调试有属性ref_for="true"，本地调试却没有，需要添加什么吗？

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#1086]
## 你想知道什么？
已安装最新版本3.1.17，在线上平台调试，查看电梯楼层组件有属性ref_for="true"，但是本地使用却没有，这是为什么呢，是不是需要增加什么？
![image](https://user-images.githubusercontent.com/40783535/157584354-95cca919-3ad0-4785-9350-1642902f32c2.png)
![image](https://user-images.githubusercontent.com/40783535/157584616-075500fb-97f8-4478-b283-1ccd54b48e2b.png)

**Comment by wangyongxiong** [comment]
是不是跟标签<script lang="ts">有关系

**Comment by szg2008** [comment]
有什么影响吗？

**Comment by wangyongxiong** [comment]
线上调试的点击电梯楼层有高亮颜色显示，本地的没有
