### ISSUE TITLE
Tabs  选项卡切换组件，点击tabs标题不触发click，点击nut-tabpane内容的东西(设置了点击事件)会触发click

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#1087]
## 你想知道什么？
click | 点击标签时触发 | {title,paneKey,disabled}
这个不是点击<nut-tabpane title="Tab 1">这里触发click事件的么，好像现在只可以在<nut-tabpane title="Tab 1"> Tab 1  </nut-tabpane>标签里面的内容点击会出发click

![QQ截图20220310131026](https://user-images.githubusercontent.com/40783535/157593999-361efd19-8a4c-4e47-b06d-4403842a37c5.png)

![image](https://user-images.githubusercontent.com/40783535/157592314-fe9242de-eda8-4371-a2e0-aa32979fecf8.png)
![image](https://user-images.githubusercontent.com/40783535/157592428-bb5b8fd5-f1c5-4859-a67f-5fe6dde9200b.png)

**Comment by richard1015** [comment]
``` html
nut-tabs  @click="xxxxx"

@click 放到  tabs组件上
```

**Comment by wangyongxiong** [comment]
能否在 nut-tabpane 加上点击事件 click，点击不同的选项卡去加载不同的内容

**Comment by richard1015** [comment]
nut-tabs  @click 目前已经将你 选中项的 {title,paneKey,disabled}  返回了 我理解的你通过panekey完全可以想去加载指定的内容啊， 你那种是什么场景呢

**Comment by wangyongxiong** [comment]
感谢，一开始我没测试到这个回调参数
