### ISSUE TITLE
[bug] 文档有问题： 快速上手\CDN 安装使用示例\引入NutUI组件库  的js 不能运行。

### ISSUE THREAD

**Issue by wy1037** [jdf2e/nutui#1089]
快速上手\CDN 安装使用示例\引入NutUI组件库  的js 不能运行。
引入 nutui@beta 组件库 有效果，
按文档 引入 nutui@next 组件库无效果，

    	
    <script src="https://cdn.jsdelivr.net/npm/@nutui/**nutui@beta**/dist/nutui.umd.js"></script>
    
    
 
[vue3-nutui@beta有效果.txt](https://github.com/jdf2e/nutui/files/8222042/vue3.txt)
[vue3-nutui@next无效果.txt](https://github.com/jdf2e/nutui/files/8222060/vue3-nutui%40next.txt)

**Comment by wy1037** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@nutui/nutui/dist/style.css"/>
    
    <script src="https://cdn.jsdelivr.net/npm/vue@next"></script>     
    	
    <script src="https://cdn.jsdelivr.net/npm/@nutui/**nutui@beta**/dist/nutui.umd.js"></script>
    
    
  </head>
  <body>
    <div id="app">
	 <nut-form id="compid">
            <nut-form-item label="姓名">
                <input class="nut-input-text" placeholder="请输入姓名" type="text" />
            </nut-form-item>
            <nut-form-item label="年龄">
                <input class="nut-input-text" placeholder="请输入年龄" type="text" />
            </nut-form-item>
            <nut-form-item label="联系电话">
                <input class="nut-input-text" placeholder="请输入联系电话" type="text" />
            </nut-form-item>
            <nut-form-item label="地址">
                <input class="nut-input-text" placeholder="请输入地址" type="text" />
            </nut-form-item>
            <nut-form-item label="备注">
                <nut-textarea placeholder="请输入备注" type="text" />
            </nut-form-item>
        </nut-form>     
    </div>
    <script>
      // 在 #app 标签下渲染一个按钮组件
      const app = Vue.createApp({
        data() {
          return {
            
          };
        },
        methods: {
          
        },
      });
    
      app.use(nutui);
      // 调用函数组件，弹出一个 Toast
      // nutui.Toast("NutUI 3.0");
      app.mount("#app");
    </script>
  </body>
</html>

**Comment by richard1015** [comment]
感谢反馈 ：）

beta 前两天刚修复了cdn 中 router的报错bug，暂时可以先使用 beta， 此版本 月底会发布

**Comment by wy1037** [comment]
[Bug]  &nbsp;beta&nbsp;
文档：Menu&nbsp;&nbsp;菜单组件\基础用法
<template&gt;   <nut-menu&gt;     <nut-menu-item v-model="state.value1" :options="state.options1" /&gt;     <nut-menu-item v-model="state.value2" @change="handleChange" :options="state.options2" /&gt;   </nut-menu&gt; </template&gt;


只能显示 state.options1   state.options2 的显示不了。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月11日(星期五) 下午3:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdf2e/nutui] [bug] 文档有问题： 快速上手\CDN 安装使用示例\引入NutUI组件库  的js 不能运行。 (Issue #1089)





 
感谢反馈 ：）
 
beta 前两天刚修复了cdn 中 router的报错bug，暂时可以先使用 beta， 此版本 月底会发布
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by richard1015** [comment]
> 

menu cdn 辛苦提供一下复现代码

**Comment by richard1015** [comment]
v3.1.18 已发布

**Comment by wy1037** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月25日(星期五) 下午4:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdf2e/nutui] [bug] 文档有问题： 快速上手\CDN 安装使用示例\引入NutUI组件库  的js 不能运行。 (Issue #1089)





 
v3.1.18 已发布

**Comment by wy1037** [comment]
文档的 cdn 文件：


***@***.******@***.***/dist/nutui.umd.js


仍然是&nbsp;&nbsp;v3.1.16
