### ISSUE TITLE
时间插件移动端 没有选择秒的选项

### ISSUE THREAD

**Issue by yyccQQu** [jdf2e/nutui#109]
![image](https://user-images.githubusercontent.com/32674176/58525876-7f0d6400-81f7-11e9-85a9-210daa654373.png)

希望加个带秒的选项
类似 滴滴的UI 他们有了，但是样子有点丑，希望大佬加一个选秒的事例
https://didi.github.io/cube-ui/#/zh-CN/docs/date-picker

**Comment by Franslee** [comment]
感谢建议，我们考虑一下
