### ISSUE TITLE
[bug] cell组件icon和title、sub-title一起使用会影响title、sub-title的样式

### ISSUE THREAD

**Issue by beijibeijing** [jdf2e/nutui#1092]
## 问题描述
cell只用title和sub-title，不用icon时，只有.nut-cell__title起作用
```
    -ms-flex-direction: column;
    flex-direction: column;
```

cell只用title、sub-title、icon同时使用时多了一个nut-cell__title.icon
```
    -ms-flex-direction: row;
    flex-direction: row;
```
而nut-cell__title中属性被覆盖掉
    ~~-ms-flex-direction: column;~~
    ~~flex-direction: column;~~

## 预期的行为和实际行为
期望cell里title、sub-title、icon同时使用时，title和sub-title还是上下两行，实际上成一行了。

## 相关环境信息
- **Taro 版本**： @tarojs/cli@npm:3.4.1
- **NutUI 版本**： @nutui/nutui-taro@npm:3.1.16
- **Vue 版本**：vue@npm:3.2.29

**Comment by hhch** [comment]
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/21006441/158045225-25145613-577c-4a23-8d07-aa418dfa7bd2.png">
3.1.17版我也遇到了

**Comment by richard1015** [comment]
v3.1.18 已发布
