### ISSUE TITLE
[suggest] 希望searchbar组件增加类似placeholderStyle属性，可以自定义placeholder样式

### ISSUE THREAD

**Issue by fengchunsun2016** [jdf2e/nutui#1094]
## 你建议我们做什么？
希望searchbar组件增加类似placeholderStyle属性，可以自定义placeholder样式

现在...

searchbar不支持自定义输入框的placeholder字体的颜色和大小

如果你能..
支持自定义输入框的placeholder字体的颜色和大小

它将使...
我会更加的爱你们

## 其它
么么哒
无

**Comment by fengchunsun2016** [comment]
已解决

**Comment by ShawnZeng** [comment]
这个是怎么解决的，placeholder-class不好使啊

**Comment by ShawnZeng** [comment]
知道了，class是固定的 textarea-placeholder
