### ISSUE TITLE
‘Elevator 电梯楼层’组件，关于点击高亮显示

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#1095]
![image](https://user-images.githubusercontent.com/40783535/158103181-32e19380-9285-413b-b18a-34f4fe6b6612.png)
复制代码测试，点击后没有高亮颜色显示
![image](https://user-images.githubusercontent.com/40783535/158103240-fa960704-c4e4-4be7-82c4-156fab1b8f1c.png)

在线平台调试，查看源码显示有附加class，但是复制代码测试并没有显示（3.1.17版本，已更新）
![image](https://user-images.githubusercontent.com/40783535/158103444-3e859a13-85c2-43d9-beea-4909cb94f4d4.png)
本地的
![image](https://user-images.githubusercontent.com/40783535/158103505-53df90b7-9828-423c-9f00-111f7dc89a8a.png)

**Comment by szg2008** [comment]
安装最新的v3.1.17了吗

**Comment by wangyongxiong** [comment]
![image](https://user-images.githubusercontent.com/40783535/158141581-c7bfa17c-220b-4156-b3bb-1e144b4aeb22.png)
我是3月4号更新到3.1.17版本的

**Comment by wangyongxiong** [comment]
![image](https://user-images.githubusercontent.com/40783535/158144728-85875fa4-d8e7-45df-84b5-a71ff424c7f8.png)
我刚刚重新安装了一下（npm i @nutui/nutui@next），这样算是安装成功了么

**Comment by szg2008** [comment]
npm i @nutui/nutui,这样安装，先把lock文件删一下，然后看一下安装之后的版本是否正确

**Comment by wangyongxiong** [comment]
我的是vue3项目，重新装，好像还是只能安装3.1.16版本（npm i @nutui/nutui@next）
![image](https://user-images.githubusercontent.com/40783535/158331898-2a8ec4f4-9b7c-491e-8f1e-27611d1075b3.png)

**Comment by szg2008** [comment]
lock文件和node_modules都删一下，重新安装
