### ISSUE TITLE
感觉过场动画稍微有点卡顿

### ISSUE THREAD

**Issue by syhyz1990** [jdf2e/nutui#11]
感觉过场动画稍微有点卡顿, 不怎么流畅

**Comment by Franslee** [comment]
@syhyz1990 您是说DEMO页面的转场动画吗？

**Comment by syhyz1990** [comment]
@Franslee 是的呢 , 感觉不怎么浏览,不知道是动画问题还是组件本身卡顿

**Comment by Franslee** [comment]
> @Franslee 是的呢 , 感觉不怎么浏览,不知道是动画问题还是组件本身卡顿

DEMO页面的转场动画是用的第三方插件，NutUI中目前没有转场动画插件。方便告诉我们你用的哪款手机、哪个浏览器浏览的吗？我们后续优化一下。

**Comment by syhyz1990** [comment]
@Franslee 小米8手机 , 微信自带的浏览器 , 夸克浏览器都卡

**Comment by Franslee** [comment]
收到，感谢反馈
