### ISSUE TITLE
noticebar本地最新版本与官方最新版本有差异

### ISSUE THREAD

**Issue by LuEdision** [jdf2e/nutui#1104]
## 问题描述
开发中对比了一下本地与官网的noticebar的渲染，样式上有些差异，或者说这个组件在动画设置上不一样。
![本地下载最新的版本](https://user-images.githubusercontent.com/63531046/158731693-5c04050e-fde5-4646-ab6f-8497dc91f66a.png)
![官方最新版本](https://user-images.githubusercontent.com/63531046/158731705-333e435b-d33e-47f8-996c-6a6cbe38af7b.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：win11 x64
- **Node 版本**：14.x.x以上
- **NutUI 版本**： @nutui/nutui@3.1.17
- **Vue 版本**：vue3.x.x
- **引用方式**：  yarn or npm

**Comment by richard1015** [comment]
该组件近期刚刚优化，3.1.18  3月25日发布
