### ISSUE TITLE
关于 Tabbar的 问题

### ISSUE THREAD

**Issue by Hiliyanbo** [jdf2e/nutui#111]
当 Tabbar 的 tab-switch列表没有href参数的时候，切换标签会报错：
`Uncaught TypeError: Cannot read property 'match' of null`

请问有解决的方法吗？

**Comment by Franslee** [comment]
无法复现，请上代码。

**Comment by Hiliyanbo** [comment]
请参考你们官方的例子：https://nutui.jd.com/demo.html#/TabBar
![image](https://user-images.githubusercontent.com/27544795/59734938-080f3c80-9286-11e9-9efa-f80a9480bf80.png)
点击切换都会导致如下错误，
![image](https://user-images.githubusercontent.com/27544795/59734958-18bfb280-9286-11e9-9d5c-f38703952827.png)
难道是我浏览器的原因？ Chrome版本 75.0

**Comment by Hiliyanbo** [comment]
实际上可以设置 href:'javascript:;' 可以解决问题，
但是我认为在我使用@tab-switch方法时又必须加上href，这行代码是多余的。

**Comment by Franslee** [comment]
我们使用Chrome 75也不能复现，你有修改代码吗？

**Comment by Hiliyanbo** [comment]
可能是我安装的某个拓展程序导致的，在我打开不使用任何插件的隐身窗口的时候没有发现这个问题。
感谢~
