### ISSUE TITLE
[question]请问nutui控件如何切换成英文版,是否是所有的控件都支持英文版

### ISSUE THREAD

**Issue by sibada228** [jdf2e/nutui#1111]
import enUS from '@nutui/nutui/dist/locales/lang/en-US'
createApp(App).use(store).use(router).use(NutUI, {
  locale: 'en-US',
  lang: enUS
}).mount('#app')

命令：
npm install --save @nutui/nutui/dist/locales/lang/en-US

找不到对应的语言包

帮忙看下

**Comment by richard1015** [comment]
3.0 当前所有组件不支持国际化， 国际化计划在Q2Q3完成

**Comment by sibada228** [comment]
感谢回信,国际化哪个版本支持？？

**Comment by richard1015** [comment]
目前nutui 2.x 版本是支持国际化的 https://nutui.jd.com/2x/#/index
