### ISSUE TITLE
[bug] picker显示时样式错位，列表数据显示重叠

### ISSUE THREAD

**Issue by caoruiy** [jdf2e/nutui#1114]
## 问题描述
在预览官方的NutUI小程序Picker功能时，进入Picker页面，选择“多列样式”，弹出星期选择Picker，样式显示重叠。
在本机项目中，同样出现该现象。
![24d4ed71fd840cd656e6f21f9583ad0](https://user-images.githubusercontent.com/13867478/159126135-b29531e6-8933-459b-9d50-97669a5901e6.jpg)

产生该现象的原因是在滚动列表数据时，nut-picker-list-panel类每滚动一次设置的`transform: translate3d`偏移高度为36px，和`nut-picker-content`类设置的高度39px不一致，导致滚动时偏移越来越大
![微信图片_20220319232706](https://user-images.githubusercontent.com/13867478/159127305-72e4f2b0-e8b4-4edb-aa20-e501ab5a6584.png)

## 最小可复现仓库
官方小程序，无需创建DEMO

## 预期的行为和实际行为
显示正常

## 复现步骤，具体代码
1. 打开小程序NutUI
2. 选择Picker cell
3. 点击"多列样式" cell

本机项目出现相同问题

## 相关环境信息
- **操作系统**：iPhone 11 15.0.1
- **Node 版本**：14.16.0
- **NutUI 版本**： @nutui/nutui-taro@3.1.17
- **Vue 版本**：3.2.26
- **引用方式**： NPM

**Comment by yangxiaolu1993** [comment]
在 nutui-taro@3.1.18中已解决
