### ISSUE TITLE
[bug] nut-calendar 在窗口打开的情况下滑动日历会报以下警告

### ISSUE THREAD

**Issue by CoderBCat** [jdf2e/nutui#1116]
runtime-core.esm-bundler.js:38 [Vue warn]: Failed to resolve component: scroll-view
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <NutCalendarItem key=0 ref="calendarRef" type="range"  ... > 
  at <BaseTransition onAfterEnter=fn<onOpened> onAfterLeave=fn<onClosed> appear=false  ... > 
  at <Transition name="popup-slide-bottom" onAfterEnter=fn<onOpened> onAfterLeave=fn<onClosed> > 
  at <NutPopup key=0 visible=true onUpdate:visible=fn  ... > 
  at <NutCalendar title="选择日期范围" visible=true type="range"  ... > 
  at <Finance tid="pages/index/Finance?$taroTimestamp=1647783615993" > 
  at <Anonymous key="pages/index/Finance?$taroTimestamp=1647783615993" > 
  at <App>

## 相关环境信息
**操作系统**：微信小程序
**NutUI 版本**："@nutui/nutui-taro": "^3.1.18-bate.0",
**Vue 版本**："vue": "^3.2.31"
**引用方式**：  NPM

**Comment by lkjh3214** [comment]
请问是在转换为微信小程序还是h5时出现的报错

**Comment by maiguangyang** [comment]
3.1.20 也有这个情况

**Comment by harjim** [comment]
3.1.22 有这个问题，并且 cv 官方示例连关闭都无法。taro 版本 3.4.12
