### ISSUE TITLE
‘Tabs 选项卡切换’组件，在数量多的情况下，能否点击后自动居中

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#1127]
## 你建议我们做什么？
在“Tabs 选项卡切换”组件中，在数量多的情况下，点击后的tab自动居中
![image](https://user-images.githubusercontent.com/40783535/159471298-bb60d7e3-8f4e-4ae9-9ab4-6ac0c8ed615a.png)

**Comment by tyh1117** [comment]
同样遇到了这个问题，请问大佬解决了吗？

**Comment by richard1015** [comment]
v3.3.2
