### ISSUE TITLE
[bug]Tabs主题定制的自定义变量$tabs-titles-item-active-color不生效

### ISSUE THREAD

**Issue by liuhp** [jdf2e/nutui#1135]
## 问题描述

Tabs主题定制中同时自定义$tabs-titles-item-color和$tabs-titles-item-active-color时，$tabs-titles-item-color定义的变量生效而$tabs-titles-item-active-color没有生效。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
在工程样式文件中自定义如下变量
```
$tabs-titles-item-color: rgba(#000e1b, 0.45);
$tabs-titles-item-active-color: rgba(#000e1b, 0.85);
```

启动工程会发现$tabs-titles-item-color的颜色是自己设置的，而$tabs-titles-item-active-color依然是nuiUI默认的颜色；

## 相关环境信息
- **操作系统**：macos
- **Node 版本**：v12.13.1
- **NutUI 版本**： @nutui/nutui-taro": "^3.1.17"
- **Vue 版本**："vue": "^3.2.1"
- **Taro版本**: "@tarojs/taro": "3.4.1",
- **引用方式**：   NPM

**Comment by richard1015** [comment]
由于变量是上周刚刚提取，本周五发版后 更新3.1.18就正常了

**Comment by richard1015** [comment]
v3.1.18 已发布
