### ISSUE TITLE
[suggest] 不要对参数执行 reactive 操作，否则会丢失掉用户的代理属性

### ISSUE THREAD

**Issue by moonRider** [jdf2e/nutui#1140]
## Addrees 组件转换用户参数时丢失了用户的代理属性

address 组件中的 regionList 在定义时使用了 reactive 函数（vue 会深度遍历里面的属性，更改为 proxy）。
如果用户提供的参数比如 props.province 本身就已经是 proxy 时，且该 proxy 内定义了一个计算属性 `id: (target) => target.row.uuid`，reactive 遍历时无法遍历到 id 这个属性 ，因此 reactive 函数执行后，regionList 中的 province 数据将不能访问到 id。 从而导致用户传入的参数和选择结果的数据在访问时会出现差异。

如果你能用 shallowReactive 去构造 regionList

它将保证组件输入的数据和选择结果输出的数据的一致性

## 其它
现有场景
```js
const originalProvinces = [{
   row: {
     uuid: '1'
     name: '第一级',
   },
}]

function parseNode(node) {
  return new Proxy(node, {
    get(target, prop) {
      if (prop === 'id') return target.row.uuid
      if (prop === 'name') return target.row.name
      return target[prop]
    }
  })
}

function onClose({ data }) {
  data.province.id // undefined
}

return () => {
  return h(NutAddress, {
    province: originalProvinces.map(parseNode),
    onClose,
    ...
  })
}
```

**Comment by yangxiaolu1993** [comment]
很抱歉这么久才回复你提出的建议，根据描述进行了复现，首先，reactive 遍历时是可以访问到 id 的，并且 shallowReactive 属于非迭代递归，数据更新时，会影响到页面不渲染。不过，你说的场景我们近期也会考虑兼容。

再次感谢您对 NutUI 的支持！

**Comment by moonRider** [comment]
感谢回答，确实不是 reactive 遍历导致的问题。例子中是用户自己构造 proxy 对象时失去了 vue 的响应性导致的。
