### ISSUE TITLE
[suggest] 提供一个ConfigProvider 全局配置组件定制主题和深色模式

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui#1150]
## 你建议我们做什么？
组件定制主题

现在主题定制还是不太灵活，只能全局修改，并且如果是动态主题的话不太好处理。
能否像vant的[ConfigProvider](https://vant-contrib.gitee.io/vant/v4/#/zh-CN/config-provider)组件一样提供局部定制主题的功能。
增加深色以及动态主题

## 其它

无

**Comment by richard1015** [comment]
v3.1.22 已发布

**Comment by richard1015** [comment]
动态主题后期会添加

**Comment by shichaohui** [comment]
@richard1015 请问 `Taro` 中想要全局配置 `ConfigProvider` 怎么搞？只能在每个页面都加上 `<nut-config-provider>...</nut-config-provider>` 吗？

**Comment by chf007** [comment]
> @richard1015 请问 `Taro` 中想要全局配置 `ConfigProvider` 怎么搞？只能在每个页面都加上 `<nut-config-provider>...</nut-config-provider>` 吗？

同问
