### ISSUE TITLE
“Elevator 电梯楼层”组件，有这样一种情况，有bug

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#1151]
## 你想知道什么？
“Elevator 电梯楼层”组件，有这样一种情况，在城市列表中，有热门城市一项；
一个城市的id固定，但是它又是热门城市，造成点击后会出现两个高亮色。

![image](https://user-images.githubusercontent.com/40783535/160117032-8be7b4a1-d3f7-485d-a6af-63c3cd24424f.png)

**Comment by szg2008** [comment]
这个建议重新定义一下热门城市的id来处理吧

**Comment by wangyongxiong** [comment]
一个城市不可能去定义两个id的。不能通过key和id去判断处理么
