### ISSUE TITLE
[question]NutUI示例中，微信端音频和视频页无法打开

### ISSUE THREAD

**Issue by 2508779859** [jdf2e/nutui#1157]
你好，NutUI示例中，微信小程序，音频播放器和视频播放器 跳转页面无法打开，为什么
![Snipaste_2022-03-29_18-57-25](https://user-images.githubusercontent.com/76721653/160596814-48bb8b5e-9d63-46b4-9c03-fe429cc41dd9.png)
？

**Comment by yurenzhen** [comment]
是的, 我今天也发现了, 小程序里面的音频和视频播放器都用不了,  公众号里面的是好的
