### ISSUE TITLE
uploader组件的接口请求方式，method设置为get不生效，请求方式还是post

### ISSUE THREAD

**Issue by Xiaoyuner** [jdf2e/nutui#1160]
## 问题描述
uploader组件的接口请求方式，method设置为get不生效，请求方式还是post

## 预期的行为和实际行为
预期结果： 接口请求 request method 为 get

实际结果：
![image](https://user-images.githubusercontent.com/21262689/160775832-a1fb9fd6-273d-4d9d-9ae4-a5080962f228.png)

`         <nut-uploader
                v-model:file-list="uplodFileList"
                method="get"
                :url="baseUrl + '/xxxx/query/v1'"
                :headers="getRequestHeader()"
                multiple
                :maximize="1024 * 1024 * 10"
                maximum="4"
                name="file"
                upload-icon="uploader"
                upload-icon-size="20px"
                :class="{ 'uploader--disabled': !recheckEditable }"
                @file-item-click="clickPicture"
                @success="uploadSuccess"
                @oversize="onOversize"
              />`

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@3.1.18  
- **Vue 版本**：vue 3.0
- **引用方式**：  NPM

**Comment by richard1015** [comment]
经测试，发现无误  
测试代码  https://github.com/jdf2e/nutui-demo/commit/1fe49b778c281dd50bc6d45155ed9b91956dbb0b
