### ISSUE TITLE
[bug]@nutui/nutui-taro h5 Elevator组件无法解析scroll-view组件

### ISSUE THREAD

**Issue by Sun79** [jdf2e/nutui#1164]
## 问题描述

Elevator组件打包后将scroll-view标签编译为下面的代码
![image](https://user-images.githubusercontent.com/17243584/161003413-ebbad2ee-9747-4b68-974f-21a728ae9258.png)
而@tarojs/components在h5端将scroll-view注册为名为taro-scroll-view的组件，导致在h5端无法找到scroll-view组件。
![image](https://user-images.githubusercontent.com/17243584/161003997-39f9fd3e-cdcc-41d1-a195-75b58f0adf64.png)

## 相关环境信息
- **操作系统**：Windows 10 专业版 21H1
- **Node 版本**：v16.13.1
- **NutUI 版本**： @nutui/nutui-taro@3.1.18
- **Vue 版本**：v3.2.31
- **引用方式**：  NPM

**Comment by richard1015** [comment]
v3.2.1 已修复 已发布
