### ISSUE TITLE
[question]nutui-taro有用tsx重构或者支持ts类型的计划么？

### ISSUE THREAD

**Issue by wubiandaxian** [jdf2e/nutui#1166]
## 你想知道什么？

nutui-taro有用tsx重构或者支持ts类型的计划么？
现在vue3项目大多都基于ts开发了，目前组件库没有类型，开发的时候比较痛苦。
并且一些组件还是比较缺乏solts的支持，像Elevator这种组件，开发者不能自定义展示内容，使用起来感觉比较受限。

## 其它
使用过程中，总感觉还有很重的vue2的影子在里面，感觉怪怪的……

**Comment by szg2008** [comment]
目前已经支持ts类型提示
