### ISSUE TITLE
[bug] 按需引入nutui，组件渲染一个神奇的现象

### ISSUE THREAD

**Issue by SpringHgui** [jdf2e/nutui#1169]
## 问题描述
nutui组件不渲染

## 最小可复现仓库
https://github.com/SpringHgui/nutui-bug
 

### 1.按需引入方式配置，执行`dev:weapp`，组件不渲染，效果如下
![image](https://user-images.githubusercontent.com/22363718/161245407-f7df29ef-8ad5-4a94-a684-6b15be1cd22f.png)

### 2.仅仅在页面增加一个button组件，nutui的按钮居然显示了，注释原生
![image](https://user-images.githubusercontent.com/22363718/161245764-96402bb4-2656-418e-a994-b22e7a99249c.png)

**Comment by szg2008** [comment]
在 `config/index.js`中添加插件 `plugins: ['taro-plugin-pinia', '@tarojs/plugin-html']`,然后重新启动就ok了。
