### ISSUE TITLE
input组件怎么使用插槽，插入发送验证码按钮的？

### ISSUE THREAD

**Issue by wbsss** [jdf2e/nutui#1170]
## 你想知道什么？

你好，我想知道这个项目是否可以...

## 描述你考虑过的替代方案

我想...

## 其它

无

**Comment by ailululu** [comment]
<nut-input v-model="state.buttonVal" clearable center label="短信验证码" placeholder="请输入短信验证码">
      <template #button>
        <nut-button size="small" type="primary"> 发送验证码 </nut-button>
      </template>
</nut-input>

**Comment by ailululu** [comment]
`<nut-input v-model="state.buttonVal" clearable center label="短信验证码" placeholder="请输入短信验证码">
      <template #button>
        <nut-button size="small" type="primary"> 发送验证码 </nut-button>
      </template>
    </nut-input>
`

**Comment by zhengxiongzhao** [comment]
文档不匹配，可以考虑以下方式

```vue
<div class="nut-cell nut-cell nut-form-item line">
     <div class="nut-cell__title nut-form-item__label required">短信验证码</div>
     <input class="nut-input-text" placeholder="请输入短信验证码" type="text"/>
     <nut-button size="small" type="primary"> 发送验证码</nut-button>
</div>
```
