### ISSUE TITLE
[bug]nutui-taro中List组件在H5下渲染出错

### ISSUE THREAD

**Issue by wubiandaxian** [jdf2e/nutui#1171]
## 问题描述

nutui-taro中List组件在H5下渲染出错，H5中滚动事件没有e.detail

## 最小可复现仓库
无

## 预期的行为和实际行为
List组件正常渲染

## 复现步骤，具体代码
组件事件源码：
```js
const handleScrollEvent = async (e) => {
      const scrollTop = e.detail.scrollTop;
      state.start = Math.floor(scrollTop / props.height);
      if (end.value > state.list.length) {
        emit("scroll");
      }
      state.startOffset = scrollTop - scrollTop % props.height;
    };
```

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@3.1.18 
- **Vue 版本**：3.2.31
- **引用方式**：   NPM

**Comment by wubiandaxian** [comment]
另外，在微信小程序里会warn： [Vue warn]: Failed to resolve component: scroll-view。
tsx开发时，如下代码，每次滚动，打印的index一直是0,1,2,3,4这种，并不是数组数据的真实索引，那我如何知道列表已经滚动到了底部？
``` TS
      <List
            height={120}
            listData={this.serchList}
            onScroll={() => {
              console.log('这里不知道为什么也不会执行')
            }}
            v-slots={{
              default: ({ item, index }: { item: any; index: number }) => {
                console.log(index)  // 这里输出的并不是真实索引
                return (
                  <div {item.name}</div>
                )
              },
            }}
          />
```

**Comment by Hsinry** [comment]
在微信小程序中使用InfiniteLoading组件，也出现了warn： [Vue warn]: Failed to resolve component: scroll-view。

**Comment by szg2008** [comment]
onScroll 事件是在滚动到底部的时候才会触发。
[Vue warn]: Failed to resolve component: scroll-view在小程序中应该不会报这个错误。在H5中存在这个问题，目前正在解决

**Comment by wubiandaxian** [comment]
> onScroll 事件是在滚动到底部的时候才会触发。 [Vue warn]: Failed to resolve component: scroll-view在小程序中应该不会报这个错误。在H5中存在这个问题，目前正在解决

H5使用的时候，需要手动注册下ScrollView组件： app.component('scroll-view', ScrollView)。
onScroll 事件名，迷惑性很强，文档上注释，迷惑性也很强

**Comment by yycmd** [comment]
> > onScroll 事件是在滚动到底部的时候才会触发。 [Vue warn]: Failed to resolve component: scroll-view在小程序中应该不会报这个错误。在H5中存在这个问题，目前正在解决
> 
> H5使用的时候，需要手动注册下ScrollView组件： app.component('scroll-view', ScrollView)。 onScroll 事件名，迷惑性很强，文档上注释，迷惑性也很强

ScrollView 组件可以通过 import { ScrollView } from "@tarojs/components";  导出
导出之后，注册 ScrollView 组件，List 组件依然渲染有问题

**Comment by wubiandaxian** [comment]
> > > onScroll 事件是在滚动到底部的时候才会触发。 [Vue warn]: Failed to resolve component: scroll-view在小程序中应该不会报这个错误。在H5中存在这个问题，目前正在解决
> > 
> > 
> > H5使用的时候，需要手动注册下ScrollView组件： app.component('scroll-view', ScrollView)。 onScroll 事件名，迷惑性很强，文档上注释，迷惑性也很强
> 
> ScrollView 这个组件怎么注册呢？我通过 import { ScrollView } from "@nutui/nutui-taro"; 也没法导出这个组件

import { ScrollView } from '@tarojs/components'

**Comment by yycmd** [comment]
> > > > onScroll 事件是在滚动到底部的时候才会触发。 [Vue warn]: Failed to resolve component: scroll-view在小程序中应该不会报这个错误。在H5中存在这个问题，目前正在解决
> > > 
> > > 
> > > H5使用的时候，需要手动注册下ScrollView组件： app.component('scroll-view', ScrollView)。 onScroll 事件名，迷惑性很强，文档上注释，迷惑性也很强
> > 
> > 
> > ScrollView 这个组件怎么注册呢？我通过 import { ScrollView } from "@nutui/nutui-taro"; 也没法导出这个组件
> 
> import { ScrollView } from '@tarojs/components'

我刚刚，按提示已经发现是这个导出 ScrollView  组件，但是注册之后，依然有这个渲染问题

**Comment by Diamondjcx** [comment]
有人解决这个问题吗？
