### ISSUE TITLE
[question]vue3 taro weapp picker组件如何设置让背景不滚动？

### ISSUE THREAD

**Issue by eriklu** [jdf2e/nutui#1172]
## 你想知道什么？

你好，我想知道这个项目是否可以...
在vue3 taro中开发微信小程序，使用picker或datepicker 滑动屏幕时，背景没有锁定。

"name": "@nutui/nutui-taro",
  "version": "3.1.18",

## 描述你考虑过的替代方案
已设置lock-scroll和@touchmove.prevent
但在微信小程序下滑动选择日期时，背景仍滑动。ios15
```
  <nut-datepicker 
  @touchmove.prevent  //网络上的建议
    v-model="birthday"
    title="选择生日"
    v-model:visible="showBirthSelector"
    :min-date="new Date(1920, 0, 1)"
    :max-date="new Date(2000, 11, 31)"
    :is-show-chinese="true"
    @confirm="confirmBirth"
    :lock-scroll=true  //Popup中有该选项
  ></nut-datepicker>
```

我想...

## 其它

无

**Comment by eriklu** [comment]
新版本可以给nut-datepicker设置catchMove属性实现。

**Comment by eriklu** [comment]
新版本可以给nut-datepicker设置catchMove属性实现。

**Comment by 307god** [comment]
picker 如何防止背景滑动呢？

**Comment by emorywang** [comment]
我也遇到了同样的问题，使用picker时，滑动picker内的选项，背景也会一起滚动，不知道该如何解决

**Comment by eriklu** [comment]
```
  <nut-datepicker
    type="time"
    title="选择时间"
    v-model="selectTime"
    :minute-step="5"
    v-model:visible="showTimeSelector"
    :is-show-chinese="true"
    @confirm="confirmTime"
    :catchMove="true"
  ></nut-datepicker>  
```


:catchMove="true"  我在微信小程序里这样设置的。picker没有测试。

**Comment by SilentFlute** [comment]
> ```
>   <nut-datepicker
>     type="time"
>     title="选择时间"
>     v-model="selectTime"
>     :minute-step="5"
>     v-model:visible="showTimeSelector"
>     :is-show-chinese="true"
>     @confirm="confirmTime"
>     :catchMove="true"
>   ></nut-datepicker>  
> ```
> 
> :catchMove="true" 我在微信小程序里这样设置的。picker没有测试。

666, 我还想着像网页那样将最外层的`page`节点的`overflow`设置为`hidden`呢, 搜了半天没找到方法, 然后转念一想, 不如来`issue`里面看看, 结果就找到了, 感谢感谢~
不过我有一个疑问, 就是`nutui 3.x` `DatePicker`的文档里面并没有这个`catchMove`, 你是怎么发现这个`API`的啊?
