### ISSUE TITLE
[bug] Taro3微信小程序InfiniteLoading组件出现告警

### ISSUE THREAD

**Issue by Hsinry** [jdf2e/nutui#1177]
## 问题描述

Taro开发微信小程序时，使用InfiniteLoading组件时出现告警：`[Vue warn]: Failed to resolve component: scroll-view`，使用小程序组件库示例Demo发现存在同样的问题。
```
[Vue warn]: Failed to resolve component: scroll-view
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <NutInfiniteloading pull-icon="JD" load-txt="loading" load-more-txt="没有啦～"  ... > 
  at <NutCell> 
  at <Index tid="feedback/pages/infiniteloading/index?$taroTimestamp=1649138523708" > 
  at <Anonymous key="feedback/pages/infiniteloading/index?$taroTimestamp=1649138523708" > 
  at <App>
```
## 最小可复现仓库
[组件库示例Demo](https://github.com/jdf2e/nutui-demo/tree/master/taro)

## 相关环境信息
- **操作系统**：Windows10专业版
- **Node 版本**：16.9.0
- **NutUI 版本**： @nutui/nutui-taro@3.1.18
- **Vue 版本**：3.2.31
- **引用方式**：  NPM

**Comment by suozhao** [comment]
我记得这个警告会在3.1.18修复啊，怎么还在
![image](https://user-images.githubusercontent.com/12658202/162232422-a50fac7d-9fa9-46bb-a2f4-71bce6d17c4b.png)

**Comment by hhch** [comment]
O(∩_∩)O哈哈~，同问，滚动好像不能生效，期待解决呀

**Comment by hhch** [comment]
建议和nutui协同作战，目前3.4.3和nutui的3.1.18存在大小写不兼容的问题，taro这边使用 onScrollToLower，而nutui使用 onScrolltolower

**Comment by yangxiaolu1993** [comment]
在Taro中，建议直接使用 Taro 现有 ScrollView 组件开发

**Comment by richard1015** [comment]
升级3.1.20
