### ISSUE TITLE
[suggest] 希望Swiper 轮播图新增一个3D模式

### ISSUE THREAD

**Issue by tqn911024** [jdf2e/nutui#1178]
一直用的nutui，但是因为目前多个项目需求 轮播图 有3d模式。类似于两边可以显示出上一张图和下一张图的 左边和右边一点。然后中间图比两边大一点那种，而目前的Swiper 无法做到。希望可以新增这个功能

**Comment by szg2008** [comment]
暂时不考虑加，如果有需求，可以直接使用swiper插件。感兴趣的话也欢迎提PR
