### ISSUE TITLE
[bug] nut-datepicker选择完日期后点击确定不关闭弹窗蒙板消失

### ISSUE THREAD

**Issue by Q-J-Brilliant** [jdf2e/nutui#1179]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
![image](https://user-images.githubusercontent.com/101537665/161797615-c9286d84-4a24-4885-adf2-f73d29323552.png)
![image](https://user-images.githubusercontent.com/101537665/161798047-eeb7a31f-2d8b-423e-922a-8748c8ad5758.png)

## 相关环境信息
- **操作系统**：windows11
- **Node 版本**：v16.13.0
- **NutUI 版本**： @nutui/nutui-taro@3.1.18
- **Vue 版本**：3.2.31
- **引用方式**：  CDN / NPM ？NPM

**Comment by yangxiaolu1993** [comment]
```<DataPicker/>``` 组件不要放到``` <Cell/>``` 组件内，尽可能保证 ```<DataPicker/>```在最外层

**Comment by richard1015** [comment]
升级3.1.20
