### ISSUE TITLE
[bug] datepicker选择日期最后一天选择小时没有出现

### ISSUE THREAD

**Issue by Q-J-Brilliant** [jdf2e/nutui#1180]
## 问题描述

![image](https://user-images.githubusercontent.com/101537665/161911585-22365859-71f6-4187-8cd3-d89849e8439d.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by yangxiaolu1993** [comment]
请问你使用的版本是多少？是否可以提供小版本复现仓库？

**Comment by Q-J-Brilliant** [comment]
@yangxiaolu1993 操作系统：windows11
Node 版本：v16.13.0
NutUI 版本： @nutui/nutui-taro@3.1.18
Vue 版本：3.2.31
引用方式： CDN / NPM ？NPM

**Comment by Q-J-Brilliant** [comment]
> 请问你使用的版本是多少？是否可以提供小版本复现仓库？

操作系统：windows11
Node 版本：v16.13.0
NutUI 版本： @nutui/nutui-taro@3.1.18
Vue 版本：3.2.31
引用方式： CDN / NPM ？NPM
