### ISSUE TITLE
[bug]DatePicker,Picker,List等控件问题

### ISSUE THREAD

**Issue by holyrong** [jdf2e/nutui#1185]
## 相关环境信息
- **操作系统**：windows 11
- **Node 版本**：16.4.2
- **NutUI 版本**： @nutui/nutui@3.1.18 
- **Vue 版本**：3.2.31
- **引用方式**：  yarn
-
#问题
**1.DatePicker 控件** 
type='year-month'时，不是按“年月”形式显示

**2.Picker控件** 
打算用Picker控件代替DatePicker选择年月。但设置 v-mode='current'绑定默认值时，出现以下情况：
（1）第一次渲染显示正常，（2）修改一次月份后，再次打开Picker，选中的月份值不是上次选中的值。比如第一次选中2022-04，再打开选择界面时，Picker显示的是：2022-08，关闭Picker再次打开时，变成2022-09，实际情况，current一直是2022-04

**3.List控件**
用官方文档的方式使用List控件，控制台报错：Failed to resolve component: scroll-view

**Comment by JiaLe1** [comment]
[Vue warn]: Failed to resolve component: scroll-view
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

也遇到了...

**Comment by note520** [comment]
"@nutui/nutui-taro": "3.1.8" 版本List组件，报同样的错误，scroll事件无效

**Comment by pubdreamcc** [comment]
一样的问题，啥时能解决吗。 datepicker  type='year-month', 不支持

**Comment by richard1015** [comment]
升级3.1.20

**Comment by shichaohui** [comment]
@richard1015 v3.1.22 还是报错 Failed to resolve component: scroll-view

**Comment by hhch** [comment]
scroll-view 多半都是跟taro版本兼容的问题
