### ISSUE TITLE
[bug] <nut-button>组件在小程序环境下build成 class="h5-button"

### ISSUE THREAD

**Issue by gezichenshan** [jdf2e/nutui#1186]
## 问题描述

`<nut-button>`组件在小程序环境下build成 `<button class="h5-button">`

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
暂无

## 预期的行为和实际行为
预期：不希望小程序下给button加上“h5-button”的class。
实际：小程序build后给button加上“h5-button”的class。

## 复现步骤，具体代码
一开始`<nut-buuton>`可以正确渲染，并未加上"h5-button"的class。
但我在项目中使用了一次原生的`<button>`后，后面build出的`<button>`标签全部加上了"h5-button"的样式。

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by gezichenshan** [comment]
现在看来，所有的原生组件都会被加上h5-tag的class name。但是其他组件h5-tag的样式并没有在最终的app.wxss中生成。除了h5-button:
```
.h5-button {
  font-family: inherit;
  font-size: 100%;
  line-height: 1.15;
  margin: 0;
  text-transform: none;
  background-color: transparent;
  background-image: none;
  padding: 0;
  line-height: inherit;
  color: inherit;
}
```
而这个样式是我不希望生成的。

**Comment by gezichenshan** [comment]
发现原因了，但凡template文件里用了原生标签，比如`<button>`，就会在最终的app.wxss里生成.h5-button的class name。
而且，就算是被注释的`<!-- <button> -->` 也会造成此效果。估计是taro cli在编译时做AST分析时，一旦发现原生标签就会加上原生class，但是忽略了对注释标签的处理。

而且，这个默认（磨人）的处理却没反映在文档里。真害人啊！！（捂脸。）

**Comment by richard1015** [comment]
有更好的建议可以反馈给taro那边   [taro issues](https://github.com/NervJS/taro/issues)
