### ISSUE TITLE
[bug] nut-infiniteloading当有滚动加载和下拉刷新时，只要触发过滚动加载，然后每次点击子元素，都会触发加载和下拉刷新事件，子元素事件没反应

### ISSUE THREAD

**Issue by LuEdision** [jdf2e/nutui#1189]
## 问题描述
nut-infiniteloading当有滚动加载和下拉刷新时，只要触发过滚动加载，然后每次点击子元素，都会触发加载和下拉刷新事件，子元素事件没反应

![动画](https://user-images.githubusercontent.com/63531046/162379540-04435415-f993-4d9e-a3b9-5ae3ce338cca.gif)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
<ul class="infiniteUl" id="refreshScroll">
      <nut-infiniteloading
        pull-icon="JD"
        container-id="refreshScroll"
        :use-window="false"
        :is-open-refresh="true"
        :has-more="hasMore"
        @load-more="onLoadMore"
        @refresh="onRefresh"
      >
        <li class="infiniteLi" v-for="(item, index) in logList" :key="index">
          {{ getTitle(item) }}
        </li>
      </nut-infiniteloading>
    </ul>

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：^14.x.x
- **NutUI 版本**： @nutui/nutui@3.1.18
- **Vue 版本**：  ^3.2.x
- **引用方式**：   NPM

**Comment by LuEdision** [comment]
<ul class="infiniteUl" id="refreshScroll">
      <nut-infiniteloading
        pull-icon="JD"
        container-id="refreshScroll"
        :use-window="false"
        :is-open-refresh="true"
        :has-more="hasMore"
        @load-more="onLoadMore"
        @refresh="onRefresh"
      >
        <li class="infiniteLi" v-for="(item, index) in logList" :key="index">
          {{ getTitle(item) }}
        </li>
      </nut-infiniteloading>
    </ul>

**Comment by LuEdision** [comment]
`<ul class="infiniteUl" id="refreshScroll">
      <nut-infiniteloading
        pull-icon="JD"
        container-id="refreshScroll"
        :use-window="false"
        :is-open-refresh="true"
        :has-more="hasMore"
        @load-more="onLoadMore"
        @refresh="onRefresh"
      >
        <li class="infiniteLi" v-for="(item, index) in logList" :key="index">
          {{ getTitle(item) }}
        </li>
      </nut-infiniteloading>
    </ul>`

**Comment by LuEdision** [comment]
[](url
![动画](https://user-images.githubusercontent.com/63531046/162380607-f084adea-fcbe-40b8-95be-b56d32bf22de.gif)
)
官网这个demo也有类似情况，都没下拉刷新，只是单纯的点击，就触发刷新事件了

**Comment by hhch** [comment]
建议和nutui协同作战，目前3.4.3和nutui的3.1.18存在大小写不兼容的问题，taro这边使用 onScrollToLower，而nutui使用 onScrolltolower

**Comment by hhch** [comment]
试过了，用taro 3.4.0 没有问题

**Comment by hhch** [comment]
taro那边使用模板构建nutui项目的时候还是要注意一下版本兼容性问题

**Comment by richard1015** [comment]
升级3.1.20

**Comment by hhch** [comment]
赞
