### ISSUE TITLE
nut-input输入类型为digit时依然可以输入汉字和字母

### ISSUE THREAD

**Issue by wangfpp** [jdf2e/nutui#1190]
## 问题描述
nut-input输入类型为digit时依然可以输入汉字和字母

## 相关环境信息
- **操作系统**：Windows10
- **Node 版本**：16.2.0
- **NutUI 版本**： @nutui/nutui@3.1.18 
- **Vue 版本**：3.2.31
- **引用方式**： NPM

**Comment by szg2008** [comment]
是在移动设备下测试的吗？

**Comment by wangfpp** [comment]
@szg2008 我是在PC上测试的 我看你们的示例上是好使的
