### ISSUE TITLE
Nutui 级联组件问题

### ISSUE THREAD

**Issue by Houvzhi-Von** [jdf2e/nutui#1191]
使用nutui的级联选择器 每一个options 的选项 text 和 value 必须是一样的吗？
我想通过后台发挥选项的数据 每一项数据是有id的
我使用了 Nutui 级联选择器组件 发现 text 和 value 必须是一致的 这是个bug吧 
value 能否支持对应数据中的 id text 对应 数据中的name 展示给用户 而最后提交将id 保存

**Comment by dongj0316** [comment]
@Houvzhi-Von text和value可以是不一样的，除此之外还可以指定其它的valueKey和textKey，你的问题能提供一个复现么
