### ISSUE TITLE
[bug]countdown组件,在倒计时过程中，控制台会一直输出警告，且读秒不应该从60开始。

### ISSUE THREAD

**Issue by wangrongding** [jdf2e/nutui#1192]
## 问题描述

![image](https://user-images.githubusercontent.com/42437658/162651004-90dba5fb-c56e-4ad6-bf39-e65ce827059c.png)

countdown组件,在倒计时过程中，控制台会一直输出警告，且读秒不应该从60开始。
由于是一秒一个警告，倒计时过长会导致电脑出现直接卡死的状态。

## 最小可复现仓库

不断警告的问题只会在小程序中出现

## 预期的行为和实际行为

没有警告，倒计时秒钟区域：最小值为00，最大值为59，非60。

## 复现步骤，具体代码

```html
<template>
  <nut-cell>
    <nut-countdown :end-time="end" />
  </nut-cell>
</template>

<script>
import { ref, reactive, toRefs } from "vue";
export default {
  name: "QweAas",
  setup(props) {
    const state = reactive({
      end: Date.now() + 60 * 1000,
    });
    return {
      ...toRefs(state),
    };
  },
};
</script>

```

将以上代码贴入小程序中，即可复现问题。

## 相关环境信息
- **操作系统**：windows10
- **Node 版本**：v16.13.0
- **NutUI 版本**：  @nutui/nutui-taro@3.1.18
- **Vue 版本**：3.2.21
- **引用方式**：  NPM

**Comment by wangrongding** [comment]
00:00:60 应该表示为 00:01:00

**Comment by wangrongding** [comment]
![image](https://user-images.githubusercontent.com/42437658/162658149-8cd18d25-7c66-42ed-b41c-c27fe6965f65.png)

countdown组件在倒计时过程中，由于控制台不断的打印警告导致的超出内存限制？

**Comment by richard1015** [comment]
升级3.1.20

**Comment by akFace** [comment]
![image](https://user-images.githubusercontent.com/22288837/221076229-58aad7d7-092c-4685-9cc9-f1f14b43b682.png)

**Comment by akFace** [comment]
v3.3.2 毫秒级渲染倒计时还会出现
![image](https://user-images.githubusercontent.com/22288837/221076268-d060b12c-27b3-483a-a9e8-83900d6eb73b.png)
