### ISSUE TITLE
[bug]nut-form-item 中使用 nut-datepicker 时间组件type="datetime"，会提示错误

### ISSUE THREAD

**Issue by yujianhui1993** [jdf2e/nutui#1197]
## 问题描述
nut-form-item 中使用 nut-datepicker 时间组件type="datetime"，会提示错误
没有在from 中使用时正常的。
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/7228360/163076475-05f5b9a7-6090-454c-8b90-6c8b22b66137.png">

<img width="457" alt="image" src="https://user-images.githubusercontent.com/7228360/163076546-7f97d099-08f5-4f13-b86c-a0e24854b53d.png">

## 最小可复现仓库
> 

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
在 Taro 中，<nut-form> 中使用 <nut-datepicker> 组件报错，无法获取高度
```<nut-form> 与 <nut-form-item> 在组合使用时，两者之间不能其余的标签，否则，Form 组件获取不到高度。
<nut-form :model-value="formData" ref="ruleForm">
  <view>
     <nut-form-item label="姓名" prop="name" required>
        <nut-datepicker  v-model:visible="show"/>
     </nut-form-item>
  </view>
<nut-form>```
上述示例，则会出现无法获取高度的错误，将 <view> 去掉即可。
