### ISSUE TITLE
[suggest] 功能建议 希望NutUI 商品卡片组件可以设置价格是否展示的开关设置

### ISSUE THREAD

**Issue by Houvzhi-Von** [jdf2e/nutui#1198]
因为不仅仅是商城类小程序开发者使用这款组件库 
我是一名做摄影社区类小程序的开发者 ，衷心希望 商品卡片组件可以加一个开关来控制价格是否展示在卡片中
现在组件里价格是必须要展示的，哪怕我在属性中不定义价格的字段 依旧展示了价格 （关于这一点我了解，因为NutiUI 毕竟是有京东孵化，所以组件库很多都是基于电商需求衍生出来的），因此提出这样的建议 希望可以采纳尽快弄好

**Comment by Drjingfubo** [comment]
25号3.1.19发版添加该props

**Comment by Houvzhi-Von** [comment]
我看NutUI的官方文档 商品卡片展示组件依旧没有 价格是否展示的可配置项 今天就是25号 请问一下会按时更新发布吗?
