### ISSUE TITLE
如何在nuxt.js里引入nutui

### ISSUE THREAD

**Issue by lhtzbj12** [jdf2e/nutui#120]
如题

**Comment by Franslee** [comment]
正常引入即可

**Comment by lhtzbj12** [comment]
在页面里只放一个nut-button，刷新页面时，出现以下错误。
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
