### ISSUE TITLE
nutui在taro3中运行css报错

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui#1200]
## 问题描述
nutui在taro3中运行报错
![image](https://user-images.githubusercontent.com/43030980/163322936-48c439df-bd8b-421d-affe-e24a5e595f46.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**： windows10
- **Node 版本**：16
- **NutUI 版本**："@nutui/nutui-taro": "^3.1.18",
- **Vue 版本**："@tarojs/cli": "^3.4.6",
- **引用方式**： NPM

**Comment by richard1015** [comment]
3.1.20
