### ISSUE TITLE
nut-picker安卓下会出现重影，ios不会[bug]

### ISSUE THREAD

**Issue by LuEdision** [jdf2e/nutui#1205]
## 问题描述

nut-picker在安卓端滑动时，选项出现重影，可以看我截图所标注的情况

![android](https://user-images.githubusercontent.com/63531046/163557392-c0e21e9b-7800-49fb-8e05-4e3f1609e6ee.png)

![ios](https://user-images.githubusercontent.com/63531046/163557413-f5b29b94-fce7-4922-b914-be4a9a923432.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：windows 10
- **Node 版本**：14.x.x
- **NutUI 版本**： @nutui/nutui@3.1.18
- **Vue 版本**：vue3.x.x
- **引用方式**：   NPM

**Comment by LuEdision** [comment]
不支持适配转换，如rem，px to viewport等

**Comment by yangxiaolu1993** [comment]
NutUI 是支持 Rem 转换的。请问，安卓的截图，你使用的是 Chrome 浏览器中的开发者工具吗

**Comment by wangfpp** [comment]
datePicker我在IOS上遇到了这样的情况  我得解决方法是给item写了一个`background-color: #fff`就可以了

**Comment by daniel87821** [comment]
转单位排除文件夹吧，保留px就好了，简单些，估计等修复没这么快！
