### ISSUE TITLE
Taro NuiUi Input组件vmode报错[bug]

### ISSUE THREAD

**Issue by lanhun** [jdf2e/nutui#1206]
## 问题描述
taro环境下,修改pluginCode的值会报错
`
<nut-input v-model="pluginCode"  label="传感器编号" />`

TypeError: Cannot read property '__treeManager__' of undefined
    at Proxy.<anonymous> (VM472 WAService.js:2)
    at Function.<anonymous> (.._src_dom_root.ts:179)
    at :49650/appservice/<setTimeout callback function>
    at VM472 WAService.js:2
    at VM472 WAService.js:2(env: macOS,mp,1.06.2203070; lib: 2.23.4)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
官方小程序demo直接扫第一个异步赋值的input就不会成功.

对应的路径
https://github.com/jdf2e/nutui-demo/blob/1fe49b778c281dd50bc6d45155ed9b91956dbb0b/taro/src/dentry/pages/input/index.vue

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by waveheart** [comment]
遇到相同问题 ...原来不是我一个人。。。。

**Comment by waveheart** [comment]
折腾了俩小时， 换了各种姿势
