### ISSUE TITLE
[bug] 模板初始化不能安装运行，直接报错

### ISSUE THREAD

**Issue by shunichio** [jdf2e/nutui#1207]
## 问题描述

根据 nutui 官网推荐的安装方式初始化项目，选择Vue3 + NutUI 模板时，项目启不起来。

<img width="610" alt="image" src="https://user-images.githubusercontent.com/23553358/163665661-1eeb468d-85e4-42f5-9016-fbf4aa90bacb.png">
<img width="937" alt="image" src="https://user-images.githubusercontent.com/23553358/163665675-5afefc66-2da7-41c4-bc66-1310400c46f4.png">

## 预期的行为和实际行为

项目可以初始化及启动

## 复现步骤，具体代码

安装指引使用NPM初始化项目既可

## 相关环境信息
- **操作系统**：macos
- **Node 版本**：15

**Comment by richard1015** [comment]
使用taro最新 cli 3.4.7 试试
