### ISSUE TITLE
为什么在"tab组件"下使用“图片预览组件”会影响图片预览组件的样式[question]

### ISSUE THREAD

**Issue by caishun2013** [jdf2e/nutui#1208]
## 你想知道什么？

tab组件与使用图片预览组件是否可以组合使用

## 描述你考虑过的替代方案

因为tab组件的transform: translate3d(0%, 0px, 0px);切换动画，会直接影响图片预览组件的定位问题

## 其它

无

**Comment by richard1015** [comment]
暂时先使用图片预览组件  不要放在 tabs下
