### ISSUE TITLE
[bug]CircleProgress 进度条组件，直接设置成100时，和从100设置成0时，会出现bug

### ISSUE THREAD

**Issue by wangrongding** [jdf2e/nutui#1209]
## 问题描述

CircleProgress 进度条组件的一些问题：  

1.  直接设置成100时，动画效果bug：有两个起始点
2.  从100变成0的时候，进度条出现问题，有一半颜色仍然在
3.  值的加减，没有最大最小值，也未提供最大最小值的设定属性，导致增加到100以上，继续增加会出现进度条样式问题

![](https://raw.githubusercontent.com/wangrongding/image-house/master/images202204181337896.gif)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

该问题仅出现在小程序端，h5并未复现，可使用下方贴出的代码在小程序端复现。

## 预期的行为和实际行为

能正常的显示动画效果和值

## 复现步骤，具体代码

```vue
<script setup lang="ts">
import { reactive } from "vue";
const state = reactive({ other: "...", count: 0 });
function change(val: number) {
  state.count = val;
}
const add = () => {
  state.count += 10;
};
const sub = () => {
  state.count -= 10;
};
</script>

<template>
  <button @click="change(100)">100</button>
  <button @click="change(0)">0</button>
  <button @click="add">加10</button>
  <button @click="sub">减10</button>
  <nut-circleprogress :progress="state.count" />
</template>

```

## 相关环境信息
- **操作系统**：Windows
- **Node 版本**：16+
- **NutUI 版本**：  "@nutui/nutui-taro": "3.1.18"
- **Vue 版本**："vue": "^3.2.24"
- **引用方式**：NPM

**Comment by Drjingfubo** [comment]
微信小程序中circleprogress已经重构，25号发版，至于最大值最小值还是需要使用者在使用时去进行限制

**Comment by Drjingfubo** [comment]
已经发布
