### ISSUE TITLE
[question]关于uploader上传图片的组件无法上传

### ISSUE THREAD

**Issue by cmlly** [jdf2e/nutui#1212]
## 你想知道什么？
在别的ui组件中，点击上传图片后能返回成功码，并且组件能识别是否上传成功。但是在nutui中，我点击上传图片后直接返回上传失败，但是服务器端已经收到了这张图片，我用了success，change，failure函数都没办法解决上传显示失败但是实则已经上传到服务器成功的问题。

**Comment by richard1015** [comment]
源码 https://github.com/jdf2e/nutui/blob/next/src/packages/__VUE/uploader/uploader.ts
官网 demo https://github.com/jdf2e/nutui/blob/next/src/packages/__VUE/uploader/demo.vue

**Comment by richard1015** [comment]
3.1.20已发布
