### ISSUE TITLE
[bug]官网文档轮播功能，在电脑端（非移动触摸）滑动时不能正常使用。

### ISSUE THREAD

**Issue by zihanoo** [jdf2e/nutui#1217]
https://nutui.jd.com/theme/#/swiper
https://nutui.jd.com/theme/demo.html#/swiper

你们的官网文档里面轮播功能，在电脑端（非移动触摸）滑动时不能正常使用。
（虽然是一个移动端触摸解决方案，但是这么一个普通的页面也需要支持一下鼠标滑动）

**Comment by nicetyler** [comment]
我也是这个问题，所有的东西在电脑端都用不了啊，也没有人回答一下到底怎么弄，但是官网上面又可以

**Comment by szg2008** [comment]
目前暂不支持电脑端，预计6月份版本支持

**Comment by szg2008** [comment]
#427

**Comment by richard1015** [comment]
v3.2.1 已修复 已发布
