### ISSUE TITLE
[question]请问一下nutui如何兼容pc浏览器，pc浏览器触发不了touch事件，picker组件无法拖动

### ISSUE THREAD

**Issue by nicetyler** [jdf2e/nutui#1218]
## 你想知道什么？

请问一下nutui如何兼容pc浏览器，pc浏览器触发不了touch事件，picker组件无法拖动

## 描述你考虑过的替代方案

我想...

## 其它

无

**Comment by RogerWenXin** [comment]
demo中可以使用，怎么设置的呢

**Comment by RogerWenXin** [comment]
我分析了官方demo,现在把这些代码贴进去使用吧

一段css, 去除用户选中文字
`.nut-picker-roller-item {
  user-select: none;
}`

这个js模块，在onMounted里面使用吧
`let Le;
let bt;
const Sn = function (t, n, o, l, s) {
  l = l || 0,
  s = s || 0,
  this.identifier = n,
  this.target = t,
  this.clientX = o.clientX + l,
  this.clientY = o.clientY + s,
  this.screenX = o.screenX + l,
  this.screenY = o.screenY + s,
  this.pageX = o.pageX + l,
  this.pageY = o.pageY + s;
};
function At() {
  const e = [];
  return e.item = function (t) {
    return this[t] || null;
  }
  ,
  e.identifiedTouch = function (t) {
    return this[t + 1] || null;
  }
  ,
  e;
}
function ln(e) {
  return e.type === 'mouseup' ? At() : Cn(e);
}
function Cn(e) {
  const t = At();
  return t.push(new Sn(Le, 1, e, 0, 0)),
  t;
}
function gg(e, t) {
  const n = document.createEvent('Event');
  n.initEvent(e, !0, !0),
  n.altKey = t.altKey,
  n.ctrlKey = t.ctrlKey,
  n.metaKey = t.metaKey,
  n.shiftKey = t.shiftKey,
  n.touches = ln(t),
  n.targetTouches = ln(t),
  n.changedTouches = Cn(t),
  Le.dispatchEvent(n);
}
function $t(e) {
  return function (t) {
    t.type === 'mousedown' && (bt = !0),
    t.type === 'mouseup' && (bt = !1),
    !(t.type === 'mousemove' && !bt) && ((t.type === 'mousedown' || !Le || Le && !Le.dispatchEvent) && (Le = t.target),
    gg(e, t),
    t.type === 'mouseup' && (Le = null));
  };
}
function enableTouch() {
  window.addEventListener('mousedown', $t('touchstart'), !0),
  window.addEventListener('mousemove', $t('touchmove'), !0),
  window.addEventListener('mouseup', $t('touchend'), !0);
}
export { enableTouch };
`

**Comment by nicetyler** [comment]
> 我分析了官方demo,现在把这些代码贴进去使用吧
> 
> 一段css, 去除用户选中文字 `.nut-picker-roller-item { user-select: none; }`
> 
> 这个js模块，在onMounted里面使用吧 `let Le; let bt; const Sn = function (t, n, o, l, s) { l = l || 0, s = s || 0, this.identifier = n, this.target = t, this.clientX = o.clientX + l, this.clientY = o.clientY + s, this.screenX = o.screenX + l, this.screenY = o.screenY + s, this.pageX = o.pageX + l, this.pageY = o.pageY + s; }; function At() { const e = []; return e.item = function (t) { return this[t] || null; } , e.identifiedTouch = function (t) { return this[t + 1] || null; } , e; } function ln(e) { return e.type === 'mouseup' ? At() : Cn(e); } function Cn(e) { const t = At(); return t.push(new Sn(Le, 1, e, 0, 0)), t; } function gg(e, t) { const n = document.createEvent('Event'); n.initEvent(e, !0, !0), n.altKey = t.altKey, n.ctrlKey = t.ctrlKey, n.metaKey = t.metaKey, n.shiftKey = t.shiftKey, n.touches = ln(t), n.targetTouches = ln(t), n.changedTouches = Cn(t), Le.dispatchEvent(n); } function $t(e) { return function (t) { t.type === 'mousedown' && (bt = !0), t.type === 'mouseup' && (bt = !1), !(t.type === 'mousemove' && !bt) && ((t.type === 'mousedown' || !Le || Le && !Le.dispatchEvent) && (Le = t.target), gg(e, t), t.type === 'mouseup' && (Le = null)); }; } function enableTouch() { window.addEventListener('mousedown', $t('touchstart'), !0), window.addEventListener('mousemove', $t('touchmove'), !0), window.addEventListener('mouseup', $t('touchend'), !0); } export { enableTouch }; `

好的太感谢了，我也试试，差不多就是要加个js做一层转化

**Comment by nicetyler** [comment]
> .nut-picker-roller-item { user-select: none; }

成功了厉害

**Comment by littleseven007** [comment]
> 我分析了官方demo,现在把这些代码贴进去使用吧
> 
> 一段css, 去除用户选中文字 `.nut-picker-roller-item { user-select: none; }`
> 
> 这个js模块，在onMounted里面使用吧 `let Le; let bt; const Sn = function (t, n, o, l, s) { l = l || 0, s = s || 0, this.identifier = n, this.target = t, this.clientX = o.clientX + l, this.clientY = o.clientY + s, this.screenX = o.screenX + l, this.screenY = o.screenY + s, this.pageX = o.pageX + l, this.pageY = o.pageY + s; }; function At() { const e = []; return e.item = function (t) { return this[t] || null; } , e.identifiedTouch = function (t) { return this[t + 1] || null; } , e; } function ln(e) { return e.type === 'mouseup' ? At() : Cn(e); } function Cn(e) { const t = At(); return t.push(new Sn(Le, 1, e, 0, 0)), t; } function gg(e, t) { const n = document.createEvent('Event'); n.initEvent(e, !0, !0), n.altKey = t.altKey, n.ctrlKey = t.ctrlKey, n.metaKey = t.metaKey, n.shiftKey = t.shiftKey, n.touches = ln(t), n.targetTouches = ln(t), n.changedTouches = Cn(t), Le.dispatchEvent(n); } function $t(e) { return function (t) { t.type === 'mousedown' && (bt = !0), t.type === 'mouseup' && (bt = !1), !(t.type === 'mousemove' && !bt) && ((t.type === 'mousedown' || !Le || Le && !Le.dispatchEvent) && (Le = t.target), gg(e, t), t.type === 'mouseup' && (Le = null)); }; } function enableTouch() { window.addEventListener('mousedown', $t('touchstart'), !0), window.addEventListener('mousemove', $t('touchmove'), !0), window.addEventListener('mouseup', $t('touchend'), !0); } export { enableTouch }; `

厉害，解决了！
