### ISSUE TITLE
[bug] 在使用Swipe组件时遇到了 Cannot read property 'width' of null

### ISSUE THREAD

**Issue by ymjdev** [jdf2e/nutui#1219]
## 问题描述

在使用Swipe组件时遇到了Cannot read property 'width' of null
const getRefWidth = async (ref2) => {
      let rect = await useTaroRect(ref2, Taro);
      return rect.width || 0;
};
上面的rect可能为undefined，当rect为undefined 时 return rect.width 控制台直接报 Cannot read property 'width' of null，后续逻辑直接失效了

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： "@nutui/nutui-taro": "^3.1.18"
- **Vue 版本**： 
- **引用方式**： NPM

**Comment by richard1015** [comment]
启动模式  是 h5 还是小程序 ，可以提供一个最小复现仓库

**Comment by ymjdev** [comment]
小程序端

**Comment by ymjdev** [comment]
> 启动模式 是 h5 还是小程序 ，可以提供一个最小复现仓库

小程序端，仓库没时间整

**Comment by ymjdev** [comment]
`<nut-swipe v-for="(item, i) in cartList" :key="item.skuId">
      <view class="product-item hairline-1px--bottom">
        <checkbox :checked="item.checked" @tap="changeChecked" :data-checked="item.checked" :data-skuId="item.skuId"
          class="checkbox"></checkbox>
      </view>
      <template #right>
        <nut-button shape="square" style="height:100%" type="primary" class="btn-delete" @tap="delCart(item, i)">删除
        </nut-button>
      </template>
    </nut-swipe>`
    
  ` import { useAuth } from '@/stores'
  const auth = useAuth()
  const cartList = computed(() => auth.cartList)`
  
 当其他页面push数据到cartlist就会报错

**Comment by ymjdev** [comment]
cartList 不实用计算属性就好了

**Comment by swinwang** [comment]
遇到一样的问题，动态push数据渲染出来的nut-swipe在iOS上左滑删除会失效，模拟器、Android都是正常的，甚至iOS扫码真机调试都是正常的，但是扫码预览左滑就失效了。
调试跟踪了一下源码，是在onMounted延时延时100ms执行initWidth有可能会失败，此时在useTaroRect方法内的query.exec执行没有回调。
![image](https://user-images.githubusercontent.com/25023718/170659130-07ffdfd8-2248-4b09-b5f8-e986ef8cecd6.png)
![image](https://user-images.githubusercontent.com/25023718/170658809-67e827de-4d8f-4837-9a9c-a1810c447930.png)
