### ISSUE TITLE
Cell、SearchBar组件触发页面刷新

### ISSUE THREAD

**Issue by Shiret** [jdf2e/nutui#122]
Cell组件无法实现router无刷新，只会当作跳转刷新，不能像<router-link>一样；
SearchBar搜索后页面刷新，这似乎就是一个表单提交刷新，源码并没阻止刷新；
Scorller组件没有提供滚动事件，让用户自定义一些滚动事件, pulldown 下拉回调不能关闭，有些时候用户不需要提供下拉刷新等功能时，希望关闭掉下拉事件，但应该将loadMore, pulldown事件默认为关闭，只有用户添加这个事件后算开启

**Comment by Franslee** [comment]
* Cell组件router跳转可以在点击事件内实现。
* SearchBar本身应该不会引起页面刷新，请贴代码。
* Scorller这部分建议我会反馈给这个组件的作者。
