### ISSUE TITLE
[bug] Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by xuwu125** [jdf2e/nutui#1222]
## 问题描述
⠼ Compiling...Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($indicator-size, 3) or calc($indicator-size / 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
557 │ $indicator-dot-size: $indicator-size / 3 !default;
    │                      ^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@nutui/nutui-taro/dist/styles/variables.scss 557:22  @import
    src/app.scss 1:9                                                  root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($indicator-size, 3) or calc($indicator-size / 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
557 │ $indicator-dot-size: $indicator-size / 3 !default;
    │                      ^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@nutui/nutui-taro/dist/styles/variables.scss 557:22  @import
    src/pages/index/index.vue 1:9                                     root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($indicator-size, 3) or calc($indicator-size / 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
557 │ $indicator-dot-size: $indicator-size / 3 !default;
    │                      ^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@nutui/nutui-taro/dist/styles/variables.scss 557:22   @import
    node_modules/@nutui/nutui-taro/dist/packages/toast/index.scss 1:9  root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($indicator-size, 3) or calc($indicator-size / 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
557 │ $indicator-dot-size: $indicator-size / 3 !default;
    │                      ^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@nutui/nutui-taro/dist/styles/variables.scss 557:22    @import
    node_modules/@nutui/nutui-taro/dist/packages/button/index.scss 1:9  root stylesheet

├── @babel/core@7.17.9
├── @babel/runtime@7.17.9
├── @nutui/nutui-taro@3.1.18
├── @tarojs/cli@3.4.7
├── @tarojs/components@3.4.7
├── @tarojs/mini-runner@3.4.7
├── @tarojs/plugin-framework-vue3@3.4.7
├── @tarojs/plugin-html@3.4.7
├── @tarojs/runtime@3.4.7
├── @tarojs/taro@3.4.7
├── @tarojs/webpack-runner@3.4.7
├── @types/webpack-env@1.16.4
├── @typescript-eslint/eslint-plugin@5.20.0
├── @typescript-eslint/parser@5.20.0
├── @vue/compiler-sfc@3.2.33
├── babel-plugin-import@1.13.5
├── babel-preset-taro@3.4.7
├── eslint-config-taro@3.4.7
├── eslint-plugin-vue@8.6.0
├── eslint@8.13.0
├── stylelint@9.3.0
├── typescript@3.9.10
├── vue-loader@16.8.3
└── vue@3.2.33

## 复现步骤，具体代码

安装完成DEMO 之后运行就直接运行 npm run dev:h5 就会出现

## 相关环境信息
- **操作系统**：Mac os 11.6.5
- **Node 版本**：16.14.2
- **NutUI 版本**： @nutui/nutui-taro@3.1.18
- **Vue 版本**：vue@3.2.33
- **引用方式**：  NPM

**Comment by richard1015** [comment]
3.1.19-beta 已修复，下周一发版

**Comment by WangShayne** [comment]
@richard1015 请问几点发版?

**Comment by richard1015** [comment]
2022年04月25日17:30

**Comment by WangShayne** [comment]
感谢

**Comment by S-T-D** [comment]
"@nutui/nutui-taro@^3.2.2" 怎么我用这个版本还是会报这个警告呢？
