### ISSUE TITLE
[bug]nutui Uploader上传组件在h5上传时header信息缺失。

### ISSUE THREAD

**Issue by bin-bin-6** [jdf2e/nutui#1226]
版本： "@nutui/nutui-taro": "^3.1.18"

打开 @nutui\nutui-taro\dist\packages\_es\Uploader.js
注释掉以下代码即刻上传成功。     
// header: __spreadValues({
  //   "Content-Type": "multipart/form-data"
  // }, options.headers),

**Comment by richard1015** [comment]
该问题已修复 ，  使用最新的 nutui-taro beta试试 

https://www.npmjs.com/package/@nutui/nutui-taro/v/3.1.19-beta.6
