### ISSUE TITLE
[上传附件远源码。      fileItem.path = file.path;  fileItem.name = file.path]

### ISSUE THREAD

**Issue by GuoWei1016** [jdf2e/nutui#1231]
## 最小可复现仓库
> const readFile = (files: Taro.chooseImage.ImageFile[]) => {
      const imgReg = /\.(png|jpeg|jpg|webp|gif)$/i;
      files.forEach((file: Taro.chooseImage.ImageFile, index: number) => {
        let fileType = file.type;
        const fileItem = reactive(new FileItem());
        if (!fileType && imgReg.test(file.path)) {
          fileType = 'image';
        }
        fileItem.path = file.path;
        fileItem.name = file.path;
        fileItem.status = 'ready';
        fileItem.message = translate('waitingUpload');
        fileItem.type = fileType;
        if (Taro.getEnv() == 'WEB') {
          const formData = new FormData();
          for (const [key, value] of Object.entries(props.data)) {
            formData.append(key, value);
          }
          formData.append(props.name, file.originalFileObj as Blob);
          fileItem.name = file.originalFileObj?.name;
          fileItem.type = file.originalFileObj?.type;
          fileItem.formData = formData;
        } else {
          fileItem.formData = props.data as FormData;
        }
        if (props.isPreview) {
          fileItem.url = file.path;
        }
        fileList.push(fileItem);
        executeUpload(fileItem, index);
      });
    };

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
使用最新beta版本试试

**Comment by richard1015** [comment]
3.1.20已发布
