### ISSUE TITLE
[bug] Cascader 传入tree 数据 末级数据有重复时 父路径查询错误

### ISSUE THREAD

**Issue by xcc1995** [jdf2e/nutui#1233]
## 问题描述

Cascader 组件 当最后一级数据重名时 父路径查询错误
应该是 eachTree（node,function）中function需改进
getNodeByValue(value: CascaderOption['value']): CascaderOption | void {
let foundNode;
console.log(this.nodes);
eachTree(this.nodes, (node: CascaderOption) => {
if (node.value === value) {
foundNode = node;
return true;
}
});
console.log(foundNode);
return foundNode;
}

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
tree 数据中增加code 父路径按code查找

## 复现步骤，具体代码
将 demo中的demo2改为以下数据可以复现
const demo2 = reactive({
visible: false,
value: ['福建', '福州', '台江区'],
options: [
{
text: '浙江',
items: [
{
text: '杭州',
disabled: true,
items: [
{ text: '西湖区', code: 1 },
{ text: '余杭区', code: 2 }
]
},
{
text: '温州',
items: [
{ text: '鹿城区', code: 3 },
{ text: '瓯海区', code: 4 } //问题出现代码----------------------------------------------------------------------
]
}
]
},
{
text: '福建',
items: [
{
text: '福州',
items: [
{ text: '鼓楼区', code: 5 },
{ text: '台江区', code: 6 },
{ text: '瓯海区', code: 4 } //问题出现代码----------------------------------------------------------------------
]
}
]
}
]
});

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by dongj0316** [comment]
@xcc1995 请问什么场景会有末级数据重复呢

**Comment by xcc1995** [comment]
@dongj0316 我是用来做了一个图书章节选择的东西

**Comment by dongj0316** [comment]
@xcc1995 好的修复中

**Comment by richard1015** [comment]
3.1.20已发布
