### ISSUE TITLE
uploader组件选择完图片后当前vue自动刷新，重新渲染，导致又重新执行app.ts

### ISSUE THREAD

**Issue by dongzheng911** [jdf2e/nutui#1242]
## 问题描述
vue页面代码
<template>
  <nut-uploader :url="uploadUrl" :data="uploaddata" maximum="5" :auto-upload="false" v-model:file-list="defaultFileList" ref="uploadRef"></nut-uploader>
  <br />
  <nut-button type="success" size="small" @click="submitUpload">执行上传</nut-button>
</template>
<script lang="ts">
import { ref,reactive,toRefs } from 'vue';
interface fileItem {
  status:string,
  uid	:string,
  name	:string,
  url	:string,
  type	:string,
  formData:FormData

}
interface FormData{
  uid:number,
  token:string,
  num:number
}
export default {
  setup() {
    const uploadUrl = 'xxxxxxx';
     const uploaddata = ref({
         uid:14,
         token:111222333,
         num:1
     });
    const uploadRef = ref<any>(null);
    const submitUpload = () => {
      console.log(uploadRef.value)
      console.log(state.defaultFileList)
         state.defaultFileList[0].formData.num = 200;
         
      
      uploadRef.value.submit();
    };
    const state = reactive<{defaultFileList:fileItem []}>({defaultFileList:[]});
    return {
      ...toRefs(state),
      uploadUrl,
      uploadRef,
      submitUpload,
      uploaddata
      

    };
  }
}
</script>
app.ts代码
import { createApp } from 'vue'
import Taro from '@tarojs/taro'
import { Button, Toast,Tabbar,TabbarItem,Icon,Uploader ,Progress} from '@nutui/nutui-taro';
import './app.scss'
import {callGetOpenIdApi} from "./services/SyncRequest";

function getOpenId(){
  Taro.login({
     success:async  result =>{
       const res = await callGetOpenIdApi({code:result.code,appid:'xxxxxxx'});
       if(res.code ==200){
         const {openid,id}=res.data;
         console.log(333,res.data);
          Taro.setStorageSync('openid',openid);
          Taro.setStorageSync('id',id);
       }
     }
  })
}
const App = createApp({
  onShow (options) {
    getOpenId();
    Taro.showModal({
      content:'小程序需要订阅以下模板获取通知消息',
      // showCancel:false,
      confirmColor:'#06B48D',
      success : function(res) {
        //trial  developer formal
        Taro.requestSubscribeMessage({
          tmplIds: [],
          success: function (res) {
            console.log(333,'授权成功');
          },
          fail : function(res) {
            console.log(333,'授权失败');
  
          }
        })
      }
    })
  },
  // 入口组件不需要实现 render 方法，即使实现了也会被 taro 所覆盖
  
})

App.use(Button).use(Toast).use(Tabbar).use(TabbarItem).use(Icon).use(Uploader).use(Progress)

export default App

## 预期的行为和实际行为
当前页面图片正常显示
实际行为：当前页面正常显示，选择完图片后，小程序会重新登陆，然后在当前页面重新弹出定义在app.ts的modal。

## 相关环境信息
- **操作系统**：macos 12.3.1
- **Node 版本**：v16.13.1
- **NutUI 版本**： "^3.1.8",
- **Vue 版本**：3.0
- **引用方式**：  NPM

**Comment by richard1015** [comment]
3.1.20已发布 试试看
