### ISSUE TITLE
[bug] uploader 组件 change 事件 fileItem 问题

### ISSUE THREAD

**Issue by daniel87821** [jdf2e/nutui#1243]
## 问题描述
nu-uploader 配置了change 事件，选择文件后，change回调 toRaw(e.fileList); proxy转对象，然后 fileList 里的数组是空白的。
但如果再上传多一个文件时，fileList 就能成功有1条数据了。。。

## 最小可复现仓库
没有

## 预期的行为和实际行为
选择文件后，预期应该是 change 事件里，能拿到文件对象 fileItem

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@next
- **Vue 版本**：3
- **引用方式**：  CDN / NPM ？NPM

**Comment by daniel87821** [comment]
估计是数据异步更新的原因，change 事件触发后，setTimeout 延时获取 fileList 就好了

**Comment by richard1015** [comment]
3.1.20已发布 试试看

**Comment by daniel87821** [comment]
昨天试过 3.1.20 了，也是会有这个问题

**Comment by daniel87821** [comment]
const changeEvent = (e) => {
  // 这样可以
  setTimeout(function () {
    console.log('file.url', e.fileList[0])
  }, 300)
  // 这样不行
  console.log(e.fileList[0])
}

**Comment by richard1015** [comment]
change 事件是  fileList 是异步装载，建议你从beforeUpload中拦截
