### ISSUE TITLE
[bug] 小程序中 nut-input 在输入过值以后，双向绑定失效，清空绑定的值，直接报错！h5中正常

### ISSUE THREAD

**Issue by waveheart** [jdf2e/nutui#1244]
## 问题描述

最简单的一个input，设置v-model ，输入值以后，再通过v-mdel 绑定，回直接报错
在添加一个按钮, 设置事件为修改v-model的值

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

```
<template>
  <view>
      <nut-input placeholder="请输入文本" v-model="state.val1" label="文本" />
    	<nut-button @click="changeValue">test</nut-button>
  </view>

</template>
<script lang="ts">
  import { reactive } from 'vue';
  export default {
    setup() {
      const state = reactive({
        val1: ''
      });
      
      const changeValue = () => {
      	state.val1 = '3333'
      }
      
      return {
        state,
        changeValue
      };
    }
  }
</script>
```

## 预期的行为和实际行为
# 注意，要先在输入框中输入一些值
预期，input值应该变为 333
实际： 控制台报错  TypeError: Cannot read property '__treeManager__' of undefined

## 复现步骤，具体代码

如上

1， 上述例子中，输入 任何值
2， 点击test按钮，无法实现更新绑定值，或者清空值， h5中正常

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by waveheart** [comment]
同 issues/1206

换了俩小时的姿势，始终怀疑是我的姿势出问题了。。。。o(╥﹏╥)o
原来别人也遇到了

**Comment by waveheart** [comment]
@ailululu 能给个解决方案么，或者说是什么原因导致的？另一个issue我看 也关掉了

**Comment by ailululu** [comment]
> @ailululu有什么问题可以解决什么问题，或者说是什么原因？

关掉issue说明最新版本已解决该问题，可以更新至最新版本3.1.20~

**Comment by ailululu** [comment]
@waveheart 
关掉issue说明最新版本已解决该问题，可以更新至最新版本3.1.20~

**Comment by waveheart** [comment]
@ailululu 我的问题， 我的issue没有描述对，taro版本是最新的

发现问题之后有尝试过过升级最新版本，但是未能解决

![image](https://user-images.githubusercontent.com/25602259/170804804-40f8dab8-03c6-4a3f-8ec2-33eef1a7149b.png)

**Comment by ghost** [comment]
nutui 4.0.3遇到同样问题

**Comment by eiinu** [comment]
> nutui 4.0.3遇到同样问题

可以试一下 4.0.4-beta.2 版本
