### ISSUE TITLE
[question]主题设计器不能在线保存或者导入吗？

### ISSUE THREAD

**Issue by kongsiyu** [jdf2e/nutui#1247]
## 你想知道什么？

    你好，我想知道主题设计器不能在线保存或者导入?
因为在用的主题难免会有调整，如果不能导入的话每次都要从头调一遍样式，很难维护

## 描述你考虑过的替代方案

    建议可以把下载的主题文件重新导入设计器，方便继续调整

## 其它

无

**Comment by richard1015** [comment]
隐藏功能  theme 参数可传入 配置文件链接

https://nutui.jd.com/theme/?theme=https://storage.360buyimg.com/nutui-static/source/variables-jdt.scss_source#/button

**Comment by richard1015** [comment]
感兴趣可以参与共建

**Comment by kongsiyu** [comment]
已尝试成功，感谢！
（提示：各位想尝试的小伙伴注意下自己的主题文件必须放在支持跨域的服务器上）
