### ISSUE TITLE
[bug]Swiper 渲染问题

### ISSUE THREAD

**Issue by sum1201** [jdf2e/nutui#1249]
## 问题描述
通过vuex 异步获取数据后，不能立即显示图片，需要手工点击一下才可以。  taro 原生的没有问题。
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
检查代码之后，发现在子元素数量更新后，重新渲染时，moving =true , 导致 style 没有更新。应该在更新后， moving=False
https://github.com/jdf2e/nutui/blob/66c88b0f5f49ca0702d252f028f0adbb1b669ef4/src/packages/__VUE/swiper/index.taro.vue#L432-L439

https://github.com/jdf2e/nutui/blob/66c88b0f5f49ca0702d252f028f0adbb1b669ef4/src/packages/__VUE/swiper/index.taro.vue#L319-L331

https://github.com/jdf2e/nutui/blob/66c88b0f5f49ca0702d252f028f0adbb1b669ef4/src/packages/__VUE/swiper/index.taro.vue#L165-L172

当我点击swiper后，moving =False, 所以图片就显示了。
https://github.com/jdf2e/nutui/blob/66c88b0f5f49ca0702d252f028f0adbb1b669ef4/src/packages/__VUE/swiper/index.taro.vue#L354-L377

[1.txt](https://github.com/jdf2e/nutui/files/8562505/1.txt)
<img width="520" alt="QQ20220426-185836@2x" src="https://user-images.githubusercontent.com/5398273/165285631-d9135fd8-6687-4c34-a24c-386dcfd859d8.png">

## 相关环境信息
- **操作系统**：Mac OS 12.2.1
- **Node 版本**：18.0
- **NutUI 版本**： @nutui/nutui-taro@3.1.20
- **Vue 版本**：3.2.33
- **引用方式**：  NPM

**Comment by richard1015** [comment]
![image](https://user-images.githubusercontent.com/13060263/185833151-d1242345-2b6b-483b-897d-519e5661d8c7.png)

**Comment by szg2008** [comment]
@sum1201 ，能否提供一下可复现的仓库，我这里无法复现
