### ISSUE TITLE
使用jdt科技主题样式不生效

### ISSUE THREAD

**Issue by 929408183** [jdf2e/nutui#1250]
## 你想知道什么？

你好，我想知道为何使用jdt科技主题样式不生效，我在vue.config.js中引入了下面的配置，自定义的custom_theme.scss 生效，但是variables-jdt.scss没有任何效果
![image](https://user-images.githubusercontent.com/37289057/165457543-95a3e8ce-4c8e-4e2a-8f46-848920bd6145.png)

下面是显示效果&配置
![image](https://user-images.githubusercontent.com/37289057/165457955-74f1d732-b9d3-4c31-b030-775fb51d060a.png)
![image](https://user-images.githubusercontent.com/37289057/165458053-8b94e7ee-39c0-47f6-b8fe-2d52a0f4af9e.png)
![image](https://user-images.githubusercontent.com/37289057/165458100-ecbd66a4-7f05-43f4-a279-005076c240a8.png)

## 描述你考虑过的替代方案

我是一个前端初学者，求解答

## 其它

无

**Comment by dongj0316** [comment]
看看sass-loader的版本是多少呢

**Comment by 929408183** [comment]
> 看看sass-loader的版本是多少呢
    "sass-loader": "^8.0.2",
![image](https://user-images.githubusercontent.com/37289057/165494725-f8da2f9e-7c1d-4efd-ac67-fb570ae82fc9.png)

**Comment by 929408183** [comment]
@dongj0316

**Comment by 929408183** [comment]
help

**Comment by 929408183** [comment]
navbar  字体样式没生效

**Comment by 929408183** [comment]
![image](https://user-images.githubusercontent.com/37289057/165503748-759f23f1-f4dc-4746-b2a2-0c07a074f16e.png)

Navbar组件  切换 jdt 科技主题  样式并没有生效，其他的部分组件生效了

**Comment by dongj0316** [comment]
@929408183 看起来主题应该已经成功引入了

**Comment by richard1015** [comment]
参考这个仓库即可，我测试了，没问题
