### ISSUE TITLE
[bug]多tab切换导航，tabs 插槽无效

### ISSUE THREAD

**Issue by yycmd** [jdf2e/nutui#1254]
## 问题描述

使用官网的[多tab切换导航例子](https://nutui.jd.com/3x/index.html#/navbar)  在 tabs 组件下使用插槽无内容渲染

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为

使用 多 tab 切换导航栏的情况下，使用 tab 的插槽，应该和单独使用 tab 组件效果一致

## 复现步骤，具体代码
```
<template>
  <nut-navbar
      @on-click-back="back"
      @on-click-title="title"
      @on-click-right="rightClick"
      desc="编辑"
    >
      <template #content>
        <nut-tabs v-model="tab1value" @click="changeTab">
          <nut-tabpane title="商品">
            <view>1111</view>
          </nut-tabpane>
          <nut-tabpane title="店铺">
          	<view>2222</view>
          </nut-tabpane>
        </nut-tabs>
      </template>
      <template #right>
        <nut-icon class="right" name="more-x"></nut-icon>
      </template>
    </nut-navbar>
  </template>
```
商品 tabpane 的 插槽里面， <view>1111</view> 标签无法渲染
店铺tabpane 的 插槽里面， <view>2222</view> 标签无法渲染

预期的效果是 单独使用 tab 一样的

nvabar 使用 tab 组件效果：
![3](https://user-images.githubusercontent.com/17695132/165504544-d9ba9724-6a79-4b70-a9b4-4dc852f7938e.png)

单独 使用 tab 组件效果：
![QQ截图20220427185855](https://user-images.githubusercontent.com/17695132/165504512-e57864d4-9ae2-491e-a7ad-c19085c50f64.png)
![QQ截图20220427185848](https://user-images.githubusercontent.com/17695132/165504533-574131fd-e75a-4ce0-b870-8dbbe3935d65.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
nav 设计初衷就是 只提供头部导航， 如果你想要tabs的效果，直接单独采用tabs组件即可， tabs头部支持自定义
