### ISSUE TITLE
[bug] Input输入框快速输入光标闪烁

### ISSUE THREAD

**Issue by millzhang** [jdf2e/nutui#1259]
## 问题描述

小程序，在Input和Form的Input中，快速输入，input光标闪烁（位置偏要当前输入字符，往前闪烁）

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

https://github.com/jdf2e/nutui-demo/tree/master/taro
## 预期的行为和实际行为

预期绿色光标稳定跟踪文字

## 复现步骤，具体代码
官方的小程序demo即可复现

https://user-images.githubusercontent.com/8767429/165701914-57f40aac-9b21-4906-8c3e-19a9b2802fc0.mov

## 相关环境信息
- **操作系统**：小程序
- **Node 版本**：14
- **NutUI 版本**： @nutui/nutui-taro@3.1.18 
- **Vue 版本**：VUE 3.0
- **引用方式**：  NPM

**Comment by richard1015** [comment]
该问题为原生bug，暂时无法解决 ，你慢点输入 :(
