### ISSUE TITLE
[bug]nut-addresslist组件加载异步数据异常

### ISSUE THREAD

**Issue by Rosethorn99** [jdf2e/nutui#1262]
## 问题描述
nut-addresslist组件异步数据无法渲染, 本地数据渲染正常

## 复现步骤，具体代码
![image](https://user-images.githubusercontent.com/40927708/165734670-a128b1fa-062d-4bf5-9b82-0ebff9f7e73e.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：14.18.1
- **NutUI 版本**： @nutui/nutui-taro@3.1.20
- **Vue 版本**：3.2.33

**Comment by yangjisen** [comment]
[Pref: 优化地址列表数据变更重新渲染](https://github.com/jdf2e/nutui/pull/1270)

**Comment by richard1015** [comment]
@yangxiaolu1993  看一下开发者，提供了修复PR 是否可以直接合入
