### ISSUE TITLE
[bug]Form表单在小程序使用

### ISSUE THREAD

**Issue by yangjinjun3** [jdf2e/nutui#1266]
## 问题描述
Form表单在小程序使用,假设有两个form-item , 第一个 form-item添加required，第二个 form-item不添加required。那么label的内容就不对齐了。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
![image](https://user-images.githubusercontent.com/44964193/165949760-1d83b235-48af-4571-a85f-773846779444.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
label-align 设置对齐方式
