### ISSUE TITLE
[suggest]自定义主题

### ISSUE THREAD

**Issue by yangjinjun3** [jdf2e/nutui#1267]
## 你建议我们做什么？

改的primary  发现在某些error的情况也用用到了  但是我觉得error虽然跟京东主题色一样  也应该用两个变量区分。
就比如 这个input 这个取的primay  这个颜色其实 给input传error用的  我觉得应该取其他变量

<img width="674" alt="eefb9b2ce718cfacc1b8aed76e19b9b" src="https://user-images.githubusercontent.com/44964193/165950001-ee46d494-7226-4de5-89fc-746ad5293ffe.png">

如果你能...

它将使...

## 其它

无

**Comment by richard1015** [comment]
@yangjinjun3 改一下pr上来
