### ISSUE TITLE
[question]如何在nutui-taro中全局调用toast组件?

### ISSUE THREAD

**Issue by WangShayne** [jdf2e/nutui#1268]
## 你想知道什么？

如何在nutui-taro中全局调用toast组件?
例如在request中全局提示错误消息

## 描述你考虑过的替代方案

我想...

## 其它

无

**Comment by richard1015** [comment]
暂时采用 Taro API
https://taro-docs.jd.com/taro/docs/apis/ui/interaction/showToast
