### ISSUE TITLE
[suggest]<nut-form-item>下的input文本样式

### ISSUE THREAD

**Issue by hustjiangtao** [jdf2e/nutui#1272]
## 你建议我们做什么？

现在...
```
  <nut-form-item label="地址" prop="address" required :rules="[{ required: true, message: '请填写地址' }]">
    <input class="nut-input-text" v-model="formData.address" placeholder="请输入地址" type="text" />
  </nut-form-item>
```
当前的`form`表单中子项样式会继承`<nut-cell />`、`<nut-form-item />`，导致`form`表单中的`input`文本样式显示为`.nut-cell__value`默认样式的灰色`#cccccc`，所以往往仍需单独另加样式

希望能够改进此项，显示默认的`input`样式或者`black`，毕竟灰色的输入项不常会用到

## 其它

示例代码可以直接复制文档中的代码，即可复现

[nutui官方文档](https://nutui.jd.com/3x/index.html#/form)

**Comment by richard1015** [comment]
感谢反馈，下个版本发版修复了

**Comment by richard1015** [comment]
标记   小程序输入后颜色与官网demo示例不符合 3.1.21发布时处理
