### ISSUE TITLE
[bug]  升级3.1.20，build样式报错 

### ISSUE THREAD

**Issue by LuEdision** [jdf2e/nutui#1274]
## 问题描述
![飞书20220505-135542](https://user-images.githubusercontent.com/63531046/166869632-795daa57-d8c6-44b0-a522-664fe57afdf8.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：14.x.x
- **NutUI 版本**： @nutui/nutui@3.1.20
- **Vue 版本**：vue3
- **引用方式**：NPM ？

**Comment by zch233** [comment]
是的，同样遇到了

**Comment by richard1015** [comment]
把taro依赖包 升级 至最新 3.4.9 即可，这是由于taro底层升级了 依赖sass 版本
