### ISSUE TITLE
[bug]Toast close关闭时触发的事件无法调用

### ISSUE THREAD

**Issue by SJW2017** [jdf2e/nutui#1275]
## 问题描述

Toast 关闭回调方法不执行

## 错误原因？？

文档方法名错误

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/33503155/166888795-7a8bbbba-256d-4427-babb-37a640072499.png">
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/33503155/166888418-fe287291-7d23-4bf7-967d-20a108e9fe60.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/33503155/166888592-4bcc9210-a4a3-4e11-9bab-fe1414dbeb55.png">

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：v14.15.4
- **NutUI 版本**： "@nutui/nutui": "^3.1.18",
- **Vue 版本**："vue": "^3.0.0",
- **引用方式**： NPM

**Comment by richard1015** [comment]
升级最新版本尝试一下，我这边测试的没问题
import { Toast } from '@nutui/nutui';
``` js
   Toast.text('登录成功，即将跳转请稍等...', {
              onClose: () => {
               console.log('xxx')
              }
            });
```
