### ISSUE TITLE
[bug] 无法全局引入NutUI

### ISSUE THREAD

**Issue by theodorehills** [jdf2e/nutui#1276]
## 问题描述

当使用官方demo全局引入NutUI时，会报“NutUI is not defined.”的问题

## 最小可复现仓库
[ GitHub 仓库](https://github.com/theodorehills/book-store)

## 预期的行为和实际行为
预期：成功引入NutUI，并可以随意使用NutUI中的内容
实际：运行 `yarn dev:h5` 浏览器报错 `Uncaught ReferenceError: NutUI is not defined`

## 复现步骤，具体代码
只要使用全局引入
```
import NutUI from '@nutui/nutui-taro'
import '@nutui/nutui-taro/dist/style.css'

...

App.use(NutUI)
```
就必定会出现此问题，但是按需导入不会出现问题

## 相关环境信息
- **操作系统**：Windows 11
- **Node 版本**：16.14.0
- **NutUI 版本**：@nutui/nutui-taro@3.1.20
- **Vue 版本**：3.0.0
- **引用方式**：npm

**Comment by richard1015** [comment]
这是由于开启了 babel 按需加载插件，把babal.config对应的plugin删除就可以了

**Comment by theodorehills** [comment]
@richard1015 不懂就问，请问下面哪一行是按需引入的插件代码？
```javascript
plugins: [
    [
      "import",
      {
        "libraryName": "@nutui/nutui-taro",
        "libraryDirectory": "dist/packages/_es",
        "style": (name, file) => name.toLowerCase().replace('_es/', '') + '/index.scss',
        "camel2DashComponentName": false
      },
      'nutui3-taro'
    ]
  ]
```
