### ISSUE TITLE
nut-popup组件小程序端 lock-scroll 无效

### ISSUE THREAD

**Issue by liuxinju** [jdf2e/nutui#1282]
## 问题描述

小程序端使用nut-popup组件会有穿透滑动的问题，滑动弹窗遮罩层或者滑动弹窗内部，弹窗底下的内容也会跟着滑动（pc端没有问题）
lock-scroll 无效
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：v16.15.0
- **NutUI 版本**： @nutui/nutui-taro@3.1.17
- **Vue 版本**： @vue/cli 5.0.4
- **引用方式**：  npm@8.5.5

**Comment by emorywang** [comment]
我也遇到同样的问题，类似的组件（比如picker）也是如此

**Comment by szg2008** [comment]
目前解决办法只能自己在外层增加样式控制

**Comment by zhangyuanliang** [comment]
可以通过配置page-meta解决，弹窗出现时设置`page-style="overflow:hidden"`，关闭时设置`page-style=""`。
```
<page-meta
  page-style="overflow: hidden"
>
</page-meta>
```
