### ISSUE TITLE
nut-calendar组件 start-date与end-date在同一月份时，会出现日期空白的情况

### ISSUE THREAD

**Issue by liuxinju** [jdf2e/nutui#1283]
## 问题描述

nut-calendar组件 start-date与end-date在同一月份时，会出现日期空白的情况，如下图：

<img width="374" alt="image" src="https://user-images.githubusercontent.com/28803566/167859760-eb640c9d-83b9-4f87-b3dd-21f3631248b2.png">

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

<template>
  <nut-cell
    :showIcon="true"
    title="选择单个日期"
    :desc="state.date ? `${state.date}` : '请选择'"
    @click="openSwitch('isVisible')"
  >
  </nut-cell>
  <nut-calendar
    v-model:visible="state.isVisible"
    :default-value="state.date"
    @close="closeSwitch('isVisible')"
    @choose="setChooseValue"
    :start-date="`2022-05-05`"
    :end-date="`2022-05-08`"
  >
  </nut-calendar>
</template>
<script setup>
import { reactive } from 'vue'

const state = reactive({
  isVisible: false,
  date: ''
})

const openSwitch = (param) => {
  state[`${param}`] = true
}
const closeSwitch = (param) => {
  state[`${param}`] = false
}
const setChooseValue = (param) => {
  state.date = param[3]
  state.dateWeek = param[4]
}

</script>

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by lkjh3214** [comment]
请问能否提供下，nutui使用的版本信息，是h5 还是taro？

**Comment by liuxinju** [comment]
taro
@nutui/nutui-taro: "3.1.18"
直接使用https://nutui.jd.com/#/zh-CN/component/calendar 这边的demo修改下日期就可以复现
