### ISSUE TITLE
List 虚拟列表[bug]

### ISSUE THREAD

**Issue by 1102712387** [jdf2e/nutui#1284]
## 问题描述
List 虚拟列表 在H5端报错 TypeError: Cannot read property 'scrollTop' of undefined

## 相关环境信息

- **NutUI 版本**： @nutui/nutui@3.x.x  
- **Vue 版本**：3.2

**Comment by hu-qi** [comment]
应该是没做 H5 的兼容，改成：
`const scrollTop = e.detail ? e.detail.scrollTop : e.target.scrollTop;`
就能正常运行了。
![image](https://user-images.githubusercontent.com/17986122/169987770-843a760a-1f27-4810-a4f8-461376196853.png)

**Comment by szg2008** [comment]
感谢提供思路，我们跟进一下
