### ISSUE TITLE
Failed to resolve component: scroll-view for nut-infiniteloading

### ISSUE THREAD

**Issue by lingdulib** [jdf2e/nutui#1286]
Failed to resolve component: scroll-view for nut-infiniteloading 使用的taro 3.4.8，nutui 3.1.20，无法上拉加载

**Comment by Qaker** [comment]
Failed to resolve component: scroll-view
taro 3.4.9, nutui 3.1.20,  按需加载
h5端有没有什么临时的解决方案呢?

**Comment by richard1015** [comment]
v3.2.1 已修复 已发布

**Comment by seedor81** [comment]
3.2.1版本确定解决了吗，taro3.4.6  "@nutui/nutui-taro": "^3.2.1" 下h5运行 我这还是不能下拉加载

**Comment by 1zilc** [comment]
taro3.5.5 "@nutui/nutui-taro": "^3.2.2" 下h5运行问题依旧，load-more事件不会触发
