### ISSUE TITLE
taro+nutui组件中style定义的px不会转rpx

### ISSUE THREAD

**Issue by WhileSun** [jdf2e/nutui#1287]
taro+nutui+vue3开发中遇style内联样式直接写px不会自动转成rpx，导致UI大小固定了，不自适应
![image](https://user-images.githubusercontent.com/31122836/168044572-a0ad4c0b-47b1-4c56-9211-0be0ac064396.png)

- 帮忙看下如何解决，可以支持style中的px也转成rpx

**Comment by richard1015** [comment]
icon 组件支持 size="14rem"

**Comment by richard1015** [comment]
你可以根据环境去设置不同的 px or rpx单位

**Comment by SilentFlute** [comment]
> 



> 你可以根据环境去设置不同的 px or rpx单位

你的意思是使用的时候直接在style中用rpx单位而不是px单位吗?
