### ISSUE TITLE
dialog标签式写法,cancelAutoClose设置为false,不起作用.

### ISSUE THREAD

**Issue by wumeng186** [jdf2e/nutui#129]
<nut-dialog title="技能" :visible="skillShow" @close="skillShow=false" :style="{textAlign:'left'}"  cancel-btn-txt="重置" :cancel-auto-close="false" :on-cancel-btn="clearSkill" :lock-bg-scroll="true">

**Comment by Franslee** [comment]
cancelAutoClose设置为false，点击取消按钮不自动关闭对话框，我验证了一下没有问题。

**Comment by linrufeng** [comment]
感觉您的问题，版本已经修复，预计本周二更新
