### ISSUE TITLE
使用vite + vue3.2 + ts 项目按需引入一个video组件，项目打包报错，报can't find PropType 

### ISSUE THREAD

**Issue by vintonHuang** [jdf2e/nutui#1290]
## 你想知道什么？

你好，我想知道这个项目是否可以...

## 描述你考虑过的替代方案

我想...

## 其它

无

**Comment by szg2008** [comment]
试了一下，没有问题。尝试解决方案参考：

1. 更新到最新版本v3.1.20试试
2. 将node版本更新到14.5及以上
3. demo参考：https://github.com/jdf2e/nutui-demo/tree/master/vite-ts
