### ISSUE TITLE
[question]文档步骤创建模版项目按需加载问题

### ISSUE THREAD

**Issue by giamchen** [jdf2e/nutui#1291]
## 你想知道什么？

为什么按照文档的步骤创建vue3-NutUI模版项目，模版已经配置好按需加载为什么还要加这个样式文件？文档和demo我看到也没有需要加这个样式，去除的话样式就不会生效，然后按照文档设置主题也没生效，配置文件都是一样的。就是按小程序开发文档走，没有任何修改，我想知道小程序开发怎么才能正确更换主题
![image](https://user-images.githubusercontent.com/33769348/168418083-38389202-3acb-4517-be5a-b5e71c36b719.png)

## 其它
版本
![image](https://user-images.githubusercontent.com/33769348/168418363-f2362218-f5e7-41cc-8d8d-6aa2aee29c8f.png)

**Comment by richard1015** [comment]
参考这个仓库即可
https://github.com/jdf2e/nutui-demo/tree/master/pinia-taro3.4.3
