### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by okbexx** [jdf2e/nutui#13]
nuxt版本2.3.X
nutui版本2.X

在nuxt中使用报window is not defined

**Comment by Franslee** [comment]
> nuxt版本2.3.X
> nutui版本2.X
> 
> 在nuxt中使用报window is not defined

- 我们将在接下来的版本中解决这个问题。

- 作为一种临时方案，可直接在项目中引用组件目录下的vue源文件

**Comment by okbexx** [comment]
期待
