### ISSUE TITLE
[bug] 按需引入和全量引入，打包后体积没有明显变化

### ISSUE THREAD

**Issue by raythunder** [jdf2e/nutui#1303]
## 问题描述

![image](https://user-images.githubusercontent.com/2842366/169249972-0d1c3375-979d-4513-9e2b-e40d18dd7613.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
https://github.com/jdf2e/nutui-demo/tree/master/vite-ts

## 预期的行为和实际行为
预期按需引入后打包体积应该明显变小

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
目前 289  263 有差距的啊，不过内部还有优化的空间
