### ISSUE TITLE
[bug] Tabs 选项卡与Picker同时使用，第二个TabPane内触发的Picker会显示在第一个TabPane中

### ISSUE THREAD

**Issue by emorywang** [jdf2e/nutui#1304]
## 问题描述

在Tabs 选项卡内使用Picker组件，如果是在第二个（只要不是第一个）TabPane内触发的Picker内容及遮罩效果，会显示在第一个TabPane中；而触发Picker动作的TabPane内，没有任何反应可以感知（发现该现象之前我一直以为是Picker没有触发）。

## 预期的行为和实际行为
无论在哪个TabPane中使用并触发的Picker，就应该在当前TabPane展示Picker内容及遮罩

## 相关环境信息
- **操作系统**：Windows 10
- **Node 版本**：16.15.0 LTS
- **NutUI 版本**： 3.1.20
- **Vue 版本**：3.2.31
- **引用方式**：NPM

**Comment by manydots** [comment]
同样遇到这个问题，怎么解决

**Comment by richard1015** [comment]
辛苦提供一个最小复现仓库，以便于我们帮你排查问题

**Comment by emorywang** [comment]
> 辛苦提供一个最小复现仓库，以便于我们帮你排查问题

不好意思周末没查看邮件

我上传一个最小的代码包以及一小段录屏
代码包中使用的是 https://nutui.jd.com/#/component/tabs 和 https://nutui.jd.com/#/component/picker 中demo代码嵌套在一起的状态。

感谢回复和关注

[代码demo](https://emory.wang/test/taro3.zip)

[demo录屏](https://emory.wang/test/video_20220530112617.wmv)

**Comment by richard1015** [comment]
由于 picker 内部依赖popup , popup 在小程序场景无法进行 指定节点挂载， 目前的解决方案是，  
1. 把 picker 放到 tabs 同节点下
2. 设置picker visible 默认值

向这样下面使用

``` vue
<template>
  <view>
    <nut-picker v-model:visible="state.show" :columns="columns" title="城市选择" @change="change" @confirm="confirm">
    </nut-picker>
    <nut-tabs v-model="state.tab1value">
      <nut-tabpane title="Tab 1">
        Tab 1
      </nut-tabpane>
      <nut-tabpane title="Tab 2">
        <nut-cell title="请选择城市" :desc="desc" @click="()=>{state.show=true}"></nut-cell>

      </nut-tabpane>
      <nut-tabpane title="Tab 3">
        Tab 3
      </nut-tabpane>
    </nut-tabs>
  </view>
</template>
<script>
import { reactive } from "vue";
export default {
  setup() {
    const state = reactive({
      tab1value: "0",
      show: false,
    });
    return { state };
  },
};
</script>

```

**Comment by emorywang** [comment]
感谢回复，我试一下
