### ISSUE TITLE
[question] 自定义主体样式问题

### ISSUE THREAD

**Issue by chenjh-8** [jdf2e/nutui#1310]
```json
"dependencies": {
    "@babel/runtime": "^7.7.7",
    "@nutui/nutui-taro": "^3.1.20",
    "@tarojs/components": "3.4.8",
    "@tarojs/plugin-framework-vue3": "3.4.8",
    "@tarojs/plugin-html": "3.4.8",
    "@tarojs/runtime": "3.4.8",
    "@tarojs/taro": "3.4.8",
    "vue": "^3.0.0"
  }
```
![image](https://user-images.githubusercontent.com/38275824/169486018-adb8f7e9-c91c-4215-85e5-7d1eba29ba55.png)

采用的是官方提供框架，vue3 nutui，添加自定义样式后会报 **找不到依赖 @tarojs/plugin-framework-react，请先在项目中安装**

**Comment by richard1015** [comment]
请升级 最新taro 包进行创建

**Comment by richard1015** [comment]
可参考 https://github.com/jdf2e/nutui-demo/tree/master/pinia-taro3.4.3
