### ISSUE TITLE
[suggest]关于picker能否添加一个监听显示与隐藏的回调

### ISSUE THREAD

**Issue by wujingjin1** [jdf2e/nutui#1311]
我们都知道在ios端使用picker滑动时会导致外部也跟着滑动，我们需要去监听visible的状态去适配。当一个场景下我们用了三个picker那么我们要去监听三个visible。情况显然不是很理想。

我希望官方可以为开发者提供显示与隐藏的回调，开发者只需对picker进行二次封装，就可以一劳永逸。希望官方能采纳我的意见。

**Comment by yangxiaolu1993** [comment]
问题已在最新版本 3.2.3 解决，可以更新试试
