### ISSUE TITLE
[suggest] 折叠面板 collapse 能否通过设置v-model:active绑定的值，展开对应面板，传

### ISSUE THREAD

**Issue by jingyuhao1995** [jdf2e/nutui#1314]
## 你建议我们做什么？

 **### 能否通过设置v-model:active绑定的值，展开对应面板，传空折叠所有**

如果你能...

它将使...

## 其它

无

**Comment by Sakiyary** [comment]
我也有这个问题，想通过其他的回调让折叠面板收起来

**Comment by Sakiyary** [comment]
现在的v-model:active好像根本就没有让CollapseItem收起来？

**Comment by jingyuhao1995** [comment]
> 现在的v-model:active好像根本就没有让CollapseItem收起来？

好像是这样，点击折叠展开会更新到绑定的值，修改绑定的值不能响应到视图

**Comment by Ymm0008** [comment]
感谢两位的问题反馈，可否提供一下最小复现demo。 @jingyuhao1995 @Sakiyary

**Comment by Sakiyary** [comment]
版本号: 3.1.20
平台: taro 3.4.10 vue3-ts 微信小程序
````
<template>
  <nut-collapse v-model:active="state.activeName" icon="down-arrow">
    <nut-collapse-item title="111" :name="1">
      <nut-button @click="closeCollapse">收起</nut-button>
    </nut-collapse-item>
  </nut-collapse>
</template>
<script lang='ts'>
import {reactive} from "vue";
export default {
  name: "111",
  setup() {
    const state = reactive({
      activeName: []
    })
    function closeCollapse() {
      state.activeName = []
    }
    return {
      state,
      closeCollapse
    }
  }
}
</script>
<style>
</style>
````
先手动点开Collapse, 然后想通过点击按钮将其收起.

**Comment by Ymm0008** [comment]
感谢您的问题反馈，目前问题已解决，在下个版本发布~ @Sakiyary @jingyuhao1995

**Comment by jingyuhao1995** [comment]
预计哪天发版呢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jdf2e/nutui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月21日(星期二) 上午9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jdf2e/nutui] [suggest] 折叠面板 collapse 能否通过设置v-model:active绑定的值，展开对应面板，传 (Issue #1314)





 
感谢您的问题反馈，目前问题已解决，在下个版本发布~ @Sakiyary @jingyuhao1995

**Comment by Ymm0008** [comment]
@jingyuhao1995   本周五发布，v3.1.22
