### ISSUE TITLE
[bug] nut-form 节点无法接除 form-item 外的其他节点，否则失去校验逻辑

### ISSUE THREAD

**Issue by yaoyirui** [jdf2e/nutui#1317]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
看了一下源码，无限节点是支持的， `view ` 标签 在 taro h5 环境下无法 获取实时 children阶段，暂时先使用div 去解决吧

**Comment by richard1015** [comment]
月底发布时修复此bug
