### ISSUE TITLE
[bug]遮罩点击穿透

### ISSUE THREAD

**Issue by tangbl-code** [jdf2e/nutui#1318]
## 问题描述

我是在使用组件库小程序预览的时候发现的问题，一个小程序经典的原生组件层级问题，在使级联选择组件的时候发现，遮罩层出现的时候仍然可以穿透点击到下方的输入框，并获取焦点

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
目前 Taro 层暂未修复此bug

**Comment by szg2008** [comment]
Taro框架层未处理catchtap，导致点击穿透，目前可以在遮罩层弹出的时候将输入框disabled来解决。
