### ISSUE TITLE
[bug]Category组件点击右侧菜单,onchange回调函数没有返回回调数据

### ISSUE THREAD

**Issue by liliyao** [jdf2e/nutui#1321]
## 问题描述

Category组件点击右侧菜单,onchange回调函数没有返回回调数据
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
Category组件点击右侧菜单,onchange回调函数没有返回回调数据

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：14.17.0
- **NutUI 版本**： nutui-taro 3.1.20
- **Vue 版本**：3.0.0
- **引用方式**：  CDN / NPM ？npm

**Comment by ericsu138** [comment]
感觉nutui新版本就是半成品，kpi绩效项目，kpi考核完成，估计就烂尾了，nutui文档上关于category组件的示例关于右边栏的点击事件 @onChange="onChange" 方法就是传递不了参数的，不知道点击的是右边栏上的哪个项目，swiper组件也是有问题，如果是异步加载的滚动图片数据，swiper就加载不出来，高度和宽度为0了，还好研究了半天，最后发现强行通过v-if指令解决

**Comment by ericsu138** [comment]
看了一下源代码，categorypane的@click="onChange()没有传递参数，需要传一下参数sku.catId
  <div class="nut-categorypane">
    <div v-if="type == 'classify'" class="nut-categorypane__cateListRight">
      <div v-for="(item, index) in categoryChild" :key="index">
        <div class="nut-categorypane__childTitle">{{ item.catName }}</div>

        <div v-if="item.catType == 1" class="nut-categorypane__childItemList">
          <div
            v-for="(sku, key) in item.childCateList"
            class="nut-categorypane__childItem"
            :key="key"
            @click="onChange()"
          >
            <img class="nut-categorypane__childImg" :src="sku.backImg" />
            <div class="nut-categorypane__skuImg">{{ sku.catName }}</div>
          </div>
        </div>
      </div>
    </div>

**Comment by 929408183** [comment]
新版本确实很垃圾，vant3比nutui3.x好用得多，组件也更多

**Comment by richard1015** [comment]
v3.2.1 已修复 已发布
