### ISSUE TITLE
[bug]支付宝uploader组件，提示参数错误

### ISSUE THREAD

**Issue by eggtart1988** [jdf2e/nutui#1322]
## 问题描述

支付宝小程序在使用uploader组件自动上传时，因组件内uploadFile中缺少fileType参数，导致无法上传图片
![image](https://user-images.githubusercontent.com/75836451/170255443-add78e16-f114-41dc-83ce-a8da5e3ea3c0.png)

uploadFile 没有fileType属性时会报同样的错误，添加后则不会
![image](https://user-images.githubusercontent.com/75836451/170258280-b6a83de2-974a-4d90-983e-c5db66954889.png)

在使用Taro.uploadFile时 不传入fileType参数与组件错误提示相同，uploader组件源码上也无该参数
![image](https://user-images.githubusercontent.com/75836451/170257144-7dde0daf-0d46-42b8-a89d-9f147874b56f.png)

目前临时解决办法是 不使用自动上传功能，使用change事件，在事件内上传图片

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
https://github.com/Rowingboat/test-1

## 预期的行为
正常上传图片

##实际行为
提示参数错误，无法进行下一步

## 复现步骤，具体代码
正常引入组件，使用自动上传图片

## 相关环境信息
- **操作系统**：
- **Node 版本**：v12.22.5
- **NutUI 版本**： 3.1.20
- **Vue 版本**：3.0.0
- **引用方式**：  npm

**Comment by richard1015** [comment]
v3.1.22 已发布
