### ISSUE TITLE
nut-swiper高度问题

### ISSUE THREAD

**Issue by zhangjing007** [jdf2e/nutui#1323]
## 问题描述

当nut-swiper的高度超过150px的时候，ios端的小程序（vue3+taro）点击图片，轮播图立马消失不见
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码

    <nut-swiper :init-page="swiperPage" :loop="true" @change="change">
      <nut-swiper-item v-for="item in data.images" :key="item">
        <template v-if="matchFileSuffixType(item) === 'image'">
          <img :src="data.staticHost + item" alt="" @click="preView(data)"/>
        </template>
        <nut-video v-else :source="item" :options="{
            controls: true,
          }">
        </nut-video>
      </nut-swiper-item>
    </nut-swiper>

## 相关环境信息
- **操作系统**：mac os
- **Node 版本**：16.15.0
- **NutUI 版本**： 3.1.18
- **Vue 版本**：3.0.0
- **引用方式**：  NPM

**Comment by szg2008** [comment]
下周一发版，更新到最新版本试试
