### ISSUE TITLE
[bug]nut-swiper-item组件中ts提示报错

### ISSUE THREAD

**Issue by whoopsHzh** [jdf2e/nutui#1324]
## 问题描述
nut-swiper-item组件中ts提示报错

## 最小可复现仓库
![image](https://user-images.githubusercontent.com/32846446/170399416-7ae74464-87c9-4fe2-8919-3c30b3cd4570.png)
![image](https://user-images.githubusercontent.com/32846446/170399442-ee6e8275-a1b4-4f70-8d9a-bfc20f1e7dfc.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by szg2008** [comment]
已修复，下周一发版

**Comment by whoopsHzh** [comment]
> 已修复，下周一发版

thx
