### ISSUE TITLE
nut-input的clearable点击报错、nut-textarea的属性autosize无效

### ISSUE THREAD

**Issue by waynehoo** [jdf2e/nutui#1327]
## 问题描述

1. nut-input组件的clearable 点击无效，报错：VM1747 WAService.js:2 TypeError: Cannot read property '__treeManager__' of undefined
2. nut-textarea组件，属性autosize(高度自定义，拉伸)无效，添加autosize属性后，整个textarea不显示。

## 相关环境信息
按官网初始化的项目，npm run dev:weapp后在微信小程序打开dist文件。
![image](https://user-images.githubusercontent.com/40262229/170627560-8645b677-00ff-413e-8c07-f4fe392613d2.png)

- **操作系统**：windows
- **Node 版本**：v16.15.0
- **NutUI 版本**： 3.1.8
- **Vue 版本**：3.0.0
- **引用方式**：   模板方式如上图（npm install）

**Comment by rocwong-cn** [comment]
请问有进展吗？

**Comment by Ymm0008** [comment]
@rocwong-cn @waynehoo  textarea的问题已经处理，请更新到nutui最新版本，进行使用。

**Comment by unclemeric** [comment]
你好，微信小程序上这个组件不能自动增高这个bug怎么解决，而且给的官网demo上那个例子在手机上运行也有问题呢
