### ISSUE TITLE
swiper 无法触发内部元素的点击事件

### ISSUE THREAD

**Issue by treasureMoment** [jdf2e/nutui#133]
swiper 无法触发内部元素的点击事件

**Comment by Franslee** [comment]
请 @wangnan41 关注

**Comment by richard1015** [comment]
https://cn.vuejs.org/v2/api/#v-on

click.native

**Comment by 490626721** [comment]
使用click.native任然无法解决

**Comment by huysh3** [comment]
@490626721 
加多个 `:is-preventDefault="true"`

**Comment by MuGuiLin** [comment]
在nut-swiper标签中，加上  :is-preventDefault="false" 才可以
例如：
`<nut-swiper
      height="240"
      auto-play="3000"
      :init-page="state.page"
      :is-preventDefault="false"
      :pagination-visible="true"
      pagination-color="#DB56EE"
    >`

**Comment by hainuo** [comment]
> @490626721 加多个 `:is-preventDefault="true"`



> 在nut-swiper标签中，加上 :is-preventDefault="false" 才可以 例如： `<nut-swiper height="240" auto-play="3000" :init-page="state.page" :is-preventDefault="false" :pagination-visible="true" pagination-color="#DB56EE" >`

我发现最新的 4.3 版本  已经更改了 设置参数         :is-prevent-default	="false"
