### ISSUE TITLE
[bug]在微信小程序webview容器下H5，nut-uploader点击无法响应，无法弹起拍照或选择图片按钮栏

### ISSUE THREAD

**Issue by bin-bin-6** [jdf2e/nutui#1336]
## 问题描述

在微信小程序webview容器下H5，nut-uploader点击无法响应，无法弹起拍照或选择图片按钮栏
官网demo有使用input[type='file']，然而当前版本使用后并没有input[type='file']

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
    <nut-uploader
        :maximize="1024 * 10240"
        :headers="headers"
        maximum = "3"
        :capture="true"
        :disabled="false"
        @oversize="onOversize"
        v-model:file-list="leaseContractInfoList"
        :url="taskUploadFile"
        @success="(res) => uploadSuccess(res, 1)"
        @delete="
          ({ files, fileList, index }) =>
            deleteFunc({ files, fileList, index }, 1)
        "
        @file-item-click="fileItemClick"
    >
    </nut-uploader>

## 预期的行为和实际行为
在微信小程序webview容器下的H5，点击nut-uploader可弹起拍照或选择图片按钮栏。

## 复现步骤，具体代码
1、运行h5
2、在小程序webview下运行。

## 相关环境信息
- **操作系统**：
- **Node 版本**：v16.15.0
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息 3.1.20
- **Vue 版本**：Vue3
- **引用方式**：  CDN / NPM ？npm

**Comment by richard1015** [comment]
请提供完整的信息， nutui 包名及版本号

**Comment by bin-bin-6** [comment]
"@babel/runtime": "^7.7.7",
  "@nutui/nutui-taro": "^3.1.20",
  "@tarojs/components": "3.4.10",
  "@tarojs/plugin-framework-vue3": "3.4.10",
  "@tarojs/plugin-html": "3.4.10",
  "@tarojs/runtime": "3.4.10",
  "@tarojs/taro": "3.4.10",
  "path": "^0.12.7",
  "qrcodejs2": "^0.0.2",
  "vue": "^3.0.0"

**Comment by bin-bin-6** [comment]
> 请提供完整的信息， nutui 包名及版本号

"@babel/runtime": "^7.7.7",
    "@nutui/nutui-taro": "^3.1.20",
    "@tarojs/components": "3.4.10",
    "@tarojs/plugin-framework-vue3": "3.4.10",
    "@tarojs/plugin-html": "3.4.10",
    "@tarojs/runtime": "3.4.10",
    "@tarojs/taro": "3.4.10",
    "path": "^0.12.7",
    "qrcodejs2": "^0.0.2",
    "vue": "^3.0.0",
    "vue-image-upload-resize": "^2.3.0"

**Comment by bin-bin-6** [comment]
***@***.***/runtime": "^7.7.7",
***@***.***/nutui-taro": "^3.1.20",
***@***.***/components": "3.4.10",
***@***.***/plugin-framework-vue3": "3.4.10",
***@***.***/plugin-html": "3.4.10",
***@***.***/runtime": "3.4.10",
***@***.***/taro": "3.4.10",
"path": "^0.12.7",
"vue": "^3.0.0"



***@***.***
 
发件人： richard1015
发送时间： 2022-05-30 13:37
收件人： jdf2e/nutui
抄送： bin-bin-6; Author
主题： Re: [jdf2e/nutui] [bug]在微信小程序webview容器下H5，nut-uploader点击无法响应，无法弹起拍照或选择图片按钮栏 (Issue #1336)
请提供完整的信息， nutui 包名及版本号
―

**Comment by richard1015** [comment]
自测 ，没问题 ，请升级至最新 版本3.1.22-beta.2 尝试一下

**Comment by kevinlvhsl** [comment]
每次上报无反应，就是关闭issue ？  安卓手机上小程序版也无反应
