### ISSUE TITLE
SearchBar 无法自定义Icon大小

### ISSUE THREAD

**Issue by treasureMoment** [jdf2e/nutui#134]
SearchBar 无法自定义Icon大小 添加参数Icon 大小设置

**Comment by Franslee** [comment]
可以通过自定义样式解决

**Comment by treasureMoment** [comment]
看了源码。固定大小。然后用的svg,难道要用transform么。不太灵活。还有就是searchBar 点击输入法的完成 可能会触发页面的刷新 触发概率多在首次加载模块

**Comment by Franslee** [comment]
下一个版本增加props控制Icon组件

**Comment by Franslee** [comment]
请试试新版
