### ISSUE TITLE
[suggest] nut-input 想要一个input插槽

### ISSUE THREAD

**Issue by zehuichan** [jdf2e/nutui#1341]
## 你建议我们做什么？

 nut-input 想要一个input插槽

**Comment by szg2008** [comment]
可以详细描述一下你的诉求，我们好跟进处理，🙏

**Comment by zehuichan** [comment]
[想要这样的](https://vant-contrib.gitee.io/vant/#/zh-CN/field#slots)

```
<nut-input label="自定义input插槽">
  <template #input>// 自定义输入框，使用此插槽后，与输入框相关的属性和事件将失效
    <v-segmented v-model="dataForm.checked" :columns="checked" />
  </template>
</nut-input>
```

**Comment by zehuichan** [comment]
看了下commit log，只是在form-item支持，但是form-item却不能单独使用，而我却需要nut-input组件新增input插槽的

**Comment by ailululu** [comment]
> 下提交日志，只是在-item 支持，却不能在form-item 中使用，而我却需要nut-input 组件添加input 单独的输入表单的

v3.1.22 已新增改插槽

**Comment by chawson** [comment]
鸡肋！为了实现input插槽，导致整个nut-input几乎失去了意义 leftIcon和rightIcon直接被干掉了
