### ISSUE TITLE
[bug]文档示例，少写了引入的依赖

### ISSUE THREAD

**Issue by v2-lab** [jdf2e/nutui#1342]
## 问题描述

https://nutui.jd.com/#/component/timeselect

这里还需要引入  
Icon 和  OverLay 组件

```
import {
  TimeSelect,
  TimePannel,
  TimeDetail,
  Popup,
  Icon,
  OverLay,
} from "@nutui/nutui-taro";
```

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by szg2008** [comment]
感谢反馈，已补充～
