### ISSUE TITLE
[bug] tabs 3.1.21 异步加载数据的时候还是不能正常自适应高度

### ISSUE THREAD

**Issue by juzijun2020** [jdf2e/nutui#1344]
## 问题描述
虽然在3.1.21里面新增了autoHeight参数，但是在异步加载的时候还是不能正常自适应高度。

## 预期的行为和实际行为
预期是高度自适应，但实际上只有第一个tab是自适应的，其他tab无法正常显示

## 复现步骤，具体代码

在官方示例代码 [数据异步渲染 3s ](https://github.com/jdf2e/nutui/blob/next/src/sites/mobile-taro/vue/src/nav/pages/tabs/index.vue) 加上` :auto-height="true"`参数即可复现

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 3.1.21
- **Vue 版本**：
- **引用方式**：  NPM

**Comment by richard1015** [comment]
设置 auto-height   必须设置 pane-key

**Comment by richard1015** [comment]
3.1.22 已发布
