### ISSUE TITLE
[bug]nut-swiper图片显示不完整

### ISSUE THREAD

**Issue by mxlt02** [jdf2e/nutui#1345]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
https://nutui.jd.com/#/component/swiper
官方文档实例中就存在此问题,  设置外边距时 图片右侧隐藏了一小部分, 无外边距时不存在此问题

## 相关环境信息
- **操作系统**：Windows 10
- **Node 版本**：16.15.0
- **NutUI 版本**： 3.1.20
- **Vue 版本**：3
- **引用方式**：  NPM

**Comment by wen-bug** [comment]
怎么解决的我官网示例两个页面一个正常一个缺失，css都没改过
