### ISSUE TITLE
组件字段不显示

### ISSUE THREAD

**Issue by Jacky-m** [jdf2e/nutui#135]
nut-tab 组件，使用cdn引用，在设置了tabTitle参数时，页面不显示设置的值

**Comment by scwlwj** [comment]
遇到了同样的问题

**Comment by richard1015** [comment]
Prop 的大小写 (camelCase vs kebab-case)
HTML 中的特性名是大小写不敏感的，所以浏览器会把所有大写字符解释为小写字符。这意味着当你使用 DOM 中的模板时，camelCase (驼峰命名法) 的 prop 名需要使用其等价的 kebab-case (短横线分隔命名) 命名
