### ISSUE TITLE
[bug] 小程序下 menu 组件无法手势滑动下拉

### ISSUE THREAD

**Issue by sickeeer** [jdf2e/nutui#1353]
## 问题描述
小程序下 menu 组件无法手势滑动下拉

## 最小可复现仓库
官方小程序 demo

## 预期的行为和实际行为
预期：移动端可以手势下滑，
实际：移动端无法下滑

## 复现步骤，具体代码
官方小程序 demo

## 相关环境信息
- **操作系统**：
- **Node 版本**：v14.18.1
- **NutUI 版本**： 3.1.21
- **Vue 版本**：3.0.0
- **引用方式**：  yarn

**Comment by szg2008** [comment]
参考 #1355

**Comment by sunWhereCode** [comment]
解决了吗
