### ISSUE TITLE
[bug]Cascader 级联选择器 小程序端内容超出无法滚动

### ISSUE THREAD

**Issue by Flamessea** [jdf2e/nutui#1355]
## 问题描述
内容超出高度时，小程序端出现滚动条，但是内容无法手势滑动

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
希望小程序端可以手势滑动内容列表，结果小程序端却滑动不了，小程序开发工具上只有鼠标滚轮可以滚动，但是手势滑动不行

## 复现步骤，具体代码

![image](https://user-images.githubusercontent.com/42063891/172193386-6e022057-9aaa-4a15-89b4-21dd0e4fe8f2.png)

## 相关环境信息
- **操作系统**：ios
- **Node 版本**：16.15.0
- **NutUI 版本**： 3.1.21
- **Vue 版本**：3.0.0
- **引用方式**： npm

**Comment by szg2008** [comment]
参考#1343

**Comment by Flamessea** [comment]
> 参考#1343

真棒

**Comment by SimboDu123** [comment]
这个问题解决了吗？

**Comment by szg2008** [comment]
> 这个问题解决了吗？

参考https://github.com/jdf2e/nutui/issues/1343

**Comment by sunWhereCode** [comment]
解决了吗
