### ISSUE TITLE
[bug] vite打包错误 ERROR  [vite]: Rollup failed to resolve import

### ISSUE THREAD

**Issue by hbalxzdl** [jdf2e/nutui#1356]
## 问题描述

打包出现错误：

ERROR  [vite]: Rollup failed to resolve import "@nutui/nutui/dist/packages/Button/index.scss" from "src/main.js".                     19:27:54
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

## 相关环境信息
- **操作系统**：Linux
- **Node 版本**：16..15
- **NutUI 版本**： 3.1.21
- **Vue 版本**：3.2.25
- **引用方式**：  yarn

**Comment by richard1015** [comment]
vite config 按需加载重写一下  NutuiResolve
```
function NutuiResolve(): Lib {
  return {
    libraryName: '@nutui/nutui',
    libraryNameChangeCase: 'pascalCase',
    resolveStyle: (name) => {
      return `@nutui/nutui/dist/packages/${name.toLowerCase()}/index.scss`
    },
  }
}

```

**Comment by beautycss** [comment]
> vite config 按需加载重写一下 NutuiResolve
> 
> ```
> function NutuiResolve(): Lib {
>   return {
>     libraryName: '@nutui/nutui',
>     libraryNameChangeCase: 'pascalCase',
>     resolveStyle: (name) => {
>       return `@nutui/nutui/dist/packages/${name.toLowerCase()}/index.scss`
>     },
>   }
> }
> ```

现在2024年了，使用vite4还是碰到这个问题。
使用重写的方法也不行，会提示：
```
App.vue:53 [Vue warn]: Failed to resolve component: nut-button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <App>
```
能不能把auto-import-resolver这个包修复下，需要修改成如下：
```
if (importStyle === "sass") {
    style = `${packageName}/dist/packages/${componentName.toLowerCase()}/index.scss`;
  }
```

**Comment by eiinu** [comment]
> > vite config 按需加载重写一下 NutuiResolve
> > ```
> > function NutuiResolve(): Lib {
> >   return {
> >     libraryName: '@nutui/nutui',
> >     libraryNameChangeCase: 'pascalCase',
> >     resolveStyle: (name) => {
> >       return `@nutui/nutui/dist/packages/${name.toLowerCase()}/index.scss`
> >     },
> >   }
> > }
> > ```
> 
> 按这个修改是解决了。 但是现在2024年了，vite4还是有这个问题，能不能把auto-import-resolver这个包修复下。

这个 issue 是 NutUI v3.x 版本上的，使用的是 [vite-plugin-style-import](https://github.com/anncwb/vite-plugin-style-import) 插件做样式的按需引入。
现在的 v4.x 版本推荐使用的是另外一个 `unplugin-vue-components` 插件，使用的配置是 `auto-import-resolver`，和这个 issue 应该没有关系。
你说的具体是什么问题呢？

**Comment by beautycss** [comment]
> > > vite config 按需加载重写一下 NutuiResolve
> > > ```
> > > function NutuiResolve(): Lib {
> > >   return {
> > >     libraryName: '@nutui/nutui',
> > >     libraryNameChangeCase: 'pascalCase',
> > >     resolveStyle: (name) => {
> > >       return `@nutui/nutui/dist/packages/${name.toLowerCase()}/index.scss`
> > >     },
> > >   }
> > > }
> > > ```
> > 
> > 
> > 按这个修改是解决了。 但是现在2024年了，vite4还是有这个问题，能不能把auto-import-resolver这个包修复下。
> 
> 这个 issue 是 NutUI v3.x 版本上的，使用的是 [vite-plugin-style-import](https://github.com/anncwb/vite-plugin-style-import) 插件做样式的按需引入。 现在的 v4.x 版本推荐使用的是另外一个 `unplugin-vue-components` 插件，使用的配置是 `auto-import-resolver`，和这个 issue 应该没有关系。 你说的具体是什么问题呢？

我现在使用的版本：
* nodejs: 18.19.0;
*  Vue: 3.3.13；
* NutUI: 4.2.7;
* Vite: 4.5.1;


问题说明：
在引入NutUI4之前，项目启动正常，页面展示正常，在按需引入NutUI4后页面报错：
```
Failed to resolve import
"@nutui/nutui/dist/packages/button/style" from
...
```
我最终修改本地的`@nutui/auto-import-resolver`解决了，我还是说一下问题和过程，看是否需要修改文档和修复插件。

重现步骤：
1. 严格按照官网文档引用`unplugin-vue-components/vite`和`@nutui/auto-import-resolver`两个插件来按需引入NutUI4。
![截屏2024-01-11 09 39 14](https://github.com/jdf2e/nutui/assets/16473160/b8f791b6-f811-4252-b503-740558fd9c8b)

2. 在页面上仅仅写了一个按钮`<nut-button type="primary">Primary</nut-button>`，就提示下图错误。
![image](https://github.com/jdf2e/nutui/assets/16473160/38893902-b218-4c53-a96a-79efdb4318ab)


3. 然后我去看了插件的文档，加了一个`importStyle: 'sass'`，还是报跟上图一样的错误。

4. 我使用了上面`vite config 按需加载重写一下 NutuiResolve`方法，报错是：
```
App.vue:53 [Vue warn]: Failed to resolve component: nut-button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <App>
```

5. 我尝试直接修改本地的`@nutui/auto-import-resolver/dist/index.js`文件第11行后，问题解决，改动如下：
```
if (importStyle === "sass") {
    - style = `${packageName}/dist/packages/${componentName.toLowerCase()}/style`;
    + style = `${packageName}/dist/packages/${componentName.toLowerCase()}/index.scss`;
  }
```

总结：
1. NutUI官网文档的vite部分里是不是要加入`importStyle: 'sass'`；
2. `auto-import-resolver`看是不是要修改下。

**Comment by eiinu** [comment]
> 我现在使用的版本：
> 
> * nodejs: 18.19.0;
> * Vue: 3.3.13；
> * NutUI: 4.2.7;
> * Vite: 4.5.1;
> 
> ......
> 
> 1. NutUI官网文档的vite部分里是不是要加入`importStyle: 'sass'`；
> 2. `auto-import-resolver`看是不是要修改下。

12、目前包内提供了 css 和 scss 两种样式文件，`auto-import-resolver` 默认会导入 css 样式文件，参考 [代码](https://github.com/jdf2e/nutui/blob/89747d8c17826b8e2c6a43a9c62ee846711111e2/packages/nutui-auto-import-resolver/src/index.ts#L37C3-L37C3)，所以第 2 步的报错信息中显示的文件路径是不符合预期的。应该是 `....../style/css` 而不是 `....../style`。
3、增加了 `importStyle: sass` 的配置后，依然报错显示找不到对应的文件。但是这个对应的文件在包中是存在的，可以参考这个路径：[button/style/index.mjs](https://github.com/jdf2e/nutui/blob/pkg/publish/nutui/dist/packages/button/style/index.mjs)。
4、不能使用该 issue 下的配置，因为是两个完全不同的插件。
5、直接修改 auto-import 配置为 `....../index.scss` 也是不行的，这样只会引入当前组件的样式，缺少其依赖组件的样式。

补充：这里是 vite 项目的 [demo](https://github.com/jdf2e/nutui-demo/tree/dev/nutui4-vue/vite-ts) 仓库，里面使用的 vite 5.0 版本没有发现类似问题。我使用 4.5.1 版本进行测试也没有发现问题。

建议检查下 `node_modules/@nutui/nutui` 包中是否真的有对应的文件，找不到文件路径的原因我猜可能是：
项目中有一些特殊配置使得 `....../style` 这种省略了 js/ts 文件后缀的 import 方式无法成功命中 `....../style/index.mjs` 文件。比如修改了 vite 中的 [resolver.extensions](https://cn.vitejs.dev/config/shared-options.html#resolve-extensions) 配置项。

如果依然有问题，可以新开一个 issue，提供可复现仓库，我们会随时跟进
