### ISSUE TITLE
@click事件不能被监听到，只有@tap事件可以被监听

### ISSUE THREAD

**Issue by XiangBo-EvanZuo** [jdf2e/nutui#1358]
## 小程序组件的click事件不能被监听到，只有tap事件

<img width="774" alt="image" src="https://user-images.githubusercontent.com/49554656/172329240-ea59acee-59de-40ad-a0fb-a8490ad178f1.png">
奇怪的是v-model是可以的

大佬们看一下是怎么回事

## 版本如下
    "@nutui/nutui-taro": "^3.1.21",
    "@tarojs/components": "3.2.13",
    "@tarojs/runtime": "3.2.13",
    "@tarojs/taro": "3.2.13",
    "babel-plugin-import": "^1.13.5",
    "vue": "^3.2.36",
    "vuex": "^4.0.0-beta.4"
## 其他
系统：mac

**Comment by szg2008** [comment]
需要配置 @tarojs/plugin-html。具体可参考 https://github.com/jdf2e/nutui-demo/tree/master/taro3

**Comment by XiangBo-EvanZuo** [comment]
@szg2008 感谢，已经搞定了。我刚才找了一个能用的项目，那里面就有@tarojs/plugin-html。现在我把项目迁移到那边儿去了。呜呜呜。
刚入taro坑就遭到了非人的折磨？？？
回头看看uni，我又露出了满意的smile。

**Comment by PythonWongXb** [comment]
closed
