### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by chenzhizhuo** [jdf2e/nutui#136]
//引入如下代码：  客户端渲染正常。  服务端渲染： ReferenceError: document is not defined

import { Dialog} from '@nutui/nutui'
Dialog.install(Vue);

**Comment by Franslee** [comment]
安装babel插件@nutui/babel-plugin-separate-import 了吗？

**Comment by chenzhizhuo** [comment]
安装了。ssr run error:
package.json
.babelrc



------------------ 原始邮件 ------------------
发件人: "Frans Lee"<notifications@github.com>;
发送时间: 2019年7月9日(星期二) 晚上6:05
收件人: "jdf2e/nutui"<nutui@noreply.github.com>;
抄送: "天涯海角"<1024932466@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jdf2e/nutui] document is not defined (#136)




安装babel插件@nutui/babel-plugin-separate-import 了吗？

**Comment by richard1015** [comment]
请升级最新版本，并且参考demo
 https://github.com/richard1015/nutui-demo
