### ISSUE TITLE
picker组件选择无效

### ISSUE THREAD

**Issue by ylm159** [jdf2e/nutui#1360]
picker这个组件在小程序上如果快速滑动后点击确认 返回的结果不对， 因为好像选择有延迟

真机上会时不时的复现此问题，微信开发者工具不会有此问题

**Comment by emorywang** [comment]
我也发现了这个问题，具体表现为：

picker打开选项后，如果快速滑动选项后即点击确认，则获取到的值并非是滑动目标值而是起始值；但是再次打开picker时会发现，picker的状态的确已经更改到目标值。

如果在滑动时，等待滑动效果完全结束再点击确定，则获得到的值是正确的。
