### ISSUE TITLE
[bug]小程序中使用input ios获取验证码后自动填写验证码 验证码显示正常但传递参数的验证码会少一位

### ISSUE THREAD

**Issue by Qirui-pig** [jdf2e/nutui#1362]
## 问题描述

使用nut-input ios获取验证码后自动填写验证码 4位验证码显示正常但传递参数的验证码会少一位，使用原生input不会出现这种问题
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
可以试下单独的input 在其他地方发送验证码后 点击input 会发现4位验证码会自动删一位 或者显示正常但是具体绑定数值少一位

## 相关环境信息
- **操作系统**：windows10
- **Node 版本**：16.14.2
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息@nutui/nutui-taro@^3.1.8
- **Vue 版本**：3.2.33
- **引用方式**：  CDN / NPM ？NPM

**Comment by ailululu** [comment]
安装下最新版@nutui/nutui-taro@3.1.22，还出现这个问题辛苦贴下代码
