### ISSUE TITLE
函数式调用 Dialog 出错

### ISSUE THREAD

**Issue by flmbbb** [jdf2e/nutui#1364]
## 问题描述

当用函数式调用Dialog弹窗时，不管在写代码，还是运行起来多会出错
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
![image](https://user-images.githubusercontent.com/17305384/172524881-7b2f4e91-dfbd-4676-88b6-c6fa982b061b.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by szg2008** [comment]
更新到3.1.21版本试试呢
