### ISSUE TITLE
[suggest]Menu MenuItem可以增加一个自定义类名：titleClass吗

### ISSUE THREAD

**Issue by SimboDu123** [jdf2e/nutui#1366]
## 你建议我们做什么？

现在想给Menu-item__title动态增加一个className 来实现自定义样式

如果你能...
Menu可以增加一个自定义类名
它将实现自定义样式

**Comment by yangjinjun3** [comment]
您好，确认下 是要给 nut-menu__title 这个加自定义样式类名吗？

**Comment by SimboDu123** [comment]
> 
对的。比如当选中的值，标题虽然替换，从视觉上没有颜色这类变化不太明显。

**Comment by yangjinjun3** [comment]
已添加，下个版本会发布，敬请期待！
