### ISSUE TITLE
[bug]address实机无法滑动城市列表

### ISSUE THREAD

**Issue by pp-tang** [jdf2e/nutui#1367]
## 问题描述
使用nutui版本 3.1.21中  address组件， 在微信小程序开发工具中没有问题， 实机调试中就会出现无法滑动城市列表的情况，滚动条也没有出现

## 复现步骤，具体代码
只要在address组件中绑定的参数 province 放入很多数据即可复现

## 相关环境信息
- **操作系统**：win10
- **NutUI 版本**： 3.1.21
- **Vue 版本**：VUE3
- **引用方式**：   NPM

**Comment by szg2008** [comment]
参考#1343

**Comment by pp-tang** [comment]
> 参考#1343

address 并没有实现 lock-scroll

**Comment by pp-tang** [comment]
这个应该是个变动导致的bug， 有的人说 3.1.20 并没有这个问题

**Comment by pp-tang** [comment]
计划在 3.1.22 修复 time-select， detail，panel  无法滚动的问题，但是 没有adress

**Comment by szg2008** [comment]
这个是popup的问题。看一下#1343的解决方案。

**Comment by Flamessea** [comment]
> 这个应该是个变动导致的bug， 有的人说 3.1.20 并没有这个问题

我也遇到这样的问题，改成用 3.1.20，但是3.1.20版本 nut-cascader 又会出现另外的滚动问题，心有点累，决定自己造轮子了
