### ISSUE TITLE
[bug]Signature组件TypeError: Cannot read properties of null (reading 'getContext')

### ISSUE THREAD

**Issue by 1zilc** [jdf2e/nutui#1368]
## 问题描述

无法使用 Signature 组件，好像是组件内部没有获取到canvas dom

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

https://github.com/1zilc/nut-signature-repo
## 预期的行为和实际行为
预期行为：
正常初始化组件，并且可以使用签名功能

实际行为：
组件初始化报错

## 复现步骤，具体代码
```ts
# 组件注册
import { Signature } from '@nutui/nutui-taro';

App.use(Signature);
```
```vue
# 使用组件
<template>
  <view class="index">
    <nut-signature />
  </view>
</template>
```

报错信息：
<img width="758" alt="image" src="https://user-images.githubusercontent.com/44715458/172774964-ff3c3194-f09e-45c0-a6cb-59391d6a8f41.png">

## 相关环境信息
- **操作系统**：MacOS 12.3
- **Node 版本**：v16.15.0
- **NutUI 版本**：3.1.21
- **Vue 版本**：3.2.37
- **引用方式**： NPM

**Comment by 1zilc** [comment]
如果是用 `@nutui/nutui` 里面的Signature 组件，在h5 dev环境能正常使用，h5 prod环境下打包后也会报这个错

**Comment by Ymm0008** [comment]
问题已修复，将在下个版本发布，感谢您的反馈。 @1zilc

**Comment by hbalxzdl** [comment]
升级到了v3.2 还是同样的问题
