### ISSUE TITLE
[suggest] 有 icon 的组件能否提供一个 icon 插槽？

### ISSUE THREAD

**Issue by allenou** [jdf2e/nutui#1372]
## 你建议我们做什么？

现在...

有些组件（Steps、Menu、Cell 等）虽提供了自定义 icon 功能，但只能使用 nut-ui 内置的 icon font，无法使用外部的 icon font。

它将使...

若能提供插槽，用户可真正的自定义 icon（可根据需要使用使用自己的 icon font 或 image icon）

## 其它

无

**Comment by richard1015** [comment]
近期我们加一下，感谢反馈



font-class-name、
class-prefix

**Comment by 929408183** [comment]
> 近期我们加一下，感谢反馈
> 
> font-class-name、 class-prefix

希望在nutui3.x其他组件中多扩展插槽，为开发者提供更灵活的使用，谢谢🤞 @richard1015

**Comment by richard1015** [comment]
v3.2.1 已发布

**Comment by emorywang** [comment]
非常感谢辛苦付出，最近正好想用到menu的自定义icon，没想到没过几天就更新版本新增插槽，再次感谢！
