### ISSUE TITLE
[bug]在编译阶段的sass引入variables.scss文件导致编译后页面样式文件增大重复

### ISSUE THREAD

**Issue by vipterry** [jdf2e/nutui#1375]
## 问题描述

由于在编译阶段增加的nutui全局变量文件variables.scss，此文件最后一行引入动画变量样式，导致编译后每一个页面的样式文件均存在此动画样式，大大增加原本已捉襟见肘的2M小程序空间。
![image](https://user-images.githubusercontent.com/7145196/173269207-45d8094c-4b5a-4737-a790-b00e9e9de5a6.png)
![image](https://user-images.githubusercontent.com/7145196/173269418-c7d33d41-c233-4730-9352-324e2fa98db1.png)

## 最小可复现仓库
> 没有创建复现代码，每个项目设置以下参数均如此。
![image](https://user-images.githubusercontent.com/7145196/173269469-656d3084-925f-4956-a2e0-b8a5fa844e35.png)

## 预期的行为和实际行为
建议将“@import './animation/index”作为项目自行全局引入即可

## 相关环境信息
- **操作系统**：MacOS
- **Node 版本**：v14.19.3
- **NutUI 版本**： v3.1.21
- **Vue 版本**：^3.2.37
- **引用方式**： npm

**Comment by WhileSun** [comment]
楼主有解决方案了吗

**Comment by vipterry** [comment]
> 楼主有解决方案了吗

只能临时解决，修改到nutui的源码了，需要修改以下三个：
1、nutui源码部分：找到 node_modules/@nutui/nutui-taro/dist/styles/variables.scss，移除最后一行：“@import './animation/index';”【图一】
2、Taro编译部分：找到config/index.js文件，sass.data暂时注释掉，在sass.resource数组内增加一行：'../node_modules/@nutui/nutui-taro/dist/styles/variables.scss' 【图二】
3、项目代码部分：在src/app.scss第一行增加引入#1注释的部分：@import '~@nutui/nutui-taro/dist/styles/animation/index.scss' 【图三】

![image](https://user-images.githubusercontent.com/7145196/173810930-36ee8824-a7e9-4878-a0a7-7da8c063118e.png)
![image](https://user-images.githubusercontent.com/7145196/173811094-e9dee421-0d84-417e-a611-89f2bcfd07a6.png)
![image](https://user-images.githubusercontent.com/7145196/173811162-7cf51802-f4ac-4601-8e97-5ae2e88d2dcb.png)

**Comment by richard1015** [comment]
可以先采用 测试包 v3.2.3-beta.1  https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.3-beta.1

正式包  v3.2.3 本周四 9.29~30 发布
