### ISSUE TITLE
nutui版本为3.1.21签名组件开发环境可以正常使用，打包后报错无法进行签名[bug]

### ISSUE THREAD

**Issue by xingwuwjn** [jdf2e/nutui#1376]
## 问题描述

在@nutui/nutui": "3.1.21" 版本下测试环境签名组件可以正常签名，如图：
<img width="888" alt="image" src="https://user-images.githubusercontent.com/25215148/173302597-c2dee6e0-0b6c-48d8-80c8-c574ec8fe478.png">
在打包后报：
<img width="558" alt="image" src="https://user-images.githubusercontent.com/25215148/173302749-f90543bb-56ca-479b-9e2b-f577723c6a90.png">
导致无法进行签名，无法滑动。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
https://github.com/xingwuwjn/nutuitest

## 相关环境信息
- **操作系统**：
- macos
- **Node 版本**：
- v14.16.1
- **NutUI 版本**：
- @nutui/nutui 3.1.21
- **Vue 版本**：
- ^3.2.36
- **引用方式**：  CDN / NPM ？
- npm

**Comment by xingwuwjn** [comment]
@nutui/nutui

**Comment by richard1015** [comment]
v3.2.1  已发布
