### ISSUE TITLE
[bug] v2 package dep

### ISSUE THREAD

**Issue by limitless-loong** [jdf2e/nutui#1377]
## 问题描述

nutui v2分支的 package.json 文件中 "@babel/plugin-proposal-object-rest-spread"、"@babel/plugin-syntax-jsx"、"@babel/plugin-transform-runtime"、"@commitlint/cli"、"@commitlint/config-conventional" 、"babel-plugin-istanbul" 和 "standard-version" 等依赖安装位置不正确，应为开发依赖，现为项目依赖，导致下载依赖锁文件会出现上述开发依赖。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
预期的行为：下载依赖锁文件不会出现开发依赖。
实际行为：下载依赖锁文件会出现开发依赖。

## 相关环境信息
- **操作系统**：window
- **Node 版本**：16.14.1
- **NutUI 版本**： 2.3.9
- **Vue 版本**：2.6.11
- **引用方式**： NPM

**Comment by richard1015** [comment]
v2.3.10 已修复
