### ISSUE TITLE
countdown 存在BUG

### ISSUE THREAD

**Issue by treasureMoment** [jdf2e/nutui#138]
countdown 同时设置start 和end ,看源码。初始 设置了一个difftime 是对的。但是后面每秒都把这个值加进去。会导致 不到剩余时间 就已经结束。

**Comment by Franslee** [comment]
@famanoder

**Comment by famanoder** [comment]
这里是针对从实际的情况出发，有些手机浏览器里面，滑动页面时会将定时器暂停，导致倒计时显示有误差，所以需要初始时计算`diffTime`，在定时器里减去的时间始终以当前时间加`diffTime`为准，这样并不会导致不到剩余时间就已结束，相反，能在一定程度上减少误差；

**Comment by treasureMoment** [comment]
自己测试下/传入start和end .会导致剩余事件变多

**Comment by treasureMoment** [comment]
还有就是考虑传入start 和end 因为是已服务器的时间为准的。再切入手机的本地时间。差异会存在。
