### ISSUE TITLE
[bug]小程序端list组件，顶部快速上下滑动时白屏

### ISSUE THREAD

**Issue by jaqen404** [jdf2e/nutui#1382]
## 问题描述
小程序端list组件，顶部快速上下滑动时白屏

## 预期的行为和实际行为
预期滑到顶部时正常渲染
![WechatIMG601](https://user-images.githubusercontent.com/6075540/173509871-cae522a8-ff12-46b5-89a3-d96f1ffc0f11.jpeg)
实际顶部几项会经常出现渲染不出来
![WechatIMG602](https://user-images.githubusercontent.com/6075540/173509907-d09a6d24-92e8-431a-812f-cf1b64484472.jpeg)
![WechatIMG600](https://user-images.githubusercontent.com/6075540/173509924-b95bc86c-9d65-4a3d-9e5e-162a39e7c352.jpeg)

## 复现步骤，具体代码
先从顶部往下滑动一段，再快速上划

## 相关环境信息
- **操作系统**：Android11     miui 12.0.5
- **NutUI 版本**： 官方小程序示例（官网二维码扫进去的）

**Comment by fanyingying** [comment]
同样问题，有解决方案没？

**Comment by jaqen404** [comment]
> 

我后来没用了，你去看看官方示例，还有没有这个问题
