### ISSUE TITLE
小程序每个页面wxss中，ui的基础动画样式重复出现

### ISSUE THREAD

**Issue by WhileSun** [jdf2e/nutui#1383]
## 问题描述
动态引入ui样式，由于文件会引入[animation,mixins]样式，导致taro生成小程序时，每个page中都会引入[animation,mixins]样式，导致wxss文件变大
![image](https://user-images.githubusercontent.com/31122836/173519138-e2fb5441-c652-4783-8e1f-03287738dc33.png)
![image](https://user-images.githubusercontent.com/31122836/173519524-b2f25396-99f8-4d41-8adc-63f62c93ae7c.png)
![image](https://user-images.githubusercontent.com/31122836/173519592-b7b72895-7116-4bef-b4ea-79999699b75c.png)

## 预期
能实现css不要在每个page的wxss重复引入

**Comment by 1045598742** [comment]
支付宝小程序也一样
