### ISSUE TITLE
TimeSelect 的title是否可以支持输入html格式

### ISSUE THREAD

**Issue by fanfantu** [jdf2e/nutui#1385]
现状：1.
![image](https://user-images.githubusercontent.com/15604444/173761440-c0c610bf-760c-4bc3-bc77-edb293195358.png)
想要的结果：
![image](https://user-images.githubusercontent.com/15604444/173761521-0d46506a-0c90-4bb9-938a-12e02b601cbd.png)

**Comment by szg2008** [comment]
已支持，本周发布
