### ISSUE TITLE
使用nut-ui 3.1.21版本中 picker  出现了选项重叠的问题，滑动控制台报错。[bug]

### ISSUE THREAD

**Issue by Loading-source** [jdf2e/nutui#1386]
## 问题描述
使用nut-ui 3.1.21版本中  出现了选项重叠的问题，滑动控制台报错。如下图的问题   
![image](https://user-images.githubusercontent.com/18030018/173782304-f82056c5-5502-431d-a6e5-7ed91fb0b09f.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by HongLiangGong1990** [comment]
不仅是重影问题，我在官方小程序中，上下滑动出现卡顿的情况

**Comment by StavinLi** [comment]
卡顿+1

**Comment by yangxiaolu1993** [comment]
已进行修改及优化，可优先尝试 3.1.23-beta.2版本

**Comment by lhc1995** [comment]
picker组件下拉选项过多 导致滚动卡顿 以及想增加搜索功能
