### ISSUE TITLE
求问tabbar怎么设置跳转 用href会报错

### ISSUE THREAD

**Issue by mrchenxxx** [jdf2e/nutui#1390]
求问tabbar怎么设置跳转 用href会报错
![image](https://user-images.githubusercontent.com/44868578/173984269-f7810625-162f-46a8-81f6-d9dc916aaf77.png)
![image](https://user-images.githubusercontent.com/44868578/173984287-ce24981b-7e65-4104-a61a-e70bbe14d7ea.png)

**Comment by HongLiangGong1990** [comment]
可以在tab-switch事件中使用navigateTo跳转页面

**Comment by mrchenxxx** [comment]
> 可以在tab-switch事件中使用navigateTo跳转页面

谢谢回复 有示例代码吗

**Comment by Drjingfubo** [comment]
路由跳转用to

**Comment by Drjingfubo** [comment]
看下文档
