### ISSUE TITLE
Signature组件是否能根据外层盒子自适应大小？

### ISSUE THREAD

**Issue by MyGitsAccount** [jdf2e/nutui#1392]
Signature组件是否能根据外层盒子自适应大小？
目前修改大小后canvas画笔位置不对，导致组件未达到想要效果

**Comment by Ymm0008** [comment]
@MyGitsAccount  外层盒子的大小是动态变化的吗？

**Comment by Ymm0008** [comment]
@MyGitsAccount 辛苦提供一下复现仓库
