### ISSUE TITLE
[bug]tabs组件添加title-scroll属性后，标签栏无法滚动

### ISSUE THREAD

**Issue by KAIUP** [jdf2e/nutui#1396]
## 问题描述
3.x版本的tabs组件添加title-scroll属性后，标签栏无法滚动

## 预期的行为和实际行为
添加title-scroll属性应该可以滚动

## 复现步骤，具体代码
官网上的demo也是无效的

## 相关环境信息
- **操作系统** ：window
- **Node 版本** ：14.13.0
- **NutUI 版本** ：^3.1.21
- **Vue 版本**：^3.2.13
- **引用方式**：NPM

**Comment by richard1015** [comment]
使用 3.1.22.beta-3试试看呢

**Comment by richard1015** [comment]
[3.1.22-beta.3](https://www.npmjs.com/package/@nutui/nutui/v/3.1.22-beta.3)

**Comment by KAIUP** [comment]
3.1.22-beta.3是可以滚动，但不是我想要的效果，应该有的效果是点击自动滚动居中的那种。目前自己实现了个这种效果的，这种效果的tab算是个建议吧。

**Comment by richard1015** [comment]
升级 v3.1.22 正式包测试一下
点击自动居中，下个版本发布
