### ISSUE TITLE
dialog 弹窗

### ISSUE THREAD

**Issue by YFEI6** [jdf2e/nutui#14]
除了js调用外， 希望给提供标签引用方式（提供插槽）更方便配置弹窗内容

**Comment by Franslee** [comment]
如果觉得弹窗内容配置不便，不妨试试es6的模板字符串写法，另外弹窗内容支持html。

**Comment by Franslee** [comment]
> 除了js调用外， 希望给提供标签引用方式（提供插槽）更方便配置弹窗内容

已经着手开发了，下个版本加上。感谢反馈

**Comment by Franslee** [comment]
2.0.6版已经增加了这个功能，欢迎体验

**Comment by cuijianjun** [comment]
小程序可以加这个全局调用吗
