### ISSUE TITLE
国际化组件安装缺少js文件

### ISSUE THREAD

**Issue by xy0514** [jdf2e/nutui#140]

**Comment by xy0514** [comment]
You may need an appropriate loader to handle this file type.
|             limitError: 'File size exceeded the limit'
|         }
>         okBtnTxt: 'Ok',
|         cancelText: 'Cancel'
|     }
怎么提示资源大小超出限制啊

**Comment by Franslee** [comment]
复现不了。请提供更多信息。

**Comment by xy0514** [comment]
in ./node_modules/_@nutui_nutui@2.1.3@@nutui/nutui/dist/locales/lang/en-US.js

Module parse failed: Unexpected token (36:8)
You may need an appropriate loader to handle this file type.
|             limitError: 'File size exceeded the limit'
|         }
>         okBtnTxt: 'Ok',
|         cancelText: 'Cancel'
|     }

 @ ./src/main.js 61:0-57 62:16-21
 @ multi ./node_modules/_webpack-dev-server@3.7.2@webpack-dev-server/client?http://192.168.20.168:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by xy0514** [comment]
引入之后就报这个错

**Comment by xy0514** [comment]
vue3.0按需引入的国际化，报错说需要一个loader,文件资源大小超出限制

**Comment by xy0514** [comment]
引入的是日历组件

**Comment by Franslee** [comment]
已处理，请升级新版试试
