### ISSUE TITLE
[bug] 官方示例小程序中datepicker滑动选择日期卡顿

### ISSUE THREAD

**Issue by HongLiangGong1990** [jdf2e/nutui#1400]
## 问题描述

官方的微信小程序中datepicker上下滑动选择日期，选择器滚动卡顿，并且和是否初始化无关，每次弹出日期选择器进行日期选择都会出现卡顿，设备是iphone12，重启手机后仍然一样的卡顿现象，微信开发者工具中调试，无明显卡顿，datepicker依赖的是picker组件，picker也有明显的卡顿
## 最小可复现仓库
官方示例微信小程序即可复现，必现

## 预期的行为和实际行为
预期滑动选择日期时，不应当卡顿

## 复现步骤，具体代码
手机打开官方微信小程序进入datepicker滑动选择日期时，会出现明显卡顿

## 相关环境信息
- **操作系统**：ios 14.71
- **Node 版本**：v16.15.0
- **NutUI 版本**： 3.1.21
- **Vue 版本**：3.2.24
- **引用方式**：  NPM

**Comment by emeiziying** [comment]
+1

**Comment by StavinLi** [comment]
+1

**Comment by zirtomirzhang** [comment]
+1

**Comment by ll790226724** [comment]
+1

**Comment by yangxiaolu1993** [comment]
已进行优化，在3.1.23 版本发布
