### ISSUE TITLE
[bug] steps页面等示例及内容展现错误

### ISSUE THREAD

**Issue by aefj11** [jdf2e/nutui#1404]
已经发现的错误页面

OverLay  展现对应内容为  Notify  消息通知
Divider 分割线  展现对应内容为  Dialog  对话框
Layout 布局   展现对应内容为  InfiniteLoading  滚动加载

等等，我发现有问题随便看了下就发现了这么多，还有，麻烦核对下

**Comment by richard1015** [comment]
刚刚发布官网有缓存， 刷新一下就好了
