### ISSUE TITLE
[bug] form中使用datepicker height 问题

### ISSUE THREAD

**Issue by emeiziying** [jdf2e/nutui#1407]
## 问题描述
目前datepicker需要简单封装一下作为component在form中使用，

```
<nut-form>
    <a></a>
</nut-form>
```

a.vue

```
<template>
<nut-datepicker
    v-model="current"
    v-model:visible="visible"
    :min-date="minDate"
    :max-date="maxDate"
    @confirm="confirm"
  ></nut-datepicker>
</template>
```

即使这样也会报height问题

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
date picker 不要放到 nut-form 节点下，
