### ISSUE TITLE
[bug]Ellipsis 组件无法导入

### ISSUE THREAD

**Issue by 490626721** [jdf2e/nutui#1409]
## 问题描述
按照文档引入Ellipsis 失败

## 最小可复现仓库
import {Ellipsis} from "@nutui/nutui"
报红，Module '"@nutui/nutui"' has no exported member 'Ellipsis'.

## 预期的行为和实际行为
能正常引入和使用

## 复现步骤，具体代码
import {Ellipsis} from "@nutui/nutui"

## 相关环境信息
- **操作系统**：win 10
- **Node 版本**：16.15.1
- **NutUI 版本**： ^3.1.21
- **Vue 版本**：vite 2.9.9
- **引用方式**：  NPM

**Comment by richard1015** [comment]
3.1.22 可使用，明天发布

**Comment by richard1015** [comment]
v3.1.22 已发布
