### ISSUE TITLE
Dialog组件禁止滚动，关闭弹窗后，页面展示异常

### ISSUE THREAD

**Issue by Olaf0509** [jdf2e/nutui#1413]
## 问题描述
Dialog组件禁止滚动，关闭弹窗后，页面展示异常

## 最小可复现仓库
初步定位是因为：组件lockBgScroll属性影响的，应该在禁用滚动，设置body定位的时候js计算了当前页面的滚动值，动态赋给body了，但是在组件关闭的时候缺少了重置body top属性逻辑
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：macOS
- **Node 版本**：10.13.0
- **NutUI 版本**： 2.2.18
- **Vue 版本**：2.5.17
- **引用方式**：  NPM

**Comment by richard1015** [comment]
查看 是否和  nutui  lock-bg 样式冲突导致的
