### ISSUE TITLE
[bug]小程序中 FormItem 嵌套 Picker 报错

### ISSUE THREAD

**Issue by az031120103** [jdf2e/nutui#1417]
## 问题描述

小程序只要在 FormItem 组件嵌套 Picker 组件就会报错
Unhandled promise rejection TypeError: Cannot read property 'height' of null

## 复现步骤，具体代码

const show = ref(false)
const columns = ref([
  { text: '南京市', value: 'NanJing' },
  { text: '无锡市', value: 'WuXi' },
  { text: '海北藏族自治区', value: 'ZangZu' },
  { text: '北京市', value: 'BeiJing' },
  { text: '连云港市', value: 'LianYunGang' },
  { text: '浙江市', value: 'ZheJiang' },
  { text: '江苏市', value: 'JiangSu' }
])

<FormItem label="选择城市">
  <Cell title="请选择城市" desc="选择城市" onClick={()=>{show.value = true}}></Cell>
  <Picker
    vModel:visible={show.value}
    columns={columns.value}
    title="城市选择"
  />
</FormItem>

## 相关环境信息

操作系统：ios 14.71
Node 版本：v16.15.0
NutUI 版本： 3.1.21
Vue 版本：3.2.24
引用方式： NPM

**Comment by yangxiaolu1993** [comment]
已解决，3.1.23 版本发布

**Comment by ShawnZeng** [comment]
> 

用的@nutui/nutui-taro 3.2.1 还发生。

**Comment by zarkin404** [comment]
自己封装了一个 Picker 组件

```tsx
import { ArrowRight } from '@nutui/icons-react-taro';
import { Picker, View } from '@tarojs/components';
import { FC } from 'react';

type CompDatePickerProps = {
  value?: string;
  placeholder?: string;
  onChange?: (value: string) => void;
}

const CompDatePicker: FC<CompDatePickerProps> = ({ value, placeholder, onChange }) => {
  return (
    // @ts-ignore
    <Picker
      mode="date"
      value={value}
      onChange={(e) => {
        onChange?.(e.detail.value);
      }}
    >
      <View className="flex items-center justify-between">
        {value ? value : (placeholder || '请选择')}
        <ArrowRight size={14} />
      </View>
    </Picker>
  )
};

export default CompDatePicker;
```

使用方法：

```
          <Form.Item
            label="出生日期"
            name="birth_date"
            required
            rules={[
              { required: true, message: '请选择出生日期' },
            ]}
          >
            <CompDatePicker />
          </Form.Item>
```

NutUI 用在小程序上面坑太多了，唉，骑虎难下
