### ISSUE TITLE
[bug]ImagePreview 图片预览 样式错误（h5）

### ISSUE THREAD

**Issue by 490626721** [jdf2e/nutui#1421]
## 问题描述
按文档使用ImagePreview 图片预览出现无法弹出，DOM是文档流，并非fixed固定，怀疑是ImagePreview相关CSS丢失

## 预期的行为和实际行为
正常显示

## 复现步骤，具体代码

无报错

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：16.15.1
- **NutUI 版本**： 3.1.21
- **Vue 版本**：vite 2.9.9
- **引用方式**：   NPM

**Comment by 490626721** [comment]
升级到3.1.22该问题还是存在

**Comment by shichaohui** [comment]
ImagePreview 内部使用了 OverLay、Popup、Swiper、SwiperItem，按需引入需要把这些组件都引入了。
