### ISSUE TITLE
[bug] DatePicker选择器 小时区域 滑动异常

### ISSUE THREAD

**Issue by 2256184693** [jdf2e/nutui#1429]
## 问题描述

DatePicker选择器中，小时区域滑动时异常。
<img width="366" alt="image" src="https://user-images.githubusercontent.com/26702624/176087874-04a5b0fa-fe2f-41ff-be41-88448028c9ba.png">

## 最小可复现仓库
具体现象可参考官网组件DatePicker区。https://nutui.jd.com/jdt/#/zh-CN/component/datepicker

## 预期的行为和实际行为
小时区域交互正常，可正常展示、滑动

## 复现步骤，具体代码
DatePicker开始选择时间，滑动小时区域滑块

## 相关环境信息
- **操作系统**：Mac
- **Node 版本**：-
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：-
- **引用方式**：  CDN / NPM ？-

**Comment by yangxiaolu1993** [comment]
已修复，可优先使用 3.1.23-beta.2
