### ISSUE TITLE
[bug] Cascader 在微信小程序下弹出输入框

### ISSUE THREAD

**Issue by Yunhui** [jdf2e/nutui#1430]
## 问题描述

在iOS微信小程序中，Cascader 和输入框会同时弹出！h5没有这个问题

## 复现步骤，具体代码
官方demo微信小程序也有

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：3.1.22
- **Vue 版本**：vue3
- **引用方式**：  CDN / NPM ？

**Comment by Yunhui** [comment]
死气沉沉

**Comment by yangxiaolu1993** [comment]
已修复，在3.1.23发布
