### ISSUE TITLE
[bug]微信小程序使用textarea报错

### ISSUE THREAD

**Issue by 6xiaoxin** [jdf2e/nutui#1432]
## 问题描述
微信小程序使用nut-textarea报错
![image](https://user-images.githubusercontent.com/55842780/176142107-ca104cf6-706a-42ca-9fb2-9dd0fd021040.png)

## 最小可复现仓库
https://nutui.jd.com/#/zh-cn/component/textarea

## 预期的行为和实际行为
正常引用

## 复现步骤，具体代码
按需引入的方式。
微信小程序开发工具版本：1.05.2204250
调试基础库：2.24.6

## 相关环境信息
- **操作系统**：
- **Node 版本**：16.10.0
- **NutUI 版本**： 3.1.22
- **Vue 版本**：vue3
- **引用方式**：   NPM

**Comment by Ymm0008** [comment]
@6xiaoxin  您好，目前测试中没有发现报错，您能提供一下复现步骤吗？
