### ISSUE TITLE
[bug] h5视频组件 播放完 跳转另一个页面黑屏，必须手动点击播放才可以

### ISSUE THREAD

**Issue by tangguo13** [jdf2e/nutui#1433]
第一个页面
playend() {
            this.$emit("playOver");
 }

跳转到的页面
结果：黑屏需要用户手动点击播放
期望：视频可以自动播放

是否静音都是黑屏的

**Comment by Drjingfubo** [comment]
我们使用的是video原生标签，部分兼容性问题无法解决
