### ISSUE TITLE
[bug] 级联选择器套在nut-tabpane中使用时，显示异常

### ISSUE THREAD

**Issue by jasper-ops** [jdf2e/nutui#1434]
## 问题描述

在微信小程序中，级联选择器放在了nut-tabpane中时，显示异常，只显示在nut-tabpane中
## 最小可复现仓库
> https://github.com/daofeng-coder/cascader-bug

## 预期的行为和实际行为
预期全屏显示，实际上只在nut-tabpane中显示了
建议不要直接嵌套一个popup，应该让用户自定义的操作方式，也许需要直接显示在页面中呢？而不需要弹出显示呢，现在的模式就有一点问题

## 复现步骤，具体代码
git项目中的第一个页面有演示代码

## 相关环境信息
- **操作系统**：
- **Node 版本**：16.15.1
- **NutUI 版本**： 3.1.22
- **Vue 版本**：3.0
- **引用方式**：  NPM

**Comment by richard1015** [comment]
由于popup 当前小程序 内不支持，指定节点挂载， 暂时不能套进 tabpane中

**Comment by Drjingfubo** [comment]
级联选择器增加了poppable 选项，是否需要弹层展示。
