### ISSUE TITLE
[bug]微信小程序使用nut-uploader报错FormData is not defined

### ISSUE THREAD

**Issue by 6xiaoxin** [jdf2e/nutui#1435]
## 问题描述

微信小程序使用nut-uploader报错FormData is not defined，在微信小程序中没有FormData对象，所以在微信小程序中无法使用new FormData()。
![image](https://user-images.githubusercontent.com/55842780/176342615-5d86f21d-b561-4add-ba97-d7c23000d91f.png)

## 最小可复现仓库
https://nutui.jd.com/#/zh-cn/component/uploader-taro

## 复现步骤，具体代码
按需引入的方式。
微信小程序开发工具版本：1.05.2204250
调试基础库：2.24.6

## 相关环境信息
- **操作系统**：win10专业版
- **Node 版本**：16.10.0
- **NutUI 版本**： 3.1.22
- **Vue 版本**：vue3
- **引用方式**： npm

**Comment by richard1015** [comment]
升级 3.1.22 试试，这个bug 3.1.22 已经修复了

**Comment by richard1015** [comment]
https://github.com/jdf2e/nutui-demo/blob/master/taro/src/dentry/pages/uploader/index.vue
