### ISSUE TITLE
[bug] popup taro 遮罩层不生效

### ISSUE THREAD

**Issue by wavesbig** [jdf2e/nutui#1437]
## 问题描述
 引用 popup 后默认不展示遮罩层，设置 overlay 为true也不生效
 
![image](https://user-images.githubusercontent.com/34082148/176379139-2e8e3d8a-e005-4283-990c-ea0e95fad30a.png)

![image](https://user-images.githubusercontent.com/34082148/176379072-86dfd164-38ae-4342-8df3-633bbf0a12df.png)

## 相关环境信息
- **操作系统**：win11
- **Node 版本**：14.15.0
- **NutUI 版本**： 3.1.22
- **Vue 版本**：3
- **引用方式**： NPM

**Comment by szg2008** [comment]
需要额外引入overlay组件

**Comment by wavesbig** [comment]
> 需要额外引入overlay组件

搜嘎搜嘎，感谢

**Comment by wavesbig** [comment]
> 需要额外引入overlay组件

还有一个问题，我能用标签名设置样式吗view，swiper，textarea这种
