### ISSUE TITLE
希望Comment 评论组件, 星星的点击状态 改成只读

### ISSUE THREAD

**Issue by zhaoyunchong** [jdf2e/nutui#1438]
## 你建议我们做什么？
希望Comment 评论组件, 可以禁用掉 评价 星星的点击状态 改成只读, 因为评论之后 显示出来的评价是无法点击更改评论的星级的

现在...

如果你能...

它将使...

## 其它

无

**Comment by yangxiaolu1993** [comment]
已修改，会在 3.1.23 版本发布

**Comment by zhaoyunchong** [comment]
> 
好的谢谢。我现在先用另一种方式解决了 每次点击重新赋值 上一次的那个星级 这样的处理的
