### ISSUE TITLE
[suggest] 使用Vuter代码提示生效，Volar代码提示不生效

### ISSUE THREAD

**Issue by wavesbig** [jdf2e/nutui#1439]
## 你建议我们做什么？
使用Vuter的情况下对script setup会有报错，希望支持Volar插件下的组件代码提示

**Comment by szg2008** [comment]
没太明白，您指的是NutUI组件支持Volar吗？

**Comment by wavesbig** [comment]
> 没太明白，您指的是NutUI组件支持Volar吗？

对的支持在volar下的代码提示

**Comment by szg2008** [comment]
ok，后面版本会支持，感谢反馈～

**Comment by szg2008** [comment]
目前支持的，可以试试
