### ISSUE TITLE
nuxt里使用nutui，出现not matching server-rendered content的错误

### ISSUE THREAD

**Issue by lhtzbj12** [jdf2e/nutui#144]
在页面里只放一个nut-button，刷新页面时，出现以下错误。
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside

, or missing . Bailing hydration and performing full client-side render.

**Comment by Franslee** [comment]
未能复现，请提供详细信息

**Comment by lhtzbj12** [comment]
我做了一个例子，https://gitee.com/lhtzbj12/html_nuxt_nutui ， 
git clone 到本地，安装后启动。用谷歌打开http://localhost:3000，初次打开时没问题，刷新后 在浏览器控制台 出现错误。

**Comment by lhtzbj12** [comment]
> 未能复现，请提供详细信息
我做了一个例子，https://gitee.com/lhtzbj12/html_nuxt_nutui ，这个错误在element里也有，官方法解决方法是在引入插件时 ssr:true
