### ISSUE TITLE
[bug] taro下使用swiper-item组件vue.d.ts文件命名生成错误

### ISSUE THREAD

**Issue by ilovintit** [jdf2e/nutui#1442]
## 问题描述

使用taro和vue3+ts开发时，ide识别的d.ts文件识别错误.
@nutui-taro/dist/types/_VUE/swiperitem/index.taro.vue.d.ts 文件内的
```
declare module 'vue' {
  interface GlobalComponents {
      NutSwiperitem: typeof _sfc_main;
  }
}   
```
段代码item的首字符大小写错误，正确应该是大写，这样子ide才能识别出是swiper-item而不是现在的swiperitem连起来了。
```
declare module 'vue' {
  interface GlobalComponents {
      NutSwiperItem: typeof _sfc_main;
  }
}   
```

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
拼写修改正确

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：node 16
- **NutUI 版本**： 3.1.21
- **Vue 版本**：3.0
- **引用方式**：  npm

**Comment by szg2008** [comment]
感谢反馈，我们跟进下
