### ISSUE TITLE
[suggest]menuitem上增加自定义class

### ISSUE THREAD

**Issue by SimboDu123** [jdf2e/nutui#1445]
## 你建议我们做什么？
![image](https://user-images.githubusercontent.com/23043164/177271666-f1346369-9006-4d83-ae89-da48fa22baf5.png)
现在...
menu上有自定义class
如果你能...
menuitem上增加
它将使...
menuitem样式根据数据变化而变化
## 其它

无

**Comment by richard1015** [comment]
v3.2.1 已发布
