### ISSUE TITLE
menu组件：当menuitem个数超过一屏宽度，是否可以增加滑动操作

### ISSUE THREAD

**Issue by SimboDu123** [jdf2e/nutui#1446]
## 你建议我们做什么？
menu组件：当menuitem个数超过一屏宽度，是否可以增加滑动操作

现在...
menuitem个数超过一屏宽度，被隐藏/挤到一起
如果你能...
增加自动滑动操作
它将使...
组件交互场景更丰富
## 其它

无

**Comment by yangjinjun3** [comment]
看下这个，是否能解决您的问题！
https://github.com/jdf2e/nutui/issues/1343
