### ISSUE TITLE
swiper组件没有touchmove交互事件？

### ISSUE THREAD

**Issue by SimboDu123** [jdf2e/nutui#1447]
## 你建议我们做什么？
swiper组件没有touchmove事件，
现在...
touchend之后，事件才执行，出现延迟。
如果你能...
增加touchmove交互 + 弹性距离【清除自动事件，采用move距离事件，touchend开启自动事件】
它将使...
交互更友好
## 其它

无

**Comment by szg2008** [comment]
目前是有touchmove事件的，没太明白你说的意思，能具体描述下吗
