### ISSUE TITLE
[question]Uploader 组件的accept

### ISSUE THREAD

**Issue by wavesbig** [jdf2e/nutui#1448]
## 你想知道什么？

Uploader 组件的accept 设置 * 或者默认或者’.pdf‘弹出的选择文件都是图片文件这样是正常的吗
![image](https://user-images.githubusercontent.com/34082148/177289571-812796e5-b6e1-4045-85b5-d9ca0f36cef2.png)

**Comment by richard1015** [comment]
使用包名请描述清楚
 @nutui/nutui-taro   ？
 @nutui/nutui    ？

**Comment by wavesbig** [comment]
> @nutui/nutui-taro

使用的@nutui/nutui-taro，是不是里面用的方法是chooseImg

**Comment by wavesbig** [comment]
> 使用包名请描述清楚 @nutui/nutui-taro ？ @nutui/nutui ？

@nutui/nutui-taro的Uploader 设置 *.pdf 我在手机上选择不到pdf文件只能选择图片文件

**Comment by selectweilin** [comment]
如果是H5模式下的话可以使用以下方式临时处理这个问题
`onMounted(() => {
      const obj = document.createElement("input");
      obj.setAttribute("type", "file");
      obj.setAttribute("id", "taroChooseImage");
      obj.setAttribute("accept", "*");
      obj.setAttribute(
        "style",
        "position: fixed; top: -4000px; left: -3000px; z-index: -300;"
      );
      document.body.appendChild(obj);
    });`
问题的原因是Taro强制使用了
`obj.setAttribute('accept', 'image/*')`
具体可详查Taro源码[taro](https://github.com/NervJS/taro)/[packages](https://github.com/NervJS/taro/tree/next/packages)/[taro-h5](https://github.com/NervJS/taro/tree/next/packages/taro-h5)/[src](https://github.com/NervJS/taro/tree/next/packages/taro-h5/src)/[api](https://github.com/NervJS/taro/tree/next/packages/taro-h5/src/api)/[media](https://github.com/NervJS/taro/tree/next/packages/taro-h5/src/api/media)/[image](https://github.com/NervJS/taro/tree/next/packages/taro-h5/src/api/media/image)/chooseImage.ts
第54行

**Comment by wavesbig** [comment]
> 如果是H5模式下的话可以使用以下方式临时处理这个问题 `onMounted(() => { const obj = document.createElement("input"); obj.setAttribute("type", "file"); obj.setAttribute("id", "taroChooseImage"); obj.setAttribute("accept", "*"); obj.setAttribute( "style", "position: fixed; top: -4000px; left: -3000px; z-index: -300;" ); document.body.appendChild(obj); });` 问题的原因是Taro强制使用了 `obj.setAttribute('accept', 'image/*')` 具体可详查Taro源码[taro](https://github.com/NervJS/taro)/[packages](https://github.com/NervJS/taro/tree/next/packages)/[taro-h5](https://github.com/NervJS/taro/tree/next/packages/taro-h5)/[src](https://github.com/NervJS/taro/tree/next/packages/taro-h5/src)/[api](https://github.com/NervJS/taro/tree/next/packages/taro-h5/src/api)/[media](https://github.com/NervJS/taro/tree/next/packages/taro-h5/src/api/media)/[image](https://github.com/NervJS/taro/tree/next/packages/taro-h5/src/api/media/image)/chooseImage.ts 第54行

可以

**Comment by richard1015** [comment]
该功能需内部改动为 chooseMessageFile ，预计 月底修复此问题

**Comment by richard1015** [comment]
https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.6-beta.1

**Comment by herodhb** [comment]
> https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.6-beta.1

只能选择图片的问题修复了。但是有个别的问题，同时有多个uploader组件时，不同的组件需要限制不同的accept上传类型。所有的uploader都只会遵循第一个accept类型。

例如，


        <nut-form-item label="缩略图">
          <nut-uploader
            id="thumb"
            name="thumb"
            url="https://xxxx"
            maximum="1"
            accept="image/jpeg, image/png"
          ></nut-uploader>
        </nut-form-item>

        <nut-form-item label="资源包">
          <nut-uploader
            id="source"
            name="source"
            url="https://xxxxxx"
            maximum="1"
            :before-upload="beforeUpload"
          ></nut-uploader>
        </nut-form-item>

第二个"资源包"组件无论是否设置accept，都一定限制只能选择png和jpeg

**Comment by richard1015** [comment]
@herodhb   先用这个，https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.7-beta.0

3.2.7正式版会在 11.18发布
