### ISSUE TITLE
[suggest] 希望tabbar 的 v-model:visible 能支持name的匹配

### ISSUE THREAD

**Issue by juzijun2020** [jdf2e/nutui#1449]
## 你建议我们做什么？

现在的tabbar对选中标签的索引值只支持number，正常情况下我们会把tabbar 封装到一个组件里面，然后在其他页面调用这个tabbar，在调用这个组件的时候我们会动态传入tabbar的索引值，但是当我调整了tabbar-item的顺序的时候，我需要同步修改每个页面的索引值，这样很麻烦，如果能增加对 name属性的支持，这样就很灵活了，不管顺序怎么变(只要name不变)，我就不需要去改其他页面的索引值。

## 其它
可参考vant [vant-tabbar](https://vant-contrib.gitee.io/vant/#/zh-CN/tabbar#tabbaritem-props)

**Comment by Drjingfubo** [comment]
3.2.0版本已经支持
