### ISSUE TITLE
[bug]Vue下的音频播放器进度条：音频时长的秒级显示异常

### ISSUE THREAD

**Issue by slpss** [jdf2e/nutui#1451]
## 问题描述
@nutui/nutui的音频播放组件【nut-audio】的进度条，当前播放时长与音频总时长显示异常，秒级显示不出来，官网demo就有问题的
![image](https://user-images.githubusercontent.com/108789766/177497269-fe08def1-0e9f-4153-9801-54b2b00a4153.png)

**Comment by slpss** [comment]
@richard1015 可以帮忙看看这个问题吗？

**Comment by richard1015** [comment]
v3.2.1 已发布
