### ISSUE TITLE
[bug] @nutui/nutui-taro 使用uploader组件accept属性不生效

### ISSUE THREAD

**Issue by wavesbig** [jdf2e/nutui#1455]
## 问题描述

@nutui/nutui-taro 使用uploader组件accept属性设置为“application/pdf”不生效，并且手机端预览只能选择png

## 相关环境信息
- **操作系统**：win
- **Node 版本** 14.15.0
- **NutUI 版本**："@nutui/nutui-taro": "^3.1.22",
- **Vue 版本**： "vue": "^3.0.0"
- **引用方式**： npm

**Comment by wavesbig** [comment]
@richard1015 这个是有问题嘛

**Comment by richard1015** [comment]
该功能需内部改动为 chooseMessageFile ，预计 月底修复此问题

**Comment by richard1015** [comment]
已修复，https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.6-beta.1

**Comment by richard1015** [comment]
关注 #1448
