### ISSUE TITLE
[bug] IOS 低版本机型 nut-picker 和 nut-datepicker 组件选项显示问题

### ISSUE THREAD

**Issue by qwerty9307111** [jdf2e/nutui#1457]
## 问题描述

使用 nut-picker 和 nut-datepicker 组件，在低版本的 IOS 机型上滑动选项时，应当被隐藏的选项仍然显示在页面中。

## 相关环境信息
- **操作系统**：iPhone 7P  IOS14
- **Node 版本**：14.15.0
- **NutUI 版本**： 3.1.18
- **Vue 版本**：3.2.13
- **引用方式**：  NPM 

![image](https://user-images.githubusercontent.com/25604284/177903073-fd56d654-54a2-45eb-8aad-a3a1ec12f172.png)

https://user-images.githubusercontent.com/25604284/177898823-34486131-805c-4428-9beb-bc7572fc93bf.mp4

**Comment by yangxiaolu1993** [comment]
可以尝试使用最新版本 3.1.23-beta.3 ，如果在低端手机上还是出现，在下个版本会新增参数用于平铺展示

**Comment by hydraZty** [comment]
升级了新版本，还是没解决，ios 14.x 在 webview 中可复现。
翻了下局部实现 isHidden 的判断为何是前后各8，这么看应该有其他属性在控制滚动到反面的元素隐藏

----

看来是 backface-visibility 的兼容性问题

**Comment by mzz2020** [comment]
nut-picker 在h5上出现重叠或是选中后再打开，下拉列表空白，有没有解决的方法
