### ISSUE TITLE
[bug] 使用InfiniteLoading提示【Vue warn】

### ISSUE THREAD

**Issue by whoopsHzh** [jdf2e/nutui#1462]
## 问题描述
使用InfiniteLoading官方示例、重复警告。请问有处理方法吗，非常感谢

## 最小可复现仓库
[组件示例代码](https://nutui.jd.com/3x/#/zh-cn/component/infiniteloading)

## 预期的行为和实际行为
两个轮番提示：
![image](https://user-images.githubusercontent.com/32846446/178174267-2fbfeed3-bd8a-43b6-8e71-14023ff5fab7.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**： v16.14.0
- **NutUI 版本**： 3.1.22
- **Vue 版本**：3
- **引用方式**：  NPM

**Comment by zjhr** [comment]
我也是，h5无法使用InfiniteLoading组件，wx小程序端没问题，但是还是会出现这个提示

**Comment by eiinu** [comment]
参考解决方案： [Taro 使用原生模块 | Taro 文档](https://taro-docs.jd.com/taro/docs/hybrid/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by richard1015** [comment]
v3.2.1 已修复 已发布
