### ISSUE TITLE
[bug]Dialog调用报错：Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by binghc** [jdf2e/nutui#1465]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码

版本:"@nutui/nutui-taro": "^3.1.23-beta.3",

官方文档的demo代码直接拿来用，报错：Uncaught TypeError: Object(...) is not a function

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
dialog taro版暂时不支持函数调用
