### ISSUE TITLE
[bug]Image组件不显示图片，显示文字：Welcome to developing components

### ISSUE THREAD

**Issue by binghc** [jdf2e/nutui#1466]
文档demo直接拿来用 版本："@nutui/nutui-taro": "^3.1.23-beta.3",

**Comment by pfsj-xk** [comment]
我也出现了这个问题

**Comment by Dongary** [comment]
这个组件还没有同步过来，我服了，，

**Comment by ipconfiger** [comment]
我也是服了

**Comment by richard1015** [comment]
https://nutui.jd.com/#/zh-cn/component/image-taro

直接使用 Taro 现有 Image 组件开发

![image](https://user-images.githubusercontent.com/13060263/183396552-1b8f6910-5d3b-4409-9964-e37d5f87cbea.png)

**Comment by droplet-js** [comment]
无语！！！！！！！！！！！！！！！！！！

**Comment by ianho7** [comment]
尬住😅

**Comment by SheepYang1993** [comment]
这都能没有？？？！！！

**Comment by nico-summer** [comment]
绷不住了 这问题还没解决阿

**Comment by yanchengjie1990** [comment]
这问题是解决了吗 怎么问题被关闭了  但我的依然有这个问题

**Comment by JuYiYang** [comment]
你们还会吗？我的现在还是会显示这个 nutui@^3.3.0
