### ISSUE TITLE
[bug] h5页面  textarea input autofoucs 属性失效

### ISSUE THREAD

**Issue by gowago** [jdf2e/nutui#1468]
## 问题描述

h5页面  textarea和input 组件 autofoucs 属性失效
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
h5页面  textarea input autofoucs  鼠标聚焦

## 复现步骤，具体代码
```
 <nut-form>
        <nut-input :autofocus="true" placeholder="忙碌而又充实的一天又过去了…" />
      </nut-form>
```

## 相关环境信息
- **操作系统**：windwos10
- **Node 版本**：16.15
- **NutUI 版本**：@nutui/nutui-taro 3.1.22
- **Vue 版本**：^3.2.33
- **引用方式**：  CDN / NPM ？NPM

**Comment by Ymm0008** [comment]
textarea 组件未复现，辛苦请提供您的复现代码 @gowago
