### ISSUE TITLE
[bug]动态创建CollapseItem的情况下折叠报错name未定义

### ISSUE THREAD

**Issue by w-zhCN** [jdf2e/nutui#1470]
https://codesandbox.io/embed/nutui3-0-vite-js-forked-s7hmnt?fontsize=14&hidenavigation=1&theme=dark

操作系统：windwos11
Node 版本：16.15
NutUI 版本：@nutui/nutui 3.1.16
Vue 版本：^3.0.0
引用方式： CDN / NPM ？NPM

**Comment by Ymm0008** [comment]
@w-zhCN   感谢您的反馈，问题在之前已修复，只是代码未合并，将在新版本修复改问题。
