### ISSUE TITLE
[bug]nut-tag  plain 添加属性后   总是红色空心样式 

### ISSUE THREAD

**Issue by clooes** [jdf2e/nutui#1472]
## 问题描述
在 taro 3.4 vue 微信小程序中使用  发现  使用了plain 属性 只会显示 danger 空心样式 (或者说红色空心样式)

## 预期的行为和实际行为
根据 type 属性变更
## 复现步骤，具体代码
```
 <nut-tag type="success" :plain="true" >xxx</nut-tag>
or
 <nut-tag type="success" plain >xxx</nut-tag>
```

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：v16.15.1
- **NutUI 版本**：   "@nutui/nutui-taro": "^3.1.22",
- **Vue 版本**： "vue": "^3.0.0"
- **引用方式**：  NPM

**Comment by richard1015** [comment]
v3.2.1 已发布
