### ISSUE TITLE
[bug]使用 NoticeBar 组件，小程序端编译报错

### ISSUE THREAD

**Issue by jiahaowu-git** [jdf2e/nutui#1473]
## 问题描述

使用 NoticeBar 组件，小程序端编译报错。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
按照官网示例使用 NoticeBar 组件，应该能正常编译。
实际上小程序端编译报错，h5端编译能通过。

## 复现步骤，具体代码
`<template>
  <nut-noticebar
      text="NutUI 是京东风格的移动端组件库，使用 Vue 语言来编写可以在 H5，小程序平台上的应用，帮助研发人员提升开发效率，改善开发体验。"
      :background="`rgba(251, 248, 220, 1)`"
      :color="`#D9500B`"
    ></nut-noticebar>
</template>`

步骤1：npm run dev:weapp，编译报错；
步骤2：npm run dev:h5，编译正常。

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：v14.4.0
- **NutUI 版本**： 3.1.22
- **Vue 版本**：3.2.26
- **引用方式**：  NPM

**Comment by szg2008** [comment]
`:background="rgba(251, 248, 220, 1)" :color="#D9500B"`.这里不应该加：，去掉就可以了
