### ISSUE TITLE
[bug]H5环境下Uploader默认只能选择图像类型，更改accept为*也无效

### ISSUE THREAD

**Issue by selectweilin** [jdf2e/nutui#1474]
## 问题描述
H5环境下Uploader默认只能选择图像类型，更改accept为*也无效

## 复现步骤，具体代码

`<nut-uploader :url="uploadUrl" v-model:file-list="defaultFileList" maximum="10" multiple list-type='list'>
    <nut-button type="success" size="small">上传文件</nut-button>
  </nut-uploader>`

直接复制的文档代码

![image](https://user-images.githubusercontent.com/972784/178946456-1b972cbd-4383-496c-b835-f9e734194afb.png)

使用沙盒模式又正常

![image](https://user-images.githubusercontent.com/972784/178946713-9b7c3898-f4ca-426b-ad1e-13f744964fba.png)

## 相关环境信息
- **操作系统**：Windows
- **Node 版本**：16.14.2
- **NutUI-taro 版本**： 3.1.22
- **Vue 版本**：Vue3
- **引用方式**：  CDN / NPM ？NPM

**Comment by az031120103** [comment]
遇到同样的问题 taro-uploader  h5 只支持上传图片，能否支持更改 accept

**Comment by richard1015** [comment]
该功能需内部改动为 chooseMessageFile ，预计 月底修复此问题

**Comment by richard1015** [comment]
https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.6-beta.1

**Comment by az031120103** [comment]
> https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.6-beta.1

ok，试一试

**Comment by richard1015** [comment]
关注 #1448
