### ISSUE TITLE
在ActionSheet中使用 nut-scroller 无法显示 slot="more"的内容

### ISSUE THREAD

**Issue by xojiangxo** [jdf2e/nutui#148]
在ActionSheet中使用 nut-scroller 无法显示 slot="more"的内容
1.第一种情况：如果ActionSheet默认是不显示 绑定的 false ，那么在其中使用的nut-scroller 在滑动后，无法显示 slot="more"的内容，
2.nut-scroller 在绑定了一个数组列表后，如果数组添加了新元素，新元素对应的在滑动后，无法显示 slot="more"的内容，

**Comment by linrufeng** [comment]
兄弟代码粘贴出来，或者描述清楚一点
