### ISSUE TITLE
input组件clearable属性默认绑定的字体图标在移动端不显示x，更改为其他图标可正常显示[bug]

### ISSUE THREAD

**Issue by meishaonian123** [jdf2e/nutui#1484]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by ailululu** [comment]
你好 @meishaonian123 , 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/s/eh6ck?resolutionWidth=414&resolutionHeight=736) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。
