### ISSUE TITLE
[bug]Menu组件必须引入遮罩，文档中未说明

### ISSUE THREAD

**Issue by ztrve** [jdf2e/nutui#1485]
## 问题描述

使用 Taro+NutUI+vue3 练手微信小程序，由于项目是刚创建的  
使用Menu组件的过程中，遮罩一直出不来，后来试着将 OverLay, Popup 组件也引入后，才正常

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

#### 预期的行为
点击Menu组件中账单1后出现遮罩
![image](https://user-images.githubusercontent.com/82516467/180189598-df5ede30-ded9-48f2-b440-9396f512a2ce.png)

#### 实际行为
点击后没有遮罩出现
![image](https://user-images.githubusercontent.com/82516467/180190324-fed176d2-42c0-4da0-af85-1c03ff31b7d5.png)
而文档中说只需要引入Menu和MenuItem即可使用
![image](https://user-images.githubusercontent.com/82516467/180190839-d7fc88de-e723-459e-9184-aa726c35565a.png)

> 文档地址：https://nutui.jd.com/jdt/#/zh-CN/component/menu

## 复现步骤，具体代码
```
import { createApp } from 'vue'
import {
  Button, Toast, Tabbar, TabbarItem, Icon,
  Avatar, Empty, Cell, CellGroup,
  Menu, MenuItem, 
  // 打开注释
  // OverLay, Popup
} from '@nutui/nutui-taro';
import './app.styl'

const App = createApp({})

App
  .use(Button).use(Toast).use(Tabbar).use(TabbarItem).use(Icon).use(Avatar).use(Empty).use(Cell).use(CellGroup)
  .use(Menu).use(MenuItem)
  // 打开注释
  // .use(OverLay).use(Popup)

export default App
```

## 相关环境信息
- **操作系统**：mac os
- **Node 版本**：v16.13.2
- **NutUI 版本**： 3.1.8
- **Vue 版本**：3.0.0
- **引用方式**：  yarn

**Comment by richard1015** [comment]
v3.2.1 已发布
