### ISSUE TITLE
[bug]nut-picker快速滑动会卡行

### ISSUE THREAD

**Issue by monsoon4948** [jdf2e/nutui#1487]
![image](https://user-images.githubusercontent.com/12999497/180348649-7eef30ed-e73c-4ff1-8f3b-0726d5acd428.png)

**Comment by monsoon4948** [comment]
就在你们官网的demo就是这样，还没搭到我本地环境

**Comment by yangxiaolu1993** [comment]
[3.1.23-beta.3](https://www.npmjs.com/package/@nutui/nutui/v/3.1.23-beta.3) 已经修复，可以使用
