### ISSUE TITLE
[bug] SearchBar 组件 autofocus 属性不起作用

### ISSUE THREAD

**Issue by BackacheGitHub** [jdf2e/nutui#1488]
## 问题描述
`<nut-searchbar :autofocus="true"></nut-searchbar>`

SearchBar 组件，指定了autofocus为true，但是并没有自动聚焦

## 最小可复现仓库
> https://gitee.com/backache/issue-nutui-searchbar

## 预期的行为和实际行为
如描述

## 复现步骤，具体代码
执行 `npm dev:h5` 打开首页发现搜索框没有自动聚焦

## 相关环境信息
- **操作系统**：MacOS Monterey 12.4 Chrome 103.0.5060.114
- **Node 版本**：v14.19.1
- **NutUI 版本**： ^3.1.22
- **Vue 版本**：^3.0.0
- **引用方式**： NPM

**Comment by LadyChatterleyLover** [comment]
这个没问题啊，可以聚焦
