### ISSUE TITLE
TabBar标签栏 tabbarList数组下面的对象icon动态加载图片地址bug

### ISSUE THREAD

**Issue by chix1221** [jdf2e/nutui#149]
tabbarList 下面的icon图片地址动态加载，值确定获取到了，但是赋值给background-img为undefined
![image](https://user-images.githubusercontent.com/20106491/61422037-69d1cd80-a93c-11e9-8dc0-2d762c164d17.png)

![image](https://user-images.githubusercontent.com/20106491/61422059-866e0580-a93c-11e9-99ae-90aa46959af0.png)
希望官方尽快给出回复，谢谢

**Comment by zhenyulei** [comment]
> tabbarList 下面的icon图片地址动态加载，值确定获取到了，但是赋值给background-img为undefined
> ![image](https://user-images.githubusercontent.com/20106491/61422037-69d1cd80-a93c-11e9-8dc0-2d762c164d17.png)
> 
> ![image](https://user-images.githubusercontent.com/20106491/61422059-866e0580-a93c-11e9-99ae-90aa46959af0.png)
> 希望官方尽快给出回复，谢谢

动态加载的图片地址应该是异步获取的吧，是不是你获取的时机不对呢？如果还有疑问，请附上详细代码，感谢！

**Comment by richard1015** [comment]
源码内部 tabbarList 没有做watch监听，辛苦玉磊修复一下这个问题

**Comment by zhenyulei** [comment]
经验证可以在demo中改变数据，页面更新 见下图：
![image](https://img11.360buyimg.com/imagetools/jfs/t1/103036/27/16328/399256/5e79c6efE880e71b8/61440fceb42ccdb9.jpg)
