### ISSUE TITLE
[bug]swiper  "is-center"  not work

### ISSUE THREAD

**Issue by bestFeeling** [jdf2e/nutui#1497]
"is-center"在官方文档提供的演示demo中没有起作用
[在线代码调试平台](https://codehouse.jd.com/?source=share&type=vue&mainJs=Ly9pbXBvcnQgVkNvbnNvbGUgZnJvbSAidmPGDyI7Ci8vdmFyIHbIID0gbmV3yS8oKTsKx0J7IGNyZWF0ZUFwcCB9yEd1xELHIcQZxhcuL2FwcC7NHU51dFVJxx9AbnV0dWkvxQbKIsc2c2Nzc8sVzCwvZGlzdC9zdHlsZS7GJukAkihBcHApLnVzZSjFaSkubW91bnQoIiNhcHAiKTs=&appValue=PHRlbXBsYXRlPgogIDxudXQtc3dpcGVyIDppbml0LXBhZ2U9IsQGIiA6bG9vcD0iZmFsc2UiIHdpZHRoPSIyODAiIGhlaWdodD0iMTUwIiA6aXMtY2VudGVyPSJ0cnVlIiBzdHlsZT0ixiY6IDE1MHB4IsRwzXItaXRlbcYWICA8aW1nIHNyYz0iaHR0cHM6Ly9zdG9yYWdlLjM2MGJ1eWltZy5jb20vamRjLWFydGljbGUvTnV0VUl0YXJvMzQuanBnIiBhbHQ9IiIgL8drL9Vs/wCC/wCC9wCCMuQAgSf/AIL/AIL/AIL2AIJ3ZWxjb21lbnV0dWn/AQX/AIP/AIP6AINmcmlzdGZhYnX/AIDKaswVPgo8L+oCkzxzY3JpcHQgbGFuZz0idHPlAjZpbXBvcnQgeyByZWFjdGl2ZSwgdG9SZWZzIH0gZnJvbSAndnVlJzsKICBleMUqZGVmYXVsdCB75QCDc2V0dXAoKccOICBjb25zdCBzdGF0ZSA9yVQoyB8gIOQC/jogMMcQfSnEWsQBcmV0dXJuIHsgLi4u5gCBKMVGKSB9xiN9CiDECzwv5gDG5ADP5AMK5wDOc2NzcyIgc2NvcGVk5ADXLu8BGucAoWxpbmUt7QM7xl3kAZrGIiDmA4w6IDEwMCXGHSDnA5PMFOUAjuQAjeQAhD4K&scssValue=)

**Comment by szg2008** [comment]
demo没有问题，可以亲自尝试一下
