### ISSUE TITLE
文档不清楚

### ISSUE THREAD

**Issue by JCXIE** [jdf2e/nutui#150]
文档能否写的清楚点，新手表示不会用啊

**Comment by main2018** [comment]
没人维护了吗，

**Comment by zhenyulei** [comment]
> 文档能否写的清楚点，新手表示不会用啊

您好，请问哪里的文档没有写清楚 我改😊

**Comment by JCXIE** [comment]
不用了 已经放弃了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhenyulei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月10日(星期四) 上午9:20
收件人:&nbsp;"jdf2e/nutui"<nutui@noreply.github.com&gt;;
抄送:&nbsp;"开飞机的贝克"<819800692@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jdf2e/nutui] 文档不清楚 (#150)



 
文档能否写的清楚点，新手表示不会用啊
  
您好，请问哪里的文档没有写清楚 我改😊

**Comment by JCXIE** [comment]
datetime-picker控件要自定义min-date怎么搞  里面的小时怎么自定义 比如（min-date='7' max-date='23'）这样





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhenyulei"<notifications@github.com&gt;; 
发送时间: 2019年10月10日(星期四) 上午9:20
收件人: "jdf2e/nutui"<nutui@noreply.github.com&gt;; 
抄送: "开飞机的贝克"<819800692@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jdf2e/nutui] 文档不清楚 (#150)



 
文档能否写的清楚点，新手表示不会用啊
  
您好，请问哪里的文档没有写清楚 我改😊

**Comment by zhenyulei** [comment]
> datetime-picker控件要自定义min-date怎么搞 里面的小时怎么自定义 比如（min-date='7' max-date='23'）这样
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhenyulei"<notifications@github.com&gt;; 发送时间: 2019年10月10日(星期四) 上午9:20 收件人: "jdf2e/nutui"<nutui@noreply.github.com&gt;; 抄送: "开飞机的贝克"<819800692@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [jdf2e/nutui] 文档不清楚 (#150) 文档能否写的清楚点，新手表示不会用啊 您好，请问哪里的文档没有写清楚 我改😊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
你是指开始和结束日期吗？这样定义：
startDate="2000-11-10 12:08"
endDate="2030-10-05 10:04"

**Comment by JCXIE** [comment]
是每天的时间7-23怎么定义（时间范围（7-23））


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhenyulei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午5:56
收件人:&nbsp;"jdf2e/nutui"<nutui@noreply.github.com&gt;;
抄送:&nbsp;"开飞机的贝克"<819800692@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jdf2e/nutui] 文档不清楚 (#150)



 
datetime-picker控件要自定义min-date怎么搞 里面的小时怎么自定义 比如（min-date='7' max-date='23'）这样
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhenyulei"<notifications@github.com&gt;; 发送时间: 2019年10月10日(星期四) 上午9:20 收件人: "jdf2e/nutui"<nutui@noreply.github.com&gt;; 抄送: "开飞机的贝克"<819800692@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [jdf2e/nutui] 文档不清楚 (#150) 文档能否写的清楚点，新手表示不会用啊 您好，请问哪里的文档没有写清楚 我改😊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
 你是指开始和结束日期吗？这样定义：
 startDate="2000-11-10 12:08"
 endDate="2030-10-05 10:04"

**Comment by zhenyulei** [comment]
> 是每天的时间7-23怎么定义（时间范围（7-23））
--------------
startHour	开始小时	;endHour	结束小时

**Comment by richard1015** [comment]
请参考最新文档
