### ISSUE TITLE
[bug]WaterMark水印使用无效

### ISSUE THREAD

**Issue by anzup** [jdf2e/nutui#1504]
## 问题描述
WaterMark 水印使用无效

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
小程序端使用水印组件无效，发现文档中此组件在线调试也无法使用

## 相关环境信息
- **操作系统**：windows 10
- **Node 版本**：17.1.0
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息 3.1.22
- **Vue 版本**：3.2.25
- **引用方式**：  CDN / NPM ？npm

**Comment by richard1015** [comment]
v3.2.0 已发布
