### ISSUE TITLE
NoticeBar公告栏组件垂直滚动时，slot图标无法显示

### ISSUE THREAD

**Issue by lww155** [jdf2e/nutui#1505]
微信小程序端 
![image](https://user-images.githubusercontent.com/69495421/181462643-74291bf0-4c73-428f-91fe-d99966e0d0bd.png)
Nut UI 文档的在线编辑运行也没看到图标显示

**Comment by richard1015** [comment]
v3.2.1 已发布

**Comment by lww996** [comment]
已更新v3.2.1，右边的icon可以显示了，但是当<template v-slot:leftIcon>时，左边插槽没显示出来，跟之前问题一样，麻烦看下
