### ISSUE TITLE
[bug]Taro升级到3.5.0后引用Icon编译错误

### ISSUE THREAD

**Issue by selectweilin** [jdf2e/nutui#1506]
## 问题描述
直接使用Cli创建脚手架后引入Icon就编译错误
![image](https://user-images.githubusercontent.com/972784/181476185-62f0a5c4-782b-4138-a200-88e97e1b97b4.png)

## 复现步骤，具体代码
`import { createApp } from "vue";
import { Button, Toast, Icon } from "@nutui/nutui-taro";

import "./app.scss";

const App = createApp({
  onShow(options) {},
  // 入口组件不需要实现 render 方法，即使实现了也会被 taro 所覆盖
});

App.use(Button)
  .use(Toast)
  .use(Icon);

export default App;
`

## 相关环境信息
- **操作系统**：
- **Node 版本**：16.14.2
- **NutUI 版本**： 3.1.12
- **Vue 版本**：3
- **Taro 版本**：3.5.0
- **引用方式**：  CDN / NPM ？NPM

**Comment by eiinu** [comment]
解决方案参考：[3.5.0nutui-taro 无法导入icon](https://github.com/NervJS/taro/issues/12148)
