### ISSUE TITLE
[bug] taro 用的小程序版本@nutui/nutui-taro picker卡得飞起

### ISSUE THREAD

**Issue by KNJON** [jdf2e/nutui#1513]
## 问题描述

picker 组件在开发者工具非常流畅，在真机小程序上卡得飞起，我一度以为是我手机问题，用了原生自带非常流畅
我看其他issues有这个问题说3.1.23-beta.3解决了，我用这个依赖依然卡。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
尽快上一个修复版，等着用呢，不可能把整个UI库换掉吧

## 相关环境信息
- **操作系统**：
- **Node 版本**：14+
- **NutUI 版本**： 3.1.22
- **Vue 版本**： 3.2.24
- **引用方式**：  yarn

**Comment by HongLiangGong1990** [comment]
picker太卡了，新版本几乎没有任何改善

**Comment by yangxiaolu1993** [comment]
可以通过  threeDimensional=false 将 3D 滚动效果关闭，效果会好很多
