### ISSUE TITLE
[bug]nut-input在支付宝小程序上统计字数有bug

### ISSUE THREAD

**Issue by cqzhong** [jdf2e/nutui#1514]
## 问题描述

出现了两行计算字数
```
<nut-input v-model="message" :border="false" rows="3" type="textarea" max-length="200" show-word-limit placeholder="请输入留言" />
```
![image](https://user-images.githubusercontent.com/10128830/182009160-b155ca8a-3a59-4baa-b9af-864534477f9e.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：任意iOS系统
- **Node 版本**：v14.18.1
- **NutUI 版本**： "@nutui/nutui-taro": "^3.1.22"
- **Vue 版本**："vue": "^3.2.24"
- **引用方式**：  CDN / NPM ？NPM

**Comment by richard1015** [comment]
v3.2.0 已发布
