### ISSUE TITLE
给个建议

### ISSUE THREAD

**Issue by myzf** [jdf2e/nutui#152]
老哥，能不能把官网文档右侧显示效果的源代码，也提供出来呢，很多组件直接复制进来效果出不来的，有报错的，可能就是某个地方没有用对，也不难。
每次粘贴组件再调右侧的效果都很费劲，虽然现在组件不多，但是凑合也能用，只提供单个组件的用法，跑不起来啊

**Comment by famanoder** [comment]
这是个不错的建议，我们后续的版本会考虑提供相应的例子的源代码；
目前有个临时的办法就是，您可以访问我们仓库里的例子的源代码：
`https://github.com/jdf2e/nutui/blob/master/src/packages/${component}/demo.vue`

**Comment by myzf** [comment]
好的先谢谢了
