### ISSUE TITLE
使用navbar组件在小程序开启自定义导航后navbar组件在状态栏下层[bug]

### ISSUE THREAD

**Issue by tcwdbb** [jdf2e/nutui#1521]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：任意系统
- **Node 版本**：v14.18.3
- **NutUI 版本**： "@nutui/nutui-taro": "^3.1.22"
- **Vue 版本**：Vue3
- **引用方式**：  CDN / NPM ？NPM

**Comment by zhangji0518** [comment]
解决了吗，navbar在微信小程序设置navigationStyle: "custom"就显示在状态栏后面，IOS

**Comment by zhangji0518** [comment]
还有left-show不是默认false吗，怎么不设置还显示呢

**Comment by Zremn9** [comment]
一样的问题
![image](https://user-images.githubusercontent.com/82388674/183055254-791908e5-0faf-4f72-b70d-c538464b4d82.png)

**Comment by ailululu** [comment]
请安装@3.2.2，看是否还出现这个问题

**Comment by zhangji0518** [comment]
> 请安装@3.2.2，看是否还出现这个问题

微信开发者工具看还是乱的，手机上看标题不居中是歪的

**Comment by zhangji0518** [comment]
> 请安装@3.2.2，看是否还出现这个问题

装了3.2.2设置left-show和left-text后标题就不居中了，被顶到右边去。还有微信开发者工具看还是错乱的，不知道其他手机型号会不会有问题

**Comment by Drjingfubo** [comment]
设置custom以后需自定义导航栏样式，组件暂时不会对这种情况做适配

**Comment by Drjingfubo** [comment]
计算一下状态栏的高度

**Comment by sperains** [comment]
不明白，如果这种情况不适配，那这个组件的意义是什么~

**Comment by ghost** [comment]
这个组件到4.0.4依然存在问题，同上所述，如果不能适配，那这个组件的意义是什么？

**Comment by GitHubWuYi** [comment]
如果不能适配，那这个组件的意义是什么？
