### ISSUE TITLE
[bug] Image,previewImage,Ellipsis组件都能用吗?

### ISSUE THREAD

**Issue by tohere** [jdf2e/nutui#1524]
我的项目是跑在H5端的

说实话这个框架问题有点多,我一共用了也就10个左右组件,已经发现了Image,previewImage,Ellipsis这三个组件不能用了,全局引入局部引入都试过,就是不能用

而且Ellipsis这个组件你们官方文档自己写的在线调试预览都不能用
https://codehouse.jd.com/?source=share&type=vue&mainJs=Ly9pbXBvcnQgVkNvbnNvbGUgZnJvbSAidmPGDyI7Ci8vdmFyIHbIID0gbmV3yS8oKTsKx0J7IGNyZWF0ZUFwcCB9yEd1xELHIcQZxhcuL2FwcC7NHU51dFVJxx9AbnV0dWkvxQbKIsc2c2Nzc8sVzCwvZGlzdC9zdHlsZS7GJukAkihBcHApLnVzZSjFaSkubW91bnQoIiNhcHAiKTs=&appValue=PHRlbXBsYXRlPgogIDxudXQtZWxsaXBzaXMgY29udGVudD0iTnV0VUkzLjDkuIrnur/lkI7miJHku6znoJTlj5Hlm6LpmJ/kuZ/lnKjkuI3mlq3nmoTkvJjljJbjgIHmtYvor5XjgIHkvb/nlKjjgIHov63ku6MgVnVlMyDnmoTnm7jlhbPnu4Tku7bvvIzkvYbmmK/lnKjot6jnq6/lsI/nqIvluo/nmoTlvIDlj5Hov4fnqIvkuK3vvIzlj5HnjrDmsqHmnInlkIjpgILEUcVL5bqT5Y+v5Lul5pSv5oyB5aSaxE7FQuOAguS4uuS6huWhq+ihpei/meS4gOepuueZvcRUkIzml7bGIeYAxsd4gIXkvZPpqozvvIzorqkg5QEUIOiDveWkn+S4uuabtMRk6QCmgIXluKbmnaXkvr/liKnvvIzmATPlhrPlrprlnKjHQOS4reWinuWKoOkA6cRGq6/pgILphY3nmoTEYYqb44CCIiBkaXJlY3Rpb249ImVuZCIgPjwv7AGvPgo8L+oBzA==&scssValue=

我的taro和nutui都升级到了最新,这三个组件依然不能用

**Comment by pfsj-xk** [comment]
组件库跟不上  还有很多问题

**Comment by richard1015** [comment]
升级最新3.2.0 测试一下呢

**Comment by tohere** [comment]
> 升级最新3.2.0 测试一下呢

就是3.2啊,taro和nut全是最新版本

**Comment by NT-Sasoli** [comment]
刚升级3.2.1，Ellipsis还不能用

**Comment by szg2008** [comment]
可试试最新版本v3.2.2

**Comment by forestRhapsody** [comment]
3.2.2还是不行啊 官网的demo也没见跑起来过

**Comment by szg2008** [comment]
1、Image 组件H5使用没问题，小程序见官方文档，直接使用小程序原生Image组件即可，NutUI暂不提供组件
2、previewImage使用也没问题，需要注意的是在使用之前需要导入overlay、popup、swiper等依赖组件，官方会及时更新
`import { ImagePreview, Overlay, Popup, Swiper, SwiperItem } from '@nutui/nutui';`
3、Ellipsis确实存在问题，源码已经修复，增加了“line-height”属性，等下一版本发布即可使用，如果不升级版本，临时解决办法是需要在组件外加一层，然后设置样式即可。如下：
`<div class="ellipsis-wrapper">
        <nut-ellipsis content="NutUI3.0上线后我们研发小程序多端适配的能力。" direction="start" class="elli"></nut-ellipsis>
    </div>`
`.ellipsis-wrapper{
  display: flex;
  line-height: 20px;
  font-size: 12px;
}`
感谢大家的反馈🙏
