### ISSUE TITLE
[suggest] List 虚拟滚动组件container-height 属性能否增加字符串的支持？

### ISSUE THREAD

**Issue by yycmd** [jdf2e/nutui#1525]
## 你建议我们做什么？

目前官网的 v3.1.19 版本增加了 container-height 属性，这个功能非常实用，但是这个属性目前只支持数字，对于某些场景希望能用 css 的 calc 函数去代替人为的计算 dom 高度的变化，使用场景如下：

正常页面可能划分三部分：
1.头部导航
2.内容主体
3.底部功能按钮

操作如下，发生 dom 变化

1.手势向上滚动的时候，自动隐藏底部功能按钮，此时内容主体的 dom 高度变化
2.手势向下滚动的时候，自动显示底部功能按钮，此时内容主体的 dom 高度变化

当这种上述场景的时候，希望能用 css 的 calc 函数去自动计算 list 虚拟滚动的容器高度

## 其它

无

**Comment by szg2008** [comment]
已经修复，目前支持动态修改高度，但是字符串需要自己解决下，源码中不考虑支持哈
