### ISSUE TITLE
[question] 引入外部微信小程序组件，编译时拉下个wxs没挪到dist目录，有什么办法吗

### ISSUE THREAD

**Issue by SHpoi** [jdf2e/nutui#1527]
使用的是vue3版本来编译的微信小程序。在引入一个原生小程序日历组件的时候，发现虽然通过 usingComponents 可以把原生小程序组件挪到dist目录，但是落下个wxs的文件没挪过去，现在还得我自己在dist目录里把文件拖过去。想问下有没有好点的办法？
<img width="671" alt="Snipaste_2022-08-02_11-23-41" src="https://user-images.githubusercontent.com/18532072/182285451-ed9d4253-5585-4bdb-92f0-cfefb4b22938.png">

**Comment by SHpoi** [comment]
这个问题已经解决，方法是在mini.webpackChain引入自定义插件，在compiler.hooks.done.tap里执行cp命令。
代码虽然不多，却发现有点折腾，最先是放在在config.plugin里的，发现里面配置的是taro插件，按照taro文档搞了一会发现老是报错，后面才在webpackChain里开搞的。

**Comment by SHpoi** [comment]
看看还有没有更好的解决方式

**Comment by richard1015** [comment]
@Chen-jj

**Comment by Chen-jj** [comment]
@SHpoi 配置一下 [copy](https://docs.taro.zone/docs/config-detail#copy)
