### ISSUE TITLE
第一次使用这个框架。

### ISSUE THREAD

**Issue by relaxgithub** [jdf2e/nutui#153]
按照说明文档，使用 gaeaCLI 报很多错误。
环境 ： Mac OS  Node(v10.13.0) npm(6.4.1).

于是换另外一种方式，npm install @nutui/nutui --save

`import NutUI from '@nutui/nutui'
import '@nutui/nutui/dist/nutui.css'

Vue.use(NutUI)

new Vue({
  el: '#app',
  render: h => h(App)
})
`

错误报路径在你们的框架内部。

ERROR in ../node_modules/@nutui/nutui/dist/nutui.js
Module not found: Error: Can't resolve 'vue' in '/Users/relax/Desktop/代码/前端学习/CodeForVue/node_modules/@nutui/nutui/dist'
 @ ../node_modules/@nutui/nutui/dist/nutui.js 8:27-41
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js

请问如何解决？

**Comment by famanoder** [comment]
请先确认您已经安装了 `vue`：
```js
npm i vue
// or
yarn add vue
```
