### ISSUE TITLE
[bug]小程序input不支持动态修改type属性

### ISSUE THREAD

**Issue by haohan88615** [jdf2e/nutui#1532]
@tarojs/taro

小程序input组件不支持动态修改type属性

password和text切换没有用

h5可以

**Comment by ailululu** [comment]
你好 @haohan88615 , 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/s/eh6ck?resolutionWidth=414&resolutionHeight=736) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

**Comment by ailululu** [comment]
> @tarojs/芋头
> 
> 小程序input组件不支持动态修改type属性
> 
> password和text切换没有用
> 
> h5可以

在微信小程序下，input 的 type 是无法动态赋值的，可以用v-if来动态切换input。
代码示例：
```
<template v-if=state.isShow>
    <nut-input type="text" placeholder="文本" v-model="state.val1" label="文本" />
</template>
<template v-else>
    <nut-input type="password" placeholder="文本" v-model="state.val1" label="文本" />
</template>
```
