### ISSUE TITLE
Cannot read properties of undefined (reading 'href')[bug]

### ISSUE THREAD

**Issue by MrWws** [jdf2e/nutui#1533]
## 问题描述

![image](https://user-images.githubusercontent.com/30725247/182809023-d9637206-4e50-4fe7-985a-279e7945355b.png)
我使用了一些按钮进行路由的跳转，但点击按钮，报错
最小化的 GitHub 仓库
## 预期的行为和实际行为
预期的行为：点击按钮跳转到另一个页面
实际行为：点击按钮路由改变页面不跳转，最小化仓库点击申请授信按钮跳转页面成功，但刷新/creditApplication对应的页面会产生上图的报错
## 相关环境信息
- **操作系统**：window10
- **Node 版本**：v16.16.0
- **NutUI 版本**：  3.1.22
- **Vue 版本**：3.2.36
- **引用方式**：  npm

**Comment by MrWws** [comment]
> 你好 @MrWws, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/s/eh6ck?resolutionWidth=414&resolutionHeight=736) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

已提供

**Comment by richard1015** [comment]
项目中的复现步骤提供一下

**Comment by Drjingfubo** [comment]
<img width="980" alt="image" src="https://user-images.githubusercontent.com/50685476/184571198-76f849c6-965b-44cd-8a9d-727e600e8c34.png">
报错原因找到了，感谢反馈，因为这里刷新页面的时候传了个-1的值，导致组件内部找不到对应的项，我后续优化一下组件内部，当value值小于0时，默认为0.

**Comment by Drjingfubo** [comment]
<img width="968" alt="image" src="https://user-images.githubusercontent.com/50685476/184590801-15cadcbd-963d-4bbd-b354-8d4f90f624ad.png">
报错原因找到了，感谢反馈，因为这里刷新页面的时候传了个-1的值，导致组件内部找不到对应的项，我后续优化一下组件内部。
