### ISSUE TITLE
dialog 添加lockBgScroll=true 关闭页面不能滚动

### ISSUE THREAD

**Issue by treasureMoment** [jdf2e/nutui#154]
页面本身可以滚动，滚到到非第一页，关闭dailog时。body 上添加的top 属性未去掉。导致页面无法正常滚动

**Comment by famanoder** [comment]
`body` 上添加的 `top` 只在打开弹窗时生效，猜测是你的页面 `body` 上本身有固定定位的样式： `position: fixed;`；

**Comment by treasureMoment** [comment]
添加lockBgScroll=true 后 组件自动给添加的。dialog close后样式移除了。但是top你们没取消

**Comment by famanoder** [comment]
该问题已解决，请关注后续版本
