### ISSUE TITLE
[bug] tabs tabpane组件绑定pane-key后切换亮标显示错误

### ISSUE THREAD

**Issue by zengkaii** [jdf2e/nutui#1544]
## 问题描述

![image](https://user-images.githubusercontent.com/38418699/183666068-615770ef-1741-4f5c-86d5-693a67a56a9a.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
预期只亮一个下标

## 复现步骤，具体代码
文档代码示例修改成如下图就可以复现
![image](https://user-images.githubusercontent.com/38418699/183666213-babddd0b-76f5-43ea-8173-874129aa716d.png)

taro 最新版本3.2.1

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：vue3
- **引用方式**：  CDN / NPM ？

**Comment by szg2008** [comment]
https://github.com/NervJS/taro/issues/12199

**Comment by szg2008** [comment]
https://github.com/jdf2e/nutui/issues/1544  一起解决

**Comment by szg2008** [comment]
https://github.com/NervJS/taro/issues/12199。一起解决

**Comment by richard1015** [comment]
升级最新版本 3.2.2
