### ISSUE TITLE
[bug] Picker 选择器的 confirm事件接收的值不是最新的

### ISSUE THREAD

**Issue by eGluZl** [jdf2e/nutui#1545]
## 问题描述

以官网演示为例，基本用法处的例子，初次打开是在“南京市”，选择“无锡市”后点确认，值却是“NanJing”。

## 最小可复现仓库
> 官网例子可复现

## 预期的行为和实际行为
picker选中值后 confirm接收的值是最新的

## 相关环境信息
- **操作系统**：Windows 11
- **Node 版本**：14.20.0
- **NutUI 版本**： 3.2.1
- **Vue 版本**：3
- **引用方式**：  NPM

**Comment by couth** [comment]
我也遇到这个问题了，好大的坑

**Comment by 1055241046** [comment]
获取到最新的值会有延时，希望官方尽快修复，测试给我提了个bug,

**Comment by grace5925** [comment]
确实有同样的问题，要等滚动动画结束后才能获取到最新的值

**Comment by yangxiaolu1993** [comment]
可优先使用 [3.2.2-beta.1](https://www.npmjs.com/package/@nutui/nutui/v/3.2.2-beta.1)
