### ISSUE TITLE
[bug] Calendar start-date end-date 设置为 null 无效

### ISSUE THREAD

**Issue by Wuge11** [jdf2e/nutui#1548]
## 问题描述

根据文档设置 start-date 和 end-date 为 null 不限制开始和结束日期，结果还是为默认值

## 最小可复现仓库
> [https://codesandbox.io/s/summer-breeze-h5djtv?file=/src/App.vue](https://codesandbox.io/s/summer-breeze-h5djtv?file=/src/App.vue)

## 预期的行为和实际行为

**预期：**
> 所有日期都可选择

**实际：**
> 开始和结束还是为默认值

## 复现步骤，具体代码
`<nut-calendar
    type="range"
    :start-date="null"
    :end-date="null"
  />`

## 相关环境信息
- **操作系统**：macOs 12.4
- **Node 版本**：14.20.0
- **NutUI 版本**： 3.2.0
- **Vue 版本**：3.2.24
- **Taro 版本**：3.4.14
- **引用方式**：  NPM

**Comment by lkjh3214** [comment]
当传null时，默认为最近一年时间。如果需要特定时间，请自己指定
![image](https://user-images.githubusercontent.com/23164467/184266196-c70c3541-bb00-4e65-b6d3-19cac0861ab7.png)

**Comment by Wuge11** [comment]
> 

好吧，还以为null是不限制日期，感谢
