### ISSUE TITLE
能否加个侧边弹出的对话框

### ISSUE THREAD

**Issue by main2018** [jdf2e/nutui#155]
像这样从侧边弹出的
![image](https://user-images.githubusercontent.com/28427901/62114213-c3e17400-b2e8-11e9-9557-17f4503ac9c9.png)

**Comment by famanoder** [comment]
后续规划中，敬请期待！
如果有兴趣的话，您也可以给我们提 PR！`Drawer 抽屉`；

**Comment by main2018** [comment]
@famanoder 好的，感谢

**Comment by richard1015** [comment]
@main2018   Popup组件来了，满足你的需求上下左右  http://nutui.jd.com/#/Popup
