### ISSUE TITLE
nut-input 组件在视图滚动并进行输入时位置发生改变

### ISSUE THREAD

**Issue by canaanjin** [jdf2e/nutui#1550]
## 问题描述

在视图滚动后对nut-input组件进行编辑时 内容的位置发生了偏移
滚动越往下偏移的位置就越大

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
input的内容本应该在原有位置。如果靠下的话应该自动上推页面。
![1660205750756](https://user-images.githubusercontent.com/12317236/184091868-bb0aad00-a6aa-4b25-a086-2250a124caab.jpg)

## 相关环境信息
- **操作系统**：移动端三星S10
- **Node 版本**：v14.17.3
- **NutUI 版本**： @nutui/nutui-taro: ^3.2.0
- **Vue 版本**：^3.0.0
- **引用方式**：   NPM ？

**Comment by ailululu** [comment]
是小程序原生input导致的，在安卓机下，scroll-view里使用input，会出现输入内容上移错位的问题，建议在使用input时，不要使用scroll-view
