### ISSUE TITLE
[bug]Taro 3.5.13 打包之后 [ WXSS 文件编译错误] ./app.wxss  unexpected token ","

### ISSUE THREAD

**Issue by erdezhuang** [jdf2e/nutui#1551]
## 问题描述
Taro 3.5.13 运行之后 [ WXSS 文件编译错误] ./app.wxss  unexpected token ","
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/12458415/184300481-850c536c-579f-439b-a0f6-95ac5acc5b1a.png">

**Comment by richard1015** [comment]
taro 升级最新 3.5.6

**Comment by yangjisen** [comment]
> taro 升级最新 3.5.6

升级以后故障依旧

**Comment by 6xiaoxin** [comment]
我所有依赖升级到3.5.6后还是会

**Comment by 6xiaoxin** [comment]
我所有依赖升级到3.5.6后还是会

**Comment by zhouzhouya1** [comment]
这个问题有人解决吗，主要是什么原因导致的呀 我的taro版本：3.6.32
