### ISSUE TITLE
Taro-vue版本的图片组件什么时候完善？ [bug]

### ISSUE THREAD

**Issue by 893949088** [jdf2e/nutui#1552]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by yangxiaolu1993** [comment]
NutUI-Taro 的 Image  组件，直接使用 Taro 的 image 组件就好 https://taro-docs.jd.com/taro/docs/components/media/image/

**Comment by linjiangl** [comment]
建议在这个组件里面简单封装下，不然后面还要切换。
