### ISSUE TITLE
[bug] nut-picker 3.2.1 ios和android都会有重影叠加

### ISSUE THREAD

**Issue by LuEdision** [jdf2e/nutui#1555]
## 问题描述
nut-picker 3.2.1 ios和android都会有重影叠加，滚动会更加明显，很严重，完全影响体验

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
可查看我ios手机截图如下：
![origin_img_v2_9503b170-ed21-4634-a839-faad7b22b6fg](https://user-images.githubusercontent.com/63531046/184600611-0d44e031-a029-4dd6-918f-82c74f5494e9.jpg)
![origin_img_v2_d4477259-5f33-4a7a-9a37-ffc1367d3f4g](https://user-images.githubusercontent.com/63531046/184600629-295fcbc4-59c9-4994-ac8b-5b0965366d14.jpg)

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：14.x.x
- **NutUI 版本**： 3.2.1
- **Vue 版本**：3.x
- **引用方式**：  NPM

**Comment by richard1015** [comment]
先暂时 使用 three-dimensional = false   关闭3d 看看是否可解决
另外可以提供一下 复现仓库
复现设备型号：xxxx  ios 1.xx

**Comment by szg2008** [comment]
可安装新版本试试是否还存在此问题
