### ISSUE TITLE
[bug] range组件只能拖动不能点击

### ISSUE THREAD

**Issue by herodhb** [jdf2e/nutui#1558]
## 问题描述

range组件点击会报错
![4481660568932_ pic](https://user-images.githubusercontent.com/14303897/184640962-52465340-e3b6-49f5-90f1-fd52efe7a85d.jpg)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
https://github.com/herodhb/range_bug_demo.git

## 预期的行为和实际行为
在demo中可以拖动但无法点击

## 相关环境信息
- **操作系统**：macos
- **Node 版本**：16.15.0
- **NutUI 版本**： "@nutui/nutui-taro": "^3.2.1",
- **Vue 版本**："vue": "^3.0.0",
- **引用方式**：  NPM

**Comment by herodhb** [comment]
这个有说法吗

**Comment by Drjingfubo** [comment]
我用你的demo测试了一下，用的也是你仓库里的lock文件，  点击没问题呐 
![image](https://user-images.githubusercontent.com/50685476/188344942-419d1c34-f685-4ebe-9aca-2d82d0fe4bfe.png)

**Comment by Drjingfubo** [comment]
如果还有问题，请再次提交issuss或者加入NutUI沟通群
