### ISSUE TITLE
nuxt中如何改变主题

### ISSUE THREAD

**Issue by main2018** [jdf2e/nutui#156]
不生效！！
![image](https://user-images.githubusercontent.com/28427901/62340128-05546800-b511-11e9-86a4-d1964c4e60be.png)
![image](https://user-images.githubusercontent.com/28427901/62340056-c7574400-b510-11e9-982d-621f80a22b2c.png)
![image](https://user-images.githubusercontent.com/28427901/62340068-d76f2380-b510-11e9-949b-c5457682ea15.png)

**Comment by famanoder** [comment]
参考 [http://nutui.jd.com/#/theme](http://nutui.jd.com/#/theme)

您还需要在 `webpack` 的 `sass-loader` 中配置您定义的 `nutui-theme.scss`：
```js
{
    test: /\.(sa|sc)ss$/,
    use: [
        {
            loader: 'sass-loader',
            options: {
                data: `@import "./asset/css/custom.scss"; @import "@nutui/nutui/dist/styles/index.scss"; `,
            }
        }
    ]
}
```

**Comment by main2018** [comment]
@famanoder 多谢

**Comment by main2018** [comment]
已解决：
nuxt中定义主题
① yarn add @nuxtjs/style-resources
② nuxt.confog.js新增
     styleResources: {
        sass: ['@/assets/css/nutui-theme.scss', '@nutui/nutui/dist/styles/index.scss'],
     },
     modules: [
        '@nuxtjs/style-resources',
     ],

**Comment by renleiabc** [comment]
> 已解决：
> nuxt中定义主题
> ① yarn add @nuxtjs/style-resources
> ② nuxt.confog.js新增
> styleResources: {
> sass: ['@/assets/css/nutui-theme.scss', '@nutui/nutui/dist/styles/index.scss'],
> },
> modules: [
> '@nuxtjs/style-resources',
> ],
采用这个方法，引入@nutui/nutui/dist/styles/index.scss还是无效，无法解决问题

**Comment by renleiabc** [comment]
@richard1015 采用你那个方法，还是无效，请问还有什么还的建议吗？

**Comment by richard1015** [comment]
> @richard1015 采用你那个方法，还是无效，请问还有什么还的建议吗？

先加一下微信把，方便及时沟通  zhida51844712

**Comment by renleiabc** [comment]
加了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "richard1015"<notifications@github.com&gt;; 
发送时间: 2020年4月9日(星期四) 中午1:34
收件人: "jdf2e/nutui"<nutui@noreply.github.com&gt;; 
抄送: "海阔天空"<421796896@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jdf2e/nutui] nuxt中如何改变主题 (#156)





  
@richard1015 采用你那个方法，还是无效，请问还有什么还的建议吗？
  
先加一下微信把，方便及时沟通  zhida51844712
