### ISSUE TITLE
[bug]List页面 demo 代码无效果

### ISSUE THREAD

**Issue by garenlyu1993** [jdf2e/nutui#1560]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by garenlyu1993** [comment]
未解决呀，这个是你们官网的代码，点击在线调试的结果
![image](https://user-images.githubusercontent.com/73512013/187128167-0ed1dabd-784c-475b-920c-64f1fa0a12ad.png)

**Comment by eiinu** [comment]
> 未解决呀，这个是你们官网的代码，点击在线调试的结果 ![image](https://user-images.githubusercontent.com/73512013/187128167-0ed1dabd-784c-475b-920c-64f1fa0a12ad.png)

官方文档还未更新，最近会发版。
旧文档中 List 的 demo 缺少了样式部分代码，加在后面就可以了。
```
<style lang="scss">
body {
  width: 100%;
  height: 100vh;
}
#app {
  width: 100%;
  height: 100%;
}
.demo {
  height: 100%;
  .nut-cell {
    height: 100%;
  }
  .list-item {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 50px;
    margin-bottom: 10px;
    background-color: #f4a8b6;
    border-radius: 10px;
  }
}
</style>
```

**Comment by oldsyang** [comment]
貌似添加了你这个样式，也不起作用

**Comment by eiinu** [comment]
> 貌似添加了你这个样式，也不起作用

[在线调试](https://codehouse.jd.com/?source=share&type=vue&mainJs=Ly9pbXBvcnQgVkNvbnNvbGUgZnJvbSAidmPGDyI7Ci8vdmFyIHbIID0gbmV3yS8oKTsKx0J7IGNyZWF0ZUFwcCB9yEd1xELHIcQZxhcuL2FwcC7NHU51dFVJxx9AbnV0dWkvxQbKIsc2c2Nzc8sVzCwvZGlzdC9zdHlsZS7GJukAkihBcHApLnVzZSjFaSkubW91bnQoIiNhcHAiKTs=&appValue=PHRlbXBsYXRlPgogIDxkaXYgY2xhc3M9ImRlbW8ixBUgIDxoMj7ln7rnoYDnlKjms5U8L2gyxxpudXQtY2VsbMYPxxFsaXN0IDpoZWlnaHQ9IjUwIiA6xBNEYXRhPSJjb3VudCIgQHNjcm9sbC1ib3R0b209ImhhbmRsZVPFFcd3xVDoAJ8gdi1zbG90PSJ7IGl0ZW0gfcsl7gC5xGstxCTNIiAge8g6fcw5L2RpdstvL8hwyBQ8L+gA0sYSxhDoAPPHP8w3PHNjcmlwdCBsYW5nPSJ0cyI+CmltcG9ydCB7IG9uTeQA/mVkLCByZWFjdGl2ZSwgdG9SZWZzIH0gZnJvbSAndnVlJzsKZXjFM2RlZmF1bHQgewogIHByb3BzOiB7fSwKICBzZXR1cCgpxRkgIGNvbnN0IHN05AEoPclbKMYdxB91bnQ6IG5ldyBBcnJheSgxMDApLmZpbGwoMCnFJH0pOwrLSuwBjSA9ICgpID0+x2sgIGxldCBhcnIgPddRO8l2xEtsZW4gPeYAmy7lAIgubGVuZ3RoyCbLGs8oY29uY2F0KGFyci5tYXAoKOQBvTogbnVtYmVyLCBpbmRleMgP5QCgxGorxhggKyAxKecAiX3nANrpAXwo7gDP+gCB33bGdspwx28pxm9yZXR1cm4geyAuLi7mAeIoxVwpLO4BXn3EN30KfTsKPC/mAjrkAkN0eWxl5wJCc2Nz5AJEYm9keeUAtHdpZHRoOiAxMDAlxDvmA2bFEHZoOwp9CiNhcHDfKSXEKC7kA+HFKc4aICAu6ALixR7SIOQDQC7pA2bHJWRpc3BsYXk6IGZsZXjEJiAgYWxpZ27FJHM6IGNlbnRlcsYZanVzdGlmeS1jb250ZeQCmswd7wC3yn81MHDHWW1hcmdpbucEO8QryBliYWNrZ3JvdW5kLWNvbG9yOiAjZjRhOGI2xx9vcmRlci1yYWRpdXPKOH0KfeQBfeQBdD4K&scssValue=)
