### ISSUE TITLE
v3.2.0版本Picker滚动选择值后快速点击确定获取到的值不是最新值，有延时。

### ISSUE THREAD

**Issue by 1055241046** [jdf2e/nutui#1561]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by 1055241046** [comment]
<nut-picker
	id="courseSelect"
	v-model="state.selectCourse"
	:visible="state.showCourse"
	:columns="state.courseList"
	title="选择课程"
	@close="
		state.showCourse = false;
		state.showPickerFlag = false;
	"
	@confirm="courseOnConfirm"
	@change="courseOnChange"
	:threeDimensional="true"
/>

**Comment by yangxiaolu1993** [comment]
可优先使用 [3.2.2-beta.1](https://www.npmjs.com/package/@nutui/nutui/v/3.2.2-beta.1)
