### ISSUE TITLE
[question]滚动加载touchstart事件和click共存的问题

### ISSUE THREAD

**Issue by luxiang0412** [jdf2e/nutui#1564]
## 你想知道什么？

滚动加载 下拉刷新好像有点问题。
[https://github.com/jdf2e/nutui/blob/next/src/packages/__VUE/infiniteloading/index.vue#L201-L208](https://github.com/jdf2e/nutui/blob/next/src/packages/__VUE/infiniteloading/index.vue#L201-L208)
这里的判断逻辑，当beforeScrollTop为0的时候。列表项被点击的时候会触发touchstart事件，然后state.isTouching变为true。这个时候再次点击列表项的时候会触发下拉加载。

## 描述你考虑过的替代方案

我想...

## 其它

无

**Comment by luxiang0412** [comment]
测试代码：[https://github.com/luxiang0412/nut-infiniteloading-test](https://github.com/luxiang0412/nut-infiniteloading-test)
![order_insert](https://user-images.githubusercontent.com/27472573/185746448-c6819e89-aab8-4122-ae00-0c470f6cf70d.gif)

**Comment by yangxiaolu1993** [comment]
提供的 Demo 是 Taro 环境，但安装的缺失 @nutui/nutui，在Taro 环境下需要安装 nutui-Taro 包

**Comment by yangxiaolu1993** [comment]
> 提供的 Demo 是 Taro 环境，但安装的缺失 @nutui/nutui，在Taro 环境下需要安装 nutui-Taro 包

在 Taro 环境中，请直接使用 Taro 现有 ScrollView 组件开发 https://nutui.jd.com/#/zh-cn/component/infiniteloading-taro
