### ISSUE TITLE
[bug]nut-datepicker 只改变小时不改变分钟的时候，confirm 事件value 不变

### ISSUE THREAD

**Issue by wy1037** [jdf2e/nutui#1566]
nut-datepicker 组件
在只改变小时，不改变分钟的时候，confirm 事件得到的 value 是旧值。
例如：
2022-01-02 10:11  改为 2022-01-02 12:11 后，
confirm 事件 selectedValue里的内容是 改前的  2022-01-02 10:11  。

如果一次没有效果，多试两次就能看到效果

环境：
  cdn的方式引入NutUI组件库：
  <script src="https://cdn.jsdelivr.net/npm/@nutui/nutui/dist/nutui.umd.js"></script>
js 版本： @nutui/nutui v3.2.1 Tue Aug 09 2022 17:11:03 GMT+0800 (中国标准时间)

**Comment by yangxiaolu1993** [comment]
问题已经修复，在 3.2.2 版本发布

**Comment by yangxiaolu1993** [comment]
可优先使用 [3.2.2-beta.1](https://www.npmjs.com/package/@nutui/nutui/v/3.2.2-beta.1)
