### ISSUE TITLE
[question] Calendar组件可以自定义多个选中颜色吗？

### ISSUE THREAD

**Issue by sunWhereCode** [jdf2e/nutui#1568]
## 你想知道什么？

你好，我想知道这个项目是否可以 Calendar组件可以自定义多个选中颜色吗？
![image](https://user-images.githubusercontent.com/1262247/185068795-e9f7a91c-fb8c-4444-ab6d-14b5a7c4972f.png)

## 描述你考虑过的替代方案

修改源码打包替换组件是否可行

## 其它

无

**Comment by richard1015** [comment]
https://nutui.jd.com/theme/#/base 在线主题定制工具

自定义多个选中颜色？ 指什么，可以具体描述一下 使用场景

**Comment by szg2008** [comment]
这个可通过自定义样式解决
