### ISSUE TITLE
nutui组件大部分都编译成image组件

### ISSUE THREAD

**Issue by mulianju** [jdf2e/nutui#1569]
nutui组件大部分都编译成image组件了，导致页面错乱
![543a5944cac2c45b30482df22686f28](https://user-images.githubusercontent.com/9363010/185082031-e79ee405-9fd4-4eb2-8887-51a4e5e5f985.jpg)
![3b9f13b765afe7420acf93ae76445b2](https://user-images.githubusercontent.com/9363010/185082102-3dc2ef0d-80c1-4007-bb87-572bf183cbf8.jpg)

demo源码在附件里，页面pages/financial/interest/interest
[calculator.zip](https://github.com/jdf2e/nutui/files/9358190/calculator.zip)

**Comment by eiinu** [comment]
测试了一下是正常的

**Comment by eiinu** [comment]
![image](https://user-images.githubusercontent.com/44915689/185089747-b21b8617-152e-408e-9c9d-5341739482cd.png)

**Comment by mulianju** [comment]
请问环境是怎样的呢  node版本什么的  对源码有什么改动吗

**Comment by eiinu** [comment]
> 请问环境是怎样的呢 node版本什么的 对源码有什么改动吗

我是直接 `pnpm install & pnpm build:weapp` ，没有修改内容，node 版本号是 `v14.20.0`。你可以重新 install 试一试

**Comment by mulianju** [comment]
切换了node版本，之前10.14.2确实不行，换了v14.19.3，现在可以了，感谢大佬
