### ISSUE TITLE
picker省市区联动

### ISSUE THREAD

**Issue by lanzhsh** [jdf2e/nutui#157]
你们省市区目前使用好麻烦,还要把 json 列出来,
啥时候可以优化一下

**Comment by SoftwareWPF** [comment]
这个省市区相对于其它的使用着真的心累

**Comment by zhenyulei** [comment]
😭picker这个组件，本意是拾取器组件，支持用户自定义json数据，这样的话可以根据配置数据渲染，具有灵活性。不过感谢您的建议，后续我们考虑增加传入的类型是省市区联动的话，给定默认的json数据。

**Comment by zhenyulei** [comment]
😭picker这个组件，本意是拾取器组件，支持用户自定义json数据，这样的话可以根据配置数据渲染，具有灵活性。不过感谢您的建议，后续我们考虑增加传入的类型是省市区联动的话，给定默认的json数据。

**Comment by lanzhsh** [comment]
是的呢,省市联动就应该和 picker 分开

**Comment by richard1015** [comment]
月底新版本 会新增一个地址组件了，敬请期待

**Comment by richard1015** [comment]
v2.2.5 已新增地址组件

http://nutui.jd.com/#/Address
