### ISSUE TITLE
[bug]Sticky 粘性布局,在微信小程序客户端，吸顶后，再下拉恢复到原始位置，出现跳动现象

### ISSUE THREAD

**Issue by lingdulib** [jdf2e/nutui#1571]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 3.2.1
- **Vue 版本**：
- **引用方式**：   NPM

**Comment by szg2008** [comment]
已修复，下周发版，感谢反馈～
