### ISSUE TITLE
[bug]Picker 选择器 多级联动，三级省市区设置默认值，在小程序端只有前两级会生效，第三级默认第一条，不会选中设置的默认值

### ISSUE THREAD

**Issue by lingdulib** [jdf2e/nutui#1572]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：3.2.1
- **Vue 版本**：
- **引用方式**： NPM

**Comment by yangxiaolu1993** [comment]
提供一下可以复现的小版本代码

**Comment by lingdulib** [comment]
> 提供一下可以复现的小版本代码
const areaCurrentDefault = ref(['420000', '420100', '420111'])
rawCitiesData=[{
		"text": "北京市",
		"value": "110000",
		"children": [{
			"text": "北京市",
			"value": "110100",
			"children": [{
					"text": "东城区",
					"value": "110101"
				},

				{
					"text": "西城区",
					"value": "110102"
				},

				{
					"text": "朝阳区",
					"value": "110105"
				},

				{
					"text": "丰台区",
					"value": "110106"
				},

				{
					"text": "石景山区",
					"value": "110107"
				},

				{
					"text": "海淀区",
					"value": "110108"
				},

				{
					"text": "门头沟区",
					"value": "110109"
				},

				{
					"text": "房山区",
					"value": "110111"
				},

				{
					"text": "通州区",
					"value": "110112"
				},

				{
					"text": "顺义区",
					"value": "110113"
				},

				{
					"text": "昌平区",
					"value": "110114"
				},

				{
					"text": "大兴区",
					"value": "110115"
				},

				{
					"text": "怀柔区",
					"value": "110116"
				},

				{
					"text": "平谷区",
					"value": "110117"
				},

				{
					"text": "密云区",
					"value": "110118"
				},

				{
					"text": "延庆区",
					"value": "110119"
				}
			]
		}]
	},

	{
		"text": "天津市",
		"value": "120000",
		"children": [


			{
				"text": "天津市",
				"value": "120100",
				"children": [


					{
						"text": "河西区",
						"value": "120103"
					},

					{
						"text": "和平区",
						"value": "120101"
					},

					{
						"text": "河东区",
						"value": "120102"
					},

					{
						"text": "南开区",
						"value": "120104"
					},

					{
						"text": "河北区",
						"value": "120105"
					},

					{
						"text": "红桥区",
						"value": "120106"
					},

					{
						"text": "东丽区",
						"value": "120110"
					},

					{
						"text": "西青区",
						"value": "120111"
					},

					{
						"text": "津南区",
						"value": "120112"
					},

					{
						"text": "北辰区",
						"value": "120113"
					},

					{
						"text": "武清区",
						"value": "120114"
					},

					{
						"text": "宝坻区",
						"value": "120115"
					},

					{
						"text": "滨海新区",
						"value": "120116"
					},

					{
						"text": "宁河区",
						"value": "120117"
					},

					{
						"text": "静海区",
						"value": "120118"
					},

					{
						"text": "蓟州区",
						"value": "120119"
					}
				]
			}
		]
	},

	{
		"text": "湖北省",
		"value": "420000",
		"children": [


			{
				"text": "武汉市",
				"value": "420100",
				"children": [


					{
						"text": "江岸区",
						"value": "420102"
					},

					{
						"text": "江汉区",
						"value": "420103"
					},

					{
						"text": "硚口区",
						"value": "420104"
					},

					{
						"text": "汉阳区",
						"value": "420105"
					},

					{
						"text": "武昌区",
						"value": "420106"
					},

					{
						"text": "青山区",
						"value": "420107"
					},

					{
						"text": "洪山区",
						"value": "420111"
					},

					{
						"text": "东西湖区",
						"value": "420112"
					},

					{
						"text": "汉南区",
						"value": "420113"
					},

					{
						"text": "蔡甸区",
						"value": "420114"
					},

					{
						"text": "江夏区",
						"value": "420115"
					},

					{
						"text": "黄陂区",
						"value": "420116"
					},

					{
						"text": "新洲区",
						"value": "420117"
					}
				]
			},

			{
				"text": "黄石市",
				"value": "420200",
				"children": [


					{
						"text": "下陆区",
						"value": "420204"
					},

					{
						"text": "黄石港区",
						"value": "420202"
					},

					{
						"text": "西塞山区",
						"value": "420203"
					},

					{
						"text": "铁山区",
						"value": "420205"
					},

					{
						"text": "大冶市",
						"value": "420281"
					},

					{
						"text": "阳新县",
						"value": "420222"
					}
				]
			},

			{
				"text": "十堰市",
				"value": "420300",
				"children": [


					{
						"text": "茅箭区",
						"value": "420302"
					},

					{
						"text": "张湾区",
						"value": "420303"
					},

					{
						"text": "郧阳区",
						"value": "420304"
					},

					{
						"text": "丹江口市",
						"value": "420381"
					},

					{
						"text": "郧西县",
						"value": "420322"
					},

					{
						"text": "竹山县",
						"value": "420323"
					},

					{
						"text": "竹溪县",
						"value": "420324"
					},

					{
						"text": "房县",
						"value": "420325"
					}
				]
			},

			{
				"text": "宜昌市",
				"value": "420500",
				"children": [


					{
						"text": "西陵区",
						"value": "420502"
					},

					{
						"text": "伍家岗区",
						"value": "420503"
					},

					{
						"text": "点军区",
						"value": "420504"
					},

					{
						"text": "猇亭区",
						"value": "420505"
					},

					{
						"text": "夷陵区",
						"value": "420506"
					},

					{
						"text": "宜都市",
						"value": "420581"
					},

					{
						"text": "当阳市",
						"value": "420582"
					},

					{
						"text": "枝江市",
						"value": "420583"
					},

					{
						"text": "远安县",
						"value": "420525"
					},

					{
						"text": "兴山县",
						"value": "420526"
					},

					{
						"text": "秭归县",
						"value": "420527"
					},

					{
						"text": "长阳土家族自治县",
						"value": "420528"
					},

					{
						"text": "五峰土家族自治县",
						"value": "420529"
					}
				]
			},

			{
				"text": "襄阳市",
				"value": "420600",
				"children": [


					{
						"text": "襄城区",
						"value": "420602"
					},

					{
						"text": "樊城区",
						"value": "420606"
					},

					{
						"text": "襄州区",
						"value": "420607"
					},

					{
						"text": "老河口市",
						"value": "420682"
					},

					{
						"text": "枣阳市",
						"value": "420683"
					},

					{
						"text": "宜城市",
						"value": "420684"
					},

					{
						"text": "南漳县",
						"value": "420624"
					},

					{
						"text": "谷城县",
						"value": "420625"
					},

					{
						"text": "保康县",
						"value": "420626"
					}
				]
			},

			{
				"text": "鄂州市",
				"value": "420700",
				"children": [


					{
						"text": "鄂城区",
						"value": "420704"
					},

					{
						"text": "梁子湖区",
						"value": "420702"
					},

					{
						"text": "华容区",
						"value": "420703"
					}
				]
			},

			{
				"text": "荆门市",
				"value": "420800",
				"children": [


					{
						"text": "东宝区",
						"value": "420802"
					},

					{
						"text": "掇刀区",
						"value": "420804"
					},

					{
						"text": "钟祥市",
						"value": "420881"
					},

					{
						"text": "京山县",
						"value": "420821"
					},

					{
						"text": "沙洋县",
						"value": "420822"
					}
				]
			},

			{
				"text": "孝感市",
				"value": "420900",
				"children": [


					{
						"text": "孝南区",
						"value": "420902"
					},

					{
						"text": "应城市",
						"value": "420981"
					},

					{
						"text": "安陆市",
						"value": "420982"
					},

					{
						"text": "汉川市",
						"value": "420984"
					},

					{
						"text": "孝昌县",
						"value": "420921"
					},

					{
						"text": "大悟县",
						"value": "420922"
					},

					{
						"text": "云梦县",
						"value": "420923"
					}
				]
			},

			{
				"text": "荆州市",
				"value": "421000",
				"children": [


					{
						"text": "沙市区",
						"value": "421002"
					},

					{
						"text": "荆州区",
						"value": "421003"
					},

					{
						"text": "石首市",
						"value": "421081"
					},

					{
						"text": "洪湖市",
						"value": "421083"
					},

					{
						"text": "松滋市",
						"value": "421087"
					},

					{
						"text": "公安县",
						"value": "421022"
					},

					{
						"text": "监利县",
						"value": "421023"
					},

					{
						"text": "江陵县",
						"value": "421024"
					}
				]
			},

			{
				"text": "黄冈市",
				"value": "421100",
				"children": [


					{
						"text": "黄州区",
						"value": "421102"
					},

					{
						"text": "麻城市",
						"value": "421181"
					},

					{
						"text": "武穴市",
						"value": "421182"
					},

					{
						"text": "团风县",
						"value": "421121"
					},

					{
						"text": "红安县",
						"value": "421122"
					},

					{
						"text": "罗田县",
						"value": "421123"
					},

					{
						"text": "英山县",
						"value": "421124"
					},

					{
						"text": "浠水县",
						"value": "421125"
					},

					{
						"text": "蕲春县",
						"value": "421126"
					},

					{
						"text": "黄梅县",
						"value": "421127"
					}
				]
			},

			{
				"text": "咸宁市",
				"value": "421200",
				"children": [


					{
						"text": "咸安区",
						"value": "421202"
					},

					{
						"text": "赤壁市",
						"value": "421281"
					},

					{
						"text": "嘉鱼县",
						"value": "421221"
					},

					{
						"text": "通城县",
						"value": "421222"
					},

					{
						"text": "崇阳县",
						"value": "421223"
					},

					{
						"text": "通山县",
						"value": "421224"
					}
				]
			},

			{
				"text": "随州市",
				"value": "421300",
				"children": [


					{
						"text": "曾都区",
						"value": "421303"
					},

					{
						"text": "广水市",
						"value": "421381"
					},

					{
						"text": "随县",
						"value": "421321"
					}
				]
			},

			{
				"text": "恩施土家族苗族自治州",
				"value": "422800",
				"children": [


					{
						"text": "恩施市",
						"value": "422801"
					},

					{
						"text": "利川市",
						"value": "422802"
					},

					{
						"text": "建始县",
						"value": "422822"
					},

					{
						"text": "巴东县",
						"value": "422823"
					},

					{
						"text": "宣恩县",
						"value": "422825"
					},

					{
						"text": "咸丰县",
						"value": "422826"
					},

					{
						"text": "来凤县",
						"value": "422827"
					},

					{
						"text": "鹤峰县",
						"value": "422828"
					}
				]
			},

			{
				"text": "省直辖县级行政单位",
				"value": "429000",
				"children": [


					{
						"text": "仙桃市",
						"value": "429004"
					},

					{
						"text": "潜江市",
						"value": "429005"
					},

					{
						"text": "天门市",
						"value": "429006"
					},

					{
						"text": "神农架林区",
						"value": "429021"
					}
				]
			}
		]
	},
]
 <nut-picker
      v-model="areaCurrentDefault"
      v-model:visible="cityShow"
      :columns="rawCitiesData"
      title="请选择城市"
      @confirm="confirm"
      @change="changeConfirm"
    />

> 提供一下可以复现的小版本代码

**Comment by lingdulib** [comment]
示例已提供，麻烦看下呢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jdf2e/nutui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 下午2:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jdf2e/nutui] [bug]Picker 选择器 多级联动，三级省市区设置默认值，在小程序端只有前两级会生效，第三级默认第一条，不会选中设置的默认值 (Issue #1572)





 
提供一下可以复现的小版本代码

**Comment by 641869306** [comment]
我也遇到同样问题。希望官方可以解决下~

**Comment by yangxiaolu1993** [comment]
感谢对NutUI的支持，问题已经修复，会在下个版本 3.2.2 发布

**Comment by szg2008** [comment]
已发布最新版本，可安装试试
