### ISSUE TITLE
[bug] ImagePreview taro 

### ISSUE THREAD

**Issue by myxfeng** [jdf2e/nutui#1573]
Nutui  v3.2.1
 createElementVNode("image", {
                    mode: "aspectFit",
                    src: item.src,
                    class: "nut-imagepreview-img"
                  }, null, 8, _hoisted_1)
                ]),

"image" dom 节点  用taro  编译h5 后 image  标签图片不显示 
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by yangxiaolu1993** [comment]
首先感谢你对 NutUI 的支持。抱歉你提出的问题我没太理解，Issue 标题为 Imagepreview，但是创建的 dom 并不是 <nut-imagepreview>，请自查一下是不是使用错误

**Comment by Jonny-Zou** [comment]
> 首先感谢你对 NutUI 的支持。抱歉你提出的问题我没太理解，Issue 标题为 Imagepreview，但是创建的 dom 并不是 ，请自查一下是不是使用错误

编译后的产物是image标签，h5需要img标签，小程序则是image

编写了一个简单的例子复现了：https://github.com/jdf2e/nutui/issues/1642#issue-1364208180
原因和这位朋友说的一样：https://github.com/jdf2e/nutui/issues/1478#issue-1308994049

**Comment by Drjingfubo** [comment]
#1642跟进

**Comment by Drjingfubo** [comment]
https://github.com/jdf2e/nutui/issues/1642#issue-1364208180 跟进
