### ISSUE TITLE
uploader 组件 before-delete  使用Promise控制是否删除无效[bug]

### ISSUE THREAD

**Issue by KwangHosea** [jdf2e/nutui#1576]
## 问题描述

uploader 组件 before-delete  使用Promise控制是否删除无效
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
`<nut-uploader 
:before-delete="removeFile"
/>`
`
const removeFile = (file) => {
          return new Promise((resolve, reject) => {
               resolve(false);
          }
}
`

## 预期的行为和实际行为
应该不删除已上传的附件，但实际删除。只支持直接返回 true或 false,
原本时希望结合Dialog组件，在confirm后点ok删除，cancel取消时不删除

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
3.2.1
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？
npm

**Comment by WangXang** [comment]
这个BUG修复了么？

**Comment by KwangHosea** [comment]
没呢




| |
邝活新
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2022年09月16日 15:33，WangXang 写道：

这个BUG修复了么？

**Comment by szg2008** [comment]
升级到最新版本v3.2.3尝试下
