### ISSUE TITLE
nut-picker 报错[bug]

### ISSUE THREAD

**Issue by gmdesting** [jdf2e/nutui#1578]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
3.X的下拉菜单就出问题，下拉结果逻辑就错了，你们官网的例子就是给的错的，也拿出做框架？最基础的picker都没法保证，拜托请谨慎点！！！！！！

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by gmdesting** [comment]
找到问题了，要等滑动效果完成后静止状态选值才有效果，如果碰到快速操作怎么处理，目前是下拉菜单得值和显示得值不同。

**Comment by KwangHosea** [comment]
> 找到问题了，要等滑动效果完成后静止状态选值才有效果，如果碰到快速操作怎么处理，目前是下拉菜单得值和显示得值不同。

也遇到了，这个bug在很早前就有人提了，但一直没有修复，并且手机上滚动卡顿情况还比较严重。

**Comment by yangxiaolu1993** [comment]
问题已经修复，在下个版本 3.2.2 发布

**Comment by yangxiaolu1993** [comment]
可优先使用 [3.2.2-beta.1](https://www.npmjs.com/package/@nutui/nutui/v/3.2.2-beta.1)
