### ISSUE TITLE
[bug] Calendar 日历组件滚动方法无效

### ISSUE THREAD

**Issue by KwangHosea** [jdf2e/nutui#1579]
## 问题描述

引用Calendar 日历组件，点开后需要定位到当前年月，但日期范围可以从2000年开始，默认会打开会显示2000年1月面板，通过scrollToDate方法想初始定位到当前年月，引用后无效
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
很多情况组件初始无需指定起止范围.
API文档中开始截止日期定义的描述 start-date  开始日期， 如果不限制开始日期传 null，一般人都会理解为传null就不限制，但实际行为确实限制为今天，这个在之前的问题中也由人提，相信很多人都会踩这个坑，希望默认就是不限制时间范围的，并且如果未传值的时候打开时是定位到当前年月面板，而不是定位到开始日期的面板。

## 复现步骤，具体代码
<nut-calendar
      v-model:visible="calendarVisible"
      :default-value="calendarVal"
      type="range"
      :start-date="startDate"
      :end-date="endDate"
      @close="closeCalendar"
      @choose="chooseDate"
      ref="calendarRef"
    >
    </nut-calendar>
onMounted(()=>{
      //空默认显示为当前年月面板
        calendarRef.value.scrollToDate('2021-12-01');
 })

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
3.2.1
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？
 npm

**Comment by lkjh3214** [comment]
你好，感谢你的反馈。
1.日期范围的限制，有出于初次渲染性能问题的考量。
2.start-date默认为今天的问题，之后会对文档进行调整。
3.初始定位问题，后续迭代中，可以考虑添加一个设置字段。不过目前暂不支持。只能通过设置默认值调整
4. scrollToDate方法， 只有日历组件打开后才能使用。
