### ISSUE TITLE
scroller组件横向滑动区域,不能上下滑动页面

### ISSUE THREAD

**Issue by wananzys** [jdf2e/nutui#158]
有横向滑动的区域,手指在该区域不能上下滑动页面,极其影响用户体验,请问怎样解决?

**Comment by zhenyulei** [comment]
你好，感谢你提的建议，可以在源码中scroller组件中的 touchMove 事件中删掉 阻止默认事件 并且删掉css中的nut-hor-list类中的touch-action: none;样式。当然如果您不着急的话，我们经过调研后可以增加该功能，再次感谢建议。
