### ISSUE TITLE
[bug]picker组件修改参数three-dimensional为false出现莫名的报错

### ISSUE THREAD

**Issue by MKP999** [jdf2e/nutui#1580]
## 问题描述

picker组件修改参数three-dimensional为false出现莫名的报错
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
<nut-picker :three-dimensional="false" v-model:visible="show" :columns="columns" title="申请原因" @change="change"
      @confirm="confirm" id="reason-picker">
    </nut-picker>

仅添加了 :three-dimensional="false" 便报错，删掉没有问题

## 预期的行为和实际行为
阻塞流程

## 相关环境信息
- **操作系统**：window
- **Node 版本**：12.18.1
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？
![1661156988538](https://user-images.githubusercontent.com/56329487/185876902-f2dd5f2e-638c-4b8b-a9d1-d08a7b34b065.jpg)

**Comment by yangxiaolu1993** [comment]
问题已修复，可 [3.2.2-beta.1](https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.2-beta.1) 版本
