### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by xzy-96** [jdf2e/nutui#1585]
## 问题描述
组件tab 下面 还有tab 就是嵌套tab
tab
---   tabpane
 ------     tab
 ---------        tabpane
   这样就报错了

## 相关环境信息
- **操作系统**：window
- **Node 版本**：16
- **NutUI 版本**： 3.2.1
- **Vue 版本**：3.2.24
- **引用方式**：   NPM

**Comment by xzy-96** [comment]
[NutUI] <Tabs> 当前未找到 TabPane 组件元素 , 请检查 .(env: Windows,mp,1.06.2208010; lib: 2.17.0)

._node_modules_@nutui_nutui-taro_dist_packages__es_Tabs.js:95
 [NutUI] <Tabs> 请检查 v-model 值是否为 paneKey ,如 paneKey 未设置，请采用下标控制 .(env: Windows,mp,1.06.2208010; lib: 2.17.0)

**Comment by eiinu** [comment]
nut-tabs 是支持嵌套的，这里有一个 demo：[CodeSandbox](https://codesandbox.io/s/nutui3-vite-demo-forked-6hy4nd?file=/src/App.vue).
报错 1 原因：某一个 nut-tabs 内部没有找到 nut-tabpane。
报错 2 原因：nut-tabs 的 v-model 值与内部所有 nut-tabpane 的标识 paneKey 都不一致。

**Comment by forestRhapsody** [comment]
<Tabs> 当前未找到 TabPane 组件元素 , 请检查 .(env: macOS,mp,1.06.2208010; lib: 2.25.1)
[NutUI] <Tabs> 请检查 v-model 值是否为 paneKey ,如 paneKey 未设置，请采用下标控制 .(env: macOS,mp,1.06.2208010; lib: 2.25.1)

我升级到3.2.1后也是报这个错，之前版本使用正常，不过不影响功能

**Comment by Drjingfubo** [comment]
https://github.com/jdf2e/nutui/issues/1544  3.2.2修复

**Comment by Drjingfubo** [comment]
#1636  报错为一个问题 3.2.2版本解决
