### ISSUE TITLE
[bug]taro 3.5.4版本按需引入@nutui/nutui-taro报错

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui#1588]
## 问题描述

taro 3.5.4版本按需引入nutui报错
<img width="1590" alt="image" src="https://user-images.githubusercontent.com/43030980/186179278-f45658bc-2b38-408b-bfc5-93062484a8fc.png">

## 最小可复现仓库
https://github.com/yanbowe/nutui-report

## 预期的行为和实际行为
正常运行

## 复现步骤，具体代码
pnpm install
pnpm dev:h5
把app.ts中的nutui相关代码注释掉就可以编译成功

## 相关环境信息
- **操作系统**：
- **Node 版本**：v16.15.0
- **NutUI 版本**： "@nutui/nutui-taro": "^3.2.1",
- **taro版本**：3.5.4
- **引用方式**：  NPM

**Comment by eiinu** [comment]
可以尝试在 Taro 项目 config/index.js 中的 h5 部分增加如下配置：
```
h5: {
    ...
    esnextModules: ['nutui-taro'],
    ...
}
```

**Comment by yanbowe** [comment]
> 可以尝试在 Taro 项目 config/index.js 中的 h5 部分增加如下配置：
> 
> ```
> h5: {
>     ...
>     esnextModules: ['nutui-taro'],
>     ...
> }
> ```

谢谢，可以运行了
