### ISSUE TITLE
"@nutui/nutui-taro": "^3.2.1" taro3.5.2 编译到h5 报错

### ISSUE THREAD

**Issue by mz-dfhp** [jdf2e/nutui#1589]
## 问题描述

![image](https://user-images.githubusercontent.com/63582593/186185458-5638f12d-2247-420c-ad75-76a67162ce60.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：window
- **Node 版本**：16.17.0
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：^3.0.0
- **引用方式**：  CDN / NPM ？yarn

**Comment by eiinu** [comment]
可以尝试在 Taro 项目 config/index.js 中的 h5 部分增加如下配置：
```
h5: {
    ...
    esnextModules: ['nutui-taro'],
    ...
}
```

**Comment by Jiang928** [comment]
> 可以尝试在 Taro 项目 config/index.js 中的 h5 部分增加如下配置：
> 
> ```
> h5: {
>     ...
>     esnextModules: ['nutui-taro'],
>     ...
> }
> ```

刚试了下, 可以了
