### ISSUE TITLE
[suggest] nut-picker选择器优化建议

### ISSUE THREAD

**Issue by mulianju** [jdf2e/nutui#1591]
1. nut-picker选择器滚动动画太慢了，接近目标时候更慢，经常视觉上我已经滑动到指定位置了，然后点击确认后，选择的选项却还是上一次的
2. 另外nut-picker的弹层，建议做成fix定位，不然我放到局部模块组件的时候，会受模块本身的定位影响

**Comment by yangxiaolu1993** [comment]
首先非常感谢你对NutUI的支持。下面是对每个建议的回复：
建议一：nut-picker 组件已经做了优化，并暴露了控制滚动速度的 props swipe-duration，并在 3.2.2 版本发布。
建议二：nut-picker 的当前使用的是 fixed 定位，你所描述的场景可以 提供一个小版本的 Demo 吗？

**Comment by mulianju** [comment]
[test.zip](https://github.com/jdf2e/nutui/files/9429225/test.zip)
不好意思，之前看表现就武断的判断是absolute定位了，仔细看了一下解析代码，确实是fixed，不过默认状态下和tab组件嵌套还是有一些问题的

**Comment by yangxiaolu1993** [comment]
> 

由于 Picker 组件设计的原因，暂时是不能放到 Tabs 、Form 这些组件中的，将 Picker 放到外部使用就可以了

**Comment by mulianju** [comment]
好的，辛苦大佬
