### ISSUE TITLE
[bug]官方小程序demo，涉及到picker 滚动非常卡顿，并且滚动picker时候，body也会跟着滑动

### ISSUE THREAD

**Issue by zengjingke** [jdf2e/nutui#1595]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by yongqcai** [comment]
@yangxiaolu1993 麻烦官方留意下这个问题

**Comment by yangxiaolu1993** [comment]
问题已经修改，可先试用 NutUI-Taro 3.2.3-beta.0 进行修改，此版本依赖 Taro 3.5.6
