### ISSUE TITLE
[question] 图片上传组件只支持 url上传吗？

### ISSUE THREAD

**Issue by ShawnZeng** [jdf2e/nutui#1596]
## 你想知道什么？
图片上传组件如下，需要有一个上传文件的url。
`<template>
  <nut-uploader :url="uploadUrl" v-model:file-list="defaultFileList" maximum="3" multiple></nut-uploader>
</template>`
小程序云开发上传文件不适用url，而是用类似以下API。

wx.cloud.uploadFile({
  cloudPath: 'example.png',
  filePath: '', // 文件路径
})

这种情况怎么办？难道我需要搭建一个HTTP服务来接收图片吗？

## 描述你考虑过的替代方案

是否可以使用:before-upload="beforeUpload" 来上传文件？然后我用一个假的url?

**Comment by richard1015** [comment]
:before-upload="beforeUpload"   最新版本已支持
