### ISSUE TITLE
来了，老弟~

### ISSUE THREAD

**Issue by Franslee** [jdf2e/nutui#16]
:tada::tada:欢迎大家使用NutUI组件库~ :tada::tada:

如果您在使用过程中遇到什么问题可通过 Issues 或邮件 nutui@jd.com 联系我们。

目前NutUI已在京东内外众多项目中应用，如果你的项目中也有用到，欢迎留言告诉我们，建议包含以下内容：

- 产品/项目：
- 链接：（如果可以）
- 公司或组织：（如果可以）
- 截图：（如果可以）
- Email：（如果可以）

> 如果不方便公开，可以通过邮件告诉我们。

您的支持是我们开发的动力。

欢迎Star，欢迎PR~

> 微信交流群
<img width="358" src="https://img14.360buyimg.com/imagetools/jfs/t1/99938/27/5896/64075/5df0772eE89888d9d/4ba34697506e331c.jpg">

**Comment by yoyo837** [comment]
你好，请问一下，你们团队和O2在工作上是什么关系，[AT-UI](https://github.com/AT-UI/at-ui) 刚开源就放弃了吗？

**Comment by sskk741** [comment]
> 
> 
> 你好，请问一下，你们团队和O2在工作上是什么关系，[AT-UI](https://github.com/AT-UI/at-ui) 刚开源就放弃了吗？

AT-UI是面向电脑端的，这个是面向移动端的，还是不一样的。

**Comment by Franslee** [comment]
> 你好，请问一下，你们团队和O2在工作上是什么关系，[AT-UI](https://github.com/AT-UI/at-ui) 刚开源就放弃了吗？

- 我们和O2是兄弟团队
- NutUI是移动端Vue组件库

**Comment by cnyyk** [comment]
见过很多大厂的开源项目，很多都是kpi产物，完成了kpi，使命就完成了。nutui会不会这样，拭目以待

**Comment by FatDong1** [comment]
请问你们团队自己搭建npm私服吗

**Comment by Franslee** [comment]
> 请问你们团队自己搭建npm私服吗

木有

**Comment by zxy89** [comment]
2.1.0的 swipper组件是不是有bug

**Comment by Franslee** [comment]
> 2.1.0的 swipper组件是不是有bug

什么bug？

**Comment by yyccQQu** [comment]
不是直接提到issue吗？
在这里解决问题？

**Comment by yyccQQu** [comment]
https://github.com/jdf2e/nutui/issues/88 
bug在此，看一下~@@@

> > 2.1.0的 swipper组件是不是有bug
> 
> 什么bug？

**Comment by Franslee** [comment]
> 不是直接提到issue吗？
> 在这里解决问题？

提issue即可

**Comment by yyccQQu** [comment]
![image](https://user-images.githubusercontent.com/32674176/63153104-b988df00-c037-11e9-8830-feb810eee86a.png)
![image](https://user-images.githubusercontent.com/32674176/63153115-c1e11a00-c037-11e9-9fb5-d7e5f99ee4e0.png)
适配问题

**Comment by ManiuLtd** [comment]
这个项目几个月没见动静了，又黄了吗？

**Comment by zhenyulei** [comment]
> 这个项目几个月没见动静了，又黄了吗？

欢迎关注 木有黄 有木有

**Comment by woderlili** [comment]
想问一下nut-uploader 该该该怎么添加请求头

**Comment by richard1015** [comment]
> 想问一下nut-uploader 该该该怎么添加请求头

非常感谢您的问题，双十一后我们会增加这个功能，请持续关注 :)

**Comment by richard1015** [comment]
> 想问一下nut-uploader 该该该怎么添加请求头

v2.1.7已发布
nut-uploader已支持自定义header请求头

**Comment by tj87418** [comment]
偶然我机会，发现了这个ui，看了demo需要的功能都有，目前有2个问题。
1：cell列表项能嵌套其他组件吗？
2：cell与其他组件怎样添加click事件，直接在上面添加@click没效果。

**Comment by yangkaixuan** [comment]
> 偶然我机会，发现了这个ui，看了demo需要的功能都有，目前有2个问题。
> 1：cell列表项能嵌套其他组件吗？
> 2：cell与其他组件怎样添加click事件，直接在上面添加@click没效果。

1.cell 暂时不支持嵌套其他组件的功能
2.可以使用@click.native方法增加点击事件
