### ISSUE TITLE
目前的icon 组件没有采用 svg-sprite 方式

### ISSUE THREAD

**Issue by brucekong** [jdf2e/nutui#160]
大佬您好，http://jdc.jd.com/archives/212600 这篇文章中有提到 nutui Icon 组件基于的是        
 svg-sprite 技术，但是目前看到 nutui 里采用的方式是直接引用svg ,没有采用 svg-symbol 方式，请问是出于什么考量？谢谢。

**Comment by Franslee** [comment]
nutui 1.0版有采用，那篇文章较老
