### ISSUE TITLE
[bug] nut-dialog 异步关闭不起作用

### ISSUE THREAD

**Issue by cherrol** [jdf2e/nutui#1602]
## 最小可复现仓库
> [请创建最小可复现代码，并上传到你的 GitHub 仓库](https://github.com/cherrol/nutui-issue/tree/dialog)

## 预期的行为和实际行为
- 能正常实现异步关闭

## 相关环境信息
- **操作系统**：windows 11
- **Node 版本**：v16.14.2
- **NutUI 版本**： "@nutui/nutui-taro": "^3.1.8"
- **Vue 版本**："vue": "^3.0.0"
- **引用方式**： NPM

**Comment by richard1015** [comment]
const onOkAsync = () => {
      sleep()
        .then(() => {
          closeContent.value = countDown(2);
          return sleep();
        })
        .then(() => {
          closeContent.value = countDown(1);
          return sleep();
        })
        .then(() => {
          closeContent.value = countDown(0);
        })
        .then(() => {
          **visible4.value = false;**
        });
    };

**Comment by richard1015** [comment]
![image](https://user-images.githubusercontent.com/13060263/197148170-ab3e1391-d27e-4509-93f2-886772399cd9.png)
