### ISSUE TITLE
[bug] taro 中 sticky  无法使用，报错：Sticky.js?b0c9:37                  Uncaught (in promise) TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_1___default(...).createSelectorQuery is not a function

### ISSUE THREAD

**Issue by iFTY-R** [jdf2e/nutui#1605]
## 问题描述
taro 中使用 @nutui/nutui-taro 组件库中的Sticky 组件 报错，无法使用，
`
       Uncaught (in promise) TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_1___default(...).createSelectorQuery is not a function`

### 实际上报错:
Sticky.js?b0c9:37 
       Uncaught (in promise) TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_1___default(...).createSelectorQuery is not a function

## 复现步骤，具体代码
    <nut-sticky top="120">
      123123
    </nut-sticky>

## 相关环境信息
- **操作系统**：window11
- **Node 版本**：v16.15.0
- **NutUI 版本**： ^3.1.8
- **Vue 版本**：3.2.38
- **引用方式**：  NPM

**Comment by szg2008** [comment]
目前没有复现哈，可以安装最新版本试试
