### ISSUE TITLE
[bug]  nut-tabs 组件 v-for 创建 nut-tabpane 时 浏览器控制台报错

### ISSUE THREAD

**Issue by wy1037** [jdf2e/nutui#1606]
版本：@nutui/nutui v3.2.1 

动态创建 nut-tabpane 时，

代码如下：
 <nut-tabs v-model="tabvalue">
            <nut-tabpane v-for="item in modulelist" :pane-key="item.moduleID" :title="item.name">
                {{item.name}}
            </nut-tabpane>
        </nut-tabs>

浏览器控制台报错：
 [NutUI] <Tabs> 当前未找到 TabPane 组件元素 , 请检查 .

**Comment by richard1015** [comment]
参考 https://github.com/jdf2e/nutui/blob/next/src/packages/__VUE/tabs/demo.vue#L32
