### ISSUE TITLE
[bug] List组件的scroll-bottom事件不被触发

### ISSUE THREAD

**Issue by ShawnZeng** [jdf2e/nutui#1607]
## 问题描述
拉到底@scroll-bottom事件也不触发。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

@scroll="handleScrollBottom($event)"

      handleScrollBottom: (e) => {
        console.log(e)
      }
## 复现步骤，具体代码
@scroll-bottom应该触发

## 相关环境信息
- **操作系统**：
- **Node 版本**：v14.18.3
- **NutUI 版本**： 3.2.1  （taro版本）
- **Vue 版本**：3.2.38
- **引用方式**：  NPM

**Comment by ShawnZeng** [comment]
好像是container-height超过某个特定高度，就不触发。高度完全在视野范围内。

**Comment by szg2008** [comment]
感谢反馈，我们跟进下

**Comment by szg2008** [comment]
已限制container-height最大为可视区
