### ISSUE TITLE
scroll组件 vertical-scroll 模式 不能设置动画的执行时间

### ISSUE THREAD

**Issue by andorcba** [jdf2e/nutui#161]
![image](https://user-images.githubusercontent.com/5809690/64075172-75f4cd00-cce7-11e9-8a54-f8a6e7047ede.png)

**Comment by zhenyulei** [comment]
你是用的CDN的方式引入的nutui吧？如果是的话，建议改成npm的方式加载nutui组件库。CDN方式引入的话该组件有点问题，我们接下来改动会将其修复。如果还不行的话，建议把代码再多提供一些，感谢！

**Comment by richard1015** [comment]
v2.1.8已修复
