### ISSUE TITLE
[bug] nut-form与nut-form-item分别在不同组件渲染时，表单验证会失效

### ISSUE THREAD

**Issue by xiblying** [jdf2e/nutui#1611]
## 问题描述

nut-form与nut-form-item分别在不同组件渲染时，表单验证会失效，debug发现findFormItem()返回空数组
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

https://github.com/xiblying/nutui-test

**Comment by yoyo837** [comment]
同遇到, 想要二次封装`nut-form-item` , 发现行不通

**Comment by yoyo837** [comment]
```html
<script>
export default {
  name: 'abc', // 加这个可以赋予name属性, 但是无法设置为 `nut-form-item` 会递归死循环
};
</script>
```

**Comment by yoyo837** [comment]
迫切需要这个

**Comment by yoyo837** [comment]
功能不够, 二次封装来凑, 但二次封装就无法使用, 就没路可走了.

**Comment by xiblying** [comment]
> 功能不够, 二次封装来凑, 但二次封装就无法使用, 就没路可走了.

我重写了验证方法，可以绕路实现

**Comment by yoyo837** [comment]
> > 功能不够, 二次封装来凑, 但二次封装就无法使用, 就没路可走了.
> 
> 我重写了验证方法，可以绕路实现

你指的是发私包?

**Comment by xiblying** [comment]
> > > 功能不够, 二次封装来凑, 但二次封装就无法使用, 就没路可走了.
> > 
> > 
> > 我重写了验证方法，可以绕路实现
> 
> 你指的是发私包?

没啊，通过ref \<nut-form/\>修改验证方法validate

**Comment by yoyo837** [comment]
噢, 这样也是一个办法

**Comment by yoyo837** [comment]
那你得全部重写, 因为其他方法也引用到了validate

**Comment by xiblying** [comment]
> 那你得全部重写, 因为其他方法也引用到了validate

form.getFormItems = getFormItems
form.validate = validate.bind(form)

我是这样弄得的，validate()是源码扒下来改的，getFormItems()去获取form下面所有form-item，不太多

**Comment by yoyo837** [comment]
checkRule 你不扒吗?

**Comment by yoyo837** [comment]
我也搞定了, 先临时用着, 看官方如何改动我再兼容.

**Comment by aehyok** [comment]
![image](https://user-images.githubusercontent.com/5900140/192709329-fcf34842-f2ac-43ba-8697-0bf7face9d55.png)
@xiblying 大佬，这个小问题有解吗

**Comment by xiblying** [comment]
> ![image](https://user-images.githubusercontent.com/5900140/192709329-fcf34842-f2ac-43ba-8697-0bf7face9d55.png) @xiblying 大佬，这个小问题

可以用

**Comment by aehyok** [comment]
@xiblying 要自己去适配样式了？

**Comment by xiblying** [comment]
> @xiblying 要自己去适配样式了？

对，就很坑

**Comment by aehyok** [comment]
@xiblying 谢谢大佬，这就很尴尬了，有点不想搞了

**Comment by xiblying** [comment]
> @xiblying 谢谢大佬，这就很尴尬了，有点不想搞了

我已经放弃了，换vant吧
