### ISSUE TITLE
picker可以自定义下方滚动区域的字体样式吗

### ISSUE THREAD

**Issue by MeiJunNa** [jdf2e/nutui#1612]
## 样式调整

目前滚动区域，字体大小和颜色无法调整

**Comment by szg2008** [comment]
这个可以通过自定义样式修改

**Comment by MeiJunNa** [comment]
作者，根本无法通过自定义样式修改呀，你这咋就直接关闭了？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
