### ISSUE TITLE
自定义主题色按照文档介绍配置完成后仍不生效

### ISSUE THREAD

**Issue by burgeryellow** [jdf2e/nutui#1614]
## 你想知道什么？

自定义主题色不生效，想请教下需要如何配置，taro版本3.5.4，nut ui 版本^3.1.8
创建了主题样式文件
![image](https://user-images.githubusercontent.com/52738928/187652284-f3a0fed0-b06e-417a-a5df-15cbde9a4843.png)

在config/index.js里进行了文档上说的配置
![image](https://user-images.githubusercontent.com/52738928/187652143-55101a0e-1f52-4af2-a963-e2d09809b1b0.png)

但是还是没有生效
<img width="241" alt="image" src="https://user-images.githubusercontent.com/52738928/187652020-6abb04ec-b33b-45eb-a458-0fc0b5dabb53.png">

## 描述你考虑过的替代方案

查了些方法，在app.js文件里引入
import '@nutui/nutui-taro/dist/styles/themes/default.scss';
或者import '@nutui/nutui-taro/dist/style.css'
还是没有生效

## 其它

无

**Comment by Jeijie** [comment]
我也遇到了，怎么解决的？
