### ISSUE TITLE
[bug]menu列表过长无法滚动

### ISSUE THREAD

**Issue by sunWhereCode** [jdf2e/nutui#1615]
## 问题描述
nut-menu 组件 nut-menu-item 内容过多，大于5条时候在微信开发者工具里可以滚动，在真机下无法滚动。

## 预期的行为和实际行为
在真机下可以滚动

## 复现步骤，具体代码
<img width="469" alt="image" src="https://user-images.githubusercontent.com/1262247/187691429-8a12955a-5e05-4fdb-9714-b414e9e2835d.png">

```
<nut-menu-item v-model="state.value1" :options="state.options1" />

const state = reactive({
  options1: [
    { text: '全部商品', value: 0 },
    { text: '新款商品', value: 1 },
    { text: '活动商品', value: 2 },
    { text: '全部商品', value: 3 },
    { text: '新款商品', value: 4 },
    { text: '活动商品', value: 5 },
    { text: '活动商品', value: 6 },
    { text: '活动商品', value: 7 },
    { text: '活动商品', value: 8 },
  ],
  value1: 0,
});
```

3.1.20是可以的，最新版本不行。

## 相关环境信息
- **操作系统**：macOS
- **Node 版本**：16.17.0
- **NutUI 版本**： 3.2.1
- **Vue 版本**：3.2.38
- **引用方式**：  NPM
- **taro**: 3.4.10

**Comment by Drjingfubo** [comment]
明日发版解决
