### ISSUE TITLE
[bug] nut-collapse  <template v-slot:mTitle>不显示插槽内容。

### ISSUE THREAD

**Issue by wy1037** [jdf2e/nutui#1616]
cdn js 引用的方式。
版本 @nutui/nutui v3.2.1 Tue Aug 09 2022 17:11:03 GMT+0800 (中国标准时间)

html：
`  <nut-collapse v-model:active="activeNames" icon="down-arrow">
            <nut-collapse-item :name="1">
                <template v-slot:mTitle>
                    {{title1}}
                </template>
               title1-child
            </nut-collapse-item>
            <nut-collapse-item :title="title2" :name="2">
                  title2-child
            </nut-collapse-item>
            <nut-collapse-item :title="title3" :name="3">
                 title3-child
            </nut-collapse-item>
        </nut-collapse>`
js:
{
    title1: '标题1',
            title2: '标题2',
            title3: '标题3',
}

效果：
![image](https://user-images.githubusercontent.com/34259090/187810654-6aac7918-d6bc-4a3b-8c42-3d55eab85b8d.png)

**Comment by Ymm0008** [comment]
@wy1037  您好，能提供完整的代码吗？目前您说的这个问题无法复现。

**Comment by wy1037** [comment]
代码在附件中，请下载。


效果如下：

**Comment by Ymm0008** [comment]
您好，没有附件内容啊。-_- ||



在 2022-09-02 15:14:18，"wy1037" ***@***.***> 写道：

代码在附件中，请下载。


效果如下：

**Comment by wy1037** [comment]
有附件的，我再发一次看看。
