### ISSUE TITLE
uploader 在h5下，点击报错：_tarojs_taro__WEBPACK_IMPORTED_MODULE_2___default(...).chooseImage is not a function

### ISSUE THREAD

**Issue by gslancer** [jdf2e/nutui#1617]
问题：
uploader 在h5下，点击报错：_tarojs_taro__WEBPACK_IMPORTED_MODULE_2___default(...).chooseImage is not a function

1. app.js中已经引入：

import { Icon, Uploader, Progress } from '@nutui/nutui-taro'

app.use(Icon)

app.use(Uploader)

app.use(Progress)

2. 页面使用：
`<nut-form :model-value="formData" ref="ruleForm">
   <nut-form-item label="上传:">
        <nut-uploader url="/upload/uploadfile" v-model:file-list="formData.othersList" ></nut-uploader>
      </nut-form-item>
</nut-form>`

3. 具体报错如下：
![err](https://user-images.githubusercontent.com/6703111/187818771-868a40fe-b59e-4192-8908-6807e28b7162.jpg)

4. 依赖版本：
"@nutui/nutui-taro": "^3.2.1",
"@tarojs/taro": "3.5.4",
"@tarojs/taro-h5": "3.5.4"

**Comment by dodaydream** [comment]
我也遇到相同的问题，依赖版本及错误信息同上面的

**Comment by richard1015** [comment]
辛苦尝试最新版本 ，如果还有问题辛苦提供最小复现仓库
