### ISSUE TITLE
[bug] Toast返回示例instance无法关闭

### ISSUE THREAD

**Issue by wangfpp** [jdf2e/nutui#1619]
## 问题描述
Toast实例无法关闭Toast

## 复现步骤，具体代码
```js
const getWarningDetail = async params => {
    let toast = Toast.loading('加载中', {
      duration: 0
    });
    try {
      let res = await getWarningDetailAPI(params);
      toast && toast.hide(); // toast 无hide方法
    } catch (e) {
      toast && toast.hide();
    }
  };

```

## 相关环境信息
- **操作系统**：Ubuntu 20.04.4 LTS on Windows 10 x86_64
- **Node 版本**：v16.2.0
- **NutUI 版本**：3.1.21
- **Vue 版本**：3.2.37
- **引用方式**：  NPM

**Comment by Drjingfubo** [comment]
NutUI的包是引用的哪个， @nutui/nutui还是@nutui/nutui-taro

**Comment by wangfpp** [comment]
@Drjingfubo nutui

**Comment by Drjingfubo** [comment]
提供一个git复现仓库，我本地按照你上边的写法复现不到
