### ISSUE TITLE
CDN方式下, nut-searchbar组件的placeText无效

### ISSUE THREAD

**Issue by isanonymous** [jdf2e/nutui#162]
CDN方式下, nut-searchbar组件的placeText属性无效,  永远是"请输入内容...", 修改不了
例:
`<nut-searchbar   placeText="测试"></nut-searchbar>`

![image](https://user-images.githubusercontent.com/48464704/64097782-b6138880-cd97-11e9-8bd3-1185cff33f38.png)

**Comment by zhenyulei** [comment]
你好可以提供你的代码和应用环境吗？我这边试了是可以的，代码如下：
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>实例</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.5/dist/nutui.min.css">
    
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.5/dist/nutui.min.js"></script>
    <style type="text/css">

    </style>
</head>

<body>
    <div id="app" v-cloak>
        <nut-searchbar placeText="测试"></nut-searchbar>
    </div>
    <script type="text/javascript">
        new Vue({
            el: '#app',
            data() {
                return {

                };
            },

            methods: {

            }
        });
    </script>
</body>

</html>`

**Comment by richard1015** [comment]
> CDN方式下, nut-searchbar组件的placeText属性无效, 永远是"请输入内容...", 修改不了
> 例:
> `<nut-searchbar placeText="测试"></nut-searchbar>`
> 
> ![image](https://user-images.githubusercontent.com/48464704/64097782-b6138880-cd97-11e9-8bd3-1185cff33f38.png)

#### 当采用   页面直接引用 CDN 资源时，请遵循 [https://cn.vuejs.org/v2/guide/components-props.html](https://cn.vuejs.org/v2/guide/components-props.html)

HTML 中的特性名是大小写不敏感的，所以浏览器会把所有大写字符解释为小写字符。这意味着当你使用 DOM 中的模板时，camelCase (驼峰命名法) 的 prop 名需要使用其等价的 kebab-case (短横线分隔命名) 命名：

###### 按照以下使用方式即可 ：）

``` html
  <nut-searchbar place-text="测试"></nut-searchbar>
```
