### ISSUE TITLE
[suggest]  DatePicker 优化建议

### ISSUE THREAD

**Issue by Zdaidia** [jdf2e/nutui#1620]
情况：使用DatePicker，选择好日期后，点击确认。经常会出现选中的日期还是上一次的日期的问题

建议：希望 DatePicker 也增加一个类似Picker的swipe-duration的props

**Comment by yangxiaolu1993** [comment]
首先感谢你对 NutUI 的支持，提出的建议与问题已添加，在下个版本发布

**Comment by szg2008** [comment]
可安装新版本试试

**Comment by Zdaidia** [comment]
感谢
