### ISSUE TITLE
[bug] 弹窗会有警告，关闭会报错问题

### ISSUE THREAD

**Issue by xiblying** [jdf2e/nutui#1625]
## 问题描述

弹窗会有警告，关闭会报错问题

## 最小可复现仓库

https://github.com/xiblying/nutui-test

**Comment by richard1015** [comment]
main文件中已经 use NutUI了，无限多次引用，像下图修改即可


![image](https://user-images.githubusercontent.com/13060263/197153044-4a773735-698e-495b-858c-a62065920375.png)

![image](https://user-images.githubusercontent.com/13060263/197153108-8536c557-856d-424d-aad2-42f09c510f3c.png)
