### ISSUE TITLE
分页的disabled样式颜色格式有错误，在很多浏览器无法识别

### ISSUE THREAD

**Issue by eruan** [jdf2e/nutui#1627]
.nut-pagination .disabled {
    color: #7474744f;
    background-color: #f7f8fa;
    cursor: not-allowed;
}
css的color格式怎么有8位16进制，不应该是6位16进制吗

**Comment by Drjingfubo** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/color_value

![image](https://user-images.githubusercontent.com/50685476/188396496-26fe5af6-6fe0-4f13-9c4c-3e78159576eb.png)
![image](https://user-images.githubusercontent.com/50685476/188396527-ca9ef799-1ba7-4977-8df9-6149a9c0658a.png)
