### ISSUE TITLE
Backtop 在小程序中不展示

### ISSUE THREAD

**Issue by yangjinjun3** [jdf2e/nutui#1629]
1、版本号
"@nutui/nutui-taro": "3.2.1"

2、使用方式
```html
<nut-backtop ></nut-backtop>
```

3、效果，控制台不报错，截图如下

<img width="320" alt="image" src="https://user-images.githubusercontent.com/44964193/188308273-7cf34c52-b323-4e5a-9d4c-14b64a177085.png">

**Comment by Drjingfubo** [comment]
backtop 默认需垂直滚动200px才会出现
