### ISSUE TITLE
[suggest]Barrage 弹幕支持插槽自定义

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui#1630]
## 你建议我们做什么？
Barrage 弹幕支持slot插槽自定义

目前不支持插槽

使用插槽可以自定义样式和元素
## 其它

无

**Comment by Ymm0008** [comment]
@yanbowe  您好，您的使用场景是什么样子的，可以提供吗？

目前这种数据格式是可以的 
```
[
    '测试1111',
    '测试2222',
    '<span style="color: red;">测试</span>'
]
```

**Comment by yanbowe** [comment]
> @yanbowe 您好，您的使用场景是什么样子的，可以提供吗？
> 
> 目前这种数据格式是可以的
> 
> ```
> [
>     '测试1111',
>     '测试2222',
>     '<span style="color: red;">测试</span>'
> ]
> ```

我这边的每个弹幕的dom结构可能比较复杂类似于这种结构，比如有自定义组件的内容的
![image](https://user-images.githubusercontent.com/43030980/191678952-33ade5cc-384a-47ad-9ffb-6c8f9177e46e.png)

**Comment by Ymm0008** [comment]
@yanbowe  ok，明白，我这边尽快适配下这种场景。

**Comment by yanbowe** [comment]
> @yanbowe ok，明白，我这边尽快适配下这种场景。
谢谢您
