### ISSUE TITLE
[bug]taro中input @update:model-value事件会触发两次

### ISSUE THREAD

**Issue by qq263402128** [jdf2e/nutui#1632]
## 问题描述
taro中input @update:model-value事件会触发两次

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
  <nut-input
        v-model="account"
        @update:model-value="inputHandler"
      />
JS
    const inputHandler = (val) => {
      console.log(">>>>>>", val);
    };

## 相关环境信息
- **操作系统**：win11
- **Node 版本**：16.14.0
- **NutUI 版本**： 3.1.8
- **Vue 版本**：3.0.0
- **引用方式**：  NPM

**Comment by Drjingfubo** [comment]
3.2.6已发布
