### ISSUE TITLE
IOS XS  input 键盘键 内容上推，必须下滑内容才能操作。

### ISSUE THREAD

**Issue by atongmu** [jdf2e/nutui#164]
`<nut-actionsheet :is-visible="isEditor" >
      <div slot="custom">
        <nut-cell title="选择货品" :showIcon="true" :isLink="true" @click.native="isItem=true">
          <div slot="desc" class="selected-option">{{item.name!='' ? item.name : '请选择'}}</div>
        </nut-cell>
        <nut-cell :isLink="true" >
          <div slot="title" class="selected-option">
            <nut-textinput v-model="item.num" :hasBorder="false" placeholder="请输入数量" :clearBtn="true" :disabled="false"/>
          </div>
        </nut-cell>
        <nut-cell :isLink="true" >
          <div slot="title" class="selected-option">
            <nut-textinput v-model="item.price" :hasBorder="false" placeholder="请输入价格" :clearBtn="true" :disabled="false"/>
          </div>
        </nut-cell>
        <nut-buttongroup shape="circle" style="margin-top:10px;padding:10px;">
            <nut-button color="#333" style="background:#eee" @click.native="isEditor=false">
              取消
            </nut-button>
            <nut-button style="background:#42b983" @click.native="addItem">
              确定
            </nut-button>
          </nut-buttongroup>
      </div>
    </nut-actionsheet>`
IOS XS  input 键盘键 内容上推，必须下滑内容才能操作。

**Comment by linrufeng** [comment]
我发现只有你这个机型这样，我也遇到过，我是当 input获取焦点时候强制滚动条滚到底部就解决这个问题了

**Comment by richard1015** [comment]
@atongmu   请采用根节点 fixed大法
https://segmentfault.com/a/1190000010510291

**Comment by richard1015** [comment]
专治各种ios问题
