### ISSUE TITLE
sku组件，异步替换数据，imagePath 字段没有响应式，替换图片不显示[bug]

### ISSUE THREAD

**Issue by muzixiaojun** [jdf2e/nutui#1641]
sku组件，异步替换数据，imagePath 字段没有响应式，替换图片不显示[bug]

**Comment by yangxiaolu1993** [comment]
可以提供一下复现场景吗，通过 setTimeout 模拟异步替换，并没有复现

**Comment by Drjingfubo** [comment]
暂时先关闭了哈，咱们这边同学没有复现到，您后续有空的话 可以给个最小复现仓库，我们在看下
