### ISSUE TITLE
[bug] Taro编译ImagePreview组件到h5端无法正确显示图片

### ISSUE THREAD

**Issue by Jonny-Zou** [jdf2e/nutui#1642]
### H5端
![image](https://user-images.githubusercontent.com/35751713/188812321-a4d0643f-701f-418e-8428-8fb309fbd99b.png)
### 微信小程序
![image](https://user-images.githubusercontent.com/35751713/188812377-57f32209-c6b2-4b67-89e2-b4c2f8e96550.png)
### 支付宝小程序
![image](https://user-images.githubusercontent.com/35751713/188812193-df4fbc95-1442-4e6b-b1f9-9f51bc707743.png)

## 最小可复现仓库
https://github.com/Jonny-Zou/nutui-taro-template.git

## 相关环境信息
- **操作系统**：macOS Big Sur 11.6
- **Node 版本**：v14.18.1
- **NutUI 版本**： ^3.1.8
- **Vue 版本**：^3.0.0
- **引用方式**：  pnpm

**Comment by yangxiaolu1993** [comment]
问题已经修改，可先试用 NutUI-Taro 3.2.3-beta.0 进行修改，此版本依赖 Taro 3.5.6
