### ISSUE TITLE
微信小程序 DatePicker  选择时间会拖动整个页面，并且很卡，官方示例也是这样。

### ISSUE THREAD

**Issue by ithreeleaf** [jdf2e/nutui#1651]
https://user-images.githubusercontent.com/30279432/189274335-0d742e0d-2c21-47dd-adb1-b6193c68b607.mp4

**Comment by ithreeleaf** [comment]
手机是iphone 11

**Comment by yangxiaolu1993** [comment]
DatePicker 卡顿问题已经修改，可先试用 NutUI-Taro 3.2.3-beta.0 进行修改，此版本依赖 Taro 3.5.6
