### ISSUE TITLE
[bug] 初始化程序直接编译钉钉小程序 不能执行

### ISSUE THREAD

**Issue by misterji** [jdf2e/nutui#1654]
## 问题描述

初始化程序直接编译钉钉小程序 不能执行
"build:alipay": "taro build --type alipay",

Failed to compile
/Users/jiyjbook/Downloads/myApp/dist/vendors.js: Unexpected token (2492:124)
Please set enableNodeModuleBabelTransform to true or add "/Users/jiyjbook/Downloads/myApp/dist/vendors.js" to node_modules_es6_whitelist in mini.project.json for node_modules babel transform

## 相关环境信息
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by Drjingfubo** [comment]
钉钉小程序暂时还没进行适配，后续适配以后会同步到您
