### ISSUE TITLE
 _tarojs_taro__WEBPACK_IMPORTED_MODULE_3___default().createSelectorQuery is not a function

### ISSUE THREAD

**Issue by jaroky** [jdf2e/nutui#1656]
taro  v3.5.5  + vue3 展现Elevator时出现

**Comment by szg2008** [comment]
能否提供下复现仓库，我这边测试的没有问题。环境是taro v3.5.5 + vue3.2

**Comment by zuilikanhua** [comment]
> 能否提供下复现仓库，我这边测试的没有问题。环境是taro v3.5.5 + vue3.2
用官方的cli 创建的项目 ，使用Elevator  h5端 就会出现，，小程序端没问题

**Comment by jaroky** [comment]
> 

我就是使用h5的时候出现的

**Comment by jaroky** [comment]
> 

`{
	"name": "taro-kdq-order",
	"version": "1.0.0",
	"private": true,
	"description": "taro-kdq-order",
	"templateInfo": {
		"name": "vue3-NutUI",
		"typescript": false,
		"css": "sass"
	},
	"scripts": {
		"build:weapp": "taro build --type weapp",
		"build:swan": "taro build --type swan",
		"build:alipay": "taro build --type alipay",
		"build:tt": "taro build --type tt",
		"build:h5": "taro build --type h5",
		"build:rn": "taro build --type rn",
		"build:qq": "taro build --type qq",
		"build:jd": "taro build --type jd",
		"build:quickapp": "taro build --type quickapp",
		"dev:weapp": "npm run build:weapp -- --watch",
		"dev:swan": "npm run build:swan -- --watch",
		"dev:alipay": "npm run build:alipay -- --watch",
		"dev:tt": "npm run build:tt -- --watch",
		"dev:h5": "npm run build:h5 -- --watch",
		"dev:rn": "npm run build:rn -- --watch",
		"dev:qq": "npm run build:qq -- --watch",
		"dev:jd": "npm run build:jd -- --watch",
		"dev:quickapp": "npm run build:quickapp -- --watch"
	},
	"browserslist": [
		"last 3 versions",
		"Android >= 4.1",
		"ios >= 8"
	],
	"author": "",
	"license": "MIT",
	"dependencies": {
		"@babel/runtime": "^7.7.7",
		"@nutui/nutui-taro": "^3.1.8",
		"@tarojs/components": "3.5.4",
		"@tarojs/helper": "3.5.4",
		"@tarojs/plugin-framework-vue3": "3.5.4",
		"@tarojs/plugin-html": "3.5.4",
		"@tarojs/plugin-platform-alipay": "3.5.4",
		"@tarojs/plugin-platform-jd": "3.5.4",
		"@tarojs/plugin-platform-qq": "3.5.4",
		"@tarojs/plugin-platform-swan": "3.5.4",
		"@tarojs/plugin-platform-tt": "3.5.4",
		"@tarojs/plugin-platform-weapp": "3.5.4",
		"@tarojs/router": "3.5.4",
		"@tarojs/runtime": "3.5.4",
		"@tarojs/shared": "3.5.4",
		"@tarojs/taro": "3.5.4",
		"@tarojs/taro-h5": "3.5.4",
		"vue": "^3.0.0"
	},
	"devDependencies": {
		"@babel/core": "^7.8.0",
		"@tarojs/cli": "3.5.4",
		"@tarojs/webpack5-runner": "3.5.4",
		"@types/webpack-env": "^1.13.6",
		"@vue/babel-plugin-jsx": "^1.0.6",
		"@vue/compiler-sfc": "^3.0.0",
		"babel-plugin-import": "^1.13.3",
		"babel-preset-taro": "3.5.4",
		"css-loader": "3.4.2",
		"eslint": "^8.12.0",
		"eslint-config-taro": "3.5.4",
		"eslint-plugin-vue": "^8.0.0",
		"style-loader": "1.3.0",
		"stylelint": "9.3.0",
		"vue-loader": "^16.0.0-beta.8",
		"webpack": "5.69.0"
	}
}
`
仓库依赖全是使用cli创建时，引入进来的。都没有自己新增。是在h5下出现的

**Comment by richard1015** [comment]
辛苦 尝试最近版本 测试一下，使用taro 3.5.6脚手架初始化
