### ISSUE TITLE
[bug] input-number 样式丢失

### ISSUE THREAD

**Issue by juzijun2020** [jdf2e/nutui#1657]
## 问题描述

单独调用inputnumber出现 input 没有样式，如下图：
![img](https://raw.githubusercontent.com/juzijun2020/test/main/nutui-taro-bug-2022-09-13_2.png)
如果和其他表单项混合使用，inputnumber 里面的input 高度会变高，如下图：
![img](https://raw.githubusercontent.com/juzijun2020/test/main/nutui-taro-bug-2022-09-13_1.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
直接安装最新版本的taro和nutui，然后复制官方示例模板就可复现。

## 相关环境信息
- **操作系统**：MACOS
- **Node 版本**：8.5.0
- **Taro 版本**：3.5.5
- **NutUI 版本**： 3.2.2
- **Vue 版本**：3.2.39
- **引用方式**：  NPM

**Comment by Drjingfubo** [comment]
![image](https://user-images.githubusercontent.com/50685476/194790747-c148160f-fd65-46df-9948-597212a48e65.png)
用3.2.3试下吧

**Comment by juzijun2020** [comment]
> ![image](https://user-images.githubusercontent.com/50685476/194790747-c148160f-fd65-46df-9948-597212a48e65.png) 用3.2.3试下吧

没用，升级到3.2.4 都是一样的

**Comment by Drjingfubo** [comment]
> > ![图片](https://user-images.githubusercontent.com/50685476/194790747-c148160f-fd65-46df-9948-597212a48e65.png) 用3.2.3试下吧
> 
> 没用，升级到3.2.4 都是一样的

提供个最小复现仓库看下

**Comment by juzijun2020** [comment]
> > > ![图片](https://user-images.githubusercontent.com/50685476/194790747-c148160f-fd65-46df-9948-597212a48e65.png) 用3.2.3试下吧
> > 
> > 
> > 没用，升级到3.2.4 都是一样的
> 
> 提供个最小复现仓库看下

https://github.com/juzijun2020/taroinputnumber

**Comment by Drjingfubo** [comment]
> > > > ![图片](https://user-images.githubusercontent.com/50685476/194790747-c148160f-fd65-46df-9948-597212a48e65.png) 用3.2.3试下吧
> > > 
> > > 
> > > 没用，升级到3.2.4 都是一样的
> > 
> > 
> > 提供个最小复现仓库看下
> 
> https://github.com/juzijun2020/taroinputnumber

是taro的h5环境对吧

**Comment by juzijun2020** [comment]
> 



> > > > > ![图片](https://user-images.githubusercontent.com/50685476/194790747-c148160f-fd65-46df-9948-597212a48e65.png) 用3.2.3试下吧
> > > > 
> > > > 
> > > > 没用，升级到3.2.4 都是一样的
> > > 
> > > 
> > > 提供个最小复现仓库看下
> > 
> > 
> > https://github.com/juzijun2020/taroinputnumber
> 
> 是taro的h5环境对吧

是的，仓库里面 直接 安装 跑起来就可以看到效果

**Comment by Drjingfubo** [comment]
> > 
> 
> > > > > > ![图片](https://user-images.githubusercontent.com/50685476/194790747-c148160f-fd65-46df-9948-597212a48e65.png) 用3.2.3试下吧
> > > > > 
> > > > > 
> > > > > 没用，升级到3.2.4 都是一样的
> > > > 
> > > > 
> > > > 提供个最小复现仓库看下
> > > 
> > > 
> > > https://github.com/juzijun2020/taroinputnumber
> > 
> > 
> > 是taro的h5环境对吧
> 
> 是的，仓库里面 直接 安装 跑起来就可以看到效果

好的 辛苦下次标注一下环境

**Comment by juzijun2020** [comment]
> > > 
> > 
> > 
> > > > > > > ![图片](https://user-images.githubusercontent.com/50685476/194790747-c148160f-fd65-46df-9948-597212a48e65.png) 用3.2.3试下吧
> > > > > > 
> > > > > > 
> > > > > > 没用，升级到3.2.4 都是一样的
> > > > > 
> > > > > 
> > > > > 提供个最小复现仓库看下
> > > > 
> > > > 
> > > > https://github.com/juzijun2020/taroinputnumber
> > > 
> > > 
> > > 是taro的h5环境对吧
> > 
> > 
> > 是的，仓库里面 直接 安装 跑起来就可以看到效果
> 
> 好的 辛苦下次标注一下环境

我有标注的，麻烦你看回帖子内容

**Comment by Drjingfubo** [comment]
> > > > 
> > > 
> > > 
> > > > > > > > ![图片](https://user-images.githubusercontent.com/50685476/194790747-c148160f-fd65-46df-9948-597212a48e65.png) 用3.2.3试下吧
> > > > > > > 
> > > > > > > 
> > > > > > > 没用，升级到3.2.4 都是一样的
> > > > > > 
> > > > > > 
> > > > > > 提供个最小复现仓库看下
> > > > > 
> > > > > 
> > > > > https://github.com/juzijun2020/taroinputnumber
> > > > 
> > > > 
> > > > 是taro的h5环境对吧
> > > 
> > > 
> > > 是的，仓库里面 直接 安装 跑起来就可以看到效果
> > 
> > 
> > 好的 辛苦下次标注一下环境
> 
> 我有标注的，麻烦你看回帖子内容

我的意思是标注清楚是taro的小程序端还是h5端哈

**Comment by juzijun2020** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > > > > > ![图片](https://user-images.githubusercontent.com/50685476/194790747-c148160f-fd65-46df-9948-597212a48e65.png) 用3.2.3试下吧
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 没用，升级到3.2.4 都是一样的
> > > > > > > 
> > > > > > > 
> > > > > > > 提供个最小复现仓库看下
> > > > > > 
> > > > > > 
> > > > > > https://github.com/juzijun2020/taroinputnumber
> > > > > 
> > > > > 
> > > > > 是taro的h5环境对吧
> > > > 
> > > > 
> > > > 是的，仓库里面 直接 安装 跑起来就可以看到效果
> > > 
> > > 
> > > 好的 辛苦下次标注一下环境
> > 
> > 
> > 我有标注的，麻烦你看回帖子内容
> 
> 我的意思是标注清楚是taro的小程序端还是h5端哈

请问这个问题什么时候能解决？难道只有我一个人出现了么？

**Comment by cyx447653591** [comment]
3.2.7还没修复吧？还是这样啊

**Comment by Drjingfubo** [comment]
下周发版处理这个
