### ISSUE TITLE
[bug]Taro3+NutUI3使用国际化就报错

### ISSUE THREAD

**Issue by GitHubWuYi** [jdf2e/nutui#1659]
`import { Locale } from '@nutui/nutui-taro';`
`import enUS from '@nutui/nutui-taro/dist/packages/locale/lang/en-US';`
`Locale.use('en-US', enUS);`

> `npm run dev:weapp`

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/19516351/190057962-1b713ed2-e0b9-4de4-9f80-e030267ad902.png">

**Comment by richard1015** [comment]
参考这个示例代码  https://github.com/jdf2e/nutui-demo/tree/master/taro3

**Comment by richard1015** [comment]
看一下 按需加载配置 文件大小写
```
 return `@nutui/nutui/dist/packages/${name.toLowerCase()}/index.scss`
```

https://nutui.jd.com/#/zh-CN/guide/start
