### ISSUE TITLE
[bug] button 禁用状态的按钮 @click.stop不生效 

### ISSUE THREAD

**Issue by jingyuhao1995** [jdf2e/nutui#1663]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by jingyuhao1995** [comment]
`<template>
  <div @click="father">
    父容器
      <nut-button plain disabled type="info" @click.stop="childClick1">禁用状态</nut-button>
      <nut-button plain type="primary" @click.stop="childClick2">非禁用状态</nut-button>
  </div>
  
</template>

<script>
import { reactive, toRefs } from 'vue';
export default {
  setup() {
    const father = ()=>{
      alert('父')
    }
    const childClick1 = ()=>{
      alert('childClick1')
    }
    const childClick2 = ()=>{
      alert('childClick2')
    }
    return {
      father,
      childClick1,
      childClick2
    };
  }
}
</script>`

**Comment by Drjingfubo** [comment]
禁用状态下的按钮点击事件不可用呐，提供简单代码看一下

**Comment by jingyuhao1995** [comment]
![image](https://user-images.githubusercontent.com/35212876/192253079-d5d487fb-5ca3-46da-8e97-caf3ee6bf0f9.png)

**Comment by jingyuhao1995** [comment]
```
<template>
  <div @click="father">
    父容器
      <nut-button plain disabled type="info" @click.stop="childClick1">禁用状态</nut-button>
      <nut-button plain type="primary" @click.stop="childClick2">非禁用状态</nut-button>
  </div>

</template>

<script>
import { reactive, toRefs } from 'vue';
export default {
  setup() {
    const father = ()=>{
      alert('父')
    }
    const childClick1 = ()=>{
      alert('childClick1')
    }
    const childClick2 = ()=>{
      alert('childClick2')
    }
    return {
      father,
      childClick1,
      childClick2
    };
  }
}
</script>
```

**Comment by jingyuhao1995** [comment]
> 禁用状态下的按钮点击事件不可用呐，提供简单代码看一下

```
<template>
  <div @click="father">
    父容器
      <nut-button plain disabled type="info" @click.stop="childClick1">禁用状态</nut-button>
      <nut-button plain type="primary" @click.stop="childClick2">非禁用状态</nut-button>
  </div>

</template>

<script>
import { reactive, toRefs } from 'vue';
export default {
  setup() {
    const father = ()=>{
      alert('父')
    }
    const childClick1 = ()=>{
      alert('childClick1')
    }
    const childClick2 = ()=>{
      alert('childClick2')
    }
    return {
      father,
      childClick1,
      childClick2
    };
  }
}
</script>
```

**Comment by Drjingfubo** [comment]
当button设置为disabled的时候，组件内部已经不提供点击事件了，所以不生效
