### ISSUE TITLE
[suggest]

### ISSUE THREAD

**Issue by rain-late** [jdf2e/nutui#1664]
loadIcon: {
      type: String,
      default: 'https://img10.360buyimg.com/imagetools/jfs/t1/169863/6/4565/6306/60125948E7e92774e/40b3a0cf42852bcb.png'
    },
上拉加载的图标类型是string类型，而官方文档是布尔类型，详情见滚动加载上拉icon

**Comment by szg2008** [comment]
感谢反馈，已更新
