### ISSUE TITLE
[suggest]

### ISSUE THREAD

**Issue by JackYumg** [jdf2e/nutui#1668]
## 你建议我们做什么？

现在在使用Empty的时候发现自带的默认图片不符合我们的设计风格，在里面存在大量使用的地方，并且不想对这个组件进行二次封装。能不能让Empty的图片全局配置。

**Comment by szg2008** [comment]
https://nutui.jd.com/#/zh-CN/component/Empty 可以支持自定义图片的

**Comment by JackYumg** [comment]
是通过全局配置各个状态的图片
