### ISSUE TITLE
Swipe 滑动手势 的一些问题

### ISSUE THREAD

**Issue by asasdsad** [jdf2e/nutui#1669]
使用Swipe 滑动手势组件时
用v-for循环出来的数据  左滑或者右滑动会导致所有数据都会显示出左边的内容
![image](https://user-images.githubusercontent.com/45427090/190547149-272a5ee3-758b-4a72-a4c8-95541c56088f.png)

**Comment by asasdsad** [comment]
造成这种原因是因为底部出现滚动条，在codesandbox运行也会出现滚动条

**Comment by richard1015** [comment]
父级横向     overflow-x: hidden; 试试看

**Comment by acmug** [comment]
@asasdsad 请问最后你怎么解决的呀，我这边使用overflow-x:hidden虽然不会全部出现，但是在左滑的同时会上下滑动

**Comment by Yanoona** [comment]
请问解决了吗？
