### ISSUE TITLE
全局引入scss的报错

### ISSUE THREAD

**Issue by qnsdt** [jdf2e/nutui#167]
在main.js里面把css换成scss
1. 
// import '@nutui/nutui/dist/nutui.css'
import '@nutui/nutui/dist/nutui.scss'
2.在webpack.base.config.js里面已经加了
      {
        loader: 'sass-loader',
        options: {
            data: `@import "@nutui/nutui/dist/styles/index.scss"; `
        }
      }     
3.npm run dev仍然报错
 ERROR  Failed to compile with 4 errors                                                                                                10:02:36 AM

Module build failed: ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'data'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (D:\vuework\sample\template\router_ui_demo\node_modules\_schema-utils@2.4.0@schema-utils\dist\validate.js:50:11)
    at Object.loader (D:\vuework\sample\template\router_ui_demo\node_modules\_sass-loader@8.0.0@sass-loader\dist\index.js:36:28)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 error  in (webpack)/hot/dev-server.js

Module build failed: ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'data'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (D:\vuework\sample\template\router_ui_demo\node_modules\_schema-utils@2.4.0@schema-utils\dist\validate.js:50:11)
    at Object.loader (D:\vuework\sample\template\router_ui_demo\node_modules\_sass-loader@8.0.0@sass-loader\dist\index.js:36:28)

 @ multi ./node_modules/_webpack-dev-server@2.11.5@webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 error  in ./node_modules/_webpack-dev-server@2.11.5@webpack-dev-server/client?http://localhost:8080

Module build failed: ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'data'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (D:\vuework\sample\template\router_ui_demo\node_modules\_schema-utils@2.4.0@schema-utils\dist\validate.js:50:11)
    at Object.loader (D:\vuework\sample\template\router_ui_demo\node_modules\_sass-loader@8.0.0@sass-loader\dist\index.js:36:28)

 @ multi ./node_modules/_webpack-dev-server@2.11.5@webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by linrufeng** [comment]
你换一种全局引用方式
` "plugins": [
            "transform-vue-jsx",
            ["@nutui/babel-plugin-separate-import",{"style":"scss"}],
            "@babel/plugin-syntax-dynamic-import"
            
        ]`
在babelrc里面这样配置，

**Comment by linrufeng** [comment]
你换一种全局引用方式，在babelrc 里面加

` "plugins": [
            ["@nutui/babel-plugin-separate-import",{"style":"scss"}]  
        ]`

**Comment by qnsdt** [comment]
好的，麻烦你了，我试一下，目前，我只能用vue_cli3重新生成项目，有你这个方法就好了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"linrufeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月9日(星期三) 下午5:34
收件人:&nbsp;"jdf2e/nutui"<nutui@noreply.github.com&gt;;
抄送:&nbsp;"qnsdt"<280067865@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jdf2e/nutui] 全局引入scss的报错 (#167)




你换一种全局引用方式，在babelrc 里面加
 
 "plugins": [ ["@nutui/babel-plugin-separate-import",{"style":"scss"}]   ]
