### ISSUE TITLE
[suggest] 这是一个kpi项目吗？

### ISSUE THREAD

**Issue by muzixiaojun** [jdf2e/nutui#1670]
说实话你们做的这个东西真的不想吐槽，文档不够全，所有组件大部分只有表面上看着能用，深入下去跟废了一样！ 最最最想吐槽的就是，我拿来开发小程序，你每个组件都很卡顿，我换了taro-ui-vue3的组件顺畅的想哭。你们这个东西除了垃圾就是垃圾，怪不得出来也一段时间了，网上文档基本没有，因为垃圾东西没人用！！！！！！也不知道为啥taro3初始化项目要绑定你们这个ui，因为自己内部的？

**Comment by kongsiyu** [comment]
确实离谱

**Comment by kongsiyu** [comment]
哪哪都是Bug

**Comment by WangXang** [comment]
bug确实离谱，都不做单元测试么？

**Comment by 1146877017** [comment]
点开主页，0贡献度，满意离开

**Comment by couth** [comment]
感谢提醒，我也是nutui一路踩坑，折腾得要死。后面转taro-ui-vue3试试看

**Comment by muzixiaojun** [comment]
> 感谢提醒，我也是nutui一路踩坑，折腾得要死。后面转taro-ui-vue3试试看

赶紧换 基本不需要大改动就能完美转taro-ui-vue3,而且你换了之后你会发现流畅的想哭，可以2个ui一起用，有些不影响的 比如cell，就不用改了，但是像轮播图 虚拟列表啥的 建议你改，反正各种稍微复杂一点点的组件 建议能改就改，很影响体验

**Comment by muzixiaojun** [comment]
> 点开主页，0贡献度，满意离开

我有没有贡献和他这个kpi项目垃圾有直接关系吗？我看这个项目开源也好几年了把，至今没啥人用难道就不存在问题吗？虽然我没贡献，但是我用过，我不能说说用的感受？？？你看看用过的人过来基本都在吐槽，你是用过的？还是贡献者？我也无意冒犯，我就想说这个开源库除了看起来好看，一无是处

**Comment by forestRhapsody** [comment]
我也要换组件库了 被折腾死了

**Comment by Tenodec** [comment]
除了这个，隔壁taro-ui基本不回复。感觉都是kpi项目。阿里的remaxjs说域名到期，搞笑会犯这种低级错误吗。大家都不倦了，就不上心了

**Comment by kongsiyu** [comment]
> 

估计人被开的多搞不过来

**Comment by kongsiyu** [comment]
> 除了这个，隔壁taro-ui基本不回复。感觉都是kpi项目。阿里的remaxjs说域名到期，搞笑会犯这种低级错误吗。大家都不倦了，就不上心了

估计人被开的多搞不过来

**Comment by laosandegudai** [comment]
最新的4.0也是卡顿，我还以为我写的有问题。tabbar切换卡顿。

**Comment by HeyShinner** [comment]
我以为就我觉得难用，到处都是 bug
