### ISSUE TITLE
微信小程序，nut-uploader before-delete返回promise对象无效

### ISSUE THREAD

**Issue by WangXang** [jdf2e/nutui#1672]
## 问题描述
微信小程序，组件nut-uploader   before-delete返回promise对象无效，图片还是被删除了

## 预期的行为和实际行为
预期的行为: 组件nut-uploader中的before-delete方法，返回 resolve(false) 或 reject 时，图片不应该被移除
实际行为：组件nut-uploader中的before-delete方法，返回 resolve(false) 或 reject 时，图片被移除

## 复现步骤，具体代码
package.json
![image](https://user-images.githubusercontent.com/23691331/190623274-402337d2-2885-456f-a5e4-834723fd689c.png)

代码：
![image](https://user-images.githubusercontent.com/23691331/190622469-54cbb2cd-36ed-4c11-9928-994dbcc5b7c4.png)

![image](https://user-images.githubusercontent.com/23691331/190623191-f721ce3f-df1e-4ff8-a291-494bad3af5c4.png)

## 相关环境信息
- **操作系统**：macos 12.5
- **Node 版本**：16
- **NutUI 版本**： "@nutui/nutui-taro": "^3.2.2",
- **Vue 版本**：vue 3.2.38
- **引用方式**：  npm

**Comment by Drjingfubo** [comment]
v3.2.3已发布
