### ISSUE TITLE
[bug]安卓微信环境下键盘收起后页面下方空白

### ISSUE THREAD

**Issue by zenghjin** [jdf2e/nutui#1673]
## 问题描述
在安卓微信环境下，若键盘已弹出，点击文件上传，选择文件，回到页面之后，页面下方键盘位置会出现空白

## 最小可复现仓库
官方demo即可复现
https://nutui.jd.com/#/zh-CN/component/form

## 预期的行为和实际行为

![image](https://user-images.githubusercontent.com/18493001/190635366-c4191c99-779a-4cae-832c-37568f5a3949.png)
![image](https://user-images.githubusercontent.com/18493001/190635418-31a4ec8d-4597-4028-831b-f0b0aa3839bc.png)

## 复现步骤，具体代码
1. 点击输入框，唤起系统键盘
2. 不收起键盘，直接点击文件上传，前往系统资源库选择文件
3. 选择文件后返回页面，键盘消失，键盘位置是空白

## 相关环境信息
- **操作系统**：安卓微信

**Comment by richard1015** [comment]
官网 bug

**Comment by richard1015** [comment]
已修复
