### ISSUE TITLE
ImagePreview props  images 类型错误[bug]

### ISSUE THREAD

**Issue by xiehai001** [jdf2e/nutui#1674]
## 问题描述
![image](https://user-images.githubusercontent.com/24218743/190837987-77a36c62-38d4-40b4-95ab-63dfbea899e1.png)
![Uploading image.png…]()
源码中对images 的类型判定有误
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by yangxiaolu1993** [comment]
错误指的是什么？
