### ISSUE TITLE
[bug] _tarojs_taro__WEBPACK_IMPORTED_MODULE_2___default(...).createSelectorQuery is not a function

### ISSUE THREAD

**Issue by weiximei** [jdf2e/nutui#1675]
## 问题描述

Taro3 H5使用 NoticeBar 组件报错

Uncaught TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_2___default(...).createSelectorQuery is not a function
    at eval (NoticeBar.js?1fac:191:1)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：Win10
- **Node 版本**：v14.17.3
- **NutUI 版本**： "@nutui/nutui-taro": "^3.2.2"
- **Vue 版本**：3.0.0
- **引用方式**：  CDN / NPM ？npm

**Comment by weiximei** [comment]
使用的是Taro 官方的 vue3-NutUI 模板

**Comment by richard1015** [comment]
使用taro 3.5.6 看一下，
具体使用方式可以参考一下  https://github.com/jdf2e/nutui-demo/tree/master/taro3
