### ISSUE TITLE
[bug]Swiper控件 taro h5 在pc 上滑动不支持

### ISSUE THREAD

**Issue by myxfeng** [jdf2e/nutui#1677]
## 问题描述

Swiper控件 taro h5 在pc 上滑动不支持
1、PC端事件
onclick 鼠标点击触发
onmousedown 鼠标按下触发
onmousemove 鼠标移动触发
onmouseup 鼠标抬起触发

 

2、移动端触屏事件
ontouchstart 手指按下触发
ontouchmove 手指移动触发
onTouchend 手指抬起触发

观看源码 貌似没支持 pC  事件
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by szg2008** [comment]
暂时不支持PC端
