### ISSUE TITLE
几个月没见这个项目有动静了，KPI产物？

### ISSUE THREAD

**Issue by ManiuLtd** [jdf2e/nutui#168]
项目前端UI框架选型，想找个大厂基于VUE的前端UI框架，在看了vant后发现了这个，但是发现这个项目几个月都没动静了，不知道还有没有后续？

**Comment by 925800521** [comment]
几个月没更新了，要凉！

**Comment by linrufeng** [comment]
没有凉，只是我们结构化调整了下，在调研

**Comment by zhenyulei** [comment]
你好

> 项目前端UI框架选型，想找个大厂基于VUE的前端UI框架，在看了vant后发现了这个，但是发现这个项目几个月都没动静了，不知道还有没有后续？

你好，没有凉。停下来是因为在调整力量，为了后续更好的发展。如果有问题欢迎留言，我们将继续维护。
