### ISSUE TITLE
[suggest] font-class-name 能否在 config-provider 组件中设置全局默认值

### ISSUE THREAD

**Issue by Lionad-Morotar** [jdf2e/nutui#1681]
每一个带 iconfont 的组件都要手写 font-class-name 和 class-prefix，特别麻烦，能否在 config-provider 中为全局的 font-class-name 设置一个默认值（并覆盖 "nutui-iconfont"）。

**Comment by thx125** [comment]
以下两个版本已实现功能，待CR后合并发版
- [x] v3.x
- [x] v4

**Comment by richard1015** [comment]
v3.3.3 已发布
