### ISSUE TITLE
是否能够出一个底部按钮组件

### ISSUE THREAD

**Issue by Jazzzy126** [jdf2e/nutui#1684]

**Comment by szg2008** [comment]
没明白什么意思？Button不能满足吗？或者给个现有的参考一下？

**Comment by Lron-boy** [comment]
@szg2008

**Comment by Jazzzy126** [comment]
@szg2008 https://tard-ui.selling.cn/comps/footer-button 这个你有现成的，实现方法应该跟导航栏差不多

**Comment by szg2008** [comment]
这个建议开发者直接使用样式处理～
