### ISSUE TITLE
停止每个页面注入variables.scss来减少体积

### ISSUE THREAD

**Issue by jasper-ops** [jdf2e/nutui#1689]
## 你建议我们做什么？

目前绝大部分的做法是在配置文件配置注入variables.scss
@import "@nutui/nutui-taro/dist/styles/variables-jdt.scss";
在这个文件内也导入了动画的代码，导致每个页面都存在相同的动画代码，
体积成倍增长，当然也不是要停止注入，而是不要注入动画的代码。

如果让开发者自己在app.scss内import动画的scss

它将使编译出来的项目只有app.wxss内存在一份公用的动画代码，而不会每个页面都存在

## 其它

需要注意的是如果使用css module可能会导致动画存在问题

**Comment by richard1015** [comment]
可以先采用 测试包 v3.2.3-beta.1  https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.3-beta.1

正式包  v3.2.3 本周四 9.29~30 发布
