### ISSUE TITLE
请问滚动相关的组件无法触发事件是什么情况

### ISSUE THREAD

**Issue by Zwr0126** [jdf2e/nutui#169]
InfiniteLoading 无限加载、Scroller 滚动、BackTop 回到顶部三个组件都无法触发滚动条事件是什么原因啊

**Comment by Zwr0126** [comment]
已解决，比如InfiniteLoading 无限加载组件，其父级不能出现height: 100%和overflow:hidden的样式属性，否则不会触发滚动事件

**Comment by Guanxiaodan** [comment]
overflow:scroll也不能出现

**Comment by richard1015** [comment]
> overflow:scroll也不能出现

如果还是有问题，可以提供一个最小可复现仓库
