### ISSUE TITLE
怎么让组件名支持 PascalCase 命名方式使用

### ISSUE THREAD

**Issue by wuyuweixin** [jdf2e/nutui#1693]
## 你想知道什么？

你好，我想知道怎么让组件名支持 PascalCase 命名方式使用

## 描述你考虑过的替代方案

例如: `<NutButton>按钮</NutButton>`
目前使用 PascalCase 命名方式会解析不到组件

## 其它

无

**Comment by richard1015** [comment]
可以描述一下您的具体场景？

当前版本暂时不支持 ，你可以用tsx那种写法  
``` js
 import { Button} from '@nutui/nutui';
  <Button>按钮</Button>
```
