### ISSUE TITLE
[bug] ImagePreview

### ISSUE THREAD

**Issue by myxfeng** [jdf2e/nutui#1696]
## 问题描述

Taro 版ImagePreview 组件 在h5 端预览时 无法进行手势缩放 ，并且希望加上 是否循环的属性控制
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
原因猜测 taro 版 转h5 是 内部swiper 增加  catch-move 属性导致 事件 无法向下穿透

## 相关环境信息
- **操作系统**：macos
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- taro  3.2.3-beta.0
- **Vue 版本**：vue3
- **引用方式**：  CDN / NPM ？
- npm

**Comment by yangxiaolu1993** [comment]
感谢对 NutUI 的支持！
1、是否循序属性已添加，在 3.2.5 版本发布
2、NutUI-Taro 中的 图片 暂不支持 缩放功能。缩放功能已经在排期中，敬请期待！
