### ISSUE TITLE
cell subTitle的slot写了没有效果

### ISSUE THREAD

**Issue by tiaotiaozai** [jdf2e/nutui#170]

**Comment by richard1015** [comment]
请提供一下可复现代码

**Comment by guoxiao158** [comment]
<nut-cell :isLink="true" :showIcon="true">
                <span slot="title">我是主标题</span>
                <span slot="sub-title">我是副标，我们都是通过Slot分发的</span>
                <span slot="desc">我是描述</span>
            </nut-cell>

参考以上写法，暂未复现

**Comment by guoxiao158** [comment]
` <nut-cell :isLink="true" :showIcon="true">
                <span slot="title">我是主标题</span>
                <span slot="sub-title">我是副标，我们都是通过Slot分发的</span>
                <span slot="desc">我是描述</span>
            </nut-cell>`
参考以上写法，暂无复现所说的 subTitle的slot写了没有效果
