### ISSUE TITLE
[bug]关于生产模式下Toast组件报hide() is not a function导致无法手动关闭toast

### ISSUE THREAD

**Issue by xjiojio** [jdf2e/nutui#1702]
## 问题描述
Toast组件展示一个提示，并且在完成某些操作后通过返回的toast.hide()方法进行手动关闭，在开发阶段（npm run dev）时是没有问题的，然后打包出来的代码部署服务器上或者是 npm run serve 预览时会报 hide() is not a function 导致无法手动关闭toast

toast 是通过 mountToast 方法进行创建然后返回 instance.component.ctx 作为 toast 实例去调用 hide 方法进行手动关闭，然而问题在于 vue render 函数创建组件在执行到 createComponentInstance 方法时会对运行环境进行判断，非生产环境调用 createDevRenderContext 方法创建了ctx，最终作为 toast 实例返回是可以hide的，然而生产环境下 ctx 被直接赋值为 { _: instance } 导致没有 hide 方法无法正常关闭toast

<img width="390" alt="截屏2022-09-28 00 01 06" src="https://user-images.githubusercontent.com/27629056/192577951-67cc43be-d057-49d8-929a-7c6616651e85.png">

## 最小可复现仓库
https://github.com/xjiojio/toast-demo

## 预期的行为和实际行为
预期行为：生产模式下无报错且可以正常手动关闭toast
实际行为：生产模式下报hide() is not a function无法手动关闭toast

## 复现步骤，具体代码

<img width="390" alt="截屏2022-09-27 23 46 46" src="https://user-images.githubusercontent.com/27629056/192578580-d7a1ac42-ac44-4bc7-85c7-7c978aca2084.png">

`npm run build & npm run serve`

## 相关环境信息
- **操作系统**：Win10、 macOS Big Sur 11.2.3
- **Node 版本**：16.17.0
- **NutUI 版本**： @nutui/nutui 3.2.2
- **Vue 版本**：3.1.0
- **引用方式**：NPM

**Comment by richard1015** [comment]
3.2.4已修复
