### ISSUE TITLE
[bug] Toast  组件微信小程序 报错_nutui_nutui_taro_dist_packages_es_Toast__WEBPACK_IMPORTED_MODULE_0__.default.text is not a function

### ISSUE THREAD

**Issue by zuilikanhua** [jdf2e/nutui#1712]
## 问题描述

Toast 组件在微信小程序使用的时候报错
_nutui_nutui_taro_dist_packages_es_Toast__WEBPACK_IMPORTED_MODULE_0__.default.fail is not a function
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
```
<template>
  <view @tap="textToast('网络失败，请稍后再试~')">点击</view>
</template>
<script>
import { Toast } from '@nutui/nutui-taro';
export default {
  setup() {
    const textToast = (msg) => {
      Toast.text(msg);
    };
    return {
      textToast,
    };
  }
}
</script>
```

## 相关环境信息
- **操作系统**：
- window 10 x64
- **Node 版本**：
-   v16.15.1
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- "@nutui/nutui-taro": "^3.1.8",
    "@tarojs/components": "3.5.5",
    "@tarojs/helper": "3.5.5",
    "@tarojs/plugin-framework-vue3": "3.5.5",
    "@tarojs/plugin-html": "3.5.5",
    "@tarojs/plugin-platform-alipay": "3.5.5",
    "@tarojs/plugin-platform-jd": "3.5.5",
    "@tarojs/plugin-platform-qq": "3.5.5",
    "@tarojs/plugin-platform-swan": "3.5.5",
    "@tarojs/plugin-platform-tt": "3.5.5",
    "@tarojs/plugin-platform-weapp": "3.5.5",
    "@tarojs/router": "3.5.5",
    "@tarojs/runtime": "3.5.5",
    "@tarojs/shared": "3.5.5",
    "@tarojs/taro": "3.5.5",
    "@tarojs/taro-h5": "3.5.5",
    "vue": "^3.0.0"
- **Vue 版本**：
- 
- **引用方式**：  CDN / NPM ？
- npm

**Comment by szg2008** [comment]
小程序目前不支持函数式调用哈，只支持标签式。如果要使用的话，可使用Taro原生的toast

**Comment by zuilikanhua** [comment]
好的
