### ISSUE TITLE
[bug]nut-checkbox和nut-checkboxgroup同时使用时，nut-checkbox的change事件state返回值永远是true

### ISSUE THREAD

**Issue by knoic** [jdf2e/nutui#1719]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
预期：nut-checkbox勾选时state===true，取消勾选state===false
实际：nut-checkbox勾选时state===true，取消勾选state===true

## 复现步骤，具体代码
      <nut-checkboxgroup v-model="checkboxgroup1">
        <template v-for="(item,index) in groupInfo" :key="index">
          <nut-cell title="">
            <nut-checkbox :label="item" icon-size="20" @change="changeBusinessBox">{{ item.name }}</nut-checkbox>
          </nut-cell>
        </template>
      </nut-checkboxgroup>

function changeBusinessBox(state,label){
  console.log(state,label)
}

## 相关环境信息
- **操作系统**：版本	Windows 11 专业版 版本	21H2
- **Node 版本**：v16.15.0
- **NutUI 版本**： 3.2.2
- **Vue 版本**：3.2.38
- **引用方式**：  NPM

**Comment by szg2008** [comment]
你好，如果想要在nut-checkboxgroup中使用checkbox的change事件，需要给单独的checkbox绑定v-model才可以拿到最新的状态。如下：
`<nut-checkbox label="1" v-model="value" @change="change">label</nut-checkbox>`。
建议在使用group的时候直接通过父级的change事件来拿到当前checkbox的状态值。
`<nut-checkboxgroup v-model="checkboxgroup" :max="2" @change="change"></nut-checkboxgroup>`。
checkbox的change事件一般是在单独使用的时候调用的。

**Comment by gitdust** [comment]
checkboxgroup 只能拿到选中的值，无法获取所有项的选中状态
如果业务需要做选项互斥，就没办法满足
