### ISSUE TITLE
[bug] 生成微信小程序css报错

### ISSUE THREAD

**Issue by 893949088** [jdf2e/nutui#1720]
## 问题描述

![image](https://user-images.githubusercontent.com/4034377/193177186-e3057fa9-b803-4627-a063-7fcedb690994.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
去掉图片上那个css的代码，就正常了

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：16.17.1
- **NutUI 版本**： ^3.2.3-beta.2
- **Vue 版本**：^3.2.31
- **引用方式**：  CDN / NPM ？

**Comment by szg2008** [comment]
升级到3.2.3版本试一下呢

**Comment by yangjisen** [comment]
问题+1, taro3.5.6, nut-ui降级到3.2.2就没有问题

**Comment by 893949088** [comment]
@szg2008 不行

**Comment by 6xiaoxin** [comment]
3.2.3也报同样的问题

**Comment by 893949088** [comment]
@richard1015 看看呢

**Comment by szg2008** [comment]
@893949088 方便提供下最小可复现的仓库吗？

**Comment by 893949088** [comment]
@szg2008 我日，这还需要复现？

**Comment by sdmu-gaoqi** [comment]
Taro init 选择 taro+nutui3的模板启动就可以复现
