### ISSUE TITLE
[bug] picker 组件 3.2.3版本，在支付宝小程序，无法显示，只显示了titlebar栏目

### ISSUE THREAD

**Issue by lingdulib** [jdf2e/nutui#1721]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
const columns = ref([
        { text: '南京市', value: 'NanJing' },
        { text: '无锡市', value: 'WuXi' },
        { text: '海北藏族自治区', value: 'ZangZu' },
        { text: '北京市', value: 'BeiJing' },
        { text: '连云港市', value: 'LianYunGang' },
        { text: '浙江市', value: 'ZheJiang' },
        { text: '江苏市', value: 'JiangSu' }
      ]);
 <nut-picker
      v-model:visible="voucherShow"
      :columns="columns"
      title="券类型"
      @confirm="confirmVoucher"
      :three-dimensional="false"
    />

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 3.2.3
- **Vue 版本**：3.2
- **引用方式**： npm

**Comment by Drjingfubo** [comment]
使用3.2.4试下

**Comment by Drjingfubo** [comment]
支付宝小程序目前还在优化中，可以使用3.2.6试下
