### ISSUE TITLE
[bug] Menu问题

### ISSUE THREAD

**Issue by zhangpei00** [jdf2e/nutui#1723]
## 问题描述
使用Menu 菜单组件出现自动重复生成下拉菜单

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

预期:声明了几个菜单就是几个菜单
实际:点击第一个菜单之后再次点击第一个菜单会生成额外菜单，且其他菜单点击没有效果

## 复现步骤，具体代码

**<nut-menu>
               <nut-menu-item v-model="value1" @@change="selectChange1" :options="options1"  /> 
               <nut-menu-item v-model="value2" @@change="selectChange2" :options="options2"  />
 </nut-menu>**
  data() {
                return {
                      options1: [{text: '全部渠道', value: 99},{text: '校招类', value: 0},{text: '社招类', value: 1}],
                      options2: [{text: '全部职位', value: 'b'}],
                      value1: 99,
                      value2:'b'
                }
            }

 selectChange1(e){ // 选择职位渠道后
                    //console.log('val', e);
                },
  selectChange2(e){ // 选择职位类别后
      //console.log('val', e);
  },

## 相关环境信息
- **操作系统**：版本 Windows 11 专业版
- **Node 版本**：无
- **NutUI 版本**： 3.2.2
- **Vue 版本**：3.2.37
- **引用方式**：  JS引用

**Comment by eiinu** [comment]
3.2.3 版本中修复了 menu 的一些问题，可以尝试升级到 3.2.3 看看这个问题是否还存在

**Comment by zhangpei00** [comment]
使用了3.2.3版本还是一样的，https://github.com/zhangpei00/nutui_bug.git  这是git仓库吧最小实现

**Comment by yangjinjun3** [comment]
嗯， 已经复现，我们排查下。
另外，您提交了个重复的issue（#1726），帮您关闭了，请知晓！

**Comment by zhangpei00** [comment]
好的麻烦了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月21日(星期五) 下午5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdf2e/nutui] [bug] (Issue #1723)





 
嗯， 已经复现，我们排查下。
 另外，您提交了个重复的issue（#1726），帮您关闭了，请知晓！

**Comment by yangjinjun3** [comment]
Item 别用自闭合标签试试！

**Comment by eiinu** [comment]
CDN 模式下不支持在 HTML 里直接使用自闭合标签，详细内容参考Vue 官方风格指南中的 [自闭合组件](https://cn.vuejs.org/style-guide/rules-strongly-recommended.html#self-closing-components)
