### ISSUE TITLE
[bug]  WXSS 文件编译错误

### ISSUE THREAD

**Issue by 6xiaoxin** [jdf2e/nutui#1727]
## 问题描述

将nutui的版本升级到3.2.3后出现这个问题
已经将taro的各个依赖升级3.5.6，还是无法解决
![image](https://user-images.githubusercontent.com/55842780/194507505-ba3fcbb4-9878-46f7-8036-21ac640ba22d.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
https://github.com/6xiaoxin/taro-vue3-template

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：v16.11.0
- **NutUI 版本**： 3.2.3
- **Vue 版本**：3.0.0
- **引用方式**：NPM

**Comment by gitub-yangjisen** [comment]
降级nutui 3.2.2 临时解决

**Comment by 6xiaoxin** [comment]
> 降级nutui 3.2.2 临时解决

将了也不行啊

**Comment by 6xiaoxin** [comment]
> 降级nutui 3.2.2 临时解决

@gitub-yangjisen 你的taro依赖是什么版本，能否截个图给我看看呢

**Comment by richard1015** [comment]
https://github.com/jdf2e/nutui-demo/tree/master/taro3.5.6

参考 此仓库

**Comment by vance-liu** [comment]
https://github.com/jdf2e/nutui/issues/1735

**Comment by yunhouhuang** [comment]
所以问题具体出现在哪里？

**Comment by 6xiaoxin** [comment]
> https://github.com/jdf2e/nutui-demo/tree/master/taro3.5.6
> 
> 参考 此仓库

@richard1015 我根据此仓库的依赖在我自己的项目进行更新，还是报同样的错误

**Comment by 6xiaoxin** [comment]
> 所以问题具体出现在哪里？

@yarnk 不清楚啊
