### ISSUE TITLE
[bug] imagePreview组件，iphone12以下一点视频播放遮罩就自己关了，content-close=false也阻止不了

### ISSUE THREAD

**Issue by westfruit** [jdf2e/nutui#1729]
## 问题描述

 imagePreview组件，iphone12以下一点视频播放遮罩就自己关了，content-close=false也阻止不了。
 可以用iphone7,iphone plus测试

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- 3.2.2--3.2.3
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by yangxiaolu1993** [comment]
感谢对NutUI的支持，问题已在 3.2.6 版本中解决
