### ISSUE TITLE
nut-datepicker

### ISSUE THREAD

**Issue by Tanglan123** [jdf2e/nutui#173]
nut-datepicker 组件，设置startDate 和 endDate 没有效果

**Comment by richard1015** [comment]
> nut-datepicker 组件，设置startDate 和 endDate 没有效果

请提供一下最小复现代码

**Comment by Tanglan123** [comment]
> > nut-datepicker 组件，设置startDate 和 endDate 没有效果
> 
> 请提供一下最小复现代码

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
		<meta name="format-detection" content="telephone=no,email=no">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.6/dist/nutui.min.css">
		<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.6/dist/nutui.min.js"></script>
	</head>
	<body>
		<div id="app">
			<input type="" name="" @click="visible=true">
			<nut-datepicker 
				:is-visible="visible" 
				title="aaa" 
				type="datetime" 
				startDate="2018/10/11" 
				endDate="2019-11-11" 
				defaultValue="2019-10-11 11:08" 
			></nut-datepicker>
		</div>
		<script type="text/javascript">
			new Vue({
				el: "#app",
				data: {
					visible: false
				}
			})
		</script>
	</body>
</html>

**Comment by Tanglan123** [comment]
> > nut-datepicker 组件，设置startDate 和 endDate 没有效果
> 
> 请提供一下最小复现代码

`<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
		<meta name="format-detection" content="telephone=no,email=no">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.6/dist/nutui.min.css">
		<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.6/dist/nutui.min.js"></script>
	</head>
	<body>
		<div id="app">
			<input type="" name="" @click="visible=true">
			<nut-datepicker 
				:is-visible="visible" 
				title="aaa" 
				type="datetime" 
				startDate="2018/10/11" 
				endDate="2019-11-11" 
				defaultValue="2019-10-11 11:08" 
			></nut-datepicker>
		</div>
		<script type="text/javascript">
			new Vue({
				el: "#app",
				data: {
					visible: false
				}
			})
		</script>
	</body>
</html>`

**Comment by Tanglan123** [comment]
> > nut-datepicker 组件，设置startDate 和 endDate 没有效果
> 
> 请提供一下最小复现代码

`<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
		<meta name="format-detection" content="telephone=no,email=no">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.6/dist/nutui.min.css">
		<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.6/dist/nutui.min.js"></script>
	</head>
	<body>
		<div id="app">
			<input type="" name="" @click="visible=true">
			<nut-datepicker 
				:is-visible="visible" 
				title="aaa" 
				type="datetime" 
				startDate="2018/10/11" 
				endDate="2019-11-11" 
				defaultValue="2019-10-11 11:08" 
			></nut-datepicker>
		</div>
		<script type="text/javascript">
			new Vue({
				el: "#app",
				data: {
					visible: false
				}
			})
		</script>
	</body>
</html>`

**Comment by richard1015** [comment]
> ```
> `>` > nut-datepicker 组件，设置startDate 和 endDate 没有效果
> > 
> > 请提供一下最小复现代码
> <!DOCTYPE html>
> <html>
> 	<head>
> 		<meta charset="UTF-8">
> 		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
> 		<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
> 		<meta name="format-detection" content="telephone=no,email=no">
> 		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.6/dist/nutui.min.css">
> 		<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
> 		<script src="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.6/dist/nutui.min.js"></script>
> 	</head>
> 	<body>
> 		<div id="app">
> 			<input type="" name="" @click="visible=true">
> 			<nut-datepicker 
> 				:is-visible="visible" 
> 				title="aaa" 
> 				type="datetime" 
> 				startDate="2018/10/11" 
> 				endDate="2019-11-11" 
> 				defaultValue="2019-10-11 11:08" 
> 			></nut-datepicker>
> 		</div>
> 		<script type="text/javascript">
> 			new Vue({
> 				el: "#app",
> 				data: {
> 					visible: false
> 				}
> 			})
> 		</script>
> 	</body>
> </html>
> ```


#### 当采用   页面直接引用 CDN 资源时，请遵循 [https://cn.vuejs.org/v2/guide/components-props.html](url)

HTML 中的特性名是大小写不敏感的，所以浏览器会把所有大写字符解释为小写字符。这意味着当你使用 DOM 中的模板时，camelCase (驼峰命名法) 的 prop 名需要使用其等价的 kebab-case (短横线分隔命名) 命名：

###### 按照下发使用方式即可 ：）

``` html
  <nut-datepicker :is-visible="visible" 
            title="请选择日期时间" 
            type="datetime" 
            start-date="2018-10-11"
            end-date="2019-11-11" 
            default-value="2019-10-11 11:08">
        </nut-datepicker>
```

**Comment by Tanglan123** [comment]
> > ```
> > `>` > nut-datepicker 组件，设置startDate 和 endDate 没有效果
> > > 
> > > 请提供一下最小复现代码
> > <!DOCTYPE html>
> > <html>
> > 	<head>
> > 		<meta charset="UTF-8">
> > 		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
> > 		<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
> > 		<meta name="format-detection" content="telephone=no,email=no">
> > 		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.6/dist/nutui.min.css">
> > 		<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
> > 		<script src="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.1.6/dist/nutui.min.js"></script>
> > 	</head>
> > 	<body>
> > 		<div id="app">
> > 			<input type="" name="" @click="visible=true">
> > 			<nut-datepicker 
> > 				:is-visible="visible" 
> > 				title="aaa" 
> > 				type="datetime" 
> > 				startDate="2018/10/11" 
> > 				endDate="2019-11-11" 
> > 				defaultValue="2019-10-11 11:08" 
> > 			></nut-datepicker>
> > 		</div>
> > 		<script type="text/javascript">
> > 			new Vue({
> > 				el: "#app",
> > 				data: {
> > 					visible: false
> > 				}
> > 			})
> > 		</script>
> > 	</body>
> > </html>
> > ```
> 
> #### 当采用 页面直接引用 CDN 资源时，请遵循 [https://cn.vuejs.org/v2/guide/components-props.html](url)
> HTML 中的特性名是大小写不敏感的，所以浏览器会把所有大写字符解释为小写字符。这意味着当你使用 DOM 中的模板时，camelCase (驼峰命名法) 的 prop 名需要使用其等价的 kebab-case (短横线分隔命名) 命名：
> 
> ###### 按照以下使用方式即可 ：）
> ```
>   <nut-datepicker :is-visible="visible" 
>             title="请选择日期时间" 
>             type="datetime" 
>             start-date="2018-10-11"
>             end-date="2019-11-11" 
>             default-value="2019-10-11 11:08">
>         </nut-datepicker>
> ```

好的，解决了！
还有一个问题：:start-date="minDate" ，我把最小时间动态绑定，在mounted的时候改变值，但是好像没用啊？

**Comment by richard1015** [comment]
@Tanglan123  
请提供一下复现代码
另外推荐您加入我们nutui微信交流群,方便及时沟通
<img src="https://img14.360buyimg.com/imagetools/jfs/t1/92590/24/1521/112113/5dc23166E0feb7b2d/3808305af58241ae.jpg" width="250" />

**Comment by Tanglan123** [comment]
> @Tanglan123
> 请提供一下复现代码
> 另外推荐您加入我们nutui微信交流群,方便及时沟通
> <img alt="" width="250" src="https://camo.githubusercontent.com/a68537265575e3bc34752c5c42ccc5190f2bc3bc/68747470733a2f2f696d6731342e333630627579696d672e636f6d2f696d616765746f6f6c732f6a66732f74312f39323539302f32342f313532312f3131323131332f35646332333136364530666562376232642f333830383330356166353832343161652e6a7067">

`<nut-datepicker 
				:is-visible="timeVisible" 
				title="请选择日期时间" 
				type="datetime" 
				:start-date="minDate" 
				:end-date="maxDate" 
				:default-value="defaultTime" 
				@close="switchPicker('timeVisible')" 
				@choose="setChooseValue"
			></nut-datepicker>
mounted: function(){
this.minDate = "2019-10-10";
					this.maxDate = "2019-11-11";
}
`

**Comment by Tanglan123** [comment]
> @Tanglan123
> 请提供一下复现代码
> 另外推荐您加入我们nutui微信交流群,方便及时沟通
> <img alt="" width="250" src="https://camo.githubusercontent.com/a68537265575e3bc34752c5c42ccc5190f2bc3bc/68747470733a2f2f696d6731342e333630627579696d672e636f6d2f696d616765746f6f6c732f6a66732f74312f39323539302f32342f313532312f3131323131332f35646332333136364530666562376232642f333830383330356166353832343161652e6a7067">

`<nut-datepicker 
				:is-visible="timeVisible" 
				title="请选择日期时间" 
				type="datetime" 
				:start-date="minDate" 
				:end-date="maxDate" 
				:default-value="defaultTime" 
				@close="switchPicker('timeVisible')" 
				@choose="setChooseValue"
			></nut-datepicker>
data: {
					timeVisible: false, //是否显示选择时间弹窗
					defaultTime: "", //默认当前时间
					minDate: "", //限制最小时间
					maxDate: "", //限制最大时间
				},
				mounted: function(){
					this.minDate = "2019-10-10";
					this.maxDate = "2019-11-11";
				},`

**Comment by richard1015** [comment]
v2.1.7版本已解决
