### ISSUE TITLE
[bug] Address 地址组件打开后点击遮罩层关闭组件 会触发两次 关闭回调

### ISSUE THREAD

**Issue by ahljj** [jdf2e/nutui#1731]
## 问题描述
Address 地址组件打开后点击遮罩层关闭组件 会触发两次 关闭回调 ，官方demo也是一样的问题。如图第一张图触发 emit("close"); 但是Address组件已经对showPopup属性做了监听也会调用close方法，如图二。
![image](https://user-images.githubusercontent.com/61975402/194749828-73a66512-8030-4501-83e6-96bf452c06be.png)
![image](https://user-images.githubusercontent.com/61975402/194749866-ec9607d4-d527-4f04-a018-6454e7fa74af.png)

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：16.16.0
- **NutUI 版本**：3.23
- **Vue 版本**：3.0.0
- **引用方式**：   NPM

**Comment by yangxiaolu1993** [comment]
已解决，在下个版本 3.2.4 更新
