### ISSUE TITLE
[suggest]基于Picker实现的组件的Props绑定有遗漏问题的也许可以通过使用v-bind来解决

### ISSUE THREAD

**Issue by eGluZl** [jdf2e/nutui#1733]
## 你建议我们做什么？

现在基于Picker实现的组件（如actionsheet、datepicker）都包含了Picker的Props，但是在使用这些组件并设置了Picker的Props时，这些组件并不一定会使用Picker的Props。
例如我在使用datepicker组件时，设置safe-area-inset-bottom为true，但是datepicker的源码并没有把这个属性设置到Picker中，导致datepicker组件不能开启 iphone 系列全面屏底部安全区适配。

如果你能使用v-bind来把Props设置到Picker中

它将使这个问题得到解决

## 其它

无

**Comment by yangxiaolu1993** [comment]
你好，Datepicker 暂时不支持 safe-area-inset-bottom 属性，可以提供一个 Demo 吗？

**Comment by eGluZl** [comment]
> 你好，Datepicker 暂时不支持 safe-area-inset-bottom 属性，可以提供一个 Demo 吗？

https://github.com/eGluZl/nut-ui-demo.git

safe-area-inset-bottom属性是popup组件的属性，之前发现actionsheet也是设置了之后无效的，可能需要检查一下依赖popup组件的组件

**Comment by yangxiaolu1993** [comment]
感谢反馈，我们也会注意其他组件类似的问题，DatePicker 组件已添加 safe-area-inset-bottom  属性，NutUI v3.2.4 版本发布

**Comment by richard1015** [comment]
3.2.4已修复
