### ISSUE TITLE
[bug] 图片预览组件PC上的demo滑动时会关闭预览弹窗

### ISSUE THREAD

**Issue by xxxsf** [jdf2e/nutui#1734]
## 问题描述

图片预览组件PC上的demo滑动时会关闭预览弹窗

https://nutui.jd.com/#/zh-CN/component/ImagePreview

<img width="436" alt="image" src="https://user-images.githubusercontent.com/14307551/194793786-f441016e-4ae2-4425-ac7e-266bec89cfd9.png">

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by yangxiaolu1993** [comment]
建议在移动端模式下浏览，官网 Imagepreview 展示是嵌入的，手势支持不太流畅

**Comment by xxxsf** [comment]
属于程序bug，已提交pr：https://github.com/jdf2e/nutui/pull/1759
