### ISSUE TITLE
[ WXSS 文件编译错误] ./app.wxss

### ISSUE THREAD

**Issue by vance-liu** [jdf2e/nutui#1735]
https://github.com/jdf2e/nutui/blob/eab94ea089f389aa045e5427d5b17d7c39687e22/src/packages/__VUE/barrage/index.scss#L1

![image](https://user-images.githubusercontent.com/9456694/194846799-129909ed-e8d5-4490-b2de-9ffb58c0bb40.png)

**Comment by vance-liu** [comment]
https://github.com/jdf2e/nutui/issues/1735

**Comment by thetbw** [comment]
我这也是，安装@tarojs/plugin-html插件也不行

**Comment by yunhouhuang** [comment]
me too

**Comment by richard1015** [comment]
3.2.4已修复
