### ISSUE TITLE
nut-dialog组件在小程序中使用导致v-show失效[bug]

### ISSUE THREAD

**Issue by songxianling** [jdf2e/nutui#1736]
## 问题描述

一个页面3个tab切换；每个tab单独成一个小组件（使用v-show控制显示隐藏；等于缓存了数据）；其中2个组件内都使用了nut-dialog组件；导致v-show的判断没有效果；两个单独的小组件都同时显示了；删除使用nut-dialog的代码；就正常了。两个小组件都不能使用nut-dialog！！

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
组件是独立开的；应该v-show正常显示

## 复现步骤，具体代码

// 3个tab

    <SmileyBader v-show="topTabActIndex === 0" />
    
    <CouponCom v-show="topTabActIndex === 1" />
    
    <orderRecord v-show="topTabActIndex === 2" />

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？
- Taro v3.5.5

  Taro CLI 3.5.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.5 => 3.5.5
      @tarojs/components: 3.5.5 => 3.5.5
      @tarojs/helper: 3.5.5 => 3.5.5
      @tarojs/mini-runner: 3.5.5 => 3.5.5
      @tarojs/plugin-framework-vue3: 3.5.5 => 3.5.5
      @tarojs/plugin-html: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-alipay: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-jd: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-qq: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-swan: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-tt: 3.5.5 => 3.5.5
      @tarojs/plugin-platform-weapp: 3.5.5 => 3.5.5
      @tarojs/plugin-vue-devtools: ^3.5.6 => 3.5.6
      @tarojs/router: 3.5.5 => 3.5.5
      @tarojs/runtime: 3.5.5 => 3.5.5
      @tarojs/shared: 3.5.5 => 3.5.5
      @tarojs/taro: ^3.5.6 => 3.5.6
      @tarojs/taro-h5: 3.5.5 => 3.5.5
      @tarojs/webpack-runner: 3.5.5 => 3.5.5
      "@nutui/nutui-taro": "^3.2.2",
      babel-preset-taro: 3.5.5 => 3.5.5
      eslint-config-taro: 3.5.5 => 3.5.5
    npmGlobalPackages:
      typescript: 4.8.3

**Comment by richard1015** [comment]
nut-dialog需提到 tabs层级外
