### ISSUE TITLE
nut-dialog noFooter属性报错

### ISSUE THREAD

**Issue by TankRyze** [jdf2e/nutui#174]
<img width="1834" alt="WeChatc541a6bec0b5aa3aee7fde7bd7d5b015" src="https://user-images.githubusercontent.com/22748893/68873693-f8175e00-073a-11ea-8965-bf8f0c4261b6.png">
<img width="874" alt="WeChat0e6d298be517a4e79e94002f540e2f39" src="https://user-images.githubusercontent.com/22748893/68873738-08c7d400-073b-11ea-9545-2603e4ce0d09.png">
在谷歌浏览器模拟移动端看见的报错信息，页面功能是可以实现

**Comment by richard1015** [comment]
> <img alt="WeChatc541a6bec0b5aa3aee7fde7bd7d5b015" width="1834" src="https://user-images.githubusercontent.com/22748893/68873693-f8175e00-073a-11ea-8965-bf8f0c4261b6.png">
> 
> <img alt="WeChat0e6d298be517a4e79e94002f540e2f39" width="874" src="https://user-images.githubusercontent.com/22748893/68873738-08c7d400-073b-11ea-9545-2603e4ce0d09.png">
> 
> 在谷歌浏览器模拟移动端看见的报错信息，页面功能是可以实现

![image](https://user-images.githubusercontent.com/13060263/68908973-cc6e9500-0787-11ea-9adb-ababd35f8ad4.png)
noFooter接受值为bool类型，请使用双向绑定传参    :noFooter="true"

**Comment by TankRyze** [comment]
<img width="856" alt="WechatIMG5" src="https://user-images.githubusercontent.com/22748893/68994057-684bee00-08b9-11ea-84bb-40ef39837df1.png">
![WechatIMG6](https://user-images.githubusercontent.com/22748893/68994070-97faf600-08b9-11ea-8a21-0d5d7183be37.jpeg)
你好，动态绑定数据是没有了错误信息，但是他的footer部分没有隐藏。辛苦看一下，谢谢

**Comment by richard1015** [comment]
> <img alt="WechatIMG5" width="856" src="https://user-images.githubusercontent.com/22748893/68994057-684bee00-08b9-11ea-84bb-40ef39837df1.png">
> 
> 这样配置不能将footer部分隐藏，没有报错信息。麻烦看一下，


noFooter | 是否隐藏底部按钮栏  
true 代表隐藏  false代表显示    你设置的false当然是不隐藏了
