### ISSUE TITLE
[bug]radio(checkbox)组件使用本地路径图片，切换选项时icon未改变

### ISSUE THREAD

**Issue by Zeppo241** [jdf2e/nutui#1740]
## 问题描述

radio组件的icon-name和icon-active-name属性均使用本地路径图片，但切换选项时icon没有切换
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
## 预期的行为和实际行为
预期：切换选项后icon也随之切换
实际：切换选项后icon未有变化
## 复现步骤，具体代码

```
html:
<nut-radiogroup v-model="selected">
        <nut-radio v-for="rosterId in rosters" :key="rosterId" :label="rosterId" :icon-name="radioUnCheckedIcon" :icon-active-name="radioCheckedIcon" icon-size="40rpx">
          <view>{{ rosterId }} </view>
       </nut-radio>
</nut-radiogroup> ```

js:
```import radioUnCheckedIcon from '../../../images/radio_un_checked.svg' \n
 import radioCheckedIcon from '../../../images/radio_checked1.svg'
const selected = ref(0)
const rosters = ref([0,1,2,3])```
<!-- https://github.com/YOUR_REPOSITORY_URL -->

<!-- 请提供复现步骤，错误日志以及相关配置 -->
<!-- 可以尝试不要锁版本，重新安装依赖试试先 -->


## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： nutui-taro3.2.2
- **Vue 版本**：3.2.6
- **引用方式**：  NPM

**Comment by qingtian5266** [comment]
没复现，我拿 png 试的
![image](https://user-images.githubusercontent.com/28749518/196145112-0b670aba-c3a3-4f85-b3f4-7389602be9b0.png)

**Comment by richard1015** [comment]
```
经过测试没问题，辛苦提供复现仓库

<template>
 <nut-icon :name="playing?r1:r2"></nut-icon>
</tempalte>

import r1 from './1.png'
import r2 from './2.png'
import icons from './../../../../../../../packages/styles/font/config.json';
export default {
  props: {},
  setup() {
    const playing = ref(false)
    setTimeout(() => {
      playing.value=true;
    }, 3000);
    return {playing,r1,r2 };
  }
};
```

**Comment by Zeppo241** [comment]
> ```
> 经过测试没问题，辛苦提供复现仓库
> 
> <template>
>  <nut-icon :name="playing?r1:r2"></nut-icon>
> </tempalte>
> 
> import r1 from './1.png'
> import r2 from './2.png'
> import icons from './../../../../../../../packages/styles/font/config.json';
> export default {
>   props: {},
>   setup() {
>     const playing = ref(false)
>     setTimeout(() => {
>       playing.value=true;
>     }, 3000);
>     return {playing,r1,r2 };
>   }
> };
> ```

我用的是svg图片，不确定是不是和这个有关系

**Comment by Zeppo241** [comment]
> 没复现，我拿 png 试的 ![image](https://user-images.githubusercontent.com/28749518/196145112-0b670aba-c3a3-4f85-b3f4-7389602be9b0.png)

我用的是svg图片
