### ISSUE TITLE
[bug]icon组件的name属性若是根据变量判断，变量修改后，name值未随之修改

### ISSUE THREAD

**Issue by Zeppo241** [jdf2e/nutui#1741]
## 问题描述

nut-icon的name值根据一个变量值判断，当这个变量修改后，name值未随之修改
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
预期：点击icon，name值应切换为resumeIcon
实际：点击icon，name值保持不变
## 复现步骤，具体代码
```
html:
<nut-icon :name="playing ? pauseIcon : resumeIcon" @click="playing = true" />

js: 
import resumeIcon from '../../images/pngs/player_resume.png'
import pauseIcon from '../../images/pngs/player_pause.png'

const playing = ref(false)
```

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： nutui-taro3.2.2
- **Vue 版本**：3.2.6
- **引用方式**：NPM

**Comment by qingtian5266** [comment]
写两个 nut-icon ，用 v-if 判断呢？我用网络图片 url 试了下好使啊

**Comment by richard1015** [comment]
```
经过测试没问题，辛苦提供复现仓库

<template>
 <nut-icon :name="playing?r1:r2"></nut-icon>
</tempalte>

import r1 from './1.png'
import r2 from './2.png'
import icons from './../../../../../../../packages/styles/font/config.json';
export default {
  props: {},
  setup() {
    const playing = ref(false)
    setTimeout(() => {
      playing.value=true;
    }, 3000);
    return {playing,r1,r2 };
  }
};
```

**Comment by eiinu** [comment]
nut-icon 组件内部使用的是 img 标签，在 Taro 下无法动态修改 src，问题已反馈 [issue](https://github.com/NervJS/taro/issues/12673)，我们会持续关注进展。

**Comment by eiinu** [comment]
Taro 已修复这个问题，[Issue](https://github.com/NervJS/taro/issues/12673)， [PR](https://github.com/NervJS/taro/pull/12698)，预计 Taro 3.5.8 上线。
