### ISSUE TITLE
[bug] Collapse 折叠面板 内容如果异步加载，展开高度有问题

### ISSUE THREAD

**Issue by wy1037** [jdf2e/nutui#1743]
<template>
<nut-collapse v-model:active="activeNames" icon="down-arrow">  
  <nut-collapse-item :title="title2" :name="2">
         在产品的功能、体验、易用性和灵活性等各个方面做了全面的升级！
  </nut-collapse-item>
  <nut-collapse-item :title="title3" :name="3" disabled>
    <div id="asyncDiv"><div>
  </nut-collapse-item>
</nut-collapse>
</template>

描述：
1，在 nut-collapse-item 里，如果内容是直接 写死的，如上“ 在产品的功能、体验……”，点击展开时，高度没有问题；
2，但是当我的内容是通过 axios 加载到 asyncDiv里，点击展开的时候，组件自己也不知道要展开的高度是多少。因为内容还没有到来，axios 还在从服务端请求中。如果内容较多的时候，只显示出来一部分。即高度不够。
3，希望此组件等我把数据加载到 nut-collapse-item内部后，他自己能调整好高度。

**Comment by ieu** [comment]
目测是因为没有 deep watch：

```javascript
watch(
  () => ctx?.slots?.default?.(),
  () => {
    setTimeout(() => {
      animation();
    }, 300);
  }
);
```


一个临时解决方法：

```javascript
const collapseItem = ref(null);
collapseItem.animation();
```

**Comment by qingtian5266** [comment]
我试了一下，可以自动撑开高度啊，我用 settimeout 模拟的 axios，是不是版本问题？

**Comment by wy1037** [comment]
版本信息：
/*!
* @nutui/nutui v3.2.2 Thu Sep 08 2022 22:10:21 GMT+0800 (中国标准时间)
* (c) 2022 @jdf2e.
* Released under the MIT License.
*/



我在&nbsp;change 事件中获取数据的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月17日(星期一) 下午4:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdf2e/nutui] [bug] Collapse 折叠面板 内容如果异步加载，展开高度有问题 (Issue #1743)





 
我试了一下，可以自动撑开高度啊，我用 settimeout 模拟的 axios，是不是版本问题？

**Comment by qingtian5266** [comment]
真没复现出来，你只能提供 demo 了


```html
<nut-collapse @change="change">
      <nut-collapse-item :title="translate('title2')" :name="2">
        {{ citem}}
      </nut-collapse-item>
</nut-collapse>

const change = (name: string) => {
      console.log(`点击了name是${name}的面板`);
      setTimeout(() => {
        citem.value = '一大堆文字xxxxxx'
      }, 3000);
    };
```

**Comment by wy1037** [comment]
好的。谢谢。等我明天研究下，如果还不行，就做个demo给你。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月17日(星期一) 下午5:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdf2e/nutui] [bug] Collapse 折叠面板 内容如果异步加载，展开高度有问题 (Issue #1743)





 
真没复现出来，你只能提供 demo 了
         {{ citem}}        
const change = (name: string) =&gt; {
 console.log(点击了name是${name}的面板);
 setTimeout(() =&gt; {
 citem.value = '一大堆文字xxxxxx'
 }, 3000);
 };

**Comment by wy1037** [comment]
代码在 压缩包里；
1，你先解决 标题的显示问题；
2，change 事件 中，没有办法知道 当前点击的是哪个，以及这个&nbsp;nut-collapse-item&nbsp; 被点击后是折叠状态还是打开状态；
3，我要在 change 事件 中根据点击的这个数据去加载自己的子项数据；现在加载后，高度的问题先放一下。
4，等你处理了1，2，我再给你演示 展开高度问题

**Comment by ieu** [comment]
这里有一个可以复现的例子：
```vue
<template>
  <nut-collapse v-model:active="activeNames" icon="down-arrow">
    <nut-collapse-item :name="1">
      <template v-slot:mTitle>
        特性
      </template>
      <nut-cell-group>
        <template v-if="features.length > 0">
          <nut-cell v-for="(feat, idx) in features" :key="`feat-${idx}`">
            {{ feat }}
          </nut-cell>
        </template>
        <template v-else>
          <nut-cell>
            无
          </nut-cell>
        </template>
      </nut-cell-group>
    </nut-collapse-item>
  </nut-collapse>
</template>

<script setup>
import {onMounted, ref} from "vue";

const activeNames = ref([1]);
const features = ref([]);

onMounted(() => {
  new Promise((resolve) => {
    setTimeout(() => {
      resolve();
    }, 1000);
  }).then(() => {
    features.value = [
      'NutUI是一套拥有京东风格的轻量级的 Vue 组件库',
      '在产品的功能、体验、易用性和灵活性等各个方面做了全面的升级！',
      '引入Vue3新特性 Composition API、Teleport、Emits 等',
      '基于京东设计语言体系，构建场景',
      'NUTUI3.0重新思考其内在的一致性和可组合性',
      '组件 emits 事件单独提取，增强代码可读性',
    ];
  });
});
</script>
```

完整项目见附件：[demo.zip](https://github.com/jdf2e/nutui/files/9799383/demo.zip)

**Comment by wy1037** [comment]
我们使用的是 cdn 直接引入js 的方式，不使用 构造工具的开发模式。 demo 已发送给你了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jdf2e/nutui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jdf2e/nutui] [bug] Collapse 折叠面板 内容如果异步加载，展开高度有问题 (Issue #1743)





 
这里有一个可以复现的例子：
 <template&gt;   <nut-collapse v-model:active="activeNames" icon="down-arrow"&gt;     <nut-collapse-item :name="1"&gt;       <template v-slot:mTitle&gt;         特性       </template&gt;       <nut-cell-group&gt;         <template v-if="features.length &gt; 0"&gt;           <nut-cell v-for="(feat, idx) in features" :key="`feat-${idx}`"&gt;             {{ feat }}           </nut-cell&gt;         </template&gt;         <template v-else&gt;           <nut-cell&gt;             无           </nut-cell&gt;         </template&gt;       </nut-cell-group&gt;     </nut-collapse-item&gt;   </nut-collapse&gt; </template&gt; <script setup&gt; import {onMounted, ref} from "vue";  const activeNames = ref([1]); const features = ref([]);  onMounted(() =&gt; {   new Promise((resolve) =&gt; {     setTimeout(() =&gt; {       resolve();     }, 1000);   }).then(() =&gt; {     features.value = [       'NutUI是一套拥有京东风格的轻量级的 Vue 组件库',       '在产品的功能、体验、易用性和灵活性等各个方面做了全面的升级！',       '引入Vue3新特性 Composition API、Teleport、Emits 等',       '基于京东设计语言体系，构建场景',       'NUTUI3.0重新思考其内在的一致性和可组合性',       '组件 emits 事件单独提取，增强代码可读性',     ];   }); }); </script&gt;
 
完整项目见附件：demo.zip

**Comment by ieu** [comment]
我们在使用过程中还遇到过一个相关的问题。如果 `nut-collapse-item` 里的内容是动态变化的，有时候在标题和内容间会出现一条“缝”。


经过排查发现，`nut-collapse-item` 在内容为空的时候，会通过 `.empty` 覆盖掉上下的 `margin`。但在内容改变时，没能随之去掉 `empty`。


以下是可复现的例子：

```vue
<template>
  <nut-collapse v-model:active="activeNames" icon="down-arrow">
    <nut-collapse-item :name="1">
      <template v-slot:mTitle>
        特性
      </template>
      <nut-cell-group>
        <template v-if="features.length > 0">
          <nut-cell v-for="(feat, idx) in features" :key="`${Math.random()}-feat-${idx}`">
            {{ feat }}
          </nut-cell>
        </template>
      </nut-cell-group>
    </nut-collapse-item>
  </nut-collapse>
</template>

<script setup>
import {onMounted, ref} from "vue";

const activeNames = ref([1]);
const features = ref([]);

onMounted(() => {
  new Promise((resolve) => {
    setTimeout(() => {
      resolve();
    }, 1000);
  }).then(() => {
    features.value = [
      'NutUI是一套拥有京东风格的轻量级的 Vue 组件库',
      '在产品的功能、体验、易用性和灵活性等各个方面做了全面的升级！',
      '引入Vue3新特性 Composition API、Teleport、Emits 等',
      '基于京东设计语言体系，构建场景',
      'NUTUI3.0重新思考其内在的一致性和可组合性',
      '组件 emits 事件单独提取，增强代码可读性',
    ];
  });
});
</script>

<style>
html, body {
  background-color: #f3f3f3;
  margin: 0;
}
</style>
```


完整项目见附件：[demo.zip](https://github.com/jdf2e/nutui/files/9861851/demo.zip)

**Comment by qingtian5266** [comment]
> 



> 我们在使用过程中还遇到过一个相关的问题。如果 `nut-collapse-item` 里的内容是动态变化的，有时候在标题和内容间会出现一条“缝”。
> 
> 经过排查发现，`nut-collapse-item` 在内容为空的时候，会通过 `.empty` 覆盖掉上下的 `margin`。但在内容改变时，没能随之去掉 `empty`。
> 
> 以下是可复现的例子：
> 
> ```
> <template>
>   <nut-collapse v-model:active="activeNames" icon="down-arrow">
>     <nut-collapse-item :name="1">
>       <template v-slot:mTitle>
>         特性
>       </template>
>       <nut-cell-group>
>         <template v-if="features.length > 0">
>           <nut-cell v-for="(feat, idx) in features" :key="`${Math.random()}-feat-${idx}`">
>             {{ feat }}
>           </nut-cell>
>         </template>
>       </nut-cell-group>
>     </nut-collapse-item>
>   </nut-collapse>
> </template>
> 
> <script setup>
> import {onMounted, ref} from "vue";
> 
> const activeNames = ref([1]);
> const features = ref([]);
> 
> onMounted(() => {
>   new Promise((resolve) => {
>     setTimeout(() => {
>       resolve();
>     }, 1000);
>   }).then(() => {
>     features.value = [
>       'NutUI是一套拥有京东风格的轻量级的 Vue 组件库',
>       '在产品的功能、体验、易用性和灵活性等各个方面做了全面的升级！',
>       '引入Vue3新特性 Composition API、Teleport、Emits 等',
>       '基于京东设计语言体系，构建场景',
>       'NUTUI3.0重新思考其内在的一致性和可组合性',
>       '组件 emits 事件单独提取，增强代码可读性',
>     ];
>   });
> });
> </script>
> 
> <style>
> html, body {
>   background-color: #f3f3f3;
>   margin: 0;
> }
> </style>
> ```
> 
> 完整项目见附件：[demo.zip](https://github.com/jdf2e/nutui/files/9861851/demo.zip)

![223F1915B4AD286B129B82DC3EA8FE2D](https://user-images.githubusercontent.com/28749518/198535014-1f7a5e0d-bed2-4868-853e-c008b05b9793.png)

你好，我测试了一下，出现缝的原因可能是你用了 nut-cell-group 组件自带的样式，你 nut-collapse-item 下面直接放 div 可是试一下。.empty 我看只有个 padding: 0 26px 样式，影响左右没影响上下

**Comment by ieu** [comment]
你好。

你说的对。`.empty` 确实没有设置 `margin`，是我疏忽大意了。

我花了一些时间研究了下。缝的出现应该跟 [margin collapsing](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing) 有关。因为 `.empty` 将上下的 `padding` 设置成 0，导致子元素的 `margin` 溢出。

不过我一开始反馈的时候想的是，`.empty` 在 `nut-collapse-item` 内容不为空时不应该被设置。另外，外部样式会被内部内容影响似乎也不太好。

**Comment by Ymm0008** [comment]
@ieu  @qingtian5266 @wy1037 感谢大家的积极反馈，我会跟进看下如何优化，诚挚邀请各位一起共建，可以加我拉大家进群。
![](https://img13.360buyimg.com/imagetools/s200x200_jfs/t1/187308/9/29678/349561/634fa983E93012590/a641089fdfed5911.png)
