### ISSUE TITLE
[bug]3.2.3构建完缺失类型文件

### ISSUE THREAD

**Issue by agileago** [jdf2e/nutui#1746]
## 问题描述

v3.2.3 缺失类型文件

v3.2.3
https://www.jsdelivr.com/package/npm/@nutui/nutui?path=dist%2Ftypes%2F__VUE%2Fbutton

v3.2.2
https://www.jsdelivr.com/package/npm/@nutui/nutui?path=dist%2Ftypes%2F__VUE%2Fbutton&version=3.2.2
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
https://www.jsdelivr.com/package/npm/@nutui/nutui?path=dist%2Ftypes%2F__VUE%2Fbutton&version=3.2.3

## 预期的行为和实际行为
类型文件正确

## 复现步骤，具体代码
https://www.jsdelivr.com/package/npm/@nutui/nutui?path=dist%2Ftypes%2F__VUE%2Fbutton&version=3.2.2

https://www.jsdelivr.com/package/npm/@nutui/nutui?path=dist%2Ftypes%2F__VUE%2Fbutton&version=3.2.2

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息 v3.2.3
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by szg2008** [comment]
发布了测试版本，nutui/nutui安装v3.2.4-beta.0。nutui/nutui-taro安装v3.2.4-beta.1试试
