### ISSUE TITLE
[bug]3.2.3 picker不显示

### ISSUE THREAD

**Issue by skyunBoss** [jdf2e/nutui#1747]
## 问题描述

3.2.3 picker不显示

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：14.20.0
- **NutUI 版本**： 3.2.3
- **Vue 版本**：3.2.37
- **引用方式**：  CDN / NPM ？

**Comment by Drjingfubo** [comment]
请提供信息完整一点，nutui还是nutui-taro，组件使用方式

**Comment by skyunBoss** [comment]
nutui-taro

<nut-picker
    v-model:visible="show"
    :columns="columns"
    @confirm="confirmPicker"
  >
  </nut-picker>

**Comment by Drjingfubo** [comment]
什么小程序端 微信？ 支付宝？ 京东？

**Comment by skyunBoss** [comment]
微信

**Comment by skyunBoss** [comment]
#1721 应该一个问题

**Comment by Drjingfubo** [comment]
不是一个问题 1721是支付宝小程序。你提供一个最小复现仓库吧

**Comment by skyunBoss** [comment]
只要3.2.3都会出现，你们没有复现？

**Comment by Drjingfubo** [comment]
![image](https://user-images.githubusercontent.com/50685476/195789748-293726b4-95c5-44f0-838d-9df83a2c6d89.png)
目前支付宝和京东小程序会出现不展示的问题，微信不会，你提供一个复现仓库吧

**Comment by Drjingfubo** [comment]
按需引入popup和overlay了吗
![image](https://user-images.githubusercontent.com/50685476/195790170-60270472-1445-4441-9dc1-be1cfec7d1ae.png)

**Comment by skyunBoss** [comment]
https://github.com/skyunBoss/taro-weapp

**Comment by skyunBoss** [comment]
看下呢，vue3版本

**Comment by Drjingfubo** [comment]
taro版本的问题，升级到3.5.6

**Comment by skyunBoss** [comment]
那你们的demo需要更新下

**Comment by skyunBoss** [comment]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/29365288/195807108-e9999468-7698-4b7a-a997-40a62ad49ba2.png">
都需要更新至3.5.6吗？

**Comment by Drjingfubo** [comment]
跟我们的模版没关系 你init的taro版本低了，你先升级下本地的taro版本，重新init一个对比下

**Comment by skyunBoss** [comment]
好的

**Comment by skyunBoss** [comment]
升级了包，代码包就超了

**Comment by yangxiaolu1993** [comment]
有使用分包吗？

**Comment by richard1015** [comment]
尝试 v3.2.4
