### ISSUE TITLE
日历组件点击确定为什么要触发close事件？点击取消按钮触发的是什么事件呢？

### ISSUE THREAD

**Issue by Guanxiaodan** [jdf2e/nutui#175]
## What happens?
日历组件点击确定按钮会触发close事件，但是如果不触发close事件，直接在choose事件中控制is-visible也是可以关闭的。为什么要触发close事件呢？而且取消按钮触发的也是close事件，这样就没办法区分两种点击状况了

## 相关环境信息
- **NutUI 版本**：V2.1.7

**Comment by richard1015** [comment]
> ## What happens?
> 日历组件点击确定按钮会触发close事件，但是如果不触发close事件，直接在choose事件中控制is-visible也是可以关闭的。为什么要触发close事件呢？而且取消按钮触发的也是close事件，这样就没办法区分两种点击状况了
> 
> ## 相关环境信息
> * **NutUI 版本**：V2.1.7

感谢你的反馈，刚才看了一下确实存在这个问题
这边已经记录，将在下个版本v2.1.8优化此问题

**Comment by richard1015** [comment]
v2.1.8已修复
