### ISSUE TITLE
[bug] 签名组件在H5端报错 无法使用

### ISSUE THREAD

**Issue by KevinBrent100** [jdf2e/nutui#1754]
## 问题描述

Signature 签名 根据官网文档写的完全一致，H5页面中无法签名，签名时页面报错，并已经过taro群里多方证实

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
预期应该与官网demo一致，但实际中页面在执行签名时大量报错

## 复现步骤，具体代码
1，taro的cli项目，安装@nutui/nutui-taro（^3.2.1版本）
2，src/app.ts文件 import { Signature } from '@nutui/nutui-taro';
3，App..use(Signature);
4，NutUI官网提供的demo
（资深老用户，已仔细检查细节）

## 相关环境信息
- **操作系统**：Mac OS
- **Node 版本**：16.13.1
- **NutUI 版本**："@nutui/nutui-taro": "^3.2.1"
- **Vue 版本**："vue": "^3.2.36"
- **引用方式**： NPM

**Comment by Ymm0008** [comment]
@KevinBrent100  hello，可以描述下错误信息吗？是不是这个
`
Uncaught TypeError: Cannot read properties of null (reading 'lineTo')
`

**Comment by Ymm0008** [comment]
@KevinBrent100  问题已修改，待下次发版，感谢反馈。
