### ISSUE TITLE
[question] 打开项目任何一个文件都报 ts 或者 eslint 的错误，请问我需要怎么设置，vscode

### ISSUE THREAD

**Issue by qingtian5266** [jdf2e/nutui#1757]
![image](https://user-images.githubusercontent.com/28749518/196104052-a428ddd0-cf79-4842-b008-3022314c1dbb.png)

**Comment by qingtian5266** [comment]
![image](https://user-images.githubusercontent.com/28749518/196105107-9b817a5a-53ae-4380-b0be-7539990d0b44.png)

**Comment by qingtian5266** [comment]
![image](https://user-images.githubusercontent.com/28749518/196118611-69bb5c4f-284d-4849-a3de-16c3c91633a3.png)

看起来代码确实有问题啊，你们是怎么本地开发的？

**Comment by pkjy** [comment]
哈哈 我昨天初始化项目 都还没跑起来 我也不知道他们是咋开发的  #1755 

> ![image](https://user-images.githubusercontent.com/28749518/196118611-69bb5c4f-284d-4849-a3de-16c3c91633a3.png)
> 
> 看起来代码确实有问题啊，你们是怎么本地开发的？

**Comment by richard1015** [comment]
ts类型报错，组件内部在逐渐完善，eslint 暂时关闭插件
