### ISSUE TITLE
dialog使用lockBgScroll时相当于给body加了flex布局

### ISSUE THREAD

**Issue by guoxiao158** [jdf2e/nutui#176]

**Comment by guoxiao158** [comment]
导致页面布局最外层div左对齐或者位置失效

**Comment by richard1015** [comment]
> 导致页面布局最外层div左对齐或者位置失效

使用lockBgScroll时 会在body上添加dialog-open  position:fixed样式，看一下是不是和你自己页面样式冲突导致
