### ISSUE TITLE
[question] nut-video 标签是否可以主动触发全屏 方法

### ISSUE THREAD

**Issue by tangguo13** [jdf2e/nutui#1762]
## 你想知道什么？

<nut-video />标签是否可以主动触发全屏 方法

**Comment by Drjingfubo** [comment]
是指点击视频触发全屏吗

**Comment by tangguo13** [comment]
我想自定义一个全屏 icon ，希望nut-video 组件能暴露一个 全屏的方法

**Comment by Drjingfubo** [comment]
可以使用组件内部的fullScreen()方法来触发全屏
<img width="327" alt="image" src="https://user-images.githubusercontent.com/50685476/200209216-d4eb4396-8429-435e-8472-7b19cdc817bd.png">

<img width="283" alt="image" src="https://user-images.githubusercontent.com/50685476/200209126-2c814345-0eb7-403e-803e-2d6caf4c6a86.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/50685476/200209142-9a998a00-6a5a-4282-a651-274a56ab8204.png">
