### ISSUE TITLE
日历组件可以 设置成星期一 至 星期日的排序吗

### ISSUE THREAD

**Issue by tangguo13** [jdf2e/nutui#1764]
目前组件是
![image](https://user-images.githubusercontent.com/94333330/196865092-2a65858a-1351-44d3-9bf5-b28c9402e81f.png)
现在需要展示 星期一到星期日的顺序，请问支持吗

**Comment by lkjh3214** [comment]
目前没有该设置，后续迭代可以添加上

**Comment by thx125** [comment]
日历组件自定义周起始日设置已完成功能迭代，待v3.2.7版本发布
