### ISSUE TITLE
OverLay 遮罩层 锁定 背景 后 里面 还有一个 滚动条， 里面的滚动条无法滚动[question]

### ISSUE THREAD

**Issue by AuYuHui** [jdf2e/nutui#1765]
## 你想知道什么？

你好，我想知道这个项目是否可以...
锁定背景后 ， 里面的滚动条是否可以滚动
## 描述你考虑过的替代方案

我想...

## 其它

无

**Comment by szg2008** [comment]
有可复现的例子吗？我们好跟进～

**Comment by AuYuHui** [comment]
> 

https://codepen.io/q2419068625/pen/zYaOJQO
H5 滑动不了

**Comment by szg2008** [comment]
这种场景建议使用popup代替，H5可以正常滑动
