### ISSUE TITLE
[bug] picker 组件 3.2.4版本，在微信小程序，无法显示，只显示了titlebar栏目

### ISSUE THREAD

**Issue by 893949088** [jdf2e/nutui#1774]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：16.x
- **NutUI 版本**： 3.2.4
- **Vue 版本**：3.x
- **引用方式**：  NPM

**Comment by 893949088** [comment]
真是哪哪都是bug，无力吐槽

**Comment by yangxiaolu1993** [comment]
自 v3.2.3 起，@nutui/nutui-taro 中的 Picker 组件依赖 Taro 版本 V3.5.6，辛苦自查一下，Taro 的版本有没有升级

**Comment by whevether** [comment]
> 
是真的bug 3.2.3没有问题 3.2.4picker有问题

**Comment by yangxiaolu1993** [comment]
> 

可以提供一个小版本的demo吗？我没复现

**Comment by whevether** [comment]
> > 
> 
> 
> 
> 可以提供一个小版本的demo吗？我没复现

你用taro最新版外加这个升级到3.2.4复制官网demo就能复现了

**Comment by wei1034937343** [comment]
![image](https://user-images.githubusercontent.com/28970254/197756351-b8c90076-b74e-4567-a78c-bbf45b77ce8a.png)
同样的问题

**Comment by 893949088** [comment]
@yangxiaolu1993 我用的就是Taro 3.5.6 ，而且值得一提的是升级到3.5.7的时候压根跑不起来

**Comment by 893949088** [comment]
@yangxiaolu1993 而且picker多级选择模式有bug ，你好好测测，我现在我本地把源代码拷贝到了本地已经修正好了

**Comment by yangxiaolu1993** [comment]
> @yangxiaolu1993 而且picker多级选择模式有bug ，你好好测测，我现在我本地把源代码拷贝到了本地已经修正好了

多选模式有哪些儿 bug ，可以列出来吗？

**Comment by 893949088** [comment]
@yangxiaolu1993 全靠社区维护吗？😓，bug很明显，1. 不支持给默认值v-model，2. 选择的时候第一次滑动切换是无效的，第二次才行

**Comment by yangxiaolu1993** [comment]
Taro 3.5.6，NutUI-Taro 3.2.4 下，Picker 组件无法使用问题已修复，会发布一个 beta 版本

**Comment by 893949088** [comment]
主要是内部记得选中index有问题

**Comment by yangxiaolu1993** [comment]
> @yangxiaolu1993 全靠社区维护吗？😓，bug很明显，1. 不支持给默认值v-model，2. 选择的时候第一次滑动切换是无效的，第二次才行

NutUI 希望有更多的社区用户参与进来，提出意见、建议，我们也会不断地进行完善

**Comment by yangxiaolu1993** [comment]
> 

列出的问题已经修改，在 3.2.6 版本发布

**Comment by xuwu125** [comment]
._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:38 [Vue warn]: Failed to resolve component: picker-view-column
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <NutPicker modelValue= [1] onUpdate:modelValue=fn visible=false  ... > 
  at <UserInfo tid="pages/user/info/index?$taroTimestamp=1666972518507" > 
  at <Anonymous key="pages/user/info/index?$taroTimestamp=1666972518507" > 
  at <App>
warn @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:38
resolveAsset @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:2869
resolveComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:2818
_sfc_render @ ._node_modules_@nutui_nutui-taro_dist_packages__es_Picker.js:609
renderComponentRoot @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:902
componentUpdateFn @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5615
run @ ._node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:187
instance.update @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5729
setupRenderEffect @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5743
mountComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5525
processComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5483
patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5085
mountChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5269
mountElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5179
processElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5162
patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5082
mountChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5269
mountElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5179
processElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5162
patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5082
mountChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5269
mountElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5179
processElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5162
patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5082
componentUpdateFn @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5622
run @ ._node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:187
instance.update @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5729
setupRenderEffect @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5743
mountComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5525
processComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5483
patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5085
mountChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5269
mountElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5179
processElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5162
patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5082
mountChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5269
processFragment @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5442
patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5078
componentUpdateFn @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5622
run @ ._node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:187
instance.update @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5729
setupRenderEffect @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5743
mountComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5525
processComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5483
patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5085
patchKeyedChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5885
patchChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5792
processFragment @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5472
patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5078
componentUpdateFn @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5695
run @ ._node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:187
instance.update @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5729
callWithErrorHandling @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:155
flushJobs @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:388
Promise.then (async)
queueFlush @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:280
queueJob @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:274
i.f.i.f @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:3065
updateAppInstance @ .._src_utils.ts:39
mount @ .._src_utils.ts:29
mount @ taro.js?t=wechat&s=1666968435246&v=fb01af3b1734db4d4a0998cd4b9584a9:8097
(anonymous) @ taro.js?t=wechat&s=1666968435246&v=fb01af3b1734db4d4a0998cd4b9584a9:8115
(anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1
l.__callPageLifeTime__ @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1
wr @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1
l.emit @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1
emit @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1
l.emit @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1
emit @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1
emit @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1
c @ VM8 asdebug.js:10
u @ VM8 asdebug.js:10
(anonymous) @ VM8 asdebug.js:1
f @ VM8 asdebug.js:1
g @ VM8 asdebug.js:1
(anonymous) @ VM8 asdebug.js:1
_ws.onmessage @ VM8 asdebug.js:1
Show 57 more frames
._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:38 [Vue warn]: Failed to resolve component: picker-view
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <NutPicker modelValue= [1] onUpdate:modelValue=fn visible=false  ... > 
  at <UserInfo tid="pages/user/info/index?$taroTimestamp=1666972518507" > 
  at <Anonymous key="pages/user/info/index?$taroTimestamp=1666972518507" > 
  at <App>

**3.2.5 依然用不了**

**Comment by yangxiaolu1993** [comment]
> ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:38 [Vue warn]: Failed to resolve component: picker-view-column If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. at <NutPicker modelValue= [1] onUpdate:modelValue=fn visible=false ... > at at at warn @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:38 resolveAsset @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:2869 resolveComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:2818 _sfc_render @ ._node_modules_@nutui_nutui-taro_dist_packages__es_Picker.js:609 renderComponentRoot @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:902 componentUpdateFn @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5615 run @ ._node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:187 instance.update @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5729 setupRenderEffect @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5743 mountComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5525 processComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5483 patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5085 mountChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5269 mountElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5179 processElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5162 patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5082 mountChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5269 mountElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5179 processElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5162 patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5082 mountChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5269 mountElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5179 processElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5162 patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5082 componentUpdateFn @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5622 run @ ._node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:187 instance.update @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5729 setupRenderEffect @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5743 mountComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5525 processComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5483 patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5085 mountChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5269 mountElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5179 processElement @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5162 patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5082 mountChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5269 processFragment @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5442 patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5078 componentUpdateFn @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5622 run @ ._node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:187 instance.update @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5729 setupRenderEffect @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5743 mountComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5525 processComponent @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5483 patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5085 patchKeyedChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5885 patchChildren @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5792 processFragment @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5472 patch @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5078 componentUpdateFn @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5695 run @ ._node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:187 instance.update @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5729 callWithErrorHandling @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:155 flushJobs @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:388 Promise.then (async) queueFlush @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:280 queueJob @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:274 i.f.i.f @ ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:3065 updateAppInstance @ .._src_utils.ts:39 mount @ .._src_utils.ts:29 mount @ taro.js?t=wechat&s=1666968435246&v=fb01af3b1734db4d4a0998cd4b9584a9:8097 (anonymous) @ taro.js?t=wechat&s=1666968435246&v=fb01af3b1734db4d4a0998cd4b9584a9:8115 (anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1 l.**callPageLifeTime** @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1 wr @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WASubContext.js?t=wechat&s=1666968435246&v=2.26.2:1 l.emit @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1 emit @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1 l.emit @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1 emit @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1 (anonymous) @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1 emit @ WAServiceMainContext.js?t=wechat&s=1666968435246&v=2.26.2:1 c @ VM8 asdebug.js:10 u @ VM8 asdebug.js:10 (anonymous) @ VM8 asdebug.js:1 f @ VM8 asdebug.js:1 g @ VM8 asdebug.js:1 (anonymous) @ VM8 asdebug.js:1 _ws.onmessage @ VM8 asdebug.js:1 Show 57 more frames ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:38 [Vue warn]: Failed to resolve component: picker-view If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. at <NutPicker modelValue= [1] onUpdate:modelValue=fn visible=false ... > at at at
> 
> **3.2.5 依然用不了**

可以先尝试一下 [3.2.6-beta.1](https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.6-beta.1)

**Comment by yarning233** [comment]
[3.2.6-beta.1](https://www.npmjs.com/package/@nutui/nutui-taro/v/3.2.6-beta.1) 这个版本可以了

**Comment by yarning233** [comment]
刚试过

**Comment by loey-shxy** [comment]
这问题解决了吗 ，唉
