### ISSUE TITLE
[bug]input组件的slot=input插槽报错，卡住页面

### ISSUE THREAD

**Issue by Erica-lyj** [jdf2e/nutui#1776]
## 问题描述
使用input组件的input插槽，报错，导致其他数据展示不出来。注释掉这部分代码其他数据可以正常展示。
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/57788867/197464508-00ab82ab-2f4c-4ecf-b1d4-97aa4ea73207.png">
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/57788867/197465512-09a0794a-7d3f-4338-bb0a-a70c03fdd08e.png">

## 预期的行为和实际行为
预期的行为：正常展示数据，不影响其他数据，不报错。

## 相关环境信息
- **操作系统**：mac 
- **Node 版本**：12.22.0
- **NutUI 版本**： ^3.2.3
- **Vue 版本**：3
- **引用方式**： NPM

**Comment by Drjingfubo** [comment]
nutui还是nutui-taro

**Comment by Erica-lyj** [comment]
> 

nutui

**Comment by Drjingfubo** [comment]
3.2.6已发布
