### ISSUE TITLE
[bug]在webstorm使用代码提示时候,tabs组件代码提示错误

### ISSUE THREAD

**Issue by Lyc0430** [jdf2e/nutui#1777]
## 问题描述

在webstorem使用tabs组件,增加一个auto-height,代码提示会显示auto-height`v3.1.21`。[如图](https://cloudlanweb.oss-cn-hangzhou.aliyuncs.com/err1.png?versionId=CAEQPBiBgMCwsOukoBgiIDdjNDdjZGRmMDkzODRmNjQ5MjgzMDk1YTI2MDMxNGE4)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
预期:显示提示auto-height

实际:显示auto-height`v3.1.21`,这是一个错误的api提示

## 复现步骤，具体代码
1.在nut-tabs background="white“ v-model="state.tab11value"中希望增加auto-height.
2.使用代码提示
3.代码提示显示auto-height`v3.1.21`

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：16.15.1
- **NutUI 版本**： 3.2.4
- **Vue 版本**：3.2.13
- **引用方式**： npm

**Comment by szg2008** [comment]
已修复，下周发布新版本支持～

**Comment by Drjingfubo** [comment]
使用v3.2.5
