### ISSUE TITLE
[bug]Tabbar组件默认unactive-color值错误

### ISSUE THREAD

**Issue by Lyc0430** [jdf2e/nutui#1779]
## 问题描述

在使用示例创建基础tabbar时,默认显示错误
[如图1](https://cloudlanweb.oss-cn-hangzhou.aliyuncs.com/issue/err.png?versionId=CAEQPBiBgIDGxZGyoBgiIDk1MGI5NjllMDViNDQyYTQ5YTUzMTBjNDkyNGVmMTY0)
[如图2](https://cloudlanweb.oss-cn-hangzhou.aliyuncs.com/issue/err-detail.png?versionId=CAEQPBiBgMCcyJGyoBgiIDcwZDRkZTRmN2MzZTRjYjA5NjQxMjZlZjNiMDhmMDk5)
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

https://github.com/Lyc0430/nut-tabbar-issue
## 预期的行为和实际行为
预期行为:非激活时icon显示黑色

实际行为:在未更改情况下,非激活时颜色和激活时颜色一致(红色)。目前可以通过unactive-color属性自行将其修改为正常黑色

## 复现步骤，具体代码
1.创建项目,引入全局nutui
2.根据示例创建tabbar
3.tabbar默认颜色为全红色,未区分激活和未激活状态颜色

ps.这个版本bug有点离谱啊...
## 相关环境信息
- **操作系统**：mac
- **Node 版本**：16.15.1
- **NutUI 版本**： 3.2.4
- **Vue 版本**：3.2.13
- **引用方式**： npm

**Comment by Drjingfubo** [comment]
抱歉哈 3.2.4这个版本因为增加了一个主题变量，新增了个样式，导致这里未选中颜色有问题，相关同学已经在跟进问题了

**Comment by Drjingfubo** [comment]
使用3.2.5
