### ISSUE TITLE
Steps组件动态加载数据循环Step报错：'filter' of undefined

### ISSUE THREAD

**Issue by lively-qcy** [jdf2e/nutui#178]
## What happens?
Steps组件动态加载数据报错：`TypeError: Cannot read property 'filter' of undefined`，复制官网静态数据示例不会

1、axios异步请求数据
2、赋值数组进行循环`step`展示

显示也错误了，如图：

![image](https://user-images.githubusercontent.com/39941460/69518926-c2bd0c80-0f93-11ea-9f8d-86adab2c383f.png)

![image](https://user-images.githubusercontent.com/39941460/69520055-8a6afd80-0f96-11ea-9d54-2482877fa50b.png)

## 预期的行为和实际行为
我按需引入的，是不是用法问题？还请协助。

## 复现步骤，具体代码
```
<nut-steps :current="logistics.length">
            <nut-step v-for="logistic in logistics"
                      :key="logistic.id"
                      :title="logistic.orderStatus"
                      :content="logistic.creationTime">
            </nut-step>
</nut-steps>

`created`中请求的数据
getLogistics(orderId).then(res=>{
      this.logistics = res.data;  //data是数组数据  logistics默认是[ ]
})
```

## 相关环境信息
- **操作系统**：
- **Node 版本**：11.2.0
- **NutUI 版本**：2.1.7

**Comment by richard1015** [comment]
@lively-qcy   当前版本 暂不支持通过 v-for 渲染nut-step，下个版本将修复此bug，请持续关注!

**Comment by lively-qcy** [comment]
> @lively-qcy 当前版本 暂不支持通过 v-for 渲染nut-step，下个版本将修复此bug，请持续关注!

大熊弟，你们的微信群二维码失效了，能不能搞个新的，反馈问题也好及时一些。

**Comment by richard1015** [comment]
> > @lively-qcy 当前版本 暂不支持通过 v-for 渲染nut-step，下个版本将修复此bug，请持续关注!
> 
> 大熊弟，你们的微信群二维码失效了，能不能搞个新的，反馈问题也好及时一些。

<img width="358" src="https://img14.360buyimg.com/imagetools/jfs/t1/93168/7/3178/64402/5ddcebd0E0bf52dc9/22c70abd92e85ac0.jpg">

**Comment by richard1015** [comment]
v2.1.8已修复
