### ISSUE TITLE
fixednav[question]

### ISSUE THREAD

**Issue by houqingbin** [jdf2e/nutui#1781]
按照文档全部组件引用,在使用fixednav时,
<img width="404" alt="image" src="https://user-images.githubusercontent.com/75670670/197699813-67326c39-7652-4785-9a9a-8da7ca462a34.png">
<img width="429" alt="image" src="https://user-images.githubusercontent.com/75670670/197699856-522f0009-5662-4c4c-856f-277335f78abe.png">
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/75670670/197700069-ed8dfd84-107a-4e52-bd8f-dbc542ce98e6.png">
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/75670670/197700251-a9e8ad11-dae1-49af-a80d-1b7e58805ca1.png">

**Comment by houqingbin** [comment]
这是最小复现demo地址
https://github.com/houqingbin/demo.git
在mac版Chrome浏览器,ios  safari浏览器和嵌入Android的H5使用fixednav组件都不可以

**Comment by houqingbin** [comment]
这个有人回答一下吗

**Comment by richard1015** [comment]
跟进中

**Comment by richard1015** [comment]
升级这两个依赖包，即可
```
    "vue": "^2.6.14",
    "vue-template-compiler": "^2.6.14"
```

**Comment by houqingbin** [comment]
升级到什么版本
