### ISSUE TITLE
[bug]NumberKeyboard中按钮样式展示问题

### ISSUE THREAD

**Issue by Tiamo-hg** [jdf2e/nutui#1782]
![b64ddb9b451478890e003b6eae41c850](https://user-images.githubusercontent.com/64953115/197734942-a197e165-570c-450e-a44d-3992315ad232.jpg)

**Comment by Drjingfubo** [comment]
感谢反馈，vite的css打包配置问题

**Comment by Drjingfubo** [comment]
官网展示的问题哈，组件使用没有影响，感谢反馈

**Comment by Drjingfubo** [comment]
下周发版修复官网
