### ISSUE TITLE
[bug]nutui中的menu菜单组件，敏感度怎么调整

### ISSUE THREAD

**Issue by xiongdou-20250617** [jdf2e/nutui#1784]
## 问题描述
用户群体：老年人
在用户使用菜单组件时反馈选择滚动下面选项时，选项切换太快，导致想选的内容经常一下就跳过去

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
可通过调整敏感度的值，延长选项切换时长

## 相关环境信息
- **操作系统**：微信小程序
- **Node 版本**：v14.17.0
- **NutUI 版本**：3.4.10
- **Vue 版本**：^3.0.0
- **引用方式**：  NPM ？

**Comment by yangjinjun3** [comment]
您好，您的意思是，选择完，下拉菜单收起的速度太快吗？ 
可否帮忙录个屏

**Comment by xiongdou-20250617** [comment]
客户的反馈，主要苹果手机我这边也没有重现出这个问题。不是收的太快，是滚动选项时选项切换的太快了。我们的客户群体主要是老年人，所以我个人觉得还好，但用户就觉得有点太快了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月31日(星期一) 下午4:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdf2e/nutui] [bug]nutui中的menu菜单组件，敏感度怎么调整 (Issue #1784)





 
您好，您的意思是，选择完，下拉菜单收起的速度太快吗？
 可否帮忙录个屏

**Comment by yangjinjun3** [comment]
意思是当下拉菜单中有很多选项时（出现了滚动条），里面的选项切换的太快？
我理解是不是滑动就没事儿，一下子滚到底肯定很快

**Comment by xiongdou-20250617** [comment]
是的，选项太多时，用户操作就会觉得本来自己要选择的选项，轻轻一划就滚上去了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月31日(星期一) 下午5:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdf2e/nutui] [bug]nutui中的menu菜单组件，敏感度怎么调整 (Issue #1784)





 
意思是当下拉菜单中有很多选项时（出现了滚动条），里面的选项切换的太快？
 我理解是不是滑动就没事儿，一下子滚到底肯定很快

**Comment by yangjinjun3** [comment]
我理解这是苹果的体验设计   不知道用户是否方便录个屏

**Comment by yangjinjun3** [comment]
或者您那边可以把下拉弹框的高度增加下呢

**Comment by xiongdou-20250617** [comment]
我这边也是同事去现场，客户给演示的，然后回来口述给我的，我自己用的安卓手机也没办法重现这个问题。现在我改用微信小程序原生的picker解决了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月31日(星期一) 下午5:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdf2e/nutui] [bug]nutui中的menu菜单组件，敏感度怎么调整 (Issue #1784)





 
我理解这是苹果的体验设计   不知道用户是否方便录个屏

**Comment by yangjinjun3** [comment]
哦，那我先把这个问题关了，这边没办法复现，等其他人再复现了再看下怎么优化？

**Comment by xiongdou-20250617** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月31日(星期一) 下午5:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdf2e/nutui] [bug]nutui中的menu菜单组件，敏感度怎么调整 (Issue #1784)





 
哦，那我先把这个问题关了，这边没办法复现，等其他人再复现了再看下怎么优化？

**Comment by yangjinjun3** [comment]
感谢！
