### ISSUE TITLE
[bug]使用自定义主题之后，所有primary按钮都变成了渐变色

### ISSUE THREAD

**Issue by cnLiuMing** [jdf2e/nutui#1785]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：window11
- **Node 版本**：18
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：3.2
- **引用方式**：  CDN / NPM ？npm

**Comment by richard1015** [comment]
可以设置 颜色一致  就不会渐变
$primary-color: #fa2c19 !default;
$primary-color-end: #fa2c19 !default;
