### ISSUE TITLE
如何根据nutui-cli快速搭建第三方组件库？

### ISSUE THREAD

**Issue by JiaLe1** [jdf2e/nutui#1787]
## 你想知道什么？

你好，我想知道这个项目是否可以...

## 描述你考虑过的替代方案

我想...

## 其它

无

**Comment by richard1015** [comment]
目前 nutui-cli 只支持 vue2 版本的构建，底层为webpack4
最新 3.x vue3是基于 vite构建，目前nutui-cli 内部暂未升级

构建自己的一套组件库，可以参考 next 分支的 vite 配置
详细的设计图见 https://github.com/jdf2e/nutui/discussions/1273
