### ISSUE TITLE
【bug】微信小程序中在nut-form里使用textarea，聚焦后输入一个字符会马上自动失焦

### ISSUE THREAD

**Issue by hong-q** [jdf2e/nutui#1791]
1、textarea绑定blur事件，在微信小程序里点击输入框聚焦后就会马上触发失焦事件（根本无法键盘输入）
2、不绑定blur事件，键盘输入值后就会自动失焦，再聚焦输入单个字符就又自动失焦，循环往复
注：在form表单容器中会如此，单独使用没事

**Comment by richard1015** [comment]
辛苦提供一下 详细复现方式 , 按照此模板
https://github.com/jdf2e/nutui/issues/new/choose

**Comment by AnonymousArthur** [comment]
Same problem here.  Input box works on pages without Form or FormItem.
```
"@nutui/nutui-taro": "^3.3.2",
"@tarojs/cli": "3.5.11",
```

**Comment by AnonymousArthur** [comment]
@hong-q 老哥解决了吗？我们的项目也有这个问题。

**Comment by lpzzv** [comment]
目前最新的4.2.6 又出现了这个问题。

**Comment by eiinu** [comment]
> 目前最新的4.2.6 又出现了这个问题。

「又出现」是指 4.26 之前的版本正常、4.2.6 不正常吗？

**Comment by lpzzv** [comment]
> > 目前最新的4.2.6 又出现了这个问题。
> 
> 是指 4.2.6 之前的版本正常、4.2.6 不正常吗？

4.2.5也不正常，再往前的版本没试。

**Comment by 490626721** [comment]
"@nutui/nutui-taro": "^4.3.13",
 "@tarojs/taro": "4.0.9",
这个问题又复现了，在H5端会在输入一个字符后自动失去焦点
