### ISSUE TITLE
[suggest] 关于 ActionSheet 动作面板组件，文档介绍不完全问题

### ISSUE THREAD

**Issue by HuziG** [jdf2e/nutui#1792]
在该组件介绍文档中，关于 <安装> 部分的描述实际上是不完全的

原文：
import { createApp } from 'vue';
// vue
import { ActionSheet, Popup } from '@nutui/nutui';
// taro
import { ActionSheet, Popup } from '@nutui/nutui-taro';

const app = createApp();
app.use(ActionSheet);
app.use(Popup);

其实应改成：
import { createApp } from 'vue';
// vue
import { ActionSheet, Popup, OverLay } from '@nutui/nutui';
// taro
import { ActionSheet, Popup, OverLay } from '@nutui/nutui-taro';

const app = createApp();
app.use(ActionSheet);
app.use(Popup);
app.use(OverLay);

否则，黑色遮罩会显示不出来，误以为组件出了 bug

**Comment by HuziG** [comment]
🔗 文档链接指向：https://nutui.jd.com/#/zh-CN/component/actionsheet

**Comment by Drjingfubo** [comment]
感谢，您也可以直接提个pr过来，帮忙修复一下文档，大家一起共建
