### ISSUE TITLE
tab组件缺乏对设备横竖屏的响应

### ISSUE THREAD

**Issue by rivenEdge** [jdf2e/nutui#180]
tab在设备横竖屏切换时navBar宽度没有响应的变化

**Comment by guoxiao158** [comment]
暂时先建议开发者监听设备屏幕切换事件。进行dom局部刷新一下

**Comment by guoxiao158** [comment]
暂时建议开发者监听设备屏幕切换事件，进行局部dom刷新，后期我们会进行修改
