### ISSUE TITLE
vite还是不能组件按需引入吗？手动引入后打包有2M多

### ISSUE THREAD

**Issue by ArtArrow** [jdf2e/nutui#1804]
### What problem does this feature solve?（这个功能解决的问题）
手动引入和打包资源过大的问题

### What does the proposed API look like?（期望的 API）
希望能改下组件引入的形式

**Comment by yanbowe** [comment]
强烈建议使用[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) @richard1015

**Comment by ArtArrow** [comment]
> 强烈建议使用[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) @richard1015

用的就是这个，但是还没有resolvers，自定义的resolvers会导致组件异常

**Comment by eiinu** [comment]
> > 强烈建议使用[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) @richard1015
> 
> 用的就是这个，但是还没有resolvers，自定义的resolvers会导致组件异常

样式文件缺少依赖关系，如果 A 组件内部使用了 B 组件，使用 unplugin 插件自动导入的只有 A 的样式

**Comment by yanbowe** [comment]
> > > 强烈建议使用[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) @richard1015
> > 
> > 
> > 用的就是这个，但是还没有resolvers，自定义的resolvers会导致组件异常
> 
> 样式文件缺少依赖关系，如果 A 组件内部使用了 B 组件，使用 unplugin 插件自动导入的只有 A 的样式

主要是需要组件可以自动引入注册有TS提示，样式的话可以手动全部导入，因为我觉得[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)导入样式有问题，例如[vant](https://github.com/antfu/unplugin-vue-components/issues/327)样式导入

**Comment by richard1015** [comment]
eiinu 大佬已经在解决依赖性，样式丢失问题，大家敬请期待

**Comment by Kareshii** [comment]
Pin一个[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 引入

**Comment by eiinu** [comment]
4.0 版本已支持 unplugin-vue-components 插件
