### ISSUE TITLE
Notify，设置了 duration 的值，但一直不会消失

### ISSUE THREAD

**Issue by richard1015** [jdf2e/nutui#1806]
### What problem does this feature solve?（这个功能解决的问题）
Notif 设置了 duration 生效

### What does the proposed API look like?（期望的 API）
跟官网的效果不一样。比如Notify，设置了duration的值，但一直不会消失

![image](https://user-images.githubusercontent.com/13060263/199141556-6c457469-483d-49c6-a32d-39cf22eee2de.png)

**Comment by Drjingfubo** [comment]
3.2.6已发布
