### ISSUE TITLE
NoticeBar修改height之后，垂直轮播会卡顿

### ISSUE THREAD

**Issue by txl1123** [jdf2e/nutui#1809]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.2.0

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
14.17.3

### Browser and its version（浏览器及其版本）
微信开发工具

### System and its version（系统及其版本）
MacOs(11.4)

### Taro environmental information（taro 环境信息）
Taro CLI 3.4.9 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
    npmPackages:
      @tarojs/components: 3.4.9 => 3.4.9 
      @tarojs/mini-runner: 3.4.9 => 3.4.9 
      @tarojs/plugin-html: ^3.4.11 => 3.4.11 
      @tarojs/runtime: 3.4.9 => 3.4.9 
      @tarojs/taro: 3.4.9 => 3.4.9 
      @tarojs/webpack-runner: 3.4.9 => 3.4.9 
      babel-preset-taro: 3.4.9 => 3.4.9 
      eslint-config-taro: 3.4.9 => 3.4.9 

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/nutui3-vite-demo-forked-wyz8zz?file=/src/App.vue)

### Steps to reproduce（重现步骤）
小程序项目，
不改高度很丝滑，一改高度就会出现卡顿

### What is expected?（期望的结果是什么？）
可以修改高度和速度，也不会一卡一卡

### What is actually happening?（实际的结果是什么？）
修改高度和速度后会一卡一卡

**Comment by yangxiaolu1993** [comment]
感谢对 NutUI 的支持，问题已经修改，将在 v3.2.6 发布

**Comment by Drjingfubo** [comment]
3.2.6已发布
