### ISSUE TITLE
Toast、Dialog组件多实例时，回调函数onClose会同时触发。

### ISSUE THREAD

**Issue by Ymm0008** [jdf2e/nutui#181]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
Toast、Dialog组件多实例时，回调函数onClose会同时触发。

## 相关环境信息
- **操作系统windows：
- **Node 版本**：
- **NutUI 版本2.1.5：

**Comment by richard1015** [comment]
已记录、修复后会第一时间通知
