### ISSUE TITLE
icon动画无效，例如<nut-icon name="loading" class="nut-icon-am-infinite"/>

### ISSUE THREAD

**Issue by clovu** [jdf2e/nutui#1811]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.2.5

### Vue version（vue 版本）
3.2.41

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
v16.15.1

### Browser and its version（浏览器及其版本）
Chrome(107.0.5304.87)

### System and its version（系统及其版本）
Windows 11 21H2

### Taro environmental information（taro 环境信息）
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\admin\AppData\Roaming\npm\yarn.CMD
      npm: 8.11.0 - D:\nodejs\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/Clover-You/yf-wechat-mini-app--reappear)

### Steps to reproduce（重现步骤）
启动即可，就是 Popup 组件中的 icon无法动画

### What is expected?（期望的结果是什么？）
能够正常进行“加载”动画

### What is actually happening?（实际的结果是什么？）
无法动画

### Remarks（补充说明）
使用NutUI模板创建的项目

**Comment by clovu** [comment]
你们Issue Helper是不是有BUG...
issue的值怎么取的是“实际结果”的值...
![1667352820(1)](https://user-images.githubusercontent.com/50982977/199374024-e58b8873-8bca-4e8a-8444-4418513a479b.jpg)

**Comment by clovu** [comment]
好像是 `@keyframes rotation` 丢失。不知道是不是要我手动加上，我在文档里没找到相关资料

**Comment by clovu** [comment]
没有引入 `@nutui/nutui-taro/dist/style.css`

**Comment by Ymm0008** [comment]
> 你们Issue Helper是不是有BUG... issue的值怎么取的是“实际结果”的值... ![1667352820(1)](https://user-images.githubusercontent.com/50982977/199374024-e58b8873-8bca-4e8a-8444-4418513a479b.jpg)

感谢反馈，这个问题已经修复发版了。@Clover-You
