### ISSUE TITLE
nut-lits和nut-infiniteloading 在微信小程序出现 Failed to resolve component: scroll-view

### ISSUE THREAD

**Issue by Q3B0** [jdf2e/nutui#1815]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.2.5

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
8.19.2

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.121)

### System and its version（系统及其版本）
Windows 10 22H2

### Taro environmental information（taro 环境信息）
 Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.2
      Yarn: 1.22.17 
      npm: 8.19.2 

### Reproduction link（重现链接）
[codepen.io/q3b0/pen/vYrGRBE](https://codepen.io/q3b0/pen/vYrGRBE)

### Steps to reproduce（重现步骤）
无

### What is expected?（期望的结果是什么？）
可以正常使用

### What is actually happening?（实际的结果是什么？）
无

**Comment by szg2008** [comment]
今天发版之后就可以了，感谢反馈

**Comment by Drjingfubo** [comment]
list组件3.2.6试下   infiniteloading直接使用 Taro 现有 ScrollView 组件开发
![image](https://user-images.githubusercontent.com/50685476/200207837-2348ab4b-0554-4775-b2f4-d86c23236a3d.png)
