### ISSUE TITLE
InfiniteLoading 某些情况下会错误触发下拉刷新

### ISSUE THREAD

**Issue by ieu** [jdf2e/nutui#1819]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.2.5

### Vue version（vue 版本）
3.2.41

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
MacOS(12.6)

### Reproduction link（重现链接）
[nutui.jd.com/demo.html](https://nutui.jd.com/demo.html#/infiniteloading)

### Steps to reproduce（重现步骤）
在官方的“下拉刷新”示例中
1. 在上半部分（如 2 或 3 附近）触摸、左滑或右滑
2. 在下半部分（如 6 或 7 附近）上滑、左滑或右滑

### What is expected?（期望的结果是什么？）
列表应向下滚动

### What is actually happening?（实际的结果是什么？）
触发了下拉刷新效果导致列表重置

**Comment by yangxiaolu1993** [comment]
感谢对NutUI的支持，问题已经修复，会在下个版本： 3.2.7 版本 发布
