### ISSUE TITLE
menu组件如果2个同时存在的话，一个点击出现后，另一个点击弹出后（第一个仍然存在，没有消失）

### ISSUE THREAD

**Issue by Ymm0008** [jdf2e/nutui#182]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：windows
- **Node 版本**：12.13.0
- **NutUI 版本**：2.1.5

**Comment by richard1015** [comment]
已记录、修复后会第一时间通知

**Comment by richard1015** [comment]
@Ymm0008
