### ISSUE TITLE
Elevator 索引的change事件希望可以对外暴露出来

### ISSUE THREAD

**Issue by Lee66** [jdf2e/nutui#1826]
### What problem does this feature solve?（这个功能解决的问题）
索引自定义的时候，点击索引可以通过scrollto让列表滚动到指定的位置，当滚动列表的时候没有办法控制自定义索引高亮

### What does the proposed API look like?（期望的 API）
当前高亮的索引字符变化时触发可以获取到index，就像vant的IndexBar一样

**Comment by szg2008** [comment]
已支持，下周发版可用，感谢反馈～
