### ISSUE TITLE
定制主题不生效

### ISSUE THREAD

**Issue by moxunbai** [jdf2e/nutui#183]
你好，我是使用vue-cli搭建的工程，根据文档对应到vue.config.js配置文件中，如下配置
 css: {
    loaderOptions: {
      sass: {
        prependData: `@import "./src/assets/scss/custom_theme.scss"; @import "@nutui/nutui/dist/styles/index.scss"; `,
      }
    },
其中我自定义的custom_theme.scss的测试内容为:
$btn-gradient-start-color: green;
$btn-gradient-end-color: green;
预期的效果是按钮背景色变绿；
实际效果却还是原来红色的。
请问这是什么原因？
 
## 相关环境信息
- **操作系统**：win10
- **Node 版本**：v8.12.0
- **NutUI 版本**："^2.1.7"
@vue/cli 4.0.5

**Comment by richard1015** [comment]
@moxunbai   是否可以提供一下最小可复现仓库到github，方便这边排查 :)

**Comment by moxunbai** [comment]
@richard1015  好的， 看看这个如何 ；https://github.com/moxunbai/testNutui.git

**Comment by richard1015** [comment]
> @richard1015 好的， 看看这个如何 ；https://github.com/moxunbai/testNutui.git

vuecli3   NutUI定制化主题 请参考 https://github.com/richard1015/nutui-demo，此demo已实现

**Comment by moxunbai** [comment]
ok,试了可以，比较了下，原来是我scss里定制的变量不对哦， 感谢解惑！

**Comment by richard1015** [comment]
@moxunbai  可以加一下我们的微信交流群，方便及时回复 
> 微信交流群
<img width="358" src="https://img14.360buyimg.com/imagetools/jfs/t1/99938/27/5896/64075/5df0772eE89888d9d/4ba34697506e331c.jpg">
