### ISSUE TITLE
Category多端组件，在Cell或表单中结合Popup使用的场景，期望支持选中类目的回显，支持类目的搜索

### ISSUE THREAD

**Issue by grainXianSen** [jdf2e/nutui#1838]
### What problem does this feature solve?（这个功能解决的问题）
1、可以在表单等更多场景中使用
2、在类目较多的时候，搜索功能可通过关键字让用户快速找到想要选择的类目

### What does the proposed API look like?（期望的 API）
1、回显功能最好使用v-model来实现
2、搜索功能api设计：1）是否展示搜索框；2）自定义搜索的方法，可以参考（http://find.jdfmgt.com/assembly/select.html#%E5%8F%AF%E6%90%9C%E7%B4%A2）
以上只是个人的简单想法，期待大佬们更全面的设计

**Comment by Drjingfubo** [comment]
选中类目的回显？ 这个我理解都是单选的情况吧，onChange事件已经暴露了选中的item，自己做显示即可
类目搜索的话，你发的这个组件是pc端的，移动端Nutui暂时不会加这种搜索

**Comment by grainXianSen** [comment]
回显是指，类目组件的回显

**Comment by grainXianSen** [comment]
类目搜索确实会有这样的场景
