### ISSUE TITLE
[bug]在ios展示时，变白屏，但是能点击里面的内容

### ISSUE THREAD

**Issue by Imageheart** [jdf2e/nutui#184]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by Imageheart** [comment]
ios版本9.2.1

**Comment by richard1015** [comment]
@Imageheart    可以提供一下复现代码，方便这边排查

**Comment by Imageheart** [comment]
稍等

**Comment by Imageheart** [comment]
人都晕了，写了个demo，就可以跑。。自己项目上，就也没报错，就是变成白屏，可以点击内容，在安卓端，pc端都是正常的。。

**Comment by richard1015** [comment]
可以通过 [vconsole](https://www.npmjs.com/package/vconsole) 在ios端运行排查一下
或者 使用[spy-debugger](https://www.npmjs.com/package/spy-debugger)

**Comment by Imageheart** [comment]
用了vconsole.,没有报错。。。还有解决的思路吗。

**Comment by Imageheart** [comment]
ios高版本低版本都是这个情况，无论是打包后塞进app里，还是直接访问node服务器的，都是那个使用了nut的页面（使用了tab，tabpanel，scroller，都是按需加载），变成白屏，其他页面都是正常的

**Comment by richard1015** [comment]
> ios高版本低版本都是这个情况，无论是打包后塞进app里，还是直接访问node服务器的，都是那个使用了nut的页面（使用了tab，tabpanel，scroller，都是按需加载），变成白屏，其他页面都是正常的

可以加一下我们的微信交流群，方便及时回复 
<img width="358" src="https://img14.360buyimg.com/imagetools/jfs/t1/99938/27/5896/64075/5df0772eE89888d9d/4ba34697506e331c.jpg">
