### ISSUE TITLE
Menu 组件 toggle 方法能否支持隐藏的情况下，不移除 popup 里的自定义内容

### ISSUE THREAD

**Issue by az031120103** [jdf2e/nutui#1842]
### What problem does this feature solve?（这个功能解决的问题）
Menu 自定义菜单内容，如果是一个独立组件，并且内容是通过接口获取的，那么每次隐藏/显示菜单弹框内容都会重新请求 重新渲染。
造成不必要的网络带宽开销

### What does the proposed API look like?（期望的 API）
Menu 组件的 toggle 方法，隐藏 popup 时保留其自定义内容

**Comment by Drjingfubo** [comment]
试下3.3.0
