### ISSUE TITLE
elevator组件elevator__item__${i}渲染出现小数

### ISSUE THREAD

**Issue by yuanxin42** [jdf2e/nutui#1844]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）微信小程序

### Reproduction link（重现链接）
[nutui.jd.com](https://nutui.jd.com/nutui-issue-helper/?repo=jdf2e/nutui&lang=zh-cn)

### Steps to reproduce（重现步骤）
渲染数据，然后点击右侧的小标，会偶现定位不准确的情况

### What is expected?（期望的结果是什么？）
点击哪个，定位到哪个

### What is actually happening?（实际的结果是什么？）
定位不准确

问题会出现定位不准确的情况，复现视频如下

https://user-images.githubusercontent.com/20502412/201879338-626ccfac-b1d5-4111-9329-fdc3900ee51b.mp4

原因：渲染的时候，偶尔会出现高度为小数的情况（打印的 state.listHeight）
<img width="371" alt="image" src="https://user-images.githubusercontent.com/20502412/201879521-a66655e6-69f0-479c-824d-b0ca7d52c9e1.png">

### Remarks（补充说明）
希望在初始化高度的时候，可以加上Math.floor，处理一下小数的情况 
height += Math.floor(res[i][0].height);

#### 对应函数如下：
const calculateHeight = () => {
      state.listHeight = [];
      let height = 0;
      state.listHeight.push(height);
      for (let i = 0; i < state.listGroup.length; i++) {
        state.query.selectAll(`.elevator__item__${i}`).boundingClientRect();
        state.query.exec((res) => {
          height += Math.floor(res[i][0].height);
          console.log(height, '看看初始化的时候每个高度是多少--');
          state.listHeight.push(height);
        });
      }
    };

**Comment by szg2008** [comment]
感谢反馈和更正，下个版本修复🙏
