### ISSUE TITLE
uploader组件，自定义上传事件后，如何激发sucess事件？ （nutui-taro)

### ISSUE THREAD

**Issue by honghuamin** [jdf2e/nutui#1845]
### What problem does this feature solve?（这个功能解决的问题）
根据文档，自定义上传是这样操作的
```
const beforeXhrUpload = (xhr: XMLHttpRequest, options: any) => {
                if (options.formData.realFormData != undefined) {
                    xhr.send(options.formData.realFormData);
                } else {
                    xhr.send(options.formData);
                    console.log(xhr);
                }           
        };
```
这样完成上传后，success事件会被调用。
但是我如果不使用xhr.send方法，而是自己调用其他接口上传文件，比如这样
```
const beforeXhrUpload = (xhr: XMLHttpRequest, options: any) => {
调用接口上传数据
}
```
这样操作后，success事件不会被激发调用。
因为要等提交成功后执行返回父页面的操作，没有success事件，就只能不等待直接返回了，体验不好，我还是希望能在success事件里面执行上传成功的后续操作的，请问该如何设置上传成功或者调用事件？

### What does the proposed API look like?（期望的 API）
提供一个自定义上传事件后，设置上传状态的接口，这样success事件就能被正常调用，完成完整的上传功能。

**Comment by richard1015** [comment]
只需执行  参考源码执行 onSuccess 即可

https://github.com/jdf2e/nutui/blob/next/src/packages/__VUE/uploader/uploader.ts#L69

taro 模式
```
  const uploadTask = uploadFile({
          url: options.url,
          filePath: options.taroFilePath,
          fileType: options.fileType,
          header: {
            'Content-Type': 'multipart/form-data',
            ...options.headers
          }, //
          formData: options.formData,
          name: options.name,
          success(response: { errMsg: any; statusCode: number; data: string }) {
            if (options.xhrState == response.statusCode) {
              options.onSuccess?.(response, options);
            } else {
              options.onFailure?.(response, options);
            }
          },
          fail(e: any) {
            options.onFailure?.(e, options);
          }
        });
        options.onStart?.(options);
        uploadTask.progress((res: { progress: any; totalBytesSent: any; totalBytesExpectedToSend: any }) => {
          options.onProgress?.(res, options);
          // console.log('上传进度', res.progress);
          // console.log('已经上传的数据长度', res.totalBytesSent);
          // console.log('预期需要上传的数据总长度', res.totalBytesExpectedToSend);
        });
```

> h5模式
```
   if (xhr.readyState === 4) {
          if (xhr.status == options.xhrState) {
            options.onSuccess?.(xhr.responseText, options);
          } else {
            options.onFailure?.(xhr.responseText, options);
          }
        }
```

**Comment by honghuamin** [comment]
我是安装 @nutui/nutui-taro ,但是是H5应用，所以参考的是vue示例写法。
```
<nut-uploader
            :url="uploadUrl"
            :auto-upload="false"
            ref="uploadRef"
            v-model:file-list="files"
            :before-xhr-upload="beforeXhrUpload"
            :headers="headers"
            capture="true"
            :source-type="['camera']"
            @success="uploadSuccess"
        ></nut-uploader>
```

```
        const uploadSuccess = (responseText: any,option: any,fileItem: any) => {
            alertService.alert("提交成功", "success");
            goback();//执行调整
        };
```
执行时，发现uploadSuccess并不会被调用。

**Comment by richard1015** [comment]
你在你的钩子函数里 保证调用 onSuccess 就会触发 ，断点看一下

```

              options.onSuccess?.(xxxxx, options);
   
```

**Comment by honghuamin** [comment]
@richard1015 谢谢你的答复，但是问题没解决。
是这样，我看了你提供的源码，里面是
```
success(response: { errMsg: any; statusCode: number; data: string }) {
            if (options.xhrState == response.statusCode) {
              options.onSuccess?.(response, options);
            } else {
              options.onFailure?.(response, options);
            }
          },
```
但是，我在beforeXhrUpload事件里面，没有调用xhr.send，所以可能 options.xhrState就是未完成的状态。
之前在beforeXhrUpload事件中，调用xhr.send(options.formData)，success事件是会被调用的，但是我不使用xhr.send了，事件就没有被调用。
还有，虽然能找到源码，在node_modules里面也能看到，但是我不知道怎么调试，直接修改 nutui.es.js好像没有用（不好意思，我不是专业前端）

另外说一下，之所以另外写了上传的方法，绕开组件自带的方法，是遇上2个问题：
一个问题是url是需要动态拼接来带上url参数的，但是测试发现，组件里面的url不会变动，我变更了uploadUrl，但是实际上传时候还是使用初始化的值。
第二个问题是，我后端是使用asp.net core接收，用了 IFormFile file参数，奇怪的是安卓手机上传正常，苹果手机上传时候，file参数为null，实在找不到原因，只好绕开组件自带的上传功能。

**Comment by honghuamin** [comment]
@richard1015 这个issue能否再看看，或者是不是需要我贴完整测试代码？

**Comment by xiang12383** [comment]
搭车问一下，小程序中，删除upload图片，需要用dialog拦截一下。感觉，一个点是在 delete 处触发，另一个点是在 before-delete 处触发。但这玩意拦不住哈？请教一下怎么个拦截法？

**Comment by thx125** [comment]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/4711266/204765207-d74d7465-0e1a-4254-a67e-8cbf0102a5c9.png">
 @honghuamin 你可以参考以下代码：

```html
<!-- 当上传方式为put时，直接上传源文件file流 -->
<template>
  <nut-uploader url="https://xxxx" method="put" :before-xhr-upload="beforeXhrUpload"
    @success="uploadSuccess"></nut-uploader>
</template>

<script lang="ts" setup>
const beforeXhrUpload = (xhr: XMLHttpRequest, options: any) => {
  // if (options.method.toLowerCase() == 'put') {
  //   xhr.send(options.sourceFile);
  // } else {
  //   xhr.send(options.formData);
  // }
  // TODO 自定义上传逻辑
  options.onSuccess?.(xhr.responseText, options);
}

const uploadSuccess = (responseText: any, option: any, fileItem: any) => {
  console.log("提交成功", "success");
  // goback();//执行调整
};
</script>
```

**Comment by thx125** [comment]
> 搭车问一下，小程序中，删除upload图片，需要用dialog拦截一下。感觉，一个点是在 delete 处触发，另一个点是在 before-delete 处触发。但这玩意拦不住哈？请教一下怎么个拦截法？

添加属性:before-delete="onBeforeDelete"

```javascript
const onBeforeDelete = (_file: any,_fileList: any) => {
  alert("拦截删除")
  return false;
}
```

**Comment by richard1015** [comment]
近期有点忙，下周一我们重点关注跟进一下，谢谢理解

**Comment by honghuamin** [comment]
> <img alt="image" width="628" src="https://user-images.githubusercontent.com/4711266/204765207-d74d7465-0e1a-4254-a67e-8cbf0102a5c9.png">
> @honghuamin 你可以参考以下代码：
> 
> ```
> 
> <template>
>   <nut-uploader url="https://xxxx" method="put" :before-xhr-upload="beforeXhrUpload"
>     @success="uploadSuccess"></nut-uploader>
> </template>
> 
> <script lang="ts" setup>
> const beforeXhrUpload = (xhr: XMLHttpRequest, options: any) => {
>   // if (options.method.toLowerCase() == 'put') {
>   //   xhr.send(options.sourceFile);
>   // } else {
>   //   xhr.send(options.formData);
>   // }
>   // TODO 自定义上传逻辑
>   options.onSuccess?.(xhr.responseText, options);
> }
> 
> const uploadSuccess = (responseText: any, option: any, fileItem: any) => {
>   console.log("提交成功", "success");
>   // goback();//执行调整
> };
> </script>
> ```

我按照您的建议试了一下，是可以的，多谢了。
