### ISSUE TITLE
imagePreview的images,init-no属性设置问题

### ISSUE THREAD

**Issue by honghuamin** [jdf2e/nutui#1849]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-vue version（nutui-vue 版本）

3.2.6

### Vue version（vue 版本）
3.2.24

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.20

### Browser and its version（浏览器及其版本）
多种浏览器

### System and its version（系统及其版本）
苹果、安卓、电脑版本

### Taro environmental information（taro 环境信息）
Taro v3.5.6

  Taro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\simon\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/nutui3-vite-demo-forked-ghhbv6)

### Steps to reproduce（重现步骤）
codesandbox写了代码，但是无法编译通过，直接一个 @click 就报parse错误了 ，哭
简单描述问题： images属性通过异步方法设置值，打开preview时候，不能显示第一张图片，只有一个空的蒙版界面，只有手指滑动后图片才正常显示。
```
<nut-imagepreview autoplay=0 :show="showPreview" :images="imageList" :init-no="imageIdx" :content-close="true"  @close="hideFn"/>
```
在setup中，这样赋值
```
let imageList=ref([])
let imageIdx=ref(1)
```
然后有一个异步调用后端的操作，在获取后端的图片列表后，设置imageList属性的值：
```
imageList.value=获取后的图片列表
```
然后通过点击事件来显示preview
```
const showFn = (idx:number) => {
            imageIdx.value=idx
            state.showPreview = true;
}
```
试着在codeSandbox里写了代码，但是无法执行和保存
```
<template>
<div>
  <nut-button type="primary" @click="showFn(2)">主要按钮</nut-button>
  <nut-imagepreview autoplay=0 :show="showPreview" 
    :images="imageList" :init-no="imageIdx" :content-close="true"  @close="hideFn"/>
</div>
</template>
<script lang="ts">

import Taro from '@tarojs/taro'
import { reactive, toRefs,ref } from "vue";
export default {
  name: 'Index',
  components: {
  },
  setup(){
    let state = reactive({
        showPreview: false,
    });
    let imageList=ref([])
    let imageIdx=ref(1)
   
    const getImages=()=>{
            setTimeout(()=>{
              imageList.value=[
                {src:"https://news.cnblogs.com/Images/logo.gif"},
                {src:"https://img2022.cnblogs.com/news/66372/202211/66372-20221116223529714-61743463.png"},
                {src:"https://img2018.cnblogs.com/news_topic/20190823073538571-1095729341.png"}]
            },1000)
        }
    getImages();
    
    const showFn = (idx:number) => {
      console.log(imageList)
            imageIdx.value=idx
            state.showPreview = true;
        }

        const hideFn = () => {
            state.showPreview = false;
        }
    return {
        ...toRefs(state),
        showFn,
        hideFn,
        imageList,
        imageIdx
    };
  }
}
</script>
```

### What is expected?（期望的结果是什么？）
1 显示imagePreview时候，能显示图片
2 设置了init-no的值后，打开显示时候能首先定位到这张图片

### What is actually happening?（实际的结果是什么？）
1 imagePreview显示时候，出现模态界面，但是没有图片，需要手指滑动一下，才能显示图片。
2 init-no的值设置无效，比如这个值设置为2，打开preview时候，能显示 2/5这样是数字，但是显示的是第一张图片。

### Remarks（补充说明）
1 在初始化时候，这样写 let imageList=ref([{src:''}]) ，则第一个问题不会重现，但是init-no的故障如旧
2 如果imageList在setup里面写固定的数组，则imagePreview表现正常，与demo一致，且init-no的功能也正常。所有这些故障现象都是在images属性为后台获取后更新才发生的

**Comment by yangxiaolu1993** [comment]
你好，首先感谢对NutUI的支持，下个版本： 3.2.7 发布
