### ISSUE TITLE
[bug]scroll组件与动态component不兼容

### ISSUE THREAD

**Issue by Imageheart** [jdf2e/nutui#185]
## 问题描述

scroll组件与动态component不兼容，即使用动态component切换组件时，scroll无法响应相应情况。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码

使用vant 的tab组件及vue 的动态component，来通过切换相应的tab来切换不同的component,但nutui的scroll没有对应切换。

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：
- **NutUI 版本**：2.1.8
- **Vue 版本**：2.6.10
- **引用方式**：  CDN / NPM ？ NPM

**Comment by richard1015** [comment]
已记录、修复后会第一时间通知
