### ISSUE TITLE
Android 红米K30 Pro Tabs 组件卡顿

### ISSUE THREAD

**Issue by richard1015** [jdf2e/nutui#1851]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.2.6

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16

### Browser and its version（浏览器及其版本）
cr

### System and its version（系统及其版本）
mac

### Taro environmental information（taro 环境信息）
Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 11.6.6
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-vue3: 3.5.7 => 3.5.7 
      @tarojs/plugin-html: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-alipay: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-jd: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-qq: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-swan: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-tt: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 

### Reproduction link（重现链接）
[github.com/coder-pz/test.git](https://github.com/coder-pz/test.git)

### Steps to reproduce（重现步骤）
点击-预约按钮

### What is expected?（期望的结果是什么？）
流程

### What is actually happening?（实际的结果是什么？）
安卓卡顿

**Comment by eiinu** [comment]
开发者工具：不卡顿
真机测试模式：卡顿
退出真机测试模式后，在手机端使用测试小程序：不卡顿

**Comment by richard1015** [comment]
该问题已定位到， 由于 首页使用 swiper 组件， 当前切换 新页面 Tabs 时，swiper 在上一个页面 依然自动轮播中占用 渲染线程，导致 其它页面切换卡顿
暂时解决方案，您的首页暂时采用  默认 Taro Swiper
