### ISSUE TITLE
vue3使用video组件，如果视频加载失败弹出”请点击重试“的提示，这个提示即使在切换到下一条能正常播放的视频时任然会存在

### ISSUE THREAD

**Issue by kerwingo** [jdf2e/nutui#1859]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.2.6

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.19.1

### Browser and its version（浏览器及其版本）
103

### System and its version（系统及其版本）
andriod

### Reproduction link（重现链接）
[https://nutui.jd.com/](https://nutui.jd.com/)

### Steps to reproduce（重现步骤）
动态切换视频链接

### What is expected?（期望的结果是什么？）
错误提示消失

### What is actually happening?（实际的结果是什么？）
未消失

**Comment by Drjingfubo** [comment]
提示需要点击一下才可以关闭

**Comment by Drjingfubo** [comment]
是点击了也没消失吗
