### ISSUE TITLE
建议增加buttonGroup组件

### ISSUE THREAD

**Issue by cn0o0king** [jdf2e/nutui#1862]
### What problem does this feature solve?（这个功能解决的问题）
世界业务中，使用按钮组的场景很多，比如对项目的操作，【新增】【修改】【删除】等

### What does the proposed API look like?（期望的 API）
API的需求应该不多，基本只是样式的继承

**Comment by szg2008** [comment]
目前没有支持的计划，您上面提到的直接使用多个Button即可
