### ISSUE TITLE
collapseitem 动态生成，响应慢

### ISSUE THREAD

**Issue by Anberm** [jdf2e/nutui#1864]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.2.7

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
Window 10

### Taro environmental information（taro 环境信息）
  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - d:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - d:\Program Files\nodejs\yarn.CMD
      npm: 8.5.5 - d:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/nutui3-vite-demo-forked-fdkjde?file=/src/App.vue)

### Steps to reproduce（重现步骤）
1.设置collapse v-model:active="active"
2.v-for遍历出collapse-item
3.点击item，触发折叠

### What is expected?（期望的结果是什么？）
期望能正常折叠

### What is actually happening?（实际的结果是什么？）
1.h5上，无响应，控制台报 Unhandled error during execution of native event handler 
2.微信小程序上，箭头图标慢1秒多才反应

**Comment by ayayui** [comment]
展开collapseitem 时后台报错  （:accordion="true" 手风琴模式失效）

VM909 WAService.js:2 TypeError: Cannot read property 'name' of null
    at ._node_modules_@nutui_nutui-taro_dist_packages__es_Collapse.js:110
    at Array.forEach (<anonymous>)
    at ._node_modules_@nutui_nutui-taro_dist_packages__es_Collapse.js:108
    at Function.<anonymous> (.._src_next-tick.ts:11)
    at :29214/appservice/<setTimeout callback function>
    at VM909 WAService.js:2
    at VM909 WAService.js:2(env: Windows,mp,1.06.2206020; lib: 2.17.0)

**Comment by whevether** [comment]
同样。  而且高度改成了计算的，计算的还不准， 直接用height: auto就好了啊.
