### ISSUE TITLE
textarea Cannot read properties of undefined (reading 'height')

### ISSUE THREAD

**Issue by hhch** [jdf2e/nutui#1866]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.2.7

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
windows10

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.7

  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.2 - D:\Program Files\nodejs\node.EXE
      npm: 9.1.2 - D:\Program Files\nodejs\npm.CMD

### Steps to reproduce（重现步骤）
沙盒里复现不了
taro init 一个最新的 nutUi项目，然后 < nut-textarea v-model="value" autosize    
是autosize    引起的

### What is expected?（期望的结果是什么？）
不报错

### What is actually happening?（实际的结果是什么？）
Uncaught TypeError: Cannot read properties of undefined (reading 'height')
    at SelectorQuery.eval (TextArea.js?0d77:152:1)
    at vendors-node_modules_taro_h5_prebundle_chunk-XERMPTE7_js.js:9310:44
    at queryBat (vendors-node_modules_taro_h5_prebundle_chunk-XERMPTE7_js.js:9285:5)
    at SelectorQuery.exec (vendors-node_modules_taro_h5_prebundle_chunk-XERMPTE7_js.js:9304:9)
    at getRefHeight (TextArea.js?0d77:149:1)
    at eval (TextArea.js?0d77:175:1)
    at vendors-node_modules_taro_h5_prebundle_chunk-NILPY676_js.js:3008:34
eval @ TextArea.js?0d77:152
(anonymous) @ vendors-node_modules_taro_h5_prebundle_chunk-XERMPTE7_js.js:9310
queryBat @ vendors-node_modules_taro_h5_prebundle_chunk-XERMPTE7_js.js:9285
exec @ vendors-node_modules_taro_h5_prebundle_chunk-XERMPTE7_js.js:9304
getRefHeight @ TextArea.js?0d77:149
eval @ TextArea.js?0d77:175
(anonymous) @ vendors-node_modules_taro_h5_prebundle_chunk-NILPY676_js.js:3008
setTimeout (async)
timerFunc @ vendors-node_modules_taro_h5_prebundle_chunk-NILPY676_js.js:3007
nextTick @ vendors-node_modules_taro_h5_prebundle_chunk-NILPY676_js.js:3022
eval @ TextArea.js?0d77:170
(anonymous) @ vendors-node_modules_taro_h5_prebundle_chunk-RPSBCJG3_js.js:11812
callWithErrorHandling @ vendors-node_modules_taro_h5_prebundle_chunk-RPSBCJG3_js.js:6271
callWithAsyncErrorHandling @ vendors-node_modules_taro_h5_prebundle_chunk-RPSBCJG3_js.js:6279
hook.__weh.hook.__weh @ vendors-node_modules_taro_h5_prebundle_chunk-RPSBCJG3_js.js:7885
flushPostFlushCbs @ vendors-node_modules_taro_h5_prebundle_chunk-RPSBCJG3_js.js:6420
flushJobs @ vendors-node_modules_taro_h5_prebundle_chunk-RPSBCJG3_js.js:6447
Promise.then (async)
queueFlush @ vendors-node_modules_taro_h5_prebundle_chunk-RPSBCJG3_js.js:6366
queueJob @ vendors-node_modules_taro_h5_prebundle_chunk-RPSBCJG3_js.js:6360
reload @ vendors-node_modules_taro_h5_prebundle_chunk-RPSBCJG3_js.js:6536
(anonymous) @ vendors-node_modules_taro_h5_prebundle_chunk-RPSBCJG3_js.js:6562
eval @ index.vue?baf6:15
./src/pages/index/index.vue @ src_pages_index_index_vue.js:72
__webpack_require__ @ runtime.js:36
_requireSelf @ runtime.js:492
apply @ runtime.js:1218
(anonymous) @ runtime.js:720
internalApply @ runtime.js:718
hotApply @ runtime.js:677
eval @ only-dev-server.js?2ed5:25
Promise.then (async)
check @ only-dev-server.js?2ed5:13
eval @ only-dev-server.js?2ed5:88
emit @ events.js?faa1:153
reloadApp @ reloadApp.js?1569:46
ok @ index.js?2be9:175
eval @ socket.js?47a2:57
client.onmessage @ WebSocketClient.js?626b:50

**Comment by Ymm0008** [comment]
问题已处理，本周发版，感谢反馈 @hhch
