### ISSUE TITLE
taro  @nutui/nutui-taro 按需加载 inputnumber 的样式失效

### ISSUE THREAD

**Issue by yanchengjie1990** [jdf2e/nutui#1874]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-vue version（nutui-vue 版本）

3.1.8

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.9.0

### Browser and its version（浏览器及其版本）
Chrome(104.0.5112.102)

### System and its version（系统及其版本）
windows

### Taro environmental information（taro 环境信息）
Debugger attached.
👽 Taro v3.5.7

  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.9.0 - C:\Program Files\nodejs\node.EXE
      npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD  

Waiting for the debugger to disconnect...

### Reproduction link（重现链接）
[github.com](https://github.com/yanchengjie1990/taroBug)

### Steps to reproduce（重现步骤）
npm install 后直接运行命令 
npm run dev:h5

### What is expected?（期望的结果是什么？）
展示成nutui官网组件一样的样式

### What is actually happening?（实际的结果是什么？）
浏览器原型无样式的input

**Comment by yanchengjie1990** [comment]
![image](https://user-images.githubusercontent.com/4362722/204174011-ca2bd4ea-667e-4feb-88db-f3ea75a86b03.png)

**Comment by Drjingfubo** [comment]
本周五发版
