### ISSUE TITLE
nutui-upload限制上传一张图片失败时 （maximum=1），无法清空上传失败的图片，导致无法再次点击上传按钮上传

### ISSUE THREAD

**Issue by houxw111jdcom** [jdf2e/nutui#1875]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.2.2

### Vue version（vue 版本）
3.2.36

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
v14.18.2

### Browser and its version（浏览器及其版本）
107.0.5304.108

### System and its version（系统及其版本）
Microsoft Windows 10 企业版 64 Build 19044

### Reproduction link（重现链接）
[codehouse.jd.com/](https://codehouse.jd.com/?source=share&type=vue&mainJs=Ly9pbXBvcnQgVkNvbnNvbGUgZnJvbSAidmPGDyI7Ci8vdmFyIHbIID0gbmV3yS8oKTsKx0J7IGNyZWF0ZUFwcCB9yEd1xELHIcQZxhcuL2FwcC7NHU51dFVJxx9AbnV0dWkvxQbKIsc2c2Nzc8sVzCwvZGlzdC9zdHlsZS7GJukAkihBcHApLnVzZSjFaSkubW91bnQoIiNhcHAiKTs=&appValue=PHRlbXBsYXRlPgogIDxudXQtdXBsb2FkZXIgdXJsPSJodHRwczovL3h4eHgiIG11bHRpcGxlIG1heGltdW09IjUiPjwvzDc+CjwvylQ=&scssValue=)

### Steps to reproduce（重现步骤）
<nut-uploader
    ref="uploadFile"
    :before-xhr-upload="
      (xhr, options) => beforeXhrUpload(xhr, options, currentIndex)
    "
    :is-preview="false"
    :maximize="1"
    method="put"
    :multiple="false"
    timeout="60000"
    :url="uploadUrl"
  >
<nut-button>确认</nut-button>
  </nut-uploader>

### What is expected?（期望的结果是什么？）
上传失败时能提空清除文件的方法，再次点击能够上传

### What is actually happening?（实际的结果是什么？）
上传失败时不能提空清除上传失败的文件，无法再次点击确认按钮上传

**Comment by richard1015** [comment]
报错后 通过 ref 执行   uploadFile.value.clearUploadQueue();
