### ISSUE TITLE
tab的优化问题

### ISSUE THREAD

**Issue by yuanxin42** [jdf2e/nutui#1884]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.2.7

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
106

### System and its version（系统及其版本）
12

### Reproduction link（重现链接）
[nutui.jd.com](https://nutui.jd.com/nutui-issue-helper/?repo=jdf2e/nutui&lang=zh-cn)

### Steps to reproduce（重现步骤）
1、如果数据量大的话，切换tab，会出现卡顿，但是用v-if隐藏其余tab下的元素，卡顿会缓解
2、@change 不生效，如果当前tabvalue为1，再次点击1的tab，仍会触发对应事件

### What is expected?（期望的结果是什么？）
1、如果数据量大的话，切换tab，会出现卡顿，但是用v-if隐藏其余tab下的元素，卡顿会缓解
2、@change 不生效，如果当前tabvalue为1，再次点击1的tab，仍会触发对应事件

### What is actually happening?（实际的结果是什么？）
1、如果数据量大的话，切换tab，会出现卡顿，但是用v-if隐藏其余tab下的元素，卡顿会缓解
2、@change 不生效，如果当前tabvalue为1，再次点击1的tab，仍会触发对应事件

### Remarks（补充说明）
1、如果数据量大的话，切换tab，会出现卡顿，但是用v-if隐藏其余tab下的元素，卡顿会缓解
2、@change 不生效，如果当前tabvalue为1，再次点击1的tab，仍会触发对应事件

**Comment by richard1015** [comment]
数据量过大时建议 :animated-time="0" 关闭动画
