### ISSUE TITLE
nutui-taro使用按需导入时使用Dialog时没有遮罩且没有居中

### ISSUE THREAD

**Issue by XJH0415** [jdf2e/nutui#1888]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.2.7

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.10.0

### Browser and its version（浏览器及其版本）
小程序？？？？？

### System and its version（系统及其版本）
MacOS 13.0 (22A380)

### Taro environmental information（taro 环境信息）
Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-vue3: 3.5.7 => 3.5.7 
      @tarojs/plugin-html: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-alipay: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-jd: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-qq: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-swan: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-tt: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 

### Reproduction link（重现链接）
小程序没有链接？？？

### Steps to reproduce（重现步骤）
babel.config.js
plugins: [
    [
      "import",
      {
        libraryName: "@nutui/nutui-taro",
        libraryDirectory: "dist/packages/_es",
        style: (name, file) => name.toLowerCase().replace("_es/", "") + "/index.scss",
        camel2DashComponentName: false,
      },
      "nutui3-taro",
    ],
  ],

app.ts
import { createApp } from "vue";
import "./app.scss";

const App = createApp({
  onShow(options) {},
});

export default App;

index.vue
<template>
  <view class="index">
    <view>
      <img src="" alt="" />
    </view>
    {{ msg }}
    <view class="btn">
      <nut-button type="primary" @click="handleClick('text', msg2, true)"
        >点我</nut-button
      >
    </view>
    <nut-dialog title="基础弹框" content="这是基础弹框。" :visible="show" />
  </view>
</template>

<script lang="ts">
import { reactive, toRefs } from "vue";
import { Button, Dialog } from "@nutui/nutui-taro";
export default {
  name: "Index",
  components: {
    "nut-button": Button,
    "nut-dialog": Dialog,
  },
  setup() {
    const state = reactive({
      msg: "欢迎使用 NutUI3.0 开发小程序",
      msg2: "你成功了～",
      type: "text",
      show: false,
      cover: false,
    });

    const handleClick = (type, msg, cover = false) => {
      state.show = true;
      state.msg2 = msg;
      state.type = type;
      state.cover = cover;
    };

    return {
      ...toRefs(state),
      handleClick,
    };
  },
};
</script>

<style lang="scss">
.index {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
}
</style>

### What is expected?（期望的结果是什么？）
期望正确显示

### What is actually happening?（实际的结果是什么？）
dialog 没有遮罩，且不居中

**Comment by Drjingfubo** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/50685476/205027172-96f9b7b6-8b2f-450e-b426-b9b8eb2b9ef2.png">
dialog还需引入popup和overlay

**Comment by XJH0415** [comment]
这不是最好的方案，这只是临时解决。最好的方案应该是dialog的样式自己内部会关联popup和overlay。目前只发现dialog会有问题，不确定其它组件是否会有问题，如果有存在相同问题，那使用者也不清楚需要导入哪些关联组件的

**Comment by Drjingfubo** [comment]
dialog组件依赖popup和overlay，目前nutui组件的使用必须引入其依赖组件
导入关联组件有哪些在组件文档上都有标注的

**Comment by Drjingfubo** [comment]
我明白您的意思
这个问题将会在v4通过[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 来解决   #1804

**Comment by Drjingfubo** [comment]
目前的话使用还是需要您导入一下关联组件

**Comment by XJH0415** [comment]
好的
