### ISSUE TITLE
NutUI 交流群

### ISSUE THREAD

**Issue by richard1015** [jdf2e/nutui#189]
> 微信交流群

请添加微信zhida51844712备注  申请加群 nutui 

:tada::tada:欢迎大家使用NutUI组件库~ :tada::tada:

如果您在使用过程中遇到什么问题可通过 Issues 或邮件 nutui@jd.com 联系我们。

目前NutUI已在京东内外众多项目中应用，如果你的项目中也有用到，欢迎留言告诉我们，建议包含以下内容：

- 产品/项目：
- 链接：（如果可以）
- 公司或组织：（如果可以）
- 截图：（如果可以）
- Email：（如果可以）

> 如果不方便公开，可以通过邮件告诉我们。

您的支持是我们开发的动力。

欢迎Star，欢迎PR~

**Comment by Draymonders** [comment]
二维码过期了

**Comment by richard1015** [comment]
> 二维码过期了

已更新

**Comment by g1012415019** [comment]
二维码过期了

**Comment by z778856** [comment]
申请了

**Comment by xiaoshidebaiyuhui** [comment]
什么时候支持vue3

**Comment by richard1015** [comment]
> 什么时候支持vue3

正在进行中

**Comment by guoxiao158** [comment]
> 什么时候支持vue3

测试版本将会在本月底发布，可以参考 next分支，欢迎关注～
