### ISSUE TITLE
Menu箭头翻转完了，然后突然关闭

### ISSUE THREAD

**Issue by yangjinjun3** [jdf2e/nutui#1898]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.3.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.13.0

### Browser and its version（浏览器及其版本）
106.0.5249.119

### System and its version（系统及其版本）
MacOS(12.6)

### Taro environmental information（taro 环境信息）
Taro v3.5.7

  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-vue3: 3.5.7 => 3.5.7 
      @tarojs/plugin-html: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-alipay: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-jd: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-qq: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-swan: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-tt: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 

### Reproduction link（重现链接）
[github.com](https://github.com/jdf2e/nutui-demo.git)

### Steps to reproduce（重现步骤）
无

### What is expected?（期望的结果是什么？）
有消失的动画

### What is actually happening?（实际的结果是什么？）
突然消失

**Comment by Ymm0008** [comment]
https://github.com/jdf2e/nutui/commit/0f7f26a2f265b5671f2ae6380e7f4dcd6109e921 修复动画问题
