### ISSUE TITLE
nutui 没有form组件？

### ISSUE THREAD

**Issue by qbob** [jdf2e/nutui#19]
form 组件
input 组件
目前看到文档和代码里面没有，后期会有吗？

**Comment by Franslee** [comment]
> form 组件
> input 组件
> 目前看到文档和代码里面没有，后期会有吗？

具体需要哪些input组件？

**Comment by qbob** [comment]
> > form 组件
> > input 组件
> > 目前看到文档和代码里面没有，后期会有吗？
> 
> 具体需要哪些input组件？

常用的 input或textarea的输入框，及其demo

**Comment by Franslee** [comment]
我们会考虑您的建议，感谢关注NutUI

**Comment by cnyyk** [comment]
textarea 参考 vux 的textarea，带字数统计，如图

![WX20190312-154136](https://user-images.githubusercontent.com/275233/54182797-71402080-44dd-11e9-929f-ecb5a2b7564c.png)

**Comment by DivXPro** [comment]
text这个是最基础的input组件啊，为啥没有啊 叹气

**Comment by Franslee** [comment]
安排~

**Comment by snowdream** [comment]
关注

**Comment by viccsen** [comment]
这个很基础也很关键～

**Comment by alennx** [comment]
等待form组件的完善

**Comment by Franslee** [comment]
text组件已经有了
