### ISSUE TITLE
请问哪里可以看到目前可用的icon集合

### ISSUE THREAD

**Issue by KevinnZou** [jdf2e/nutui#1900]
### What problem does this feature solve?（这个功能解决的问题）
可以直接看到所有可用的icon即name，不然现在不知道能用啥？

### What does the proposed API look like?（期望的 API）
如上

**Comment by szg2008** [comment]
demo中展示的就是目前所有可直接使用的icon，其他的可以自定义

**Comment by richard1015** [comment]
https://nutui.jd.com/#/zh-CN/component/icon
