### ISSUE TITLE
nut-calendar能支持不展示title吗？

### ISSUE THREAD

**Issue by KevinnZou** [jdf2e/nutui#1902]
### What problem does this feature solve?（这个功能解决的问题）
nut-calendar能支持不展示title吗？因为如果起了一个新页面全屏展示日历，本身页面就有标题，日历又带一个标题，就重合了

### What does the proposed API look like?（期望的 API）
如上

**Comment by szg2008** [comment]
设置title为空试试呢

**Comment by KevinnZou** [comment]
传空或者不传都会展示默认标题

**Comment by szg2008** [comment]
好的，明白了，我们跟进一下，🙏反馈

**Comment by lkjh3214** [comment]
可以通过 show-title 字段控制
![image](https://user-images.githubusercontent.com/23164467/205786362-a22e7959-a75d-4dde-bbcc-4ca9eb5dfdd7.png)

**Comment by KevinnZou** [comment]
哦哦，是我没注意到这个字段。。。
还有一个问题，我是拿一整个页面来展示日历的，日历在平铺状态下是没有底部确认按钮的？我只能自己写了一个，但是发现了另外一个问题，日历只有前几个月能正常展示，后面都是白屏，没渲染出来。
![飞书20221206-100740](https://user-images.githubusercontent.com/43654611/205791427-83093835-deb7-47a9-af98-e7afc76379d5.jpg)
![飞书20221206-100744](https://user-images.githubusercontent.com/43654611/205791433-bbfbb732-bfb5-4cc9-b06f-4283af131d3d.jpg)
```
<template>
  <view class="calendar-page">
    <view class="calendar-wrapper">
      <nut-calendar
        class="calendar"
        :poppable="false"
        :default-value="date"
        type="range"
        :is-auto-back-fill="true"
        @choose="onDateChosen"
        confirm-text="提交"
        start-text="入店"
        end-text="离店"
        title="选择入住日期"
        :show-title="false"
        :show-sub-title="false"
      >
      </nut-calendar>
    </view>

    <nut-button
      size="large"
      class="confirm-button"
      type="primary"
      @click="confirmDate"
      >确认</nut-button
    >
  </view>
</template>
```
```
<style lang="scss">
.calendar-page {
  width: 100%;
  height: 100%;
  align-items: center;

  .calendar-wrapper {
    display: flex;
    width: 100%;
    height: 90%;
    overflow: hidden;
  }

  .confirm-button {
    // width: 80%;
    width: 90%;
    position: fixed;
    bottom: 20px;
    left: 0;
    right: 0;
    margin: 0 auto;
    text-align: center;
  }
}
</style>
```

**Comment by KevinnZou** [comment]
还有想要设置日历高度为页面的90%也没有生效

**Comment by lkjh3214** [comment]
给外层加个容器， 给容器设置一个高度。

**Comment by lkjh3214** [comment]
![image](https://user-images.githubusercontent.com/23164467/205804877-f50cafe9-5595-4844-918f-f5135ff83510.png)
例如这里，平铺的日历 会根据容器来

**Comment by KevinnZou** [comment]
你看我上面的代码，内外都加了，但是没有效果。

**Comment by lkjh3214** [comment]
请问是在 小程序 还是 H5 ?  然后就是 nutui 版本是多少？方便的话可以留个微信，便于联系，同时可以将你拉入沟通群

**Comment by KevinnZou** [comment]
小程序，3.1.8。要不你留一个，我加你？

**Comment by lkjh3214** [comment]
Lk_chibaoshui  加一下吧
