### ISSUE TITLE
nut-dialog Property "overlayClass" was accessed during render but is not defined on instance. 

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui#1905]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.3.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.0

### Browser and its version（浏览器及其版本）
版本 107.0.5304.87（正式版本）

### System and its version（系统及其版本）
Macos(10.15.7)

### Taro environmental information（taro 环境信息）
Taro CLI 3.5.8 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: ^3.5.8 => 3.5.8 
      @tarojs/components: ^3.5.8 => 3.5.8 
      @tarojs/helper: ^3.5.8 => 3.5.8 
      @tarojs/plugin-framework-vue3: ^3.5.8 => 3.5.8 
      @tarojs/plugin-html: ^3.5.8 => 3.5.8 
      @tarojs/plugin-platform-alipay: ^3.5.8 => 3.5.8 
      @tarojs/plugin-platform-jd: ^3.5.8 => 3.5.8 
      @tarojs/plugin-platform-qq: ^3.5.8 => 3.5.8 
      @tarojs/plugin-platform-swan: ^3.5.8 => 3.5.8 
      @tarojs/plugin-platform-tt: ^3.5.8 => 3.5.8 
      @tarojs/plugin-platform-weapp: ^3.5.8 => 3.5.8 
      @tarojs/plugin-vue-devtools: ^3.5.8 => 3.5.8 
      @tarojs/router: ^3.5.8 => 3.5.8 
      @tarojs/runtime: ^3.5.8 => 3.5.8 
      @tarojs/shared: ^3.5.8 => 3.5.8 
      @tarojs/taro: ^3.5.8 => 3.5.8 
      @tarojs/taro-h5: ^3.5.8 => 3.5.8 
      @tarojs/webpack5-runner: ^3.5.8 => 3.5.8 
      babel-preset-taro: ^3.5.8 => 3.5.8 

### Reproduction link（重现链接）
[github.com](https://github.com/yanbowe/taro-vue3-pinia)

### Steps to reproduce（重现步骤）
pnpm install & pnpm dev:h5
查看控制台

### What is expected?（期望的结果是什么？）
不输出警告

### What is actually happening?（实际的结果是什么？）
每次显示隐藏弹窗都会有警告报错
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/43030980/206069470-fe9cf2d9-aab7-45d0-924f-20657cdd6011.png">

**Comment by shijunti19** [comment]
对啊，你们开发好了，不校对的吗，这种低级错误都有！还不及时修复

**Comment by yanbowe** [comment]
> 对啊，你们开发好了，不校对的吗，这种低级错误都有！还不及时修复

问题不是你发泄的地方，你行你上，不然就别bb

**Comment by shijunti19** [comment]
@yanbowe 他们本来就是态度有问题，每次发布新版本，右边的官方例子不同步升级，所有的页面不自己重新点一遍看的，每次更都是一堆严重影响使用的小BUG

**Comment by yanbowe** [comment]
> 

本身就是开源的，没必要这么大的怨气，觉得不行就换一个，选择权在你手上
