### ISSUE TITLE
price 组件划线价

### ISSUE THREAD

**Issue by KevinnZou** [jdf2e/nutui#1907]
### What problem does this feature solve?（这个功能解决的问题）
price组件能提供划线价的支持吗？

### What does the proposed API look like?（期望的 API）
如上

**Comment by KevinnZou** [comment]
似乎还是没有支持？

**Comment by Drjingfubo** [comment]
你用的v3还是v4

**Comment by KevinnZou** [comment]
v4

**Comment by Drjingfubo** [comment]
先自己整个样式实现下，v4下次发版的时候加上
