### ISSUE TITLE
[suggest]nut-picker可不可以加个自定义类名设置？

### ISSUE THREAD

**Issue by hong-q** [jdf2e/nutui#1908]
### What problem does this feature solve?（这个功能解决的问题）
如此就可以在选择限制外的日期时，禁用掉“确认”按钮，或者可以修改标题栏的文字样式

### What does the proposed API look like?（期望的 API）
和columns类似，加个className的配置项

**Comment by yangxiaolu1993** [comment]
你好，感谢对NutUI的支持。
1、在调用 picker 组件时，可直接设置 class 值。
2、禁用掉“确认”按钮功能，组件自身会加一个 api
