### ISSUE TITLE
nut-image 无法正常显示图片

### ISSUE THREAD

**Issue by yanchengjie1990** [jdf2e/nutui#1909]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.1.8

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18.12.1

### Browser and its version（浏览器及其版本）
Chrome(104.0.5112.102)

### System and its version（系统及其版本）
windows

### Reproduction link（重现链接）
[github.com](https://github.com/yanchengjie1990/taroBug)

### Steps to reproduce（重现步骤）
npm install 后直接运行命令
npm run dev:h5

### What is expected?（期望的结果是什么？）
展示成nutui官网demo组件一样的样式

### What is actually happening?（实际的结果是什么？）
展示：Welcome to developing components

### Remarks（补充说明）
我是直接复制官网demo，但无法正常显示

**Comment by yanchengjie1990** [comment]
![image](https://user-images.githubusercontent.com/4362722/206380673-44bf05fe-24bf-45ef-87b0-dbcecd123c75.png)

**Comment by szg2008** [comment]
nut-image不支持小程序，使用原生Image组件即可.https://nutui.jd.com/#/zh-cn/component/image-taro

**Comment by yanchengjie1990** [comment]
> nut-image不支持小程序，使用原生Image组件即可.https://nutui.jd.com/#/zh-cn/component/image-taro

好的
