### ISSUE TITLE
datepicker 部分手机样式不兼容

### ISSUE THREAD

**Issue by wychengnuo** [jdf2e/nutui#191]
![image](https://user-images.githubusercontent.com/10297021/71566690-9ba6ad00-2af4-11ea-8e5c-aca99a05af75.png)

**Comment by richard1015** [comment]
@wychengnuo 

请提供一下 相关环境信息
- **手机型号**：
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by wychengnuo** [comment]
手机型号：SM-G9650/DS
操作系统：安卓
Node版本：10.14.2
NutUI版本：2.1.7
Vue版本：2.5.17
引用方式：npm
场景：京东金融app

**Comment by wychengnuo** [comment]
安卓版本9

**Comment by guoxiao158** [comment]
@wychengnuo  请问是在滑动的时候出现的还是 初始化的时候，使用的代码方便贴一下吗

**Comment by wychengnuo** [comment]
滑动的时候，这个我自己解决了。
.nut-picker-list .nut-picker-item, .nut-picker-list .nut-picker-roller-item {
    height: 36px !important;
}
给这个一个高度，因为里面只写了line-height以至于有的手机会出现高度的错位情况
