### ISSUE TITLE
picker 选择器 无法正常选择

### ISSUE THREAD

**Issue by juzijun2020** [jdf2e/nutui#1911]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.3.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
Chrome(107.0.5304.121)

### System and its version（系统及其版本）
Macos(10.15.7)

### Taro environmental information（taro 环境信息）
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.8 => 3.5.8 
      @tarojs/components: 3.5.8 => 3.5.8 
      @tarojs/plugin-html: 3.5.8 => 3.5.8 
      @tarojs/runtime: 3.5.8 => 3.5.8 
      @tarojs/taro: 3.5.8 => 3.5.8 
      babel-preset-taro: 3.5.8 => 3.5.8 
      eslint-config-taro: 3.5.8 => 3.5.8 
    npmGlobalPackages:
      typescript: 4.1.3

### Reproduction link（重现链接）
[github.com](https://github.com/juzijun2020/test/commit/43184d0df5396a197028d17402021a997db9e527)

### Steps to reproduce（重现步骤）
看上面的链接

### What is expected?（期望的结果是什么？）
正常选择

### What is actually happening?（实际的结果是什么？）
无法正常选择

**Comment by welchwsy** [comment]
同样的问题，五无报错，就是无法使用

**Comment by yangxiaolu1993** [comment]
感谢反馈，问题已修改，将在 3.3.1 版本发布

**Comment by SmalldayEvil** [comment]
> 

3.3.1什么时候发布  项目也出现了这种情况
