### ISSUE TITLE
Picker组件在H5环境真机下从底部弹出时没有动画

### ISSUE THREAD

**Issue by gyt95** [jdf2e/nutui#1921]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.3.0

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
chrome108

### System and its version（系统及其版本）
win10

### Reproduction link（重现链接）
[nutui.jd.com/](https://nutui.jd.com/?jdb#/zh-CN/component/picker)

### Steps to reproduce（重现步骤）
官方demo

### What is expected?（期望的结果是什么？）
真机下底部弹出有动画。

### What is actually happening?（实际的结果是什么？）
真机没有动画，开发者工具模拟器有动画。

**Comment by yangxiaolu1993** [comment]
感谢反馈，问题已修改，将在 3.3.1 版本发布
