### ISSUE TITLE
Datepicker组件：将手机字体调大后放大镜效果错乱[bug]

### ISSUE THREAD

**Issue by CyrusFeng** [jdf2e/nutui#193]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
将手机字体调大后放大镜效果错乱，导致选择的日期和显示结果日期不匹配

## 相关环境信息
- **操作系统**：安卓
- **Node 版本**：v10.4.1
- **NutUI 版本**：2.1.5
- **Vue 版本**：2.6.10
- **引用方式**：  CDN / NPM ？yarn

**Comment by richard1015** [comment]
@CyrusFeng    是否可以提供一下手机型号和相关使用场景， 内嵌APP 还是 H5

**Comment by CyrusFeng** [comment]
@richard1015 华为meta30；在App中内嵌的H5；将手机系统字体调大后，调用datepicker组件滚动效果错乱。如：选择2019年后，但是返回结果却是2017年

**Comment by richard1015** [comment]
@CyrusFeng    尝试一下 #191 解决方案
