### ISSUE TITLE
Form 中 Button 点击都会触发 submit  ,希望增加 htmlType 的props  可控的触发submit 

### ISSUE THREAD

**Issue by Chen20181120** [jdf2e/nutui#1939]
### What problem does this feature solve?（这个功能解决的问题）
button 可控的触发submit 

### What does the proposed API look like?（期望的 API）
htmlType	设置 button 原生的 type 值，

**Comment by richard1015** [comment]
taro 场景吗？ 当前是默认支持透传属性的 直接设置试试呢
