### ISSUE TITLE
【bug】tab切换title不会自动滚动到可视区域

### ISSUE THREAD

**Issue by akFace** [jdf2e/nutui#1943]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-vue version（nutui-vue 版本）

3.3.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5  
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
window10

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.7

  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/nutui3-vite-demo-forked-5bfgek?file=/src/App.vue)

### Steps to reproduce（重现步骤）
点击按钮手动切换tab

### What is expected?（期望的结果是什么？）
title部分自动滚动到可视区域

### What is actually happening?（实际的结果是什么？）
没有在自动滚动

**Comment by gyt95** [comment]
能否具体描述下想要的效果。意思是你想点击一个按钮，下方显示tab10对应的内容，并且title也要滚动到tab10的位置？

**Comment by akFace** [comment]
> 能否具体描述下想要的效果。意思是你想点击一个按钮，下方显示tab10对应的内容，并且title也要滚动到tab10的位置？

是的 可以看看这里demo：[codesandbox](https://codesandbox.io/s/nutui3-vite-demo-forked-5bfgek?file=/src/App.vue)
点击按钮的时候内容是切换了，但是tab上的title没有滚动到可视区域

**Comment by richard1015** [comment]
v3.3.2

**Comment by akFace** [comment]
> v3.3.2

![image](https://user-images.githubusercontent.com/22288837/210688835-d631f0d2-ab2c-4a67-8d88-a2c3f8a47cf0.png)

打印的日志没去掉 😂

**Comment by akFace** [comment]
> v3.3.2

我更新到 3.3.3 版本的又不行了 😂
