### ISSUE TITLE
设计稿750nutui是用350

### ISSUE THREAD

**Issue by 603507931** [jdf2e/nutui#195]
求问我项目中引用了px2rem-loader按照750设计稿大小来的，但是nutui是用350设计稿大小来的，这个怎么处理哈

**Comment by 603507931** [comment]
比如设计稿750使用postcss-px2rem会导致样式崩塌
解决方法：
卸载postcss-px2rem： npm uninstall postcss-px2rem
安装postcss-px2rem-exclude：npm i postcss-px2rem-exclude -D
在根目录.postcssrc.js文件夹下写入
module.exports = {
  plugins: {
    'autoprefixer': {
      browsers: ['Android >= 4.0', 'iOS >= 7']
    },
    'postcss-px2rem-exclude': {
      remUnit: 75,//结果为：设计稿元素尺寸/16，比如元素宽320px,最终页面会换算成 20rem
      exclude: /node_modules/     //此行为忽略node_modules下的文件
    }
  }
}

如果package.json 中有关于postcss的配置请删除写到.postcssrc.js里

**Comment by richard1015** [comment]
@603507931   👍
