### ISSUE TITLE
关于Dialog使用lockBgScroll: true属性设置时会把背景挤压的问题

### ISSUE THREAD

**Issue by moxunbai** [jdf2e/nutui#196]
测试代码如下：
<template>
  <div id="app">

    <div style="width:88%;margin:auto;">
      <nut-button @click="showDialog" block >
        测试1
      </nut-button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'app',
  methods:{
    showDialog(){
      this.$dialog({lockBgScroll: true,  title: '这里是测试啊啊啊阿 !'});
    }
  }
}

**Comment by guoxiao158** [comment]
能把这个挤压具体描述一下吗，是因为个body加了fix导致的吗？

**Comment by moxunbai** [comment]
应该是的，去掉好像正常了
