### ISSUE TITLE
关于iOS上面ButtonGroup 按钮之间有空隙问题

### ISSUE THREAD

**Issue by moxunbai** [jdf2e/nutui#197]
使用测试的手机为 iPhone 6s  Mac电脑上用Safari浏览器也试过，发现可以通过设置button样式的margin-left:0;margin-right:0;解决

**Comment by richard1015** [comment]
> 使用测试的手机为 iPhone 6s Mac电脑上用Safari浏览器也试过，发现可以通过设置button样式的margin-left:0;margin-right:0;解决

项目一般都有 reset.css 来处理这个问题
