### ISSUE TITLE
微信小程序版本 dialog  teleport

### ISSUE THREAD

**Issue by 939243423** [jdf2e/nutui#1972]
### What problem does this feature solve?（这个功能解决的问题）
解决随时随地可以放置dialog 而不受相同位置dialog影响

### What does the proposed API look like?（期望的 API）
目前小程序版本 dialog 的 teleport属性是不可用的，我希望向vue版本的dialog一样可以支持teleport属性

**Comment by richard1015** [comment]
小程序机制暂时不支持此场景
