### ISSUE TITLE
[bug] Actionsheet 选项太多时候内容展示不全，不能滚动

### ISSUE THREAD

**Issue by lively-qcy** [jdf2e/nutui#198]
## 问题描述

如图，选项过多，不能滚动，遮挡了列表页，实际滚动还是在滚动列表页，内容展示不全

![image](https://user-images.githubusercontent.com/39941460/72133523-9f6fe480-33bc-11ea-8810-15d7316eec3d.png)

## 预期的行为和实际行为
组件可以设置一个高度，进行滚动展示选项，类似省市区的选择

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：11.2
- **NutUI 版本**：2.1.9
- **Vue 版本**：2.6.10
- **引用方式**：  NPM

**Comment by irisSong** [comment]
数据较多的话，可考虑使用Picker组件，
