### ISSUE TITLE
uploader组件增加图片的object-fit

### ISSUE THREAD

**Issue by JuYiYang** [jdf2e/nutui#1983]
### What problem does this feature solve?（这个功能解决的问题）
图片尺寸不相符时可以选择尺寸裁剪模式，而不是直接拉伸

### What does the proposed API look like?（期望的 API）
新增Props:fit
用法
fit:'cover'
实现
object-fit:cover

**Comment by richard1015** [comment]
4.0.1 已解决拉伸问题
