### ISSUE TITLE
tabs切换时，如果swiper也在同时切换，tabs就会卡顿1秒左右

### ISSUE THREAD

**Issue by vvliu** [jdf2e/nutui#1984]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.3.1

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16.0

### Browser and its version（浏览器及其版本）
Chrome 108.0.5359.72

### System and its version（系统及其版本）
win 11

### Taro environmental information（taro 环境信息）
 Taro CLI 3.5.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.17.0 - C:\Program Files\nodejs\npm.CMD

### Steps to reproduce（重现步骤）
swiper 和 tabs同时切换就会卡顿，tabs点击有时1秒左右才切换过来

### What is expected?（期望的结果是什么？）
不卡顿

### What is actually happening?（实际的结果是什么？）
卡顿

**Comment by richard1015** [comment]
辛苦提供一下最小复现链接，   如何同时触发，  混合使用 ，还是 通过事件触发滑动

**Comment by richard1015** [comment]
经排查，开启swiper 自动轮播后会造成 线程阻塞卡顿，暂时可以关闭自动轮播，  或者 tabs 设置 :animated-time="0" 关闭动画
