### ISSUE TITLE
elevator组件吸顶功能错乱，滚动后直接将最后一项的title吸顶了

### ISSUE THREAD

**Issue by 1045598742** [jdf2e/nutui#1991]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.3.1

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.1

### Browser and its version（浏览器及其版本）
chrome 105.0.5195.127

### System and its version（系统及其版本）
windows11

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/nutui3-vite-demo-forked-cr9erp?file=/src/App.vue)

### Steps to reproduce（重现步骤）
vue-cli配合官方demo的代码即可复现

### What is expected?（期望的结果是什么？）
吸顶楼层正常

### What is actually happening?（实际的结果是什么？）
吸顶楼层错乱

**Comment by szg2008** [comment]
上面的例子没有复现，能详细描述下么？或者截图示意下🙏
