### ISSUE TITLE
List虚拟列表的列表项高度height参数目前只能是固定高度，希望支持动态高度

### ISSUE THREAD

**Issue by Jacleklm** [jdf2e/nutui#2004]
### What problem does this feature solve?（这个功能解决的问题）
虚拟列表的列表项动态高度问题。实际应用的时候，当列表项中包含大量文本、图片之类时，列表项的高度其实较难保持为固定

### What does the proposed API look like?（期望的 API）
支持传递类型为数字、数组、函数
  - 可以是一个固定值，如 100，此时列表项是固高的
  - 可以是一个包含所有列表项高度的数据，如 [50, 20, 100, 80, ...]
  - 可以是一个根据列表项索引返回其高度的函数：(index: number): number

**Comment by Jacleklm** [comment]
或者自适应高度更好

**Comment by szg2008** [comment]
这个已有相关issues[#1658](https://github.com/jdf2e/nutui/issues/1658)。
也欢迎pr
