### ISSUE TITLE
Signature签名组件可以新增一个识别是否签名的功能吗？

### ISSUE THREAD

**Issue by PDMoFan** [jdf2e/nutui#2005]
### What problem does this feature solve?（这个功能解决的问题）
用户可能未真实签名直接选择确认，这样生成的签名内容就是空白的，这并不是我们想要的。所以希望可以增加一个识别用户是否有进行过签名（笔画）的操作，只有签名了才允许确认

### What does the proposed API look like?（期望的 API）
希望可以增加一个props属性，标识是否要有签名内容才允许生成图片

**Comment by Ymm0008** [comment]
已优化，本周发版 @PDMoFan 其中v4版本此功能已同步

**Comment by Ymm0008** [comment]
#2061
