### ISSUE TITLE
uploader上传组件is-deletable属性在上传列表展示模式的情况下不生效

### ISSUE THREAD

**Issue by aibayanyu20** [jdf2e/nutui#2006]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.3.1

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.13.1

### Browser and its version（浏览器及其版本）
Chrome(108.0.5359.125)

### System and its version（系统及其版本）
Win11

### Reproduction link（重现链接）
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-a6f2gp?file=src/App.vue)

### Steps to reproduce（重现步骤）
nut-uploader配置list-type属性为list
并设置is-deletable属性为false

### What is expected?（期望的结果是什么？）
期望列表中的删除按钮会被隐藏调

### What is actually happening?（实际的结果是什么？）
实际没有隐藏

**Comment by richard1015** [comment]
v3.3.3 已发布
