### ISSUE TITLE
picker在支付宝小程序无效

### ISSUE THREAD

**Issue by Q-J-Brilliant** [jdf2e/nutui#2007]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.3.2

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:alipay

### Citation method（引用方式）
npm

### Node version（node 版本）
16.13.0

### Browser and its version（浏览器及其版本）
108.0.5359.125

### System and its version（系统及其版本）
windows11

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.10

  Taro CLI 3.5.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Users\qiujiecan\AppData\Roaming\npm\yarn.CMD
      npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/nutui3-vite-demo-forked-5lsihl?file=/src/App.vue)

### Steps to reproduce（重现步骤）
<template>
    <nut-cell title="所在地区" is-link @tap="checkCity"></nut-cell>
    <nut-picker v-model:visible="show" v-model="city" :columns="cityList" title="城市选择" />
</template>

<script setup>
import { ref } from 'vue'

let show = ref(false)
let city = ref(['FuJian', 'FuZhou', 'TaiJiang'])
const cityList = ref([
    {
        text: '浙江',
        value: 'ZheJiang',
        children: [
            {
                text: '杭州',
                value: 'HangZhou',
                children: [
                    { text: '西湖区', value: 'XiHu' },
                    { text: '余杭区', value: 'YuHang' }
                ]
            },
            {
                text: '温州',
                value: 'WenZhou',
                children: [
                    { text: '鹿城区', value: 'LuCheng' },
                    { text: '瓯海区', value: 'OuHai' }
                ]
            }
        ]
    },
    {
        text: '福建',
        value: 'FuJian',
        children: [
            {
                text: '福州',
                value: 'FuZhou',
                children: [
                    { text: '鼓楼区', value: 'GuLou' },
                    { text: '台江区', value: 'TaiJiang' }
                ]
            },
            {
                text: '厦门',
                value: 'XiaMen',
                children: [
                    { text: '思明区', value: 'SiMing' },
                    { text: '海沧区', value: 'HaiCang' }
                ]
            }
        ]
    }
]);

const checkCity = () => {
    show.value = true
}

const change = (e) => {
    console.log(e);
}

### What is expected?（期望的结果是什么？）
可以生效

### What is actually happening?（实际的结果是什么？）
报错
![image](https://user-images.githubusercontent.com/101537665/210547232-453a6e26-a070-4826-9ed1-0b7e9df54cdf.png)

**Comment by Q-J-Brilliant** [comment]
![image](https://user-images.githubusercontent.com/101537665/210547837-678248f9-728b-4820-98ee-720effbcea98.png)
第一次打开会白屏

**Comment by Q-J-Brilliant** [comment]
![image](https://user-images.githubusercontent.com/101537665/210547926-df3b6bee-853a-467a-9448-4046c1d28aa2.png)
用的官方示例

**Comment by Q-J-Brilliant** [comment]
![image](https://user-images.githubusercontent.com/101537665/210547979-2b56d558-c7e8-4616-8ec6-e5533bf84a60.png)
第二次打开就会更改一级选项，二级没有变化，还会报错

**Comment by SnowWind91** [comment]
![image](https://user-images.githubusercontent.com/20529125/211256696-c250b013-5fa1-491b-ba97-ee1fec9fea28.png)
百度小程序也有问题用；样式错位无法正确选择
版本是："@nutui/nutui-taro": "3.3.2",  "@tarojs/cli": "3.5.11",
顶一下

**Comment by emmmm-maker** [comment]
@Q-J-Brilliant 你好，请问解决了吗？

**Comment by yangxiaolu1993** [comment]
你好，NutUI-Taro 中的 Picker 以及 Datepicker  组件，暂时不支持 百度小程序以及支付宝小程序，可暂时使用原生 Picker 组件
