### ISSUE TITLE
input type="textarea"在支付宝小程序无效

### ISSUE THREAD

**Issue by Q-J-Brilliant** [jdf2e/nutui#2008]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.3.2

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:alipay

### Citation method（引用方式）
npm

### Node version（node 版本）
16.13.0

### Browser and its version（浏览器及其版本）
108.0.5359.125

### System and its version（系统及其版本）
windows11

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.11

  Taro CLI 3.5.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Users\qiujiecan\AppData\Roaming\npm\yarn.CMD
      npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/nutui3-vite-demo-forked-tj9uqh?file=/src/App.vue)

### Steps to reproduce（重现步骤）
<nut-input label="文本" type="textarea" show-word-limit rows="2" max-length="50" placeholder="请输入留言" />
![image](https://user-images.githubusercontent.com/101537665/210718311-a12c794d-2c0d-48ef-9ad3-4a983408ee44.png)

### What is expected?（期望的结果是什么？）
生效

### What is actually happening?（实际的结果是什么？）
不生效

**Comment by Q-J-Brilliant** [comment]
![image](https://user-images.githubusercontent.com/101537665/210718350-b567656e-5c7b-46da-a9ae-d79231ac36b5.png)

**Comment by eiinu** [comment]
建议直接使用 TextArea 组件
