### ISSUE TITLE
Uploader上传组件file-list响应丢失，通过置空file-list清空文件列表操作不生效

### ISSUE THREAD

**Issue by iSmilee** [jdf2e/nutui#2014]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.3.2

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.13.1

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.103)

### System and its version（系统及其版本）
Win10

### Reproduction link（重现链接）
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-hpzdxk?file=src%2FApp.vue)

### Steps to reproduce（重现步骤）
nut-uploader 配置list-type为list，上传一个文件后置空file-list

### What is expected?（期望的结果是什么？）
期望file-list实现响应，支持清空、编辑等业务场景

### What is actually happening?（实际的结果是什么？）
置空file-list 未生效，文件列表未发生变化

**Comment by thx125** [comment]
#1875 可以参考这个issue

**Comment by iSmilee** [comment]
> #1875 可以参考这个issue

好的 谢谢
