### ISSUE TITLE
地址选择 picker  自定义数据   数据修改后，选中值没有修改  

### ISSUE THREAD

**Issue by wsxgs** [jdf2e/nutui#202]
示例页面就有这个问题
![image](https://user-images.githubusercontent.com/30249531/74019006-d8a66f00-49d1-11ea-8f40-41f2730d17b5.png)

![image](https://user-images.githubusercontent.com/30249531/74018832-8f561f80-49d1-11ea-97fb-366864cfc82f.png)
想问下怎么触发选中值修改， 以及重新选择省，市和区默认划回第一条数据

**Comment by FatDong1** [comment]
#203 demo示例的问题

**Comment by richard1015** [comment]
最新版已解决 ，感谢 @FatDong1
