### ISSUE TITLE
upload和Avatar 组件需要新增设置 mode 属性

### ISSUE THREAD

**Issue by akFace** [jdf2e/nutui#2026]
## 小程序内设置mode="aspectFill"无效
-  小程序的mode类型参照 [https://developers.weixin.qq.com/miniprogram/dev/component/image.html](https://developers.weixin.qq.com/miniprogram/dev/component/image.html)

### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.3.2

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
window1o

### Reproduction link（重现链接）
[nutui.jd.com/](https://nutui.jd.com/#/zh-cn/component/uploader-taro)

### Steps to reproduce（重现步骤）
```vue
<nut-uploader mode="aspectFill" :url="uploadUrl" v-model:file-list="defaultFileList" maximum="10" multiple list-type='list'>
</nut-uploader>

<nut-avatar
    size="large"
mode="aspectFill"
icon="https://img12.360buyimg.com/imagetools/jfs/t1/143702/31/16654/116794/5fc6f541Edebf8a57/4138097748889987.png"
  ></nut-avatar>
```

### What is expected?（期望的结果是什么？）
```mode="aspectFill" 有效```

### What is actually happening?（实际的结果是什么？）
```mode="aspectFill" 无效```

**Comment by richard1015** [comment]
![image](https://user-images.githubusercontent.com/13060263/216863454-59190245-ba51-48dd-9043-ada7f040d944.png)
