### ISSUE TITLE
Picker增加可搜索功能

### ISSUE THREAD

**Issue by yangjisen** [jdf2e/nutui#2028]
### What problem does this feature solve?（这个功能解决的问题）
因筛选项过多，选择太费劲，增加一个可本地或远程搜索功能

### What does the proposed API look like?（期望的 API）
空

**Comment by thx125** [comment]
可按照业务实际情况，扩展Picker的插槽top（自定义滑动数据顶部区域），添加搜索框进去

**Comment by yangxiaolu1993** [comment]
你好，NutUI4.0 将内置 Popup 去掉，可任意组合使用，更加灵活
