### ISSUE TITLE
示例代码错误

### ISSUE THREAD

**Issue by lovelyqun** [jdf2e/nutui#2038]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.3.2

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
108.0.5359.125（正式版本)

### System and its version（系统及其版本）
win10

### Reproduction link（重现链接）
[codehouse.jd.com/](https://codehouse.jd.com/?source=share&type=vue&mainJs=Ly9pbXBvcnQgVkNvbnNvbGUgZnJvbSAidmPGDyI7Ci8vdmFyIHbIID0gbmV3yS8oKTsKx0J7IGNyZWF0ZUFwcCB9yEd1xELHIcQZxhcuL2FwcC7NHU51dFVJxx9AbnV0dWkvxQbKIsc2c2Nzc8sVzCwvZGlzdC9zdHlsZS7GJukAkihBcHApLnVzZSjFaSkubW91bnQoIiNhcHAiKTs=&appValue=PHRlbXBsYXRlPgogIDxudXQtY2VsbCB0aXRsZT0i5pi+56S65Lit5paHIiA6ZGVzYz0ixAYiIEBjbGljaz0ic2hvdyA9IHRydWUiPjwvyELJT2RhdGVwaWNrZXIKIMUBdi1tb2RlbD0iY3VycmVudERhdGUizhw6dmlzaWLkAIHEXsgdOm1pbsVPPSJtaW7MNzptYXjIGmF4zRppcy3ERC1jaGluZXNlPSLlAKnIHnRocmVlLWRpbWVuc2lvbmFsPSJmYWxzySFAY29uZmlybT0ixwnEGecA5uoA2T4gCjwv6gFICjxzY3JpcHTkAQNpbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnOwogIGV4xR1kZWZhdWx0IHvFdXNldHVwKHByb3BzKccTICBjb25zdCDnAWtyZWYo5QCmKcRFyh/kAZjHHycyMDIy5bm0MDXmnIgxMOaXpSfPLecBQiA9IG5ldyDECygyMDIwLCAwLCAxKSzOLOYBVM8sNSwgMdMt6wHWzzEyLCA0xzTFBO8AkucBYiA9ICh7IHNlbGVjdGVkVmFsdWUsyQ9PcHRpb25zIH0pPT7oARwg5QD5LnbEKiA90CsubWFwKChvxQ0pID0+IMYLLnRleHQpLmpvaW4oJ+oBHH3HCHJldHVybukBfyDsANboAO8g5QGQyg7kAIbKDucBYMsR5gFFyhHnAPDIeuYAg+QAgX07Cjwv6AJDCg==&scssValue=)

### Steps to reproduce（重现步骤）
直接运行报错

### What is expected?（期望的结果是什么？）
正常显示

### What is actually happening?（实际的结果是什么？）
报错

### Remarks（补充说明）
  const minDate = new Date(2020, 0, 1),
  const maxDate = new Date(2025, 10, 1),
  标点符号问题

**Comment by yangxiaolu1993** [comment]
感谢反馈，问题已修复，下个版本发布
