### ISSUE TITLE
nut-collapse 渲染超过200个后极度卡顿，占用JS执行线程

### ISSUE THREAD

**Issue by defaultjacky** [jdf2e/nutui#2041]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.3.1

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.0

### Browser and its version（浏览器及其版本）
微信小程序

### System and its version（系统及其版本）
2.29.0

### Reproduction link（重现链接）
[codepen.io](https://codepen.io/zhenghangjie/pen/abjWbVR)

### Steps to reproduce（重现步骤）
任何形式访问

### What is expected?（期望的结果是什么？）
正常渲染

### What is actually happening?（实际的结果是什么？）
渲染卡顿

**Comment by defaultjacky** [comment]
@Ymm0008 大佬帮忙看看？

**Comment by Ymm0008** [comment]
> @Ymm0008大佬帮忙看？

收到

**Comment by Ymm0008** [comment]
https://github.com/jdf2e/nutui/pull/2061
