### ISSUE TITLE
Dialog和Toast 能提供函数式调用吗?

### ISSUE THREAD

**Issue by g1012415019** [jdf2e/nutui#205]
## 调用Dialog时使用
Dialog.alert({
  title: '标题',
  message: '弹窗内容'
}).then(() => {
  // on close
});
## 调用Toast时使用
Toast.loading({
  message: '加载中...',
  forbidClick: true
});
提供这样类似的函数调用

**Comment by richard1015** [comment]
> ## 调用Dialog时使用
> Dialog.alert({
> title: '标题',
> message: '弹窗内容'
> }).then(() => {
> // on close
> });
> 
> ## 调用Toast时使用
> Toast.loading({
> message: '加载中...',
> forbidClick: true
> });
> 提供这样类似的函数调用



``` javascript
// 全局引入
import { Toast, Dialog } from '@nutui/nutui'
Toast.install(Vue)
Dialog.install(Vue)
// 项目中引用
this.$dialog({
        title: "自定义Dialog标题",
        content: "小屏或移动端浏览效果最佳",
        closeBtn:true,  //显式右上角关闭按钮
        onOkBtn(event) {  //确定按钮点击事件
          alert("okBtn");
          this.close(); //关闭对话框
        },
        onCancelBtn(event) {  //取消按钮点击事件，默认行为关闭对话框
          alert("cancelBtn");
          //return false;  //阻止默认“关闭对话框”的行为
        },
        onCloseBtn(event) { //右上角关闭按钮点击事件
          alert("closeBtn");
          //return false;  //阻止默认“关闭对话框”的行为
        },
        closeCallback(target) {
          alert("will close");  //对话框关闭回调函数，无论通过何种方式关闭都会触发
        }
});
//带文字，自动消失，不要遮罩
this.$toast.loading('加载中...',{ 
    duration:3000,
    cover:false
});
```

**Comment by g1012415019** [comment]
我想在一个类中调用 Toast组件
`import toast from "@/util/toast";

  //通过这种方式把当前页面的vue对象传入进去
 toast.text.call(this, err.msg);
`
所以想问有没有一个Toast的全局对象,通过这个对象来调用

**Comment by kevinlvhsl** [comment]
更何况在vue3中，都不用this了，非得用模板来调用toast 是很麻烦的， 接口出错时提示等场景
