### ISSUE TITLE
toast 吐司

### ISSUE THREAD

**Issue by asasdsad** [jdf2e/nutui#2059]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.0

### Browser and its version（浏览器及其版本）
微信浏览器

### System and its version（系统及其版本）
安卓11

### Reproduction link（重现链接）
[nbjh.taiduyuncang.com](http://nbjh.taiduyuncang.com/watch/code)

### Steps to reproduce（重现步骤）
如果第一次进入  点击吐司图标正常显示的话请刷新一下页面再点击下面的几个显示toast 如果是微信开发者工具 图标则会很大 如果第一次进入正常显示 点击刷新再次点击即可    有特殊要求  必须是打包之后 未打包的不会有次bug

### What is expected?（期望的结果是什么？）
修复bug

### What is actually happening?（实际的结果是什么？）
啊？

**Comment by Drjingfubo** [comment]
你这个是普通h5的吧，怎么还有微信开发者工具？
给个复现仓库吧

**Comment by Drjingfubo** [comment]
把@nutui/icons-vue 依赖升级下    0.0.25
