### ISSUE TITLE
tabs 组件建议支持滚动导航

### ISSUE THREAD

**Issue by juzijun2020** [jdf2e/nutui#2065]
### What problem does this feature solve?（这个功能解决的问题）
在某些场景下，需要点击tab title 滚动到指定位置，不点击tab title 时，滚动屏幕能看到全部 tab content，可参考vant 的 tab 滚动导航：https://vant-contrib.gitee.io/vant/v3/#/zh-CN/tab#gun-dong-dao-hang

### What does the proposed API look like?（期望的 API）
可以参考vant 新增一个 scrollspy 参数

**Comment by richard1015** [comment]
Tabs 不支持该功能，建议使用 sticky 自定义实现
