### ISSUE TITLE
4.0的vue文档标签栏-徽标提示-components后面少了个逗号

### ISSUE THREAD

**Issue by ken-wu-201** [jdf2e/nutui#2069]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(109.0.5414.75)

### System and its version（系统及其版本）
Windows 11

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/tabbar)

### Steps to reproduce（重现步骤）
打开 https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/tabbar
浏览到"徽标提示"的代码部分

### What is expected?（期望的结果是什么？）
//...
<script>
  import { Home,Category,Find,Cart,My} from '@nutui/icons-vue-taro';
  export default{
    components: {Home,Category,Find,Cart, My } //应该有逗号
    setup(){
      return{
        Home,Category,Find,Cart, My
      }
    }
  }
</script>

### What is actually happening?（实际的结果是什么？）
//...
<script>
  import { Home,Category,Find,Cart,My} from '@nutui/icons-vue-taro';
  export default{
    components: {Home,Category,Find,Cart, My } //没有逗号
    setup(){
      return{
        Home,Category,Find,Cart, My
      }
    }
  }
</script>

**Comment by Drjingfubo** [comment]
等待官网发版
