### ISSUE TITLE
Sticky 布局内组件吸顶无效且超出布局

### ISSUE THREAD

**Issue by Ouopoulos** [jdf2e/nutui#2074]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
MacOS(12.4)

### Taro environmental information（taro 环境信息）
Taro v3.5.12

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/sticky)

### Steps to reproduce（重现步骤）
top属性失效 超出布局 可上滑或下拉至布局尽头 可参照文档内的效果

### What is expected?（期望的结果是什么？）
Bug修复

### What is actually happening?（实际的结果是什么？）
Bug修复

**Comment by szg2008** [comment]
例子是对的哈，吸顶相对父级，因为给父级设置了高度

**Comment by SengTime** [comment]
请问你有试过最小复现吗? Sticky会生成等同于窗口高度的一个组件,并且不会有吸顶效果.

**Comment by lihuangshuaige** [comment]
啥意思啊？父级高度，直接把我的页面撑高了啊
