### ISSUE TITLE
Icon中如果写style click失效

### ISSUE THREAD

**Issue by Ouopoulos** [jdf2e/nutui#2075]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
MacOS(12.4)

### Taro environmental information（taro 环境信息）
Taro v3.5.12

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/icon)

### Steps to reproduce（重现步骤）
例: <Photograph size="20" style="right:55px"  @click="handleClick()" />

### What is expected?（期望的结果是什么？）
是否是Bug

### What is actually happening?（实际的结果是什么？）
是否是Bug

**Comment by eiinu** [comment]
改成 `@click="handleClick"` 或者 `@click="handleClick($event)"`
具体参考 [Vue#v-on](https://cn.vuejs.org/api/built-in-directives.html#v-on)
