### ISSUE TITLE
taro版的 InfiniteLoading 滚动加载没有该组件了吗

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui#2076]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.0

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
masos

### Taro environmental information（taro 环境信息）
111

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/infiniteloading)

### Steps to reproduce（重现步骤）
https://nutui.jd.com/taro/vue/4x/#/zh-CN/infiniteloading 打不开

### What is expected?（期望的结果是什么？）
正常打开

### What is actually happening?（实际的结果是什么？）
地址无法打开

**Comment by yanbowe** [comment]
https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/infiniteloading
路径链接错误

**Comment by Drjingfubo** [comment]
不是路径错误，v4版本我们考虑到如果可以直接使用Taro的组件，就不再漏出该组件

**Comment by yanbowe** [comment]
> 

好的，谢谢您
