### ISSUE TITLE
ActionSheet 嵌套 Elevator 报错TypeError: Cannot read property 'height' of undefined 和滚动报错：TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by bcdon** [jdf2e/nutui#2078]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.3.2

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.8.0

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
macos 13

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.6

  Taro CLI 3.5.6 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.6 => 3.5.6 
      @tarojs/components: 3.5.6 => 3.5.6 
      @tarojs/helper: 3.5.6 => 3.5.6 
      @tarojs/plugin-framework-vue3: 3.5.6 => 3.5.6 
      @tarojs/plugin-html: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-alipay: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-jd: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-qq: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-swan: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-tt: 3.5.6 => 3.5.6 
      @tarojs/plugin-platform-weapp: 3.5.6 => 3.5.6 
      @tarojs/router: 3.5.6 => 3.5.6 
      @tarojs/runtime: 3.5.6 => 3.5.6 
      @tarojs/shared: 3.5.6 => 3.5.6 
      @tarojs/taro: 3.5.6 => 3.5.6 
      @tarojs/taro-h5: 3.5.6 => 3.5.6 
      @tarojs/webpack5-runner: 3.5.6 => 3.5.6 
      babel-preset-taro: 3.5.6 => 3.5.6 
      eslint-config-taro: 3.5.6 => 3.5.6 

### Reproduction link（重现链接）
[codepen.io/bcdon/pen/ExpeMRw](https://codepen.io/bcdon/pen/ExpeMRw)

### Steps to reproduce（重现步骤）
加载页面，滚动列表

### What is expected?（期望的结果是什么？）
功能正常，无报错

### What is actually happening?（实际的结果是什么？）
加载页面，控制台报错：TypeError: Cannot read property 'height' of undefined
滚动列表，控制台会报错 TypeError: Cannot read property 'title' of undefined

**Comment by szg2008** [comment]
您好，按照提供的示例，没有复现上面的问题，@nutui/nutui-taro版本，3.3.2。

**Comment by chenchunfeng** [comment]
![image](https://user-images.githubusercontent.com/24191925/219566201-da2a9fb7-fa23-4aa9-8390-7a93d7871d33.png)

![image](https://user-images.githubusercontent.com/24191925/219566991-200b10a8-78be-4d37-bde9-7439dd688ee8.png)
