### ISSUE TITLE
通过ConfigProvider动态改变组件样式无法生效

### ISSUE THREAD

**Issue by emmmm-maker** [jdf2e/nutui#2080]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:alipay

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16.0

### Browser and its version（浏览器及其版本）
Microsoft Edge版本 109.0.1518.49 (正式版本) (x86_64)

### System and its version（系统及其版本）
MacOS13.0

### Taro environmental information（taro 环境信息）
Taro v3.5.12

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/p/sandbox/nutui3-vite-demo-forked-g6koov?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A17%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A17%7D%5D)

### Steps to reproduce（重现步骤）
复制文档ConfigProvider 全局配置组件中的  通过 ConfigProvider 覆盖 代码片段

### What is expected?（期望的结果是什么？）
期望range组件颜色改变

### What is actually happening?（实际的结果是什么？）
range组件颜色没有发生变化

**Comment by Drjingfubo** [comment]
看下你提供的复现链接,请提供正确的复现仓库

**Comment by emmmm-maker** [comment]
@Drjingfubo 复现链接为代码片段

**Comment by emmmm-maker** [comment]
@Drjingfubo 请问是打不开吗？我这边是可以打开的

**Comment by Drjingfubo** [comment]
看下这个demo。我这儿试了是好的 https://github.com/jdf2e/nutui-demo/tree/dev/nutui4-vue/taro

**Comment by emmmm-maker** [comment]
@Drjingfubo 我这边也创建个demo，试了下是可以的，我明天在项目中在试试吧，谢谢解答~
