### ISSUE TITLE
关于4.0的图标名称命名问题，建议使用 xxx-icon 格式

### ISSUE THREAD

**Issue by yunhouhuang** [jdf2e/nutui#2085]
### What problem does this feature solve?（这个功能解决的问题）
现在命名太直接，会和业务有冲突，比如 category 、shop 、order、notice 这种组件出现在 vue标签上很容易误导影响代码阅读，虽然可   as xxx，但是也影响了编码的效率。

### What does the proposed API look like?（期望的 API）
可以加后缀区分组件是icon

**Comment by richard1015** [comment]
这种破坏性变更，等待 4.1.0 高版本变更，小版本暂时挂起
