### ISSUE TITLE
demo中的自定义tabbar在h5下切换卡顿

### ISSUE THREAD

**Issue by laosandegudai** [jdf2e/nutui#2087]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.21.2

### Browser and its version（浏览器及其版本）
Chrome 已是最新版本 版本 109.0.5414.120（正式版本） （64 位

### System and its version（系统及其版本）
Win10

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.11

  Taro CLI 3.5.11 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.21.2 - D:\Apps\node\node.EXE
      Yarn: 1.22.19 - D:\Program Files\nodejs\yarn\bin\yarn.CMD
      npm: 6.14.17 - D:\Apps\node\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/jdf2e/nutui-demo.git)

### Steps to reproduce（重现步骤）
npm run build:weapp -- --watch
在h5下，tabbar切换卡顿，在小程序下无问题

### What is expected?（期望的结果是什么？）
h5下不卡顿

### What is actually happening?（实际的结果是什么？）
h5下卡顿

### Remarks（补充说明）
tabar的使用能够同时兼顾h5和微信小程序，或者说必须分开使用？

**Comment by Drjingfubo** [comment]
https://github.com/jdf2e/nutui-demo/tree/master/tabbar-demo。这个demo 在h5下卡顿？

**Comment by Drjingfubo** [comment]
你提供下demo，你提供的不对
![image](https://user-images.githubusercontent.com/50685476/216278404-bda88dc8-3290-4aa7-813f-139621acdb5f.png)

**Comment by laosandegudai** [comment]
抱歉仓库地址不精确，https://github.com/jdf2e/nutui-demo/tree/master/tabbar-demo,
这个官方例子在微信小程序下是流畅的，但是在h5下有肉眼可见的卡顿（路由和tabbar切换都很快，但是页面内容慢），并且我尝试了使用taroui同样的方式，我发现也是h5页面呈现缓慢而小程序是可以的。我现在不能够确定是否这个示例不能同时兼容h5和小程序。

**Comment by Drjingfubo** [comment]
组件库只能提供样式和切换功能，页面内容慢的话，你可以试下h5跳转的时候不使用switchTab,使用navigateTo看下

**Comment by laosandegudai** [comment]
> 组件库只能提供样式和切换功能，页面内容慢的话，你可以试下h5跳转的时候不使用switchTab,使用navigateTo看下

不行，一样慢。但是我现在怀疑是taro的问题不是UI框架。
