### ISSUE TITLE
List 虚拟列表未设置height，滚动加载有问题

### ISSUE THREAD

**Issue by ZhangRuyi0528** [jdf2e/nutui#2088]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.1

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
macos12.6

### Taro environmental information（taro 环境信息）
Taro v3.5.11

  Taro CLI 3.5.11 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.11 => 3.5.11 
      @tarojs/components: 3.5.11 => 3.5.11 
      @tarojs/helper: 3.5.11 => 3.5.11 
      @tarojs/mini-runner: 3.5.11 => 3.5.11 
      @tarojs/plugin-framework-vue3: 3.5.11 => 3.5.11 
      @tarojs/plugin-html: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-alipay: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-jd: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-qq: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-swan: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-tt: 3.5.11 => 3.5.11 
      @tarojs/plugin-platform-weapp: 3.5.11 => 3.5.11 
      @tarojs/plugin-vue-devtools: ^3.6.0 => 3.6.0 
      @tarojs/router: 3.5.11 => 3.5.11 
      @tarojs/runtime: 3.5.11 => 3.5.11 
      @tarojs/shared: 3.5.11 => 3.5.11 
      @tarojs/taro: 3.5.11 => 3.5.11 
      @tarojs/taro-h5: 3.5.11 => 3.5.11 
      @tarojs/webpack-runner: 3.5.11 => 3.5.11 
      babel-preset-taro: 3.5.11 => 3.5.11 
      eslint-config-taro: 3.5.11 => 3.5.11 

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/list)

### Steps to reproduce（重现步骤）
https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/list

1、不通过传值设置nut-list 的height，而是通过css自定义样式设置自动撑开
2、首次加载正常显示，通过滚动加载触发后，页面空白

解决方式，必须传值设置height！！（限制，切出现区域空白）

### What is expected?（期望的结果是什么？）
滚动加载不空白

### What is actually happening?（实际的结果是什么？）
加载数据正常显示

### Remarks（补充说明）
https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/list

**Comment by a11266897** [comment]
taro v4
infiniteloading的文档空白

https://nutui.jd.com/taro/vue/4x/#/zh-CN/infiniteloading

**Comment by szg2008** [comment]
@a11266897 taro v4 已经删除 infiniteloading 组件，使用原生scroll-view自行实现。
