### ISSUE TITLE
在一个js类中调用 Toast组件,请问一下怎样调用？

### ISSUE THREAD

**Issue by g1012415019** [jdf2e/nutui#209]
//现在是通过这种方式把当前页面的vue对象传入进去
`import toast from "@/util/toast";
toast.text.call(this, err.msg);
`
所以想问有没有一个Toast的全局对象,通过这个对象来调用

**Comment by richard1015** [comment]
> //现在是通过这种方式把当前页面的vue对象传入进去
> `import toast from "@/util/toast"; toast.text.call(this, err.msg); `
> 所以想问有没有一个Toast的全局对象,通过这个对象来调用

``` javascript

import { Toast } from '@nutui/nutui';
 Toast.text('我是toast！');
```

**Comment by kevinlvhsl** [comment]
> > //现在是通过这种方式把当前页面的vue对象传入进去
> > `import toast from "@/util/toast"; toast.text.call(this, err.msg); `
> > 所以想问有没有一个Toast的全局对象,通过这个对象来调用
> 
> ```js
> import { Toast } from '@nutui/nutui';
>  Toast.text('我是toast！');
> ```

@nutui/nutui-taro  小程序中，这样的方式不行
import { Toast } from '@nutui/nutui-taro'
Toast.text('3333')

**Comment by ztrve** [comment]
> Toast.text('3333'

同问

**Comment by ForeverJuvenile** [comment]
使用 微信自有的api  wx.showToast 吧
