### ISSUE TITLE
steps步骤条组件 title文字显示问题

### ISSUE THREAD

**Issue by emmmm-maker** [jdf2e/nutui#2090]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:alipay

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16.0

### Browser and its version（浏览器及其版本）
Microsoft Edge 版本 109.0.1518.70 (正式版本) (64 位)

### System and its version（系统及其版本）
Windows 11 专业版 22H2 
手机系统为IOS 16.1

### Taro environmental information（taro 环境信息）
v3.5.12

### Reproduction link（重现链接）
[github.com](https://github.com/emmmm-maker/nutui4.0test)

### Steps to reproduce（重现步骤）
1.taro init 创建项目选择 nutui4.0模板  编译成支付宝小程序
2.在支付宝开发工具中正常steps 标题能正常显示为一行 
3.通过预览 在手机上查看 标题文字会多行显示
4.将手机锁屏再解锁之后 文字又可以正常一行显示

### What is expected?（期望的结果是什么？）
手机预览第一次看见的标题文字为正常的一行显示

### What is actually happening?（实际的结果是什么？）
手机预览第一次看见的标题文字为多行显示

**Comment by emmmm-maker** [comment]
手机型号为 Iphone 12

**Comment by emmmm-maker** [comment]
@szg2008 请问是否可以重现

**Comment by szg2008** [comment]
是否有截图看看？

**Comment by szg2008** [comment]
我这里没有复现，可以查看下是否样式冲突导致

**Comment by emmmm-maker** [comment]
模拟器截图:<img width="430" alt="image" src="https://user-images.githubusercontent.com/67179703/217738333-d961f112-7e00-42d5-9b84-257188efbced.png">
手机预览截图![image](https://user-images.githubusercontent.com/67179703/217738527-26984bca-2fdd-4d54-9b70-6133beca9ca1.png)
手机锁屏后再解锁后截图![image](https://user-images.githubusercontent.com/67179703/217738675-7b43510b-bbd4-4be1-8400-cd247bb48167.png)

**Comment by emmmm-maker** [comment]
@szg2008 这个是我根据重现链接截图的 并没有写任何样式

**Comment by emmmm-maker** [comment]
@szg2008 我这边看了下 发现苹果手机(使用了12、13)存在这样的问题  安卓手机 我使用小米手机试了就没问题的

**Comment by szg2008** [comment]
自行设置一下标题的宽度

**Comment by emmmm-maker** [comment]
@szg2008 设置标题宽度好像无法居中对齐 我给了个全局样式就可以了 
.nut-step-main {
    width: 70%;
}
