### ISSUE TITLE
4.0版本的vue-cli自动引入无效

### ISSUE THREAD

**Issue by fonghehe** [jdf2e/nutui#2092]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.17.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
MacOS 13.1

### Reproduction link（重现链接）
[github.com](https://github.com/jdf2e/nutui-demo.git)

### Steps to reproduce（重现步骤）
你们自己的示例库都无法实现，4.0版本切换到vue-cli的库

### What is expected?（期望的结果是什么？）
可以自动引入样式文件

### What is actually happening?（实际的结果是什么？）
自动引入无效，样式文件未加载

**Comment by eiinu** [comment]
`@nutui/nutui@4.0.1-beta.2` 已解决这个问题，下个版本会更新，感谢反馈

**Comment by eiinu** [comment]
`@nutui/nutui@4.0.1` 已发布
