### ISSUE TITLE
nutui 4.0 nut-icon引入自定义icon报错

### ISSUE THREAD

**Issue by adonis-lsh** [jdf2e/nutui#2093]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16

### Browser and its version（浏览器及其版本）
106

### System and its version（系统及其版本）
12.6

### Taro environmental information（taro 环境信息）
taro info
👽 Taro v3.5.12

  Taro CLI 3.5.12 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.12 => 3.5.12 
      @tarojs/components: 3.5.12 => 3.5.12 
      @tarojs/helper: 3.5.12 => 3.5.12 
      @tarojs/plugin-framework-vue3: 3.5.12 => 3.5.12 
      @tarojs/plugin-html: 3.5.12 => 3.5.12 
      @tarojs/plugin-platform-weapp: 3.5.12 => 3.5.12 
      @tarojs/router: 3.5.12 => 3.5.12 
      @tarojs/runtime: 3.5.12 => 3.5.12 
      @tarojs/shared: 3.5.12 => 3.5.12 
      @tarojs/taro: 3.5.12 => 3.5.12 
      @tarojs/taro-h5: 3.5.12 => 3.5.12 
      @tarojs/webpack5-runner: 3.5.12 => 3.5.12 
      babel-preset-taro: 3.5.12 => 3.5.12 
      eslint-config-taro: 3.5.12 => 3.5.12 
    npmGlobalPackages:
      typescript: 4.1.5

### Reproduction link（重现链接）
[github.com](https://github.com/jdf2e/nutui-demo/blob/master/vite/src/assets/custom_font/demo.css)

### Steps to reproduce（重现步骤）
可以跑一下官网的引用iconfont的demo,第二种方式,直接就报错了

### What is expected?（期望的结果是什么？）
正常展示icon

### What is actually happening?（实际的结果是什么？）
编译报错:
ERROR in ./node_modules/@nutui/nutui-taro/dist/packages/icon/index.scss (./node_modules/@tarojs/webpack5-runner/node_modules/css-loader/dist/cjs.js??clonedRuleSet-4.use[0]!./node_modules/@tarojs/webpack5-runner/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-5.use[0]!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-7.use[1]!./node_modules/@nutui/nutui-taro/dist/packages/icon/index.scss)
Module build failed (from ./node_modules/@tarojs/webpack5-runner/node_modules/postcss-loader/dist/cjs.js):
Error: Failed to find '@nutui/icons-vue/dist/style_iconfont.css'

**Comment by richard1015** [comment]
参考此解决方案  #2089  ， 先降级Taro 3.5.11  , 测试后 辛苦反馈一下

**Comment by adonis-lsh** [comment]
降级之后不报错了,但是icon还是没有正常展示出来

**Comment by adonis-lsh** [comment]
看了一下应该是input给清除icon的焦点抢跑了

**Comment by richard1015** [comment]
> 降级之后不报错了,但是icon还是没有正常展示出来

辛苦提供一个最小复现git仓库 链接

**Comment by richard1015** [comment]
参考文档
https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/icon

**Comment by Yomaris** [comment]
> > 降级之后不报错了,但是icon还是没有正常展示出来
> 
> 辛苦提供一个最小复现git仓库 链接



> 参考此解决方案 #2089 ， 先降级Taro 3.5.11 , 测试后 辛苦反馈一下

你好，我想问一下@nutui/icons-react-taro引入图标无法显示，需要怎么配置
