### ISSUE TITLE
Popover 气泡弹出框 reference插槽内的元素内容被定位时 Popover显示在元素原位置 无法跟随元素

### ISSUE THREAD

**Issue by emmmm-maker** [jdf2e/nutui#2095]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:alipay

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16.0

### Browser and its version（浏览器及其版本）
Edge版本 109.0.1518.49 (正式版本) (x86_64)

### System and its version（系统及其版本）
MacOs(13.0)

### Taro environmental information（taro 环境信息）
v3.5.12

### Reproduction link（重现链接）
[github.com](https://github.com/emmmm-maker/nutui-test-popover)

### Steps to reproduce（重现步骤）
当 Popover 气泡弹出框 reference插槽内的元素被定位时，Popover 气泡弹出框 弹出框的位置不会跟随元素 而是在元素没被定位时的位置

### What is expected?（期望的结果是什么？）
 Popover 气泡弹出框 reference插槽内的元素被定位时 ，Popover 气泡弹出框可以跟随元素显示在定位后的位置

### What is actually happening?（实际的结果是什么？）
 Popover 气泡弹出框 reference插槽内的元素被定位时 ，Popover 气泡弹出框显示在元素未定位之前的位置

**Comment by yangxiaolu1993** [comment]
首先感谢您对NutUI的支持，Popover 是通过 getBoundingClientRect() 获取元素的位置信息，reference插槽内的元素内容最外层的对象不建议设置 margin、padding、定位，若设置建议在引用该组件前进行设置
