### ISSUE TITLE
从nutui-taro 3.3.2版本起，Tabs组件选项卡标题在小程序中排版错位

### ISSUE THREAD

**Issue by ggpcn** [jdf2e/nutui#2099]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.3.2

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:qq

### Citation method（引用方式）
npm

### Node version（node 版本）
16.19.0

### Browser and its version（浏览器及其版本）
QQ小程序

### System and its version（系统及其版本）
iOS和Android

### Taro environmental information（taro 环境信息）
Taro CLI 3.6.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.19.0 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - D:\nodejs\node_global\yarn.CMD
      npm: 9.4.1 - D:\nodejs\npm.CMD

### Reproduction link（重现链接）
[nutui.jd.com/3x/](https://nutui.jd.com/3x/#/zh-CN/component/tabs)

### Steps to reproduce（重现步骤）
官方的演示代码即可复现。

### What is expected?（期望的结果是什么？）
期望修复Tabs选项卡标题的问题，能够正常显示。

### What is actually happening?（实际的结果是什么？）
3.3.1版本是正常的，3.3.2和3.3.3均不正常（Tabs的标题，会一行一个，而不是并列）。
同时测试了4.0.1-beta3也不正常。

**Comment by Drjingfubo** [comment]
![image](https://user-images.githubusercontent.com/50685476/217989805-da72b344-2b79-489b-940b-1cc95f6505e6.png)
没懂啥意思，能描述的详细一点

**Comment by ggpcn** [comment]
> ![image](https://user-images.githubusercontent.com/50685476/217989805-da72b344-2b79-489b-940b-1cc95f6505e6.png) 没懂啥意思，能描述的详细一点

使用nutui-taro 3.3.3的效果（不正常）：
![3 3 3](https://user-images.githubusercontent.com/37258035/217998338-4bb3cf3b-cb72-40ef-803f-13100e5cdfdb.png)
==============================
使用nutui-taro 3.3.1的效果（正常）：
![image](https://user-images.githubusercontent.com/37258035/217998465-2d0da7a1-1f19-446a-94b8-76baaf466cee.png)

**Comment by Drjingfubo** [comment]
建议先回退到3.3.1版本，目前排查到问题是因为qq小程序中使用scroll-view标签flex布局会失效，改动需要动整体布局，需要等等。目前组件库主要适配的是微信，支付宝和京东小程序，其他的小程序没有系统测试过。

**Comment by Drjingfubo** [comment]
v3版本已修复该问题
