### ISSUE TITLE
ShortPassword居中短密码输入框溢出

### ISSUE THREAD

**Issue by suguoyao** [jdf2e/nutui#21]
在小屏幕下，如iphone4，居中短密码弹窗中的输入框超出弹窗外了。
![image](https://user-images.githubusercontent.com/16471605/54035892-52980c00-41f5-11e9-826d-9c24bc455db4.png)

官网对应demo链接：https://nutui.jd.com/demo.html#/ShortPassword

**Comment by Franslee** [comment]
感谢反馈

**Comment by Franslee** [comment]
已修复，感谢

**Comment by suguoyao** [comment]
@Franslee Thanks
