### ISSUE TITLE
[bug]Dialog组件过渡动画失效

### ISSUE THREAD

**Issue by richard1015** [jdf2e/nutui#210]
## 问题描述

http://nutui.jd.com/demo.html#/Dialog
dialog 在ios 13.3 chrome 打开时，过渡动画失效

## 相关环境信息
- **操作系统**：ios 13.3
- **NutUI 版本**：2.2.0
- **引用方式**：  NPM

**Comment by guoxiao158** [comment]
一下是我的操作系统，目前在13.3.1的谷歌浏览器上暂无发现该bug，希望提供更详细的数据，谢谢

感谢使用nutui.

![微信图片_20200330152855](https://user-images.githubusercontent.com/23353280/77886606-c216e880-729b-11ea-9867-35513461662e.jpg)
