### ISSUE TITLE
小程序输入框清除按钮 不正常

### ISSUE THREAD

**Issue by adonis-lsh** [jdf2e/nutui#2100]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18

### Browser and its version（浏览器及其版本）
106

### System and its version（系统及其版本）
12.6

### Taro environmental information（taro 环境信息）
taro info
👽 Taro v3.5.12

Taro CLI 3.5.12 environment info:
System:
OS: macOS 12.3
Shell: 5.8 - /bin/zsh
Binaries:
Node: 16.17.0 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 8.15.0 - /usr/local/bin/npm
npmPackages:
@tarojs/cli: 3.5.12 => 3.5.12
@tarojs/components: 3.5.12 => 3.5.12
@tarojs/helper: 3.5.12 => 3.5.12
@tarojs/plugin-framework-vue3: 3.5.12 => 3.5.12
@tarojs/plugin-html: 3.5.12 => 3.5.12
@tarojs/plugin-platform-weapp: 3.5.12 => 3.5.12
@tarojs/router: 3.5.12 => 3.5.12
@tarojs/runtime: 3.5.12 => 3.5.12
@tarojs/shared: 3.5.12 => 3.5.12
@tarojs/taro: 3.5.12 => 3.5.12
@tarojs/taro-h5: 3.5.12 => 3.5.12
@tarojs/webpack5-runner: 3.5.12 => 3.5.12
babel-preset-taro: 3.5.12 => 3.5.12
eslint-config-taro: 3.5.12 => 3.5.12
npmGlobalPackages:
typescript: 4.1.5

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/guide/intro)

### Steps to reproduce（重现步骤）
1. 官网上网提供的demo清除按钮就有问题

### What is expected?（期望的结果是什么？）
正常清除文本

### What is actually happening?（实际的结果是什么？）
没有生效

### Remarks（补充说明）
下面是我手机的录屏,可以100%复现

http://img.bendaidai.top/222_1675872008.mp4

**Comment by adonis-lsh** [comment]
4.0和3.0的UI库都有问题

**Comment by lkjh3214** [comment]
> 4.0和3.0的UI库都有问题

请问手机录屏中的项目，是通过微信开发工具dev:weapp启动，然后进行的预览么？

**Comment by ggpcn** [comment]
> 

嗯，和你一样的问题，我测试了SearchBar 搜索栏的输入框，点击清除按钮无效。

**Comment by adonis-lsh** [comment]
> > 4.0和3.0的UI库都有问题
> 
> 请问手机录屏中的项目，是通过微信开发工具dev:weapp启动，然后进行的预览么？

这个是
<img width="237" alt="image" src="https://user-images.githubusercontent.com/20501172/218103581-d6fe7d0a-42cd-47e0-ace2-565f644e598f.png">
官网上面挂的demo小程序啊

**Comment by adonis-lsh** [comment]
实际项目中 通过微信开发工具dev:weapp启动，然后进行预览 也是不行的

**Comment by lkjh3214** [comment]
> 

请问预览使用的手机型号，与手机系统版本是多少

**Comment by adonis-lsh** [comment]
![image](https://user-images.githubusercontent.com/20501172/218402487-0b1858c4-24b5-4b4a-bbf4-79b8c318266f.png)
![image](https://user-images.githubusercontent.com/20501172/218402510-e322e2c0-d968-4724-b703-21453a5e21f4.png)

**Comment by lkjh3214** [comment]
> 实际项目中 通过微信开发工具dev:weapp启动，然后进行预览 也是不行的

![image](https://user-images.githubusercontent.com/23164467/218408755-5263e771-931d-45e8-b3d9-a218326aa718.png)

**Comment by adonis-lsh** [comment]
点击的事清除按钮,不是点击的空白,我曾尝试给input通过margin让它远离清除按钮,但是发现还是不行,说明并不是点击到input上面导致的

**Comment by adonis-lsh** [comment]
> > 实际项目中 通过微信开发工具dev:weapp启动，然后进行预览 也是不行的
> 
> ![image](https://user-images.githubusercontent.com/23164467/218408755-5263e771-931d-45e8-b3d9-a218326aa718.png)
点击的事清除按钮,不是点击的空白,我曾尝试给input通过margin让它远离清除按钮,但是发现还是不行,说明并不是点击到input上面导致的

**Comment by lkjh3214** [comment]
> > > 实际项目中 通过微信开发工具dev:weapp启动，然后进行预览 也是不行的
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/23164467/218408755-5263e771-931d-45e8-b3d9-a218326aa718.png)
> > 点击的事清除按钮,不是点击的空白,我曾尝试给input通过margin让它远离清除按钮,但是发现还是不行,说明并不是点击到input上面导致的

通过云端测试机，与真机测试，可能是图标比较小。点不到[捂脸]。可以尝试自定义一个比较大的图标试一下。 
后续会添加一个参数，设置 清除按钮的 展示时机，可以在未聚焦的时候 展示 清除按钮

**Comment by daofeng-1998** [comment]
> > > > 实际项目中 通过微信开发工具dev:weapp启动，然后进行预览 也是不行的
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/23164467/218408755-5263e771-931d-45e8-b3d9-a218326aa718.png)
> > > 点击的事清除按钮,不是点击的空白,我曾尝试给input通过margin让它远离清除按钮,但是发现还是不行,说明并不是点击到input上面导致的
> 
> 通过云端测试机，与真机测试，可能是图标比较小。点不到[捂脸]。可以尝试自定义一个比较大的图标试一下。 后续会添加一个参数，设置 清除按钮的 展示时机，可以在未聚焦的时候 展示 清除按钮

把可点击区域放大一点就行了，小程序上这种小按钮贼难点

**Comment by eiinu** [comment]
`4.0.4`
