### ISSUE TITLE
Navbar底部留有空白区域

### ISSUE THREAD

**Issue by Ouopoulos** [jdf2e/nutui#2109]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.1

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
MacOS(12.4)

### Taro environmental information（taro 环境信息）
Taro v3.5.12

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/navbar)

### Steps to reproduce（重现步骤）

        <nut-navbar
            :fixed="true"
            :border="false"
            :placeholder="true"
            :safe-area-inset-top="true"
            title="首页"
            :style="styleObject"
        >
            <template #left>
                <Dongdong @click="handleClick" size="16"></Dongdong>
            </template>
        </nut-navbar>

        <Dongdong @click="handleClick" size="16"></Dongdong>

### What is expected?（期望的结果是什么？）
什么原因造成的

### What is actually happening?（实际的结果是什么？）
什么原因造成的

**Comment by eiinu** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/44915689/218382957-26b6b9a7-d6e8-4533-8006-cc2cdf2437ef.png">
Navbar 组件默认会有 20px 的下外边距，可以通过 ConfigProvider 组件或者 CSS 选择器覆盖掉该样式变量

**Comment by Ouopoulos** [comment]
这个解决方案我很早就试过了,并不是这个原因导致的.
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/52897984/218401484-b23e9f16-e924-40aa-8448-bb2f08a06efe.png">

**Comment by eiinu** [comment]
> 这个解决方案我很早就试过了,并不是这个原因导致的. <img alt="image" width="1188" src="https://user-images.githubusercontent.com/52897984/218401484-b23e9f16-e924-40aa-8448-bb2f08a06efe.png">

图上这个宽度是 box-shadow，如果想要去除，需要将 box-shadow 置为 `none`，同时将 `.nut-navbar--placeholder` 的 display 设置为 `block`。后续会对这个问题进行优化，用更友好的方式实现 box-shadow 的去除。感谢反馈！
