### ISSUE TITLE
datepicker 在电脑端的模式下无法进行使用

### ISSUE THREAD

**Issue by samchenws** [jdf2e/nutui#2112]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.1

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
谷歌

### System and its version（系统及其版本）
windows

### Reproduction link（重现链接）
[nutui.jd.com/4x/demo.html](https://nutui.jd.com/4x/demo.html#/datepicker)

### Steps to reproduce（重现步骤）
用nutui开发的程序，在微信电脑端打开网页datepicker 完全失灵

### What is expected?（期望的结果是什么？）
在微信电脑端打开网页datepicker 可以进行点击或者滑动

### What is actually happening?（实际的结果是什么？）
完全失灵

### Remarks（补充说明）
希望能兼容下，比较在电脑面前和多人都习惯直接用电脑打开

**Comment by eiinu** [comment]
可以自行引入 [hammerjs/touchemulator](https://github.com/hammerjs/touchemulator) 解决这个问题。
一种更简单的方法是，将 [touchEmulator.js](https://github.com/jdf2e/nutui/blob/v4/src/packages/utils/touchEmulator.js) 整个文件代码拷贝至项目中，并在项目入口中引入它。

**Comment by samchenws** [comment]
ok，thank you
