### ISSUE TITLE
Signature 签名组件4.0.1版本更新触发clear事件逻辑错误

### ISSUE THREAD

**Issue by Spectature** [jdf2e/nutui#2116]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.1

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
windows11

### Reproduction link（重现链接）
[nutui.jd.com/h5/vue/4x/](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/signature)

### Steps to reproduce（重现步骤）
1.签字 2.点击确认

### What is expected?（期望的结果是什么？）
签字的内容应该显示在demo下方

### What is actually happening?（实际的结果是什么？）
签字的内容未显示在demo下方

### Remarks（补充说明）
看4.0.1更新后源码里面 clear方法呗放到了confirm事件之后，这样一定会导致生成的img被示例里面的清除方法清除掉

**Comment by Ymm0008** [comment]
https://github.com/jdf2e/nutui/commit/2c9fdbefcdb06cd78cd5724e10898f93a389c92e 已修复，不再自动执行 clear 方法。
后期迭代，会把操作按钮暴露在外面，用户可自定义设置，根据需求调用回调函数。

@Spectature
