### ISSUE TITLE
avatar组件不支持动态设置default slot中img的src

### ISSUE THREAD

**Issue by PurpleForever** [jdf2e/nutui#2118]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.1

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16

### Browser and its version（浏览器及其版本）
微信小程序调试工具

### System and its version（系统及其版本）
Win11

### Taro environmental information（taro 环境信息）
无需

### Reproduction link（重现链接）
[http://nothing.com/](http://nothing.com)

### Steps to reproduce（重现步骤）
` <nut-avatar size="large">
          <img :src="userInfo.headImageUrl" />
  </nut-avatar>

<script setup>
const userInfo = reactive({headImageUrl:null})
userInfo.headImageUrl = "https://img12.360buyimg.com/imagetools/jfs/t1/196430/38/8105/14329/60c806a4Ed506298a/e6de9fb7b8490f38.png"
</script>
`
### What is expected?（期望的结果是什么？）
src被更新，显示用户头像

### What is actually happening?（实际的结果是什么？）
调试工具中查看，无src属性

**Comment by eiinu** [comment]
实测可以修改。

**Comment by eiinu** [comment]
实测没有问题。
猜测你那边失败的原因：
Taro 版本过低，Taro 插件对于 HTML 中 img 的映射存在 bug：https://github.com/NervJS/taro/issues/12673
两种解决方案：
1、升级 Taro 版本，至少为 3.5.8
2、直接把 img 标签改成 Taro 不经过转换就能支持的 image 标签

**Comment by PurpleForever** [comment]
> 实测没有问题。 猜测你那边失败的原因： Taro 版本过低，Taro 插件对于 HTML 中 img 的映射存在 bug：[NervJS/taro#12673](https://github.com/NervJS/taro/issues/12673) 两种解决方案： 1、升级 Taro 版本，至少为 3.5.8 2、直接把 img 标签改成 Taro 不经过转换就能支持的 image 标签

确实是Taro版本问题，升级为3.6.1后功能正常。
