### ISSUE TITLE
 uploader组件 小程序原生api wx.chooseImage不支持上传视频，需要更新为wx.chooseMedia才支持上传

### ISSUE THREAD

**Issue by yongqcai** [jdf2e/nutui#2119]
### What problem does this feature solve?（这个功能解决的问题）
uploader组件在小程序环境中可以支持上传视频/图片

### What does the proposed API look like?（期望的 API）
 uploader组件源代码中，判断env是小程序，使用新api wx.chooseMedia替换wx.chooseImage

**Comment by richard1015** [comment]
您当前用的是4.x还是3.x
