### ISSUE TITLE
小程序打包prebundle多出了一个.wxss文件

### ISSUE THREAD

**Issue by lczc** [jdf2e/nutui#2124]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.1

### Vue version（vue 版本）
3.2.24

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.12.0

### Browser and its version（浏览器及其版本）
微信小程序

### System and its version（系统及其版本）
window10

### Taro environmental information（taro 环境信息）
  Taro CLI 3.4.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.5.0 - D:\node.EXE
      Yarn: 1.22.11 - C:\Users\HLX\AppData\Roaming\npm\yarn.CMD
      npm: 7.22.0 - D:\npm.CMD

### Reproduction link（重现链接）
[github.com/lczc/nutui-lzc](https://github.com/lczc/nutui-lzc)

### Steps to reproduce（重现步骤）
1.yarn dev:weapp
2.使用微信开发者工具打开/dist/weapp文件 

### What is expected?（期望的结果是什么？）
小程序正常打开

### What is actually happening?（实际的结果是什么？）
prebundle多出一个vendors-node_modules_taro_weapp_prebundle_nutui_icons-vue-taro_js.wxss文件导致小程序编译报错

**Comment by richard1015** [comment]
taro config index.js 这样配置一下
```
  compiler: {
    type: 'webpack5',
    prebundle: { enable: false }
  }, 
```
