### ISSUE TITLE
inputNumber组件插槽失效

### ISSUE THREAD

**Issue by Spectature** [jdf2e/nutui#2125]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.1

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
windows

### Reproduction link（重现链接）
[nutui.jd.com/h5/vue/4x/](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/inputnumber)

### Steps to reproduce（重现步骤）
使用自定义图标插槽

### What is expected?（期望的结果是什么？）
插槽可以显示出自定义图标

### What is actually happening?（实际的结果是什么？）
插槽不能显示出自定义图标

**Comment by Drjingfubo** [comment]
<template #left-icon>
          <Left />
   </template>
   <template #right-icon>
          <Right />
    </template>
文档有误哈，插槽名称修改一下 leftIcon -> left-icon
