### ISSUE TITLE
datepicker的滚动问题

### ISSUE THREAD

**Issue by Zeppo241** [jdf2e/nutui#2127]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.3.4

### Vue version（vue 版本）
3.2.6

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chorme(106.0.5249.119)

### System and its version（系统及其版本）
Window10.0

### Taro environmental information（taro 环境信息）
Taro v3.4.10

### Reproduction link（重现链接）
[codehouse.jd.com/](https://codehouse.jd.com/?source=share&type=vue&mainJs=Ly9pbXBvcnQgVkNvbnNvbGUgZnJvbSAidmPGDyI7Ci8vdmFyIHbIID0gbmV3yS8oKTsKx0J7IGNyZWF0ZUFwcCB9yEd1xELHIcQZxhcuL2FwcC7NHU51dFVJxx9AbnV0dWkvxQbKIsc2c2Nzc8sVzCwvZGlzdC9zdHlsZS7GJukAkihBcHApLnVzZSjFaSkubW91bnQoIiNhcHAiKTs=&appValue=PHRlbXBsYXRlPgogIDxudXQtY2VsbCB0aXRsZT0i5pi+56S65Lit5paHIiA6ZGVzYz0ixAYiIEBjbGljaz0ic2hvdyA9IHRydWUiPjwvyELJT2RhdGVwaWNrZXIKIMUBdi1tb2RlbD0iY3VycmVudERhdGUizhw6dmlzaWLkAIHEXsgdOm1pbsVPPSJtaW7MNzptYXjIGmF4zRppcy3ERC1jaGluZXNlPSLlAKnIHnRocmVlLWRpbWVuc2lvbmFsPSJmYWxzySFAY29uZmlybT0ixwnEGecA5uoA2T4gCjwv6gFICjxzY3JpcHTkAQNpbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnOwogIGV4xR1kZWZhdWx0IHvFdXNldHVwKHByb3BzKccTICBjb25zdCDnAWtyZWYo5QCmKcRFyh/kAZjHHycyMDIy5bm0MDXmnIgxMOaXpSfPLecBQiA9IG5ldyDECygyMDIwLCAwLCAxKSzOLOYBVM8sNSwgMdMt6wHWzzEyLCA0xzTFBO8AkucBYiA9ICh7IHNlbGVjdGVkVmFsdWUsyQ9PcHRpb25zIH0pPT7oARwg5QD5LnbEKiA90CsubWFwKChvxQ0pID0+IMYLLnRleHQpLmpvaW4oJ+oBHH3HCHJldHVybukBfyDsANboAO8g5QGQyg7kAIbKDucBYMsR5gFFyhHnAPDIeuYAg+QAgX07Cjwv6AJDCg==&scssValue=)

### Steps to reproduce（重现步骤）
将v-model绑定的值以及min-date均设为当前时间new Date(),例如：
<nut-datepicker v-model="date" v-model:visible="isVisible" :min-date="new Date()" />
 <nut-button class="form__btn" type="primary" @click="isVisible = true">
           点击
 </nut-button>

const date = ref(new Date())
const isVisible = ref(false)，
之后，滚动选择器第二列的月份

### What is expected?（期望的结果是什么？）
只变动月份一列，其他两列不变

### What is actually happening?（实际的结果是什么？）
第三列的日期变为01，且点击确定后返回的日期为当前日期

**Comment by eiinu** [comment]
该问题将被关闭，并重定位至 Picker 相关的新 Issue #2219
