### ISSUE TITLE
uploader丧失效应式： 通过 ref 执行   uploadFile.value.clearUploadQueue();确实清空了，重新直接赋初始值无法显示

### ISSUE THREAD

**Issue by xyw1229** [jdf2e/nutui#2128]
报错后 通过 ref 执行   uploadFile.value.clearUploadQueue();

_Originally posted by @richard1015 in https://github.com/jdf2e/nutui/issues/1875#issuecomment-1354365196_
            
>> 通过这种方式直接清空是可以了。。清空之后，直接赋初始值无法显示

**Comment by richard1015** [comment]
检测一下重新赋值的方式

**Comment by xyw1229** [comment]
我自己改了下源码 监听了对应传入的属性 这样的话 无论传入空 还是传入其它值都没问题。。也不用调clearUploadQueue()这个方法删除了
