### ISSUE TITLE
在自定义tabbar中使用IconFont组件，再在其他页面中使用其他组件后IconFont图标不显示

### ISSUE THREAD

**Issue by allendevx** [jdf2e/nutui#2138]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.1

### Browser and its version（浏览器及其版本）
Chrome(110.0.5481.105)

### System and its version（系统及其版本）
Windows10

### Reproduction link（重现链接）
[github.com](https://github.com/WuWenL0/dream-diary)

### Steps to reproduce（重现步骤）
注释掉pages/index/index中的nut相关组件代码，custom-tab-bar中iconfont就正常显示

### What is expected?（期望的结果是什么？）
在使用nut组件时不影响自定义导航中的图标正常显示

### What is actually happening?（实际的结果是什么？）
在使用nut组件时不影响自定义导航中的图标不正常显示

**Comment by eiinu** [comment]
Taro 下自定义 tabBar 默认存在样式隔离，无法引用到全局样式中的字体文件，需要手动配置：
```
<script>
  export default {
    options: {
      addGlobalClass: true,
    },
  }
</script>
```
相关 issue：https://github.com/NervJS/taro/issues/11060
Taro 文档：https://docs.taro.zone/docs/custom-tabbar

**Comment by allendevx** [comment]
好的，多谢
