### ISSUE TITLE
Elevator 在 Popup 组件里嵌套时索引能正常使用

### ISSUE THREAD

**Issue by lw-742787938** [jdf2e/nutui#2139]
### What problem does this feature solve?（这个功能解决的问题）
Elevator 在 Popup 组件里嵌套时索引不能正常使用，滑动时索引无变化，点击索引时一直定位第一个索引

### What does the proposed API look like?（期望的 API）
解决Elevator 在 Popup 组件里嵌套时索引能正常使用

**Comment by szg2008** [comment]
提供下可复现代码和环境，🙏

**Comment by ANCB520** [comment]
我也遇到了
![image](https://github.com/jdf2e/nutui/assets/23068266/1d635850-07b9-400d-a1bf-ddf5c3e3595f)
放置到van-checkbox-group中就会有这个错误

**Comment by ANCB520** [comment]
![image](https://github.com/jdf2e/nutui/assets/23068266/848ef6f5-34d4-43a4-8beb-0b132bf577ce)
我也遇到了,放置到nut-checkbox-group下就会出现这个错误

**Comment by ANCB520** [comment]
![Uploading image.png…]()
我也遇到这个错误

**Comment by ANCB520** [comment]
![image](https://github.com/jdf2e/nutui/assets/23068266/54d15574-c932-47e1-814d-63ccc2e7b0d9)
我也遇到了这个错误,不知道是啥原因
