### ISSUE TITLE
Popup组件在refresherEnabled为true的Scroll-View中显示错误

### ISSUE THREAD

**Issue by 649683137** [jdf2e/nutui#2140]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.2.7

### Vue version（vue 版本）
3.2.31

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
14.17.0

### Browser and its version（浏览器及其版本）
Chrome(110.0.5481.100)

### System and its version（系统及其版本）
MacOS(11.2.3 )

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.7

  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    npmPackages:
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/extend: 3.5.7 => 3.5.7 
      @tarojs/mini-runner: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-vue3: 3.5.7 => 3.5.7 
      @tarojs/plugin-html: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/webpack-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/festive-poincare-hx9pu8?file=/src/App.vue)

### Steps to reproduce（重现步骤）
抱歉重现仓库还未调试好，重现页面代码如下
在上述依赖环境中建立复现页面
往下滑动后唤出Popup，定位出现错误
```html
<template>
  <view class="body-div">
    <view
      style="
        position: fixed;
        left: 0;
        top: 30px;
        background-color: yellow;
        z-index: 1;
      "
      @tap="show = !show"
      >切换show</view
    >
    <scroll-view
      class="scroll-view-container"
      :scroll-y="true"
      :refresher-enabled="true"
    >
      <view class="scroll-view-content">
        <view class="block"> </view>
        <view class="block"> </view>
        <view class="block"> </view>
        <nut-popup
          position="bottom"
          :style="{ height: '600px' }"
          :round="true"
          :destroy-on-close="false"
          v-model:visible="show"
          :catch-move="true"
        >
          <view>弹窗</view>
          <view style="height: 400px; background-color: red"></view>
        </nut-popup>
      </view>
    </scroll-view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
const show = ref(false)
</script>

<style lang="scss" module>
.scroll-view-container {
  height: 100vh;
  .scroll-view-content {
    .block {
      height: 500px;
      &:nth-child(1) {
        background-color: #ccc;
      }
      &:nth-child(2) {
        background-color: #aaa;
      }
      &:nth-child(3) {
        background-color: #666;
      }
    }
  }
}
</style>

```

### What is expected?（期望的结果是什么？）
定位出现问题

### What is actually happening?（实际的结果是什么？）
定位符合预期

**Comment by szg2008** [comment]
Popup不支持放在scroll-view中使用，建议把它拿出来
