### ISSUE TITLE
Collapse 折叠面板组件支持自定义图标插槽

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui#2141]
### What problem does this feature solve?（这个功能解决的问题）
有时项目里面或许会有UI制作的SVG图标，@nutui/icons-vue包里并没有的图标，这时候就没办法使用了

### What does the proposed API look like?（期望的 API）
slot="icon", 增加插槽并不只局限于Collapse组件，可能还有其他组件的图标也希望支持完全自定义

**Comment by eiinu** [comment]
当前 collapse-item 的 icon 属性支持传入 h 渲染函数
```vue
<template>
  <nut-collapse>
    <nut-collapse-item :icon="svgImg">
    </nut-collapse-item>
  </nut-collapse>
</template>
<script setup lang="ts">
import { h } from 'vue'
import Img from './pic.svg'
const svgImg = h('img', {
  src: Img,
  width: 20,
  height: 20
})
</script>
```

**Comment by yanbowe** [comment]
> 当前 collapse-item 的 icon 属性支持传入 h 渲染函数
> 
> ```
> <template>
>   <nut-collapse>
>     <nut-collapse-item :icon="svgImg">
>     </nut-collapse-item>
>   </nut-collapse>
> </template>
> <script setup lang="ts">
> import { h } from 'vue'
> import Img from './pic.svg'
> const svgImg = h('img', {
>   src: Img,
>   width: 20,
>   height: 20
> })
> </script>
> ```

收到，感谢
