### ISSUE TITLE
nut-datepicker 快速滑动无法正常选中

### ISSUE THREAD

**Issue by chenly3300** [jdf2e/nutui#2142]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

3.3.5

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
小程序

### System and its version（系统及其版本）
小程序

### Taro environmental information（taro 环境信息）
aro CLI 3.5.6 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.2 - D:\Develop\nodejs\node.EXE
      Yarn: 1.22.18 - D:\Develop\nodejs\node_global\yarn.CMD
      npm: 8.5.0 - D:\Develop\nodejs\npm.CMD

### Reproduction link（重现链接）
[https://github.com/](https://github.com/)

### Steps to reproduce（重现步骤）
在快速滑动的过程中 无法选中正常的日期

### What is expected?（期望的结果是什么？）
选中正常的日期

### What is actually happening?（实际的结果是什么？）
无法选中正常的日期

### Remarks（补充说明）
无法选中正常的日期

**Comment by eiinu** [comment]
`3.3.7-beta.2`
