### ISSUE TITLE
v4.0.2小程序版本Picker滚动选择值后快速点击“确定”获取到的值不是最新值，有延时。

### ISSUE THREAD

**Issue by troublezzb** [jdf2e/nutui#2143]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.0

### Browser and its version（浏览器及其版本）
微信开发者工具1.06.2301160

### System and its version（系统及其版本）
win11

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.2

  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - C:\GreenSoft\nodejs\node.EXE
      npm: 9.4.0 - C:\GreenSoft\nodejs\npm.CMD

### Reproduction link（重现链接）
[https://github.com/](https://github.com/)

### Steps to reproduce（重现步骤）
```js
<nut-popup position="bottom" v-model:visible="state.showDatePicker">
  <nut-date-picker
    type="year-month"
    v-model="pickedRange[0]"
    :min-date="minDate"
    :max-date="maxDate"
    @confirm="popupConfirm"
    @cancel="state.showDatePicker=false"
    :is-show-chinese="true"
  >
  </nut-date-picker>
</nut-popup>
```

### What is expected?（期望的结果是什么？）
滚动选择值后快速点击“确定”获取到最新值

### What is actually happening?（实际的结果是什么？）
滚动选择值后快速点击“确定”无法获取到最新值

### Remarks（补充说明）
1、点击“确定”时，picker-view的onChange事件还没执行。
2、据悉v3.2.2已修复。

**Comment by hong-q** [comment]
同问题，请问解决了吗

**Comment by Xhyen** [comment]
打开弹窗直接点确定拿到是一个[undefined]数组

**Comment by eiinu** [comment]
`4.0.4` 已增加 `immediate-change: true`
