### ISSUE TITLE
[input] 结合dialog使用时，首次打开dialog，input不显示

### ISSUE THREAD

**Issue by thx125** [jdf2e/nutui#2144]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
v19.3.0

### Browser and its version（浏览器及其版本）
Chrome(110.0.5481.100)

### System and its version（系统及其版本）
MacOs(13.2.1)

### Steps to reproduce（重现步骤）
``` html
<nut-dialog
    teleport="#app"
    :lock-scroll="true"
    title="登 录"
    v-model:visible="state.loginPopup"
    ok-text="登 录"
    @cancel="onCancel"
    @ok="doLogin"
  >
    <nut-form style="height: 100px">
      <nut-form-item label="账号" label-width="40px">
        <nut-input placeholder="请输入账号" v-model="loginParam.account" :border="false" />
      </nut-form-item>
      <nut-form-item label="密码" label-width="40px">
        <nut-input
          placeholder="请输入密码"
          v-model="loginParam.password"
          type="password"
          :border="false"
        />
      </nut-form-item>
    </nut-form>
  </nut-dialog>
```

### What is expected?（期望的结果是什么？）
input不受外层结构影响

### What is actually happening?（实际的结果是什么？）
input不受外层结构影响

**Comment by jsczxyt** [comment]
ActionSheet中放置form存在同样的问题

**Comment by yangjisen** [comment]
#2170 nut-popup 故障一样

**Comment by eiinu** [comment]
`@nutui/nutui@4.0.3` 已发布
