### ISSUE TITLE
input组件 type为idcard 时 输入值后 获取值为空

### ISSUE THREAD

**Issue by emmmm-maker** [jdf2e/nutui#2147]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:alipay

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16.0

### Browser and its version（浏览器及其版本）
Microsoft Edge 版本 110.0.1587.57 (正式版本) (x86_64)

### System and its version（系统及其版本）
MacOs(13.0.0)

### Taro environmental information（taro 环境信息）
Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 9.4.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1 
      @tarojs/components: 3.6.1 => 3.6.1 
      @tarojs/helper: 3.6.1 => 3.6.1 
      @tarojs/plugin-framework-vue3: 3.6.1 => 3.6.1 
      @tarojs/plugin-html: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-h5: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1 
      @tarojs/runtime: 3.6.1 => 3.6.1 
      @tarojs/shared: 3.6.1 => 3.6.1 
      @tarojs/taro: 3.6.1 => 3.6.1 
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1 
      babel-preset-taro: 3.6.1 => 3.6.1 
      eslint-config-taro: 3.6.1 => 3.6.1 
    npmGlobalPackages:
      typescript: 4.8.4

### Reproduction link（重现链接）
[github.com](https://github.com/emmmm-maker/nutui-input-test)

### Steps to reproduce（重现步骤）
支付宝小程序预览 身份证输入框 输入后 点击按钮获取input value值 为空

### What is expected?（期望的结果是什么？）
支付宝小程序 身份证输入框能正确获取到身份证值

### What is actually happening?（实际的结果是什么？）
支付宝小程序 身份证输入框获取到的input值为空

**Comment by eiinu** [comment]
排查问题：NutInput 组件会默认设置 maxLength 为 -1，在支付宝 IDE 下无法触发 onInput 事件
临时性解决方案：手动给 nut-input 传入 `max-length="140"` （默认最大长度），或者 `max-length="18"`
后续会修复这个问题

**Comment by emmmm-maker** [comment]
我手动给 nut-input 传入 max-length="140"或max-length="18"还是获取不到值😂

**Comment by eiinu** [comment]
测试复现仓库时，IDE 下无法获取，真机正常。增加 max-length 设置后都能正常获取。
IDE 版本 3.3.3，启用小程序基础库 2.0 构建。
```vue
<template>
  <view>
    <nut-input v-model="id" placeholder="请输入身份证" type="idcard" max-length="18"/>
    <nut-button type='primary' @click="getId">获取身份证</nut-button>
  </view>
</template>
<script setup lang="ts">
import { ref } from 'vue'
const id = ref<string>('')
const getId = () => {
  console.log('id', id.value)
}
</script>
```

**Comment by panguoxian** [comment]
> 排查问题：NutInput 组件会默认设置 maxLength 为 -1，在支付宝 IDE 下无法触发 onInput 事件 临时性解决方案：手动给 nut-input 传入 `max-length="140"` （默认最大长度），或者 `max-length="18"` 后续会修复这个问题

我这边测试 微信小程序 type="digit" 或 type="number" 不管是真机还是模拟器，输入的居然不限制无效，居然还可以输入中文

**Comment by eiinu** [comment]
input 类型、number/digit 限制输入问题已修复
