### ISSUE TITLE
Menu组件在tabs标签内无法正常使用(不能正常展开)

### ISSUE THREAD

**Issue by fssgh** [jdf2e/nutui#2148]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.2.21

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.x

### Browser and its version（浏览器及其版本）
Chrome(107.0.5304.63)

### System and its version（系统及其版本）
win11

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/p/sandbox/nutui3-vite-demo-forked-mljlbt)

### Steps to reproduce（重现步骤）
点击tabs中的menu组件，无法正常展开。

### What is expected?（期望的结果是什么？）
能正常展开

### What is actually happening?（实际的结果是什么？）
无法正常展开

**Comment by Ymm0008** [comment]
https://github.com/jdf2e/nutui/commit/8d550bdf53f638132ca4103cbb069168174ac3e4   问题已跟进修复。

**Comment by fssgh** [comment]
> 

加了transform: none;这个只修复了闪动，menu但在tabs内还是没有正常展开显示呀（请看上面的重现链接）
