### ISSUE TITLE
Elevator 组件在 ios 上拉会回弹，比如我已经滑到 A 了，但是又弹回 D 了 ， 同事希望提供默认选中某个城市的属性

### ISSUE THREAD

**Issue by lisong981174580** [jdf2e/nutui#2149]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.0.0

### Browser and its version（浏览器及其版本）
110.0.5481.178

### System and its version（系统及其版本）
12.6

### Reproduction link（重现链接）
[eduresources.oss-cn-beijing.aliyuncs.com](https://eduresources.oss-cn-beijing.aliyuncs.com/web-project/images/employment/bug.mp4)

### Steps to reproduce（重现步骤）
具体见重现链接

### What is expected?（期望的结果是什么？）
期望不要回弹，滑到哪里停在哪里

### What is actually happening?（实际的结果是什么？）
已滑到顶部，但是又回弹回来了

**Comment by Drjingfubo** [comment]
NutUI场景和运行环境请填写正确，从视频来看 场景应该是小程序(nutui-taro)，运行环境是dev:weapp吧

**Comment by lisong981174580** [comment]
dev 和 build 都有这个问题

**Comment by lisong981174580** [comment]
> NutUI场景和运行环境请填写正确，从视频来看 场景应该是小程序(nutui-taro)，运行环境是dev:weapp吧

都有这个问题 dev 和 build

**Comment by Drjingfubo** [comment]
> > NutUI场景和运行环境请填写正确，从视频来看场景应该是小程序(nutui-taro)，运行环境是dev:weapp吧
> 
> 都有这个问题的开发和构建
我的意思是你的包选的（@nutui/nutui），不应该是（@nutui/nutui-taro）吗，运行环境是小程序端，不是h5端吧
咱们尽量填的准确点，我们定位问题也快点

**Comment by szg2008** [comment]
最好能够提供下在线代码，好定位问题

**Comment by lisong981174580** [comment]
可以拉一个腾讯会议我给你视频下吗？

**Comment by lisong981174580** [comment]
我的电话 18165057632  微信也一样

**Comment by lisong981174580** [comment]
https://eduresources.oss-cn-beijing.aliyuncs.com/web-project/json/cities.json?t=1679019854717

**Comment by lisong981174580** [comment]
数据源：https://eduresources.oss-cn-beijing.aliyuncs.com/web-project/json/cities.json?t=1679019854717

**Comment by eiinu** [comment]
回弹问题已修复 `4.0.4`。
默认选中：暂无计划
可以在组件外实现相似功能，比如在顶部增加「当前选中城市：modelValue」
