### ISSUE TITLE
[bug] TabPanel不是响应式的？

### ISSUE THREAD

**Issue by sulin2018** [jdf2e/nutui#215]
## 问题描述

```
   <nut-tab-panel 
      v-for="value in editableTabs" 
      v-bind:key="value.tabTitle" 
      :tabTitle="value.tabTitle" 
      :iconUrl="value.tabUrl" 
      v-html="value.content"
    >
    </nut-tab-panel>
```
示例中修改, edittabTabs UI不会变动。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by zhenyulei** [comment]
你好，nut-tab-panel 组件并不能单独使用，是nut-tab的子组件，需和nut-tab配合使用，详见Tab组件的说明文档，
另外确认一下，vue是否正确监听了数组更新：
https://cn.vuejs.org/v2/guide/list.html#数组更新检测
如果调用方法正确，请给出详细的使用情况，最好能够提供可复现的代码，多谢！

**Comment by zhenyulei** [comment]
> ## 问题描述
> ```
>    <nut-tab-panel 
>       v-for="value in editableTabs" 
>       v-bind:key="value.tabTitle" 
>       :tabTitle="value.tabTitle" 
>       :iconUrl="value.tabUrl" 
>       v-html="value.content"
>     >
>     </nut-tab-panel>
> ```
> 
> 示例中修改, edittabTabs UI不会变动。
> 
> ## 最小可复现仓库
> > 请创建最小可复现代码，并上传到你的 GitHub 仓库
> 
> ## 预期的行为和实际行为
> ## 复现步骤，具体代码
> ## 相关环境信息
> * **操作系统**：
> * **Node 版本**：
> * **NutUI 版本**：
> * **Vue 版本**：
> * **引用方式**：  CDN / NPM ？

你好，nut-tab-panel 组件并不能单独使用，是nut-tab的子组件，需和nut-tab配合使用，详见Tab组件的说明文档，
另外确认一下，vue是否正确监听了数组更新：
https://cn.vuejs.org/v2/guide/list.html#数组更新检测
如果调用方法正确，请给出详细的使用情况，最好能够提供可复现的代码，多谢！

**Comment by zhenyulei** [comment]
> ## 问题描述
> ```
>    <nut-tab-panel 
>       v-for="value in editableTabs" 
>       v-bind:key="value.tabTitle" 
>       :tabTitle="value.tabTitle" 
>       :iconUrl="value.tabUrl" 
>       v-html="value.content"
>     >
>     </nut-tab-panel>
> ```
> 
> 示例中修改, edittabTabs UI不会变动。
> 
> ## 最小可复现仓库
> > 请创建最小可复现代码，并上传到你的 GitHub 仓库
> 
> ## 预期的行为和实际行为
> ## 复现步骤，具体代码
> ## 相关环境信息
> * **操作系统**：
> * **Node 版本**：
> * **NutUI 版本**：
> * **Vue 版本**：
> * **引用方式**：  CDN / NPM ？

已修复，待上线后可以使用，如需要更新页面，请将监听变化的数据传入init-data

**Comment by zhenyulei** [comment]
已经上线 请见最后一个demo 将监听变化的数据传入init-data

**Comment by zhenyulei** [comment]
你好 已经上线 请将监听变化的数据传入init-data 也可以参考官网最后一个demo示例

**Comment by zhenyulei** [comment]
> ## 问题描述
> ```
>    <nut-tab-panel 
>       v-for="value in editableTabs" 
>       v-bind:key="value.tabTitle" 
>       :tabTitle="value.tabTitle" 
>       :iconUrl="value.tabUrl" 
>       v-html="value.content"
>     >
>     </nut-tab-panel>
> ```
> 
> 示例中修改, edittabTabs UI不会变动。
> 
> ## 最小可复现仓库
> > 请创建最小可复现代码，并上传到你的 GitHub 仓库
> 
> ## 预期的行为和实际行为
> ## 复现步骤，具体代码
> ## 相关环境信息
> * **操作系统**：
> * **Node 版本**：
> * **NutUI 版本**：
> * **Vue 版本**：
> * **引用方式**：  CDN / NPM ？

你好 已经上线 请将监听变化的数据传入init-data 也可以参考官网最后一个demo示例
