### ISSUE TITLE
H5环境下使用nut-swiper报错：ReferenceError: _getEnv is not defined

### ISSUE THREAD

**Issue by yoloseeyou** [jdf2e/nutui#2151]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.20.1

### Browser and its version（浏览器及其版本）
Chrome 110.0.5481.178（正式版本）

### System and its version（系统及其版本）
win11

### Reproduction link（重现链接）
[nutui.jd.com/h5/vue/4x/](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/swiper)

### Steps to reproduce（重现步骤）
1、初始化命令taro init myApp，
2、选择vue3 + NutUI，
3、复制官网的代码nut-swiper，使用H5运行起来就直接报错ReferenceError: _getEnv is not defined

### What is expected?（期望的结果是什么？）
H5运行正常，轮播图正常使用

### What is actually happening?（实际的结果是什么？）
报错ReferenceError: _getEnv is not defined

### Remarks（补充说明）
const useTaroRect = (elementRef, Taro) => {
  let element = unref(elementRef);
  console.log(Taro.getEnv());
  return new Promise((resolve) => {
    //这一步报错ReferenceError: _getEnv is not defined，
   //直接改为true运行后，所有内容正常
    if (Taro.getEnv() === "WEB") {
      if (element && element.$el) {
        element = element.$el;
      }
      if (isWindow(element)) {
        const width = element.innerWidth;
        const height = element.innerHeight;
        resolve({
          top: 0,
          left: 0,
          right: width,
          bottom: height,
          width,
          height
        });
      }
      if (element && element.getBoundingClientRect) {
        resolve(element.getBoundingClientRect());
      }
      resolve({
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: 0,
        height: 0
      });
    } else {
      const query = Taro.createSelectorQuery();
      let el = element.id ? element.id : element;
      query.select(`#${el}`) && query.select(`#${el}`).boundingClientRect();
      query.exec(function(res) {
        resolve(res[0]);
      });
    }
  });
};

**Comment by szg2008** [comment]
已修复，下个版本支持

**Comment by CoderPXin** [comment]
请问是什么问题呀，我这边是3.3.8，想看看能不能通过patch-package打补丁解决
