### ISSUE TITLE
更新最新的v4.0.2版本, H5列表滚动以及高度不正常

### ISSUE THREAD

**Issue by adonis-lsh** [jdf2e/nutui#2156]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
106

### System and its version（系统及其版本）
12.6

### Reproduction link（重现链接）
[nutui.jd.com/h5/vue/4x/](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/list)

### Steps to reproduce（重现步骤）
<template>
  <fs-layout>
    <template v-slot:content>
      <nut-searchbar v-model="state.searchValue">
        <template v-slot:leftin>
          <Search2/>
        </template>
      </nut-searchbar>
      <nut-tabs v-model="state.tab1value">
        <nut-tab-pane title="未处理">
          <div class="approve-list-wrapper">
            <nut-list v-if="state.count.length > 0" :height="100" :listData="state.count" @scroll-bottom="handleScroll">
              <template v-slot="{ item }">
                <div class="list-item">
                  <nut-avatar>小明</nut-avatar>
                </div>
              </template>
            </nut-list>
            <nut-empty v-else description="无数据"></nut-empty>
          </div>
        </nut-tab-pane>
        <nut-tab-pane title="已处理">
          <div class="approve-list-wrapper">
            <nut-list :height="50" :listData="state.count" @scroll-bottom="handleScroll">
              <template v-slot="{ item }">
                <div class="list-item">
                  {{ item }}
                </div>
              </template>
            </nut-list>
          </div>
        </nut-tab-pane>
      </nut-tabs>
    </template>
  </fs-layout>
</template>

<script lang="ts" setup>
import {onMounted, reactive} from 'vue';
import {Search2} from '@nutui/icons-vue-taro';
import './index.less'

onMounted(() => {
  state.count = state.count.map((item: number, index: number) => index + 1);
})

const state = reactive({
  searchValue: "",
  tab1value: 0,
  count: new Array(100).fill(0)
});

const handleScroll = () => {
  let arr = new Array(100).fill(0);
  const len = state.count.length;
  state.count = state.count.concat(arr.map((item: number, index: number) => len + index + 1));
};

</script>

### What is expected?（期望的结果是什么？）
正常展示

### What is actually happening?（实际的结果是什么？）
<img width="435" alt="image" src="https://user-images.githubusercontent.com/20501172/222616684-5403ad9b-49a4-43c5-9c53-8788ad6a44cc.png">

**Comment by panguoxian** [comment]
还有一个问题，我这边还有一个问题是最后一个数据不显示。

**Comment by xsjkj-com** [comment]
是的，最后一个数据不显示。
更新数据还有错误
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'height')
    at List.js:115:70

**Comment by LeeZChuan** [comment]
是nut-list这个虚拟列表吗？好像一个数据就会不渲染，多个数据最后一个数据就会不展示，这个列表会有这个问题

**Comment by adonis-lsh** [comment]
> 还有一个问题，我这边还有一个问题是最后一个数据不显示。

的确是这样, 我更新了4.0.3也不行, 头疼, 问题比较多

**Comment by adonis-lsh** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/20501172/225241253-c2e0bd93-a746-41b0-9bb6-383b762c84fc.png">
滚动的时候一直报这个错, 并且最后一个item没有展示全, 最新的4.0.3

**Comment by LeeZChuan** [comment]
> 

考虑再提一个issues?反馈一下这个问题？

**Comment by LeeZChuan** [comment]
> <img alt="image" width="893" src="https://user-images.githubusercontent.com/20501172/225241253-c2e0bd93-a746-41b0-9bb6-383b762c84fc.png">
> 
> 滚动的时候一直报这个错, 并且最后一个item没有展示全, 最新的4.0.3

考虑再提一个issues?反馈一下这个问题？

**Comment by dyubo2005** [comment]
上述异常全是nut-list中的 watch(() => props.listData, ...) 事件没有生效，很烦躁
