### ISSUE TITLE
AddressList组件获取不到对应的item回调参数

### ISSUE THREAD

**Issue by ghost** [jdf2e/nutui#2159]
### What problem does this feature solve?（这个功能解决的问题）
获取对应的item参数

### What does the proposed API look like?（期望的 API）
默认应该有相应对应回调数据

**Comment by eiinu** [comment]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/44915689/223028978-28d25a72-53b4-40cd-989d-6dd75b6e341d.png">
第二个参数是 item

**Comment by ghost** [comment]
看到了，感谢!
