### ISSUE TITLE
[suggest]建议uploader组件

### ISSUE THREAD

**Issue by richard1015** [jdf2e/nutui#216]
## 你建议我们做什么？

现在uploader组件 选择文件后，会直接进行上传

期望 
- 新增一个上传前置钩子（用于用户自定义拦截）
- 新增用户 主动调用 上传功能（非当前场景：文件选择后立即上传）

## 其它

无

**Comment by richard1015** [comment]
2.2.3已解决

**Comment by 307god** [comment]
新增用户 主动调用 上传功能 ，vue3 小程序 taro  有这个功能吗？
@richard1015

**Comment by richard1015** [comment]
暂时没有
