### ISSUE TITLE
list组价

### ISSUE THREAD

**Issue by yanduhantan1991** [jdf2e/nutui#2162]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
最新

### System and its version（系统及其版本）
win10

### Reproduction link（重现链接）
[nutui.jd.com/h5/vue/4x/](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/list)

### Steps to reproduce（重现步骤）
不太清楚是不是使用方式不正确，在数据比较少的时候，只有几条数据，list组件列表项最后一个没有显示，visibleData在截取数据的时候最后一条没有算上

### What is expected?（期望的结果是什么？）
正常显示数据

### What is actually happening?（实际的结果是什么？）
列表最后一条数据没有显示

### Remarks（补充说明）
const end = computed(() => {
      return Math.min(state.originStartIndex + visibleCount.value + props.bufferSize, state.list.length - 1);
    });

const visibleData: ComputedRef = computed(() => {
      return state.list.slice(state.start, end.value);
    });

**Comment by szg2008** [comment]
已修复，下次发版可用，感谢反馈🙏
