### ISSUE TITLE
nutui-react-taro 小程序 版本ui丢失 h5版本无事

### ISSUE THREAD

**Issue by Aliujiayu** [jdf2e/nutui#2164]
刚开始配置了tailwind
然后把tailwind相关删掉
就这样了
不知道发生了什么
`_sass:{
    resource: [
      path.resolve(__dirname, '..', 'src/assets/styles/custom_theme.scss')
    ],
    data: '@import "@nutui/nutui-react-taro/dist/styles/variables.scss";'
  },`
`import { Button, Checkbox, Input } from '@nutui/nutui-react-taro';`
![image](https://user-images.githubusercontent.com/32925657/223117547-cb0c5f91-5f9e-4971-8c07-d32fa4536c9e.png)
![image](https://user-images.githubusercontent.com/32925657/223117603-1f83b4b4-e227-466b-91a5-6d9cbb99e6a5.png)

**Comment by eiinu** [comment]
React 版本在这个仓库 https://github.com/jdf2e/nutui-react
