### ISSUE TITLE
被nut-config-provider包裹的具名插槽传值失效

### ISSUE THREAD

**Issue by LeoFeng23** [jdf2e/nutui#2165]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18.14.2 & 14.21.3

### Browser and its version（浏览器及其版本）
110.0.5481.177

### System and its version（系统及其版本）
Macos(13.2.1)

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.1

  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.n/bin/node
      Yarn: 1.22.19 - ~/Library/pnpm/yarn
      npm: 9.5.0 - ~/.n/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1 
      @tarojs/components: 3.6.1 => 3.6.1 
      @tarojs/helper: 3.6.1 => 3.6.1 
      @tarojs/plugin-framework-vue3: 3.6.1 => 3.6.1 
      @tarojs/plugin-html: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-h5: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1 
      @tarojs/plugin-vue-devtools: ^3.6.1 => 3.6.1 
      @tarojs/router: 3.6.1 => 3.6.1 
      @tarojs/runtime: 3.6.1 => 3.6.1 
      @tarojs/service: 3.6.1 => 3.6.1 
      @tarojs/shared: 3.6.1 => 3.6.1 
      @tarojs/taro: 3.6.1 => 3.6.1 
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1 
      babel-preset-taro: 3.6.1 => 3.6.1 
      eslint-config-taro: 3.6.1 => 3.6.1 

### Reproduction link（重现链接）
[github.com/LeoFeng23/bug-test](https://github.com/LeoFeng23/bug-test)

### Steps to reproduce（重现步骤）
1. 引入nut-config-provider组件
2. 在nut-config-provider包裹的元素中使用具名插槽并传递任意属性

### What is expected?（期望的结果是什么？）
具名插槽传递的属性值可以被正常获取

### What is actually happening?（实际的结果是什么？）
无法获取插槽传递的任何属性

**Comment by yokingma** [comment]
类似的环境，在微信小程序开发中同样出现获取不到值。
Cannot read property 'item' of undefined

**Comment by eiinu** [comment]
`@nutui/nutui@4.0.3` 已发布
