### ISSUE TITLE
DatePicker 支持时分格式,不需要秒

### ISSUE THREAD

**Issue by lovelyqun** [jdf2e/nutui#2167]
### What problem does this feature solve?（这个功能解决的问题）
用户只需要选择时分,不想选择秒

### What does the proposed API look like?（期望的 API）
新增一个type类型进行设置

**Comment by lovelyqun** [comment]
同时希望在选项顶部添加选项的说明文字
年月日时分秒

**Comment by lovelyqun** [comment]
![image](https://user-images.githubusercontent.com/25495741/223611251-765f7969-f231-45a4-adb9-79d2815dbf69.png)

**Comment by eiinu** [comment]
`v4.0.5`已支持选择时分
