### ISSUE TITLE
nut-input-number组件在ios h5下输入小数点会清空整个输入框

### ISSUE THREAD

**Issue by sgssxf** [jdf2e/nutui#2168]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
cdn

### Node version（node 版本）
16.18

### Browser and its version（浏览器及其版本）
safari

### System and its version（系统及其版本）
ios

### Reproduction link（重现链接）
[codepen.io/sgssxf/pen/BaOwYzG](https://codepen.io/sgssxf/pen/BaOwYzG)

### Steps to reproduce（重现步骤）
ios用safari浏览器打开后，点击输入123正常，再输入小数点“.”后内容清空，并且小数点按钮弹起有个延时，继续输入“.”，可以继续显示，只能用光标移动到前面去修改。

### What is expected?（期望的结果是什么？）
123.45

### What is actually happening?（实际的结果是什么？）
输入.后清空

### Remarks（补充说明）
ios用safari浏览器打开后，点击输入123正常，再输入小数点“.”后内容清空，并且小数点按钮弹起有个延时，继续输入“.”，可以继续显示，只能用光标移动到前面去修改。

**Comment by szg2008** [comment]
![image](https://user-images.githubusercontent.com/8221688/223968416-47c37bef-e4af-4cac-be52-c1b38f0c1817.png)
试了一下问题

**Comment by szg2008** [comment]
没有复现问题
