### ISSUE TITLE
nut-tabs 在字节跳动小程序中 tab名称 显示不正常[bug]

### ISSUE THREAD

**Issue by tagnxianglong** [jdf2e/nutui#2169]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:tt

### Citation method（引用方式）
npm

### Node version（node 版本）
v16.4.2

### Browser and its version（浏览器及其版本）
safari 16.3 (18614.4.6.1.6)

### System and its version（系统及其版本）
Mac OS 13.2.1

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.0

### Reproduction link（重现链接）
[github.com](https://github.com/tagnxianglong/nutbugs.git)

### Steps to reproduce（重现步骤）
无

### What is expected?（期望的结果是什么？）
修复正常显示

### What is actually happening?（实际的结果是什么？）
在字节跳动小程序中，nut-tabs tab标题  本身应该水平显示，实际显示不正常

**Comment by richard1015** [comment]
辛苦提供个截图

**Comment by tagnxianglong** [comment]
> 辛苦提供个截图
![1678354610165](https://user-images.githubusercontent.com/30792872/223981916-14f8f332-67c0-49c0-a5c4-03d5fd3b2f53.jpg)

**Comment by ggpcn** [comment]
和 [https://github.com/jdf2e/nutui/issues/2099](https://github.com/jdf2e/nutui/issues/2099)是一样的问题。

**Comment by eiinu** [comment]
`@4.0.4-beta.2` 已修复

**Comment by eiinu** [comment]
`4.0.4` 已发布
