### ISSUE TITLE
最新的虚拟滚动列表渲染问题（最后一条数据/传入一条数据无法正常渲染）

### ISSUE THREAD

**Issue by LeeZChuan** [jdf2e/nutui#2174]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.18.1

### Browser and its version（浏览器及其版本）
dingding小程序

### System and its version（系统及其版本）
暂无

### Reproduction link（重现链接）
[nutui.jd.com/h5/vue/4x/](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/list)

### Steps to reproduce（重现步骤）

```vue
<nut-list :height="cardHeight" :list-data="cardList" @scroll-bottom="handleScrollHandler()">
          <template #default="{ item, index }">
            <slot name="cardList" :row="item" :row-index="index" />
          </template>
        </nut-list>
```

传入cardList就会导致无法正常渲染

### What is expected?（期望的结果是什么？）
传入一条数据或者传入多条数据，可以正常显示出来

### What is actually happening?（实际的结果是什么？）
传入一条数据无法正常渲染；
传入多条数据，最后一条无法正常渲染

### Remarks（补充说明）
同样的，虚拟列表的height这个字段高度无法自适应配置；

**Comment by szg2008** [comment]
已修复，下个版本可用
