### ISSUE TITLE
【Taro】NutInput 组件的 type 类型表现与 Taro 的 input 不一致

### ISSUE THREAD

**Issue by eiinu** [jdf2e/nutui#2176]
### What problem does this feature solve?（这个功能解决的问题）

NutInput（小程序与H5）
- number: 数字类型，支持负号、小数点，校验，原生类型为 text，唤起系统键盘
- digit: 整数类型，原生类型为 tel，唤起微信小程序纯数字键盘

TaroInput（小程序）
- number: 整数类型，唤起微信小程序纯数字键盘
- digit: 允许小数点和数字，无校验，唤起微信小程序带小数点键盘

TaroInput（H5）
- number: `<input type="number" />` 限制数字输入，唤起系统键盘
- digit: 输入无限制，唤起系统键盘

### What does the proposed API look like?（期望的 API）
type 类型是否应该与 Taro/微信小程序保持一致，或者至少要支持唤起带小数点键盘

**Comment by chenchunfeng** [comment]
我更新了4.0.4，发现了两个问题
1. 你上次说的，之前v4.0.0 NutInput  type="number" 调起的就是text类型，设置digit才是纯数字
2. input的class名也变了，由nut-input 变为nut-input-box

**Comment by BG7ZAG** [comment]
想不明白为什么把number类型改成text，digit改成tel，小程序中的原生类型被覆盖了~~

```
const inputType = (type: InputType) => {
      if (type === 'number') {
        return {
          type: 'text'
        };
      }
      if (type === 'digit') {
        return {
          type: 'tel'
        };
      }
      return { type };
    };
```
