### ISSUE TITLE
Collapse 折叠面板在微信小程序点击打开后，会自动收起来

### ISSUE THREAD

**Issue by ymzcode** [jdf2e/nutui#2177]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.3

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.12.1

### Browser and its version（浏览器及其版本）
微信小程序基础库：2.30.2

### System and its version（系统及其版本）
Macos（13.2.1 ）

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.2

  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      npm: 9.6.1 - ~/.nvm/versions/node/v18.12.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2 
      @tarojs/components: 3.6.2 => 3.6.2 
      @tarojs/helper: 3.6.2 => 3.6.2 
      @tarojs/plugin-framework-vue3: 3.6.2 => 3.6.2 
      @tarojs/plugin-html: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2 
      @tarojs/runtime: 3.6.2 => 3.6.2 
      @tarojs/shared: 3.6.2 => 3.6.2 
      @tarojs/taro: 3.6.2 => 3.6.2 
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2 
      babel-preset-taro: 3.6.2 => 3.6.2 
      eslint-config-taro: 3.6.2 => 3.6.2 

### Reproduction link（重现链接）
[github.com](https://github.com/ymzcode/taro-test-1)

### Steps to reproduce（重现步骤）
可复现代码
```
<template>
  <view class="index">
    <nut-collapse v-model="activeNames" @change="collapseChange">
      <nut-collapse-item v-for="(item) in filterListArr" :title="item.title" :key="item.catalogId" :name="item.catalogId">
        NutUI是一套拥有京东风格的轻量级的 Vue 组件库
      </nut-collapse-item>
    </nut-collapse>
  </view>
</template>

<script setup>
import {onMounted, reactive, ref, toRefs} from 'vue';
import Taro from "@tarojs/taro";

const activeNames = ref([])
const collapseChange = (data) => {
  console.log(data)
}

const filterListArr = ref([])

onMounted(async () => {
  const res = await Taro.request({
    url: 'xxxxxxxxxx',
    data: {
      subjectId: 5,
      parentId: 0
    }
  })
  filterListArr.value = res.data.data
  console.log(res)
})

</script>

<style lang="scss">

</style>

```

### What is expected?（期望的结果是什么？）
1. 手动触发展开后，不自动关闭
2. v-model指定默认展开值时，微信小程序能正常展开

### What is actually happening?（实际的结果是什么？）
在H5端正常
在微信小程序，手动触发展开后，会自动关闭，再次点击展开，这时不再关闭。并带有以下问题。
1. 控制台打印的console值错乱。
2. 当指定一个默认展开项`const activeNames = ref([1])` ，微信小程序端无法默认展开。

### Remarks（补充说明）
自测不使用接口返回的值，直接写死`filterListArr`的值，问题消失

**Comment by ymzcode** [comment]
问题演示
链接: https://pan.baidu.com/s/1LKUZtHbgzdG5Ensgfhkykw?pwd=7fmk 提取码: 7fmk

**Comment by freescale218** [comment]
我也碰到,我是在nut-popup里的nut-collapse不正常,其他地方正常
nut-popup显示后,本来默认要打开的,它那个箭头是打开的,但是内容没显示出来,要再点击下屏幕才能出现,好像是页面不刷新的样子

**Comment by gezichenshan** [comment]
same

**Comment by gezichenshan** [comment]
经查，问题似乎源自于npm里下载的lib库和github上的同版本文件不同步导致。

如果要手动更正这个bug，需要删除node_modules/@nutui/nutui-taro/dist/packages/_es/CollapseItem.js中的`init.value && handleOpen()`
```
const getH = (list) => {
      parent.children.forEach((item1, index1) => {
        let ary = Array.from(item1.$el.children);
        let _uid = ary[1].children[0]["uid"];
        let tm = list == null ? void 0 : list.filter((item2) => item2.id == _uid);
        if (tm && tm.length > 0) {
          let h = tm[0]["height"];
          item1.conHeight = h;
          setTimeout(() => {
            init.value && handleOpen(); // 需要屏蔽或删除此行，这里判断如果init为true，则自动调用handleOpen，和之前的open操作叠加就变成了!open(closed)。而之后init会变成false，就不会再出现问题。
          }, 500);
        }
      });
    };
```
我看github上的v4.0.3中CollapseItem.js文件应该已经修复了这个bug，但是npm中的lib包似乎没有更新，不知道为什么。希望官方大大能解决一下这个问题。@ailululu  @eiinu 

-------
2023/03/14 22:15 edit:
不是`经查，问题似乎源自于npm里下载的lib库和github上的同版本文件不同步导致。` `npm中的lib包似乎没有更新`，这里我说错了。因为看源码一个组件有两份文件，小程序对应的我应该看*.taro.vue文件。

**Comment by gezichenshan** [comment]
这个问题可能要快点解决了。因为我在使用小程序端使用其他组件时也遇到各类不期望的bug。
我用的是@nutui/nutui-taro@3.3.6, 也有上述bug，而且input组件也遇到手动设置v-model值时报错的问题。

**Comment by eiinu** [comment]
> 这个问题可能要快点解决了。因为我在使用小程序端使用其他组件时也遇到各类不期望的bug。
> 我用的是@nutui/nutui-taro@3.3.6, 也有上述bug，而且input组件也遇到手动设置v-model值时报错的问题。

input 的问题已经更新到 3.3.7-beta.2，预计周五会发布正式版。collapse 的问题我们会跟进一下

**Comment by newyangkun** [comment]
请问这个问题解决了吗?

**Comment by freescale218** [comment]
没有
&nbsp;


guowx
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月11日(星期二) 下午3:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jdf2e/nutui] Collapse 折叠面板在微信小程序点击打开后，会自动收起来 (Issue #2177)





 
请问这个问题解决了吗?

**Comment by eiinu** [comment]
修复代码将合并入 4.0.8 于本周五发布

**Comment by hissincn** [comment]
现在的默认模版好像是是4.0.4，依然会遇到这个问题，升级到最新版就好了。
希望可以改一下默认模版的package.json
