### ISSUE TITLE
nut-form 的 model对象，不管是 reactive 还是 ref，当更新 model对象属性时会报错

### ISSUE THREAD

**Issue by junxiaotan** [jdf2e/nutui#2178]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.3

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(110.0.5481.177)

### System and its version（系统及其版本）
MacOS(13.0.1)

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.2

  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2
      @tarojs/components: 3.6.2 => 3.6.2
      @tarojs/helper: 3.6.2 => 3.6.2
      @tarojs/plugin-framework-vue3: 3.6.2 => 3.6.2
      @tarojs/plugin-html: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2
      @tarojs/runtime: 3.6.2 => 3.6.2
      @tarojs/shared: 3.6.2 => 3.6.2
      @tarojs/taro: 3.6.2 => 3.6.2
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2
      babel-preset-taro: 3.6.2 => 3.6.2
      eslint-config-taro: 3.6.2 => 3.6.2

### Reproduction link（重现链接）
[github.com](https://github.com/junxiaotan/vue-taro-nutui-config-provider/blob/master/src/pages/form/index.vue)

### Steps to reproduce（重现步骤）
1，克隆仓库
2，pnpm install
3，npm run dev:weapp
4，打开的默认页面，点击按钮 《点我》
5，控制台会出现以下报错

### What is expected?（期望的结果是什么？）
不会报错

### What is actually happening?（实际的结果是什么？）
WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1 Error: traceEndEvent mismatch, args={}
    at l (WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at d (WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at Proxy.<anonymous> (WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at Function.<anonymous> (.._src_dom_root.ts:180)
    at f (WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
    at r.<anonymous> (WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at Function.<anonymous> (WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at p (WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1(env: macOS,mp,1.06.2301160; lib: 2.30.2)
errorReport @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
l @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
d @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ .._src_dom_root.ts:180
f @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
p @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
setTimeout (async)
globalThis.setTimeout @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
globalThis.setTimeout @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
performUpdate @ .._src_dom_root.ts:87
enqueueUpdate @ .._src_dom_root.ts:78
enqueueUpdate @ .._src_dom_node.ts:298
setAttribute @ .._src_dom_element.ts:202
set @ .._src_dom_form.ts:18
set @ ._node_modules_.pnpm_@vue+reactivity@3.2.47_node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:536
updateValue @ ._node_modules_.pnpm_@nutui+nutui-taro@4.0.3-beta.2_gukcl7kz2zsa3mg46tfztplbd4_node_modules_@nutui_nutui-taro_dist_packages__es_Input.js:189
(anonymous) @ ._node_modules_.pnpm_@nutui+nutui-taro@4.0.3-beta.2_gukcl7kz2zsa3mg46tfztplbd4_node_modules_@nutui_nutui-taro_dist_packages__es_Input.js:254
callWithErrorHandling @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:173
callWithAsyncErrorHandling @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:182
job @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:1812
flushPreFlushCbs @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:336
updateComponentPreRender @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5789
componentUpdateFn @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5702
run @ ._node_modules_.pnpm_@vue+reactivity@3.2.47_node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:190
instance.update @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5763
updateComponent @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5588
processComponent @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5521
patch @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5119
patchBlockChildren @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5424
processFragment @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5487
patch @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5112
patchBlockChildren @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5424
processFragment @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5487
patch @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5112
patchBlockChildren @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5424
patchElement @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5332
processElement @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5199
patch @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5116
componentUpdateFn @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5729
run @ ._node_modules_.pnpm_@vue+reactivity@3.2.47_node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:190
instance.update @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5763
callWithErrorHandling @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:173
flushJobs @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:406
Promise.then (async)
queueFlush @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:298
queueJob @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:292
(anonymous) @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:5761
triggerEffect @ ._node_modules_.pnpm_@vue+reactivity@3.2.47_node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:400
triggerEffects @ ._node_modules_.pnpm_@vue+reactivity@3.2.47_node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:390
trigger @ ._node_modules_.pnpm_@vue+reactivity@3.2.47_node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:358
set @ ._node_modules_.pnpm_@vue+reactivity@3.2.47_node_modules_@vue_reactivity_dist_reactivity.esm-bundler.js:543
handleClick @ ._src_pages_form_index.vue:14
callWithErrorHandling @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:173
callWithAsyncErrorHandling @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:182
emit @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:730
(anonymous) @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:7465
handleClick @ ._node_modules_.pnpm_@nutui+nutui-taro@4.0.3-beta.2_gukcl7kz2zsa3mg46tfztplbd4_node_modules_@nutui_nutui-taro_dist_packages__es_Button.js:45
onClick._cache.<computed>._cache.<computed> @ ._node_modules_.pnpm_@nutui+nutui-taro@4.0.3-beta.2_gukcl7kz2zsa3mg46tfztplbd4_node_modules_@nutui_nutui-taro_dist_packages__es_Button.js:91
callWithErrorHandling @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:173
callWithAsyncErrorHandling @ ._node_modules_.pnpm_@vue+runtime-core@3.2.47_node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:182
invoker @ ._node_modules_.pnpm_@vue+runtime-dom@3.2.47_node_modules_@vue_runtime-dom_dist_runtime-dom.esm-bundler.js:345
handler @ .._src_dom_event-target.ts:47
dispatchEvent @ .._src_dom_element.ts:327
dispatch @ .._src_dom_event.ts:169
eventHandler @ .._src_dom_event.ts:193
o.safeCallback @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
Ln @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
he @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
fe @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
emit @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
dispatch @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
cb @ WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
a @ VM9 asdebug.js:10
c @ VM9 asdebug.js:10
(anonymous) @ VM9 asdebug.js:1
f @ VM9 asdebug.js:1
g @ VM9 asdebug.js:1
(anonymous) @ VM9 asdebug.js:1
_ws.onmessage @ VM9 asdebug.js:1
Show 59 more frames
WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1 TypeError: Cannot read property '__treeManager__' of undefined
    at Proxy.<anonymous> (WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at Proxy.<anonymous> (WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at Function.<anonymous> (.._src_dom_root.ts:180)
    at :45749/appservice/<setTimeout callback function>
    at WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1
    at r.<anonymous> (WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at Function.<anonymous> (WASubContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at p (WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1)
    at WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1
    at WAServiceMainContext.js?t=wechat&s=1678671913296&v=2.30.2:1(env: macOS,mp,1.06.2301160; lib: 2.30.2)

**Comment by junxiaotan** [comment]
package.json 里面的版本 4.0.3-beta.2 可以忽略，忘了改版本了，已经在重新初始化的工程中测试，最新 4.0.3 也可以复现。

**Comment by junxiaotan** [comment]
顺便想问一下，现在如果用于生产环境，建议4.x还是3.x呢？

**Comment by mzcgithub** [comment]
> 顺便想问一下，现在如果用于生产环境，建议4.x还是3.x呢？



> package.json 里面的版本 4.0.3-beta.2 可以忽略，忘了改版本了，已经在重新初始化的工程中测试，最新 4.0.3 也可以复现。

4.3我也复现了，有解决吗？

**Comment by junxiaotan** [comment]
> > 顺便想问一下，现在如果用于生产环境，建议4.x还是3.x呢？
> 
> > package.json 里面的版本 4.0.3-beta.2 可以忽略，忘了改版本了，已经在重新初始化的工程中测试，最新 4.0.3 也可以复现。
> 
> 4.3我也复现了，有解决吗？

我打算用 react 版本再试试，如果不行，就用 v3，UI都设计好了，我也就剩下这点选择了。

**Comment by eiinu** [comment]
> 我打算用 react 版本再试试，如果不行，就用 v3，UI都设计好了，我也就剩下这点选择了。

明天测试通过后会发一个 beta 包。README 里有交流群信息，在群里反馈问题响应会更快。

**Comment by mzcgithub** [comment]
> 



> > 我打算用 react 版本再试试，如果不行，就用 v3，UI都设计好了，我也就剩下这点选择了。
> 
> 明天测试通过后会发一个 beta 包。README 里有交流群信息，在群里反馈问题响应会更快。

我这边是从3.0升级到4.0的，项目已经完成了，还react肯定不现实了，希望能解决这个问题吧

**Comment by eiinu** [comment]
可以先试下 `@nutui/nutui-taro@4.0.4-beta.1` ，阻塞性问题已修复。

**Comment by eiinu** [comment]
`4.0.4` 已发布
