### ISSUE TITLE
DatePicker日期选择器在钉钉小程序中无法使用

### ISSUE THREAD

**Issue by Mxtzz** [jdf2e/nutui#2180]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.3

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:tt

### Citation method（引用方式）
npm

### Node version（node 版本）
16.0.0

### Browser and its version（浏览器及其版本）
钉钉小程序开发者工具 3.1.3

### System and its version（系统及其版本）
Windows 11

### Taro environmental information（taro 环境信息）
Taro v3.6.2

  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.0.0 - C:\Users\mazw2\AppData\Local\Temp\yarn--1678845929062-0.24539505586514743\node.CMD
      Yarn: 1.22.19 - C:\Users\mazw2\AppData\Local\Temp\yarn--1678845929062-0.24539505586514743\yarn.CMD
      npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/datepicker)

### Steps to reproduce（重现步骤）
钉钉小程序，使用官方文档DatePicker的Demo，无法设置默认日期，选择日期后控制台会报错。

### What is expected?（期望的结果是什么？）
可以设置默认日期，可以选择日期。

### What is actually happening?（实际的结果是什么？）
无法设置默认日期，选择日期后控制台会报错。

**Comment by LeeZChuan** [comment]
官方何时能解决，钉钉小程序的时间控件兼容问题呢？

**Comment by eiinu** [comment]
DatePicker 组件依赖于小程序端的原生 picker-view 组件。
测试发现，在 Taro + 钉钉小程序环境下，picker-view 的 onChange 事件会返回错误的结果（设置的是两列数据，但返回值为三列数据），从而造成后续操作出现异常，相关 issue：https://github.com/NervJS/taro/issues/11367
需要进一步确认问题来源。

**Comment by eiinu** [comment]
redirect to #2292
