### ISSUE TITLE
nutui dialog组件暗黑模式下标题颜色对比度不明显

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui#2186]
### What problem does this feature solve?（这个功能解决的问题）
可以明显的看清标题，现在不好看出来
<img width="527" alt="image" src="https://user-images.githubusercontent.com/43030980/225803322-9b394cea-c3b6-4624-ac9b-19a4adba4c8a.png">

### What does the proposed API look like?（期望的 API）
修改颜色

**Comment by eiinu** [comment]
`4.0.4` 已增加 header 区域暗黑模式字体颜色
