### ISSUE TITLE
nut-signature随页面滚动问题

### ISSUE THREAD

**Issue by JackYumg** [jdf2e/nutui#2187]
### What problem does this feature solve?（这个功能解决的问题）
签名时固定当前位置

### What does the proposed API look like?（期望的 API）
签名时在具有滚动条界面时不要随着页面一起滚动

[](url)
微信小程序出现的问题

**Comment by LeeZChuan** [comment]
不只是签字控件会随着页面一起滚动，比如使用echarts这类底层使用canvas实现的组件，都会出现这个问题，可能是组件库在使用canvas这个存在逻辑问题；
官方对于可视化图表的使用兼容上，有没有相对好的兼容开发计划，目前社区也有相关的demo例如：echarts4taro3，但是兼容性相对比较差，只能在h5或者wx上使用，钉钉小程序就无法正常绘制

**Comment by KKandLL-Forever** [comment]
小程序模拟器会随着页面滚动，在真机/预览时就不会跟着滚动了
