### ISSUE TITLE
小程序自定义tabbar使用tabbar组件，控制台报错 Cannot read property 'height' of null

### ISSUE THREAD

**Issue by osinglee** [jdf2e/nutui#2188]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16.0

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
macos 13

### Taro environmental information（taro 环境信息）
Taro CLI 3.5.11 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.18.0 - ~/.nvm/versions/node/v16.16.0/bin/npm

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/datepicker)

### Steps to reproduce（重现步骤）
Cannot read property 'height' of null
```vue
setTimeout(() => {
          const query = Taro.createSelectorQuery();
          query.select(".nut-tabbar").boundingClientRect();
          query.exec((res) => {
            height.value = res[0].height;
          });
        }, 500);
```
微信小程序自定义tabbar在dom中跟 page平级，Taro.createSelectorQuery() 无法获取到 ".nut-tabbar" 节点。导致res为[null]

### What is expected?（期望的结果是什么？）
Cannot read property 'height' of null

### What is actually happening?（实际的结果是什么？）
Cannot read property 'height' of null

**Comment by w-zhCN** [comment]
怎么解决呢？

**Comment by ye21st** [comment]
怎么解决的呢
