### ISSUE TITLE
CheckboxGroup在数据发生减少时model似乎没有同步更新

### ISSUE THREAD

**Issue by ghost** [jdf2e/nutui#2189]
### What problem does this feature solve?（这个功能解决的问题）
CheckboxGroup可以在Checkbox发生后变化后正常的全选

### What does the proposed API look like?（期望的 API）
[重现地址](https://codesandbox.io/p/sandbox/nutui3-vite-demo-forked-pf2jns?welcome=true)

在添加data的时候，可以正确的全选，取消全选。但是data的数据减少之后，v-model的值好像没有更新到，导致了全选效果失效

**Comment by awnawnawn** [comment]
看到文档中的CheckboxGroup Events事件返回label数组，表示当前选中项的集合。
有办法返回当前点击的Checkbox的状态和model值么？

**Comment by eiinu** [comment]
`4.0.5-beta.1` 已更新，周五发布正式版。
