### ISSUE TITLE
fork源码，本地执行build:site后，一直卡在`dist/h5/vue/4x/demo-4.0.3/mobile.js     482.07 kB │ gzip: 146.70 kB` 这条输出日志，构建任务结束不了

### ISSUE THREAD

**Issue by Capchen** [jdf2e/nutui#2192]
### What problem does this feature solve?（这个功能解决的问题）
如何本地执行npm run build:site

### What does the proposed API look like?（期望的 API）
希望能本地构建文档

**Comment by eiinu** [comment]
已解决
