### ISSUE TITLE
nut-picker 问题

### ISSUE THREAD

**Issue by g1012415019** [jdf2e/nutui#220]
## 问题描述

1. 页面 多个nut-picker 时  nut-picker 联动后 第二个nut-picker显示空白，
2. 异步请求后 nut-picker 没有手动选中第一个选项时，confirm 没有返回选中值

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
 https://github.com/g1012415019/nutui-nut-picker-bug-dome.git 
## 相关环境信息
- **操作系统**：macOS cataline  10.15.3
- **Node 版本**： v10.0.0
- **NutUI 版本**：2.2.0
- **Vue 版本**：@vue/cli 4.1.1
- **引用方式**：  CDN / NPM ？ NPM

**Comment by richard1015** [comment]
已安排对于开发者跟进，请耐心等待

**Comment by irisSong** [comment]
1、初始化数据直接[],不要[[]]。

**Comment by irisSong** [comment]
按照以下建议修改代码，可解决上述问题。1、更新数据使用this.$set()这个方法。2、初始化数据，直接[],不要[[]]。
