### ISSUE TITLE
nut-button去除不掉点击时的样式

### ISSUE THREAD

**Issue by Ouopoulos** [jdf2e/nutui#2202]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
MacOS(12.4)

### Taro environmental information（taro 环境信息）
Taro v3.6

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/button)

### Steps to reproduce（重现步骤）
.button-hover{

    background-color: #ffffff !important;

  }

### What is expected?（期望的结果是什么？）
怎么去除样式问题

### What is actually happening?（实际的结果是什么？）
优先级最高 依然无法去除

**Comment by eiinu** [comment]
点击时的样式对应的选择器：
```css
.nut-button:active {
  background: xxx
}
```

**Comment by Ouopoulos** [comment]
没有效果 没有类似微信小程序button的hover-class这样的属性吗

**Comment by eiinu** [comment]
> 没有效果 没有类似微信小程序button的hover-class这样的属性吗

目前 `@nutui/nutui` 与 `@nutui/nutui-taro` 使用的是同一套 [scss 文件](https://github.com/jdf2e/nutui/blob/v4/src/packages/__VUE/button/index.scss)，点击态使用 css 样式控制。

没有效果可能是优先级不够高。

**Comment by Ouopoulos** [comment]
!important 也没用

**Comment by eiinu** [comment]
> !important 也没用

我测试了下小程序下，使用
```css
.button-hover {
  background: blue !important;
}
```
或者使用
```css
.nut-button:active {
  background: blue !important;
}
```
都是可以覆盖掉默认点击态样式的🤔

**Comment by Ouopoulos** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/52897984/228181473-3134a00f-8953-47cf-af20-0bfbacf2821f.png">
<img width="99" alt="image" src="https://user-images.githubusercontent.com/52897984/228180689-d45aa124-7fd2-4faf-afd9-00b5ef5c3f8d.png">
<img width="645" alt="image" src="https://user-images.githubusercontent.com/52897984/228180753-c743a8f4-2b65-40c0-8470-03d12eeda72a.png">
<img width="511" alt="image" src="https://user-images.githubusercontent.com/52897984/228181684-57f32594-ccf2-46c5-b8b1-d492ca0055ab.png">
从我的结果上来说,这两种解决方案都不行.

**Comment by eiinu** [comment]
> <img alt="image" width="1080" src="https://user-images.githubusercontent.com/52897984/228181473-3134a00f-8953-47cf-af20-0bfbacf2821f.png">
> 
> <img alt="image" width="99" src="https://user-images.githubusercontent.com/52897984/228180689-d45aa124-7fd2-4faf-afd9-00b5ef5c3f8d.png">
> 
> <img alt="image" width="645" src="https://user-images.githubusercontent.com/52897984/228180753-c743a8f4-2b65-40c0-8470-03d12eeda72a.png">
> 
> <img alt="image" width="511" src="https://user-images.githubusercontent.com/52897984/228181684-57f32594-ccf2-46c5-b8b1-d492ca0055ab.png">
> 
> 从我的结果上来说,这两种解决方案都不行.

你的选择器没有匹配上。。。

**Comment by Ouopoulos** [comment]
我试过了 只要不是#fff 和 transparent 都能正常显示 但问题是 我想把背景变成透明亦或是白色
<img width="90" alt="image" src="https://user-images.githubusercontent.com/52897984/228416492-e12cfd8f-68f5-406e-aa56-d635a459f1de.png">
<img width="445" alt="image" src="https://user-images.githubusercontent.com/52897984/228416529-cdeba6d5-fb4d-4546-a6ac-6273a413b5e1.png">
<img width="97" alt="image" src="https://user-images.githubusercontent.com/52897984/228416754-cf40ea2e-2651-4404-bc47-ac0f2482bdc3.png">
<img width="442" alt="image" src="https://user-images.githubusercontent.com/52897984/228416767-215828f5-82e1-41fd-9163-9f77aeef53e7.png">

**Comment by eiinu** [comment]
> 我试过了 只要不是#fff 和 transparent 都能正常显示 但问题是 我想把背景变成透明亦或是白色 

```css
.nut-button:active::before {
  opacity: 0;
}
```
增加这个代码可以清除剩余的底色，实现背景透明。

Button 组件暂时没有计划提供这样定制化的功能，更推荐自行封装 button 或者 view 来实现。
