### ISSUE TITLE
image组件无法使用

### ISSUE THREAD

**Issue by leilay** [jdf2e/nutui#2203]
![image](https://user-images.githubusercontent.com/14231925/227701908-7f900123-5916-4574-910f-e7639b55fa4f.png)
Welcome to developing components

**Comment by leilay** [comment]
关闭了，nutUI-taro不行，nutUI可以

**Comment by eiinu** [comment]
NutUI Taro 版没有提供 Image 组件，可以直接使用 Taro 提供的 image，功能已经很丰富了。
