### ISSUE TITLE
addresslist 的组件点击事件全部不触发

### ISSUE THREAD

**Issue by bigbossx** [jdf2e/nutui#2204]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-vue version（nutui-vue 版本）

3.2.3

### Vue version（vue 版本）
3.2.44

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14

### Browser and its version（浏览器及其版本）
小程序

### System and its version（系统及其版本）
mac

### Taro environmental information（taro 环境信息）
1

### Reproduction link（重现链接）
[nutui.jd.com/3x/](https://nutui.jd.com/3x/#/zh-CN/component/addresslist)

### Steps to reproduce（重现步骤）
1

### What is expected?（期望的结果是什么？）
1

### What is actually happening?（实际的结果是什么？）
1

### Remarks（补充说明）
官网例子都点击没反应，不过测试用例的吗

**Comment by eiinu** [comment]
最新版本 3.3.6
