### ISSUE TITLE
datepicker组件取消想还原成当前时间

### ISSUE THREAD

**Issue by Xhyen** [jdf2e/nutui#2205]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.2.24

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
14.18.0

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
macos

### Taro environmental information（taro 环境信息）
 Taro v3.4.11

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  Taro CLI 3.4.11 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2
      @tarojs/components: 3.6.2 => 3.6.2
      @tarojs/helper: 3.6.2 => 3.6.2
      @tarojs/mini-runner: 3.6.2 => 3.6.2
      @tarojs/plugin-html: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2
      @tarojs/runtime: 3.6.2 => 3.6.2
      @tarojs/shared: 3.6.2 => 3.6.2
      @tarojs/taro: 3.6.2 => 3.6.2
      @tarojs/webpack-runner: 3.6.2 => 3.6.2
      babel-preset-taro: 3.6.2 => 3.6.2
      eslint-config-taro: 3.6.2 => 3.6.2
    npmGlobalPackages:
      typescript: 5.0.2

### Reproduction link（重现链接）
[https://github.com/](https://github.com/)

### Steps to reproduce（重现步骤）
1.初始化的时候v-model传入的事new Date() 对象，这个时候组件会定位到当前的年月
2.打开datepicker组件 随便选一个年月日点确定
3.打开组件，点击取消，然后在取消的方法里面重置v-model参数为new Date()对象，弹窗关闭
4.再次打开弹窗，发现组件定位的还是上次随便选的年月

### What is expected?（期望的结果是什么？）
点取消后 重新传入对象后，能定位到传入对象的年月

### What is actually happening?（实际的结果是什么？）
还是上一次选择的结果

**Comment by Xhyen** [comment]
设置 v-model的参数如 time.value = new Date() 
会变成"2023-03-27T03:09:29.845Z"

**Comment by eiinu** [comment]
`v4.0.5`已修复
