### ISSUE TITLE
Ecard 虚拟电子卡 文档问题

### ISSUE THREAD

**Issue by AndersonBY** [jdf2e/nutui#2207]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.3.0-alpha.5

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16

### Browser and its version（浏览器及其版本）
Chrome110

### System and its version（系统及其版本）
Windows11

### Reproduction link（重现链接）
[[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/ecard)](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/ecard)

### Steps to reproduce（重现步骤）
card-amount-min	其它面值最小值	number	1
card-amount-max	其他面值最大值	number	9999
card-buy-min	购买数量最小值	number	9999
card-buy-max	购买数量最大值	number	9999

card-buy和card-amount写反了

### What is expected?（期望的结果是什么？）
card-amount-min	购买数量最小值	number	1
card-amount-max	购买数量最大值	number	9999
card-buy-min	其它面值最小值	number	9999
card-buy-max	其他面值最大值	number	9999

### What is actually happening?（实际的结果是什么？）
反了

**Comment by eiinu** [comment]
从代码上看，card-amount 对应的是其他面值的金额，card-buy 对应的是购买的数量。文档标识的是正确的。
amount 这个词一般修饰像金额这种不可数名词的数量，可能容易产生误解，暂时优化一下文案描述，不调整API。
