### ISSUE TITLE
Tabs 组件在小程序环境下标题会出现左右滚动

### ISSUE THREAD

**Issue by rickx81** [jdf2e/nutui#2208]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.17.0

### Browser and its version（浏览器及其版本）
Microsoft Edge (111.0.1661.54)

### System and its version（系统及其版本）
Windows 11

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/tabs)

### Steps to reproduce（重现步骤）
Tabs 组件设置 type="smile" direction="vertical" 后，在小程序环境下标题会出现左右滚动
官方小程序也可复现

### What is expected?（期望的结果是什么？）
和 h5 端一样标题不出现滚动

### What is actually happening?（实际的结果是什么？）
标题出现左右滚动

https://user-images.githubusercontent.com/51046506/228419105-f77d8568-fa9a-4b0d-b83d-1d99adaeb409.mp4

**Comment by eiinu** [comment]
`v4.0.5`已修复
