### ISSUE TITLE
Picker 选择器的数据源应支持自定义label和key

### ISSUE THREAD

**Issue by sfwxp945** [jdf2e/nutui#2209]
### What problem does this feature solve?（这个功能解决的问题）
一般情况下，数据的来源均由后端给到前端，且，由于需求的多样性，导致不能保证每一次数据都是由text字段展示label，value字段做为key。需要一个功能可以指定text，value分别从什么字段获取。实际场景中几乎没有先天就有的text，value数据对，基本都要重新进行转换，比较费时间

### What does the proposed API look like?（期望的 API）
增加两个属性配置：textStr以及valueStr (如下)
```
<nut-picker
      v-model="selectedTime"
      :columns="multipleColumns"
      title="城市选择"
      @confirm="confirm"
      @change="change"
      textStr="aaa"
      valueStr="bbb"
    >
```
这样就可以自由的对展示值text,以及实际获取值value进行配置,无需重新转换数据了

**Comment by eiinu** [comment]
4.1.4+ 版本已支持
