### ISSUE TITLE
form 自定义校验validator不能自定义校验信息？？

### ISSUE THREAD

**Issue by golduck01** [jdf2e/nutui#2210]
### What problem does this feature solve?（这个功能解决的问题）
表单返回自定义校验信息

### What does the proposed API look like?（期望的 API）
我觉得其他element ui这样的校验就挺好的

**Comment by eiinu** [comment]
自定义校验信息具体指的是？可以提供一个使用场景和 demo 吗

**Comment by golduck01** [comment]
![WeChat7878875fa59fc0900d22329ca246b348](https://user-images.githubusercontent.com/36034429/229064131-98b76869-f9cd-47f2-87fa-c57c0d0132c8.png)

类似这样的场景 我想在validator里面输出任意的信息

**Comment by baoxiaowang** [comment]
+1 啥时候能解决啊发现源码里面取的都是 errorMessage 但是很多时候错误信息都是在接口返回后才知道
![image](https://github.com/jdf2e/nutui/assets/38904744/6fee428b-20ab-4787-87eb-9ecbabe9a4bb)

**Comment by baoxiaowang** [comment]
可以采取我这样的临时解决方法
![image](https://github.com/jdf2e/nutui/assets/38904744/e062b7dc-defe-47ed-9359-938f61076168)
