### ISSUE TITLE
Dialog 关闭后 没有移出 body上的 nut-overflow-hidden

### ISSUE THREAD

**Issue by eiinu** [jdf2e/nutui#2211]
### Discussed in https://github.com/jdf2e/nutui/discussions/2201

<div type='discussions-op-text'>

<sup>Originally posted by **xiaobei66** March 24, 2023</sup>
大佬们，Dialog开启后关闭就会干掉滚动条，检查一看 body上有一个开启时添加的 .nut-overflow-hidden类名 ，想要关掉时移出 但是不可能每个页面都去写一下吧 ，所以 怎么解决啊 ? 在线等！`class="nut-overflow-hidden"`</div>

**Comment by Formulaaa** [comment]
我也有这个问题，暂时的解决办法就是自己再封装一个函数，在beforeClose的时候移除那个类。看了一下源码，那个地方逻辑应该有问题，但是PR成本太高，搞了半天也没弄好。这块还有一个问题就是没法触发onCLosed函数，也是源码那块先unmount了，之后就没办法触发这个时间了。
