### ISSUE TITLE
CSS 类名单词拼写错误 warp -> wrap

### ISSUE THREAD

**Issue by JChehe** [jdf2e/nutui#2213]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.14.2

### Browser and its version（浏览器及其版本）
111.0.5563.147

### System and its version（系统及其版本）
Windows 11

### Taro environmental information（taro 环境信息）
  Taro CLI 3.6.2 environment info:
    System:      OS: Windows 10
    Binaries:      Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/cell)

### Steps to reproduce（重现步骤）
类名 nut-cell-gourp-warp 的 `warp` 是否拼写错误？正确拼写应该为 `wrap`

在代码仓库搜索 `warp` 发现还有 dialog、button 等文件出现这个拼写错误的单词。

### What is expected?（期望的结果是什么？）
`wrap`

### What is actually happening?（实际的结果是什么？）
`warp`

**Comment by eiinu** [comment]
代码已更新，预计 `4.0.5` 发布
