### ISSUE TITLE
nut-tabs 滚动区域受限，不能完整显示最后一项 item.title

### ISSUE THREAD

**Issue by JChehe** [jdf2e/nutui#2214]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.14.2

### Browser and its version（浏览器及其版本）
111.0.5563.147

### System and its version（系统及其版本）
Windows 11

### Taro environmental information（taro 环境信息）
```
Taro CLI 3.6.2 environment info: 
  System: OS: 
    Windows 10 
  Binaries: 
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE 
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
```

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/tabs)

https://user-images.githubusercontent.com/8402442/229301178-4bfac00c-e32c-4fad-94a1-d1e532f6bedf.mp4

### Steps to reproduce（重现步骤）

```
nut-tabs(
  name="tabs"
  :title-scroll="true"
  size="large"
  :title-gutter="20"
)
  nut-tab-pane(
    v-for="item in TAB_LIST"
    :key="item.key"
    :pane-key="item.key"
    :title="item.title"
  )
```
```
const TAB_LIST = [
  {
    key: 'item1',
    title: '我是 ITEM 1'
  },
  {
    key: 'item2',
    title: '我是 ITEM 2'
  },
  {
    key: 'item3',
    title: '我是 ITEM 3'
  },
  {
    key: 'item4',
    title: '我是 ITEM 4'
  },
]
```

### What is expected?（期望的结果是什么？）
能正确滚动到有边界。

### What is actually happening?（实际的结果是什么？）
最后一项 title 不能完整显示。

### Remarks（补充说明）
观察发现：正确滚动的 tabs，会出现 `nut-tabs__titles-placeholder`，而上面代码未出现该元素，可能是以下源代码片段导致该问题：

```
if (navRectRef.value) {
  const titlesTotalWidth = titleRects.reduce((prev: number, curr: RectItem) => prev + curr.width, 0);
  if (titlesTotalWidth > navRectRef.value.width) {
    canShowLabel.value = true;
  } else {
    canShowLabel.value = false;
  }
}
```

**Comment by eiinu** [comment]
`v4.0.5`已修复
