### ISSUE TITLE
swipe open 方法说明与效果不符

### ISSUE THREAD

**Issue by lovelyqun** [jdf2e/nutui#2216]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.3.0-alpha.6

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
106

### System and its version（系统及其版本）
window

### Taro environmental information（taro 环境信息）
  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.19.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/swipe)

### Steps to reproduce（重现步骤）
直接看官网提供的案例即可

### What is expected?（期望的结果是什么？）
left 打开左边
right 打开右边

### What is actually happening?（实际的结果是什么？）
left 打开右边
right 打开左边

**Comment by eiinu** [comment]
左右指的是 Swipe 向左滑和向右滑。
为了避免开发者升级后出现问题，暂时不修改其内部实现。名称上可能存在一些歧义，会在文档中增加详细说明。
