### ISSUE TITLE
[小程序][Picker] 动态增删列表项时，会导致当前选项错位

### ISSUE THREAD

**Issue by eiinu** [jdf2e/nutui#2219]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16

### Browser and its version（浏览器及其版本）
Chrome

### System and its version（系统及其版本）
MacOS

### Taro environmental information（taro 环境信息）
Taro 3.6.2

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/DatePicker)

### Steps to reproduce（重现步骤）
```vue
<template>
  <div class="demo">
    <nut-date-picker
      v-model="currentDate"
      :min-date="minDate"
      :max-date="maxDate"
      :is-show-chinese="true"
      @confirm="confirm"
      @change="change"
    ></nut-date-picker>
  </div>
</template>

<script setup>
import { ref } from 'vue'
const minDate = new Date()
const maxDate = new Date(2025, 10, 1)
const currentDate = new Date()
const confirm = ({ selectedValue, selectedOptions }) => {
  desc.value = selectedOptions.map((option) => option.text).join('')
}
const change = (val) => {
  console.log('change', val)
}
</script>
```

### What is expected?（期望的结果是什么？）
正常切换

### What is actually happening?（实际的结果是什么？）
在切换月份的时候，可能会导致日的错误更新。

**Comment by Zeppo241** [comment]
为何最新版4.1.2都没解决这个问题？
