### ISSUE TITLE
[bug]nut-scroller无法上拉加载 严重的大bug

### ISSUE THREAD

**Issue by 836438020** [jdf2e/nutui#222]
向上一拉就弹回来了 
有时候还会变成出现下拉加载的
<nut-scroller
          :is-un-more="isNoMore"
          :is-loading="isLoading"
          :type="'vertical'"
          @loadMore="onInfinite"
          @pulldown="pulldown"
        >
          <div slot="list" class="nut-vert-list-panel">
            <div class="nut-vert-list-item">
<ul><li></li></ul>
</div>
</div>
</nut-scroller>

**Comment by richard1015** [comment]
请提供详细复现代码，最好可以提供一个可复现仓库

**Comment by richard1015** [comment]
目前测试官方demo，是没问题的，请仔细阅读官网文档
