### ISSUE TITLE
【datepicker】文档和实际 api 不对应

### ISSUE THREAD

**Issue by shaddollxz** [jdf2e/nutui#2221]
### What problem does this feature solve?（这个功能解决的问题）
https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/datepicker
文档中关闭按钮的 emit 事件名为 cancel 实际上需要使用 `@close`设置关闭事件

### What does the proposed API look like?（期望的 API）
将文档中的 cancel 事件修改为 close

**Comment by eiinu** [comment]
你使用的应该是 NutUI 3.x 版本，对应的文档在这里：[3x DatePicker](https://nutui.jd.com/3x/#/zh-CN/component/DatePicker)。
从 3 到 4，DatePicker 将内部的 Popup 组件剥离出来，因此事件名从 Popup 的 close 变更为了 Picker 的 cancel。
