### ISSUE TITLE
[小程序][Popover] 页面滚动后，popover 显示错位

### ISSUE THREAD

**Issue by eiinu** [jdf2e/nutui#2225]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16

### Browser and its version（浏览器及其版本）
Chrome

### System and its version（系统及其版本）
MacOS

### Taro environmental information（taro 环境信息）
taro 3.6.2

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/Popover)

### Steps to reproduce（重现步骤）
先点开 popover，然后滚动页面。
先滚动页面，然后点开 popover。

### What is expected?（期望的结果是什么？）
先点开，后滚动，要么跟随，要么锁定禁止滚动。
先滚动页面，再点开，能出现在正确的位置。

### What is actually happening?（实际的结果是什么？）
H5 版本
- 先点开，后滚动，异常。
- 先滚动，后点开，正常。
Taro 版本
- 先点开，后滚动，正常。
- 先滚动，后点开，异常。

**Comment by zspggp** [comment]
你好，这个问题有计划在4.0.9或4.1.0中解决嘛？

**Comment by lanrenbulan** [comment]
除了错位，不能连续切换，比如有两个popover ,点击第二个时，第一个先闭，然后需要点第二个次

**Comment by emmmm-maker** [comment]
@eiinu 请问在小程序中 页面先滚动再触发 popover 导致popover位置错乱，有什么解决方案吗？

**Comment by Tomao2014** [comment]
问题又遇到了，2024年了，大佬们可有什么解决方案

**Comment by eiinu** [comment]
H5 页面上可以通过 clickAway 方法避免这种问题。
小程序下类似的操作都不支持，定位和滚动的问题很难处理。

**Comment by Tomao2014** [comment]
> H5 页面上可以通过 clickAway 方法避免这种问题。 小程序下类似的操作都不支持，定位和滚动的问题很难处理。

我项目是从`uni-app`迁移过来的，也是微信小程序，原先使用`tmui.design` UI框架，不存在这个问题
