### ISSUE TITLE
扩展nut-input，支持单位功能

### ISSUE THREAD

**Issue by JackYumg** [jdf2e/nutui#2228]
### What problem does this feature solve?（这个功能解决的问题）
单位展示问题
输入框输入数字，然后有单位在输入框末尾

### What does the proposed API look like?（期望的 API）
<nut-input  sub="km"/>

**Comment by eiinu** [comment]
建议直接使用 Input 的 right 插槽

**Comment by JackYumg** [comment]
抱歉，忘了说版本了，用的3.2.36




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月10日 09:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jdf2e/nutui] 扩展nut-input，支持单位功能 (Issue #2228) |

建议直接使用 Input 的 right 插槽

**Comment by eiinu** [comment]
3.x 最新版本为 3.3.7，Input 组件右侧有一个 button 插槽，可以放单位。
