### ISSUE TITLE
[question]Flex.install(Vue); 报错

### ISSUE THREAD

**Issue by z778856** [jdf2e/nutui#223]
## 你想知道什么？
错误提示
main.ts?bc82:19 Uncaught TypeError: _nutui_nutui_dist_packages_flex_flex_js__WEBPACK_IMPORTED_MODULE_20___default.a.install is not a function

## 描述你考虑过的替代方案
vue版本 4.2.3 nui版本2.2.1
## 其它

无

**Comment by richard1015** [comment]
https://github.com/richard1015/nutui-demo/tree/master/typescript
