### ISSUE TITLE
文档页面，屏幕尺寸小的时候预览窗口显示不完整

### ISSUE THREAD

**Issue by 7lhao** [jdf2e/nutui#2230]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.5

### Vue version（vue 版本）
3.3.0-alpha.9

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
window

### Reproduction link（重现链接）
[nutui.jd.com/h5/vue/4x/](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/overlay)

### Steps to reproduce（重现步骤）
如题

### What is expected?（期望的结果是什么？）
如题

### What is actually happening?（实际的结果是什么？）
如题

**Comment by eiinu** [comment]
可以提供一个截图或者屏幕相关参数吗？

**Comment by 7lhao** [comment]
屏幕尺寸1366x768



AHao
***@***.***

&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jdf2e/nutui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 下午3:05
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [jdf2e/nutui] 文档页面，屏幕尺寸小的时候预览窗口显示不完整 (Issue #2230)





 
可以提供一个截图或者屏幕相关参数吗？

**Comment by eiinu** [comment]
代码已修改，网站文档随下次版本发布更新
