### ISSUE TITLE
有计划开发Page组件么？

### ISSUE THREAD

**Issue by beanhacker** [jdf2e/nutui#2231]
像京东APP一样，访问新页面后，关闭，即可平滑的切换会旧页面，而且不会导致旧页面刷新。

**Comment by eiinu** [comment]
近期没有新增组件计划。
这个功能应该由 vue-router + keep-alive 实现。
小程序下也可以找到解决方案：[微信开放社区](https://developers.weixin.qq.com/community/develop/doc/000e6a9cde8a582ea09c7603858c00)。
因为依赖于环境提供的路由工具，所以它可能更适合作为一个插件工具而不是一个组件库组件🤔

**Comment by beanhacker** [comment]
哦，我是看到framework7有这个组件，虽然改造了VUE的路由表，但是这样做比较简单实用。
