### ISSUE TITLE
ActionSheet 希望增加一个底部适配 配置项 针对全面屏手机

### ISSUE THREAD

**Issue by Xhyen** [jdf2e/nutui#2232]
### What problem does this feature solve?（这个功能解决的问题）
底部弹出的时候 最下面的按钮有可能被iphone的那个横杠挡住

### What does the proposed API look like?（期望的 API）
无

**Comment by eiinu** [comment]
ActionSheet 组件支持透传 Popup 的属性，直接添加 safe-area-inset-bottom 属性即可。

**Comment by Xhyen** [comment]
> ActionSheet 组件支持透传 Popup 的属性，直接添加 safe-area-inset-bottom 属性即可。

好的，谢谢

**Comment by GauharChan** [comment]
> ActionSheet 组件支持透传 Popup 的属性，直接添加 safe-area-inset-bottom 属性即可。

props中看到有使用popup props声明了，但实际上没有运用传入的props呀
![image](https://github.com/jdf2e/nutui/assets/45651308/35f47142-b8d8-45aa-bc88-c29e549849c5)
