### ISSUE TITLE
nut-tabs设置title-scroll属性后，切换tab时未自动滚动

### ISSUE THREAD

**Issue by lSpikeSpiegel** [jdf2e/nutui#2233]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.0

### Vue version（vue 版本）
3.3.0-alpha.9

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.15.0 

### Browser and its version（浏览器及其版本）
微信开发者工具（1.06.2303220 win32-x64）

### System and its version（系统及其版本）
win10

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.7

  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/lSpikeSpiegel/nutui-issue-demo)

### Steps to reproduce（重现步骤）
npm i
npm run dev
打开微信开发者工具，切换nut-tab-pane，nut-tabs不会自动滚动

### What is expected?（期望的结果是什么？）
切换nut-tab-pane，nut-tabs会自动滚动

### What is actually happening?（实际的结果是什么？）
切换nut-tab-pane，nut-tabs不会自动滚动

**Comment by eiinu** [comment]
建议升级 4.0.5 版本，Tabs 的滚动有更新

**Comment by lSpikeSpiegel** [comment]
> 建议升级 4.0.5 版本，Tabs 的滚动有更新

感谢大佬，升级版本确实ok了
