### ISSUE TITLE
SideNavbarItem按需引入有拼写导致的问题

### ISSUE THREAD

**Issue by zspggp** [jdf2e/nutui#2235]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.6-beta.2

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:qq

### Citation method（引用方式）
npm

### Node version（node 版本）
16.19.0

### Browser and its version（浏览器及其版本）
无

### System and its version（系统及其版本）
Windows11

### Taro environmental information（taro 环境信息）
  Taro CLI 3.6.5-alpha.1 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.19.0 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - D:\nodejs\node_global\yarn.CMD
      npm: 9.6.1 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/components: ^3.6.5-alpha.1 => 3.6.5-alpha.1
      @tarojs/extend: ^3.6.5-alpha.1 => 3.6.5-alpha.1
      @tarojs/mini-runner: ^3.6.5-alpha.1 => 3.6.5-alpha.1
      @tarojs/plugin-framework-vue3: ^3.6.5-alpha.1 => 3.6.5-alpha.1
      @tarojs/plugin-html: ^3.6.5-alpha.1 => 3.6.5-alpha.1
      @tarojs/plugin-platform-qq: ^3.6.5-alpha.1 => 3.6.5-alpha.1
      @tarojs/runtime: ^3.6.5-alpha.1 => 3.6.5-alpha.1
      @tarojs/taro: ^3.6.5-alpha.1 => 3.6.5-alpha.1
      @tarojs/webpack-runner: ^3.6.5-alpha.1 => 3.6.5-alpha.1
      babel-preset-taro: ^3.6.5-alpha.1 => 3.6.5-alpha.1
      eslint-config-taro: ^3.6.5-alpha.1 => 3.6.5-alpha.1

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/sidenavbar)

### Steps to reproduce（重现步骤）
使用unplugin-vue-components按需引入，在build的时候会有报错。因为在@nutui/nutui-taro中拼写是SideNavbarItem，而按需引入时拼写是SideNavbaritem

### What is expected?（期望的结果是什么？）
期望能够正常的按需引入

### What is actually happening?（实际的结果是什么？）
WARNING in ./src/pages/index2/guildCronMessageAdd/index.vue?vue&type=template&id=ef202d36 (./node_modules/unplugin/dist/webpack/loaders/transform.js?unpluginName=unplugin-vue-components!./node_modules/babel-loader/lib!./node_modules/vue-loader/dist/templateLoader.js??ref--7!./node_modules/vue-loader/dist??ref--10-0!./src/pages/index2/guildCronMessageAdd/index.vue?vue&type=template&id=ef202d36) 100:39-62
"export 'SideNavbaritem' (imported as '__unplugin_components_7') was not found in '@nutui/nutui-taro'
 @ ./src/pages/index2/guildCronMessageAdd/index.vue?vue&type=template&id=ef202d36
 @ ./node_modules/@tarojs/taro-loader/lib/raw.js!./src/pages/index2/guildCronMessageAdd/index.vue
 @ ./src/pages/index2/guildCronMessageAdd/index.vue

**Comment by eiinu** [comment]
按需引入插件的规则是 spinal-case 与 CamelCase 的映射关系：
```
<nut-side-navbar-item />   ==>  SideNavbarItem
```
使用左边的书写方式，会去找右边名称的组件。

**Comment by zspggp** [comment]
> 按需引入插件的规则是 spinal-case 与 CamelCase 的映射关系：
> 
> ```
> <nut-side-navbar-item />   ==>  SideNavbarItem
> ```
> 
> 使用左边的书写方式，会去找右边名称的组件。

感谢大佬，一语中的。我是从nutui 3.x升级上来的，根据升级指南，替换没到位，按您说的修改后，测试通过了。
