### ISSUE TITLE
Checkbox 复选按钮 全选/半选/取消功能问题

### ISSUE THREAD

**Issue by yvette0907** [jdf2e/nutui#2237]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.2.40

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
14.19.3

### Browser and its version（浏览器及其版本）
Chrome(111.0.5563.147)

### System and its version（系统及其版本）
windows10

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.4

  Taro CLI 3.6.4 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.19.3 - E:\nodejs\node.EXE
      npm: 6.14.17 - E:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2
      @tarojs/components: 3.6.2 => 3.6.2
      @tarojs/helper: 3.6.2 => 3.6.2
      @tarojs/mini-runner: 3.6.2 => 3.6.2
      @tarojs/plugin-framework-vue3: 3.6.2 => 3.6.2
      @tarojs/plugin-html: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2
      @tarojs/runtime: 3.6.2 => 3.6.2
      @tarojs/shared: 3.6.2 => 3.6.2
      @tarojs/taro: 3.6.2 => 3.6.2
      @tarojs/webpack-runner: 3.6.2 => 3.6.2
      babel-preset-taro: 3.6.2 => 3.6.2
      eslint-config-taro: 3.6.2 => 3.6.2

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/checkbox)

### Steps to reproduce（重现步骤）
    1.打开官方组件库地址
    2.Checkbox复选按钮----- 全选/半选/取消这个样例
    3.点击组合复选框中的随机一项（假定为第一项）
    4.结果：其他三项组合复选框也被选中了，全选按钮也变为了选中状态而非半选状态

    ps:代码跑起来之后我发现是点击某项组合复选框时候，全选项的change事件也被触发了，然后走了toggleAll方法，其他的组合复选框项也被一起选上了。

### What is expected?（期望的结果是什么？）
”全选/半选/取消项“这个样例，点击一个组合复选框中的某一项，全选项显示半选状态，其他组合复选框不被勾上

### What is actually happening?（实际的结果是什么？）
”全选/半选/取消项“这个样例，点击一个组合复选框中的某一项，全选按钮变为了全选状态，其他组合复选框也全被勾上了

**Comment by eiinu** [comment]
demo 使用问题，仓库代码已更新，网站文档会跟着下个版本更新。
