### ISSUE TITLE
Tour 引导组件 使用后 Switch组件无法点击

### ISSUE THREAD

**Issue by zspggp** [jdf2e/nutui#2238]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.6-beta.2

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:qq

### Citation method（引用方式）
npm

### Node version（node 版本）
16.19.0

### Browser and its version（浏览器及其版本）
无

### System and its version（系统及其版本）
Windows 11

### Taro environmental information（taro 环境信息）
Taro CLI 3.6.5-alpha.1 environment info:
System:
OS: Windows 10 10.0.22621
Binaries:
Node: 16.19.0 - D:\nodejs\node.EXE
Yarn: 1.22.19 - D:\nodejs\node_global\yarn.CMD
npm: 9.6.1 - D:\nodejs\npm.CMD
npmPackages:
@tarojs/components: ^3.6.5-alpha.1 => 3.6.5-alpha.1
@tarojs/extend: ^3.6.5-alpha.1 => 3.6.5-alpha.1
@tarojs/mini-runner: ^3.6.5-alpha.1 => 3.6.5-alpha.1
@tarojs/plugin-framework-vue3: ^3.6.5-alpha.1 => 3.6.5-alpha.1
@tarojs/plugin-html: ^3.6.5-alpha.1 => 3.6.5-alpha.1
@tarojs/plugin-platform-qq: ^3.6.5-alpha.1 => 3.6.5-alpha.1
@tarojs/runtime: ^3.6.5-alpha.1 => 3.6.5-alpha.1
@tarojs/taro: ^3.6.5-alpha.1 => 3.6.5-alpha.1
@tarojs/webpack-runner: ^3.6.5-alpha.1 => 3.6.5-alpha.1
babel-preset-taro: ^3.6.5-alpha.1 => 3.6.5-alpha.1
eslint-config-taro: ^3.6.5-alpha.1 => 3.6.5-alpha.1

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/tour)

### Steps to reproduce（重现步骤）
官网的Tour演示效果即可测试。
点击Switch是无反应的。

### What is expected?（期望的结果是什么？）
期望Tour不影响Switch操作。

### What is actually happening?（实际的结果是什么？）
实际点击Switch无反应。

**Comment by eiinu** [comment]
原因是 Switch 组件需要绑定 v-model 才能使用，Tour 的 demo 中没有添加上，下次发版前会更新一下代码
