### ISSUE TITLE
tabs-tabpane下的日期选择框弹出到另一个tabs-tabpane下

### ISSUE THREAD

**Issue by 15603871022** [jdf2e/nutui#2244]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.3.6

### Vue version（vue 版本）
3.2.40

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18

### Browser and its version（浏览器及其版本）
所有浏览器都这样

### System and its version（系统及其版本）
win11

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/nutui3-vite-demo-forked-29nxyy)

### Steps to reproduce（重现步骤）
tabs里面创建两个tabpane， 第二个tabpane下如果有任何选择类型的组件（选择器或时间之类的），都会弹出的popup选择框都会在第一个tabpane下，必须切换tabpane从才能选择

### What is expected?（期望的结果是什么？）
在哪个tabpane下选择器弹出的popup就显示在对应的tabpane上

### What is actually happening?（实际的结果是什么？）
出现在非当前tabpane上

**Comment by eiinu** [comment]
datepicker 可以增加以下属性挂载到更高层级来避免这种问题。
```
<nut-datepicker teleport="#app" :teleportDisable="true" />
```

原因是 Tabs 和 Popup 可能存在定位样式上的冲突，后续会做优化。

**Comment by 15603871022** [comment]
好的 感谢解答




牛宏扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jdf2e/nutui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jdf2e/nutui] tabs-tabpane下的日期选择框弹出到另一个tabs-tabpane下 (Issue #2244)





 
datepicker 可以增加以下属性挂载到更高层级来避免这种问题。
 <nut-datepicker teleport="#app" :teleportDisable="true" /&gt;  
Tabs 和 Popup 样式可能存在定位样式冲突，后续会做优化。

**Comment by eiinu** [comment]
redirect to #2277
