### ISSUE TITLE
弹幕组件真机显示不正确

### ISSUE THREAD

**Issue by bo-tea** [jdf2e/nutui#2246]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.5

### Vue version（vue 版本）
3.2.44

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
19

### Browser and its version（浏览器及其版本）
weapp

### System and its version（系统及其版本）
ios

### Taro environmental information（taro 环境信息）
3.6.2

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/barrage)

### Steps to reproduce（重现步骤）
官方范例直接编译就行

### What is expected?（期望的结果是什么？）
弹幕显示正确

### What is actually happening?（实际的结果是什么？）
组件似乎无法正确获取区域宽度，导致--move-distance计算错误，进一步导致弹幕在动画过程中直接消失，从图中也能看出弹幕已经开始重叠
模拟器上显示是正常的，真机预览才出的问题。模拟器机型和真机都是iPhone X
![ddb76181d6f5b93aa8181cb0931fc3a](https://user-images.githubusercontent.com/61230488/233113940-188e8c32-95df-4e7b-a161-8b712ba36782.jpg)

**Comment by eiinu** [comment]
redirect #2440

**Comment by talent129** [comment]
不维护了吗，这个问题确实存在，根本用不了，而且弹幕文字如果较多，也会显示不全
