### ISSUE TITLE
nut-cell-group圆角问题

### ISSUE THREAD

**Issue by leon2017** [jdf2e/nutui#2248]
### What problem does this feature solve?（这个功能解决的问题）
无论是nut-cell-group还是 nut-cell设置round-radius ， nut-cell-group 都没有圆角

### What does the proposed API look like?（期望的 API）
可能是我的操作方式不对

**Comment by eiinu** [comment]
![image](https://user-images.githubusercontent.com/44915689/233306406-b610aff7-4b49-44bf-b6ca-9e110c622661.png)
Cell 上设置的 round-radius 仅对于单个 Cell 生效，通过 ConfigProvider 设置样式可以设置 CellGroup 的圆角
