### ISSUE TITLE
NutUI 3.x + vite + ts 不支持TSX语法

### ISSUE THREAD

**Issue by frontendWangqun** [jdf2e/nutui#2249]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.1.17

### Vue version（vue 版本）
3.2.6

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome（112.0.5615.121）

### System and its version（系统及其版本）
MACOS(12.3.1)

### Reproduction link（重现链接）
[github.com](https://github.com/jdf2e/nutui/issues/new/choose)

### Steps to reproduce（重现步骤）
渲染没问题，但是idea中有红线告警，如下：
JSX element class does not support attributes because it does not have a '$props' property JSX 元素类不支持特性，因为它不具有“$props”属性

### What is expected?（期望的结果是什么？）
支持TSX/JSX语法

### What is actually happening?（实际的结果是什么？）
idea中不支持JSX语法

**Comment by frontendWangqun** [comment]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/43572671/233318955-499ab498-9399-4750-b99e-ffe9df77df08.png">

**Comment by frontendWangqun** [comment]
> 你好 @frontendWangqun, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/s/eh6ck?resolutionWidth=414&resolutionHeight=736) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/43572671/233319301-79b464ce-d0c2-4a9b-86a8-21d263b8a4a1.png">

**Comment by eiinu** [comment]
Vetur 插件并不能很好的兼容 Vue3 语法，你可能需要更换到 Volar。
https://github.com/vuejs/language-tools/discussions/583
https://github.com/vuejs/vetur/issues/3416

**Comment by frontendWangqun** [comment]
> Vetur 插件并不能很好的兼容 Vue3 语法，你可能需要更换到 Volar。 [vuejs/language-tools#583](https://github.com/vuejs/language-tools/discussions/583) [vuejs/vetur#3416](https://github.com/vuejs/vetur/issues/3416)

将Vetur禁用掉，且更换到Volar也会出现同样警告，原因是nutui组件不是用jsx语法编写，而是用模板语法编写导致的，感谢回答。
