### ISSUE TITLE
FormItem 设置label-width无效

### ISSUE THREAD

**Issue by YujiaCheng1996** [jdf2e/nutui#2253]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.5

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
19.9.0

### Browser and its version（浏览器及其版本）
Chrome113

### System and its version（系统及其版本）
Windows

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.3

  Taro CLI 3.6.3 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 19.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
      npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2
      @tarojs/components: 3.6.2 => 3.6.2
      @tarojs/helper: 3.6.2 => 3.6.2
      @tarojs/plugin-framework-vue3: 3.6.2 => 3.6.2
      @tarojs/plugin-html: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2
      @tarojs/runtime: 3.6.2 => 3.6.2
      @tarojs/shared: 3.6.2 => 3.6.2
      @tarojs/taro: 3.6.2 => 3.6.2
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2
      babel-preset-taro: 3.6.2 => 3.6.2
      eslint-config-taro: 3.6.2 => 3.6.2

### Reproduction link（重现链接）
[nutui.jd.com/h5/vue/4x/](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/form)

### Steps to reproduce（重现步骤）
FormItem 设置label-width为20

### What is expected?（期望的结果是什么？）
变窄为20px

### What is actually happening?（实际的结果是什么？）
仍然很宽，甚至达到了146px

### Remarks（补充说明）
 cell组件这里有
 &__title {
    display: flex;
    flex-direction: column;
    flex: 1;
    min-width: 80px;
    &-desc {
      font-size: $cell-title-desc-font;
    }
  }
编译为css为
.nut-cell__title {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column;
    -webkit-flex: 1;
    -ms-flex: 1;
    flex: 1;
    min-width: 4rem;
}
使得所有比这个值小的都不生效！

**Comment by ntnyq** [comment]
使用权值更高的选择器局部覆盖掉 `.nut-cell__title` 的 `min-width`
