### ISSUE TITLE
date-picker 性能问题

### ISSUE THREAD

**Issue by lovelyqun** [jdf2e/nutui#2264]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.3

### Vue version（vue 版本）
3.3.0-alpha.13

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.19.1

### Browser and its version（浏览器及其版本）
112.0.5615.138

### System and its version（系统及其版本）
window10

### Taro environmental information（taro 环境信息）
 Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.19.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/lovelyqun/taro-nut-tsx.git)

### Steps to reproduce（重现步骤）
渲染多个date-picker组件
在微信小程序上非常卡顿

### What is expected?（期望的结果是什么？）
期望不卡顿

### What is actually happening?（实际的结果是什么？）
非常卡顿

**Comment by eiinu** [comment]
这种情况可以通过 custom-wrapper 组件，将多个 date-picker 分别包裹起来，避免 Taro 层级的重复 render

**Comment by lovelyqun** [comment]
加了，有好点，但是还是卡
