### ISSUE TITLE
nut-range绑定的值无法更新到组件

### ISSUE THREAD

**Issue by Hello-Huxu** [jdf2e/nutui#227]
:rangeValues.sync
目前我的需求是需要重置绑定的值，但是值改变了但无法更新改组件，感觉与vue视图无关，$set无效

**Comment by Hello-Huxu** [comment]
这个问题2.2.2版本还没有解决，时间赶，想要解决这个问题的童鞋可以把该组件直接拉到本地，定义一个方法重置一些值即可，好像不能贴图，具体改哪些，自己看看组件数据就知道了

**Comment by richard1015** [comment]
> 这个问题2.2.2版本还没有解决，时间赶，想要解决这个问题的童鞋可以把该组件直接拉到本地，定义一个方法重置一些值即可，好像不能贴图，具体改哪些，自己看看组件数据就知道了

期望提供一个  最小可复现仓库，方便这边开发人员进行复现跟进

**Comment by Hello-Huxu** [comment]
ok，我发群里

**Comment by undo03** [comment]
上次修复的时候理解有偏差，少watch了一个prop，现已修修复

**Comment by richard1015** [comment]
2.2.3已解决
