### ISSUE TITLE
当nut-popup搭配nut-checkboxgroup一起使用时, 每当关掉popup时, checkboxgroup绑定的v-model会自动减掉最后一个元素

### ISSUE THREAD

**Issue by starhao** [jdf2e/nutui#2270]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.6

### Vue version（vue 版本）
3.3.0-alpha.13

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18.16.0

### Browser and its version（浏览器及其版本）
112.0.5615.137

### System and its version（系统及其版本）
MacOS13.0

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/p/sandbox/nutui4-vite-demo-forked-80xlpr?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A32%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A32%2C%22startLineNumber%22%3A7%7D%5D)

### Steps to reproduce（重现步骤）
1,点开弹出层 
2,勾选弹出层的checkbox
3,点击界面其他位置, 让弹出层关闭
4,当前选中值所显示的值会自动减掉最后一个元素

### What is expected?（期望的结果是什么？）
关闭弹出层时, checkbox所选的值不变

### What is actually happening?（实际的结果是什么？）
当前选中值所显示的值会自动减掉最后一个元素

**Comment by eiinu** [comment]
关联 Issue/PR：#2189 #2190

**Comment by eiinu** [comment]
主要原因：
checkbox 销毁时（例如 v-for 场景），会导致 checkbox-group 上的 v-model 中移除对应的值，Popup 在关闭时默认会被销毁。
临时解决办法：
Popup 设置 destroy-on-close 为 false，不销毁，就不会导致 v-model 中的值变动。

下个版本 4.0.8 会优化该问题
