### ISSUE TITLE
NutUI4引入IconFont提示不能赋给类型“Plugin_2<[]>”的参数，Icon不显示

### ISSUE THREAD

**Issue by charle-xx** [jdf2e/nutui#2271]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.6

### Vue version（vue 版本）
3.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.19.1

### Browser and its version（浏览器及其版本）
Chrome

### System and its version（系统及其版本）
Macos

### Taro environmental information（taro 环境信息）
 Taro v3.6.6

  Taro CLI 3.6.6 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.1 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6
      @tarojs/components: 3.6.6 => 3.6.6
      @tarojs/helper: 3.6.6 => 3.6.6
      @tarojs/plugin-framework-vue3: 3.6.6 => 3.6.6
      @tarojs/plugin-html: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6
      @tarojs/router: 3.6.6 => 3.6.6
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/taro-h5: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6

### Reproduction link（重现链接）
[github.com](https://github.com/charle-xx/nutui-test)

### Steps to reproduce（重现步骤）
直接在app.ts引入IconFont，使用APP.user(IconFont)就会提示

### What is expected?（期望的结果是什么？）
期望icon正常显示

### What is actually happening?（实际的结果是什么？）
icon现在不显示

**Comment by eiinu** [comment]
可以先使用 `App.component('IconFont', IconFont)` 的方式注册组件，use 的方式暂时存在问题

**Comment by charle-xx** [comment]
> 可以先使用 `App.component('IconFont', IconFont)` 的方式注册组件，use 的方式暂时存在问题

好的，谢谢！
