### ISSUE TITLE
自动按需引入(unplugin-vue-components)，与自定义组合式函数冲突，出现白屏

### ISSUE THREAD

**Issue by ruixiaozi** [jdf2e/nutui#2273]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.6

### Vue version（vue 版本）
3.2.44

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.13.0

### Browser and its version（浏览器及其版本）
无

### System and its version（系统及其版本）
win10

### Taro environmental information（taro 环境信息）
  Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\npm_global\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6

### Reproduction link（重现链接）
[github.com/jdf2e/nutui/issues](https://github.com/jdf2e/nutui/issues)

### Steps to reproduce（重现步骤）
通过自动按需引入(unplugin-vue-components)的方式，同时页面组件使用<script lang="ts" setup>的方式，在script标签里面Import其他ts的内容。存在多个pages同时引用同一个ts文件时，运行白屏。

### What is expected?（期望的结果是什么？）
正常显示

### What is actually happening?（实际的结果是什么？）
运行白屏。

**Comment by eiinu** [comment]
unplugin 插件本身的作用是扫描组件代码并添加 import 语句，从原理上看应该不会对其他的代码引用产生影响。
如果仍未解决，建议提供可复现代码仓库。
