### ISSUE TITLE
第一次进入页面打开poup后date-picker在支付宝上面显示错误

### ISSUE THREAD

**Issue by JCqiu** [jdf2e/nutui#2274]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.6

### Vue version（vue 版本）
3.2.40

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18.13.0

### Browser and its version（浏览器及其版本）
Chrome(112.0.5615.138)

### System and its version（系统及其版本）
window10

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.5

undefined

  Taro CLI 3.6.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD    
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6 
      @tarojs/components: 3.6.6 => 3.6.6 
      @tarojs/helper: 3.6.6 => 3.6.6 
      @tarojs/plugin-framework-vue3: 3.6.6 => 3.6.6   
      @tarojs/plugin-html: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6

### Reproduction link（重现链接）
[github.com/jdf2e/nutui](https://github.com/jdf2e/nutui)

### Steps to reproduce（重现步骤）
date-picker在支付宝上面显示错误
![image](https://user-images.githubusercontent.com/16211027/236665136-3083ef9b-8903-47ad-8432-43d30d377e01.png)

### What is expected?（期望的结果是什么？）
显示正常

### What is actually happening?（实际的结果是什么？）
显示错误

**Comment by eiinu** [comment]
redirect to #2292
