### ISSUE TITLE
nut-uploader组件使用自定义上传方式(before-xhr-upload)拿不到真实的文件名

### ISSUE THREAD

**Issue by aisuandebowen** [jdf2e/nutui#2278]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.2.1

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16.0

### Browser and its version（浏览器及其版本）
Chrome( 86.0.4240.75)

### System and its version（系统及其版本）
Window10

### Taro environmental information（taro 环境信息）
  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/nutui3-vite-demo-forked-w78lle?file=/src/App.vue)

### Steps to reproduce（重现步骤）
1. 使用nut-uploader组件
2. 使用自定义上传方式(before-xhr-upload)
3. 打印options.taroFilePath

### What is expected?（期望的结果是什么？）
options.taroFilePath是真实的文件路径

### What is actually happening?（实际的结果是什么？）
options.taroFilePath不是真实的文件路径，文件名发生变化。

**Comment by eiinu** [comment]
Uploader 内部使用的是小程序的 chooseImage 或者 chooseMedia 接口，只能拿到临时文件路径，获取不到真实文件路径。[chooseMedia](https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html)

**Comment by aisuandebowen** [comment]
> Uploader 内部使用的是小程序的 chooseImage 或者 chooseMedia 接口，只能拿到临时文件路径，获取不到真实文件路径。[chooseMedia](https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html)

你好，请问下小程序里面是都拿不到真实路径，只能拿临时路径吗？有没有其他的解决方案？

**Comment by eiinu** [comment]
> > Uploader 内部使用的是小程序的 chooseImage 或者 chooseMedia 接口，只能拿到临时文件路径，获取不到真实文件路径。[chooseMedia](https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html)
> 
> 你好，请问下小程序里面是都拿不到真实路径，只能拿临时路径吗？有没有其他的解决方案？

暂时不了解有能获取到真实文件路径的微信小程序 API，可以到微信开放社区看看有没有解决方案

**Comment by CNBroderick** [comment]
您好，能否将 Taro.chooseMedia 替换  Taro.chooseMessageFile 实现：
```
Taro.chooseMessageFile({
    count: 1,
    success: (result) => console.log('chooseMessageFile', result),
})
```
### 参考：

1. [微信小程序文档](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html)
2. [Taro文档](https://taro-docs.jd.com/docs/apis/media/image/chooseMessageFile)
3. [Uploader代码地址](https://github.com/jdf2e/nutui/blob/v4/src/packages/__VUE/uploader/index.taro.vue)

### 选择后回调函数内容
```
{
  "errMsg": "chooseMessageFile:ok",
  "tempFiles": [
    {
      "name": "QQ截图20230613085524.png",
      "size": 2389391,
      "time": 1686617738,
      "path": "http://tmp/VoSkJ4MdMXtS0bf7b2e95831cc082c6d848b4550d829.png",
      "type": "image"
    }
  ]
}
```

**Comment by eiinu** [comment]
> 您好，能否将 Taro.chooseMedia 替换 Taro.chooseMessageFile 实现：
> 
> ```
> Taro.chooseMessageFile({
>     count: 1,
>     success: (result) => console.log('chooseMessageFile', result),
> })
> ```
> 
> ### 参考：
> 1. [微信小程序文档](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html)
> 2. [Taro文档](https://taro-docs.jd.com/docs/apis/media/image/chooseMessageFile)
> 3. [Uploader代码地址](https://github.com/jdf2e/nutui/blob/v4/src/packages/__VUE/uploader/index.taro.vue)
> 
> ### 选择后回调函数内容
> ```
> {
>   "errMsg": "chooseMessageFile:ok",
>   "tempFiles": [
>     {
>       "name": "QQ截图20230613085524.png",
>       "size": 2389391,
>       "time": 1686617738,
>       "path": "http://tmp/VoSkJ4MdMXtS0bf7b2e95831cc082c6d848b4550d829.png",
>       "type": "image"
>     }
>   ]
> }
> ```

这个接口只能选择「微信聊天会话中的文件」，无法上传本地文件，通用性不够，应该不太适合放到 Uploader 组件中

**Comment by CNBroderick** [comment]
当前的限制：
### Taro.chooseMedia：

1. 手机端只支持上传图片和视频。电脑端可以任意类型。
2. 手机和电脑的路径不同
     - 手机的路径为：wxfile://temp/xxxxxxxxxxx.png
     - 电脑的路径为：wxfile://temp/2026年06月06日改动内容.txt

### Taro.chooseMessageFile
- 手机端：支持微信内的聊天文件
- 电脑端：无法使用

看样子这个也只能作为补充项，而无法替代。
