### ISSUE TITLE
Tour组件重复点击会报错，多个Tour组件时部分气泡弹出位置错位

### ISSUE THREAD

**Issue by zspggp** [jdf2e/nutui#2289]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.7

### Vue version（vue 版本）
3.3.2

### Operating environment（运行环境）
dev:qq

### Citation method（引用方式）
npm

### Node version（node 版本）
16.20.0

### Browser and its version（浏览器及其版本）
无

### System and its version（系统及其版本）
Windows11

### Taro environmental information（taro 环境信息）
Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.20.0 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - D:\nodejs\node_global\yarn.CMD
      npm: 9.6.4 - D:\nodejs\node_global\npm.CMD
    npmPackages:
      @tarojs/components: ^3.6.6 => 3.6.6
      @tarojs/extend: ^3.6.6 => 3.6.6
      @tarojs/plugin-framework-vue3: ^3.6.6 => 3.6.6
      @tarojs/plugin-html: ^3.6.6 => 3.6.6
      @tarojs/plugin-platform-qq: ^3.6.6 => 3.6.6
      @tarojs/runtime: ^3.6.6 => 3.6.6
      @tarojs/taro: ^3.6.6 => 3.6.6
      @tarojs/webpack5-runner: ^3.6.6 => 3.6.6
      babel-preset-taro: ^3.6.6 => 3.6.6
      eslint-config-taro: ^3.6.6 => 3.6.6

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/tour)

### Steps to reproduce（重现步骤）
重复点击Tour组件的展示开关

### What is expected?（期望的结果是什么？）
期望无报错，且气泡展示位置正确。

### What is actually happening?（实际的结果是什么？）
多次点击Tour组件的展示开关，会出现报错：
Unhandled promise rejection TypeError: Cannot read properties of null (reading 'top')
如果页面存在多个Tour组件，部分气泡的弹出显示位置会错位。

**Comment by eiinu** [comment]
问题重定向 #2225
