### ISSUE TITLE
fork 仓库文件本地build:taro:vue，nutui\publish\nutui-taro\dist 文件替换 测试环境 taro\node_modules\@nutui\nutui-taro\dist 文件编译trao 报错，远程pnpm @nutui 包编译没问题 

### ISSUE THREAD

**Issue by hisunny520** [jdf2e/nutui#2291]
### What problem does this feature solve?（这个功能解决的问题）
可以本地 修改组件 build，测试环境能编译测试  

报错  fork 文件和测试环境pnpm sass , pnpm i 多次没用

#✖ Errors: 

#SassError: SassError: Can't find stylesheet to import.
  ╷
1 │ @import '@nutui/nutui-taro/dist/styles/variables.scss';
 │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  ..\nutui\publish\nutui-taro\dist\packages\badge\index.scss 1:9  root stylesheet

→ Watching... [2023/5/15 12:07:41]

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {        
  code: 'ERR_UNHANDLED_REJECTION'
}

环境

"dependencies": {
    "@babel/runtime": "^7.7.7",
    "@nutui/icons-vue-taro": "^0.0.9",
    "@nutui/nutui-taro": "^4.0.6",
    "@tarojs/components": "3.6.6",
    "@tarojs/helper": "3.6.6",
    "@tarojs/plugin-framework-vue3": "3.6.6",
    "@tarojs/plugin-html": "^3.6.6",
    "@tarojs/plugin-http": "^3.6.6",
    "@tarojs/plugin-platform-alipay": "3.6.6",
    "@tarojs/plugin-platform-h5": "3.6.6",
    "@tarojs/plugin-platform-jd": "3.6.6",
    "@tarojs/plugin-platform-qq": "3.6.6",
    "@tarojs/plugin-platform-swan": "3.6.6",
    "@tarojs/plugin-platform-tt": "3.6.6",
    "@tarojs/plugin-platform-weapp": "3.6.6",
    "@tarojs/runtime": "3.6.6",
    "@tarojs/shared": "3.6.6",
    "@tarojs/taro": "3.6.6",
    "@vue/runtime-core": "^3.3.2",
    "axios": "^1.4.0",
    "pinia": "^2.0.36",
    "taro-plugin-pinia": "^1.0.0",
    "tarojs-router-next": "^3.2.0",
    "tarojs-router-next-plugin": "^3.2.0",
    "vue": "^3.2.40"
  }
  

"devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/cli": "3.6.6",
    "@tarojs/webpack5-runner": "3.6.6",
    "@types/node": "^18.15.11",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.20.0",
    "@vue/babel-plugin-jsx": "^1.0.6",
    "@vue/compiler-sfc": "^3.0.0",
    "add": "^2.0.6",
    "babel-preset-taro": "3.6.6",
    "cache-loader": "^4.1.0",
    "css-loader": "3.4.2",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.6.6",
    "eslint-plugin-vue": "^8.0.0",
    "sass": "^1.62.1",
    "style-loader": "1.3.0",
    "stylelint": "9.3.0",
    "taro-plugin-compiler-optimization": "^1.0.4",
    "terser-webpack-plugin": "^5.3.8",
    "thread-loader": "^4.0.1",
    "ts-node": "^10.9.1",
    "typescript": "^4.1.0",
    "unplugin-vue-components": "^0.23.0",
    "vue-loader": "^17.0.0",
    "webpack": "^5.78.0"
  }

### What does the proposed API look like?（期望的 API）
可以本地 修改组件 build，测试环境能编译测试

**Comment by eiinu** [comment]
可以提供一下测试环境的仓库代码吗？

**Comment by hisunny520** [comment]
@eiinu  原因已找到了，不能用pnpm link ,直接替换可用
