### ISSUE TITLE
NutUI最新的版本按照文档安装引入找不到模块

### ISSUE THREAD

**Issue by RemiHoston** [jdf2e/nutui#230]
是文档过时了还是 最新的版本不稳定呢?
 
import NutUI from '@nutui/nutui'

====================

* @nutui/nutui in ./src/main.js

To install it, you can run: npm install --save @nutui/nutui

**Comment by RemiHoston** [comment]
Version 2.2.2

**Comment by richard1015** [comment]
> 是文档过时了还是 最新的版本不稳定呢?
> 
> import NutUI from '@nutui/nutui'
> 
> ====================
> 
> * @nutui/nutui in ./src/main.js
> 
> To install it, you can run: npm install --save @nutui/nutui

2.2.2版本 建议先采用按需加载模式

 import { Button, Toast, Infiniteloading, Swiper, Switch } from '@nutui/nutui';
 console.log(Button, Toast, Infiniteloading, Swiper, Switch)
 Button.install(Vue);
 Switch.install(Vue);

**Comment by richard1015** [comment]
v2.2.2 修复包  替换 项目下 node_module/@nutui/nutui/dist 即可
[dist.zip](https://github.com/jdf2e/nutui/files/4419344/dist.zip)

**Comment by richard1015** [comment]
最新版已解决，感谢您的反馈 @RemiHoston
