### ISSUE TITLE
下拉刷新，滚动刷新

### ISSUE THREAD

**Issue by zj770660841** [jdf2e/nutui#2300]
### What problem does this feature solve?（这个功能解决的问题）
我发现vue3版本的nutUI 有下拉刷新跟滚动刷新，但是taro小程序版本里的Nutui4，没有下拉刷新跟滚动刷新

### What does the proposed API look like?（期望的 API）
taro + Nutui4.0.7版本 + vue3  版本没有下拉刷新
希望添加下拉刷新，滚动刷新

**Comment by eiinu** [comment]
[ScrollView](https://docs.taro.zone/docs/components/viewContainer/scroll-view)
Taro 的 ScrollView 组件已经有了类似的功能（包括下拉刷新、滚动到底部等事件），因此 NutUI 4.0 没有提供对应的组件。
