### ISSUE TITLE
期望增加 Chat 交互组件

### ISSUE THREAD

**Issue by larrykoo711** [jdf2e/nutui#2304]
### What problem does this feature solve?（这个功能解决的问题）
ChatGPT 的发布，带来了很多需要开发 Chat 对话窗口的 UI 需求，可以快速通过 NutUI 完成 Chat 交互 UI 的开发

### What does the proposed API look like?（期望的 API）
有一个 React 的  https://chatui.io/ 希望 NutUI 有一个 Vue 版本的，小程序版本的

**Comment by xiamu14** [comment]
也有类似的需求，希望能出类似的小程序版本 ，taro 的

**Comment by ifwrong** [comment]
为什么关了呢？
