### ISSUE TITLE
关于Tabbar的问题重复点击一个TAB的时候会报错

### ISSUE THREAD

**Issue by jendy2012** [jdf2e/nutui#231]
![image](https://user-images.githubusercontent.com/2418263/78258084-4b911980-752d-11ea-9128-203a35eef33b.png)

**Comment by richard1015** [comment]
感谢您的反馈，我们这边尽快跟进此问题

**Comment by zhenyulei** [comment]
您好 感谢您的反馈 问题已经修复 在下个版本中更新此问题～

**Comment by richard1015** [comment]
2.2.3已解决

**Comment by Helen403** [comment]
Tabbar的选中颜色和未选中颜色可以设置吗？
