### ISSUE TITLE
「疑问」popup 的 lock-scroll 到底支不支持？

### ISSUE THREAD

**Issue by wenfangdu** [jdf2e/nutui#2310]
小程序版的 nutui 文档上写着支持：
![image](https://github.com/jdf2e/nutui/assets/28700378/1beed105-de79-412d-9cf8-78518627399a)
实际用没效果，看了几个相关 issue：#935 #1282，都是说不支持，需要自己实现，既然不支持，那就把文档上这个属性去掉吧。

**Comment by eiinu** [comment]
Popup 内部使用 catchMove 实现了阻止滚动穿透。
微信开发者工具中需要测试鼠标点击后滑动，如果使用鼠标滚轮滚动是没有效果的。

**Comment by wenfangdu** [comment]
@eiinu 是不是代码重构的时候给去掉了？[PR 里是有的](https://github.com/jdf2e/nutui/pull/1338/files)。
![image](https://github.com/jdf2e/nutui/assets/28700378/6b26d87d-ed3e-434f-9939-48591581dce2)
![image](https://github.com/jdf2e/nutui/assets/28700378/d3344bb2-6360-446e-94c2-70f46f6c362c)

**Comment by wenfangdu** [comment]
@eiinu 试试 https://github.com/jdf2e/nutui/pull/2311 行不
