### ISSUE TITLE
CSS 变量覆盖功能不生效

### ISSUE THREAD

**Issue by parabolazz** [jdf2e/nutui#2312]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.8

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.12.1

### Browser and its version（浏览器及其版本）
Chrome 113/最新版微信开发者工具

### System and its version（系统及其版本）
macOS 13

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.6

  Taro CLI 3.6.6 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6 
      @tarojs/components: 3.6.6 => 3.6.6 
      @tarojs/helper: 3.6.6 => 3.6.6 
      @tarojs/plugin-framework-vue3: 3.6.6 => 3.6.6 
      @tarojs/plugin-html: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6 
      @tarojs/plugin-vue-devtools: 3.6.6 => 3.6.6 
      @tarojs/runtime: 3.6.6 => 3.6.6 
      @tarojs/shared: 3.6.6 => 3.6.6 
      @tarojs/taro: 3.6.6 => 3.6.6 
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6 
      babel-preset-taro: 3.6.6 => 3.6.6 
      eslint-config-taro: 3.6.6 => 3.6.6 

### Reproduction link（重现链接）
[github.com](https://github.com/parabolazz/nutui-css-test.git)

### Steps to reproduce（重现步骤）
npm run dev:weapp

### What is expected?（期望的结果是什么？）
按钮的颜色是绿色的

### What is actually happening?（实际的结果是什么？）
![image](https://github.com/jdf2e/nutui/assets/17560446/754de32a-e741-4bdf-ae83-4c12ac063242)

按钮的颜色是红色的

**Comment by eiinu** [comment]
![image](https://github.com/jdf2e/nutui/assets/44915689/0de15cd7-194d-462f-ae8e-45e070bbf045)
这里的选择器是 「page,」 多了一个逗号，没有匹配上。
把选择器调整为 `:root, page` 或者把这个分组选择器拆开写就正常了，可能是微信小程序的 bug。

**Comment by eiinu** [comment]
用微信小程序原生项目测试了一下 css 变量，如果写 `page, :root` 这种分组选择器确实是没有效果的

**Comment by parabolazz** [comment]
微信小程序这么坑爹！能否麻烦在文档里备注一下呢？我参照文档写的但是一直没生效，就一直很摸不着头脑
<img width="1019" alt="image" src="https://github.com/jdf2e/nutui/assets/17560446/ae5f667c-4604-4b7a-ba06-027759b7569b">

**Comment by eiinu** [comment]
> 微信小程序这么坑爹！能否麻烦在文档里备注一下呢？我参照文档写的但是一直没生效，就一直很摸不着头脑 <img alt="image" width="1019" src="https://user-images.githubusercontent.com/17560446/241615991-ae5f667c-4604-4b7a-ba06-027759b7569b.png">

下次发版的时候更新一下，感谢反馈
