### ISSUE TITLE
[bug] nutui-vue版本中 Sticky 组件没有达到预期效果

### ISSUE THREAD

**Issue by wellfrog16** [jdf2e/nutui#2314]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-vue version（nutui-vue 版本）

4.0.8

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.16.0

### Browser and its version（浏览器及其版本）
chrome最新版本

### System and its version（系统及其版本）
window10

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.6

  Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.16.0 - D:\nodejs\node.EXE
      npm: 9.5.1 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6
      @tarojs/components: 3.6.6 => 3.6.6
      @tarojs/helper: 3.6.6 => 3.6.6
      @tarojs/plugin-framework-vue3: 3.6.6 => 3.6.6  
      @tarojs/plugin-html: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6     
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6     
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6     
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6   
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6     
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6  
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6        
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/sticky)

### Steps to reproduce（重现步骤）
查看官方示例即可，且小程序官方示例内容以div展示。手机扫码查看也可以复现

### What is expected?（期望的结果是什么？）
正确的演示结果，多种参数展示方式

### What is actually happening?（实际的结果是什么？）
不符合预期

**Comment by lihuangshuaige** [comment]
遇到了   官方解决了吗？
