### ISSUE TITLE
searchBar搜索栏无法点击

### ISSUE THREAD

**Issue by emmmm-maker** [jdf2e/nutui#2317]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.8

### Vue version（vue 版本）
3.2.40

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16.0

### Browser and its version（浏览器及其版本）
微信小程序模拟器

### System and its version（系统及其版本）
MacOs(13.0)

### Taro environmental information（taro 环境信息）
Taro CLI 3.6.7 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 9.4.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.7 => 3.6.7 
      @tarojs/components: 3.6.7 => 3.6.7 
      @tarojs/helper: 3.6.7 => 3.6.7 
      @tarojs/plugin-framework-vue3: 3.6.7 => 3.6.7 
      @tarojs/plugin-html: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-alipay: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-h5: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-jd: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-qq: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-swan: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-tt: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-weapp: 3.6.7 => 3.6.7 
      @tarojs/runtime: 3.6.7 => 3.6.7 
      @tarojs/shared: 3.6.7 => 3.6.7 
      @tarojs/taro: 3.6.7 => 3.6.7 
      @tarojs/webpack5-runner: 3.6.7 => 3.6.7 
      babel-preset-taro: 3.6.7 => 3.6.7 
      eslint-config-taro: 3.6.7 => 3.6.7 
    npmGlobalPackages:
      typescript: 4.8.4

### Reproduction link（重现链接）
[github.com](https://github.com/emmmm-maker/SearchBarTest)

### Steps to reproduce（重现步骤）
运行yarn dev:weapp 首页及分类页面的SearchBar组件无法被点击，placeholder也无法显示，如果第一次运行yarn dev:weapp正常，请结束当前编译，再次运行yarn dev:weapp看下

### What is expected?（期望的结果是什么？）
SearchBar可以正常点击进行输入

### What is actually happening?（实际的结果是什么？）
SearchBar可以无法点击，无法弹出键盘，placeholder无法正常显示

### Remarks（补充说明）
如果编译后正常，请尝试进行再次运行yarn dev:weapp 或 npm run  dev:weapp

**Comment by eiinu** [comment]
<img width="414" alt="image" src="https://github.com/jdf2e/nutui/assets/44915689/7676eb93-aa6c-4968-a961-8d615f3d8c4a">

在出现如上警告时，Taro 的一部分原生组件是丢失的，使用第三方组件库（NutUI、TaroUI 等）时，如果开启了 prebundle 或者 cache，就经常出现这个问题，例如 https://github.com/NervJS/taro/issues/12553
解决办法就是在 `config/index.js` 中关闭 cache

**Comment by emmmm-maker** [comment]
好的，感谢~
