### ISSUE TITLE
期望v4有 video 组件

### ISSUE THREAD

**Issue by orange-juzipi** [jdf2e/nutui#2319]
### What problem does this feature solve?（这个功能解决的问题）
可以为某个商品演示、介绍或首页上介绍某些需求。

### What does the proposed API look like?（期望的 API）
与v3的功能差不多即可，或者有更丰富的功能就更好了。

**Comment by eiinu** [comment]
[Taro/Video](https://docs.taro.zone/docs/components/media/video)
建议使用这个，Taro 已经提供了功能足够丰富的 Video 组件
