### ISSUE TITLE
安卓部分手机不兼容（华为 Honor Play4T Pro）

### ISSUE THREAD

**Issue by blue0728** [jdf2e/nutui#2320]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.8

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
cdn

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
支付宝客户端10.3.80

### System and its version（系统及其版本）
HarmonyOs Mate40 Pro  12  

### Reproduction link（重现链接）
[codepen.io](https://codepen.io/blue0728/pen/bGmPxjw)

### Steps to reproduce（重现步骤）
使用支付宝客户端扫码访问

### What is expected?（期望的结果是什么？）
正常访问

### What is actually happening?（实际的结果是什么？）
白屏

### Remarks（补充说明）
目前测试了几台华为手机都是有问题的

**Comment by eiinu** [comment]
NutUI 使用 Vue3 编写 Vite4 构建 [Vite 构建生产版本](https://cn.vitejs.dev/guide/build.html)
白屏问题可能是因为支付宝内浏览器内核版本较低，某些语法不可用，可以尝试在项目中引入 `@vitejs/plugin-legacy` 等插件做兼容适配

**Comment by blue0728** [comment]
> NutUI 使用Vue3 编写Vite4 构建[Vite 构建生成版本](https://cn.vitejs.dev/guide/build.html) 白屏问题可能是因为支持支付宝内部浏览器内部版本比较低，某些语言法不可用，可以试试在项目中引入`@vitejs/plugin-legacy`等插件做兼容合适配

为什么不构建成 es2015 呢？这样 CDN 使用，不存在兼容性问题了

https://github.com/jdf2e/nutui/compare/v4...blue0728:nutui:fix-vite-build-es2015

**Comment by eiinu** [comment]
> > NutUI 使用Vue3 编写Vite4 构建[Vite 构建生成版本](https://cn.vitejs.dev/guide/build.html) 白屏问题可能是因为支持支付宝内部浏览器内部版本比较低，某些语言法不可用，可以试试在项目中引入`@vitejs/plugin-legacy`等插件做兼容合适配
> 
> 为什么不构建成 es2015 呢？这样 CDN 使用，不存在兼容性问题了
> 
> [v4...blue0728:nutui:fix-vite-build-es2015](https://github.com/jdf2e/nutui/compare/v4...blue0728:nutui:fix-vite-build-es2015)

可以提交 PR，会合并到 4.0.9 发布
