### ISSUE TITLE
Form组件，输入组件有划线

### ISSUE THREAD

**Issue by lanrenbulan** [jdf2e/nutui#2321]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.8

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.1

### Browser and its version（浏览器及其版本）
113.0.5672.12

### System and its version（系统及其版本）
window11

### Taro environmental information（taro 环境信息）
Taro CLI 3.6.7 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.7 => 3.6.7
      @tarojs/components: 3.6.7 => 3.6.7
      @tarojs/helper: 3.6.7 => 3.6.7
      @tarojs/plugin-framework-vue3: 3.6.7 => 3.6.7
      @tarojs/plugin-html: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-alipay: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-h5: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-jd: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-qq: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-swan: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-tt: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-weapp: 3.6.7 => 3.6.7
      @tarojs/runtime: 3.6.7 => 3.6.7
      @tarojs/shared: 3.6.7 => 3.6.7
      @tarojs/taro: 3.6.7 => 3.6.7
      @tarojs/webpack5-runner: 3.6.7 => 3.6.7
      babel-preset-taro: 3.6.7 => 3.6.7
      eslint-config-taro: 3.6.7 => 3.6.7

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/guide/intro)

### Steps to reproduce（重现步骤）
官方示例能重现，扫描示例：https://nutui.jd.com/taro/vue/4x/#/zh-CN/guide/intro

### What is expected?（期望的结果是什么？）
微信小程序：输入组件无有下划线
京东小程序：textarea的placeholder显示正常
支付宝小程序：没有上面两个问题

### What is actually happening?（实际的结果是什么？）

* 微信小程序：输入组件有下划线
![c8eafae23c5ad1d93dec434d591f292](https://github.com/jdf2e/nutui/assets/9604624/d7266897-f820-4ba7-bbf5-3df4d1b14b5b)

* 京东小程序：textarea的placeholder显示不正常，滑动后显示的位置延时一会才正确，而且颜色也不对
![5918b326f755dc615363d12d5985e88](https://github.com/jdf2e/nutui/assets/9604624/db0720dc-a2ff-4dd8-90d4-223bf8bd6476)

### Remarks（补充说明）
iphone 8 plus / 14.7.1

**Comment by eiinu** [comment]
各平台小程序的审核发布流程比较长，所以一般不会跟着组件库的版本更新。
微信小程序下 Form input 的下划线在 4.0.8 中实际是没有的，已上架最新版本。
京东小程序对应版本更早，在 4.0.8 下没有复现延时问题，placeholder 是京东小程序平台的默认颜色，没有做特殊设置。
感谢反馈。
