### ISSUE TITLE
NutUI-vue ImagePreview 组件函数式打开图片且关闭后，页面无法滚动

### ISSUE THREAD

**Issue by leezhian** [jdf2e/nutui#2325]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.8

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18.8

### Browser and its version（浏览器及其版本）
Chrome(113.0.5672.126)

### System and its version（系统及其版本）
MacOS13.0

### Reproduction link（重现链接）
[codesandbox.io/s/ky24xj](https://codesandbox.io/s/ky24xj?file=/src/App.vue)

### Steps to reproduce（重现步骤）
官方案例代码即可触发。
1. 点击 “函数式调用的图片预览” 按钮触发显示图片
2. 点击图片退出预览。
3. 页面无法滚动。
原因是 ImagePreview 组件为了阻止预览时背景滚动，因此在 body 上加了 `nut-overflow-hidden` 类；但在预览关闭时没有进行移除，导致打开一次预览后页面就无法滚动了。

### What is expected?（期望的结果是什么？）
页面能滚动。

### What is actually happening?（实际的结果是什么？）
页面无法滚动。

### Remarks（补充说明）
如果页面本身就无法滚动，在一页内是没有问题的，即使是触发bug也无大碍，但页面超出一页后  `nut-overflow-hidden` 会隐藏超出的内容导致无法滚动。

**Comment by eiinu** [comment]
关联问题 #2211
