### ISSUE TITLE
给Notify、Toast等组件增加函数打开的方式

### ISSUE THREAD

**Issue by CS-liujf** [jdf2e/nutui#2334]
### What problem does this feature solve?（这个功能解决的问题）
以Notify组件为例，目前使用他得在当前页面放置该组件，并通过show属性控制显隐，但有的时候希望能直接通过函数打开它，这样会更加解耦合，比如在我的request.ts(用于封装axios)中打开Notify。

### What does the proposed API look like?（期望的 API）
```js
import Notify from 'nut-ui'
Notify.warning()
Notify.success()
```

**Comment by eiinu** [comment]
`@nutui/nutui` 中提供了 showToast、showNotify 等四个函数
`@nutui/nutui-taro` 中没有提供，原因是小程序环境限制，无法实现类似功能
