### ISSUE TITLE
Dialog 对话框

### ISSUE THREAD

**Issue by momtboy** [jdf2e/nutui#2336]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.8

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.13.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
window10

### Reproduction link（重现链接）
[codesandbox.io/s/bknjpg](https://codesandbox.io/s/bknjpg?file=/src/App.vue)

### Steps to reproduce（重现步骤）
点击显示弹窗，点击遮罩，弹窗被关闭

### What is expected?（期望的结果是什么？）
点击遮罩，弹窗不关闭

### What is actually happening?（实际的结果是什么？）
弹窗被关闭

**Comment by eiinu** [comment]
通过 close-on-click-overlay 属性可以控制 Dialog 点击遮罩时是否关闭，默认值为 true。
之前的版本未生效，已修复，4.0.9 发布。
