### ISSUE TITLE
小程序下事件捕获执行问题

### ISSUE THREAD

**Issue by lanrenbulan** [jdf2e/nutui#2338]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-vue version（nutui-vue 版本）

4.0.8

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
v16.14.2

### Browser and its version（浏览器及其版本）
114.0.5735.110

### System and its version（系统及其版本）
window11

### Taro environmental information（taro 环境信息）
 Taro CLI 3.6.7 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.14.2 - D:\software\nodejs\node.EXE
      Yarn: 1.22.15 - D:\software\nodejs\yarn.CMD
      npm: 8.19.2 - D:\software\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.7 => 3.6.7
      @tarojs/components: 3.6.7 => 3.6.7
      @tarojs/helper: 3.6.7 => 3.6.7
      @tarojs/plugin-framework-vue3: 3.6.7 => 3.6.7
      @tarojs/plugin-html: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-alipay: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-h5: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-jd: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-qq: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-swan: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-tt: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-weapp: 3.6.7 => 3.6.7
      @tarojs/runtime: 3.6.7 => 3.6.7
      @tarojs/shared: 3.6.7 => 3.6.7
      @tarojs/taro: 3.6.7 => 3.6.7
      @tarojs/webpack5-runner: 3.6.7 => 3.6.7
      babel-preset-taro: 3.6.7 => 3.6.7
      eslint-config-taro: 3.6.7 => 3.6.7

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/p/sandbox/hardcore-chatelet-nh35f1?file=%2Fsrc%2FApp.vue%3A3%2C6-3%2C7)

### Steps to reproduce（重现步骤）
重现链接是H5下的，是没问题的，但小程序有问题

### What is expected?（期望的结果是什么？）
小程序下，Parent组件的@click.capture先执行， 子组件的@click事件后执行

### What is actually happening?（实际的结果是什么？）
小程序下，实际是子组件@click先执行，父组件的@click.capture后执行

### Remarks（补充说明）
小程序下有问题，h5下没问题

**Comment by eiinu** [comment]
小程序下的事件机制是 Taro 框架的逻辑层实现的，似乎并没有对 capture 进行支持，参考 https://github.com/NervJS/taro/issues/11807
可以移步 [NervJS/Taro](https://github.com/NervJS/taro/issues) 进行讨论
