### ISSUE TITLE
AddressList插槽点击事件只能获取event获取不到item

### ISSUE THREAD

**Issue by Ouopoulos** [jdf2e/nutui#2358]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.9

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
开发者工具

### System and its version（系统及其版本）
Win10

### Taro environmental information（taro 环境信息）
Taro 3.6.7

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/addresslist)

### Steps to reproduce（重现步骤）
  <nut-address-list
    :data="data"
    swipe-edition
    show-bottom-button
    @del-icon="delClick"
    @edit-icon="editClick"
    @click-item="clickItem"
    @add="addAddress"
    
    :data-options="dataOptions"
  >
  <template #item-icon>
    <Edit  @click="onEdit"/>
  </template>
  <template #swipe-right>
    <nut-button type='default' shape="square" style="height: 100%;" @click="defClickSwipe">设置默认</nut-button>
    <nut-button type='primary' shape="square" style="height: 100%;" @click="delClickSwipe">删除</nut-button>

### What is expected?（期望的结果是什么？）
获取item

### What is actually happening?（实际的结果是什么？）
只能拿到event

**Comment by Ouopoulos** [comment]
edit-icon也拿不到

**Comment by eiinu** [comment]
计划通过具名作用域插槽传递每个列表项的数据
