### ISSUE TITLE
nut-card无法禁用vip-price

### ISSUE THREAD

**Issue by Ouopoulos** [jdf2e/nutui#2359]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.9

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
开发者工具

### System and its version（系统及其版本）
Win10

### Taro environmental information（taro 环境信息）
Taro 3.6.7

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/card)

### Steps to reproduce（重现步骤）
            <nut-card
            :img-url="item.imgUrl"
            :title="item.title"
            :shop-name="item.shopName"
            >
              <template #price>
                  <view>
                    <text>￥{{item.price}}</text>
                  </view>
              </template>
            </nut-card>

### What is expected?（期望的结果是什么？）
vip-price不再显示

### What is actually happening?（实际的结果是什么？）
自定义插槽后仍无法去掉vip-price

**Comment by eiinu** [comment]
vip-price 可以被 origin 插槽控制，参考文档第三个 demo
