### ISSUE TITLE
TABS页面内放置Menu后，Menu的下拉窗口不再贴合菜单，低于菜单项的标题一段距离。

### ISSUE THREAD

**Issue by beanhacker** [jdf2e/nutui#2365]
经过测试，发现这个问题由TABS的transform样式的动态设置引起，问题确定，帮忙解决一下。

**Comment by beanhacker** [comment]
这个问题在最新的V4.0.7上可复现。

**Comment by eiinu** [comment]
可以将 Tabs 的 animated-time 设置为 0，此时 Tabs 不再使用 transform 的布局方式
