### ISSUE TITLE
nut-number-keyboard 存在click和blur 冲突

### ISSUE THREAD

**Issue by samchenws** [jdf2e/nutui#2367]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.9

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
106

### System and its version（系统及其版本）
window

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/p/sandbox/nutui4-vite-demo-forked-5fcpjf?file=%2Fsrc%2FApp.vue%3A16%2C25)

### Steps to reproduce（重现步骤）
一直点击绑定的nut-number-keyboard 的nut-cell会导致nut-number-keyboard消失

### What is expected?（期望的结果是什么？）
一直点击绑定的nut-number-keyboard 的nut-cell，nut-number-keyboard不会消失

### What is actually happening?（实际的结果是什么？）
一直点击绑定的nut-number-keyboard 的nut-cell，nut-number-keyboard不会消失

**Comment by mikasayw** [comment]
需要阻止元素上的 touchstart 事件冒泡避免键盘收起，请将click改成touchstart.stop事件
先关闭了
