### ISSUE TITLE
tabbar 在用switchTab切换tabbar页面时，激活色不跟随新切换页面变更，页面切换成功后还要再次点击才会变色，tabbar页面点击两次新页面才会变色

### ISSUE THREAD

**Issue by hisunny520** [jdf2e/nutui#2368]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.9

### Vue version（vue 版本）
3.2.40

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.16

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
win10

### Taro environmental information（taro 环境信息）
Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.16.0 - d:\nodejs\node.EXE
      npm: 9.5.1 - d:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6 
      @tarojs/components: 3.6.6 => 3.6.6 
      @tarojs/helper: 3.6.6 => 3.6.6
      @tarojs/plugin-framework-vue3: 3.6.6 => 3.6.6
      @tarojs/plugin-html: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/taro-loader: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6

### Reproduction link（重现链接）
[github.com](https://github.com/hisunny520/test.git)

### Steps to reproduce（重现步骤）
tabbar 在用switchTab切换tabbar页面时，激活色不跟随新切换页面变更，页面切换成功后还要再次点击才会变色，tabbar页面点击两次新页面才会变色

### What is expected?（期望的结果是什么？）
switchTab切换tabbar页面时，新页面能跟随新切换激活变色

### What is actually happening?（实际的结果是什么？）
switchTab切换tabbar页面时，tabbar页面要点击两次新页面才会变色

**Comment by eiinu** [comment]
自定义 Tabbar 的用法参考：https://taro-docs.jd.com/docs/custom-tabbar

**Comment by hisunny520** [comment]
@eiinu  这样用不就成taro原生自定义tabbar,   nutui  tabber没有用了？

**Comment by CS-liujf** [comment]
> @eiinu 这样用不就成taro原生自定义tabbar, nutui tabber没有用了？

请问你知道该怎么解决了吗，我也一直在找如何用nut ui的tabbar自定义tabbar

**Comment by hisunny520** [comment]
@CS-liujf  这不没回复，nut ui的tabbar有bug 用不了，不行就只能用原生的了

**Comment by CS-liujf** [comment]
> @CS-liujf 这不没回复，nut ui的tabbar有bug 用不了，不行就只能用原生的了

我现在的方法是，通过vue-router来使用nut ui的tabbar，因为taro 3.6之后支持使用vue router了

**Comment by hisunny520** [comment]
@CS-liujf  通过vue-router 那成单页应用吧，多页可以用吗？ 

我的项目用了其他路由不好改，没想到tabbar 也能翻车

**Comment by CS-liujf** [comment]
@hisunny520 所以我的项目目前是混合的，即tabbar所管理的页面用vue-router做成单页面，比如tabbar里有两项：`主页`和`我的`，那么这俩页面都属于同一单页面，其他依然采用多页面。不过这样似乎也有个问题，假设我在其他页面(属于多页面的)里想要回到`我的`，貌似不易实现

**Comment by eiinu** [comment]
NutUI 的 Tabbar 与路由之间没有耦合关系。
你给的 demo 中，在每个页面都使用了 Tabbar，它们是完全没有关联的、各自独立的组件实例。将 v-model 绑定常量的使用方式会造成组件内 `update:modelValue` 失败，可能导致无法预测的错误。
两种可行的做法：
方式一：所有页面的组件实例都通过 vuex 或者 pinia 等状态管理工具共享同一个值
方式二：在每个页面中，watch 当前的页面路由（小程序路由，或者 Vue Router 路由）的变化，触发修改 v-model 绑定的值
