### ISSUE TITLE
Nut-Input Type 和 Taro-Input Type 不一致

### ISSUE THREAD

**Issue by rxay** [jdf2e/nutui#2369]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.9

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome

### System and its version（系统及其版本）
MacOS

### Taro environmental information（taro 环境信息）
-

### Reproduction link（重现链接）
[github.com](https://github.com/jdf2e/nutui/blob/v4/src/packages/__VUE/input/index.taro.vue)

### Steps to reproduce（重现步骤）
```javascript
    const renderInput = (type: InputType) => {
      return h('input', {
        style: styles,
        ...inputType(type)
      });
    };

    const inputType = (type: InputType) => {
      if (type === 'number') {
        return {
          type: 'text'
        };
      }

      if (type === 'digit') {
        return {
          type: 'tel'
        };
      }

      return { type };
    };
```

### What is expected?（期望的结果是什么？）
nut-input 的 type 和 taro-input 的 type 一致

### What is actually happening?（实际的结果是什么？）
实际不一致

### Remarks（补充说明）
为什么要额外把 number 转换为 text，digit 转换为 tel？

**Comment by eiinu** [comment]
历史遗留问题，最初实现的 Taro 端组件是以 HTML5 而不是以小程序为参考目标实现的。
我觉得后续可以增加一个新的 native-type 属性，优先级高于原有的 type。
