### ISSUE TITLE
picker多列选择bug

### ISSUE THREAD

**Issue by tangchi695** [jdf2e/nutui#2374]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
小程序

### System and its version（系统及其版本）
win10

### Taro environmental information（taro 环境信息）
 Taro CLI 3.6.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE       
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.5 => 3.6.5
      @tarojs/components: 3.6.5 => 3.6.5
      @tarojs/helper: 3.6.5 => 3.6.5
      @tarojs/plugin-framework-vue3: 3.6.5 => 3.6.5
      @tarojs/plugin-html: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-alipay: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-h5: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-jd: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-qq: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-swan: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-tt: 3.6.5 => 3.6.5
      @tarojs/plugin-platform-weapp: 3.6.5 => 3.6.5
      @tarojs/runtime: 3.6.5 => 3.6.5
      @tarojs/shared: 3.6.5 => 3.6.5
      @tarojs/taro: 3.6.8 => 3.6.8
      @tarojs/webpack5-runner: 3.6.5 => 3.6.5
      babel-preset-taro: 3.6.5 => 3.6.5
      eslint-config-taro: 3.6.5 => 3.6.5

### Reproduction link（重现链接）
[nutui.jd.com](https://nutui.jd.com/nutui-issue-helper/?repo=jdf2e/nutui&lang=zh-cn)

### Steps to reproduce（重现步骤）
picker组件按照文档上的多列展示方法使用，confirm事件收到的selectedOptions数组第一个元素为undefined

### What is expected?（期望的结果是什么？）
选中的值

### What is actually happening?（实际的结果是什么？）
undefined

**Comment by tangchi695** [comment]
破案了，picke多列选择的时候，必须要给一个v-model值，不然选择的时候第一列选不上，而且两列会互相影响😤

**Comment by mlwxxx** [comment]
> 破案了，picke多列选择的时候，必须要给一个v-model值，不然选择的时候第一列选不上，而且两列会互相影响😤

帮了大忙了。。感谢！

**Comment by eiinu** [comment]
v4.2.0+ 已支持在不设置 v-model 的情况下使用。
