### ISSUE TITLE
Image懒加载功能失效，ios系统

### ISSUE THREAD

**Issue by momtboy** [jdf2e/nutui#2375]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.9

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
safari

### System and its version（系统及其版本）
iPhone

### Reproduction link（重现链接）
[ittest.store.valarpick.net/](https://ittest.store.valarpick.net/)

### Steps to reproduce（重现步骤）
首页图片延迟加载失效，菜单栏图片延迟加载失效

### What is expected?（期望的结果是什么？）
延迟加载正常
![image](https://github.com/jdf2e/nutui/assets/9612078/f5872b29-e9f9-4388-b087-a26626e3351c)

### What is actually happening?（实际的结果是什么？）
延迟加载失效
![d18047d69761148b389e49af4e3df52](https://github.com/jdf2e/nutui/assets/9612078/b6df2895-3d25-424f-8d9a-61b663ac62c5)

**Comment by eiinu** [comment]
已发布 [@nutui/nutui@4.0.12-beta.1](https://www.npmjs.com/package/@nutui/nutui/v/4.0.12-beta.1)

**Comment by eiinu** [comment]
已发布 4.0.12 正式版
