### ISSUE TITLE
button组件报错

### ISSUE THREAD

**Issue by tangchi695** [jdf2e/nutui#2377]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.11

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
小程序

### System and its version（系统及其版本）
win10

### Taro environmental information（taro 环境信息）
  Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 7.23.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8 
      @tarojs/components: 3.6.8 => 3.6.8 
      @tarojs/helper: 3.6.8 => 3.6.8 
      @tarojs/plugin-framework-vue3: 3.6.8 => 3.6.8 
      @tarojs/plugin-html: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8 
      @tarojs/runtime: 3.6.8 => 3.6.8 
      @tarojs/shared: 3.6.8 => 3.6.8 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8 
      babel-preset-taro: 3.6.8 => 3.6.8 
      eslint-config-taro: 3.6.8 => 3.6.8 

### Reproduction link（重现链接）
[nutui.jd.com](https://nutui.jd.com/nutui-issue-helper/?repo=jdf2e/nutui&lang=zh-cn)

### Steps to reproduce（重现步骤）
页面引入nut-button组件以后报 
[WXML Runtime warning] ./base.wxml
 Template `tmpl_0_13` not found.
  279 | 
  280 | <template name="tmpl_2_container">
> 281 |   <template is="{{xs.a(2, i.nn, l)}}" data="{{i:i,cid:2,l:xs.f(l,i.nn)}}" />
      |                ^
  282 | </template>
  283 | 
  284 | <template name="tmpl_3_0">

之前都是正常用的， 更新依赖到最新以后就出这个问题了。

### What is expected?（期望的结果是什么？）
没懂

### What is actually happening?（实际的结果是什么？）
[WXML Runtime warning] ./base.wxml
 Template `tmpl_0_13` not found.
  279 | 
  280 | <template name="tmpl_2_container">
> 281 |   <template is="{{xs.a(2, i.nn, l)}}" data="{{i:i,cid:2,l:xs.f(l,i.nn)}}" />
      |                ^
  282 | </template>
  283 | 
  284 | <template name="tmpl_3_0">

**Comment by eiinu** [comment]
已发布 4.0.12 修复了该问题
