### ISSUE TITLE
组件props没有类型提示和补全功能

### ISSUE THREAD

**Issue by JxJPu9bD** [jdf2e/nutui#2378]
### What problem does this feature solve?（这个功能解决的问题）
可以大幅提高开发效率, 在我提出这个问题前我已经搜索了相关内容, 之前也有做过类似的优化, 但是还不彻底
https://zhuanlan.zhihu.com/p/512519974

### What does the proposed API look like?（期望的 API）
可以有类型提示和自动补全, 这个element-plus 和 trao-ui都是支持的
<img width="360" alt="image" src="https://github.com/jdf2e/nutui/assets/12554248/7749a209-62e3-4c63-ab23-200cae2b0d00">
<img width="336" alt="image" src="https://github.com/jdf2e/nutui/assets/12554248/535faac2-6b22-4e89-b912-5c29b2aa46d2">
但是 nutui没有
<img width="379" alt="image" src="https://github.com/jdf2e/nutui/assets/12554248/bf635171-4262-412b-b596-63105fbe113a">

**Comment by eiinu** [comment]
<img width="734" alt="image" src="https://github.com/jdf2e/nutui/assets/44915689/0c28638c-a8f0-4114-8843-46144471e7de">

Props 值的提示不是通过 vscode 插件实现的，而是 Typescript 提供的功能，目前 npm 包中是提供了类型声明文件的，应该可以看到提示。

可以把鼠标移动到 `nut-button` 上，看看能否出现组件完整类型提示的 hover。

可能会丢失类型提示的原因：
1、使用一个新的组件时，还没有执行过项目(dev/build)，`unplugin-vue-components` 插件未运行，导致 `components.d.ts` 中没有该组件的全局类型声明。可以看下这个文件中是否有 `NutButton`。
2、`tsconfig.json` 文件中没有将 `components.d.ts` 文件加入 include 内。

**Comment by eiinu** [comment]
使用 `unplugin-vue-components` 注册组件时，由于插件会生成全局类型声明文件，是有类型提示语补全功能的。

如果手动引入单个组件并注册为全局变量，在 volar 插件下无法提示，该问题会在下个版本修复。

**Comment by JxJPu9bD** [comment]
感谢您的付出
