### ISSUE TITLE
官方demo，nut-picker无法滚动

### ISSUE THREAD

**Issue by JackYumg** [jdf2e/nutui#2379]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.12

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
无，用的codesandbox

### Browser and its version（浏览器及其版本）
114.0.5735.91

### System and its version（系统及其版本）
window11

### Reproduction link（重现链接）
[codesandbox.io/s/l579v3](https://codesandbox.io/s/l579v3?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675)

就是官方的codesandbox

### Steps to reproduce（重现步骤）
不管切换到phone还是什么都不能进行滚动选择

### What is expected?（期望的结果是什么？）
及时非手机模式也可以滚动选择

### What is actually happening?（实际的结果是什么？）
不能滚动选择

**Comment by JackYumg** [comment]
对鼠标事件未兼容

**Comment by eiinu** [comment]
组件库中大多数使用的是 touch 事件，在 PC 端无法触发。

一般会通过引入模拟事件的脚本解决，[touchEmulator](https://github.com/jdf2e/nutui/blob/v4/src/packages/utils/touchEmulator.js) 可以将这个文件引入到项目入口实现 PC 端适配。
实际上，官网文档右侧的 demo 就是通过这种方式实现的。

后续会在 codesanbox 加入这一脚本。

**Comment by JackYumg** [comment]
问题已解决，希望在库里加上，通过 import '@nutui/touchEmulator'手动引入
