### ISSUE TITLE
Calendar日历组件周起始日非星期日时，未正确高亮周末列

### ISSUE THREAD

**Issue by liyuz** [jdf2e/nutui#2384]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.12

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18.15.0

### Browser and its version（浏览器及其版本）
Chrome(91.0.4472.114)

### System and its version（系统及其版本）
Windows 10(10.0)

### Reproduction link（重现链接）
![image](https://github.com/jdf2e/nutui/assets/21266415/3fa82c8f-b9e2-4af6-bd5f-97ba0c8de39d)

### Steps to reproduce（重现步骤）
1、打开官方示例微信小程序
2、日历组件，点击【周选择】（周起始日为周一）

### What is expected?（期望的结果是什么？）
周六、周日两列数据高亮显示

### What is actually happening?（实际的结果是什么？）
日历最左一列和最右一列数据高亮显示

**Comment by JxJPu9bD** [comment]
👍我也遇到了这个问题
