### ISSUE TITLE
uploader 组件，v-model:file-list 默认文件列表，在异步请求中，赋值不进去

### ISSUE THREAD

**Issue by chen-ccll** [jdf2e/nutui#2391]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.12

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome 114.0.5735.199

### System and its version（系统及其版本）
windows

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/uploader)

### Steps to reproduce（重现步骤）
文件列表是通过发请求，后端返回数据，然后把值赋给v-model:file-list，值设不进去
 onMounted(() => {
      upfileLists.value = [{
                name: "注册证书",
                status: "success",
                url: '图片地址',
                uid: '111',
                type: "image",
                message: "cs",
              },]
   });

### What is expected?（期望的结果是什么？）
希望可以赋进去值

### What is actually happening?（实际的结果是什么？）
赋不进去默认值

**Comment by chen-ccll** [comment]
https://codesandbox.io/s/nutui4-vite-demo-forked-jpjlw7?file=/src/App.vue

**Comment by eiinu** [comment]
![image](https://github.com/jdf2e/nutui/assets/44915689/f179c140-63d4-4e00-b984-a824c82adc6c)
当前的 uploader 组件内的 fileList 不会跟随 props fileList 的修改而变更，下个版本会加上。

如果不重新赋值一个新的数组，而是对已有的数组进行操作，则在当前版本就可以实现，像这样：
```js
const list = ref([])
const func = () => {
  list.value.push()
  list.value.pop()
  list....
}
```
可以作为临时解决方案。

**Comment by chen-ccll** [comment]
感谢你的回答解决。

**Comment by zhangyuan1988** [comment]
@eiinu `const list = ref([])
const func = () => {
  list.value.push()
  list.value.pop()
  list....
}`
这种方式在页面中有多个组件时，依然无法解决

**Comment by zhangyuan1988** [comment]
@eiinu 

const func = () => {
 list.value.push()
 list.value.pop()
 list....
}
这种方式在页面中有多个上传组件时，依然无法解决

**Comment by eiinu** [comment]
> @eiinu
> 
> const func = () => { list.value.push() list.value.pop() list.... } 这种方式在页面中有多个上传组件时，依然无法解决

该问题的原因是：
Uploader 组件只在 setup 阶段获取一次 props 中的 fileList，后续如果重新赋值了 fileList（指换成了另一个数组对象），组件内没有 watch 该变化并同步更新。
因此在当前版本下，只要一直对初始传入的数组进行修改，就可以绕过这个问题。
