### ISSUE TITLE
tab组件

### ISSUE THREAD

**Issue by xchd** [jdf2e/nutui#241]
##tab组件高度，背景色样式的修改
<nut-tab @tab-switch="tabSwitch">
    <nut-tab-panel tab-title="页签1">页签1</nut-tab-panel>
    <nut-tab-panel tab-title="页签2">页签2</nut-tab-panel>
    <nut-tab-panel tab-title="页签3">页签3</nut-tab-panel>
</nut-tab>

发现nut-tab背景色不能修改,nut-tab-item是200px,无法容纳内容

**Comment by richard1015** [comment]
需要充值样式的 style 标签避免使用  scoped 否则只会局部生效
