### ISSUE TITLE
taro中组件无法正常显示

### ISSUE THREAD

**Issue by 370295005** [jdf2e/nutui#2415]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.12

### Vue version（vue 版本）
3.2.40

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.19.0

### Browser and its version（浏览器及其版本）
无

### System and its version（系统及其版本）
Windows10

### Taro environmental information（taro 环境信息）
Taro CLI 3.6.8 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8
      @tarojs/components: 3.6.8 => 3.6.8
      @tarojs/helper: 3.6.8 => 3.6.8
      @tarojs/plugin-framework-vue3: 3.6.8 => 3.6.8
      @tarojs/plugin-html: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8
      @tarojs/runtime: 3.6.8 => 3.6.8
      @tarojs/shared: 3.6.8 => 3.6.8
      @tarojs/taro: 3.6.8 => 3.6.8
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8
      babel-preset-taro: 3.6.8 => 3.6.8
      eslint-config-taro: 3.6.8 => 3.6.8

### Reproduction link（重现链接）
[codepen.io](https://codepen.io/ijyvvnmf-the-styleful/pen/oNQpeMJ)

### Steps to reproduce（重现步骤）
在微信开发者工具和真机上无法正确显示按钮和输入框

### What is expected?（期望的结果是什么？）
组件正常显示

### What is actually happening?（实际的结果是什么？）
不显示组件
 Template `tmpl_0_27` not found.
Template `tmpl_0_13` not found.
![image](https://github.com/jdf2e/nutui/assets/39272235/056519aa-2c5f-428e-a099-765be85463f7)

![image](https://github.com/jdf2e/nutui/assets/39272235/38a2bd41-2264-44c8-a9d2-09e0ce21876a)

### Remarks（补充说明）
小概率能正常显示

**Comment by eiinu** [comment]
https://github.com/jdf2e/nutui/discussions/2356#discussioncomment-6277270
参考这个

**Comment by 370295005** [comment]
> [#2356 (comment)](https://github.com/jdf2e/nutui/discussions/2356#discussioncomment-6277270) 参考这个
但是我没有开启预加载，目前配置是这样的
  compiler: {
    type: 'webpack5',
    prebundle: { enable: false }
  },

**Comment by 370295005** [comment]
关闭了cache和预加载后可以正常显示，但是开启cache关闭预加载有时候也不能正常显示
https://github.com/370295005/taro-demo

**Comment by eiinu** [comment]
> 关闭了cache和预加载后可以正常显示，但是开启cache关闭预加载有时候也不能正常显示 https://github.com/370295005/taro-demo

https://github.com/NervJS/taro/issues/12553
开启 prebundle 或者 cache 就可能出现这种问题，在 Taro 中使用第三方组件库都是这样。需要等 Taro 解决。

**Comment by 370295005** [comment]
> > 关闭了cache和预加载后可以正常显示，但是开启cache关闭预加载有时候也不能正常显示 https://github.com/370295005/taro-demo
> 
> [NervJS/taro#12553](https://github.com/NervJS/taro/issues/12553) 开启 prebundle 或者 cache 就可能出现这种问题，在 Taro 中使用第三方组件库都是这样。需要等 Taro 解决。

好的谢谢

**Comment by vcc0827** [comment]
使用vite构建的模板也出现了这个问题，现在有地方配置关闭vite的预加载和cache吗？

**Comment by duerlatter** [comment]
> 使用vite构建的模板也出现了这个问题，现在有地方配置关闭vite的预加载和cache吗？

请问有解决方法么
