### ISSUE TITLE
真机点击轮播图内的图片， 不会跳转图片链接

### ISSUE THREAD

**Issue by MrLiuMrLiu** [jdf2e/nutui#2418]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.12

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.15.0

### Browser and its version（浏览器及其版本）
114.0.5735.199

### System and its version（系统及其版本）
12.6

### Reproduction link（重现链接）
[115.182.208.161/](http://115.182.208.161:9001/#/about)

### Steps to reproduce（重现步骤）
使用网页窗口点击轮播图内的图片可以跳转链接，F12选择手机窗口或者使用真机， 点击轮播图内的图片， 不会跳转图片链接

### What is expected?（期望的结果是什么？）
F12选择手机窗口， 点击轮播图内的图片， 跳转图片链接

### What is actually happening?（实际的结果是什么？）
使用网页窗口点击轮播图内的图片可以跳转链接，F12选择手机窗口或者使用真机， 点击轮播图内的图片， 不会跳转图片链接

**Comment by eiinu** [comment]
![image](https://github.com/jdf2e/nutui/assets/44915689/729da8df-0623-4e8d-bb95-4073a98698e4)
可以设置这两个属性避免事件被拦截

**Comment by MrLiuMrLiu** [comment]
好的，谢谢
