### ISSUE TITLE
Error: 全局配置缺少 pages 字段，请检查！

### ISSUE THREAD

**Issue by e8tg001** [jdf2e/nutui#2420]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.2.40

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.19.0

### Browser and its version（浏览器及其版本）
Chrome(114.0.5735.199)

### System and its version（系统及其版本）
windows10

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.1

  Taro CLI 3.6.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.19.0 - D:\Program Files\nodejs\node.EXE
      npm: 9.7.1 - D:\Program Files\nodejs\npm.CMD

package.json

{
....
"dependencies": {
    "@babel/runtime": "^7.7.7",
    "@nutui/icons-vue-taro": "^0.0.9",
    "@nutui/nutui-taro": "^4.0.4",
    "@tarojs/components": "3.6.1",
    "@tarojs/helper": "3.6.1",
    "@tarojs/mini-runner": "^3.6.1",
    "@tarojs/plugin-framework-vue3": "3.6.1",
    "@tarojs/plugin-html": "3.6.1",
    "@tarojs/plugin-platform-alipay": "3.6.1",
    "@tarojs/plugin-platform-h5": "3.6.1",
    "@tarojs/plugin-platform-jd": "3.6.1",
    "@tarojs/plugin-platform-qq": "3.6.1",
    "@tarojs/plugin-platform-swan": "3.6.1",
    "@tarojs/plugin-platform-tt": "3.6.1",
    "@tarojs/plugin-platform-weapp": "3.6.1",
    "@tarojs/runtime": "3.6.1",
    "@tarojs/shared": "3.6.1",
    "@tarojs/taro": "3.6.1",
    "@tarojs/webpack-runner": "^3.6.1",
    "vue": "^3.2.40"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/cli": "3.6.1",
    "@tarojs/taro-loader": "3.6.1",
    "@tarojs/webpack5-runner": "3.6.1",
    "@types/node": "^18.15.11",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.20.0",
    "@vue/babel-plugin-jsx": "^1.0.6",
    "@vue/compiler-sfc": "^3.2.40",
    "babel-preset-taro": "3.6.1",
    "css-loader": "3.4.2",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.6.1",
    "eslint-plugin-vue": "^8.0.0",
    "style-loader": "1.3.0",
    "stylelint": "9.3.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.1.0",
    "unplugin-vue-components": "^0.25.1",
    "vue-loader": "^17.0.0",
    "webpack": "^5.77.0"
  }
}

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/guide/start)

### Steps to reproduce（重现步骤）
直接按官方步骤：
1.先taro init appName
2.再npm install
3.检查包 taro doctor ，根据提示安装缺失的依赖
4.直接npm run build:weapp
在第4步时，控制台出现异常
● Webpack █████████████████████████  (0%)  
D:\Workspaces\taro\cardApp\node_modules\@tarojs\webpack5-runner\dist\plugins\MiniPlugin.js:414
            throw new Error('全局配置缺少 pages 字段，请检查！');
                  ^

Error: 全局配置缺少 pages 字段，请检查！
    at TaroMiniPlugin.getPages (D:\Workspaces\taro\cardApp\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:513:6)
    at TaroMiniPlugin.run (D:\Workspaces\taro\cardApp\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:360:12)
    at TaroMiniPlugin.<anonymous> (D:\Workspaces\taro\cardApp\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:168:20)
    at Generator.next (<anonymous>)
    at D:\Workspaces\taro\cardApp\node_modules\@tarojs\webpack5-runner\dist\plugins\MiniPlugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Workspaces\taro\cardApp\node_modules\@tarojs\webpack5-runner\dist\plugins\MiniPlugin.js:4:12)
    at D:\Workspaces\taro\cardApp\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:167:48
    at TaroMiniPlugin.<anonymous> (D:\Workspaces\taro\cardApp\node_modules\@tarojs\webpack5-runner\src\plugins\MiniPlugin.ts:144:15)

实际上在src/app.config.ts是存在，pages和window有初始化配置

### What is expected?（期望的结果是什么？）
找到具体的原因，帮忙提供解决方案

### What is actually happening?（实际的结果是什么？）
编译暂停

**Comment by eiinu** [comment]
升级 Taro 版本至 3.6.5 以上（最新版本为 3.6.8）
参考 https://github.com/NervJS/taro/issues/13672

**Comment by e8tg001** [comment]
感谢，已升级到3.6.8，并在npm 模式下，package.json锁定@swc/core版本
"overrides": {
    "@swc/core": "1.3.42"
  }
已解决上述问题
