### ISSUE TITLE
nutui-taro 组件 nut-tabs 编译到 h5 的问题

### ISSUE THREAD

**Issue by refinist** [jdf2e/nutui#2425]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.12

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.0

### Browser and its version（浏览器及其版本）
版本 114.0.5735.198（正式版本） (arm64)

### System and its version（系统及其版本）
macOS 12.3

### Taro environmental information（taro 环境信息）
Taro CLI 3.6.8 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.8 => 3.6.8 
      @tarojs/components: 3.6.8 => 3.6.8 
      @tarojs/helper: 3.6.8 => 3.6.8 
      @tarojs/plugin-framework-vue3: 3.6.8 => 3.6.8 
      @tarojs/plugin-html: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-alipay: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-h5: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-jd: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-qq: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-swan: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-tt: 3.6.8 => 3.6.8 
      @tarojs/plugin-platform-weapp: 3.6.8 => 3.6.8 
      @tarojs/runtime: 3.6.8 => 3.6.8 
      @tarojs/shared: 3.6.8 => 3.6.8 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/taro-loader: 3.6.8 => 3.6.8 
      @tarojs/webpack5-runner: 3.6.8 => 3.6.8 
      babel-preset-taro: 3.6.8 => 3.6.8 
      eslint-config-taro: 3.6.8 => 3.6.8 

### Reproduction link（重现链接）
[github.com](https://github.com/front-refined/nutui-taro-compile-h5-issue)

### Steps to reproduce（重现步骤）
拉取 git 仓库

yarn run dev:h5 

h5 端，首页 tabs 过长时，点击 item 不会自动滚动定位到指定位置，在小程序环境可以

### What is expected?（期望的结果是什么？）
tabs 过长时，点击 item 自动滚动定位到指定位置

### What is actually happening?（实际的结果是什么？）
tabs 过长时，点击 item 不会自动滚动定位到指定位置

### Remarks（补充说明）
最近自己在封装组件时，参考了 nutui-taro 的封装风格，但发现组件构建后经过 Taro 处理编译成 h5 时所有标签都不会被转换，从而造成了一些问题，

如 `<view />` 应该会被编译成 `<taro-view-core />`，但是仍然显示 `<view />`，这个 `<nut-tabs />` 的问题也是因为 `<scroll-view />` 不会被正常编译成 h5 版的 `<taro-scroll-view-core />` 导致的，

然后我就没有用 vite 构建组件了，直接源码扔到 npm 私仓，让 Taro 去打包就可以了（但是还是打包会好点），

所以我个人是猜测由于构建之后 Taro 无法识别标签，从而导致不会编译成 h5 标签，

这个库很棒！期待反馈 ❤️（这个问题我也会在 Taro 发一次）

**Comment by eiinu** [comment]
Vue 组件经过打包后通过 npm 引入，在 Taro H5 下的标签和直接引入 vue 模板确实是不一致的。
之前给 Taro 反馈过，没有得到合适的解决办法。
不过在大多数场景下是没有问题的，也几乎没有收到这方面的 bug 反馈。（即使有，可能也被当成了 Taro H5 端的兼容问题额外做处理了）
我们也在考虑如何将仓库内的 Taro 测试 demo 项目从直接引用代码变更为引入构建产物的方式。

**Comment by refinist** [comment]
> Vue 组件经过打包后通过 npm 引入，在 Taro H5 下的标签和直接引入 vue 模板确实是不一致的。 之前给 Taro 反馈过，没有得到合适的解决办法。 不过在大多数场景下是没有问题的，也几乎没有收到这方面的 bug 反馈。（即使有，可能也被当成了 Taro H5 端的兼容问题额外做处理了） 我们也在考虑如何将仓库内的 Taro 测试 demo 项目从直接引用代码变更为引入构建产物的方式。

感谢反馈 ❤️，解开了疑惑。那就期待 Taro 的修复升级，毕竟还是走 h5 的标签会好点，否则就需要额外来兼容 h5 代码了，有点失去了 ”一套多端“ 的感觉了。

另外你最后说的 ”我们也在考虑如何将仓库内的 Taro 测试 demo 项目从直接引用代码变更为引入构建产物的方式。“ 
是说由于目前用 pnpm 维护的 monorepo demo 编译都是直接引用代码编译所以不会有这些编译问题，转换引入构建产物更贴近现在开发者使用 npm 方式引入吗?

无论如何，我觉得还是 Taro 尽快处理此问题会好点。

另外有没有一种可能，暴露一个不打包版本，当然这块局限性会高点，开发者只能用 ts，库内还要修改 NutUIResolver 。我目前公司的私仓也是用这种直接暴露源码的方式让 Taro 去打包的方式 😄
