### ISSUE TITLE
dialog在安卓微信浏览器的显示有BUG

### ISSUE THREAD

**Issue by qzd1989** [jdf2e/nutui#243]
官方demo - "操作反馈" - "dialog" - "窗体内部滚动不影响页面滚动" 这个演示 在 安卓(小米)微信浏览器里有显示BUG,无法拖动,下面的按钮也不见了.  苹果微信OK. 外部浏览器OK.

**Comment by guoxiao158** [comment]
原因是因为 fix 定位的兼容性问题，如果内容过多，建议使用pop组件
