### ISSUE TITLE
Swiper4.10更新后 报错

### ISSUE THREAD

**Issue by Ouopoulos** [jdf2e/nutui#2430]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.1.0

### Vue version（vue 版本）
3.3.2

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
Win10

### Taro environmental information（taro 环境信息）
Taro v3.6.7

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/swiper)

### Steps to reproduce（重现步骤）
直接引用官网文档内用法 报错._node_modules_@nutui_nutui-taro_dist_packages__es_Swiper.js:14 Uncaught (in promise) undefined(env: Windows,mp,1.06.2306020; lib: 2.33.0)

### What is expected?（期望的结果是什么？）
捕获异常问题？

### What is actually happening?（实际的结果是什么？）
._node_modules_@nutui_nutui-taro_dist_packages__es_Swiper.js:14 Uncaught (in promise) undefined(env: Windows,mp,1.06.2306020; lib: 2.33.0)

**Comment by eiinu** [comment]
正常现象，组件内部调用 createSelectorQuery + boundingClientRect 没有成功，抛出了这个错误。不影响组件使用。
下个版本会把错误兜底处理一下。
