### ISSUE TITLE
[bug]button组件文档错误 

### ISSUE THREAD

**Issue by ljk-study** [jdf2e/nutui#244]
<nut-button-group><nut-button-group>

实际上应该是
<nut-buttongroup></nut-buttongroup>

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
实际上应该是 ？  请补充一下

**Comment by richard1015** [comment]
已修改，感谢您的反馈
