### ISSUE TITLE
视频播放器没有暂停或者停止等方法

### ISSUE THREAD

**Issue by beanhacker** [jdf2e/nutui#2447]
VUE版的nut-video中没有找到视频播放、暂停和停止的方法，希望指导添加下，谢谢！

**Comment by AuYuHui** [comment]
![image](https://github.com/jdf2e/nutui/assets/38815121/c64b24f7-d0c3-4ccb-9e9e-2076e91cb0af)
这个不是吗

**Comment by beanhacker** [comment]
我希望通过方法控制它的这些动作，谢谢！

**Comment by AuYuHui** [comment]
> 我希望通过方法控制它的这些动作，谢谢！

你绑定  Ref，不就可以通过方法控制吗

**Comment by beanhacker** [comment]
句柄里没有我上面描述的几个方法啊。
