### ISSUE TITLE
0天后的追评不会被显示，这应该是一个BUG。

### ISSUE THREAD

**Issue by beanhacker** [jdf2e/nutui#2449]
现实场景是，用户刚评论完，发现自己评论内容不充足，需要补充，就需要追评，或者连续追评。目前的控件既不支持当天(0天后)追评，也不支持多次追评，希望增加。

**Comment by eiinu** [comment]
反馈问题或者新功能请走 issue helper 的模板，不符合要求的会被关闭。

**Comment by beanhacker** [comment]
我这边由于提交渠道的关系，看不到模板，请谅解。这个追评的问题，你们有计划解决么？
