### ISSUE TITLE
引入tailwindcss后主题色丢失

### ISSUE THREAD

**Issue by JxJPu9bD** [jdf2e/nutui#2450]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.1.1

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.20.0

### Browser and its version（浏览器及其版本）
chrome(115.0.5790.102)

### System and its version（系统及其版本）
macOS(12.5.1)

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/p/github/JxJPu9bD/taro-nutui-tailwindcss/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clkfh8d7t000g3u6m4juapxty%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clkfh8d7t000b3u6ml7g87vra%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clkfh8d7t000f3u6mfi8mripw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clkfh8d7t000d3u6mrji4ufpw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clkfh8d7t000b3u6ml7g87vra%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clkfh8d7t000a3u6moj19p694%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%257D%255D%252C%2522id%2522%253A%2522clkfh8d7t000b3u6ml7g87vra%2522%252C%2522activeTabId%2522%253A%2522clkfh8d7t000a3u6moj19p694%2522%257D%252C%2522clkfh8d7t000d3u6mrji4ufpw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clkfh8d7t000c3u6mxe0gpok2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%257D%255D%252C%2522id%2522%253A%2522clkfh8d7t000d3u6mrji4ufpw%2522%252C%2522activeTabId%2522%253A%2522clkfh8d7t000c3u6mxe0gpok2%2522%257D%252C%2522clkfh8d7t000f3u6mfi8mripw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clkfh8d7t000e3u6mnku26uvy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clkfh8dhs001jh0ga9kcm99hq%2522%257D%255D%252C%2522id%2522%253A%2522clkfh8d7t000f3u6mfi8mripw%2522%252C%2522activeTabId%2522%253A%2522clkfh8d7t000e3u6mnku26uvy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce（重现步骤）
index 页面是有一个登录按钮的, 但是 项目引入了tailiwindcss后 这个按钮增加了一个 taro-button-core 的class, 里面有一个 background-image 的属性, 然后导致按钮背景变为白色不可见, 可以右键检查看到 
按钮在hello 文本的下方, 

### What is expected?（期望的结果是什么？）
能按照主题正常显示

### What is actually happening?（实际的结果是什么？）
实际按钮不可背景色丢失了

**Comment by JxJPu9bD** [comment]
<img width="1321" alt="image" src="https://github.com/jdf2e/nutui/assets/12554248/7daeb748-f690-47fc-a7ab-b458b5e73ebe">
如果不引入tailwindcss的话没有这个 class
如果取消background-image后或者设置背景色可使按钮可见, 但我不能每个按钮都去加一遍

**Comment by JxJPu9bD** [comment]
<img width="1231" alt="image" src="https://github.com/jdf2e/nutui/assets/12554248/129ecd84-086b-44d6-a173-820fd496719d">
取消属性后按钮可见

**Comment by JxJPu9bD** [comment]
<img width="1425" alt="image" src="https://github.com/jdf2e/nutui/assets/12554248/ad5d5f88-b1e6-4afa-86eb-4a75e7147324">
移除tailwindcss后则没有这个class 和属性

**Comment by eiinu** [comment]
> <img alt="image" width="1321" src="https://user-images.githubusercontent.com/12554248/255396312-7daeb748-f690-47fc-a7ab-b458b5e73ebe.png"> 如果不引入tailwindcss的话没有这个 class 如果取消background-image后或者设置背景色可使按钮可见, 但我不能每个按钮都去加一遍

图中的 `taro-button-core` 类名是灰色的，并未生效。实际生效的是 `[type='button']` 这个选择器，它是由 tailwind 引入的，因此也应该从 tailwind 配置中解决。

**Comment by JxJPu9bD** [comment]
> 

好的 我检查下
