### ISSUE TITLE
Calendar 日历 不设置起始日期就不能选过去的时间，比如用于选择出生日期范围，都是选过去的日期，太难用了

### ISSUE THREAD

**Issue by mxj009** [jdf2e/nutui#2451]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.9

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16.0

### Browser and its version（浏览器及其版本）
chrome14.0.5735.199

### System and its version（系统及其版本）
win11

### Reproduction link（重现链接）
[nutui.jd.com/h5/vue/4x/](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/calendar)

### Steps to reproduce（重现步骤）
包括DatePicker组件也是，选择出生日期，你怎么设置起始日期，不允许别人活100岁？非要设置起始日期干什么？

### What is expected?（期望的结果是什么？）
什么都不设置，默认是今天，但是往前往后选都可以。

### What is actually happening?（实际的结果是什么？）
什么都不设置，只能选今天之后。但是日历组件一般都是选过去的日期

**Comment by mxj009** [comment]
另外不能快带的切换年和月，用起来很难用。看起来有这个组件，非常难用

**Comment by mxj009** [comment]
建议看看苹果系统里的日历组件，看看人家怎么用的

**Comment by yangjisen** [comment]
看到楼主很激动, 我曾经也为此问题而纠结, 最后我放弃了使用这个日历组件使用了原生的代替, 也是无奈之举啊

**Comment by eiinu** [comment]
在当前的这种滚动翻页的日历组件中，很难实现快速切换年月。而且如果不限制范围，组件内没法生成对应的节点，DOM数量会爆炸，在小程序环境也会很卡顿。
我觉得卡片式的日历更适合实现这些功能，可以作为一个新的组件提供。

**Comment by mxj009** [comment]
> 
你可以看下ios的日历，人家也是滚动翻页的，左上角有个年，点进去，可以扩大到12个月，再上下滚就变成翻年了。简直不要太好用。最主要的是不要设置上下限，只要想滚就应该可以滚。

**Comment by eiinu** [comment]
> > 
> 你可以看下ios的日历，人家也是滚动翻页的，左上角有个年，点进去，可以扩大到12个月，再上下滚就变成翻年了。简直不要太好用。最主要的是不要设置上下限，只要想滚就应该可以滚。
> 

web 与原生没有可比性。之前的回复已经说明了原因。

**Comment by Xhyen** [comment]
> > > 
> > 
> > 
> > 你可以看下ios的日历，人家也是滚动翻页的，左上角有个年，点进去，可以扩大到12个月，再上下滚就变成翻年了。简直不要太好用。最主要的是不要设置上下限，只要想滚就应该可以滚。
> 
> web 与原生没有可比性。之前的回复已经说明了原因。

你好请问下，如果设置了区间，但是想定位到今天得怎么写？我看你们文档好像也没有提供此类方法
