### ISSUE TITLE
swiper图片点击跳转没效果

### ISSUE THREAD

**Issue by ZYJ-199508** [jdf2e/nutui#2455]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.1.2

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
106.0.5249.119

### System and its version（系统及其版本）
12.6

### Reproduction link（重现链接）
[codesandbox.io/s/wgvjgq](https://codesandbox.io/s/wgvjgq?file=/src/App.vue)

### Steps to reproduce（重现步骤）
任意一个轮播图，绑定点击事件

### What is expected?（期望的结果是什么？）
点击图片可以跳转

### What is actually happening?（实际的结果是什么？）
点击图片不跳转

**Comment by eiinu** [comment]
<img width="1111" alt="image" src="https://github.com/jdf2e/nutui/assets/44915689/b80cf283-72a7-4525-ae6c-07a85229a0a8">
点击事件可能会被拦截，可通过这两个属性控制

**Comment by ZYJ-199508** [comment]
> 可以了，thanks
