### ISSUE TITLE
ConfigProvider 中的地区选择器最后一级的选择无法在文本框中显示

### ISSUE THREAD

**Issue by febelery** [jdf2e/nutui#2456]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.1.2

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16

### Browser and its version（浏览器及其版本）
edge

### System and its version（系统及其版本）
win

### Reproduction link（重现链接）
[nutui.jd.com/h5/vue/4x/](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/configprovider)

### Steps to reproduce（重现步骤）
点击 地区，然后依次选择，仔细看，最后一级的选择无法在input中显示

### What is expected?（期望的结果是什么？）
在文本框中显示

### What is actually happening?（实际的结果是什么？）
无法在文本框中显示

**Comment by eiinu** [comment]
ConfigProvider demo 代码已修改，感谢反馈。
