### ISSUE TITLE
button 连字体颜色 都自定义不了

### ISSUE THREAD

**Issue by yemaozi999** [jdf2e/nutui#2464]
### 这个功能解决了什么问题？

button 连字体颜色 都自定义不了, 希望可以设置字体颜色

### 你期望的 API 是怎样的？

加上
text-color | 按钮组文字颜色

**Comment by eiinu** [comment]
可通过 css 变量修改不同 type 的字体颜色

```
--nut-button-primary-color
--nut-button-default-color
...
```
