### ISSUE TITLE
Popup事件类型错误

### ISSUE THREAD

**Issue by agileago** [jdf2e/nutui#2468]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

latest

### 平台

weapp

### 重现链接

https://github.com/agileago/vue3-taro

### 重现步骤

tsx下面popup无事件提示

### 期望的结果是什么？

有提示

### 实际的结果是什么？

没有

### 其他补充信息

发现类型变成这样了   

![image](https://github.com/jdf2e/nutui/assets/11799110/7453d00c-e787-497b-992e-3c1c1a8c9bfd)

**Comment by eiinu** [comment]
图中的只是兜底类型，Popup 的事件参数类型在该文件这行代码往上的部分。
没有类型提示可参考：https://github.com/jdf2e/nutui/issues/2461#issuecomment-1655315897

**Comment by agileago** [comment]
@eiinu 生成的是否还是有问题

<img width="620" alt="image" src="https://github.com/jdf2e/nutui/assets/11799110/bd36c373-7516-44ee-a2be-4c7e78365deb">

jsx风格都是camelCase的

**Comment by eiinu** [comment]
> @eiinu 生成的是否还是有问题
> 
> <img alt="image" width="620" src="https://user-images.githubusercontent.com/11799110/258555435-bd36c373-7516-44ee-a2be-4c7e78365deb.png">
> jsx风格都是camelCase的

Popup 组件内的事件使用的是 kebab-case，比如 `click-pop`，在使用模板语法时，`@click-pop` 或者 `@clickPop` 都是合法的。
但是 `vue-tsc` 并没有将这种命名完整地转换为 camelCase，只对首字母处理后加了 on。
vue 本身是兼容两种写法的，`vue-tsc` 这个处理逻辑就很奇怪。
现在看需要都统一改成 camelCase 才行

**Comment by agileago** [comment]
ant-design-vue和naiveui都是对的，所以这块得定个规则，支持tsx

**Comment by eiinu** [comment]
> ant-design-vue和naiveui都是对的，所以这块得定个规则，支持tsx

后续仓库内会增加 [vue/v-on-event-hyphenation](https://eslint.vuejs.org/rules/v-on-event-hyphenation.html#vue-v-on-event-hyphenation) 和 [vue/custom-event-name-casing](https://eslint.vuejs.org/rules/custom-event-name-casing.html) 规则校验

**Comment by agileago** [comment]
@eiinu 类型声明这块不改成 camelCase么？

**Comment by agileago** [comment]
京东内部不使用vue的tsx么？

**Comment by eiinu** [comment]
> @eiinu 类型声明这块不改成 camelCase么？

开发中。
