### ISSUE TITLE
[bug]使用省市区联动组件初始化报错

### ISSUE THREAD

**Issue by wuguobin123** [jdf2e/nutui#247]
## 问题描述

demo的数据虽然可以正常使用，但是具有特殊性。当换成正常的省市区数据时，页面初始化会报错。
原因是获取数据的方式上存在问题：
正确的代码如下：
created() {
    this.listData = [
      ...[this.listData[0]],
      this.data[this.listData[0][0]],
      this.dataSub[this.data[this.listData[0][0]][0]]
    ];
  },

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
月底新版本 会新增一个地址组件了，敬请期待

**Comment by richard1015** [comment]
v2.2.5 已新增地址组件

http://nutui.jd.com/#/Address
