### ISSUE TITLE
Tabs横向显示问题

### ISSUE THREAD

**Issue by GrayCarbon** [jdf2e/nutui#2471]
能否提供一个 设置Tabs靠左、居中、靠右，
当Tabs个数少的时候，居中显示整体看来不是很美观
<img width="410" alt="image" src="https://github.com/jdf2e/nutui/assets/22533675/89c7c124-6ecb-41cc-8dd1-7acc24a06c5d">

**Comment by mikasayw** [comment]
是否可以通过设置style满足你的需求🤔

**Comment by eiinu** [comment]
可以增加一个左对齐的布局，效果参考 NutUI React 版本
