### ISSUE TITLE
[Doc] `<nut-searchbar>` 文档布局崩了

### ISSUE THREAD

**Issue by wenfangdu** [jdf2e/nutui#2474]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

-

### 平台

tt

### 重现链接

https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/searchbar

### 重现步骤

![image](https://github.com/jdf2e/nutui/assets/28700378/cf5c6f10-f8b9-409b-8aaf-1320a9cbd499)

### 期望的结果是什么？

布局没崩

### 实际的结果是什么？

布局崩了

**Comment by eiinu** [comment]
已修改，下次发版时会更新文档
