### ISSUE TITLE
[Bug] `<nut-searchbar>` 输入/删除时闪烁

### ISSUE THREAD

**Issue by wenfangdu** [jdf2e/nutui#2475]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.1.2

### 平台

tt

### 重现链接

https://github.com/wenfangdu/taro-nutui/tree/searchbar

### 重现步骤

https://github.com/jdf2e/nutui/assets/28700378/0dcf4b77-948b-40e3-acf3-9e07c875a1e2

### 期望的结果是什么？

输入/删除时无闪烁

### 实际的结果是什么？

输入/删除时有闪烁

**Comment by wenfangdu** [comment]
@eiinu 4.1.6 并未修复该问题，请重新打开哈

**Comment by eiinu** [comment]
> @eiinu 4.1.6 并未修复该问题，请重新打开哈

使用复现链接仓库代码，真机调试，在输入第一个字符或者删除最后一个字符（对应右侧清除图标出现与消失的状态），输入框的内容会闪烁（宽度变化）。
将仓库依赖升级到 4.1.6 后重新进行真机调试，未复现上述问题。
抖音IDE 版本号 4.1.4，基础库版本 2.98.0.1。
如果仍然有问题，建议提供使用 4.1.6 的可复现代码。

**Comment by wenfangdu** [comment]
@eiinu 已更新代码仓库，抖音 IDE 版本和基础库版本相同，请使用英文输入法复现，快速输入后，会丢失部分文字：

https://github.com/jdf2e/nutui/assets/28700378/b8052fe9-152f-4a1f-b903-3b8faf879c0d

**Comment by wenfangdu** [comment]
@eiinu 已更新代码仓库，抖音 IDE 版本和基础库版本相同，请使用英文输入法复现，快速输入后松手，会丢失部分文字：

https://github.com/jdf2e/nutui/assets/28700378/b8052fe9-152f-4a1f-b903-3b8faf879c0d

**Comment by eiinu** [comment]
> @eiinu 已更新代码仓库，抖音 IDE 版本和基础库版本相同，请使用英文输入法复现，快速输入后松手，会丢失部分文字：
> 
> https://github.com/jdf2e/nutui/assets/28700378/b8052fe9-152f-4a1f-b903-3b8faf879c0d

快速输入时会丢失文字的问题，是 taro input 组件的 input 事件触发先后顺序问题，需要 taro 解决，参考 https://github.com/NervJS/taro/issues/13979

抖音小程序下的闪烁问题是清除图标的样式导致的，这个已经解决。
