### ISSUE TITLE
tabs中使用menu 高度 错误

### ISSUE THREAD

**Issue by gaoxjin** [jdf2e/nutui#2476]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.1.2

### 平台

h5

### 重现链接

[https://codesandbox.io/p/sandbox/nutui4-vite-demo-forked-lrx6n3](https://codesandbox.io/p/sandbox/nutui4-vite-demo-forked-lrx6n3)

### 重现步骤

    <nut-tabs v-model="tab1value" size="large" :swipeable="false" :auto-height="false"
              :sticky="false" :top="0">
      <nut-tab-pane title="列表" pane-key="0">

        <nut-menu :scroll-fixed="false" :lock-scroll="true">
          <nut-menu-item v-model="state1.value1" :options="state1.options1" style=""/>
          <nut-menu-item v-model="state1.value2" @change="handleChange" :options="state1.options2" style=""/>
        </nut-menu>

        <nut-card
            :img-url="state.imgUrl"
            :title="state.title"
            :price="state.price"
            :vipPrice="state.vipPrice"
            :shopDesc="state.shopDesc"
            :delivery="state.delivery"
            :shopName="state.shopName"
            v-for="i in 10"
        ></nut-card>
      </nut-tab-pane>

      <nut-tab-pane title="分类" pane-key="1">
          <div>分类分类分类分类</div>
      </nut-tab-pane>

    </nut-tabs>

![image](https://github.com/jdf2e/nutui/assets/7439572/9ca2226d-a078-4c6a-bf1b-cb0965908739)
展开后
![image](https://github.com/jdf2e/nutui/assets/7439572/7e75a8b5-dfef-4bd8-872f-2e01a5c05be5)

### 期望的结果是什么？

![image](https://github.com/jdf2e/nutui/assets/7439572/c64c74b2-174c-4704-b66e-8771486e227a)

### 实际的结果是什么？

![image](https://github.com/jdf2e/nutui/assets/7439572/88b172d4-d17a-4d03-bf93-e37283f9fbd9)

**Comment by eiinu** [comment]
没有复现：[demo](https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LXRhYnMgdi1tb2RlbD1cInN0YXRlLnRhYjF2YWx1ZVwiIDphbmltYXRlZC10aW1lPVwiMFwiPlxuICAgIDxudXQtdGFiLXBhbmUgdGl0bGU9XCJUYWIgMVwiIHBhbmUta2V5PVwiMTExXCI+XG4gICAgXHQ8bnV0LW1lbnU+XG4gICAgICAgIDxudXQtbWVudS1pdGVtIHYtbW9kZWw9XCJzdGF0ZS52YWx1ZTFcIiA6b3B0aW9ucz1cInN0YXRlLm9wdGlvbnMxXCIgLz5cbiAgICAgICAgPG51dC1tZW51LWl0ZW0gdi1tb2RlbD1cInN0YXRlLnZhbHVlMlwiIDpvcHRpb25zPVwic3RhdGUub3B0aW9uczJcIiAvPlxuICAgICAgPC9udXQtbWVudT5cbiAgICAgIDxkaXY+MTIzPC9kaXY+XG4gICAgICA8ZGl2PjEyMzwvZGl2PlxuICAgICAgPGRpdj4xMjM8L2Rpdj5cbiAgICAgIDxkaXY+MTIzPC9kaXY+XG4gICAgICA8ZGl2PjEyMzwvZGl2PlxuICAgICAgPGRpdj4xMjM8L2Rpdj5cbiAgICAgIDxkaXY+MTIzPC9kaXY+XG4gICAgPC9udXQtdGFiLXBhbmU+XG4gICAgPG51dC10YWItcGFuZSB0aXRsZT1cIlRhYiAyXCIgcGFuZS1rZXk9XCIyMjJcIj4gVGFiIDIgPC9udXQtdGFiLXBhbmU+XG4gICAgPG51dC10YWItcGFuZSB0aXRsZT1cIlRhYiAzXCIgcGFuZS1rZXk9XCIzMzNcIj4gVGFiIDMgPC9udXQtdGFiLXBhbmU+XG4gIDwvbnV0LXRhYnM+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIj5cbiAgaW1wb3J0IHsgcmVhY3RpdmUgfSBmcm9tICd2dWUnO1xuICBleHBvcnQgZGVmYXVsdCB7XG4gICAgc2V0dXAoKSB7XG4gICAgICBjb25zdCBzdGF0ZSA9IHJlYWN0aXZlKHtcbiAgICAgICAgdGFiMXZhbHVlOiAnMTExJyxcbiAgICAgICAgb3B0aW9uczE6IFtcbiAgICAgICAgICB7IHRleHQ6ICflhajpg6jllYblk4EnLCB2YWx1ZTogMCB9LFxuICAgICAgICAgIHsgdGV4dDogJ+aWsOasvuWVhuWTgScsIHZhbHVlOiAxIH0sXG4gICAgICAgICAgeyB0ZXh0OiAn5rS75Yqo5ZWG5ZOBJywgdmFsdWU6IDIgfVxuICAgICAgICBdLFxuICAgICAgICBvcHRpb25zMjogW1xuICAgICAgICAgIHsgdGV4dDogJ+m7mOiupOaOkuW6jycsIHZhbHVlOiAnYScgfSxcbiAgICAgICAgICB7IHRleHQ6ICflpb3or4TmjpLluo8nLCB2YWx1ZTogJ2InIH0sXG4gICAgICAgICAgeyB0ZXh0OiAn6ZSA6YeP5o6S5bqPJywgdmFsdWU6ICdjJyB9XG4gICAgICAgIF0sXG4gICAgICAgIHZhbHVlMTogMCxcbiAgICAgICAgdmFsdWUyOiAnYSdcbiAgICAgIH0pO1xuICAgICAgcmV0dXJuIHsgc3RhdGUgfTtcbiAgICB9XG4gIH07XG48L3NjcmlwdD5cbjxzdHlsZT5cbiAgLm51dC10YWItcGFuZSB7XG4gICAgcGFkZGluZzogMCAhaW1wb3J0YW50O1xuICB9XG48L3N0eWxlPiJ9)

**Comment by gaoxjin** [comment]
@eiinu https://codesandbox.io/p/sandbox/nutui4-vite-demo-forked-lrx6n3?welcome=true

**Comment by eiinu** [comment]
> @eiinu [codesandbox.io/p/sandbox/nutui4-vite-demo-forked-lrx6n3?welcome=true](https://codesandbox.io/p/sandbox/nutui4-vite-demo-forked-lrx6n3?welcome=true)

默认情况下，Tabs 内部使用 transform 实现多面板切换，而 Menu 使用的是固定定位，这两种样式会冲突。
可以设置 Tabs 的 `:animated-time="0"`，这时 Tabs 就会变为直接替换面板的定位，就可以嵌套 Menu 了。

**Comment by gaoxjin** [comment]
@eiinu 多谢

**Comment by GreatAuk** [comment]
> > @eiinu [codesandbox.io/p/sandbox/nutui4-vite-demo-forked-lrx6n3?welcome=true](https://codesandbox.io/p/sandbox/nutui4-vite-demo-forked-lrx6n3?welcome=true)
> 
> 默认情况下，Tabs 内部使用 transform 实现多面板切换，而 Menu 使用的是固定定位，这两种样式会冲突。 可以设置 Tabs 的 `:animated-time="0"`，这时 Tabs 就会变为直接替换面板的定位，就可以嵌套 Menu 了。

这个是不是写到文档上好些， 感觉这种场景挺多的
