### ISSUE TITLE
[bug]省市区设计思路问题

### ISSUE THREAD

**Issue by wuguobin123** [jdf2e/nutui#248]
## 问题描述

省市区组件的设计思路是用中文进行匹配，这样会遇到在直辖市一级时，会出现重复的数据，如重庆市和上海市（都有“县”和辖”），这样进行匹配的时候数据就会串。

暂时解决方案：可以将县和辖的数据进行合并；或者对相同的中文数据进行重定义来区分。
一劳永逸的方案：利用唯一的ID值来进行数据的匹配查询。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
月底新版本  会新增一个地址组件了，敬请期待

**Comment by richard1015** [comment]
v2.2.5 已新增地址组件

http://nutui.jd.com/#/Address
