### ISSUE TITLE
CircleProgress 环形进度条每秒更新进度会闪烁

### ISSUE THREAD

**Issue by SuGod** [jdf2e/nutui#2481]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.1.3

### 平台

weapp

### 重现链接

https://github.com/SuGod/nut-circle-progress-demo.git

### 重现步骤

微信小程序开发工具中正常,但是IOS真机预览时会出现闪烁(每次进度更新时大小会变)

### 期望的结果是什么？

ios真机预览正常

### 实际的结果是什么？

ios真机预览出现闪烁

### 环境信息

```
👽 Taro v3.6.6


  Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 19.7.0 - ~\scoop\apps\nodejs\current\node.EXE
      npm: 9.5.0 - ~\scoop\apps\nodejs\current\npm.CMD
```

IOS版本: 16.5.1

微信版本: 8.0.40

### 其他补充信息

Android 未测试

**Comment by eiinu** [comment]
需要提供一下闪烁的录屏效果以更快地排查问题

**Comment by SuGod** [comment]
> @eiinu 

https://github.com/jdf2e/nutui/assets/18413524/14b64321-2da8-4cee-be59-928db7121b87

**Comment by chenchunfeng** [comment]
我今天也发现了，安卓正常，就苹果不行
