### ISSUE TITLE
scroller组件可以自定义上拉和下拉的有无嘛?

### ISSUE THREAD

**Issue by qsjc** [jdf2e/nutui#249]
## 你建议我们做什么？

可以定义scroller有单独的上拉或者下拉功能嘛? 而不是同时存在
因为有些页面真的是不需要下拉  
另外滚动感觉不是很流畅哎 惯性好低

**Comment by richard1015** [comment]
感谢您的反馈，我们近期优化一下这个问题

**Comment by wangjun521** [comment]
感谢回复  因为有时候可能只是想要个滚动或者单纯某一项
毕竟会比浏览器原生的滚动体验更棒  
期待早日更新呀

**Comment by richard1015** [comment]
流畅的滚动 你可以采用 [ InfiniteLoading](http://nutui.jd.com/#/InfiniteLoading) 无限加载组件

**Comment by wangjun521** [comment]
这个明白的 只不过项目中基本 是用不到这个组件的  hhhh

**Comment by richard1015** [comment]
ing

**Comment by richard1015** [comment]
不需要下拉 采用 [ InfiniteLoading](http://nutui.jd.com/#/InfiniteLoading) 无限加载组件
