### ISSUE TITLE
地址列表的数据项数不全，会露出例子数据，帮忙看下能否处理？

### ISSUE THREAD

**Issue by beanhacker** [jdf2e/nutui#2491]
如果以下数据缺少某个字段或者这个字段为空，会露出以下默认的数据。

id: 2,

addressName: '姓名',

phone: '123****4567',

defaultAddress: false,

fullAddress: '北京市通州区测试测试测试测试测试测试测试测试测试'

**Comment by eiinu** [comment]
不通过 Template 创建的 Issue 将会被关闭。

**Comment by beanhacker** [comment]
我这边没有模板，就是一个提交框。
