### ISSUE TITLE
table组件不知道是bug还是建议加新feat功能

### ISSUE THREAD

**Issue by kuzanFrozen** [jdf2e/nutui#2499]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.1.3

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LXRhYmxlIDpjb2x1bW5zPVwiY29sdW1uc1wiIDpkYXRhPVwiZGF0YVwiPjwvbnV0LXRhYmxlPlxuICB7e2RhdGF9fVxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCI+XG4gIGltcG9ydCB7IHJlYWN0aXZlLCB0b1JlZnMsIGggfSBmcm9tICd2dWUnO1xuICBleHBvcnQgZGVmYXVsdCB7XG4gICAgcHJvcHM6IHt9LFxuICAgIHNldHVwKCkge1xuICAgICAgY29uc3Qgc3RhdGUgPSByZWFjdGl2ZSh7XG4gICAgICAgIGNvbHVtbnM6IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB0aXRsZTogJ+Wnk+WQjScsXG4gICAgICAgICAgICBrZXk6ICduYW1lJyxcbiAgICAgICAgICAgIHN0eWxlaGVhZDogJ2ZvbnQtc2l6ZToyMHB4O2NvbG9yOnJlZDtmb250LXdlaWdodDpib2xkZXI7JyxcbiAgICAgICAgICAgIHN0eWxlY29sdW1uOiAnZm9udC1zaXplOjEwcHg7Y29sb3I6Ymx1ZTsnXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB0aXRsZTogJ+aAp+WIqycsXG4gICAgICAgICAgICBrZXk6ICdzZXgnLFxuICAgICAgICAgICAgcmVuZGVyOiAocmVjb3JkKSA9PiB7XG4gICAgICAgICAgICAgIHJldHVybiBoKFxuICAgICAgICAgICAgICAgICdzcGFuJyxcbiAgICAgICAgICAgICAgICB7XG4gICAgICAgICAgICAgICAgICBzdHlsZToge1xuICAgICAgICAgICAgICAgICAgICBjb2xvcjogcmVjb3JkLnNleCA9PT0gJ+WlsycgPyAnYmx1ZScgOiAnZ3JlZW4nXG4gICAgICAgICAgICAgICAgICB9XG4gICAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgICAgICByZWNvcmQuc2V4XG4gICAgICAgICAgICAgICk7XG4gICAgICAgICAgICB9XG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB0aXRsZTogJ+W5tOm+hCcsXG4gICAgICAgICAgICByZW5kZXI6KHJlY29yZCkgPT57XG4gICAgICAgICAgICAgIHJldHVybiBoKCdpbnB1dCcsIHtcbiAgICAgICAgICAgICAgICB2YWx1ZTogcmVjb3JkWydhZ2UnXSxcbiAgICAgICAgICAgICAgICBvbklucHV0KGUpIHtcbiAgICAgICAgICAgICAgICAgIHJlY29yZFsnYWdlJ10gPSBlLmRhdGFcbiAgICAgICAgICAgICAgICB9XG4gICAgICAgICAgICAgIH0pXG4gICAgICAgICAgICB9XG4gICAgICAgICAgfVxuICAgICAgICBdLFxuICAgICAgICBkYXRhOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbmFtZTogJ1RvbScsXG4gICAgICAgICAgICBzZXg6ICfnlLcnLFxuICAgICAgICAgICAgYWdlOiAnMSdcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIG5hbWU6ICdMdWN5JyxcbiAgICAgICAgICAgIHNleDogJ+WlsycsXG4gICAgICAgICAgICBhZ2U6ICcyJ1xuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgbmFtZTogJ0phY2snLFxuICAgICAgICAgICAgc2V4OiAn55S3JyxcbiAgICAgICAgICAgIGFnZTogJzMnXG4gICAgICAgICAgfVxuICAgICAgICBdXG4gICAgICB9KTtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIC4uLnRvUmVmcyhzdGF0ZSlcbiAgICAgIH07XG4gICAgfVxuICB9O1xuPC9zY3JpcHQ+XG4ifQ==

### 重现步骤

table中 render一个input，并修改赋值，数据未更新

### 期望的结果是什么？

table中 render一个input，并修改赋值，数据更新

### 实际的结果是什么？

table中 render一个input，并修改赋值，数据未更新

**Comment by eiinu** [comment]
```js
render:(record) =>{
  return h('input', {
    value: record['age'],
    onInput(e) {
      record['age'] = e.target.value
    }
  })
}
```
[playground](https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LXRhYmxlIDpjb2x1bW5zPVwiY29sdW1uc1wiIDpkYXRhPVwiZGF0YVwiPjwvbnV0LXRhYmxlPlxuICB7e2RhdGF9fVxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCI+XG4gIGltcG9ydCB7IHJlYWN0aXZlLCB0b1JlZnMsIGggfSBmcm9tICd2dWUnO1xuICBleHBvcnQgZGVmYXVsdCB7XG4gICAgcHJvcHM6IHt9LFxuICAgIHNldHVwKCkge1xuICAgICAgY29uc3Qgc3RhdGUgPSByZWFjdGl2ZSh7XG4gICAgICAgIGNvbHVtbnM6IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB0aXRsZTogJ+Wnk+WQjScsXG4gICAgICAgICAgICBrZXk6ICduYW1lJyxcbiAgICAgICAgICAgIHN0eWxlaGVhZDogJ2ZvbnQtc2l6ZToyMHB4O2NvbG9yOnJlZDtmb250LXdlaWdodDpib2xkZXI7JyxcbiAgICAgICAgICAgIHN0eWxlY29sdW1uOiAnZm9udC1zaXplOjEwcHg7Y29sb3I6Ymx1ZTsnXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB0aXRsZTogJ+aAp+WIqycsXG4gICAgICAgICAgICBrZXk6ICdzZXgnLFxuICAgICAgICAgICAgcmVuZGVyOiAocmVjb3JkKSA9PiB7XG4gICAgICAgICAgICAgIHJldHVybiBoKFxuICAgICAgICAgICAgICAgICdzcGFuJyxcbiAgICAgICAgICAgICAgICB7XG4gICAgICAgICAgICAgICAgICBzdHlsZToge1xuICAgICAgICAgICAgICAgICAgICBjb2xvcjogcmVjb3JkLnNleCA9PT0gJ+WlsycgPyAnYmx1ZScgOiAnZ3JlZW4nXG4gICAgICAgICAgICAgICAgICB9XG4gICAgICAgICAgICAgICAgfSxcbiAgICAgICAgICAgICAgICByZWNvcmQuc2V4XG4gICAgICAgICAgICAgICk7XG4gICAgICAgICAgICB9XG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB0aXRsZTogJ+W5tOm+hCcsXG4gICAgICAgICAgICByZW5kZXI6KHJlY29yZCkgPT57XG4gICAgICAgICAgICAgIHJldHVybiBoKCdpbnB1dCcsIHtcbiAgICAgICAgICAgICAgICB2YWx1ZTogcmVjb3JkWydhZ2UnXSxcbiAgICAgICAgICAgICAgICBvbklucHV0KGUpIHtcbiAgICAgICAgICAgICAgICAgIHJlY29yZFsnYWdlJ10gPSBlLnRhcmdldC52YWx1ZVxuICAgICAgICAgICAgICAgIH1cbiAgICAgICAgICAgICAgfSlcbiAgICAgICAgICAgIH1cbiAgICAgICAgICB9XG4gICAgICAgIF0sXG4gICAgICAgIGRhdGE6IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBuYW1lOiAnVG9tJyxcbiAgICAgICAgICAgIHNleDogJ+eUtycsXG4gICAgICAgICAgICBhZ2U6ICcxJ1xuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgbmFtZTogJ0x1Y3knLFxuICAgICAgICAgICAgc2V4OiAn5aWzJyxcbiAgICAgICAgICAgIGFnZTogJzInXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBuYW1lOiAnSmFjaycsXG4gICAgICAgICAgICBzZXg6ICfnlLcnLFxuICAgICAgICAgICAgYWdlOiAnMydcbiAgICAgICAgICB9XG4gICAgICAgIF1cbiAgICAgIH0pO1xuICAgICAgcmV0dXJuIHtcbiAgICAgICAgLi4udG9SZWZzKHN0YXRlKVxuICAgICAgfTtcbiAgICB9XG4gIH07XG48L3NjcmlwdD5cbiJ9)
