### ISSUE TITLE
[FR]: Calendar组件能支持在 可选日期start-date 和 end-date 之间 设置某些日期不可选择么？

### ISSUE THREAD

**Issue by laoriy** [jdf2e/nutui#2502]
### 这个功能解决了什么问题？

比如想看用户近一个月中某天的数据，其中有些日期是不可选择的，可以通过禁用选择来标识。

### 你期望的组件设计是怎样的？

通过对每个日期单元格进行一个用户自定义的formatter  ，返回如disabled这样特性的属性。

**Comment by momtboy** [comment]
这个功能有计划开发嘛，确实很需要，特别是电商项目。
