### ISSUE TITLE
[bug]SideNavBar组件，嵌套使用时，如果一个层级引入了多个<nut-subsidenavbar>,会导致第二个<nut-subsidenavbar>的offset计算错误

### ISSUE THREAD

**Issue by reidsu** [jdf2e/nutui#252]
代码如下：

>   <nut-sidenavbar :show="show3">
          <nut-subsidenavbar title="智能城市AI" ikey="6">
            <nut-subsidenavbar title="人体识别1" ikey="9">
              <nut-sidenavbaritem ikey="10" title="人体检测1"></nut-sidenavbaritem>
              <nut-sidenavbaritem ikey="11" title="细粒度人像分割1"></nut-sidenavbaritem>
            </nut-subsidenavbar>
            <nut-subsidenavbar title="人体识别2" ikey="12">
              <nut-sidenavbaritem ikey="13" title="人体检测2"></nut-sidenavbaritem>
              <nut-sidenavbaritem ikey="14" title="细粒度人像分割2"></nut-sidenavbaritem>
            </nut-subsidenavbar>
          </nut-subsidenavbar>
        </nut-sidenavbar>

最终效果：

"人体识别1"子元素“人体检测1”计算offset为45，而"人体识别2"子元素“人体检测2”计算的offset为30.

**Comment by szg2008** [comment]
目前已在v2-dev分支上修复，等下个版本一起发布
