### ISSUE TITLE
Rate 评分组件，无法修改星星的颜色[question]

### ISSUE THREAD

**Issue by carpenterzoe** [jdf2e/nutui#253]
## 问题描述

Rate 评分这个组件的颜色无法配置，也不能通过修改样式来修改。
固定一种红色，可能并不适用于很多项目的ui风格。

**Comment by richard1015** [comment]
请先采用 自定义Icon 来实现此需求

**Comment by carpenterzoe** [comment]
谢谢，我已经用重写svg样式来暂时实现需求了。
