### ISSUE TITLE
nut-steps 点击事件click-step无效，官网演示也无效

### ISSUE THREAD

**Issue by Mystuddent** [jdf2e/nutui#2530]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.1.3

### 平台

weapp

### 重现链接

https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/steps

### 重现步骤

在官网示例中可复现。https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/steps

### 期望的结果是什么？

增加点击事件

### 实际的结果是什么？

无点击事件

**Comment by Mystuddent** [comment]
可以在官网示例中明显看到示例。在官网的4.版本中的基础示例中，点击后控制台无日志。示例地址：https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/steps
![image](https://github.com/jdf2e/nutui/assets/24928560/f064f6b7-fdf6-417d-b3f7-24da7dafbf94)

在3.版本中无问题，示例地址：https://nutui.jd.com/3x/#/zh-CN/component/steps
![image](https://github.com/jdf2e/nutui/assets/24928560/4b12d35f-3b90-4bef-94c8-597f2d37c0a9)

**Comment by eiinu** [comment]
这个是网站 demo 的代码中没有编写该事件的触发逻辑，下次发版会加上。
组件本身没有问题。

**Comment by Mystuddent** [comment]
> 这个是网站demo的代码中没有编写该事件的触发逻辑，接下来发版会加上 组件。本身没有问题。

谢谢，我自己本地测试后无问题，当时官网看到示例无效。
