### ISSUE TITLE
Picker 组件可否加一个 visible-option-num 属性来设置可见的选项个数，现在默认是7个貌似无法改变

### ISSUE THREAD

**Issue by laoriy** [jdf2e/nutui#2535]
### 这个功能解决了什么问题？

有时候并不需要很高的容器显示那么多的可见选项，只想显示三个，目前无法做到

### 你期望的组件设计是怎样的？

加一个visible-option-num 即可，

**Comment by eiinu** [comment]
<img width="1157" alt="image" src="https://github.com/jdf2e/nutui/assets/44915689/4d22b4d7-1856-430c-a1a5-9e5bff188888">
