### ISSUE TITLE
Tab组件展示demo，最下面禁止选中的动画[suggest]

### ISSUE THREAD

**Issue by MangoTsing** [jdf2e/nutui#254]
## Tab组件展示demo，最下面禁止选中的动画

选中tab时背景颜色没有transition太诡异了，而且下面的条条还有0.4s的过渡

如果稍微修改一下，把背景颜色搞成平移滑块的样式，和底部条条同步过渡会好看很多

起码让人觉得ui整体统一。

**Comment by zhenyulei** [comment]
你好 感谢您的反馈 因为最后一个tab示例样式其实是用户来定义的【也就是在demo中自定义的】 tab组件的选中样式其实是前几个示例中展示的样子 选中后底部位置条移动 如果想要更好的效果 还请在组件外侧自定义哈
