### ISSUE TITLE
bug:input type="digit"软键盘没有小数点，设置了这个属性导致会有小数点的值变成了整数

### ISSUE THREAD

**Issue by kuzanFrozen** [jdf2e/nutui#2542]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.1.3

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LWlucHV0IHYtbW9kZWw9XCJzdGF0ZS50ZXh0XCIgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXmlofmnKxcIiB0eXBlPVwiZGlnaXRcIi8+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIj5cbiAgaW1wb3J0IHsgcmVhY3RpdmUgfSBmcm9tICd2dWUnO1xuICBleHBvcnQgZGVmYXVsdCB7XG4gICAgc2V0dXAoKSB7XG4gICAgICBjb25zdCBzdGF0ZSA9IHJlYWN0aXZlKHtcbiAgICAgICAgdGV4dDogJzEuMSdcbiAgICAgIH0pO1xuICAgICAgcmV0dXJuIHtcbiAgICAgICAgc3RhdGVcbiAgICAgIH07XG4gICAgfVxuICB9O1xuPC9zY3JpcHQ+XG4ifQ==

### 重现步骤

链接上能复现

### 期望的结果是什么？

input type="digit"软键盘要有小数点，设置了这个属性不会导致会有小数点的值变成了整数

### 实际的结果是什么？

input type="digit"软键盘没有小数点，设置了这个属性导致会有小数点的值变成了整数

**Comment by eiinu** [comment]
number 为数字类型，digit 为整数。
为了同时兼容 H5 和小程序，NutUI 的 input 并没有使用小程序原生键盘。
