### ISSUE TITLE
popover在cell组件内无法正常使用

### ISSUE THREAD

**Issue by lSpikeSpiegel** [jdf2e/nutui#2544]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.1.5

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7cmVmLCByZWFjdGl2ZX0gZnJvbSAndnVlJztcbmNvbnN0IHZpc2libGUgPSByZWYoe1xuXHRkYXJrVGhlbWU6IGZhbHNlLFxuXHRsaWdodFRoZW1lOiBmYWxzZVxufSk7XG5jb25zdCBpY29uSXRlbUxpc3QgPSByZWFjdGl2ZShbeyBuYW1lOiBcIumAiemhueS4gFwiIH0sIHsgbmFtZTogXCLpgInpobnkuoxcIiB9LCB7IG5hbWU6IFwi6YCJ6aG55LiJXCIgfV0pO1xuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG5cdFx0XHQ8bnV0LWNlbGw+XG5cdFx0XHRcdDxudXQtcG9wb3ZlclxuXHRcdFx0XHRcdHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGUubGlnaHRUaGVtZVwiXG5cdFx0XHRcdFx0Omxpc3Q9XCJpY29uSXRlbUxpc3RcIlxuXHRcdFx0XHRcdGxvY2F0aW9uPVwiYm90dG9tXCJcblx0XHRcdFx0PlxuXHRcdFx0XHRcdDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuXHRcdFx0XHRcdFx0PGRpdj7mm7TlpJo8L2Rpdj5cblx0XHRcdFx0XHQ8L3RlbXBsYXRlPlxuXHRcdFx0XHQ8L251dC1wb3BvdmVyPlxuXHRcdFx0PC9udXQtY2VsbD5cbjwvdGVtcGxhdGU+In0=

### 重现步骤

重现链接中的代码在web端能够正常运行，在小程序的模拟器和真机上则无法正常弹出popover

### 期望的结果是什么？

能够在cell组件中正常使用popover组件

### 实际的结果是什么？

无法正常使用

### 环境信息

  Taro CLI 3.6.15 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: ^3.6.15 => 3.6.15
      @tarojs/components: ^3.6.15 => 3.6.15
      @tarojs/helper: ^3.6.15 => 3.6.15
      @tarojs/plugin-framework-react: ^3.6.15 => 3.6.15
      @tarojs/plugin-framework-vue3: ^3.6.15 => 3.6.15
      @tarojs/plugin-html: ^3.6.15 => 3.6.15
      @tarojs/plugin-platform-alipay: ^3.6.15 => 3.6.15
      @tarojs/plugin-platform-jd: ^3.6.15 => 3.6.15
      @tarojs/plugin-platform-qq: ^3.6.15 => 3.6.15
      @tarojs/plugin-platform-swan: ^3.6.15 => 3.6.15
      @tarojs/plugin-platform-tt: ^3.6.15 => 3.6.15
      @tarojs/plugin-platform-weapp: ^3.6.15 => 3.6.15
      @tarojs/router: ^3.6.15 => 3.6.15
      @tarojs/runtime: ^3.6.15 => 3.6.15
      @tarojs/shared: ^3.6.15 => 3.6.15
      @tarojs/taro: ^3.6.15 => 3.6.15
      @tarojs/taro-h5: ^3.6.15 => 3.6.15
      @tarojs/webpack5-runner: ^3.6.15 => 3.6.15
      babel-preset-taro: ^3.6.15 => 3.6.15
      eslint-config-taro: ^3.6.15 => 3.6.15

**Comment by ptko5** [comment]
popover在cell-group组件内无法正常使用
