### ISSUE TITLE
[FR]: Collapse组件能否提供修改CollapseItem底部分割线颜色和左右间距的样式变量？

### ISSUE THREAD

**Issue by ColinHwang** [jdf2e/nutui#2557]
### 这个功能解决了什么问题？

产品总是有新的想法。。。Collapse组件能否提供修改CollapseItem底部分割线颜色和左右间距的样式变量？

### 你期望的组件设计是怎样的？

--nut-collapse-item-border-bottom-line-color: #ebedf0;
--nut-collapse-item-border-bottom-line-margin-left: 16px;
--nut-collapse-item-border-bottom-line-margin-right: 16px;

**Comment by eiinu** [comment]
这种情况建议自己写选择器覆盖组件内的样式
