### ISSUE TITLE
[question]Infiniteloading 组件在配合由定位实现的瀑布流的时候，滚动就会触发多次加载事件，怎么解决

### ISSUE THREAD

**Issue by xts871722743** [jdf2e/nutui#256]
## 你想知道什么？

你好，我想知道这个项目是否可以...

## 描述你考虑过的替代方案

我想...

## 其它

无

**Comment by richard1015** [comment]
是否可以提供一个最小复现代码

**Comment by xts871722743** [comment]
链接：https://sp6tv.csb.app/
在loadmore里面写的console，滚动就会触发

**Comment by irisSong** [comment]
请提供一个最小复现代仓库，不是页面地址哦！

**Comment by richard1015** [comment]
@irisSong 

https://codesandbox.io/s/sp6tv?file=/src/components/HelloWorld.vue

**Comment by richard1015** [comment]
如果页面固定高度 请参考 use-window 参数来处理
