### ISSUE TITLE
inut-popup 组件嵌套一个弹出  nut-date-picker 组件，在android 显示正常，iOS显示不正常

### ISSUE THREAD

**Issue by xiangBiaoOne** [jdf2e/nutui#2562]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.0.4

### 平台

h5

### 重现链接

没办法提供链接

### 重现步骤

inut-popup 组件嵌套一个弹出  nut-date-picker 组件，在android 显示正常，iOS显示不正常

### 期望的结果是什么？

![企业微信20230914-173036](https://github.com/jdf2e/nutui/assets/16659627/d67d169e-69ab-469d-9592-2f73a29f3aeb)

### 实际的结果是什么？

![IMG_0795](https://github.com/jdf2e/nutui/assets/16659627/90be131e-c6ee-443e-9980-e7a37afb4767)

**Comment by eiinu** [comment]
Popup 使用 fixed 定位，多个 Popup 通过 z-index 实现分层
safari 对于 fixed 元素的 z-index 处理有问题

**Comment by xiangBiaoOne** [comment]
> Popup 使用 fixed 定位，多个 Popup 通过 z-index 实现分层 safari 对于 fixed 元素的 z-index 处理有问题

有好的方案解决这个问题吗？

**Comment by Wws54loi** [comment]
遇到了同样的问题 有解决方式嘛？

**Comment by xiangBiaoOne** [comment]
> 遇到了同样的问题 有解决方式嘛？

我现在的处理方法是，把弹窗组建放到了最外层。放到了侧拉菜单平级节点。这样有点麻烦，但是能解决问题

**Comment by xiangBiaoOne** [comment]
> 遇到了同样的问题 有解决方式嘛？

再次回答，其实文档有给出方案：
<template>
  <nut-cell title="多层堆叠" is-link @click="showPop1 = true"></nut-cell>
  <nut-popup :style="{ padding: '30px 50px' }" v-model:visible="showPop1">
    <div @click="showPop2 = true">点击它</div>
  </nut-popup>
  <nut-popup :style="{ padding: '30px 50px' }" v-model:visible="showPop2">正文</nut-popup>
</template>
<script setup>
import { ref } from 'vue';
const showPop1 = ref(false);
const showPop2 = ref(false);
</script>
  nut-popup 不能嵌套、只能并排。写的时候注意一下就ok

**Comment by xiangBiaoOne** [comment]
> Popup 使用 fixed 定位，多个 Popup 通过 z-index 实现分层 safari 对于 fixed 元素的 z-index 处理有问题

已经解决了，谢谢

**Comment by xiangBiaoOne** [comment]
> 你好 @xiangBiaoOne, 我们需要你提供一个最小重现实例以便于我们帮你排查问题。你可以提供一个基于 Taro NutUI4.0 模板项目的 GitHub 仓库链接（`@nutui/nutui-taro`），也可以通过 [CodeSandbox](https://codesandbox.io/s/nutui4-vite-demo-2fw7xh?file=/src/App.vue) 创建一个在线实例（`@nutui/nutui`）。请确保选择准确的版本。

已经解决了，谢谢
