### ISSUE TITLE
[bug]video组件运行控制台会报错

### ISSUE THREAD

**Issue by albgjws** [jdf2e/nutui#257]
## 问题描述

错误提示：Uncaught DOMException: Failed to execute 'end' on 'TimeRanges': The index provided (0) is greater than or equal to the maximum bound (0).

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为

![image](https://user-images.githubusercontent.com/19258900/82640856-ec52aa00-9c3d-11ea-8092-e89afb39c188.png)
源码中添加这个判断可以解决报错问题：
// 获取缓存时间
            getLoadTime() {
                // console.log('缓存了...',this.videoElm.buffered.end(0));
                if(this.videoElm.buffered.length!=0){
                    this.videoSet.loaded = (this.videoElm.buffered.end(0) / this.videoElm.duration) * 100;
                }
            }

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by vickyYE** [comment]
新版会修复该问题
