### ISSUE TITLE
cascader组件，选择选择城市区 数据多时，Y轴无法进行滚动

### ISSUE THREAD

**Issue by sufansufan** [jdf2e/nutui#2571]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.1.2

### 平台

weapp

### 重现链接

https://github.com/jdf2e/nutui/blob/v4/src/packages/__VUE/cascader/cascader-item.vue

### 重现步骤

```
     <nut-cascader
        title="地址选择"
        v-model:visible="address.visible"
        v-model="address.value"
        @change="addressChange"
        @pathChange="pathChange"
        :options="address.options"
      >
      </nut-cascader>
```

### 期望的结果是什么？

内容增加scroll-view包裹

### 实际的结果是什么？

内容无法滚动

**Comment by eiinu** [comment]
可以测试一下最新版本

**Comment by sufansufan** [comment]
4.1.5的版本没有问题
