### ISSUE TITLE
uploader组件在高于小程序基础库2.33.0的版本点击无反应

### ISSUE THREAD

**Issue by Xhyen** [jdf2e/nutui#2576]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.1.6

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IERvbmdkb25nIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcbmNvbnN0IHNob3cgPSAoKSA9PiB7XG4gIHNob3dUb2FzdC50ZXh0KCdIZWxsbywgTnV0VUkhJylcbn07XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC11cGxvYWRlclxuICAgIHVybD1cIjEyM1wiXG4gICAgaGVhZGVycz1cIjEyM1wiXG4gICAgOm1heGltaXplPVwiMTAyNCAqIDEwMjQgKiA1XCJcbiAgICBtYXhpbXVtPVwiMlwiXG4gICAgOnNpemUtdHlwZT1cIlsnY29tcHJlc3NlZCddXCJcbiAgPlxuICA8L251dC11cGxvYWRlcj5cbjwvdGVtcGxhdGU+In0=

### 重现步骤

点击无反应

### 期望的结果是什么？

点击有响应

### 实际的结果是什么？

目前点击结果无反应

### 环境信息

👽 Taro v3.6.16

  Taro CLI 3.6.16 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2
      @tarojs/components: 3.6.2 => 3.6.2
      @tarojs/helper: 3.6.2 => 3.6.2
      @tarojs/mini-runner: 3.6.2 => 3.6.2
      @tarojs/plugin-framework-vue3: 3.6.2 => 3.6.2
      @tarojs/plugin-html: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2
      @tarojs/runtime: 3.6.2 => 3.6.2
      @tarojs/shared: 3.6.2 => 3.6.2
      @tarojs/taro: 3.6.2 => 3.6.2
      @tarojs/webpack-runner: 3.6.2 => 3.6.2
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2
      babel-preset-taro: 3.6.2 => 3.6.2
      eslint-config-taro: 3.6.2 => 3.6.2

**Comment by Xhyen** [comment]
![飞书20230919-155258](https://github.com/jdf2e/nutui/assets/17582511/54c55f33-e335-4ac6-91a9-8844ab0e87e4)

**Comment by Xhyen** [comment]
如上面动图，在开发者工具就可复现

**Comment by Xhyen** [comment]
哦是权限问题，已经解决

**Comment by beehoo** [comment]
> 哦是权限问题，已经解决

请问下是要配置哪里的权限？

**Comment by FireFoxMsj** [comment]
我这边也是低版本基础库使用是可以的3.2.0就不行了，要哪里配置权限么?

**Comment by eiinu** [comment]
> 我这边也是低版本基础库使用是可以的3.2.0就不行了，要哪里配置权限么?

需要在微信隐私协议中声明读取相册相关的内容

**Comment by FireFoxMsj** [comment]
配置上了   没有提示信息不好排查问题
