### ISSUE TITLE
nutui如果在nut-form里引入外部的表单组件（输入框什么的），同时在nut-form里定义外部组件的必填验证的操作后，nut-form不会校验外部的这个组件吗？

### ISSUE THREAD

**Issue by myby7000p** [jdf2e/nutui#2577]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.0.4

### 平台

h5, weapp

### 重现链接

https://codesandbox.io/p/sandbox/nutui4-vite-demo-forked-k3jtth?welcome=true

### 重现步骤

nutui如果在el-form里引入外部的表单组件（输入框什么的），同时在el-form里定义外部组件的必填验证的操作后，el-form不会校验外部的这个组件吗？

### 期望的结果是什么？

在el-form里点击校验必填项的时候，校验外部引用的组件

### 实际的结果是什么？

在el-form里点击校验必填项的时候，现在没用校验外部引用的组件

**Comment by mikasayw** [comment]
原因是递归slot.default时获取不到自定义组件内部的vnode，业务上可以先用ref循环应急一下
@eiinu 大佬看看有好的解决思路吗

**Comment by myby7000p** [comment]
> 原因是递归slot.default时获取不到自定义组件内部的vnode，业务上可以先用ref循环应急一下 @eiinu 大佬看看有好的解决思路吗

ref循环怎么应急，请大佬明示

**Comment by mikasayw** [comment]
> > 原因是递归slot.default时获取不到自定义组件内部的vnode，业务上可以先用ref循环应急一下 @eiinu 大佬看看有好的解决思路吗
> 
> ref循环怎么应急，请大佬明示
校验放入自定义组件内部，父级组件通过添加ref进行循环逻辑操作

**Comment by mikasayw** [comment]
> > 原因是递归slot.default时获取不到自定义组件内部的vnode，业务上可以先用ref循环应急一下 @eiinu 大佬看看有好的解决思路吗
> 
> ref循环怎么应急，请大佬明示

校验放入自定义组件内部，父级组件通过添加ref进行循环逻辑操作

**Comment by eiinu** [comment]
> 原因是递归slot.default时获取不到自定义组件内部的vnode，业务上可以先用ref循环应急一下 @eiinu 大佬看看有好的解决思路吗

递归的方式需要修改，不使用 slot 而是用 subTree
