### ISSUE TITLE
[bug]video的autoplay 属性在ios不生效

### ISSUE THREAD

**Issue by albgjws** [jdf2e/nutui#258]
## 问题描述

video的autoplay 属性在ios不生效

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
安卓生效，ios不行

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by vickyYE** [comment]
请提供下最小可复现代码，我为您排查下
