### ISSUE TITLE
list和swipe一起使用时，删除列表项会报错

### ISSUE THREAD

**Issue by Nemowxy** [jdf2e/nutui#2585]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.0.3

### 平台

h5

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IERvbmdkb25nIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcbiAgaW1wb3J0IHtyZWZ9IGZyb20gJ3Z1ZSc7XG5jb25zdCBzaG93ID0gKCkgPT4ge1xuICBzaG93VG9hc3QudGV4dCgnSGVsbG8sIE51dFVJIScpXG59O1xuICBjb25zdCB1c2VyTGlzdCA9IHJlZihbXG4gICAge1wiaWRcIjpcIjFcIixcIm5hbWVcIjpcIjFcIiwgXCJ0ZWxlcGhvbmVcIjpcIjEzOTk5OTk5OTlcIn0sXG4gICAgIHtcImlkXCI6XCIyXCIsXCJuYW1lXCI6XCIxXCIsIFwidGVsZXBob25lXCI6XCIxMzk5OTk5OTk5XCJ9LFxuICAgICB7XCJpZFwiOlwiM1wiLFwibmFtZVwiOlwiMVwiLCBcInRlbGVwaG9uZVwiOlwiMTM5OTk5OTk5OVwifVxuICBdKTtcbiAgXG4gIGNvbnN0IG9uRGVsZXRlID0gKGl0ZW0pPT57XG4gICAgdXNlckxpc3QudmFsdWUgPSB1c2VyTGlzdC52YWx1ZS5maWx0ZXIoKGl0KT0+aXRlbS5pZCA9PT0gaXQuaWQpO1xuICB9XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiA8bnV0LWxpc3Qgdi1pZj1cInVzZXJMaXN0Lmxlbmd0aCA+IDBcIiA6bGlzdERhdGE9XCJ1c2VyTGlzdFwiPlxuICAgICAgPHRlbXBsYXRlIHYtc2xvdD1cInsgaXRlbSwgaW5kZXggfVwiPlxuICAgICAgICA8bnV0LXN3aXBlPlxuICAgICAgICAgIDxkaXYgPlxuICAgICAgICAgICAgPGRpdiA+XG4gICAgICAgICAgICAgIDxkaXYgPnt7IGl0ZW0ubmFtZSB9fTwvZGl2PlxuICAgICAgICAgICAgICA8ZGl2ID57eyBpdGVtLnRlbGVwaG9uZX19PC9kaXY+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8dGVtcGxhdGUgI3JpZ2h0PlxuICAgICAgICAgICAgPGRpdiAgQGNsaWNrPVwib25EZWxldGUoaXRlbSlcIj5cbiAgICAgICAgICAgICAg5Yig6ZmkXG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L251dC1zd2lwZT5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9udXQtbGlzdD5cbjwvdGVtcGxhdGU+In0=

### 重现步骤

list和swipe组合展示，通过swipe删除listdata时会报错，如图
<img width="580" alt="image" src="https://github.com/jdf2e/nutui/assets/12393700/d2da6cc9-aae6-4f34-a06a-0438a3670f41">

### 期望的结果是什么？

正常删除

### 实际的结果是什么？

报错，无法正常使用

### 环境信息

环境无关，demo也能复现

**Comment by eiinu** [comment]
List 本身是虚拟列表，正常需求下并不需要使用到这种组件。而且该组件目前问题比较多，比如滑动白屏、距离计算不精确等等，可能会在某个版本废弃。
建议采用滚动加载（H5）或者 scroll-view（小程序）等组件替代

**Comment by Nemowxy** [comment]
> List 本身是虚拟列表，正常需求下并不需要使用到这种组件。而且该组件目前问题比较多，比如滑动白屏、距离计算不精确等等，可能会在某个版本废弃。 建议采用滚动加载（H5）或者 scroll-view（小程序）等组件替代

滚动加载在和swipe组合时也有一些问题，我再尝试看看

**Comment by eiinu** [comment]
> > List 本身是虚拟列表，正常需求下并不需要使用到这种组件。而且该组件目前问题比较多，比如滑动白屏、距离计算不精确等等，可能会在某个版本废弃。 建议采用滚动加载（H5）或者 scroll-view（小程序）等组件替代
> 
> 滚动加载在和swipe组合时也有一些问题，我再尝试看看

swipe 在 4.1.0 进行了重构，可以尝试升级到最新的版本
