### ISSUE TITLE
[FR]: calendar组件设置了日期范围之后，无法定位到今天的位置，打开组件显示的是start-date的那个日期

### ISSUE THREAD

**Issue by Xhyen** [jdf2e/nutui#2595]
### 这个功能解决了什么问题？

期望增加或者默认设置成设置了区间之后，定位为今天的日期位置

### 你期望的组件设计是怎样的？

期望增加或者默认设置成设置了区间之后，定位为今天的日期位置

**Comment by yi-boide** [comment]
props有个default-value字段，你设置为今天的日期即可定位到当天

> ### 这个功能解决了什么问题？
> 期望增加或者默认设置成设置了区间之后，定位为今天的日期位置
> 
> ### 你期望的组件设计是怎样的？
> 期望增加或者默认设置成设置了区间之后，定位为今天的日期位置

**Comment by daiwanxing** [comment]
目前可行的解决办法，当日历面板打开的时候手动定位今天的日期

```js
calendarRef.value.scrollToDate(dayjs().format("YYYY-MM-DD"));
```

**Comment by yh927** [comment]
calendarRef.value.scrollToDate这个在使用时候会报cssScrollHeight的错误，应该是还没加载到最新日期的dom，所以不好用
