### ISSUE TITLE
[FR]: 希望增加调色板功能

### ISSUE THREAD

**Issue by tanxiaomm** [jdf2e/nutui#2596]
### 这个功能解决了什么问题？

希望能够支持调色板的功能，方便选取颜色。

### 你期望的组件设计是怎样的？

快捷的选择颜色代码插入。

**Comment by yi-boide** [comment]
h5的input输入框本身支持调色板，input的type设置为color即可，小程序的input本身不支持

**Comment by 490626721** [comment]
🧐目前我的项目也需要颜色拾取组件
