### ISSUE TITLE
在使用tabs时，如果nut-tab-pane有多个时，在非第一个nut-tab-pane中使用dialog,popover，popup组件时，都会在第一个tabpanel中弹出，导致后面其它页面无法使用到组件

### ISSUE THREAD

**Issue by Mystuddent** [jdf2e/nutui#2605]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.1.7

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LXRhYnMgdi1tb2RlbD1cInZhbHVlXCI+XG4gICAgPG51dC10YWItcGFuZSB0aXRsZT1cIlRhYiAxXCIgcGFuZS1rZXk9XCIwXCI+IFRhYiAxIDwvbnV0LXRhYi1wYW5lPlxuICAgIDxudXQtdGFiLXBhbmUgdGl0bGU9XCJUYWIgMlwiIHBhbmUta2V5PVwiMVwiPlxuICAgICAgPHZpZXcgc3R5bGU9XCJtYXJnaW4tYm90dG9tOiAxMHB4XCI+XG4gICAgICAgIDxudXQtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgc2hhcGU9XCJzcXVhcmVcIiBAY2xpY2s9XCJ2aXNpYmxlMSA9IHRydWVcIlxuICAgICAgICAgID5kaWFsb2flsZXnpLo8L251dC1idXR0b25cbiAgICAgICAgPlxuICAgICAgPC92aWV3PlxuICAgICAgPG51dC1wb3BvdmVyXG4gICAgICAgIHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGUubGlnaHRUaGVtZVwiXG4gICAgICAgIDpsaXN0PVwiaWNvbkl0ZW1MaXN0XCJcbiAgICAgICAgbG9jYXRpb249XCJib3R0b20tc3RhcnRcIlxuICAgICAgPlxuICAgICAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgICAgICA8bnV0LWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIHNoYXBlPVwic3F1YXJlXCI+cG9wb3ZlcuWxleekujwvbnV0LWJ1dHRvbj5cbiAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDwvbnV0LXBvcG92ZXI+XG5cbiAgICAgIDxudXQtZGlhbG9nXG4gICAgICAgIHRpdGxlPVwi5Z+656GA5by55qGGXCJcbiAgICAgICAgY29udGVudD1cIui/meaYr+WfuuehgOW8ueahhuOAglwiXG4gICAgICAgIHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGUxXCJcbiAgICAgIC8+XG4gICAgPC9udXQtdGFiLXBhbmU+XG4gICAgPG51dC10YWItcGFuZSB0aXRsZT1cIlRhYiAzXCIgcGFuZS1rZXk9XCIyXCI+IFRhYiAzIDwvbnV0LXRhYi1wYW5lPlxuICA8L251dC10YWJzPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIjtcbmNvbnN0IHZhbHVlID0gcmVmKFwiMFwiKTtcbmNvbnN0IHZpc2libGUxID0gcmVmKGZhbHNlKTtcbmNvbnN0IHZpc2libGUgPSByZWYoe1xuICBkYXJrVGhlbWU6IGZhbHNlLFxuICBsaWdodFRoZW1lOiBmYWxzZSxcbn0pO1xuY29uc3QgaWNvbkl0ZW1MaXN0ID0gW1xuICB7IG5hbWU6IFwi6YCJ6aG55LiAXCIgfSxcbiAgeyBuYW1lOiBcIumAiemhueS6jFwiIH0sXG4gIHsgbmFtZTogXCLpgInpobnkuIlcIiB9LFxuXTtcbjwvc2NyaXB0PlxuIn0=

### 重现步骤

文字以及布局在第二个页面中
![image](https://github.com/jdf2e/nutui/assets/24928560/0ea2754f-d32e-4098-98cd-356b0855ea66)
点击后展示到第一个页面去了
![image](https://github.com/jdf2e/nutui/assets/24928560/f1d739a5-1d86-488b-b900-ce8385ee780d)
是使用的问题吗？以下是我写的示例代码：

> <nut-tabs v-model="value">
    <nut-tab-pane title="Tab 1" pane-key="0"> Tab 1 </nut-tab-pane>
    <nut-tab-pane title="Tab 2" pane-key="1">
      <view style="margin-bottom: 10px">
        <nut-button type="primary" shape="square" @click="visible1 = true"
          >dialog展示</nut-button
        >
      </view>
      <nut-popover
        v-model:visible="visible.lightTheme"
        :list="iconItemList"
        location="bottom-start"
      >
        <template #reference>
          <nut-button type="primary" shape="square">popover展示</nut-button>
        </template>
      </nut-popover>

      <nut-dialog
        title="基础弹框"
        content="这是基础弹框。"
        v-model:visible="visible1"
      />
    </nut-tab-pane>
    <nut-tab-pane title="Tab 3" pane-key="2"> Tab 3 </nut-tab-pane>
  </nut-tabs>

### 期望的结果是什么？

能在其它nut-tab-pane页面正确展示所使用的组件

### 实际的结果是什么？

在非第一个nut-tab-pane中使用dialog,popover，popup组件时，都会在第一个tabpanel中弹出，导致后面其它页面无法使用到组件

### 环境信息

@nutui/nutui-taro
Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\easygoo\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD

@nutui/nutui
  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.07 GB / 15.84 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.3570.0
    Internet Explorer: 11.0.19041.3570

### 其他补充信息

Node.js v16.17.0

**Comment by eiinu** [comment]
原因：
transform 元素（指 tabs）的内部使用了 fixed 定位元素（指dialog）时，实际的定位参考目标元素会被改变。

解决方法1：
将 tabs 的动画时长属性设置为 0，这样 tabs 就不再是 transform 布局。

解决方法2：
将 dialog 挪到 tabs 外面。

**Comment by Mystuddent** [comment]
> 原因： transform元素（指tabs）的内部使用了固定定位元素（指dialog）时，实际的定位参考目标元素会被改变。
> 
> 解决方法1： 将tabs的动画时长属性设置为0，这样tabs就不再是transform布局。
> 
> 解决方法2： 将对话框挪到标签页外面。

谢谢回复，经测试解决了问题。

**Comment by asu-git** [comment]
同样遇到了这个问题，怎么点按钮popover都不显示，设置动画时间为0了也没用
