### ISSUE TITLE
[bug]在部分安卓手机上关闭dialog的时候会有滚动异常

### ISSUE THREAD

**Issue by reidsu** [jdf2e/nutui#261]
使用了lockBgScroll属性后，在部分安卓手机上关闭dialog的时，会出现先滚动到最顶部，随后滚动到关闭dialog的位置。
  机型：部分华为原生浏览器、uc浏览器。

**Comment by guoxiao158** [comment]
因为使用了 lockBgScroll  实际在全局加 fix定位，导致的fix兼容性问题，如果要使用该场景，推荐以下pop组件
