### ISSUE TITLE
[bug] swiper的销毁钩子内计时器清空无效

### ISSUE THREAD

**Issue by wangjun521** [jdf2e/nutui#262]
## 问题描述
swiper 源码在销毁钩子内将计时器单单置为 null 是无用的 并不能清空掉计时器

## 预期的行为和实际行为
单页面应用  在销毁钩子以及 keepAlive 时的停用钩子里都需要 clear掉 计时器

**Comment by richard1015** [comment]
好的，我这边跟进一下
