### ISSUE TITLE
小红书小程序input的maxlength无效

### ISSUE THREAD

**Issue by a13837811459** [jdf2e/nutui#2630]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.1.6

### 平台

其他小程序

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IERvbmdkb25nIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcbmNvbnN0IHNob3cgPSAoKSA9PiB7XG4gIHNob3dUb2FzdC50ZXh0KCdIZWxsbywgTnV0VUkhJylcbn07XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC1jZWxsIHRpdGxlPVwiQ2xpY2sgdG8gc2hvdyBUb2FzdFwiIGlzLWxpbmsgQGNsaWNrPVwic2hvd1wiPlxuICAgIDxudXQtaW5wdXQgOm1heC1sZW5ndGg9XCI1XCIgLz5cbiAgPC9udXQtY2VsbD5cbjwvdGVtcGxhdGU+In0=

### 重现步骤

1. 编译成小红书小程序
2. 设置input的max-length属性

### 期望的结果是什么？

max-length无效

### 实际的结果是什么？

max-length有效

### 环境信息

  Taro CLI 3.4.14 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.17.0 - C:\Program Files\nodejs\npm.CMD

### 其他补充信息

[小红书小程序input](https://miniapp.xiaohongshu.com/docs?path=/docs/component/input)的maxlength属性名为max-length，而组件中使用的是maxlength

**Comment by eiinu** [comment]
NutUI 内使用的是 Taro 框架的 Input 组件，对外暴露的 API 为 maxlength。
它与实际小程序平台存在的差异会由 Taro 抹平，建议升级到 Taro 更高的版本测试。如果仍有问题，可以在 [Taro](https://github.com/NervJS/taro/issues) 仓库反馈
