### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by szz19960815** [jdf2e/nutui#264]
nutbutton在chrome浏览器上windows和mac下均正常，但是在iphone下不管用什么浏览器都会出现按钮跑到右上角，当全局使用了position：static以后又丢失按钮高度，经测试发现当shape为circle时出现

**Comment by richard1015** [comment]
是否可以提供一个  可复现仓库

**Comment by szz19960815** [comment]
抱歉因为不是公司项目所以可能暂时没有办法提供复现仓库

**Comment by szz19960815** [comment]
抱歉因为不是公司项目所以可能暂时没有办法提供复现仓库

**Comment by richard1015** [comment]
最小复现仓库呢，不包含公司代码
