### ISSUE TITLE
滚动插件清楚延时[question]

### ISSUE THREAD

**Issue by ghostNv** [jdf2e/nutui#265]
loadMoreVert() {
            this.isLoading1 = true;
            if (this.page1 > this.maxPages) {
                this.isUnMore1 = true;
                this.isLoading1 = false;
            } else {
                clearTimeout(this.timers);
                this.timer = setTimeout(() => {
                    this.isLoading1 = false;
                    this.isUnMore1 = false;
                    this.listData1 = new Array(20 * this.page1);
                    this.page1 = ++this.page1;
                }, 300);
            }
        },
这里的timers跟timer是写错了，还是就是2个变量，但是没有找到timers这个变量

**Comment by richard1015** [comment]
收到，感谢反馈

**Comment by irisSong** [comment]
抱歉，demo写错了，下次发版会更正，感谢反馈
