### ISSUE TITLE
[bug] TabBar 中的 curr 起不到默认选中的功能 

### ISSUE THREAD

**Issue by qingshubing** [jdf2e/nutui#266]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
![image](https://user-images.githubusercontent.com/31761155/83225110-989e0e80-a1b1-11ea-9637-6322cfc1a0bb.png)

## 复现步骤，具体代码
源码中好像没有使用到   版本 "@nutui/nutui": "^2.2.4",
![image](https://user-images.githubusercontent.com/31761155/83225228-def36d80-a1b1-11ea-9145-26aa7b8c30d7.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： "@nutui/nutui": "^2.2.4",
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by zjyau** [comment]
哈，这个已经处理 #268

**Comment by zhenyulei** [comment]
感谢反馈问题 以及在代码库中修复 之后上线后 更新

**Comment by qingshubing** [comment]
ok
