### ISSUE TITLE
image-preview组件一次性展示除了四张图片,,并且页面不断打印错误日志:

### ISSUE THREAD

**Issue by 15603871022** [jdf2e/nutui#2660]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

3.2.6

### 平台

h5

### 重现链接

https://9zq6ml-3000.csb.app/

### 重现步骤

正常像案例点击即可实现

### 期望的结果是什么？

页面不卡死,正常显示一张一张的图片,而不是一次展示四张

### 实际的结果是什么？

一次性展示了四张拼接后的图片 并且页面卡死

**Comment by eiinu** [comment]
NutUI Vue v3 最新的版本号为 3.3.8，可以升级测试下效果。

**Comment by 15603871022** [comment]
升级了最新版本也不行,&nbsp;image-preview组件只要绑定了ref变量形式的boolean值,就会卡死




牛宏扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jdf2e/nutui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月16日(星期四) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jdf2e/nutui] image-preview组件一次性展示除了四张图片,,并且页面不断打印错误日志: (Issue #2660)





 
NutUI Vue v3 最新的版本号为 3.3.8，可以升级测试下效果。

**Comment by 15603871022** [comment]
后来我发现在全局引入时 必须使用nut-imagepreview标签,此时能正常使用. 
但是当我不全局引入,单独引入时, 按照你们官网的 引入方式 import { ImagePreview, Overlay, Popup, Swiper, SwiperItem } from ***@***.***/nutui';
然后使用image-preview标签时,就会出现之前的问题.不知道为什么会这样,难道imagepreview强制全局引入么


牛宏扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jdf2e/nutui" ***@***.***&gt;;
发送时间:&nbsp;2023年11月16日(星期四) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jdf2e/nutui] image-preview组件一次性展示除了四张图片,,并且页面不断打印错误日志: (Issue #2660)






NutUI Vue v3 最新的版本号为 3.3.8，可以升级测试下效果。

—
Reply to this email directly,&nbsp;view it on GitHub, or&nbsp;unsubscribe.
You are receiving this because you authored the thread.






牛宏扬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jdf2e/nutui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月16日(星期四) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jdf2e/nutui] image-preview组件一次性展示除了四张图片,,并且页面不断打印错误日志: (Issue #2660)





 
NutUI Vue v3 最新的版本号为 3.3.8，可以升级测试下效果。

**Comment by eiinu** [comment]
> 后来我发现在全局引入时 必须使用nut-imagepreview标签,此时能正常使用. 
> 但是当我不全局引入,单独引入时, 按照你们官网的 引入方式 import { ImagePreview, Overlay, Popup, Swiper, SwiperItem } from ***@***.***/nutui';
> 然后使用image-preview标签时,就会出现之前的问题.不知道为什么会这样,难道imagepreview强制全局引入么

单独注册与全部注册最终的效果应该是一样的，怀疑是在单独注册时漏掉了某个子组件，或者其样式没有成功引入。
建议提供可复现的代码用于排查问题。
