### ISSUE TITLE
nut-popup里如果又输入框（nut-input）在小程序端页面上推会出现css混乱

### ISSUE THREAD

**Issue by myby7000p** [jdf2e/nutui#2672]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.2.1

### 平台

weapp

### 重现链接

https://gitee.com/shitou158/nut-ui-test

### 重现步骤

在页面写一个nut-popup，设置为true，然后往nut-popup里写nut-input组件（nut-input一定到超过一屏,否则弹起来的手机键盘不会挡住输入框，也就不会上推页面了）

### 期望的结果是什么？

nut-popup里面的nut-input组件能够正常的上推页面`

### 实际的结果是什么？

nut-popup里面的nut-input组件没正常的上推页面，并且还和其他组件重叠了
![70cc15607c616e4cbf785b47d7c1fe7](https://github.com/jdf2e/nutui/assets/88788426/a436708b-2b85-4a76-8820-1166d2eda7e9)
![779164903b8d4d3bde00304abf0d162](https://github.com/jdf2e/nutui/assets/88788426/b4200496-f911-4f58-a833-096851e84359)

### 环境信息

 "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@nutui/icons-vue-taro": "^0.0.9",
    "@nutui/nutui-taro": "^4.2.1",
    "@tarojs/components": "3.6.15",
    "@tarojs/helper": "3.6.15",
    "@tarojs/plugin-framework-vue3": "3.6.15",
    "@tarojs/plugin-html": "^3.6.15",
    "@tarojs/plugin-platform-alipay": "3.6.15",
    "@tarojs/plugin-platform-h5": "3.6.15",
    "@tarojs/plugin-platform-jd": "3.6.15",
    "@tarojs/plugin-platform-qq": "3.6.15",
    "@tarojs/plugin-platform-swan": "3.6.15",
    "@tarojs/plugin-platform-tt": "3.6.15",
    "@tarojs/plugin-platform-weapp": "3.6.15",
    "@tarojs/runtime": "3.6.15",
    "@tarojs/shared": "3.6.15",
    "@tarojs/taro": "3.6.15",
    "vue": "^3.2.40"
  },

**Comment by eiinu** [comment]
测试了安卓设备没有复现。
输入框底部与键盘的距离可以通过 cursorSpacing 属性控制，默认值为 0，参考 https://taro-docs.jd.com/docs/components/forms/input#inputprops
