### ISSUE TITLE
typescript中，form表单的ref类型问题

### ISSUE THREAD

**Issue by zolinzone** [jdf2e/nutui#2677]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.2.0

### 平台

h5

### 重现链接

无

### 重现步骤

`<template>
  <section class="main">
    <nut-avatar size="40" bg-color="#effafa">
      <img src="logo.png"/>
    </nut-avatar>
    <h1 class="main-title">登录</h1>
    <nut-form :rules="rules" :model-value="formData" ref="formRef">
      <nut-form-item label="账号" prop="account">
        <nut-input v-model="formData.account" placeholder="请输入账号" clearable :border="false" />
      </nut-form-item>
      <nut-form-item label="密码" prop="password">
        <nut-input v-model="formData.password" type="password" placeholder="请输入密码" clearable :border="false" />
      </nut-form-item>
    </nut-form>
    <nut-button type="primary" shape="square" block @click="submit">登录</nut-button>
  </section>
</template>
<route lang="yaml">
  path: /
</route>
<script setup lang="ts">
const formRef = ref(null);
const formData = reactive({
  account: '',
  password: ''
});

const rules = { 
  account: [
    { required: true, message: '请输入账号'},
  ],
  password: [
    { required: true, message: '请输入密码'},
  ]
};

const submit = () => {
  // @ts-ignore
  formRef.value.validate().then(({ valid, errors }) => {
    if (valid) {
      console.log('success');
    } else {
      console.log('error', errors);
    }
  })
}

</script>`

我在form表单上绑定了ref变量formRef，声明变量时，应该传入其泛型，以便调用其validate等方法时不会报错，我尝试从@nutui/nutui中寻找导出的form表单类型，但是并没有找到，此组件库是否不提供类型的导出

### 期望的结果是什么？

通过泛型处理form表单的类型，而不是使用 // @ts-ignore忽略typescript的报错

### 实际的结果是什么？

使用 // @ts-ignore忽略typescript的报错

### 其他补充信息

{
  "name": "manager",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@nutui/nutui": "^4.2.0",
    "amfe-flexible": "^2.2.1",
    "vue": "^3.3.4"
  },
  "devDependencies": {
    "@types/node": "^20.8.9",
    "@types/postcss-pxtorem": "^6.0.2",
    "@vitejs/plugin-vue": "^4.2.3",
    "postcss": "^8.4.31",
    "postcss-pxtorem": "^6.0.0",
    "typescript": "^5.0.2",
    "unplugin-auto-import": "^0.16.7",
    "unplugin-vue-components": "^0.25.2",
    "vite": "^4.4.5",
    "vite-plugin-pages": "^0.31.0",
    "vite-plugin-vue-layouts": "^0.8.0",
    "vue-tsc": "^1.8.5"
  }
}

**Comment by ntnyq** [comment]
可以通过 `InstanceType` 获取组件类型，不过组件库提供导出更方便点。

```vue
<template>
  <nut-form ref="formRef">
    <nut-button @click="handleSubmit">提交</nut-button>
  </nut-form>
</template>

<script lang="ts" setup>
import { Form } from '@nutui/nutui-taro'

type FormInstance = InstanceType<typeof Form>

const formRef = ref<FormInstance>()

const handleSubmit = async () => {
  try {
    await formRef.value?.validate()  
  } catch (err) {
    console.log(err)
  }
}
</script>
```

**Comment by eiinu** [comment]
在目前的组件库构建方式下，没有能力扩展出新的类型导出字段。
最近在测试对这部分逻辑的改造方案。
