### ISSUE TITLE
自定义主题，报错[question]

### ISSUE THREAD

**Issue by FENGHUIQING** [jdf2e/nutui#269]
![image](https://user-images.githubusercontent.com/10751077/83398396-dad58300-a431-11ea-95cb-f473f9aaa350.png)

**Comment by FENGHUIQING** [comment]
Module build failed:
$assetsPath:'./assets/';
                                                                                     ^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in E:\songyan\leader-web-mobile\node_modules\@nutui\nutui\dist\nutui.scss (line 1, column 87)    

 @ ./src/main.js 12:0-38
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js

**Comment by richard1015** [comment]
请参考demo库

https://github.com/jdf2e/nutui-demo
