### ISSUE TITLE
请问怎么设置局域网可访问呢？

### ISSUE THREAD

**Issue by mrxu0** [jdf2e/nutui#27]
使用 npm run dev 启动项目之后只能够本地访问，这样手机调试的时候会比较麻烦，如何能够让属于同一个局域网的用户可访问呢？

**Comment by Franslee** [comment]
手机和电脑处于同一局域网内的话，是可以访问的

**Comment by mrxu0** [comment]
> 手机和电脑处于同一局域网内的话，是可以访问的

你好，我用本机IP地址直接访问时访问不了的。

**Comment by Franslee** [comment]
可改一下webpack配置中devserver的配置，指定host为本机ip
https://www.webpackjs.com/configuration/dev-server/#devserver-host
