### ISSUE TITLE
[question]2.2.5版本的tab组件，没有了contentShow的控制变量

### ISSUE THREAD

**Issue by alennx** [jdf2e/nutui#270]
2.2.5版本的tab组件没有考虑向下兼容吗？2.2.1前tab的contentShow没有了，后面会修复还是以后都会去掉，官网的api文档还有这个参数
![image](https://user-images.githubusercontent.com/13479374/83522531-607d2f80-a513-11ea-824d-72417829d1ec.png)

**Comment by zhenyulei** [comment]
因为contentShow控制的是tab页签下面的区域是否展示，如果不展示请使用 tabbar组件，之后的版本也会在tab中删除这个属性  tab文档后续也会删除该属性
