### ISSUE TITLE
[FR]: countdown组件，在自定义展示样式里不能显示毫秒

### ISSUE THREAD

**Issue by JasirVoriya** [jdf2e/nutui#2700]
### NutUI 包名

@nutui/nutui

### 这个功能解决了什么问题？

countdown在format 格式下，可以支持显示到毫秒，可是在自定义展示样式里，无法显示到毫秒：
```
<script setup lang="ts">
const end = ref(Date.now() + 60 * 60 * 1000);
const resetTime = ref({
  d: '0',
  h: '00',
  m: '00',
  s: '00',
});
</script>
<template>
  <nut-countdown v-model="resetTime" :end-time="end" millisecond format="HH:mm:ss:SS">
    <span class=" text-sm">
      距离结束还剩：
      <span class=" text-red-600 text-2xl">{{ resetTime.d }}</span>天
      <span class=" text-red-600 text-2xl">{{ resetTime.h }}</span>时
      <span class=" text-red-600 text-2xl">{{ resetTime.m }}</span>分
      <span class=" text-red-600 text-2xl">{{ resetTime.s }}</span>秒
    </span>
  </nut-countdown>
</template>
```
如上，只能显示到秒，官方文档也没有讲如何显示毫秒

### 你期望的组件设计是怎样的？

能够在自定义样式里面，显示毫秒

**Comment by eiinu** [comment]
参考 [NutUI Playground](https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LWNlbGw+XG4gICAgPG51dC1jb3VudGRvd24gdi1tb2RlbD1cInJlc2V0VGltZVwiIDplbmQtdGltZT1cImVuZFwiPlxuICAgICAgPGRpdiBjbGFzcz1cImNvdW50ZG93bi1wYXJ0LWJveFwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPnt7IHJlc2V0VGltZS5kIH195aSpPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gaFwiPnt7IHJlc2V0VGltZS5oIH19PC9kaXY+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPjo8L3NwYW4+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gbVwiPnt7IHJlc2V0VGltZS5tIH19PC9kaXY+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPjo8L3NwYW4+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gc1wiPnt7IHJlc2V0VGltZS5zIH19PC9kaXY+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPjo8L3NwYW4+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gc1wiPnt7IHJlc2V0VGltZS5tcyB9fTwvZGl2PlxuICAgICAgPC9kaXY+XG4gICAgPC9udXQtY291bnRkb3duPlxuICA8L251dC1jZWxsPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnO1xuY29uc3QgZW5kID0gcmVmKERhdGUubm93KCkgKyA2MCAqIDEwMDApO1xuY29uc3QgcmVzZXRUaW1lID0gcmVmKHtcbiAgZDogJzEnLFxuICBoOiAnMDAnLFxuICBtOiAnMDAnLFxuICBzOiAnMDAnLFxuICBtczogJzAwJ1xufSk7XG48L3NjcmlwdD5cbjxzdHlsZT5cbi5jb3VudGRvd24tcGFydC1ib3gge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLnBhcnQtaXRlbSB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICB3aWR0aDogNTBweDtcbiAgYmFja2dyb3VuZDogI2U4MjIwZTtcbiAgY29sb3I6ICNmZmY7XG4gIGZvbnQtc2l6ZTogMTRweDtcbiAgYm9yZGVyLXJhZGl1czogNnB4O1xufVxuXG4ucGFydC1pdGVtLXN5bWJvbCB7XG4gIG1hcmdpbjogMCA1cHg7XG59XG48L3N0eWxlPlxuIn0=)
下次发版会把毫秒加到文档演示代码中

**Comment by JasirVoriya** [comment]
> 参考 [NutUI Playground](https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LWNlbGw+XG4gICAgPG51dC1jb3VudGRvd24gdi1tb2RlbD1cInJlc2V0VGltZVwiIDplbmQtdGltZT1cImVuZFwiPlxuICAgICAgPGRpdiBjbGFzcz1cImNvdW50ZG93bi1wYXJ0LWJveFwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPnt7IHJlc2V0VGltZS5kIH195aSpPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gaFwiPnt7IHJlc2V0VGltZS5oIH19PC9kaXY+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPjo8L3NwYW4+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gbVwiPnt7IHJlc2V0VGltZS5tIH19PC9kaXY+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPjo8L3NwYW4+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gc1wiPnt7IHJlc2V0VGltZS5zIH19PC9kaXY+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPjo8L3NwYW4+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gc1wiPnt7IHJlc2V0VGltZS5tcyB9fTwvZGl2PlxuICAgICAgPC9kaXY+XG4gICAgPC9udXQtY291bnRkb3duPlxuICA8L251dC1jZWxsPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnO1xuY29uc3QgZW5kID0gcmVmKERhdGUubm93KCkgKyA2MCAqIDEwMDApO1xuY29uc3QgcmVzZXRUaW1lID0gcmVmKHtcbiAgZDogJzEnLFxuICBoOiAnMDAnLFxuICBtOiAnMDAnLFxuICBzOiAnMDAnLFxuICBtczogJzAwJ1xufSk7XG48L3NjcmlwdD5cbjxzdHlsZT5cbi5jb3VudGRvd24tcGFydC1ib3gge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLnBhcnQtaXRlbSB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICB3aWR0aDogNTBweDtcbiAgYmFja2dyb3VuZDogI2U4MjIwZTtcbiAgY29sb3I6ICNmZmY7XG4gIGZvbnQtc2l6ZTogMTRweDtcbiAgYm9yZGVyLXJhZGl1czogNnB4O1xufVxuXG4ucGFydC1pdGVtLXN5bWJvbCB7XG4gIG1hcmdpbjogMCA1cHg7XG59XG48L3N0eWxlPlxuIn0=) 下次发版会把毫秒加到文档演示代码中

请问支持只显示1位毫秒嘛

**Comment by eiinu** [comment]
> > 参考 [NutUI Playground](https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LWNlbGw+XG4gICAgPG51dC1jb3VudGRvd24gdi1tb2RlbD1cInJlc2V0VGltZVwiIDplbmQtdGltZT1cImVuZFwiPlxuICAgICAgPGRpdiBjbGFzcz1cImNvdW50ZG93bi1wYXJ0LWJveFwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPnt7IHJlc2V0VGltZS5kIH195aSpPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gaFwiPnt7IHJlc2V0VGltZS5oIH19PC9kaXY+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPjo8L3NwYW4+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gbVwiPnt7IHJlc2V0VGltZS5tIH19PC9kaXY+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPjo8L3NwYW4+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gc1wiPnt7IHJlc2V0VGltZS5zIH19PC9kaXY+XG4gICAgICAgIDxzcGFuIGNsYXNzPVwicGFydC1pdGVtLXN5bWJvbFwiPjo8L3NwYW4+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYXJ0LWl0ZW0gc1wiPnt7IHJlc2V0VGltZS5tcyB9fTwvZGl2PlxuICAgICAgPC9kaXY+XG4gICAgPC9udXQtY291bnRkb3duPlxuICA8L251dC1jZWxsPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnO1xuY29uc3QgZW5kID0gcmVmKERhdGUubm93KCkgKyA2MCAqIDEwMDApO1xuY29uc3QgcmVzZXRUaW1lID0gcmVmKHtcbiAgZDogJzEnLFxuICBoOiAnMDAnLFxuICBtOiAnMDAnLFxuICBzOiAnMDAnLFxuICBtczogJzAwJ1xufSk7XG48L3NjcmlwdD5cbjxzdHlsZT5cbi5jb3VudGRvd24tcGFydC1ib3gge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLnBhcnQtaXRlbSB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICB3aWR0aDogNTBweDtcbiAgYmFja2dyb3VuZDogI2U4MjIwZTtcbiAgY29sb3I6ICNmZmY7XG4gIGZvbnQtc2l6ZTogMTRweDtcbiAgYm9yZGVyLXJhZGl1czogNnB4O1xufVxuXG4ucGFydC1pdGVtLXN5bWJvbCB7XG4gIG1hcmdpbjogMCA1cHg7XG59XG48L3N0eWxlPlxuIn0=) 下次发版会把毫秒加到文档演示代码中
> 
> 请问支持只显示1位毫秒嘛

可以自行对毫秒的原始数据进行格式化展示
