### ISSUE TITLE
webstorm 开发， 一写代码输入内容，cpu就上涨到50%，连续输入能到100%，我cpu是13700k

### ISSUE THREAD

**Issue by houxianyj** [jdf2e/nutui#2722]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.0

### 平台

weapp

### 重现链接

https://github.com/houxianyj/myApp.git

### 重现步骤

src/pages/index/index.vue  文件里连续输入字符

### 期望的结果是什么？

cpu使用率应该在合理的范围

### 实际的结果是什么？

cpu占用到100%

### 环境信息

👽 Taro v3.6.20

  Taro CLI 3.6.20 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.9.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.7.2 - D:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.20 => 3.6.20
      @tarojs/components: 3.6.20 => 3.6.20
      @tarojs/helper: 3.6.20 => 3.6.20
      @tarojs/plugin-framework-vue3: 3.6.20 => 3.6.20
      @tarojs/plugin-html: 3.6.20 => 3.6.20
      @tarojs/plugin-platform-alipay: 3.6.20 => 3.6.20
      @tarojs/plugin-platform-h5: 3.6.20 => 3.6.20
      @tarojs/plugin-platform-jd: 3.6.20 => 3.6.20
      @tarojs/plugin-platform-qq: 3.6.20 => 3.6.20
      @tarojs/plugin-platform-swan: 3.6.20 => 3.6.20
      @tarojs/plugin-platform-tt: 3.6.20 => 3.6.20
      @tarojs/plugin-platform-weapp: 3.6.20 => 3.6.20
      @tarojs/runtime: 3.6.20 => 3.6.20
      @tarojs/shared: 3.6.20 => 3.6.20
      @tarojs/taro: 3.6.20 => 3.6.20
      @tarojs/taro-loader: 3.6.20 => 3.6.20
      @tarojs/webpack5-runner: 3.6.20 => 3.6.20
      babel-preset-taro: 3.6.20 => 3.6.20
      eslint-config-taro: 3.6.20 => 3.6.20

**Comment by eiinu** [comment]
这和组件库没有关系，建议去找开发框架反馈。
