### ISSUE TITLE
nut-navbar 左侧按钮的颜色参数

### ISSUE THREAD

**Issue by lixiuwen** [jdf2e/nutui#2758]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.2.0

### 平台

h5

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IERvbmdkb25nIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcbmNvbnN0IHNob3cgPSAoKSA9PiB7XG4gIHNob3dUb2FzdC50ZXh0KCdIZWxsbywgTnV0VUkhJylcbn07XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC1uYXZiYXIgbGVmdC1zaG93IEBjbGljay1iYWNrPVwib25DbGlja1wiIHRpdGxlPVwi5qCH6aKYXCIgZml4ZWQgIEBjbGljay1yaWdodD1cIm9uQ2xpY2tcIj5cbjwvbnV0LW5hdmJhcj5cbjwvdGVtcGxhdGU+In0=

### 重现步骤

nut-navbar，使用left-show ，默认的返回按钮的颜色无法自己修改，或者通过主题变量修改，只能使用自定义插槽修改

### 期望的结果是什么？

期望能通过主题变量修改或者其它的方式调整

### 实际的结果是什么？

无法自己修改

**Comment by eiinu** [comment]
[playground](https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IExlZnQgfSBmcm9tICdAbnV0dWkvaWNvbnMtdnVlJ1xuY29uc3Qgc2hvdyA9ICgpID0+IHtcbiAgc2hvd1RvYXN0LnRleHQoJ0hlbGxvLCBOdXRVSSEnKVxufTtcbjwvc2NyaXB0PlxuPHRlbXBsYXRlPlxuICA8bnV0LW5hdmJhciB0aXRsZT1cIuagh+mimFwiPlxuICAgIDx0ZW1wbGF0ZSAjbGVmdD5cbiAgICBcdDxMZWZ0IEBjbGljaz1cInNob3dcIiBjb2xvcj1cImJsdWVcIiAvPlxuICAgIDwvdGVtcGxhdGU+XG48L251dC1uYXZiYXI+XG48L3RlbXBsYXRlPiJ9)

通过 left 插槽就可以实现，而且更加灵活，也不再需要使用 `left-show` 或者 `click-back` 事件

```vue
<script setup lang="ts">
import { showToast } from '@nutui/nutui'
import { Left } from '@nutui/icons-vue'
const show = () => {
  showToast.text('Hello, NutUI!')
};
</script>
<template>
  <nut-navbar title="标题">
    <template #left>
    	<Left @click="show" color="blue" />
    </template>
</nut-navbar>
</template>
```
