### ISSUE TITLE
使用 nut-textarea 会报错[Vue warn]  Failed to resolve component: rich-text

### ISSUE THREAD

**Issue by wy1037** [jdf2e/nutui#2759]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.2.3

### 平台

weapp

### 重现链接

无

### 重现步骤

只要使用了此版本的
  <nut-textarea           
            placeholder="请输入其他信息"
          >
          </nut-textarea>

就会报：
VM1632 vendors.js:106 [Vue warn]: Failed to resolve component: rich-text
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

### 期望的结果是什么？

不报 [Vue warn]

### 实际的结果是什么？

1

### 环境信息

2

### 其他补充信息

2

**Comment by eiinu** [comment]
`v4.2.4` 已移除 textarea 内部使用的 rich-text
