### ISSUE TITLE
[suggest] 整一个PullRefresh下拉刷新组件

### ISSUE THREAD

**Issue by jokingzhang** [jdf2e/nutui#276]
## 你建议我们做什么？

现在...
没有PullRefresh下拉刷新组件
如果你能...
整一个PullRefresh下拉刷新组件
它将使...
下拉刷新更加方便
## 其它

无

**Comment by richard1015** [comment]
目前正处开发中，敬请期待

**Comment by richard1015** [comment]
https://nutui.jd.com/jdl/#/scroll 已发布可以使用，有问题欢迎反馈，谢谢

**Comment by JakeWoki** [comment]
希望在taro分支也加上下拉刷新，上拉加载更多组件
