### ISSUE TITLE
icon 组件全量引入的问题

### ISSUE THREAD

**Issue by tiny-dust** [jdf2e/nutui#2769]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.2.3

### 平台

weapp

### 重现链接

https://gitee.com/shun_shun_zhou/nutui-icon

### 重现步骤

- 克隆仓库  安装依赖
- dev 或者 build 项目
- 自动启动包分析页面
- 选择 page/index/index
- 勾选 Show content of concatenated modules (inaccurate)

### 期望的结果是什么？

只将使用的 icon打包进去

### 实际的结果是什么？

全量打包进去了
![image](https://github.com/jdf2e/nutui/assets/49502875/935d3aae-a629-4847-ac5a-c3229438ab11)

### 环境信息

👽 Taro v3.6.18

  Taro CLI 3.6.18 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.npm-global/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.18 => 3.6.18 
      @tarojs/components: 3.6.18 => 3.6.18 
      @tarojs/helper: 3.6.18 => 3.6.18 
      @tarojs/plugin-framework-vue3: 3.6.18 => 3.6.18 
      @tarojs/plugin-html: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-alipay: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-weapp: 3.6.18 => 3.6.18 
      @tarojs/plugin-vue-devtools: ^3.6.19 => 3.6.19 
      @tarojs/runtime: 3.6.18 => 3.6.18 
      @tarojs/shared: 3.6.18 => 3.6.18 
      @tarojs/taro: 3.6.18 => 3.6.18 
      @tarojs/taro-loader: 3.6.18 => 3.6.18 
      @tarojs/webpack5-runner: 3.6.18 => 3.6.18 
      babel-preset-taro: 3.6.18 => 3.6.18 
      eslint-config-taro: 3.6.18 => 3.6.18 

### 其他补充信息

- 小程序端
- webpack 5.78.0
- webpack-bundle-analyzer 4.10.1

**Comment by eiinu** [comment]
`@nutui/icons-vue-taro` 使用的是 iconfont 方案，主要分为两部分：
- iconfont 字体样式文件，所有图标都在里面，大概 100kb。在字体图标方案下，这部分资源无法实现按需引入，会作为样式被全量引入。
- 图标的 vue 组件，即图片中展示的文件，这部分作为 vue 组件本身就支持按需引入。

测试了仓库中的代码，`dev:weapp` 下有这些组件代码，`build:weapp`的构建产物则没有，是符合预期的。

**Comment by tiny-dust** [comment]
> `@nutui/icons-vue-taro` 使用的是 iconfont 方案，主要分为两部分：
> 
> * iconfont 字体样式文件，所有图标都在里面，大概 100kb。在字体图标方案下，这部分资源无法实现按需引入，会作为样式被全量引入。
> * 图标的 vue 组件，即图片中展示的文件，这部分作为 vue 组件本身就支持按需引入。
> 
> 测试了仓库中的代码，`dev:weapp` 下有这些组件代码，`build:weapp`的构建产物则没有，是符合预期的。

明白了，我去检查了一下，确实是只有 100k的 wxss 资源，感谢测试和回复
