### ISSUE TITLE
nut-tab-panel动态渲染不上数据，怎么解决？

### ISSUE THREAD

**Issue by nocence** [jdf2e/nutui#277]
<nut-tab class="part-title" @tab-switch="getChildSorts">
                    <nut-tab-panel v-for="(item,index) in partySorts" :tab-title="item.name" :key="index"> 
                     </nut-tab-panel>
 </nut-tab>
动态渲染nut-tab-panel的数据失败，试过 :tab-title，:tabtitle，tab-title的写法，都不行

**Comment by richard1015** [comment]
辛苦提供一个最小复现仓库
