### ISSUE TITLE
input-number disbaled 减号仍然可以点击!

### ISSUE THREAD

**Issue by kuzanFrozen** [jdf2e/nutui#2779]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.1.4

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LWlucHV0LW51bWJlciB2LW1vZGVsPVwidmFsdWVcIiBkaXNhYmxlZCAvPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnO1xuY29uc3QgdmFsdWUgPSByZWYoMTAwKTtcbjwvc2NyaXB0PiJ9

### 重现步骤

设置disabled属性，加减按钮仍然可以点并且值也会变化，官网demo和本地开发可以复现，重现链接又没有问题

### 期望的结果是什么？

设置disabled属性，不可以点击加减按钮且值不要变化

### 实际的结果是什么？

设置disabled属性，加减按钮仍然可以点并且值也会变化

**Comment by eiinu** [comment]
#2675
`v4.2.2` 已修复

**Comment by kuzanFrozen** [comment]
我升级到最新版还是有问题 @eiinu

**Comment by kuzanFrozen** [comment]
我重新创建了新项目，把nut升级到最新版本仍然有这个问题

**Comment by kuzanFrozen** [comment]
![WX20231221-163316](https://github.com/jdf2e/nutui/assets/140991981/0fda8048-d83d-41cc-af30-8481b19a5d51)

**Comment by kuzanFrozen** [comment]
![WX20231221-163338](https://github.com/jdf2e/nutui/assets/140991981/2c9c45ae-e10c-4b45-9b67-d23acd62123a)
![WX20231221-163352](https://github.com/jdf2e/nutui/assets/140991981/e66c6948-43a3-447e-b636-62655a8986df)
![WX20231221-163419](https://github.com/jdf2e/nutui/assets/140991981/d83cf383-dea0-4ce7-b0ac-ad1929a25251)

**Comment by kuzanFrozen** [comment]
@eiinu

**Comment by eiinu** [comment]
之前的 PR 似乎只修复了 `@nutui/nutui`，taro 版本未处理。
下个版本会修复这个问题。

**Comment by eiinu** [comment]
redirect #2782
