### ISSUE TITLE
DatePicker 限制了开始时间，但是开始时间之前的时间还能选择，期望禁用[bug]

### ISSUE THREAD

**Issue by carpenterzoe** [jdf2e/nutui#278]
## 问题描述
DatePicker 限制了开始时间，但是开始时间之前的时间仍然能选择，期望能设置禁用开始时间之前的时间。

## 预期的行为和实际行为
期望能设置禁用开始时间之前的时间。

**Comment by richard1015** [comment]
可以提供一个最小复现仓库

**Comment by zjyau** [comment]
应该是这个问题，已经修复了 #275

**Comment by carpenterzoe** [comment]
> 应该是这个问题，已经修复了 #275

谢谢，请问是更新最新的包就可以了吗

**Comment by carpenterzoe** [comment]
@zjyau 我重新删除再装过包，修改部分的代码好像并没有更新。。

**Comment by zjyau** [comment]
@carpenterzoe  ,这块没更新，估计月底修复

**Comment by richard1015** [comment]
请使用 v2.2.6 最新包进行测试此问题，
