### ISSUE TITLE
input-number disbaled 加号仍然可以点击!

### ISSUE THREAD

**Issue by kuzanFrozen** [jdf2e/nutui#2782]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.2.4

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LWNlbGwgOnNob3ctaWNvbj1cInRydWVcIiA6aXNMaW5rPVwidHJ1ZVwiIEBjbGljaz1cInN3aXRjaEFjdGlvblNoZWV0KCdpc1Zpc2libGUxJylcIj5cbiAgICA8c3Bhbj48bGFiZWw+5Z+656GA55So5rOVPC9sYWJlbD48L3NwYW4+XG4gICAgPGRpdiB2LWh0bWw9XCJzdGF0ZS52YWxcIj48L2Rpdj5cbiAgPC9udXQtY2VsbD5cbiAgPCEtLSBkZW1vIOWfuuehgOeUqOazlSAtLT5cbiAgPG51dC1hY3Rpb24tc2hlZXQgdi1tb2RlbDp2aXNpYmxlPVwic3RhdGUuaXNWaXNpYmxlMVwiIDptZW51LWl0ZW1zPVwibWVudUl0ZW1zT25lXCIgQGNob29zZT1cImNob29zZUl0ZW1cIiA6Y2xvc2UtYWJsZWQ9XCJmYWxzZVwiPlxuICA8L251dC1hY3Rpb24tc2hlZXQ+XG48L3RlbXBsYXRlPlxuPHNjcmlwdD5cbiAgaW1wb3J0IHsgcmVhY3RpdmUgfSBmcm9tICd2dWUnO1xuICBleHBvcnQgZGVmYXVsdCB7XG4gICAgc2V0dXAoKSB7XG4gICAgICBjb25zdCBzdGF0ZSA9IHJlYWN0aXZlKHtcbiAgICAgICAgaXNWaXNpYmxlMTogZmFsc2UsXG4gICAgICAgIHZhbDogJydcbiAgICAgIH0pO1xuICAgICAgY29uc3QgbWVudUl0ZW1zT25lID0gW1xuICAgICAgICB7XG4gICAgICAgICAgbmFtZTogJ+mAiemhueS4gCdcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIG5hbWU6ICfpgInpobnkuownXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBuYW1

### 重现步骤

设置disabled属性，加减按钮仍然可以点并且值也会变化，官网demo和本地开发可以复现，重现链接又没有问题，在微信小程序端出现这个问题

### 期望的结果是什么？

设置disabled属性，加减按钮仍然可以点并且值也会变化，官网demo和本地开发可以复现，重现链接又没有问题

### 实际的结果是什么？

设置disabled属性，不可以点击加减按钮且值不要变化

### 其他补充信息

![image](https://github.com/jdf2e/nutui/assets/140991981/cb768ee3-0cb5-4c90-9ed6-33c65c9a7839)

**Comment by kuzanFrozen** [comment]
在h5端4.2.2是已经修复了，在taro里却没有同步这个问题

**Comment by eiinu** [comment]
感谢反馈，明天会发版 `v4.2.5` 修复这个问题
