### ISSUE TITLE
tab组件点击回调的问题

### ISSUE THREAD

**Issue by augustVino** [jdf2e/nutui#28]
tab组件中，点击tab的title文字，不会触发tabSwitch事件，看了下组件代码，发现是被event.target拦截了。
`switchTab:function(index,event,disable){
       if(!disable && event.target.className.indexOf('nut-title-nav')!==-1){
                ...
                ...
                this.$emit('tab-switch',index,event); 
       }
}`

**Comment by augustVino** [comment]
问题不是switchTab方法，是switchTabLink方法中的event.target.parentNode.click();的问题，改成
             let myEvent = new Event('click');
             event.target.parentNode.dispatchEvent(myEvent);
之后可以正常运行了。

**Comment by Franslee** [comment]
复现不了啊
