### ISSUE TITLE
Dialog、ActionSheet组件内嵌套form表单，在真机调试下栈溢出

### ISSUE THREAD

**Issue by wlitd** [jdf2e/nutui#2807]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.2.0

### 平台

weapp

### 重现链接

无

### 重现步骤

 <nut-action-sheet v-model:visible="visible" :title="title">
      <nut-form :model-value="formData">
        <nut-form-item label="标题">
          <nut-input
            v-model="formData.title"
            class="nut-input-text"
            type="text"
          />
        </nut-form-item>
        <nut-form-item label="类型">
          <nut-input
            v-model="formData.type"
            class="nut-input-text"
            type="text"
          />
        </nut-form-item>
        <nut-form-item label="描述">
          <nut-input
            v-model="formData.description"
            class="nut-input-text"
            type="text"
          />
        </nut-form-item>
        <nut-form-item label="纬度">
          <nut-input-number
            v-model="formData.latitude"
            class="nut-input-text"
            input-width="80px"
            button-size="20px"
            min="-180"
            max="180"
            decimal-places="5"
            :disabled="isEdit"
          />
        </nut-form-item>
        <nut-form-item label="经度">
          <nut-input-number
            v-model="formData.longitude"
            class="nut-input-text"
            input-width="80px"
            button-size="20px"
            min="-180"
            max="180"
            decimal-places="5"
            :disabled="isEdit"
          />
        </nut-form-item>
        <nut-cell class="flex justify-end">
          <nut-button type="primary" size="small" @click="onSubmit"
            >提交</nut-button
          >
        </nut-cell>
      </nut-form>
    </nut-action-sheet>

### 期望的结果是什么？

打开dialog或者actionSheet时填写保存表单

### 实际的结果是什么？

通过微信开发工具真机调式栈溢出，但是开发者工具预览没出现此问题，代码无死循环等等错误逻辑
![屏幕截图 2023-12-27 165058](https://github.com/jdf2e/nutui/assets/67183310/b4ef3d20-3852-495b-80b8-258283fde9c7)

### 环境信息

👽 Taro v3.6.18

  Taro CLI 3.6.18 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 16.18.1 - ~\Documents\Node\node.EXE
      npm: 8.19.2 - ~\Documents\Node\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.18 => 3.6.18 
      @tarojs/components: 3.6.18 => 3.6.18 
      @tarojs/helper: 3.6.18 => 3.6.18 
      @tarojs/plugin-framework-vue3: 3.6.18 => 3.6.18 
      @tarojs/plugin-html: ^3.6.18 => 3.6.18 
      @tarojs/plugin-platform-alipay: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-h5: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-jd: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-qq: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-swan: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-tt: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-weapp: 3.6.18 => 3.6.18 
      @tarojs/runtime: 3.6.18 => 3.6.18 
      @tarojs/shared: 3.6.18 => 3.6.18
      @tarojs/taro: 3.6.18 => 3.6.18
      @tarojs/taro-loader: 3.6.18 => 3.6.18
      @tarojs/webpack5-runner: 3.6.18 => 3.6.18
      babel-preset-taro: 3.6.18 => 3.6.18
      eslint-config-taro: 3.6.18 => 3.6.18

### 其他补充信息

vue3、Node16+、webpack5

**Comment by wlitd** [comment]
非常抱歉、这并不是一个bug，问题出现在我外面全局组件上的slot

**Comment by gyhyzx** [comment]
<template>
  <view>
    <nut-button type="primary" @click="onClick">测试</nut-button>
    <nut-action-sheet v-model:visible="visible" title="测试">
      <nut-form>
        <nut-form-item label="拍摄">
          <nut-grid :column-num="2" :border="false">
            <nut-grid-item v-for="item in fileList" :key="item.id">
              <nut-badge :color="'#ffffff'">
                <template #icon>
                  <CircleClose />
                </template>
                <img class="w-200 h-200" :src="item.sts" alt="" />
              </nut-badge>
            </nut-grid-item>
            <nut-grid-item>
              <nut-uploader url=""></nut-uploader>
            </nut-grid-item>
          </nut-grid>
        </nut-form-item>
      </nut-form>
    </nut-action-sheet>
  </view>
</template>

<script setup lang="ts">
import { FileInfo } from '@/busPackage/api/file'
import { CircleClose } from '@nutui/icons-vue-taro'

definePageConfig({
  navigationBarTitleText: '首页'
})

const fileList = ref<FileInfo[]>([])
const visible = ref<boolean>(false)
const onClick = () => {
  visible.value = true
}
</script>
抱歉提供一个复现仓库有点困难、这是我的首页代码 在开发工具下预览没问题 在真机ios下出现上述的栈溢出问题 ios17

**Comment by wlitd** [comment]
```
<template>
  <view>
    <nut-button type="primary" @click="onClick">测试</nut-button>
    <nut-action-sheet v-model:visible="visible" title="测试">
      <nut-form>
        <nut-form-item label="拍摄">
          <nut-grid :column-num="2" :border="false">
            <nut-grid-item v-for="item in fileList" :key="item.id">
              <nut-badge :color="'#ffffff'">
                <template #icon>
                  <CircleClose />
                </template>
                <img class="w-200 h-200" :src="item.sts" alt="" />
              </nut-badge>
            </nut-grid-item>
            <nut-grid-item>
              <nut-uploader url=""></nut-uploader>
            </nut-grid-item>
          </nut-grid>
        </nut-form-item>
      </nut-form>
    </nut-action-sheet>
  </view>
</template>

<script setup lang="ts">
import { FileInfo } from '@/busPackage/api/file'
import { CircleClose } from '@nutui/icons-vue-taro'

definePageConfig({
  navigationBarTitleText: '首页'
})

const fileList = ref<FileInfo[]>([])
const visible = ref<boolean>(false)
const onClick = () => {
  visible.value = true
}
</script>
```
抱歉提供一个复现仓库可能有点困难，这是我的首页代码，此代码在开发工具下预览没问题，真机到ios下出现上述栈溢出错误，ios17

**Comment by eiinu** [comment]
> 抱歉提供一个复现仓库可能有点困难，这是我的首页代码，此代码在开发工具下预览没问题，真机到ios下出现上述栈溢出错误，ios17

我们实际真机测试了这段代码在 iOS设备（iOS15）、安卓设备（安卓14），均没有出现类似问题

可能是其他因素导致的，建议提供完整的最小可复现仓库

**Comment by wlitd** [comment]
> > 抱歉提供一个复现仓库可能有点困难，这是我的首页代码，此代码在开发工具下预览没问题，真机到ios下出现上述栈溢出错误，ios17
> 
> 我们实际真机测试了这段代码在 iOS设备（iOS15）、安卓设备（安卓14），均没有出现类似问题
> 
> 可能是其他因素导致的，建议提供完整的最小可复现仓库

https://github.com/gyhyzx/test.git 这是一个复现仓库、目前出现的问题是真机到IOS17下出现错误、真机到PC端无错误、安卓设备没有测试

**Comment by eiinu** [comment]
> > > 抱歉提供一个复现仓库可能有点困难，这是我的首页代码，此代码在开发工具下预览没问题，真机到ios下出现上述栈溢出错误，ios17
> > 
> > 
> > 我们实际真机测试了这段代码在 iOS设备（iOS15）、安卓设备（安卓14），均没有出现类似问题
> > 可能是其他因素导致的，建议提供完整的最小可复现仓库
> 
> https://github.com/gyhyzx/test.git 这是一个复现仓库、目前出现的问题是真机到IOS17下出现错误、真机到PC端无错误、安卓设备没有测试

使用 npm、yarn、pnpm 安装依赖后都无法启动这个项目……
