### ISSUE TITLE
Popup 弹出层 这个组件直接把overflow hidden加到body上了，导致所有页面不能滚动[bug]

### ISSUE THREAD

**Issue by carpenterzoe** [jdf2e/nutui#281]
## 问题描述

Popup 弹出层 这个组件直接把overflow hidden加到body上了，导致所有页面不能滚动

## 预期的行为和实际行为
.nut-overflow-hidden {
    overflow: hidden !important;
}
全局加的这个样式，在popup隐藏了之后也没有移除，导致全部其他页面都无法滚动。

**Comment by yangkaixuan** [comment]
能提供下复现的demo吗？我这边没有找到复现规律，也可以加我微信，我来看下 yangkaixuan909319

**Comment by carpenterzoe** [comment]
> 能提供下复现的demo吗？我这边没有找到复现规律，也可以加我微信，我来看下 yangkaixuan909319

在当前页弹出Popup，然后跳转到任意其他页面。
由于overflow: hidden加到了body上，所以其他页面滚动不了。
并且直接跳转到其他页，也触发不了popup close事件。
我目前采取的方法是离开页面时，自己手动清除这个class，暂时解决了。

**Comment by yangkaixuan** [comment]
了解了，下个版本修复

**Comment by doghap** [comment]
我目前用的版本是4.0.1， 使用dialog(底层用popup实现的)的时候也遇到同样的问题，我看了[官方演示](https://nutui.jd.com/h5/vue/4x/demo.html#/dialog)里也存在同样的问题，自己断点测试了一下，Overlay 组件里66-68行:
```    watchEffect(() => {
      props.visible ? lock() : unlock();
    });``` 
`visible` 为true时能触发，false (也就是弹窗关闭之时) 时还没watchEffect 组件就销毁了，导致unlock()没有执行，body里的class就没有去掉导致后面所有的页面都带这class
