### ISSUE TITLE
[FR]: AvatarCropper 头像上传头像裁剪组件支持圆角，属性暴露出来或者增加css设置即可

### ISSUE THREAD

**Issue by asdtiang** [jdf2e/nutui#2810]
### NutUI 包名

@nutui/nutui-taro

### 这个功能解决了什么问题？

![66f6377aedb64b1820b270598633eba](https://github.com/jdf2e/nutui/assets/1144419/f11a67ea-c31c-4d58-9311-508eaf6c769f)

或者设置一个css，开发者可以自己添加样式

### 你期望的组件设计是怎样的？

头像上传圆角选择

**Comment by yi-boide** [comment]
这个可不止是暴露出来那么简单，你可以直接使用:deep进行样式设置，截取后内容还会是方形的，在展示的地方加圆角
