### ISSUE TITLE
nut-form-item body-align="right" 不生效

### ISSUE THREAD

**Issue by lyedoc** [jdf2e/nutui#2817]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.0.4

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7XG5jb25zdCBjdXJyZW50ID0gcmVmKDEpO1xuY29uc3QgYmFzaWNEYXRhID0gcmVmPGFueT4oe1xufSk7XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC1mb3JtPlxuICAgIDxudXQtZm9ybS1pdGVtIGJvZHktYWxpZ249XCJyaWdodFwiIDpsYWJlbC13aWR0aD1cIjYwXCIgbGFiZWw9XCLlp5PlkI1cIj5cbiAgICAgIDxudXQtaW5wdXQgdi1tb2RlbD1cImJhc2ljRGF0YS5uYW1lXCIgY2xhc3M9XCJudXQtaW5wdXQtdGV4dFwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl5aeT5ZCNXCIgdHlwZT1cInRleHRcIiAvPlxuICAgIDwvbnV0LWZvcm0taXRlbT5cbiAgICA8bnV0LWZvcm0taXRlbSBib2R5LWFsaWduPVwicmlnaHRcIiA6bGFiZWwtd2lkdGg9XCI2MFwiIGxhYmVsPVwi5bm06b6EXCI+XG4gICAgICA8bnV0LWlucHV0IHYtbW9kZWw9XCJiYXNpY0RhdGEuYWdlXCIgY2xhc3M9XCJudXQtaW5wdXQtdGV4dFwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl5bm06b6EXCIgdHlwZT1cInRleHRcIiAvPlxuICAgIDwvbnV0LWZvcm0taXRlbT5cbiAgICA8bnV0LWZvcm0taXRlbSBib2R5LWFsaWduPVwicmlnaHRcIiA6bGFiZWwtd2lkdGg9XCI2MFwiIGxhYmVsPVwi6IGU57O755S16K+dXCI+XG4gICAgICA8bnV0LWlucHV0IHYtbW9kZWw9XCJiYXNpY0RhdGEudGVsXCIgY2xhc3M9XCJudXQtaW5wdXQtdGV4dFwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl6IGU57O755S16K+dXCIgdHlwZT1cInRleHRcIiAvPlxuICAgIDwvbnV0LWZvcm0taXRlbT5cbiAgICA8bnV0LWZvcm0taXRlbSBib2R5LWFsaWduPVwicmlnaHRcIiA6bGFiZWwtd2lkdGg9XCI2MFwiIHYtbW9kZWw9XCJiYXNpY0RhdGEuYWRkcmVzc1wiIGxhYmVsPVwi5Zyw5Z2AXCI+XG4gICAgICA8bnV0LWlucHV0IGNsYXNzPVwibnV0LWlucHV0LXRleHRcIiBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpeWcsOWdgFwiIHR5cGU9XCJ0ZXh0XCIgLz5cbiAgICA8L251dC1mb3JtLWl0ZW0+XG4gICAgPG51dC1mb3JtLWl0ZW0gYm9keS1hbGlnbj1cInJpZ2h0XCIgOmxhYmVsLXdpZHRoPVwiNjBcIiBsYWJlbD1cIuWkh+azqFwiPlxuICAgICAgPG51dC10ZXh0YXJlYSBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpeWkh+azqFwiIHR5cGU9XCJ0ZXh0XCIgLz5cbiAgICA8L251dC1mb3JtLWl0ZW0+XG4gIDwvbnV0LWZvcm0+XG48L3RlbXBsYXRlPiJ9

### 重现步骤

1、将nutui form的示例拷进项目；
2、修改nut-form-item body-align="right"。

`
<nut-form>

        <nut-form-item body-align="right" :label-width="60" label="姓名">
          <nut-input v-model="basicData.name" class="nut-input-text" placeholder="请输入姓名" type="text" />
        </nut-form-item>

        <nut-form-item body-align="right" :label-width="60" label="年龄">
          <nut-input v-model="basicData.age" class="nut-input-text" placeholder="请输入年龄" type="text" />
        </nut-form-item>

        <nut-form-item body-align="right" :label-width="60" label="联系电话">
          <nut-input v-model="basicData.tel" class="nut-input-text" placeholder="请输入联系电话" type="text" />
        </nut-form-item>

        <nut-form-item body-align="right" :label-width="60" v-model="basicData.address" label="地址">
          <nut-input class="nut-input-text" placeholder="请输入地址" type="text" />
        </nut-form-item>

        <nut-form-item body-align="right" :label-width="60" label="备注">
          <nut-textarea placeholder="请输入备注" type="text" />
        </nut-form-item>

</nut-form>`

### 期望的结果是什么？

![bug](https://github.com/jdf2e/nutui/assets/97219226/8141038d-e2f9-4c42-9224-8ed733cc0f53)

### 实际的结果是什么？

![image](https://github.com/jdf2e/nutui/assets/97219226/94c4347a-ad63-4af6-875f-be9897ca55c2)

### 环境信息

  System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 308.43 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Edge: 120.0.2210.91
    Safari: 16.5.2

### 其他补充信息

经分析节点发现，是内部的input输入框内容没有右对齐，同时包裹input的外层容器的flex水平对齐方式不对，应该为flex-end。
![image](https://github.com/jdf2e/nutui/assets/97219226/ef07c076-b40f-44eb-bec4-9a7f5e833367)

**Comment by eiinu** [comment]
FormItem 上的 body-align 控制的是右侧插槽的文本对齐方式。

如果想设置 FormItem 内部的 Input 的对齐方式，可以直接使用 Input 上的 input-align 属性，参考 [Playground](https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7XG5jb25zdCBjdXJyZW50ID0gcmVmKDEpO1xuY29uc3QgYmFzaWNEYXRhID0gcmVmPGFueT4oe1xufSk7XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC1mb3JtPlxuICAgIDxudXQtZm9ybS1pdGVtIDpsYWJlbC13aWR0aD1cIjYwXCIgbGFiZWw9XCLlp5PlkI1cIj5cbiAgICAgIDxudXQtaW5wdXQgdi1tb2RlbD1cImJhc2ljRGF0YS5uYW1lXCIgaW5wdXQtYWxpZ249XCJyaWdodFwiIGNsYXNzPVwibnV0LWlucHV0LXRleHRcIiBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpeWnk+WQjVwiIHR5cGU9XCJ0ZXh0XCIgLz5cbiAgICA8L251dC1mb3JtLWl0ZW0+XG4gICAgPG51dC1mb3JtLWl0ZW0gOmxhYmVsLXdpZHRoPVwiNjBcIiBsYWJlbD1cIuW5tOm+hFwiPlxuICAgICAgPG51dC1pbnB1dCB2LW1vZGVsPVwiYmFzaWNEYXRhLmFnZVwiIGlucHV0LWFsaWduPVwicmlnaHRcIiBjbGFzcz1cIm51dC1pbnB1dC10ZXh0XCIgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXlubTpvoRcIiB0eXBlPVwidGV4dFwiIC8+XG4gICAgPC9udXQtZm9ybS1pdGVtPlxuICAgIDxudXQtZm9ybS1pdGVtIDpsYWJlbC13aWR0aD1cIjYwXCIgbGFiZWw9XCLogZTns7vnlLXor51cIj5cbiAgICAgIDxudXQtaW5wdXQgdi1tb2RlbD1cImJhc2ljRGF0YS50ZWxcIiBpbnB1dC1hbGlnbj1cInJpZ2h0XCIgY2xhc3M9XCJudXQtaW5wdXQtdGV4dFwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl6IGU57O755S16K+dXCIgdHlwZT1cInRleHRcIiAvPlxuICAgIDwvbnV0LWZvcm0taXRlbT5cbiAgICA8bnV0LWZvcm0taXRlbSA6bGFiZWwtd2lkdGg9XCI2MFwiIHYtbW9kZWw9XCJiYXNpY0RhdGEuYWRkcmVzc1wiIGxhYmVsPVwi5Zyw5Z2AXCI+XG4gICAgICA8bnV0LWlucHV0IGNsYXNzPVwibnV0LWlucHV0LXRleHRcIiBpbnB1dC1hbGlnbj1cInJpZ2h0XCIgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXlnLDlnYBcIiB0eXBlPVwidGV4dFwiIC8+XG4gICAgPC9udXQtZm9ybS1pdGVtPlxuICAgIDxudXQtZm9ybS1pdGVtIDpsYWJlbC13aWR0aD1cIjYwXCIgbGFiZWw9XCLlpIfms6hcIj5cbiAgICAgIDxudXQtdGV4dGFyZWEgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXlpIfms6hcIiB0ZXh0LWFsaWduPVwicmlnaHRcIiB0eXBlPVwidGV4dFwiIC8+XG4gICAgPC9udXQtZm9ybS1pdGVtPlxuICA8L251dC1mb3JtPlxuPC90ZW1wbGF0ZT4ifQ==)

**Comment by lyedoc** [comment]
> FormItem 上的 body-align 控制的是右侧插槽的文本对齐方式。
> 
> 如果想设置 FormItem 内部的 Input 的对齐方式，可以直接使用 Input 上的 input-align 属性，参考 [Playground](https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7XG5jb25zdCBjdXJyZW50ID0gcmVmKDEpO1xuY29uc3QgYmFzaWNEYXRhID0gcmVmPGFueT4oe1xufSk7XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC1mb3JtPlxuICAgIDxudXQtZm9ybS1pdGVtIDpsYWJlbC13aWR0aD1cIjYwXCIgbGFiZWw9XCLlp5PlkI1cIj5cbiAgICAgIDxudXQtaW5wdXQgdi1tb2RlbD1cImJhc2ljRGF0YS5uYW1lXCIgaW5wdXQtYWxpZ249XCJyaWdodFwiIGNsYXNzPVwibnV0LWlucHV0LXRleHRcIiBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpeWnk+WQjVwiIHR5cGU9XCJ0ZXh0XCIgLz5cbiAgICA8L251dC1mb3JtLWl0ZW0+XG4gICAgPG51dC1mb3JtLWl0ZW0gOmxhYmVsLXdpZHRoPVwiNjBcIiBsYWJlbD1cIuW5tOm+hFwiPlxuICAgICAgPG51dC1pbnB1dCB2LW1vZGVsPVwiYmFzaWNEYXRhLmFnZVwiIGlucHV0LWFsaWduPVwicmlnaHRcIiBjbGFzcz1cIm51dC1pbnB1dC10ZXh0XCIgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXlubTpvoRcIiB0eXBlPVwidGV4dFwiIC8+XG4gICAgPC9udXQtZm9ybS1pdGVtPlxuICAgIDxudXQtZm9ybS1pdGVtIDpsYWJlbC13aWR0aD1cIjYwXCIgbGFiZWw9XCLogZTns7vnlLXor51cIj5cbiAgICAgIDxudXQtaW5wdXQgdi1tb2RlbD1cImJhc2ljRGF0YS50ZWxcIiBpbnB1dC1hbGlnbj1cInJpZ2h0XCIgY2xhc3M9XCJudXQtaW5wdXQtdGV4dFwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl6IGU57O755S16K+dXCIgdHlwZT1cInRleHRcIiAvPlxuICAgIDwvbnV0LWZvcm0taXRlbT5cbiAgICA8bnV0LWZvcm0taXRlbSA6bGFiZWwtd2lkdGg9XCI2MFwiIHYtbW9kZWw9XCJiYXNpY0RhdGEuYWRkcmVzc1wiIGxhYmVsPVwi5Zyw5Z2AXCI+XG4gICAgICA8bnV0LWlucHV0IGNsYXNzPVwibnV0LWlucHV0LXRleHRcIiBpbnB1dC1hbGlnbj1cInJpZ2h0XCIgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXlnLDlnYBcIiB0eXBlPVwidGV4dFwiIC8+XG4gICAgPC9udXQtZm9ybS1pdGVtPlxuICAgIDxudXQtZm9ybS1pdGVtIDpsYWJlbC13aWR0aD1cIjYwXCIgbGFiZWw9XCLlpIfms6hcIj5cbiAgICAgIDxudXQtdGV4dGFyZWEgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXlpIfms6hcIiB0ZXh0LWFsaWduPVwicmlnaHRcIiB0eXBlPVwidGV4dFwiIC8+XG4gICAgPC9udXQtZm9ybS1pdGVtPlxuICA8L251dC1mb3JtPlxuPC90ZW1wbGF0ZT4ifQ==)
好的
