### ISSUE TITLE
希望能出一个类elementUI的折叠面板功能

### ISSUE THREAD

**Issue by Ma-Tao007** [jdf2e/nutui#282]
## 你建议我们做什么？
希望能出一个类elementUI的折叠面板功能，
折叠面板在手机中的使用场景较多，之前写小程序的使用用到过，希望你们团队可以做出来一个，目前的公众号项目中也想使用折叠面板，但是nutui框架中没有

**Comment by richard1015** [comment]
感谢反馈，我们近期跟进一下
