### ISSUE TITLE
[FR]: data-picker希望增加年份选择

### ISSUE THREAD

**Issue by yh927** [jdf2e/nutui#2827]
### NutUI 包名

@nutui/nutui

### 这个功能解决了什么问题？

目前都是年月，月日联动，我觉得单独选择查询xx年或者xx月的数据是有这些需求的

### 你期望的组件设计是怎样的？

我期望的data-picker可以单独选择xx年或者xx月

**Comment by eiinu** [comment]
如果只需要单列数据，可以直接使用 picker，更容易实现这个功能

**Comment by yh927** [comment]
是的，可以把想要的年份放到一起，但是样式不太一样，这种方式是可行的
