### ISSUE TITLE
Swipe 滑动手势 Swipe 互斥lock失效，并且页面不可以向上滑动

### ISSUE THREAD

**Issue by live-beautiful** [jdf2e/nutui#2832]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.0.4

### 平台

weapp

### 重现链接

eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgIDxudXQtc3dpcGUtZ3JvdXAgbG9jayB2LWZvcj1cIihpdGVtLCBpbmRleCkgaW4gZGF0YUxpc3RcIiA6a2V5PVwiaW5kZXhcIj5cbiAgICAgIDxudXQtc3dpcGUgbmFtZT1cIml0ZW0uaWRcIj5cbiAgICAgICAgPG51dC1jZWxsIHJvdW5kLXJhZGl1cz1cIjBcIiA6dGl0bGU9XCJpdGVtLm5hbWVcIiAvPlxuICAgICAgICA8dGVtcGxhdGUgI3JpZ2h0PlxuICAgICAgICAgIDxudXQtYnV0dG9uIHNoYXBlPVwic3F1YXJlXCIgc3R5bGU9XCJoZWlnaHQ6IDEwMCVcIiB0eXBlPVwiZGFuZ2VyXCI

### 重现步骤

`<template>
    <nut-swipe-group lock v-for="(item, index) in dataList" :key="index">
      <nut-swipe name="item.id">
        <nut-cell round-radius="0" :title="item.name" />
        <template #right>
          <nut-button shape="square" style="height: 100%" type="danger">Button</nut-button>
        </template>
      </nut-swipe>
    </nut-swipe-group>
  </template>
  
<script setup>
import { ref } from "vue";
import mockData from "./mock.json"
const dataList = ref(mockData)
[</script>`]
[Uploading mock.json…]()

### 期望的结果是什么？

微信小程序内部 Swipe 互斥，数据多的情况下页面可以scroll

### 实际的结果是什么？

微信小程序内部 Swipe 互斥不生效，数据多的情况下页面不能上下滑动

### 环境信息

Taro CLI 3.6.22 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.14.2 - D:\nodejs\node.EXE
      npm: 9.5.0 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.22 => 3.6.22
      @tarojs/components: 3.6.22 => 3.6.22
      @tarojs/helper: 3.6.22 => 3.6.22
      @tarojs/plugin-framework-vue3: 3.6.22 => 3.6.22
      @tarojs/plugin-html: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-alipay: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-h5: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-jd: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-qq: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-swan: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-tt: 3.6.22 => 3.6.22
      @tarojs/plugin-platform-weapp: 3.6.22 => 3.6.22
      @tarojs/runtime: 3.6.22 => 3.6.22
      @tarojs/shared: 3.6.22 => 3.6.22
      @tarojs/taro: 3.6.22 => 3.6.22
      @tarojs/taro-loader: 3.6.22 => 3.6.22
      @tarojs/webpack5-runner: 3.6.22 => 3.6.22
      babel-preset-taro: 3.6.22 => 3.6.22
      eslint-config-taro: 3.6.22 => 3.6.22

### 其他补充信息

vue版本3.2.40

**Comment by live-beautiful** [comment]
重现链接：https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgIDxudXQtc3dpcGUtZ3JvdXAgbG9jayB2LWZvcj1cIihpdGVtLCBpbmRleCkgaW4gZGF0YUxpc3RcIiA6a2V5PVwiaW5kZXhcIj5cbiAgICAgIDxudXQtc3dpcGUgbmFtZT1cIml0ZW0uaWRcIj5cbiAgICAgICAgPG51dC1jZWxsIHJvdW5kLXJhZGl1cz1cIjBcIiA6dGl0bGU9XCJpdGVtLm5hbWVcIiAvPlxuICAgICAgICA8dGVtcGxhdGUgI3JpZ2h0PlxuICAgICAgICAgIDxudXQtYnV0dG9uIHNoYXBlPVwic3F1YXJlXCIgc3R5bGU9XCJoZWlnaHQ6IDEwMCVcIiB0eXBlPVwiZGFuZ2VyXCI+QnV0dG9uPC9udXQtYnV0dG9uPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgPC9udXQtc3dpcGU+XG4gICAgPC9udXQtc3dpcGUtZ3JvdXA+XG4gIDwvdGVtcGxhdGU+XG4gIFxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIjtcbmltcG9ydCBtb2NrRGF0YSBmcm9tIFwiLi9tb2NrLmpzb25cIlxuY29uc3QgZGF0YUxpc3QgPSByZWYobW9ja0RhdGEpXG48L3NjcmlwdD4iLCJtb2NrLmpzb24iOiJbXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLpg73mmJ9cIixcbiAgICAgICAgXCJpZFwiOiBcIjFcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLnqqbmjaLosapcIixcbiAgICAgICAgXCJpZFwiOiBcIjJcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLmrrXmnbBcIixcbiAgICAgICAgXCJpZFwiOiBcIjNcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLpg63ooYzmoZBcIixcbiAgICAgICAgXCJpZFwiOiBcIjRcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLpg63lt7LmpaBcIixcbiAgICAgICAgXCJpZFwiOiBcIjVcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLkvZXlrozlq6NcIixcbiAgICAgICAgXCJpZFwiOiBcIjZcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLpnbPpl67mlodcIixcbiAgICAgICAgXCJpZFwiOiBcIjdcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLmnY7miJHonbZcIixcbiAgICAgICAgXCJpZFwiOiBcIjhcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLliJjmtZtcIixcbiAgICAgICAgXCJpZFwiOiBcIjlcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLpqaznjKrom4tcIixcbiAgICAgICAgXCJpZFwiOiBcIjEwXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJuYW1lXCI6IFwi5Lu755qT6ZyPXCIsXG4gICAgICAgIFwiaWRcIjogXCIxMVwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwibmFtZVwiOiBcIuWui+WNk+eEtlwiLFxuICAgICAgICBcImlkXCI6IFwiMTJcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLnlLDmrKfnnb9cIixcbiAgICAgICAgXCJpZFwiOiBcIjEzXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJuYW1lXCI6IFwi546L5p+v6IKJXCIsXG4gICAgICAgIFwiaWRcIjogXCIxNFwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwibmFtZVwiOiBcIueOi+agkVwiLFxuICAgICAgICBcImlkXCI6IFwiMTVcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLnjovnuqLliJpcIixcbiAgICAgICAgXCJpZFwiOiBcIjE2XCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJuYW1lXCI6IFwi5YiR6ZyWXCIsXG4gICAgICAgIFwiaWRcIjogXCIxN1wiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwibmFtZVwiOiBcIuWOn+ivreWMllwiLFxuICAgICAgICBcImlkXCI6IFwiMThcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLlvKDlh6FcIixcbiAgICAgICAgXCJpZFwiOiBcIjE5XCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJuYW1lXCI6IFwi5byg5a2Y5YKoXCIsXG4gICAgICAgIFwiaWRcIjogXCIyMFwiXG4gICAgfVxuXSJ9

**Comment by eiinu** [comment]
> 重现链接：https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgIDxudXQtc3dpcGUtZ3JvdXAgbG9jayB2LWZvcj1cIihpdGVtLCBpbmRleCkgaW4gZGF0YUxpc3RcIiA6a2V5PVwiaW5kZXhcIj5cbiAgICAgIDxudXQtc3dpcGUgbmFtZT1cIml0ZW0uaWRcIj5cbiAgICAgICAgPG51dC1jZWxsIHJvdW5kLXJhZGl1cz1cIjBcIiA6dGl0bGU9XCJpdGVtLm5hbWVcIiAvPlxuICAgICAgICA8dGVtcGxhdGUgI3JpZ2h0PlxuICAgICAgICAgIDxudXQtYnV0dG9uIHNoYXBlPVwic3F1YXJlXCIgc3R5bGU9XCJoZWlnaHQ6IDEwMCVcIiB0eXBlPVwiZGFuZ2VyXCI+QnV0dG9uPC9udXQtYnV0dG9uPlxuICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgPC9udXQtc3dpcGU+XG4gICAgPC9udXQtc3dpcGUtZ3JvdXA+XG4gIDwvdGVtcGxhdGU+XG4gIFxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIjtcbmltcG9ydCBtb2NrRGF0YSBmcm9tIFwiLi9tb2NrLmpzb25cIlxuY29uc3QgZGF0YUxpc3QgPSByZWYobW9ja0RhdGEpXG48L3NjcmlwdD4iLCJtb2NrLmpzb24iOiJbXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLpg73mmJ9cIixcbiAgICAgICAgXCJpZFwiOiBcIjFcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLnqqbmjaLosapcIixcbiAgICAgICAgXCJpZFwiOiBcIjJcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLmrrXmnbBcIixcbiAgICAgICAgXCJpZFwiOiBcIjNcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLpg63ooYzmoZBcIixcbiAgICAgICAgXCJpZFwiOiBcIjRcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLpg63lt7LmpaBcIixcbiAgICAgICAgXCJpZFwiOiBcIjVcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLkvZXlrozlq6NcIixcbiAgICAgICAgXCJpZFwiOiBcIjZcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLpnbPpl67mlodcIixcbiAgICAgICAgXCJpZFwiOiBcIjdcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLmnY7miJHonbZcIixcbiAgICAgICAgXCJpZFwiOiBcIjhcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLliJjmtZtcIixcbiAgICAgICAgXCJpZFwiOiBcIjlcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLpqaznjKrom4tcIixcbiAgICAgICAgXCJpZFwiOiBcIjEwXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJuYW1lXCI6IFwi5Lu755qT6ZyPXCIsXG4gICAgICAgIFwiaWRcIjogXCIxMVwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwibmFtZVwiOiBcIuWui+WNk+eEtlwiLFxuICAgICAgICBcImlkXCI6IFwiMTJcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLnlLDmrKfnnb9cIixcbiAgICAgICAgXCJpZFwiOiBcIjEzXCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJuYW1lXCI6IFwi546L5p+v6IKJXCIsXG4gICAgICAgIFwiaWRcIjogXCIxNFwiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwibmFtZVwiOiBcIueOi+agkVwiLFxuICAgICAgICBcImlkXCI6IFwiMTVcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLnjovnuqLliJpcIixcbiAgICAgICAgXCJpZFwiOiBcIjE2XCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJuYW1lXCI6IFwi5YiR6ZyWXCIsXG4gICAgICAgIFwiaWRcIjogXCIxN1wiXG4gICAgfSxcbiAgICB7XG4gICAgICAgIFwibmFtZVwiOiBcIuWOn+ivreWMllwiLFxuICAgICAgICBcImlkXCI6IFwiMThcIlxuICAgIH0sXG4gICAge1xuICAgICAgICBcIm5hbWVcIjogXCLlvKDlh6FcIixcbiAgICAgICAgXCJpZFwiOiBcIjE5XCJcbiAgICB9LFxuICAgIHtcbiAgICAgICAgXCJuYW1lXCI6IFwi5byg5a2Y5YKoXCIsXG4gICAgICAgIFwiaWRcIjogXCIyMFwiXG4gICAgfVxuXSJ9

建议重新看文档检查一下 swipe-group 的用法。

**Comment by live-beautiful** [comment]
可以支持我说的这种用法吗😁

**Comment by eiinu** [comment]
> 可以支持我说的这种用法吗😁

正确用法：一个 swipe-group 中使用多个 swipe，lock 可控制这些 swipe 之间互斥。

你的 demo 中一个 swipe-group 中只用一个 swipe，是没有意义的

**Comment by live-beautiful** [comment]
好的
