### ISSUE TITLE
vite4使用auto-import-resolver按需引入任一组件报错

### ISSUE THREAD

**Issue by beautycss** [jdf2e/nutui#2841]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.2.7

### 平台

h5

### 重现链接

https://codesandbox.io/s/nutui4-vite-demo-forked-8x7xdr?file=/vite.config.ts

### 重现步骤

1. 本地基于vite4+vue3的h5新项目，运行正常，页面展示正常；
2. 安装4.2.7版本的nutui；
3. 在页面加了一个按钮，`<nut-button>按钮</nut-button>`；
4. 安装`unplugin-vue-components/vite`和`@nutui/auto-import-resolver`；
5. 按照官网文档，css按需引入nutui报错。
```
import Components from 'unplugin-vue-components/vite'
import NutUIResolver from '@nutui/auto-import-resolver'
```
```
...
Components({
  resolvers: [
    NutuiResolve()
  ]
}),
...
```
6. 加上`importStyle: 'sass'`，sass按需引入也报错。
```
...
Components({
  resolvers: [
    NutUIResolver({
      importStyle: 'sass'
    })
  ]
}),
...
```

### 期望的结果是什么？

任一组件正常引入，页面能正常显示

### 实际的结果是什么？

css方式引入报错：
```
NutUIResolver()
```
![css](https://github.com/jdf2e/nutui/assets/16473160/55d9bdf0-269b-4ac3-9bb8-655f1bcc775f)

sass方式引入也报错：
```
NutUIResolver({
  importStyle: 'sass'
})
```

![sass](https://github.com/jdf2e/nutui/assets/16473160/346ff8b2-d9b1-468e-8a34-6c239dead131)

### 环境信息

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.2.1
  npmPackages:
    @nutui/nutui: ^4.2.7 => 4.2.7 

windows和mac多台电脑，nodejs版本18都是同样的问题。

### 其他信息：
* nodejs: 18.19.0;
* Vue: 3.3.13；
* NutUI: 4.2.7;
* Vite: 4.5.1;
* "@nutui/auto-import-resolver": "^1.0.0";
* "unplugin-vue-components": "^0.25.2";

### 解决方法：
直接修改本地的@nutui/auto-import-resolver/dist/index.js文件第11行后，sass按需引入成功，改动如下：
```
if (importStyle === "sass") {
    - style = `${packageName}/dist/packages/${componentName.toLowerCase()}/style`;
    + style = `${packageName}/dist/packages/${componentName.toLowerCase()}/index.scss`;
  }
```

**Comment by eiinu** [comment]
运行重现链接中的项目，未复现问题。

![image](https://github.com/jdf2e/nutui/assets/44915689/2be85826-5d90-470f-a82c-94010a66f5d6)

**Comment by beautycss** [comment]
> 运行重现链接中的项目，未复现问题。
> 
> ![image](https://private-user-images.githubusercontent.com/44915689/296920160-2be85826-5d90-470f-a82c-94010a66f5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzUxNTAsIm5iZiI6MTcwNTM3NDg1MCwicGF0aCI6Ii80NDkxNTY4OS8yOTY5MjAxNjAtMmJlODU4MjYtNWQ5MC00NzBmLWE4MmMtOTQwMTBhNjZmNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlOGMzMjhlMGUwZmQzYWY4MTBlODEyOTc4NDA0MzY3NTUzNzAxMGEwODk3MGI0NGIwYmFmM2UyZmI3NzE3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f1qGbyABWyxz80td0b5dPbztKbB-cs3fi1fcpkeULOs)

![image](https://github.com/jdf2e/nutui/assets/16473160/a06f170e-b72e-416a-9684-29e5a4d5f0eb)

**Comment by eiinu** [comment]
> > 运行重现链接中的项目，未复现问题。
> > ![image](https://private-user-images.githubusercontent.com/44915689/296920160-2be85826-5d90-470f-a82c-94010a66f5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzUxNTAsIm5iZiI6MTcwNTM3NDg1MCwicGF0aCI6Ii80NDkxNTY4OS8yOTY5MjAxNjAtMmJlODU4MjYtNWQ5MC00NzBmLWE4MmMtOTQwMTBhNjZmNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlOGMzMjhlMGUwZmQzYWY4MTBlODEyOTc4NDA0MzY3NTUzNzAxMGEwODk3MGI0NGIwYmFmM2UyZmI3NzE3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f1qGbyABWyxz80td0b5dPbztKbB-cs3fi1fcpkeULOs)
> 
> ![image](https://private-user-images.githubusercontent.com/16473160/296921867-a06f170e-b72e-416a-9684-29e5a4d5f0eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzUyNjgsIm5iZiI6MTcwNTM3NDk2OCwicGF0aCI6Ii8xNjQ3MzE2MC8yOTY5MjE4NjctYTA2ZjE3MGUtYjcyZS00MTZhLTk2ODQtMjllNWE0ZDVmMGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MGQyOGUzZWRhMmE4YzM2Y2M3ZTZiNzRkZjI3NjI5Zjg0MTllODMwZmE4M2Q0NDhkZjk2NjM3MDllYTQ0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vb0j65W8Uz4BW-k3jg8RjAAqbQoJgd5gmQ1BIRWoW3I)

图上的错误是因为项目中没有安装 `unplugin-vue-components` 插件，与 issue 反馈的内容没有关系。

**Comment by beautycss** [comment]
1. vite4就是碰到这个问题，多个电脑上碰到过了。
2. 给的demo是vite5，版本不一样。

**Comment by eiinu** [comment]
> 1. vite4就是碰到这个问题，多个电脑上碰到过了。
> 2. 给的demo是vite5，版本不一样。

建议提供能复现的依赖版本都正确的 demo

**Comment by beautycss** [comment]
> > > 运行重现链接中的项目，未复现问题。
> > > ![image](https://private-user-images.githubusercontent.com/44915689/296920160-2be85826-5d90-470f-a82c-94010a66f5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzUxNTAsIm5iZiI6MTcwNTM3NDg1MCwicGF0aCI6Ii80NDkxNTY4OS8yOTY5MjAxNjAtMmJlODU4MjYtNWQ5MC00NzBmLWE4MmMtOTQwMTBhNjZmNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlOGMzMjhlMGUwZmQzYWY4MTBlODEyOTc4NDA0MzY3NTUzNzAxMGEwODk3MGI0NGIwYmFmM2UyZmI3NzE3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f1qGbyABWyxz80td0b5dPbztKbB-cs3fi1fcpkeULOs)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/16473160/296921867-a06f170e-b72e-416a-9684-29e5a4d5f0eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzUyNjgsIm5iZiI6MTcwNTM3NDk2OCwicGF0aCI6Ii8xNjQ3MzE2MC8yOTY5MjE4NjctYTA2ZjE3MGUtYjcyZS00MTZhLTk2ODQtMjllNWE0ZDVmMGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MGQyOGUzZWRhMmE4YzM2Y2M3ZTZiNzRkZjI3NjI5Zjg0MTllODMwZmE4M2Q0NDhkZjk2NjM3MDllYTQ0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vb0j65W8Uz4BW-k3jg8RjAAqbQoJgd5gmQ1BIRWoW3I)
> 
> 这是没安装 `unplugin-vue-components` 插件的报错。

1. codebox里没有`unplugin-vue-components/vite`这个包，选的一个其他的。
2. vite4就是碰到这个问题，多个电脑上碰到过了。
3. 给的demo是vite5，版本不一样。
4. 我是本着负责的态度提出来，本来之前评论了，又费了不少时间重新提交了issue。基于问题1，需要本地复现，其实问题也很简单，如果仅凭在线链接来判定，那不如直接关闭好了，我就当给其他碰到同样问题的人一个解决方法。

**Comment by eiinu** [comment]
> > > > 运行重现链接中的项目，未复现问题。
> > > > ![image](https://private-user-images.githubusercontent.com/44915689/296920160-2be85826-5d90-470f-a82c-94010a66f5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzUxNTAsIm5iZiI6MTcwNTM3NDg1MCwicGF0aCI6Ii80NDkxNTY4OS8yOTY5MjAxNjAtMmJlODU4MjYtNWQ5MC00NzBmLWE4MmMtOTQwMTBhNjZmNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlOGMzMjhlMGUwZmQzYWY4MTBlODEyOTc4NDA0MzY3NTUzNzAxMGEwODk3MGI0NGIwYmFmM2UyZmI3NzE3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f1qGbyABWyxz80td0b5dPbztKbB-cs3fi1fcpkeULOs)
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/16473160/296921867-a06f170e-b72e-416a-9684-29e5a4d5f0eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzUyNjgsIm5iZiI6MTcwNTM3NDk2OCwicGF0aCI6Ii8xNjQ3MzE2MC8yOTY5MjE4NjctYTA2ZjE3MGUtYjcyZS00MTZhLTk2ODQtMjllNWE0ZDVmMGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MGQyOGUzZWRhMmE4YzM2Y2M3ZTZiNzRkZjI3NjI5Zjg0MTllODMwZmE4M2Q0NDhkZjk2NjM3MDllYTQ0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vb0j65W8Uz4BW-k3jg8RjAAqbQoJgd5gmQ1BIRWoW3I)
> > 
> > 
> > 这是没安装 `unplugin-vue-components` 插件的报错。
> 
> 1. codebox里没有`unplugin-vue-components/vite`这个包，选的一个其他的。
> 2. vite4就是碰到这个问题，多个电脑上碰到过了。
> 3. 给的demo是vite5，版本不一样。
> 4. 我是本着负责的态度提出来，本来之前评论了，又费了不少时间重新提交了issue。基于问题1，需要本地复现，其实问题也很简单，如果仅凭在线链接来判定，那不如直接关闭好了，我就当给其他碰到同样问题的人一个解决方法。

1、这个插件的包名为 `unplugin-vue-components`，`unplugin-vue-component/vite` 只是该包的一个子模块。
2、提供最小可复现的作用，可以参考这里： [vuejs/core](https://github.com/vuejs/core/blob/main/.github/bug-repro-guidelines.md)。
3、在线链接并不是唯一的依据，在另一个 issue 里已回复过，**在本地测试过 vite4 版本，没有复现问题**。

不同项目里的配置可能是天差地别的，yarn/npm/pnpm、js/ts、vite/vue/unplugin 版本不同都会影响，甚至可能是 tsconfig 或者 vite 的哪个配置项出了问题。提供可复现的环境能直接避开这些差异，更快的解决问题。
