### ISSUE TITLE
datepicker 结束日期限制时 日期限制失败[bug]

### ISSUE THREAD

**Issue by xukaishan** [jdf2e/nutui#287]
datepicker 结束日期限制时 日期限制失败，年月限制正常，日期会全部出现，比如我限制到2020-06-24，结果会出现2020-06-30
<nut-datepicker 
      :is-visible="true"
      startDate="2020-06-01"
      end-date="2020-06-24"
      title="请选择日期" 
      type="date"
  />
npm 安装使用

**Comment by zjyau** [comment]
#284  限制范围已经修复过了，master没更新

**Comment by richard1015** [comment]
复现仓库
https://codesandbox.io/s/nutui-cnd-test-i5h1p?file=/index.html

**Comment by zjyau** [comment]
@richard1015 ，这个问题已经修复  #284  ，最新的DEV-2已经MERGED

**Comment by richard1015** [comment]
> @richard1015 ，这个问题已经修复 #284 ，最新的DEV-2已经MERGED

看到了，非常感谢，这两天会再发一版 更新到线上
