### ISSUE TITLE
自定义主题后，datepicker在ios真机场景下 样式错乱[bug]

### ISSUE THREAD

**Issue by xukaishan** [jdf2e/nutui#288]
npm 安装
datepicker 使用自定义主题时，模拟器及安卓样式不会出现错乱，IOS真机出现样式错误，已排除px2rem转换，vue.config也已正常配置

**Comment by richard1015** [comment]
参考 demo vue.config

https://github.com/jdf2e/nutui-demo/blob/master/base/vue.config.js
