### ISSUE TITLE
vertical方向的tabs，非第一个tab里包含nut-popup，弹出框永远在第一个tab里展示

### ISSUE THREAD

**Issue by zhusimei-magictavern-com** [jdf2e/nutui#2883]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.1.2

### 平台

h5

### 重现链接

无

### 重现步骤

1. <nut-tabs direction="vertical"，写一个tabs
2. 第二个tab的内容里有<nut-cell :title="`请选择${item.cnName}`" @click="item.show = true" class="custom-form-item"></nut-cell>
          <nut-popup
3. 弹框在第一个tab里展示

### 期望的结果是什么？

弹框在当前操作的tab 展示

### 实际的结果是什么？

弹框在第一个tab展示

**Comment by eiinu** [comment]
原因：fixed 定位（Popup）受到 transform 布局（TabPane）影响，css 设计如此。
方法1、将 Popup 放在 Tabs 外面
方法2、Tabs 设置 `animated-time="0"`，此时不使用 transform 布局，同时 TabPane 无切换动画

**Comment by zhusimei-magictavern-com** [comment]
我用方法2试了，popup我是第二个tab里做一个下拉的功能，拖动下拉的话又回到第一个tab，这个不是我想要的效果。

我试了popup里面配置teleport-disable :teleport="pickerId"，这个pickerId是外面的一个div的id，但是console里会报警
![image](https://github.com/jdf2e/nutui/assets/144194532/648c95a8-c96e-4c15-9faa-5d78e841126f)

**Comment by eiinu** [comment]
> 我用方法2试了，popup我是第二个tab里做一个下拉的功能，拖动下拉的话又回到第一个tab，这个不是我想要的效果。
> 
> 我试了popup里面配置teleport-disable :teleport="pickerId"，这个pickerId是外面的一个div的id，但是console里会报警
> ![image](https://github.com/jdf2e/nutui/assets/144194532/648c95a8-c96e-4c15-9faa-5d78e841126f)
> 

Popup 的 teleport 属性会传给 vue Teleport 元素的 to 属性。
你这个是代码语法有问题。

**Comment by zhusimei-magictavern-com** [comment]
> > 我用方法2试了，popup我是第二个tab里做一个下拉的功能，拖动下拉的话又回到第一个tab，这个不是我想要的效果。
> > 我试了popup里面配置teleport-disable :teleport="pickerId"，这个pickerId是外面的一个div的id，但是console里会报警
> > ![image](https://private-user-images.githubusercontent.com/144194532/299873110-648c95a8-c96e-4c15-9faa-5d78e841126f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTQyODQsIm5iZiI6MTcwNjI1Mzk4NCwicGF0aCI6Ii8xNDQxOTQ1MzIvMjk5ODczMTEwLTY0OGM5NWE4LWM5NmUtNGMxNS05ZmFhLTVkNzhlODQxMTI2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQwNzI2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzljNzQyMDdkNjBjMzA3OWFmMWYzMzcxMGViMjE1YzZmMjA5OGZjMDhkMDE0ZTVjNzM1MzFhYzNhNTg4NGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mijZ8KBeA2sXrvDPttYpIW-VskMgwBTJEgOJxXAyNGs)
> 
> Popup 的 teleport 属性会传给 vue Teleport 元素的 to 属性。 你这个是代码语法有问题。


外面div id ="toolBasicForm"
1. teleport-disable :teleport="toolBasicForm" 效果可以实现，就是console告警
2. teleport-disable teleport="#toolBasicForm" 直接报错
 
![image](https://github.com/jdf2e/nutui/assets/144194532/754f74dd-e0cf-4843-ac13-4f9511455ef4)

**Comment by eiinu** [comment]
Popup Teleport 属性接收的应该是 CSS 选择器或者DOM元素，参考 [vue/teleport](https://cn.vuejs.org/guide/built-ins/teleport.html#basic-usage)。

1、是语法错误，当前文件内存在 toolBasicForm 这个变量吗？不存在，所以 console 告警变量未定义。
效果并没有真正实现，只是挂载到了 Popup 的 teleport 属性默认值 `body` 上面，可以审查元素确认一下最终的 dom 元素位置。
2、是 vue 内部抛出的错误，主要原因是选择的目标元素 `#toolBasicForm` 并不合适，vue 文档中有相应的说明：

> Teleport 挂载时，传送的 to 目标必须已经存在于 DOM 中。理想情况下，这应该是整个 Vue 应用 DOM 树外部的一个元素。如果目标元素也是由 Vue 渲染的，你需要确保在挂载 Teleport 之前先挂载该元素。

**Comment by 100cm** [comment]
没解决就关闭了？在TARO 中存在一样的问题。
