### ISSUE TITLE
icons-vue-taro icon 不显示

### ISSUE THREAD

**Issue by 501956430** [jdf2e/nutui#2894]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.2.5

### 平台

tt

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbi8vaW1wb3J0IHsgSWNvbkZvbnQgfSBmcm9tICdAbnV0dWkvaWNvbnMtdnVlLXRhcm8nO1xuICBjb25zdCBzaG93ID0gcmVmKGZhbHNlKTtcbjwvc2NyaXB0PlxuPHRlbXBsYXRlPlxuICBcbiAgPG51dC1jZWxsIHRpdGxlPVwi5ZyG6KeS5by55qGGXCIgaXMtbGluayBAdGFwPVwic2hvdyA9IHRydWVcIj48L251dC1jZWxsPlxuICAgICAgPG51dC1wb3B1cCBwb3NpdGlvbj1cImJvdHRvbVwiIGNsb3NlYWJsZSByb3VuZCA6c3R5bGU9XCJ7IGhlaWdodDogJzMwJScgfVwiIHYtbW9kZWw6dmlzaWJsZT1cInNob3dcIj48L251dC1wb3B1cD5cbiAgXG48L3RlbXBsYXRlPiJ9

### 重现步骤

点击圆角弹框，显示Popup 弹窗

### 期望的结果是什么？

Popup 弹窗右边显示关闭按钮icon

### 实际的结果是什么？

Popup 弹窗未显示关闭按钮icon

### 环境信息

Taro CLI 3.6.19 environment info:
    System:
      OS: macOS 12.7.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.8.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.19 => 3.6.19 
      @tarojs/components: 3.6.19 => 3.6.19 
      @tarojs/helper: 3.6.19 => 3.6.19 
      @tarojs/plugin-framework-vue3: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-alipay: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-h5: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-jd: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-qq: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-swan: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-tt: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-weapp: 3.6.19 => 3.6.19 
      @tarojs/plugin-vue-devtools: ^3.6.21 => 3.6.21 
      @tarojs/runtime: 3.6.19 => 3.6.19 
      @tarojs/shared: 3.6.19 => 3.6.19 
      @tarojs/taro: 3.6.19 => 3.6.19 
      @tarojs/taro-loader: 3.6.19 => 3.6.19 
      @tarojs/webpack5-runner: 3.6.19 => 3.6.19 
      babel-preset-taro: 3.6.19 => 3.6.19 
      eslint-config-taro: 3.6.19 => 3.6.19

**Comment by eiinu** [comment]
<img width="407" alt="image" src="https://github.com/jdf2e/nutui/assets/44915689/cbbc277b-3e5f-4069-af0d-c29653c1b751">
无法复现，建议提供完整的最小可复现 demo。

**Comment by 501956430** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 501956430** [comment]
[myApp的副本.zip](https://github.com/jdf2e/nutui/files/14087184/myApp.zip)
@eiinu 附件demo detail.vue 组件

**Comment by eiinu** [comment]
参考文档[快速上手](https://nutui.jd.com/taro/vue/4x/#/zh-CN/guide/start)。
`@tarojs/plugin-html` 插件是不可缺少的。

**Comment by 501956430** [comment]
@eiinu  刚刚安装了该插件 然而icon依然不显示

**Comment by 501956430** [comment]
<img width="326" alt="截屏2024-01-30 01 00 15" src="https://github.com/jdf2e/nutui/assets/20204491/a37e81a3-f56d-4b73-8103-ac9d5dda9199">
效果

**Comment by 501956430** [comment]
有一个步骤忘记加了， 开启@tarojs/plugin-html插件 我在试试

**Comment by eiinu** [comment]
> <img alt="截屏2024-01-30 01 00 15" width="326" src="https://private-user-images.githubusercontent.com/20204491/300543451-a37e81a3-f56d-4b73-8103-ac9d5dda9199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODIxMjQsIm5iZiI6MTcwNjU4MTgyNCwicGF0aCI6Ii8yMDIwNDQ5MS8zMDA1NDM0NTEtYTM3ZTgxYTMtZjU2ZC00YjczLTgxMDMtYWM5ZDVkZGE5MTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAyMzAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMWNlNjc3NmNiNDBkNjljNzZhM2YwYjI5ZjA5Yjc2ZWEzZmVhOGI4MzY2NzVmYzZlZDc3OGQxZTlhMWJjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CPNAXmwaYJArjpMfCabBIkn33DPzblAwSugv6QtnLe4"> 效果

这张图上还有一个问题，designWidth 的部分需要按照文档修改一下，NutUI 的设计尺寸是 375

**Comment by 501956430** [comment]
@eiinu designWidth 已经参考文档修改了。
安装完plugin-html 插件并配置好，问题已解决 感谢🙏
