### ISSUE TITLE
按需加载报错

### ISSUE THREAD

**Issue by chix1221** [jdf2e/nutui#29]
按照文档操作，按需加载对应组件报错
`Cannot read property 'install' of undefined`

**Comment by Franslee** [comment]
安装@nutui/babel-plugin-separate-import插件了吗？

**Comment by chix1221** [comment]
可以了，又碰到新的问题就是动态改变列:span的值不能class="nut-col nut-col-12" class不变，是发邮件给你了，是你们自身机制问题还是什么？麻烦解决一下  急急急！！！

**Comment by Franslee** [comment]
已安排组件作者改进，请关注下一个版本

**Comment by hapiman** [comment]
当前使用下面这种方式报错: `Cannot read property 'install' of undefined`
```js
import Mutui from '@nutui/nutui';
Mutui.Dialog.install(Vue);
Mutui.Picker.install(Vue);
```
我当前使用的是`https://cli.vuejs.org/zh/guide/`生成的项目,
在`vue.config.js`配置如下:
```js
module.exports = {
  configureWebpack: {
    plugins: [
      ["@nutui/babel-plugin-separate-import", {
        "style": "scss"
      }]
    ]
  }
}
```
然而好想并没用什么作用,
当使用`Object.keys(Mutui)`时,输出下面的
![image](https://user-images.githubusercontent.com/7567048/56726491-73a2c500-6781-11e9-8812-4876cfb0dab9.png)

**Comment by Franslee** [comment]
@hapiman 
@nutui/babel-plugin-separate-import 是Babel的插件不是webpack插件，需要在Babel的配置文件（如.babelrc）中配置

**Comment by hapiman** [comment]
> @hapiman
> @nutui/babel-plugin-separate-import 是Babel的插件不是webpack插件，需要在Babel的配置文件（如.babelrc）中配置

ok. Solved, thanks
