### ISSUE TITLE
同时有多个swiper，懒加载失效的问题[bug]

### ISSUE THREAD

**Issue by carpenterzoe** [jdf2e/nutui#290]
## 问题描述
当同一个页面存在多个swiper 同时加载的时候，使用懒加载会失效。所有的图片资源都一次性被加载了。
只有单个页面中仅仅存在一个swiper，懒加载才有效。

**Comment by carpenterzoe** [comment]
PS. swiper组件我二次封装处理了样式，这里同个页面存在多个swipe的情况r，调用的是同一个nut-swiper。

**Comment by richard1015** [comment]
是否可以提供一个 最小可复现仓库
