### ISSUE TITLE
AvatarCropper 头像裁剪组件IOS真机,选中图片会把工具栏覆盖完全遮挡

### ISSUE THREAD

**Issue by ltcwan995** [jdf2e/nutui#2904]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.0.4

### 平台

h5, weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IERvbmdkb25nIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcbiAgaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJztcbmltcG9ydCBUYXJvIGZyb20gJ0B0YXJvanMvdGFybydcbmNvbnN0IHNob3cgPSAoKSA9PiB7XG4gIHNob3dUb2FzdC50ZXh0KCdIZWxsbywgTnV0VUkhJylcbn07XG4gIGNvbnN0IGltYWdlVXJsID0gcmVmKCcnKTtcbmNvbnN0IGF2YXRhckNyb3BwZXJSZWYgPSByZWYoKTtcbiAgY29uc3QgY29uZmlybSA9ICh1cmw6IHN0cmluZykgPT4ge1xuICBpbWFnZVVybC52YWx1ZSA9IHVybDtcbn07XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC1zcGFjZT5cblx0XHQgIDxudXQtYXZhdGFyLWNyb3BwZXIgcmVmPVwiYXZhdGFyQ3JvcHBlclJlZlwiIHNoYXBlPVwic3F1YXJlXCIgQGNvbmZpcm09XCJjb25maXJtXCI+XG5cdFx0XHQ8bnV0LWF2YXRhciBzaXplPVwibGFyZ2VcIiBzaGFwZT1cInNxdWFyZVwiPlxuXHRcdFx0ICA8aW1nIHN0eWxlPVwid2lkdGg6IDEwMHB4O2hlaWdodDogMTAwcHg7XCIgdi1pZj1cImltYWdlVXJsXCIgOnNyYz1cImltYWdlVXJsXCIgLz5cblx0XHRcdDwvbnV0LWF2YXRhcj5cblx0XHRcdDx0ZW1wbGF0ZSAjdG9vbGJhcj5cblx0XHRcdFx0PGRpdiBjbGFzcz1cImRlbW8tdG9vbGJhclwiPlxuXHRcdFx0XHQgIDxudXQtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwiYXZhdGFyQ3JvcHBlclJlZi5jYW5jZWwoKVwiPuWPlua2iDwvbnV0LWJ1dHRvbj5cblx0XHRcdFx0ICA8bnV0LWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImF2YXRhckNyb3BwZXJSZWYucmVzZXQoKVwiPumHjee9rjwvbnV0LWJ1dHRvbj5cblx0XHRcdFx0ICA8bnV0LWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImF2YXRhckNyb3BwZXJSZWYucm90YXRlKClcIj7ml4vovaw8L251dC1idXR0b24+XG5cdFx0XHRcdCAgPG51dC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJhdmF0YXJDcm9wcGVyUmVmLmNvbmZpcm0oKVwiPuehruiupDwvbnV0LWJ1dHRvbj5cblx0XHRcdFx0PC9kaXY+XG5cdFx0XHQ8L3RlbXBsYXRlPlxuXHRcdCAgPC9udXQtYXZhdGFyLWNyb3BwZXI+XG5cdCAgPC9udXQtc3BhY2U+XG48L3RlbXBsYXRlPiJ9

### 重现步骤

AvatarCropper 头像裁剪,真机测试图片会完全覆盖遮挡工具栏

### 期望的结果是什么？

AvatarCropper 头像裁剪,真机测试图片区域能够正常展示,修改移动图片位置

### 实际的结果是什么？

AvatarCropper 头像裁剪,真机测试图片区域不能够正常展示,修改移动图片位置无法操作
![fafb582ef61e2d4588eab4e9c4a6d3a](https://github.com/jdf2e/nutui/assets/20805254/f95d56f9-fca2-4c11-9d10-1b31bc5311d0)
![8a8cf24ecea33480db6a67a304a76aa](https://github.com/jdf2e/nutui/assets/20805254/b7836429-1540-49ec-a4c0-9ef02fffd63a)

**Comment by yi-boide** [comment]
安卓设备正常，目前手上没有ios设备，无法模拟

**Comment by yi-boide** [comment]
我借同事手机访问看了下，并没有你所说的情况出现，下方的编辑栏也都在。
![image](https://github.com/jdf2e/nutui/assets/63292605/f21b1768-e6d1-4b7e-85dc-658e2e82a731)

**Comment by yi-boide** [comment]
无论是h5还是小程序，都适用iphone手机测试了下，都没有这些问题，能够正常使用。
![image](https://github.com/jdf2e/nutui/assets/63292605/e5d6fc94-22c6-47f7-a0e3-c257b0d7363d)

**Comment by yi-boide** [comment]
请等待nutui版本4.3.0的发布，更新到这个版本就能正常使用了。

**Comment by ltcwan995** [comment]
> 无论是h5还是小程序，都适用iphone手机测试了下，都没有这些问题，能够正常使用。 ![image](https://private-user-images.githubusercontent.com/63292605/301077931-e5d6fc94-22c6-47f7-a0e3-c257b0d7363d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODcyNjYsIm5iZiI6MTcwNjY4Njk2NiwicGF0aCI6Ii82MzI5MjYwNS8zMDEwNzc5MzEtZTVkNmZjOTQtMjJjNi00N2Y3LWEwZTMtYzI1N2IwZDczNjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA3NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDI2YmY1Y2Q3NWRkNWYyYWFkNDk5OGU2YzE1MzY4NmEzNzcxNWZhZTk5ZWFhYTFlN2ExYjNlYzU5MjVlZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3IwXFgeky9_7qUeEtBTw8Dg4brrfjMJRObA_LjB_Wd4)


https://github.com/jdf2e/nutui/assets/20805254/de6a4acb-8afe-4056-85b9-7cc8a5f212fc

大概这样子的情况,按钮被图片遮住无法操作

**Comment by yi-boide** [comment]
这个需要等4.3.0发布，之前版本确实有这个问题#2865 
修复代码已经合并到了主分支，你还可以拉取主分支代码，本地打包后，使用打包后的本地包，而不是用npm里面的包。

**Comment by ltcwan995** [comment]
> 这个需要等4.3.0发布，之前版本确实有这个问题#2865

好的,谢谢!

**Comment by yi-boide** [comment]
#2865
