### ISSUE TITLE
Uploader在h5端不能上传pdf，excel等文件，只能上传图标类型文件

### ISSUE THREAD

**Issue by myby7000p** [jdf2e/nutui#2906]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.2.9

### 平台

h5

### 重现链接

https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/uploader

### 重现步骤

h5端使用Uploader这个组件

### 期望的结果是什么？

可以上传pdf，excel等类型文件

### 实际的结果是什么？

不能上传pdf，excel等类型文件

**Comment by babalrlr** [comment]
请问这个问题解决了吗？

**Comment by myby7000p** [comment]
> 请问这个问题解决了吗？

nutui没有解决，我用了别的组件库

**Comment by babalrlr** [comment]
好的，感谢
