### ISSUE TITLE
nut-input 会出现不显示输入框！

### ISSUE THREAD

**Issue by 501956430** [jdf2e/nutui#2909]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.2.5

### 平台

tt

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IERvbmdkb25nIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcbmNvbnN0IHNob3cgPSAoKSA9PiB7XG4gIHNob3dUb2FzdC50ZXh0KCdIZWxsbywgTnV0VUkhJylcbn07XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPHZpZXc+MTIzPC92aWV3PlxuICA8bnV0LWlucHV0IGNsYXNzPVwibnV0LWlucHV0LXRleHRcIiBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpVwiIG1vZGVsLXZhbHVlPVwi6K+36L6T5YWlXCI+PC9udXQtaW5wdXQ+XG4gICAgXG48L3RlbXBsYXRlPiJ9

### 重现步骤

不显示input输入框标签，源码也没渲染出input标签

### 期望的结果是什么？

显示输入框

### 实际的结果是什么？

未显示输入框

### 环境信息

Taro CLI 3.6.19 environment info:
    System:
      OS: macOS 12.7.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.19 => 3.6.19 
      @tarojs/components: 3.6.19 => 3.6.19 
      @tarojs/helper: 3.6.19 => 3.6.19 
      @tarojs/plugin-framework-vue3: 3.6.19 => 3.6.19 
      @tarojs/plugin-html: ^3.6.23 => 3.6.23 
      @tarojs/plugin-platform-alipay: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-h5: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-jd: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-qq: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-swan: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-tt: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-weapp: 3.6.19 => 3.6.19 
      @tarojs/plugin-vue-devtools: ^3.6.21 => 3.6.21 
      @tarojs/runtime: 3.6.19 => 3.6.19 
      @tarojs/shared: 3.6.19 => 3.6.19 
      @tarojs/taro: 3.6.19 => 3.6.19 
      @tarojs/taro-loader: 3.6.19 => 3.6.19 
      @tarojs/webpack5-runner: 3.6.19 => 3.6.19 
      babel-preset-taro: 3.6.19 => 3.6.19 
      eslint-config-taro: 3.6.19 => 3.6.19

**Comment by 501956430** [comment]
正常情况显示：
<img width="314" alt="截屏2024-02-01 16 36 31" src="https://github.com/jdf2e/nutui/assets/20204491/74fbf2ab-7906-43c5-8a38-5d63fcac8163">

**Comment by 501956430** [comment]
不显示输入框：<img width="319" alt="截屏2024-02-01 20 14 19" src="https://github.com/jdf2e/nutui/assets/20204491/0ac7986e-09ff-4d90-87ea-d5144af4a7b2">

**Comment by eiinu** [comment]
`@tarojs/plugin-html` 插件的版本不正确，所有 taro 包的版本应该保持一致。

**Comment by 501956430** [comment]
@eiinu 好的，我调整下插件版本保持一致，难怪时不时出现不显示情况

**Comment by 501956430** [comment]
Taro CLI 3.6.19 environment info:
System:
OS: macOS 12.7.2
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 20.11.0 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 10.2.4 - /usr/local/bin/npm
npmPackages:
@tarojs/cli: 3.6.19 => 3.6.19
@tarojs/components: 3.6.19 => 3.6.19
@tarojs/helper: 3.6.19 => 3.6.19
@tarojs/plugin-framework-vue3: 3.6.19 => 3.6.19
@tarojs/plugin-html: 3.6.19 => 3.6.23
@tarojs/plugin-platform-alipay: 3.6.19 => 3.6.19
@tarojs/plugin-platform-h5: 3.6.19 => 3.6.19
@tarojs/plugin-platform-jd: 3.6.19 => 3.6.19
@tarojs/plugin-platform-qq: 3.6.19 => 3.6.19
@tarojs/plugin-platform-swan: 3.6.19 => 3.6.19
@tarojs/plugin-platform-tt: 3.6.19 => 3.6.19
@tarojs/plugin-platform-weapp: 3.6.19 => 3.6.19
@tarojs/plugin-vue-devtools: ^3.6.21 => 3.6.21
@tarojs/runtime: 3.6.19 => 3.6.19
@tarojs/shared: 3.6.19 => 3.6.19
@tarojs/taro: 3.6.19 => 3.6.19
@tarojs/taro-loader: 3.6.19 => 3.6.19
@tarojs/webpack5-runner: 3.6.19 => 3.6.19
babel-preset-taro: 3.6.19 => 3.6.19
eslint-config-taro: 3.6.19 => 3.6.19

代码编译后 时不时还是会出现input不显示问题。
1、编译后，小程序开发工具预览 nut-input不显示输入框，真机预览也不显示，必须重复一次或多次编译/打包代码：npm run tt 或 npm build tt，重新预览小程序才可能恢复正常。
2、编译后，小程序开发工具预览 nut-input显示输入框，真机预览不显示，一旦出现不显示，重启真机小程序即可恢复正常，但是一旦出现会影响直接使用。

使用input标签则不存在上述现象。

请教下我应该如何排除这样的不稳定现象！

**Comment by eiinu** [comment]
<img width="412" alt="image" src="https://github.com/jdf2e/nutui/assets/44915689/1cff6b52-21fa-4550-8271-f76ac2ad4a0d">

依然没有解决之前说过的问题，你先确保使用的所有版本号都一致吧……

**Comment by 501956430** [comment]
最新环境：
Taro CLI 3.6.19 environment info:
    System:
      OS: macOS 12.7.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.19 => 3.6.19 
      @tarojs/components: 3.6.19 => 3.6.19 
      @tarojs/helper: 3.6.19 => 3.6.19 
      @tarojs/plugin-framework-vue3: 3.6.19 => 3.6.19 
      @tarojs/plugin-html: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-alipay: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-h5: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-jd: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-qq: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-swan: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-tt: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-weapp: 3.6.19 => 3.6.19 
      @tarojs/plugin-vue-devtools: 3.6.19 => 3.6.19 
      @tarojs/runtime: 3.6.19 => 3.6.19 
      @tarojs/shared: 3.6.19 => 3.6.19 
      @tarojs/taro: 3.6.19 => 3.6.19 
      @tarojs/taro-loader: 3.6.19 => 3.6.19 
      @tarojs/webpack5-runner: 3.6.19 => 3.6.19 
      babel-preset-taro: 3.6.19 => 3.6.19 
      eslint-config-taro: 3.6.19 => 3.6.19 

这几天使用的版本环境开发，问题依然存在，问题出现的方式是： 偶现，时不时的。
当问题出现时，必须得重新编译1次或2次代码，问题就没有了

**Comment by eiinu** [comment]
找不到模板&组件无法显示的问题：
除了 Taro 相关包版本号需要保持一致以外，还有可能是开启了 prebundle 导致的，参考 https://github.com/jdf2e/nutui/issues/2461#issuecomment-1655316373

**Comment by 501956430** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
