### ISSUE TITLE
ios / Android App环境下Actionsheet和Popup(2.2.6版本ios下可以)的遮罩层无法锁定背景滚动

### ISSUE THREAD

**Issue by chen978000** [jdf2e/nutui#291]
## 问题描述

**ios / Android App环境下Actionsheet和Popup(2.2.6版本ios下可以)的遮罩层无法锁定背景滚动**

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
官方demo

## 预期的行为和实际行为
希望锁定背景滚动行为

## 相关环境信息
- **操作系统**：
app内嵌webview环境下访问

- **Node 版本**：
未使用

- **NutUI 版本**：
2.2.6

- **Vue 版本**：
2.x

- **引用方式**：  CDN / NPM ？
CDN

**Comment by richard1015** [comment]
等待 v2.2.7 进行测试，  下周发版

**Comment by richard1015** [comment]
升级 v2.2.7 测试一下看看
