### ISSUE TITLE
在v-for中使用nut-swipe时，右滑删除中间的某一个nut-swipe（使用splice或filter移除），被删除的nut-swipe下一个会变为右滑状态

### ISSUE THREAD

**Issue by ql2023** [jdf2e/nutui#2911]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.2.9

### 平台

h5

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIlxuY29uc3QgYXJyYXkgPSByZWYoW1wiYVwiLCBcImJcIiwgXCJjXCJdKVxuY29uc3QgZGVsID0gKGl0KSA9PiB7XG4gIGNvbnN0IGluZGV4ID0gYXJyYXkudmFsdWUuaW5kZXhPZihpdCk7XG4gIGFycmF5LnZhbHVlLnNwbGljZShpbmRleCwgMSk7XG59XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC1zd2lwZSB2LWZvcj1cIml0IGluIGFycmF5XCI+XG4gICAgPG51dC1jZWxsIHJvdW5kLXJhZGl1cz1cIjBcIiA6dGl0bGU9XCJgU3dpcGUgTGVmdCAtLS0tJHtpdH1gXCIgLz5cbiAgICA8dGVtcGxhdGUgI3JpZ2h0PlxuICAgICAgPG51dC1idXR0b24gc2hhcGU9XCJzcXVhcmVcIiBzdHlsZT1cImhlaWdodDogMTAwJVwiIHR5cGU9XCJkYW5nZXJcIiBAY2xpY2s9XCJkZWwoaXQpXCI+5Yig6ZmkPC9udXQtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvbnV0LXN3aXBlPlxuPC90ZW1wbGF0ZT4ifQ==

### 重现步骤

```vue
<script setup>
import { ref } from "vue"
const array = ref(["a", "b", "c"])
const del = (it) => {
  const index = array.value.indexOf(it);
  array.value.splice(index, 1);
}
</script>
<template>
  <nut-swipe v-for="it in array">
    <nut-cell round-radius="0" :title="`Swipe Left ----${it}`" />
    <template #right>
      <nut-button shape="square" style="height: 100%" type="danger" @click="del(it)">删除</nut-button>
    </template>
  </nut-swipe>
</template>
```

### 期望的结果是什么？

被删除的下一个nut-swipe不应该为右滑状态

### 实际的结果是什么？

被删除的下一个nut-swipe右滑状态

**Comment by eiinu** [comment]
https://cn.vuejs.org/guide/essentials/list.html#maintaining-state-with-key
