### ISSUE TITLE
使用官网Dialog 对话框 例子代码在本地未显示按钮

### ISSUE THREAD

**Issue by 501956430** [jdf2e/nutui#2912]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.2.5

### 平台

tt

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IERvbmdkb25nIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcbiAgY29uc3QgdmlzaWJsZTM9cmVmKGZhbHNlKTtcbmNvbnN0IHNob3cgPSAoKSA9PiB7XG4gIHNob3dUb2FzdC50ZXh0KCdIZWxsbywgTnV0VUkhJylcbn07XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC1kaWFsb2dcbiAgICBuby1jYW5jZWwtYnRuXG4gICAgdGl0bGU9XCLmuKnppqjmj5DnpLpcIlxuICAgIGNvbnRlbnQ9XCLov5nmmK/mj5DnpLrlvLnmoYbjgIJcIlxuICAgIHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGUzXCJcbiAgICBAb2s9XCJvbk9rXCJcbiAgLz5cbjwvdGVtcGxhdGU+In0=

### 重现步骤

使用官网的例子，在本地使用中，不显示确认按钮

### 期望的结果是什么？

应该正常显示确认按钮

### 实际的结果是什么？

没有显示确认按钮

**Comment by 501956430** [comment]
<img width="309" alt="截屏2024-02-02 17 06 57" src="https://github.com/jdf2e/nutui/assets/20204491/abd76895-d91c-4758-97d2-8c3108767b4c">
未显示按钮

**Comment by 501956430** [comment]
`<nut-dialog
    no-cancel-btn
    title="温馨提示"
    content="这是提示弹框。"
    v-model:visible="visible3"
    @ok="onOk"
  />`
就这一行代码，官网的例子

**Comment by 501956430** [comment]
<img width="417" alt="截屏2024-02-02 17 14 05" src="https://github.com/jdf2e/nutui/assets/20204491/b83d38d8-2de5-4870-bff3-2c2a07f34cfd">
官网的例子

**Comment by 501956430** [comment]
环境信息：
 Taro CLI 3.6.19 environment info:
    System:
      OS: macOS 12.7.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.19 => 3.6.19 
      @tarojs/components: 3.6.19 => 3.6.19 
      @tarojs/helper: 3.6.19 => 3.6.19 
      @tarojs/plugin-framework-vue3: 3.6.19 => 3.6.19 
      @tarojs/plugin-html: ^3.6.19 => 3.6.23 
      @tarojs/plugin-platform-alipay: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-h5: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-jd: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-qq: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-swan: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-tt: 3.6.19 => 3.6.19 
      @tarojs/plugin-platform-weapp: 3.6.19 => 3.6.19 
      @tarojs/plugin-vue-devtools: ^3.6.21 => 3.6.21 
      @tarojs/runtime: 3.6.19 => 3.6.19 
      @tarojs/shared: 3.6.19 => 3.6.19 
      @tarojs/taro: 3.6.19 => 3.6.19 
      @tarojs/taro-loader: 3.6.19 => 3.6.19 
      @tarojs/webpack5-runner: 3.6.19 => 3.6.19 
      babel-preset-taro: 3.6.19 => 3.6.19 
      eslint-config-taro: 3.6.19 => 3.6.19

**Comment by eiinu** [comment]
https://github.com/jdf2e/nutui/issues/2909

`@tarojs/plugin-html` 的实际安装版本还是不正确的，应该把 `^3.6.19` 改为 `3.6.19` 后重新安装依赖。
