### ISSUE TITLE
[bug] nutui address 点击左上角异常

### ISSUE THREAD

**Issue by sanheng** [jdf2e/nutui#292]
## 问题描述

![ezgif-6-d39befed0519](https://user-images.githubusercontent.com/13793256/86688314-904eb400-c038-11ea-98bc-2157142612a7.gif)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

https://nutui.jd.com/demo.html#/address?ver=2.2.6

## 预期的行为和实际行为
选择了地址之后，点击左上角表现异常

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
v2.2.7 已修复
