### ISSUE TITLE
Navbar 头部导航 顶部安全距离不够

### ISSUE THREAD

**Issue by Astrsea** [jdf2e/nutui#2928]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.0.4

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IERvbmdkb25nIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcbmNvbnN0IHNob3cgPSAoKSA9PiB7XG4gIHNob3dUb2FzdC50ZXh0KCdIZWxsbywgTnV0VUkhJylcbn07XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgICA8bnV0LW5hdmJhciBmaXhlZCBib3JkZXIgc2FmZS1hcmVhLWluc2V0LXRvcCBwbGFjZWhvbGRlciBAb24tY2xpY2stYmFjaz1cImNsaWNrQmFja1wiIEBvbi1jbGljay10aXRsZT1cImNsaWNrVGl0bGVcIiBAb24tY2xpY2stcmlnaHQ9XCJyaWdodENsaWNrXCIgOnRpdGxlPVwibmF2YmFyVGl0bGVcIj5cbiAgICAgIDx0ZW1wbGF0ZSB2LWlmPVwiIXByb3BzLm5lZWRUYWJiYXJcIiAjbGVmdD5cbiAgICAgICAgPGRpdj7ov5Tlm548L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9udXQtbmF2YmFyPlxuPC90ZW1wbGF0ZT4ifQ==

### 重现步骤

` <nut-navbar fixed border safe-area-inset-top placeholder @on-click-back="clickBack" @on-click-title="clickTitle" @on-click-right="rightClick" :title="navbarTitle">
      <template v-if="!props.needTabbar" #left>
        <div>返回</div>
      </template>
    </nut-navbar> `
关闭默认头部导航，调用nut-navbar组件

### 期望的结果是什么？

运行在小程序里顶部文字与顶部会有个安全距离，并将文字展示出来
<img width="340" alt="image" src="https://github.com/jdf2e/nutui/assets/134401374/7c784b42-dceb-4143-8c4b-bd9ea3c7fbae">

### 实际的结果是什么？

苹果安全距离不够，文字展示不出来
<img width="333" alt="屏幕截图 2024-02-19 223406" src="https://github.com/jdf2e/nutui/assets/134401374/e2926411-feca-4833-b468-44e37c929d05">
<img width="1173" alt="屏幕截图 2024-02-21 112819" src="https://github.com/jdf2e/nutui/assets/134401374/82c16478-de99-4083-9f2e-806139bf2bc5">
安卓的安全距离也有些问题，距离顶部靠太近
<img width="332" alt="image" src="https://github.com/jdf2e/nutui/assets/134401374/f4917252-39f1-4c0d-9d5c-c8064e8650b4">

**Comment by eiinu** [comment]
NutNavbar 的安全区指的是 iOS 安全区，样式代码只在 iOS 下的浏览器会生效。
与微信小程序的自定义头部没有关联。
