### ISSUE TITLE
Range区间选择器滑动异常

### ISSUE THREAD

**Issue by l-ll** [jdf2e/nutui#293]
## 问题描述
Range区间选择器页面显示标签文字例子中，点击或者按住左侧range滑动时会超出屏幕左侧

## 最小可复现仓库
> 官方demo [https://nutui.jd.com/demo.html#/Range](https://nutui.jd.com/demo.html#/Range)

## 预期的行为和实际行为
该页面其他例子正常

## 复现步骤，具体代码
手机浏览器按住滑动或鼠标拖动均能复现

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by undo03** [comment]
已修复
