### ISSUE TITLE
vue3 AvatarCropper小程序报错 TypeError: Cannot read property 'node' of null

### ISSUE THREAD

**Issue by yangyingbiao** [jdf2e/nutui#2931]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.0

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LWF2YXRhci1jcm9wcGVyIHNoYXBlPVwic3F1YXJlXCIgQGNvbmZpcm09XCJjb25maXJtXCI+XG4gICAgICA8bnV0LWF2YXRhciBzaXplPVwibGFyZ2VcIiBzaGFwZT1cInNxdWFyZVwiPlxuICAgICAgICAgIDxpbWcgdi1pZj1cImltYWdlVXJsXCIgOnNyYz1cImltYWdlVXJsXCIgLz5cbiAgICAgIDwvbnV0LWF2YXRhcj5cbiAgPC9udXQtYXZhdGFyLWNyb3BwZXI+XG48L3RlbXBsYXRlPiJ9

### 重现步骤

<nut-avatar-cropper shape="square" @confirm="confirm">
      <nut-avatar size="large" shape="square">
          <img v-if="imageUrl" :src="imageUrl" />
      </nut-avatar>
  </nut-avatar-cropper>

### 期望的结果是什么？

正常使用

### 实际的结果是什么？

TypeError: Cannot read property 'node' of null
    at Object.<anonymous> (._node_modules_.pnpm_@nutui+nutui-taro@4.3.0_unplugin-vue-components@0.23.0_vue@3.4.19_node_modules_@nutui_nutui-taro_dist_packages_avatarcropper_AvatarCropper.js:183)
    at Function.<anonymous> (WAServiceMainContext.js?t=wechat&s=1708735279343&v=3.3.4:1)
    at :30069/appservice/<SelectorQuery callback function>
    at WAServiceMainContext.js?t=wechat&s=1708735279343&v=3.3.4:1
    at WAServiceMainContext.js?t=wechat&s=1708735279343&v=3.3.4:1
    at Array.forEach (<anonymous>)
    at WAServiceMainContext.js?t=wechat&s=1708735279343&v=3.3.4:1
    at WAServiceMainContext.js?t=wechat&s=1708735279343&v=3.3.4:1
    at WASubContext.js?t=wechat&s=1708735279343&v=3.3.4:1
    at ve (WASubContext.js?t=wechat&s=1708735279343&v=3.3.4:1)(env: Windows,mp,1.06.2306020; lib: 3.3.4)

useReady(() => {
      if (showCanvas2D.value) {
        const { canvasId } = canvasAll;
        Taro.createSelectorQuery().select(`#${canvasId}`).node(({ node: canvas }) => {
          canvas.width = state.displayWidth;
          canvas.height = state.displayHeight;
          canvasAll.cropperCanvas = canvas;
        }).exec();
      }
    });

### 环境信息

"@tarojs/taro": "3.6.5",
"@nutui/nutui-taro": "^4.3.0",

### 其他补充信息

node

**Comment by yangyingbiao** [comment]
是微信小程序的原因，useReady(() => {
      setTimeout(() => {
        if (showCanvas2D.value) {
          const { canvasId } = canvasAll;
          Taro.createSelectorQuery().select(`#${canvasId}`).node(({ node: canvas }) => {
            canvas.width = state.displayWidth;
            canvas.height = state.displayHeight;
            canvasAll.cropperCanvas = canvas;
          }).exec();
        }
      }, 500)
    });
延时再获取createSelectorQuery

**Comment by yi-boide** [comment]
你在你的项目中是怎么使用的？官方例子我允行在微信小程序没有发现这个问题。
