### ISSUE TITLE
【Calendar 日历】选中某个月的【日期区间】日历后再次点击进去查看时，无法定位到之前选中的日期，会跳到其他月份的日历选择界面

### ISSUE THREAD

**Issue by zhimianhub** [jdf2e/nutui#2937]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.0

### 平台

h5

### 重现链接

https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/calendar

### 重现步骤

【Calendar 日历】选中某个月的【日期区间】日历后再次点击进去查看时，无法定位到之前选中的日期，会跳到其他月份的日历选择界面

### 期望的结果是什么？

正确显示已选中的【日期区间】

### 实际的结果是什么？

跳到其他月份的日历，没有显示已选中的【日期区间】

**Comment by zhimianhub** [comment]
官网可以复现，https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/calendar

**Comment by zhimianhub** [comment]
> 你好 @zhimianhub, 我们需要你提供一个最小重现实例以便于我们帮你排查问题。你可以提供一个基于 Taro NutUI4.0 模板项目的 GitHub 仓库链接（`@nutui/nutui-taro`），也可以通过 [CodeSandbox](https://codesandbox.io/s/nutui4-vite-demo-2fw7xh?file=/src/App.vue) 创建一个在线实例（`@nutui/nutui`）。请确保选择准确的版本。

官网可以复现 https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/calendar

**Comment by eiinu** [comment]
每次打开日历时，默认展示的是 `default-value` 里的值。
如果只是选择了其他日期，但没有点确认并修改 `default-value` 的值，那么关闭后再打开，依然是上次的位置。
这是符合预期的。

**Comment by zhimianhub** [comment]
> 每次打开日历时，默认展示的是 `default-value` 里的值。 如果只是选择了其他日期，但没有点确认并修改 `default-value` 的值，那么关闭后再打开，依然是上次的位置。 这是符合预期的。

是这样的，我在官网里操作的，具体操作如下
点击【选择日期专区】，选择日期后点击确认按钮，之后选择框已经显示了我选择的日期范围，再次点击选择框进去，位置并没有跳转到我已选择的日期，你可以试试选择【2020-01-30至2020-01-31】（选择奇数的月份才有这个问题，偶数的月份没有这个问题）

**Comment by eiinu** [comment]
> https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/calendar

网站示例无法复现问题。可以提供一下环境信息，比如使用的浏览器、是否使用了其他时区，提供录屏或者最小可复现代码仓库用于排查问题。
