### ISSUE TITLE
Elevator 电梯楼层组件的问题

### ISSUE THREAD

**Issue by 859809405** [jdf2e/nutui#295]
navHeight参数改变之后,对应导航item的lineheight不会跟着变，会造成点击不准确
![image](https://user-images.githubusercontent.com/68373044/87649932-825d0980-c783-11ea-8190-6d4a5023a4c9.png)

**Comment by zhenyulei** [comment]
非常感谢您的细心 我已经在源码中修改了该问题 待后续新版本上线即可生效 欢迎使用 nutui
