### ISSUE TITLE
form 表单验证出现警告 [NutUI] <FormItem> 使用 rules 校验规则时 , 必须设置 prop 参数

### ISSUE THREAD

**Issue by febelery** [jdf2e/nutui#2953]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.1

### 平台

h5

### 重现链接

https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/form

### 重现步骤

直接 https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/form  这个页面打开 f12 点击提交验证，就会出现，实际上是设置了prop

### 期望的结果是什么？

不警告

### 实际的结果是什么？

[NutUI] <FormItem> 使用 rules 校验规则时 , 必须设置 prop 参数

**Comment by eiinu** [comment]
关联 PR：#2690
