### ISSUE TITLE
DatePicker 日期选择器 v-model 的值不能设置为null，会报错 Maximum recursive

### ISSUE THREAD

**Issue by febelery** [jdf2e/nutui#2955]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.1

### 平台

h5

### 重现链接

https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/datepicker

### 重现步骤

```js
      <!-- 比如默认formData.date 是null会报错，目前date的逻辑是必须在min和max之间 -->
      <!-- 但是一般初始化的date是null -->
      <!-- 打开日期选择，默认是min的值 -->
      <nut-date-picker
        is-show-chinese
        v-model="formData.date"
        type="datetime"
        :min-date="
          () => {
            let date = new Date();
            date.setMonth(date.getMonth() - 5);
            return date;
          }
        "
        :max-date="
          () => {
            let date = new Date();
            date.setMonth(date.getMonth() + 5);
            return date;
          }
        "
      ></nut-date-picker>
      
      formData = ref({date:null})
```

### 期望的结果是什么？

date为null的时候，打开日期选择默认为当前时间，如果当前时间小于Min时间，则默认时间为min时间

### 实际的结果是什么？

form:1  Uncaught (in promise) Maximum recursive updates exceeded in component <NutCell>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

**Comment by eiinu** [comment]
1、`max-date` 与 `min-date` 的类型是 Date 而不是函数。
2、`v-model` 支持传 null，会默认选择第一个选项。
