### ISSUE TITLE
Picker 选择器 默认会选第一个，按照select的逻辑默认是没有选中任何选项

### ISSUE THREAD

**Issue by febelery** [jdf2e/nutui#2956]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.1

### 平台

h5

### 重现链接

https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/picker

### 重现步骤

```js
<!--  <默认会选中第一个，未找到默认不选择方案> -->
<nut-cell
  class="border-wrapper"
  title=" '请选择'"
  is-link
  @click="visible = true"
></nut-cell>
<nut-popup v-model:visible="visible" position="bottom">
  <nut-picker
    v-model="formData.data"
    three-dimensional
    :columns="[
      { text: '南京', value: 'Nanjing' },
      { text: '无锡', value: 'Wuxi' },
    ]"
  />
</nut-popup>

formData = ref({data:null})
```

### 期望的结果是什么？

默认不选中

### 实际的结果是什么？

默认会选中第一个

**Comment by zxlmmmm** [comment]
This is a same question which hanppend to me. Please click this link.
https://github.com/jdf2e/nutui/issues/2946

**Comment by eiinu** [comment]
Picker 的交互设计可以参考微信 [picker-view](https://developers.weixin.qq.com/miniprogram/dev/component/picker-view.html)，这种形式下**不存在选中空值**的展示逻辑。
