### ISSUE TITLE
nut-tab下滑线不见了，并没有加让它消失的参数

### ISSUE THREAD

**Issue by Stonewalling** [jdf2e/nutui#296]
## 问题描述

在popup层里面嵌套了一个nut-tab，然后发现nut-tab的下划线不见了，

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
![image](https://user-images.githubusercontent.com/21361701/87924978-35926f00-cab2-11ea-9c8a-67f4153d46db.png)
就想这个tab的下划线能出来，观察发现，下划线的宽度一直为0，单独用nut-tab是可以的

## 复现步骤，具体代码
![image](https://user-images.githubusercontent.com/21361701/87924885-15fb4680-cab2-11ea-97e4-3416844626ef.png)
![image](https://user-images.githubusercontent.com/21361701/87924921-214e7200-cab2-11ea-9f81-e800f84a3807.png)

![image](https://user-images.githubusercontent.com/21361701/87924885-15fb4680-cab2-11ea-97e4-3416844626ef.png)
![image](https://user-images.githubusercontent.com/21361701/87924921-214e7200-cab2-11ea-9f81-e800f84a3807.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by Stonewalling** [comment]
通过观察大佬的源代码发现，导致下划线没有的情况可能是组件渲染的问题，我在popup组件里tab外层加一个div，并用v-if条件与popup组件条件一致，结果就是tab下划线能出来

**Comment by zhenyulei** [comment]
你好 由于没有提供最小代码复现仓库 我按照你的截图 猜测是不是 is-scroll 是动态变化的 也就是刚开始数据么有返回来的时候 is-scroll是false，待数据返回来之后是true，目前我已经在源码中对 is-scroll 做了监听 待上线后你再看看是否可以 或者提供最小代码复现仓库 我调试一下 感谢

**Comment by Stonewalling** [comment]
好的，我是这么改的，可能是我写的问题吧
![image](https://user-images.githubusercontent.com/21361701/89136203-1214fd00-d565-11ea-9f54-df115aed5cf3.png)

**Comment by Stonewalling** [comment]
好的，我是这么改的，可能是我写的问题吧
![image](https://user-images.githubusercontent.com/21361701/89136217-20631900-d565-11ea-9122-d73c8bdd09f1.png)

**Comment by Stonewalling** [comment]
好的，我是这么改的，可能是我写的问题吧
![A32B0159-6E14-42B0-B397-90231065D94A](https://user-images.githubusercontent.com/21361701/89136243-42f53200-d565-11ea-83ee-92d8eb1b93b4.png)

**Comment by richard1015** [comment]
@Stonewalling   是否已解决
