### ISSUE TITLE
使用jdt主题样式时并未生效

### ISSUE THREAD

**Issue by lengxiaoyu6** [jdf2e/nutui#2960]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.1

### 平台

h5

### 重现链接

https://codesandbox.io/p/sandbox/nutui4-vite-demo-forked-fq8zq4

### 重现步骤

在vite.config.ts里配置了，但是使用<nut-button type="primary">主要按钮</nut-button>的时候是红色色调的样式，按照文档来看应该是蓝色色调
![{1F2F4007-841A-4faa-9FF7-141A38B7980C}](https://github.com/jdf2e/nutui/assets/43517191/5678e7f5-848a-40c1-afbb-bde754e9fc50)
![{6910D411-1DB2-4779-B0BF-23228C7AB3C6}](https://github.com/jdf2e/nutui/assets/43517191/737497f6-a82e-44c0-84fd-ccfbeb8adf56)

并且我尝试在main.ts引入import '@nutui/nutui/dist/styles/variables-jdt.scss'，但是出现了Internal server error: [sass] This file is already being loaded.的提示，也就代表着我的vite配置是生效了的
![{F825C56A-D210-4880-AFB8-9C962F130714}](https://github.com/jdf2e/nutui/assets/43517191/ad2ff0ab-82c7-43b7-9942-ee09687511b5)

### 期望的结果是什么？

能够出现实际正常的主题样式

### 实际的结果是什么？

没有出现

### 环境信息

  System:
    OS: Windows 11 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 17.60 GB / 31.84 GB
  Binaries:
    Node: 16.15.1 - G:\nvm\nodejs\node.EXE
    Yarn: 1.22.19 - E:\nodejs\node_modules\node_global\yarn.CMD
    npm: 8.11.0 - G:\nvm\nodejs\npm.CMD
    pnpm: 8.14.0 - G:\nvm\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (122.0.2365.80)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @nutui/nutui: ^4.3.1 => 4.3.1

**Comment by eiinu** [comment]
默认配置下组件使用的是 css 样式。
如果使用特定主题，需要使用 scss 样式，完整的 vite 配置如下：

```ts
// vite.config.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import Components from 'unplugin-vue-components/vite'
import NutUIResolver from '@nutui/auto-import-resolver'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    Components({
      resolvers: [
        NutUIResolver({
          importStyle: 'sass' // 使用 scss 样式
        })
      ],
    }),
  ],
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: `@import "@nutui/nutui/dist/styles/variables-jdt.scss";`
      }
    }
  }
})
```

后面会更新一下文档说明。

**Comment by lengxiaoyu6** [comment]
已经解决

**Comment by Zckor** [comment]
找半天才知道。。。希望文档及时更新下，太崩溃了
