### ISSUE TITLE
tab组件增加下划线宽度设定

### ISSUE THREAD

**Issue by Stonewalling** [jdf2e/nutui#297]
## 你建议我们做什么？

现在...

项目中经常需要设置下划线宽度，而这个宽度又是通过tab项的宽度计算过来的，无法通过css设置修改

如果你能...
![image](https://user-images.githubusercontent.com/21361701/88122558-7e097400-cbfb-11ea-9af5-4adeab224e12.png)
![image](https://user-images.githubusercontent.com/21361701/88122578-8f528080-cbfb-11ea-8eb2-e27cfd52f36f.png)
![image](https://user-images.githubusercontent.com/21361701/88122661-c163e280-cbfb-11ea-94c7-18b2fe61913b.png)
![image](https://user-images.githubusercontent.com/21361701/88122676-cde83b00-cbfb-11ea-95c2-a09e1ba6cb6d.png)

它将使...
tab的设置更加灵活
## 其它

无

**Comment by zhenyulei** [comment]
非常好的建议 感谢您的建议 我己经集成到代码中了 下一个版本会更新 再次表示感谢
