### ISSUE TITLE
[FR]: Address组件省市区的json数据  必须开发者传吗

### ISSUE THREAD

**Issue by yyh1413** [jdf2e/nutui#2973]
### NutUI 包名

@nutui/nutui

### 这个功能解决了什么问题？

省市区json还需要开发者自己传到组件中吗 ?，因为找省市区json真的不方便，而且还需要分开传

### 你期望的组件设计是怎样的？

期望省市区的json可以在组件中内置下，建议可以通过传参数来定义是选择省市     还是省市区    uview做的就挺好的可以参考

**Comment by eiinu** [comment]
短期内没有维护一套省市区数据的计划

**Comment by itzwg** [comment]
老大找到解决方案了吗，还是换了个组件库
