### ISSUE TITLE
Swipe在动态ref下手动调用open()无效

### ISSUE THREAD

**Issue by selectweilin** [jdf2e/nutui#2974]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.2

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydHtyZWZ9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IFN3aXBlIH0gZnJvbSAnQG51dHVpL251dHVpLXRhcm8nO1xuaW1wb3J0IHsgRG9uZ2RvbmcgfSBmcm9tICdAbnV0dWkvaWNvbnMtdnVlJ1xuY29uc3Qgc2hvdyA9ICgpID0+IHtcbiAgc2hvd1RvYXN0LnRleHQoJ0hlbGxvLCBOdXRVSSEnKVxufTtcbmNvbnN0IGl0ZW1zPXJlZihbJ2EnLCdiJywnYycsJ2QnXSlcbmNvbnN0IHN3aXBlUmVmcz1yZWYoKVxuY29uc3Qgb3BlblN3aXBlPShpbmRleCk9PntcbiAgc2hvd1RvYXN0LnRleHQoc3dpcGVSZWZzLnZhbHVlW2luZGV4XS5uYW1lKVxuICBzd2lwZVJlZnMudmFsdWVbaW5kZXhdLm9wZW4oKVxufVxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG4gICA8bnV0LXN3aXBlIHYtZm9yPVwiKGl0ZW0saW5kZXgpIGluIGl0ZW1zXCIgOm5hbWU9XCInc3dpcGUnK2luZGV4XCIgOmtleT1cImluZGV4XCIgcmVmPVwic3dpcGVSZWZzXCI+XG4gICAgPG51dC1jZWxsIDp0aXRsZT1cIidDbGljayBTd2l0Y2ggdG8gU3dpcGUnK2luZGV4XCIgQGNsaWNrPVwib3BlblN3aXBlKGluZGV4KVwiPjwvbnV0LWNlbGw+XG4gICAgPHRlbXBsYXRlICNyaWdodD5cbiAgICAgIDxudXQtYnV0dG9uIHNoYXBlPVwic3F1YXJlXCIgc3R5bGU9XCJoZWlnaHQ6IDEwMCVcIiB0eXBlPVwiZGFuZ2VyXCI+QnV0dG9uPC9udXQtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvbnV0LXN3aXBlPlxuPC90ZW1wbGF0ZT4ifQ==

### 重现步骤

```vue
<script setup lang="ts">
import{ref} from 'vue'
import { showToast } from '@nutui/nutui'
import { Swipe } from '@nutui/nutui-taro';
import { Dongdong } from '@nutui/icons-vue'
const show = () => {
  showToast.text('Hello, NutUI!')
};
const items=ref(['a','b','c','d'])
const swipeRefs=ref()
const openSwipe=(index)=>{
  showToast.text(swipeRefs.value[index].name)
  swipeRefs.value[index].open()
}
</script>
<template>
   <nut-swipe v-for="(item,index) in items" :name="'swipe'+index" :key="index" ref="swipeRefs">
    <nut-cell :title="'Click Switch to Swipe'+index" @click="openSwipe(index)"></nut-cell>
    <template #right>
      <nut-button shape="square" style="height: 100%" type="danger">Button</nut-button>
    </template>
  </nut-swipe>
</template>
``` 

### 期望的结果是什么？

点击后能打开swipe

### 实际的结果是什么？

点击后无法open

**Comment by eiinu** [comment]
1、open 方法需要传参数，比如 'left'
2、swipe 默认带有点击后关闭的效果，cell 上的点击事件应该增加阻止冒泡的处理。

**Comment by selectweilin** [comment]
解决了，谢谢
