### ISSUE TITLE
[FR]: input框更新一下focus属性 autofocus即将废弃

### ISSUE THREAD

**Issue by Xhyen** [jdf2e/nutui#2988]
### NutUI 包名

@nutui/nutui

### 这个功能解决了什么问题？

auto-focus即将废弃 要用focus替代

https://developers.weixin.qq.com/miniprogram/dev/component/input.html

### 你期望的组件设计是怎样的？

auto-focus即将废弃 要用focus替代

https://developers.weixin.qq.com/miniprogram/dev/component/input.html

**Comment by eiinu** [comment]
由于 [@tarojs/plugin-html](https://taro-docs.jd.com/docs/use-h5#2-html-input-%E6%A0%87%E7%AD%BE) 的存在，`autofoucs` 在小程序环境下会被映射为 `focus`，NutUI 不需要调整。
