### ISSUE TITLE
使用自动按需引入的方式，同时使用了nutui-bingo组件，build的时候会报错

### ISSUE THREAD

**Issue by febelery** [jdf2e/nutui#2998]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.3

### 平台

h5

### 重现链接

https://nutui.jd.com/h5/vue/4x/#/zh-CN/guide/start

### 重现步骤

```shell
npm i @nutui/nutui
npm i @nutui/nutui-bingo
```

```vue
// vite.config.js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import Components from 'unplugin-vue-components/vite'
import NutUIResolver from '@nutui/auto-import-resolver'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    // 开启 unplugin 插件，自动引入 NutUI 组件
    Components({
      resolvers: [NutUIResolver()],
    }),
  ]
})
```

```
npm run build
```
报错，将 nutui-bingo 组件的css地址识别为  nutui

### 期望的结果是什么？

`npm run build` 打包正常通过 

### 实际的结果是什么？

将 nutui-bingo 组件的css地址识别为  nutui , 然后打包报错，编译不通过

**Comment by eiinu** [comment]
1、自动按需引入方式，只支持 NutUI 4.x 版本。
2、NutUI Bingo，只支持 NutUI 3.x 版本，不可与 4.x 版本同时使用。
