### ISSUE TITLE
按需加载ImagePicker，使用scss时报错

### ISSUE THREAD

**Issue by p-eng** [jdf2e/nutui#30]
使用css正常，使用scss报错
![image](https://user-images.githubusercontent.com/33571719/54329950-df582500-464e-11e9-877b-f7eef7b83c2e.png)

**Comment by famanoder** [comment]
按需构建组件时，我们默认使用的是打包好的 `.css`，如果需要修改主题或将按需构建插件的 `style` 属性设置为 `scss`，还需要额外的 `webpack` 配置。
```js
{
    loader: 'sass-loader',
    options: {
        data: `@import "@nutui/nutui/dist/styles/index.scss"; `
    }
}
```

**Comment by peng-xiaoyu** [comment]
好的，谢谢。
