### ISSUE TITLE
希望增加一个下滑加载、上拉刷新的组件

### ISSUE THREAD

**Issue by Stonewalling** [jdf2e/nutui#300]
## 你建议我们做什么？

现在...
希望增加一个下滑加载、上拉刷新的组件。功能和mintUI一样，但是，那个BUG太多了
如果你能...

它将使...

## 其它

无

**Comment by richard1015** [comment]
下拉刷新，上拉加载
正在开发中，近一两天会发布

**Comment by luobinbinchina** [comment]
@Stonewalling https://nutui.jd.com/jdl/#/scroll 已发布可以使用，有问题欢迎反馈，谢谢
