### ISSUE TITLE
Signature 签名

### ISSUE THREAD

**Issue by LGXAK** [jdf2e/nutui#301]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为

直接在NutUI官网测试出bug了，签名UI组件，应该是点击重置清空画版，鼠标移动上去点击持续按住鼠标画版才开始绘画，而不是鼠标移动上去就开始绘画了

## 复现步骤，具体代码

点击签名UI，然后先开始正常操作按住鼠标绘画，确认3次绘画签名，然后点击重置画版功能，持续点击重置画板功能大概8-10次，鼠标要快速点击重置，画板就会出现bug，不需要按住鼠标也可以开启绘画功能bug

![QQ图片20200730163717](https://user-images.githubusercontent.com/47965708/88901126-fc60b880-d282-11ea-88e4-4401da5e5178.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by Stonewalling** [comment]
这个BUG，我解决了，不过我用的是自己写canvas.js 文件

**Comment by guoxiao158** [comment]
正在收起修改。。。

**Comment by LGXAK** [comment]
> 正在收起修改。。。。

你好，这个触发bug方式，说起来有点无语，其实就是鼠标在画板里绘制，然后按住鼠标不放，移除到边框外面后回到绘制画板就不出现bug了，bug原因是没有监听鼠标事件是否存在点击情况，如果鼠标超出div需要重新点击触发鼠标事件才能开始绘画，这样bug就解决了，这种情况在真实手机环境其实很触发的到这bug

**Comment by LGXAK** [comment]
但是你的重签功能，需要完善一下，因为没有清除鼠标事件，导致我鼠标移出div后再回来绘制后出现bug，即使点击重签也没清除鼠标事件，

**Comment by richard1015** [comment]
@guoxiao158   尽快跟进一下

**Comment by guoxiao158** [comment]
已经修复，等待下个版本发布

**Comment by richard1015** [comment]
请更新至最新版本
