### ISSUE TITLE
nut-calendar控件运用Slots插槽，ios真机不展示插槽内容，希望帮忙解决

### ISSUE THREAD

**Issue by TaoZi6277** [jdf2e/nutui#3010]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.2.8

### 平台

h5

### 重现链接

https://dev.epayservice.cn:19210/internetfuneralh5/cemetery/reservationFlowPath

### 重现步骤

进入项目选择完机构、位置后进入时间选择页面，可选择日期top、bottom插槽写有自定义内容，显示当天可预约数量，只有ios真机不显示，浏览器模拟器跟安卓机子可以正常显示；
![ios机器截图](https://github.com/jdf2e/nutui/assets/116068932/c902caba-571d-4181-bd8c-820d436ec137)
![安卓机子截图](https://github.com/jdf2e/nutui/assets/116068932/f9ae0bc0-4a67-4742-bd47-9d216df6dd14)

### 期望的结果是什么？

ios跟安卓都能正常展示插槽自定义内容

### 实际的结果是什么？

ios真机不展示插槽内容

### 环境信息

  System:
    OS: Windows 11 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz
    Memory: 3.12 GB / 15.79 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.6.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (123.0.2420.81)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @nutui/nutui: 4.3.4 => 4.3.4

### 其他补充信息

![image](https://github.com/jdf2e/nutui/assets/116068932/80ad2814-45aa-4282-9a95-0c4cc306a97f)

**Comment by eiinu** [comment]
`xxxx-xx-xx` 在 Safari 中是不合法的，更换为 `xxxx/xx/xx` 即可

**Comment by TaoZi6277** [comment]
![image](https://github.com/jdf2e/nutui/assets/116068932/cbbd5e35-e8a1-48d5-99c1-b4a249d8e219)
@nutui_nutui.js?v=69f705f2:9050 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'curData')
    at getCurrData (@nutui_nutui.js?v=69f705f2:9050:37)
    at initData (@nutui_nutui.js?v=69f705f2:9175:18)
    at @nutui_nutui.js?v=69f705f2:9394:7
    at chunk-CFLHC4X7.js?v=69f705f2:4318:88
    at callWithErrorHandling (chunk-CFLHC4X7.js?v=69f705f2:1650:18)
    at callWithAsyncErrorHandling (chunk-CFLHC4X7.js?v=69f705f2:1658:17)
    at hook.__weh.hook.__weh (chunk-CFLHC4X7.js?v=69f705f2:4298:19)
    at flushPostFlushCbs (chunk-CFLHC4X7.js?v=69f705f2:1825:41)
    at flushJobs (chunk-CFLHC4X7.js?v=69f705f2:1863:5)
修改判断时间格式之后，报错了

**Comment by TaoZi6277** [comment]
![image](https://github.com/jdf2e/nutui/assets/116068932/de7f8f56-43be-4d36-8cd5-1feb4d5b6415)
