### ISSUE TITLE
popup组件和input组件混用 当popupd的隐藏的时候 input组件中的placeholder会在页面显示一下再消失

### ISSUE THREAD

**Issue by Xhyen** [jdf2e/nutui#3019]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.1

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IENsb3NlIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcblxuICBcbmNvbnN0IHNob3cgPSByZWYoZmFsc2UpXG5jb25zdCB2YWx1ZTEgPSAnJ1xuXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC1jZWxsIHRpdGxlPVwiQ2VudGVyXCIgaXMtbGluayBAY2xpY2s9XCJzaG93ID0gdHJ1ZVwiPjwvbnV0LWNlbGw+XG4gXHRcdDxudXQtcG9wdXAgdi1tb2RlbDp2aXNpYmxlPVwic2hvd1wiIDpjbG9zZS1vbi1jbGljay1vdmVybGF5PVwiZmFsc2VcIiByb3VuZCBwb3AtY2xhc3M9XCJwb3B1cFwiPlxuICAgICAgPGRpdiBjbGFzcz1cInBvcC10aXRsZVwiPlxuICAgICAgICA8Q2xvc2UgY2xhc3M9XCJpY29uXCIgY29sb3I9XCIjMmIyYjJiXCIgc2l6ZT1cIjE0cHhcIiBAY2xpY2s9XCJzaG93ID0gZmFsc2VcIiAvPlxuICAgICAgPC9kaXY+XG4gICAgICA8bnV0LWlucHV0IHYtbW9kZWw9XCJ2YWx1ZTFcIiBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpeaHgueahOaHgueahFwiIHR5cGU9XCJudW1iZXJcIiA6bWF4LWxlbmd0aD1cIjZcIiAvPlxuICAgIDwvbnV0LXBvcHVwPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLnBvcHVwe1xuICBkaXNwbGF5OiBmbGV4O1xuICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICB0b3A6IDQwJTtcbiAgd2lkdGg6IDIwMHB4O1xuICBoZWlnaHQ6IDUwcHg7XG4gIHBhZGRpbmc6IDMycHg7XG4gIC5wb3AtdGl0bGV7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICAgIHdpZHRoOiAxMDAlO1xuICB9XG59XG48L3N0eWxlPiJ9

### 重现步骤

隐藏popup的时候 会自动清空input内容 然后显示了placeholder 导致页面上出现了placeholder的残影 

是否是popup层级的问题导致的 

### 期望的结果是什么？

可以设置先隐藏popup 再清空内部组件的内容

### 实际的结果是什么？

先清空内部组件的内容 再隐藏弹窗

### 环境信息

  Taro CLI 3.6.24 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.24 => 3.6.24
      @tarojs/components: 3.6.24 => 3.6.24
      @tarojs/helper: 3.6.24 => 3.6.24
      @tarojs/mini-runner: 3.6.24 => 3.6.24
      @tarojs/plugin-framework-vue3: 3.6.24 => 3.6.24
      @tarojs/plugin-html: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-h5: 3.6.24 => 3.6.24
      @tarojs/plugin-platform-weapp: 3.6.24 => 3.6.24
      @tarojs/runtime: 3.6.24 => 3.6.24
      @tarojs/shared: 3.6.24 => 3.6.24
      @tarojs/taro: 3.6.24 => 3.6.24
      @tarojs/webpack-runner: 3.6.24 => 3.6.24
      @tarojs/webpack5-runner: 3.6.24 => 3.6.24
      babel-preset-taro: 3.6.24 => 3.6.24
      eslint-config-taro: 3.6.24 => 3.6.24

**Comment by eiinu** [comment]
```
const value1 = ''
```
代码逻辑有问题，input 没有双向绑定 value。
