### ISSUE TITLE
nut-tabbar组件中的icon的来源路径变的灵活一些[suggest]

### ISSUE THREAD

**Issue by yeyuqiu-ux** [jdf2e/nutui#302]
## 你建议我们做什么？
建议官方将 nut-tabbar组件中的icon的来源路径变的灵活一些,最好能像一般的icon字体图标一样引用,不用一个字体下载一个svg

现在...现在icon为图片/是使用单个字体的svg

如果你能...

它将使...如果能实现,将会大大提升了项目的合理性,不必要去为了一个tar分好几次下载svg,当可以使用icon编码或者是icon-xxx的时候,开发者可以在自己的常用库中就能找到需要的字体图标

## 其它

无

**Comment by richard1015** [comment]
近期开发中，感谢您的反馈，下个版本更新此需求

**Comment by richard1015** [comment]
最新版已优化
