### ISSUE TITLE
【Button】@click不能同时兼容H5和小程序

### ISSUE THREAD

**Issue by woshishade** [jdf2e/nutui#3024]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.4

### 平台

h5, weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCwgQnV0dG9uIH0gZnJvbSAnQG51dHVpL251dHVpJ1xuY29uc3QgaGFuZGxlVGVzdCA9ICgpID0+IHtcbiAgc2hvd1RvYXN0LnRleHQoJ0hlbGxvLCBOdXRVSSEnKVxufTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxudXQtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQHRhcD1cImhhbmRsZVRlc3RcIiBAY2xpY2s9XCJoYW5kbGVUZXN0XCI+dGVzdDwvbnV0LWJ1dHRvbj5cbjwvdGVtcGxhdGU+In0=

### 重现步骤

``` js
<template>
  <view class="col">
    <nut-button type="primary" @tap="handleTest" @click="handleTest">test</nut-button>
  </view>
</template>

<script setup lang="ts">
import Taro from '@tarojs/taro'
definePageConfig({
  navigationBarTitleText: '我的',
})

const handleTest = () => {
  Taro.showToast({
    title: '成功!',
    icon: 'success',
    duration: 2000
  })
}
</script>
```

### 期望的结果是什么？

@click可以同时兼容H5和小程序

### 实际的结果是什么？

@click只能作用于H5，@tap才能作用于weapp

### 环境信息

  Taro CLI 3.6.25 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.25 => 3.6.25 
      @tarojs/components: 3.6.25 => 3.6.25 
      @tarojs/helper: 3.6.25 => 3.6.25 
      @tarojs/plugin-framework-vue3: 3.6.25 => 3.6.25 
      @tarojs/plugin-platform-alipay: 3.6.25 => 3.6.25 
      @tarojs/plugin-platform-h5: 3.6.25 => 3.6.25 
      @tarojs/plugin-platform-jd: 3.6.25 => 3.6.25 
      @tarojs/plugin-platform-qq: 3.6.25 => 3.6.25 
      @tarojs/plugin-platform-swan: 3.6.25 => 3.6.25 
      @tarojs/plugin-platform-tt: 3.6.25 => 3.6.25 
      @tarojs/plugin-platform-weapp: 3.6.25 => 3.6.25 
      @tarojs/runtime: 3.6.25 => 3.6.25 
      @tarojs/shared: 3.6.25 => 3.6.25 
      @tarojs/taro: 3.6.25 => 3.6.25 
      @tarojs/taro-loader: 3.6.25 => 3.6.25 
      @tarojs/webpack5-runner: 3.6.25 => 3.6.25 
      babel-preset-taro: 3.6.25 => 3.6.25 
      eslint-config-taro: 3.6.25 => 3.6.25 
    npmGlobalPackages:
      typescript: 5.0.2

**Comment by eiinu** [comment]
[NutUI Taro 快速上手文档](https://nutui.jd.com/taro/vue/4x/#/zh-CN/guide/start)

> 安装 @tarojs/plugin-html
