### ISSUE TITLE
nut-tabs和nut-popup一起使用的bug

### ISSUE THREAD

**Issue by myby7000p** [jdf2e/nutui#3032]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.2.9

### 平台

h5

### 重现链接

https://codesandbox.io/p/devbox/nutui4-vite-demo-forked-9ql6fq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluukt9qt0007356m0ww69vbc%2522%252C%2522sizes%2522%253A%255B67.60076780116364%252C32.39923219883636%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluukt9qt0002356m7v135g5a%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluukt9qt0004356m7x422axp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluukt9qt0006356mnw3engee%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluukt9qt0002356m7v135g5a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluukt9qt0001356mtff7354z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluukukxm003x356mat2k0cyo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluukxc0q0002356ljm93sxw1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluukt9qt0002356m7v135g5a%2522%252C%2522activeTabId%2522%253A%2522cluukxc0q0002356ljm93sxw1%2522%257D%252C%2522cluukt9qt0006356mnw3engee%2522%253A%257B%2522id%2522%253A%2522cluukt9qt0006356mnw3engee%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluukt9qt0005356mgc4jq2f4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluukt9qt0005356mgc4jq2f4%2522%257D%252C%2522cluukt9qt0004356m7x422axp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluukt9qt0003356m03znghnf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cluukt9qt0004356m7x422axp%2522%252C%2522activeTabId%2522%253A%2522cluukt9qt0003356m03znghnf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 重现步骤

nut-tabs和nut-popup一起使用的 nut-popup的遮罩没遮住nut-tabs的标题，导致弹窗打开还能切换页面
![image](https://github.com/jdf2e/nutui/assets/88788426/759eb1c8-404f-467b-aa10-684060ecb621)

### 期望的结果是什么？

nut-popup打开会遮住页面所有东西

### 实际的结果是什么？

nut-popup打开没遮住nut-tabs的标题

**Comment by eiinu** [comment]
[NutUI Tabs](https://nutui.jd.com/h5/vue/4x/#/zh-CN/component/tabs#%E6%97%A0%E5%88%87%E6%8D%A2%E5%8A%A8%E7%94%BB)
