### ISSUE TITLE
官网的组件图标使用错误

### ISSUE THREAD

**Issue by Dumbliidore** [jdf2e/nutui#3034]
### NutUI 包名

@nutui/nutui, @nutui/nutui-taro

### NutUI 版本号

*

### 平台

weapp

### 重现链接

https://nutui.jd.com/#/

### 重现步骤

![image](https://github.com/jdf2e/nutui/assets/35067857/16091ec5-5d15-4d2f-888f-661d7add7781)

### 期望的结果是什么？

名称与图标对应

### 实际的结果是什么？

名称与图标不对应

### 环境信息

Windows

### 其他补充信息

![image](https://github.com/jdf2e/nutui/assets/35067857/16091ec5-5d15-4d2f-888f-661d7add7781)
为什么用的不是 React 的图标？

**Comment by eiinu** [comment]
这是 HTML5……

**Comment by Dumbliidore** [comment]
> 这是 HTML5……

哈哈搞错了，我刚好也在看svelte，先入为主了。
