### ISSUE TITLE
[FR]: 第一个，nut popover 实在太挫了；第二个问题，nut文档写的也很一般，内容案例都不太行。

### ISSUE THREAD

**Issue by ZhangRuyi0528** [jdf2e/nutui#3039]
### NutUI 包名

@nutui/nutui-taro

### 这个功能解决了什么问题？

[FR]: nut popover 实在太挫了，印象大大折扣，多选块来回选中效果，定位计算都很鸡肋，好好优化下；第二个问题，nut文档写的也很一般，内容案例都不太行。

### 你期望的组件设计是怎样的？

拉出来祭天，好好优化下，感觉想弃坑

**Comment by eiinu** [comment]
正确做法 1：提供 bug 的最小重现帮助我们排查问题
正确做法 2：提交 PR 修改 bug、优化文档、添加新的 demo
错误案例：当前 Issue
