### ISSUE TITLE
[suggest]改进DatePicker组件

### ISSUE THREAD

**Issue by Jungzl** [jdf2e/nutui#304]
## 你建议我们做什么？

目前在DatePicker组件中中间突出显示那一行「.nut-picker-list-panel」的行内样式
`transform: translate3d(0px, -2340px, 0px);`
对于使用了postcss-to-viewport的项目不起作用，会导致错位，直接更改较为麻烦，望得到改进
![image](https://user-images.githubusercontent.com/35426360/89246809-853e7200-d63e-11ea-8b26-457f64224a19.png)

## 其它

无

**Comment by richard1015** [comment]
@Jungzl    转换 rem 的时候 请过滤掉该组件

**Comment by richard1015** [comment]
是否已解决

**Comment by Jungzl** [comment]
@richard1015 已解决😀
