### ISSUE TITLE
使用slot嵌套nut-textarea时，输入内容自动失去焦点

### ISSUE THREAD

**Issue by liubo91** [jdf2e/nutui#3040]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.3

### 平台

weapp

### 重现链接

<demo>       <nut-textarea v-model="description" style="width: 100%" limit-show :max-length="100" />     </demo>

### 重现步骤

// demo 组件
<div style="flex: 1">
        <div style="flex: 1">
          <div style="flex: 1">
            <div style="flex: 1">
              <div style="flex: 1">
                <div style="flex: 1">
                  <slot></slot>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

### 期望的结果是什么？

正常输入内容，不失去焦点

### 实际的结果是什么？

多层嵌套后，输入内容时自动失去焦点

### 环境信息

Chrome: 123.0.6312.124
    Edge: 123.0.2420.97
    Safari: 15.0

**Comment by eiinu** [comment]
需要提供最小可复现仓库。
