### ISSUE TITLE
Picker 选择器在支付宝小程序下无法正常工作

### ISSUE THREAD

**Issue by functionwell** [jdf2e/nutui#3049]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.6

### 平台

alipay

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8bnV0LWNlbGwgdGl0bGU9XCLor7fpgInmi6nln47luIJcIiA6ZGVzYz1cIlN0cmluZyh2YWwpXCIgQGNsaWNrPVwic2hvdyA9IHRydWVcIj48L251dC1jZWxsPlxuICA8bnV0LXBvcHVwIHYtbW9kZWw6dmlzaWJsZT1cInNob3dcIiBwb3NpdGlvbj1cImJvdHRvbVwiPlxuICAgIDxudXQtcGlja2VyIHYtbW9kZWw9XCJ2YWxcIiA6Y29sdW1ucz1cImNvbHVtbnNcIiB0aXRsZT1cIuivt+mAieaLqeWfjuW4glwiIEBjb25maXJtPVwiY29uZmlybVwiIEBjYW5jZWw9XCJzaG93ID0gZmFsc2VcIiAvPlxuICA8L251dC1wb3B1cD5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3Qgc2hvdyA9IHJlZihmYWxzZSlcbmNvbnN0IHZhbCA9IHJlZihbJ0JlaWppbmcnXSlcbmNvbnN0IGNvbHVtbnMgPSByZWYoW1xuICB7IHRleHQ6ICfljZfkuqwnLCB2YWx1ZTogJ05hbmppbmcnIH0sXG4gIHsgdGV4dDogJ+aXoOmUoScsIHZhbHVlOiAnV3V4aScgfSxcbiAgeyB0ZXh0OiAn5rW35YyXJywgdmFsdWU6ICdIYWliZWknIH0sXG4gIHsgdGV4dDogJ+WMl+S6rCcsIHZhbHVlOiAnQmVpamluZycgfSxcbiAgeyB0ZXh0OiAn6L+e5LqR5rivJywgdmFsdWU6ICdMaWFueXVuZ2FuZycgfSxcbiAgeyB0ZXh0OiAn6ZW/5rKZJywgdmFsdWU6ICdDaGFuZ3NoYScgfSxcbiAgeyB0ZXh0OiAn5q2m5rGJJywgdmFsdWU6ICdXdWhhbicgfVxuXSlcblxuY29uc3QgY29uZmlybSA9ICh7IHNlbGVjdGVkVmFsdWUsIHNlbGVjdGVkT3B0aW9ucyB9KSA9PiB7XG4gIGNvbnNvbGUubG9nKHNlbGVjdGVkVmFsdWVbMF0sIHNlbGVjdGVkT3B0aW9uc1swXSlcbiAgc2hvdy52YWx1ZSA9IGZhbHNlXG59XG48L3NjcmlwdD4ifQ==

### 重现步骤

dev:alipay 启动工程后，在支付宝小程序开发工具中打开工程，picker 在支付宝小程序下，工作不正常：
1. picker 的 `tileChange` 方法在每次滚动选项时，都会报错，报错信息: Cannot read properties of undefined (reading '3') at Proxy.tileChange (Picker.js:588:1)
2. 选中过任一选项后，picker 的 confirm 事件，不会再返回新选中的选项，例如上面例子中，给定初始值为 ['Berijing']，在滚动到其他选项后，再点击 确定，仍旧返回 北京 选项
3. v-model 的值不会变化，同上，v-model 不管给初始值或者不传 v-model，选中过任一选项后，picker 的 value 不再变化
4. 与 popup 结合，使用异步获取选项进行展示时，初次展示会出现，第一个选项多行文字重叠的现象，且不能进行滚动选择，点击 取消 收起 popup 后，第二次再打开 popup，选项才会正常展示

### 期望的结果是什么？

picker 能正常工作，与微信小程序中表现一致

### 实际的结果是什么？

picker 在支付宝小程序下无法正常工作

**Comment by eiinu** [comment]
redirect to https://github.com/jdf2e/nutui/issues/2292
