### ISSUE TITLE
抖音小程序 input 不显示清除图标

### ISSUE THREAD

**Issue by 501956430** [jdf2e/nutui#3052]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.2

### 平台

tt

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IERvbmdkb25nIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbi8vaW1wb3J0IHsgQ2xvc2UgfSBmcm9tICdAbnV0dWkvaWNvbnMtdnVlLXRhcm8nXG5jb25zdCB2YWwxID0gcmVmKCcnKVxuY29uc3QgdmFsMiA9IHJlZignJylcbmNvbnN0IG9uQ2xpY2sgPSAoKSA9PiB7XG4gIHZhbDIudmFsdWUgPSAnJ1xufVxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG4gIDxudXQtaW5wdXQgdi1tb2RlbD1cInZhbDFcIiAgOmJvcmRlcj1cImZhbHNlXCIgcGxhY2Vob2xkZXI9XCJDbGVhcmFibGVcIiB0eXBlPVwibnVtYmVyXCIgY2xlYXJhYmxlIC8+XG4gIDxudXQtaW5wdXQgdi1tb2RlbD1cInZhbDJcIiBwbGFjZWhvbGRlcj1cIkNsZWFyIFNsb3RcIiBjbGVhcmFibGUgc2hvdy1jbGVhci1pY29uPlxuICAgIDx0ZW1wbGF0ZSAjY2xlYXI+XG4gICAgICA8Q2xvc2Ugc2l6ZT1cIjEyXCIgQGNsaWNrPVwib25DbGlja1wiPjwvQ2xvc2U+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9udXQtaW5wdXQ+XG48L3RlbXBsYXRlPiJ9

### 重现步骤

抖音小程序 不显示 清除图标

### 期望的结果是什么？

input 显示清除图标

### 实际的结果是什么？

不显示清除图标

### 环境信息

Taro CLI 3.6.27 environment info:
    System:
      OS: macOS 12.7.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 20.11.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.27 => 3.6.27 
      @tarojs/components: 3.6.27 => 3.6.27 
      @tarojs/helper: 3.6.27 => 3.6.27 
      @tarojs/plugin-framework-vue3: 3.6.27 => 3.6.27 
      @tarojs/plugin-html: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-alipay: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-h5: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-jd: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-qq: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-swan: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-tt: 3.6.27 => 3.6.27 
      @tarojs/plugin-platform-weapp: 3.6.27 => 3.6.27 
      @tarojs/runtime: 3.6.27 => 3.6.27 
      @tarojs/shared: 3.6.27 => 3.6.27 
      @tarojs/taro: 3.6.27 => 3.6.27 
      @tarojs/taro-loader: 3.6.27 => 3.6.27 
      @tarojs/webpack5-runner: 3.6.27 => 3.6.27 
      babel-preset-taro: 3.6.27 => 3.6.27 
      eslint-config-taro: 3.6.27 => 3.6.27

**Comment by eiinu** [comment]
抖音开发者工具 IDE 4.2.3，无法复现。可以提供一个完整的最小可复现 demo 仓库。

**Comment by 501956430** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
