### ISSUE TITLE
[FR]: tabbar添加新功能

### ISSUE THREAD

**Issue by like-cherry** [jdf2e/nutui#3054]
### NutUI 包名

@nutui/nutui-taro

### 这个功能解决了什么问题？

tabbar一般用在自定义导航栏，自定义导航肯定是希望更加灵活，可以随时控制tabbar的选中状态（用代码逻辑来控制），比如有一个场景，需要用户登录才能访问tabbar页，就需要在点击tabbar时做逻辑处理，处理完了后再决定是否跳转到该tabbar页（也决定了是否active该tabbar-item）。现在的组件并不能满足这个需求，现在只要点击了，就默认被添加选中样式了。

### 你期望的组件设计是怎样的？

可以参考一下Naive UI，它里面就有一个概念叫受控模式和非受控模式

**Comment by JonathanStrangeHelium** [comment]
tabbar好像有个tab-switch

**Comment by like-cherry** [comment]
没有用，tabbar这个组件只要点击了，样式立马就变了，用v-model控制不了样式。如果用代码控制v-model的值来改变选中状态，会出现v-model的值和选中状态不匹配的情况，问题还是挺多的。我现在用的是自己写的tabbar，没有用nutUI的tabbar

**Comment by like-cherry** [comment]
> tabbar好像有个tab-switch

没有用，tabbar这个组件只要点击了，样式立马就变了，用v-model控制不了样式。如果用代码控制v-model的值来改变选中状态，会出现v-model的值和选中状态不匹配的情况，问题还是挺多的。我现在用的是自己写的tabbar，没有用nutUI的tabbar
