### ISSUE TITLE
[suggest]nut-ui日期选择组件支持固定日期选择

### ISSUE THREAD

**Issue by k-jay-wang** [jdf2e/nutui#306]
## 日期选择组件固定每月最后一天可选，其他日期不可选
现在日期选择组件支持从固定日期开始，之前不可选。如果能够支持限制只能选择每个月的某一天，就会给用户更多的适配场景。

**Comment by richard1015** [comment]
1.类型支持年月
2.底部文案展示
3.指定日功能，可选（具体日或者月末）
