### ISSUE TITLE
Dialog 对话框组件，当content的值为"<"开头时，内容就不显示了，例如文本为<EXTIC2,123456,22...>

### ISSUE THREAD

**Issue by Lazydd** [jdf2e/nutui#3089]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.0.4

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmNvbnN0IHZpc2libGU9dHJ1ZVxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG4gIDxudXQtZGlhbG9nXG5cdFx0XHR0aXRsZT1cIuehruiupOWIoOmZpFwiXG5cdFx0XHRjb250ZW50PVwiPEVYVElDMiwxMjM0NTYsMjIuLi4+XCJcblx0XHRcdHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGVcIlxuXHRcdC8+XG48L3RlbXBsYXRlPiJ9

### 重现步骤

打开链接

### 期望的结果是什么？

展示真确的内容

### 实际的结果是什么？

空白

### 其他补充信息

估计是context允许使用html组件，匹配规则有问题，html标签应该是有闭合标签的才能当初html标签，临时用转义符可以解决我的问题

**Comment by Lazydd** [comment]
用转义符只有在playground的写法有用，用变量的写法还是没用

**Comment by eiinu** [comment]
https://github.com/jdf2e/nutui/blob/f0e37993e70d8d65cb3a2c0815d70a630d092c38/src/packages/__VUE/dialog/index.taro.vue#L23-L27
content 会传给一个 v-html 的元素，没有做其他的逻辑。可能是 Taro 的小程序端对 v-html 的处理不够完善。
也可以尝试下使用 default 插槽，它不会被当成 html 处理。

**Comment by Lazydd** [comment]
已经使用小程序自带的弹窗了
