### ISSUE TITLE
Icon nut-icon-am-shake nut-icon-am-infinite 动画怎么都动不起来

### ISSUE THREAD

**Issue by dreams-iP** [jdf2e/nutui#3098]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

1.7.10

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG5cblx0PG51dC1pY29uIG5hbWU9XCJkb3UtYXJyb3ctdXBcIiBjbGFzcz1cIm51dC1pY29uLWFtLWp1bXAgbnV0LWljb24tYW0taW5maW5pdGVcIj48L251dC1pY29uPlxuXHQ8bnV0LWljb24gbmFtZT1cInN0YXItZmlsbC1uXCIgY2xhc3M9XCJudXQtaWNvbi1hbS1ibGluayBudXQtaWNvbi1hbS1pbmZpbml0ZVwiPjwvbnV0LWljb24+XG5cdDxudXQtaWNvbiBuYW1lPVwicmVmcmVzaDJcIiBjbGFzcz1cIm51dC1pY29uLWFtLXJvdGF0ZSBudXQtaWNvbi1hbS1pbmZpbml0ZVwiPjwvbnV0LWljb24+XG5cdDxudXQtaWNvbiBuYW1lPVwiaGVhcnQtZmlsbFwiIGNsYXNzPVwibnV0LWljb24tYW0tYnJlYXRoZSBudXQtaWNvbi1hbS1pbmZpbml0ZVwiPjwvbnV0LWljb24+XG5cdDxudXQtaWNvbiBuYW1lPVwibWljcm9waG9uZVwiIGNsYXNzPVwibnV0LWljb24tYW0tZmxhc2ggbnV0LWljb24tYW0taW5maW5pdGVcIj48L251dC1pY29uPlxuXHQ8bnV0LWljb24gbmFtZT1cImRvd25sb2FkXCIgY2xhc3M9XCJudXQtaWNvbi1hbS1ib3VuY2UgbnV0LWljb24tYW0taW5maW5pdGVcIj48L251dC1pY29uPlxuXHQ8bnV0LWljb24gbmFtZT1cIm1lc3NhZ2VcIiBjbGFzcz1cIm51dC1pY29uLWFtLXNoYWtlIG51dC1pY29uLWFtLWluZmluaXRlXCI+PC9udXQtaWNvbj5cblxuXHQ8bnV0LXRvYXN0PjwvbnV0LXRvYXN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdD5cblx0aW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJztcblxuXHRleHBvcnQgZGVmYXVsdCB7XG5cblx0XHRkYXRhKCkge1xuXHRcdFx0cmV0dXJuIHtcblx0XHRcdFx0c3RhdHVzQmFySGVpZ2h0OiAwLFxuXHRcdFx0XHRidWJibGVCYXJIZWlnaHQ6IDAsXG5cdFx0XHRcdHRlc3RWYWx1ZTogXCJvb29vXCJcblx0XHRcdH1cblx0XHR9LFxuXHRcdG9uTG9hZCgpIHtcblx0XHRcdC8qXG5cdFx0XHRsZXQgc3lzdGVtSW5mbyA9IHVuaS5nZXRTeXN0ZW1JbmZvU3luYygpXG5cdFx0XHR0aGlzLnN0YXR1c0JhckhlaWdodCA9IHN5c3RlbUluZm8uc3RhdHVzQmFySGVpZ2h0XG5cdFx0XHRsZXQgbWVudUJ1dHRvbkluZm8gPSB1bmkuZ2V0TWVudUJ1dHRvbkJvdW5kaW5nQ2xpZW50UmVjdCgpXG5cdFx0XHR0aGlzLmJ1YmJsZUJhckhlaWdodCA9IChtZW51QnV0dG9uSW5mby50b3AgLSB0aGlzLnN0YXR1c0JhckhlaWdodCkgKiAyICsgbWVudUJ1dHRvbkluZm8uaGVpZ2h0XG5cdFx0XHQqL1xuXHRcdH0sXG5cdFx0b25TaG93KCkge1xuXHRcdFx0bGV0IHN5c3RlbUluZm8gPSB1bmkuZ2V0U3lzdGVtSW5mb1N5bmMoKVxuXHRcdFx0dGhpcy5zdGF0dXNCYXJIZWlnaHQgPSBzeXN0ZW1JbmZvLnN0YXR1c0JhckhlaWdodFxuXHRcdFx0bGV0IG1lbnVCdXR0b25JbmZvID0gdW5pLmdldE1lbnVCdXR0b25Cb3VuZGluZ0NsaWVudFJlY3QoKVxuXHRcdFx0dGhpcy5idWJibGVCYXJIZWlnaHQgPSAobWVudUJ1dHRvbkluZm8udG9wIC0gdGhpcy5zdGF0dXNCYXJIZWlnaHQpICogMiArIG1lbnVCdXR0b25JbmZvLmhlaWdodFxuXHRcdFx0XG5cdFx0fSxcblx0XHRtZXRob2RzOiB7XG5cblx0XHR9XG5cdH07XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuXHRAaW1wb3J0IFwiaW5kZXguY3NzXCI7XG5cbjwvc3R5bGU+XG4ifQ==

### 重现步骤

<template>
  <nut-icon name="dou-arrow-up" class="nut-icon-am-jump nut-icon-am-infinite"></nut-icon>
  <nut-icon name="star-fill-n" class="nut-icon-am-blink nut-icon-am-infinite"></nut-icon>
  <nut-icon name="refresh2" class="nut-icon-am-rotate nut-icon-am-infinite"></nut-icon>
  <nut-icon name="heart-fill" class="nut-icon-am-breathe nut-icon-am-infinite"></nut-icon>
  <nut-icon name="microphone" class="nut-icon-am-flash nut-icon-am-infinite"></nut-icon>
  <nut-icon name="download" class="nut-icon-am-bounce nut-icon-am-infinite"></nut-icon>
  <nut-icon name="message" class="nut-icon-am-shake nut-icon-am-infinite"></nut-icon>
</template>

<style>
  .nut-icon{
    --animate-duration: 1s ; 
    --animate-delay: 0s;
  }
</style>

![image](https://github.com/jdf2e/nutui/assets/57364350/2cde1169-540f-42f4-be75-24227905cf16)

### 期望的结果是什么？

icon正常动画

### 实际的结果是什么？

无反应，怎么样都没反应....

### 环境信息

System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 18.08 GB / 31.90 GB
  Binaries:
    Node: 20.10.0 - E:\nodejs\node.EXE
    npm: 10.2.3 - E:\nodejs\npm.CMD
    pnpm: 8.15.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.3527

### 其他补充信息

头都大了 就是不动起来这个图标

**Comment by eiinu** [comment]
NutUI uniapp 版本的相关问题需要到对应的代码仓库进行反馈
