### ISSUE TITLE
nut-picker 连续点击两次确定后，会重复弹出picker框~

### ISSUE THREAD

**Issue by yyccQQu** [jdf2e/nutui#310]
## 你想知道什么？

你好，我想知道这个项目是否可以 连续点击n次确定后,picker框收起而不是弹出

## 描述你考虑过的替代方案

我想...
第一次点击设置为 true,第二次为false，操作完成后，再重新设置为true。这种方法终究不是完美次，只是为了解决而解决，希望作者优化一下，thx~！
<img width="390" alt="截屏2020-08-19 下午3 01 23" src="https://user-images.githubusercontent.com/32674176/90627522-1c095200-e22d-11ea-93c4-cb0c65f6d108.png">

**Comment by richard1015** [comment]
马上修复

**Comment by richard1015** [comment]
已修复
