### ISSUE TITLE
input无法输入内容

### ISSUE THREAD

**Issue by txzh007** [jdf2e/nutui#3100]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.9

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIjtcbmNvbnN0IHZhbCA9IHJlZihcIlwiKTtcbjwvc2NyaXB0PlxuPHRlbXBsYXRlPlxuICAgICA8bnV0LWlucHV0IHYtbW9kZWw9XCJ2YWxcIiBwbGFjZWhvbGRlcj1cIlBsYWNlaG9sZGVyXCIgLz5cblxuPC90ZW1wbGF0ZT4ifQ==

### 重现步骤

使用手脚架初始化了一个 vue3-NutUI4模版，nut-input无法输入内容

### 期望的结果是什么？

修复结果

### 实际的结果是什么？

无法正常使用

### 环境信息

👽 Taro v3.6.30

  Taro CLI 3.6.30 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.30 => 3.6.30
      @tarojs/components: 3.6.30 => 3.6.30
      @tarojs/helper: 3.6.30 => 3.6.30
      @tarojs/plugin-framework-vue3: 3.6.30 => 3.6.30
      @tarojs/plugin-html: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-alipay: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-h5: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-jd: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-qq: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-swan: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-tt: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-weapp: 3.6.30 => 3.6.30
      @tarojs/runtime: 3.6.30 => 3.6.30
      @tarojs/shared: 3.6.30 => 3.6.30
      @tarojs/taro: 3.6.30 => 3.6.30
      @tarojs/taro-loader: 3.6.30 => 3.6.30
      @tarojs/webpack5-runner: 3.6.30 => 3.6.30
      babel-preset-taro: 3.6.30 => 3.6.30
      eslint-config-taro: 3.6.30 => 3.6.30

**Comment by zhm5921** [comment]
"@nutui/nutui-taro": "^4.3.9",
"@tarojs/taro": "3.6.32",

遇到同样问题 <nut-input  placeholder="请输入搜索关键词"   />  在微信小程序 ， 不能输入，焦点直接无法获取

**Comment by wangz-code** [comment]
我遇到了 所有的输入框都不能输入数据

**Comment by stupidream** [comment]
@eiinu h5页面不会有这种情况，小程序就无法输入
