### ISSUE TITLE
input 无法输入 好像一直是只读状态

### ISSUE THREAD

**Issue by wangz-code** [jdf2e/nutui#3103]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.0

### 平台

weapp

### 重现链接

https://github.com/wangz-code/vue3-NutUI4-bug/tree/main

### 重现步骤

taro init myApp

选择模板 vue3-NutUI4
执行  npm run dev:weapp

就能复现了

### 期望的结果是什么？

能输入数据

### 实际的结果是什么？

无法输入

### 环境信息

微信开发者工具 
稳定版 [Stable Build](https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html) (1.06.2405020)

👽 Taro v3.6.32

  Taro CLI 3.6.32 environment info:
    System:
      OS: macOS 13.5.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.32 => 3.6.32 
      @tarojs/components: 3.6.32 => 3.6.32 
      @tarojs/helper: 3.6.32 => 3.6.32 
      @tarojs/plugin-framework-vue3: 3.6.32 => 3.6.32 
      @tarojs/plugin-html: 3.6.32 => 3.6.32 
      @tarojs/plugin-platform-alipay: 3.6.32 => 3.6.32 
      @tarojs/plugin-platform-h5: 3.6.32 => 3.6.32 
      @tarojs/plugin-platform-jd: 3.6.32 => 3.6.32 
      @tarojs/plugin-platform-qq: 3.6.32 => 3.6.32 
      @tarojs/plugin-platform-swan: 3.6.32 => 3.6.32 
      @tarojs/plugin-platform-tt: 3.6.32 => 3.6.32 
      @tarojs/plugin-platform-weapp: 3.6.32 => 3.6.32 
      @tarojs/runtime: 3.6.32 => 3.6.32 
      @tarojs/shared: 3.6.32 => 3.6.32 
      @tarojs/taro: 3.6.32 => 3.6.32 
      @tarojs/taro-loader: 3.6.32 => 3.6.32 
      @tarojs/webpack5-runner: 3.6.32 => 3.6.32 
      babel-preset-taro: 3.6.32 => 3.6.32 
      eslint-config-taro: 3.6.32 => 3.6.32 

### 其他补充信息

webpack5

**Comment by stupidream** [comment]
我也遇到了，他们都不测试一下吗

**Comment by stupidream** [comment]
本来还想着用这个来开发，一上手就劝退了

**Comment by stupidream** [comment]
我的是支付宝小程序，无法输入，但h5页面可以输入
![20240620002855](https://github.com/jdf2e/nutui/assets/19191904/b1abbabc-db83-4375-b8ce-a42fcb7b0690)

**Comment by stupidream** [comment]
我的是支付宝小程序，无法输入，但h5页面可以输入
![20240620002855](https://github.com/jdf2e/nutui/assets/19191904/b1abbabc-db83-4375-b8ce-a42fcb7b0690)

**Comment by eiinu** [comment]
初步排查了一下，发现是在 vue 版本 ＞= 3.4.28(2024-06-14) 时出现的问题。
与此相关的问题反馈也都晚于这个版本时间。
具体原因和修复方式还要进一步确认。

**Comment by qilimazhualuo** [comment]
我今天重新安装了依赖就无法输入了 emm

**Comment by qilimazhualuo** [comment]
插个眼 是什么东西更新了吧

**Comment by qilimazhualuo** [comment]
[package.json](https://github.com/user-attachments/files/15908452/package.json)
[package-lock.json](https://github.com/user-attachments/files/15908453/package-lock.json)
对了我的vue版本3.2.40
这个package.json 现在安装就不行不能输入 但是我几天前安装生成的这个package-loack.json装的依赖就是可以输入的应该是某个依赖更新不对了
我不太懂这个lock文件，有大佬来看看嘛

**Comment by qilimazhualuo** [comment]
对比了下vue版本确实从3.4.27改到3.4.29了 但是其他的改动也很大

**Comment by wangz-code** [comment]
我根据上面eiinu 老哥说的 把 vue版本降级到  "vue": "^3.4.27",  就能正常输入了   又不是不能用 [[社会社会]]

**Comment by stupidream** [comment]
确实vue版本小于3.4.28就能用了

**Comment by stupidream** [comment]
确实vue版本小于3.4.28就能用了

**Comment by hn2wangcan** [comment]
> 确实vue版本小于3.4.28就能用了

多谢总结

**Comment by gaoguxing** [comment]
> 初步排查了一下，发现是在 vue 版本 ＞= 3.4.28(2024-06-14) 时出现的问题。 与此相关的问题反馈也都晚于这个版本时间。 具体原因和修复方式还要进一步确认。

其实vue >= 3.4.28后的版本，影响的不仅是input，DatePicker 日期选择器也会出现问题，症状就是自动回弹初始值。

**Comment by eiinu** [comment]
> > 初步排查了一下，发现是在 vue 版本 ＞= 3.4.28(2024-06-14) 时出现的问题。 与此相关的问题反馈也都晚于这个版本时间。 具体原因和修复方式还要进一步确认。
> 
> 其实vue >= 3.4.28后的版本，影响的不仅是input，DatePicker 日期选择器也会出现问题，症状就是自动回弹初始值。

在这个版本之后，直接使用 Taro 的 picker-view 组件就会自动回弹。NutUI 的 DatePicker 内部使用了这个组件，所以会有同样的问题。

这样看还是需要 Taro 去做修复。

**Comment by eiinu** [comment]
taro 上的关联 issue：https://github.com/NervJS/taro/issues/15946 https://github.com/NervJS/taro/issues/15950

vue 社区中也有关于 3.4.28 版本中 prop、attribute 逻辑修改的问题反馈和修复，不过不确定它与我们遇到的问题是否直接相关，需要再看看

**Comment by eiinu** [comment]
vue 3.4.30 已修复相关问题
