### ISSUE TITLE
icon图标无法正常显示@nutui/nutui-taro": "^4.3.10 ",@nutui/icons-vue-taro": "^0.0.9"

### ISSUE THREAD

**Issue by DU-bai** [jdf2e/nutui#3116]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.10

### 平台

weapp

### 重现链接

git@github.com:DU-bai/nutui-button-issue.git

### 重现步骤

执行dev:weapp脚本后在微信开发者工具中预览

### 期望的结果是什么？

正常显示icon

### 实际的结果是什么？

无法显示icon

Failed to resolve component: IconFont
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Index tid="pages/index/index?$taroTimestamp=1719748228830" option= {} > 
  at <Anonymous key="pages/index/index?$taroTimestamp=1719748228830" > 
  at <App>

### 环境信息

  Taro CLI 3.6.32 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.15.0 - D:\nodejs\node.EXE
      npm: 10.7.0 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.32 => 3.6.32
      @tarojs/components: 3.6.32 => 3.6.32
      @tarojs/components-rn: ^3.6.32 => 3.6.32
      @tarojs/helper: 3.6.32 => 3.6.32
      @tarojs/plugin-framework-vue3: 3.6.32 => 3.6.32       
      @tarojs/plugin-html: ^3.6.32 => 3.6.32
      @tarojs/plugin-platform-alipay: 3.6.32 => 3.6.32      
      @tarojs/plugin-platform-h5: 3.6.32 => 3.6.32
      @tarojs/plugin-platform-jd: 3.6.32 => 3.6.32
      @tarojs/plugin-platform-qq: 3.6.32 => 3.6.32
      @tarojs/plugin-platform-swan: 3.6.32 => 3.6.32        
      @tarojs/plugin-platform-tt: 3.6.32 => 3.6.32
      @tarojs/plugin-platform-weapp: 3.6.32 => 3.6.32       
      @tarojs/rn-runner: ^3.6.32 => 3.6.32
      @tarojs/rn-supporter: ^3.6.32 => 3.6.32
      @tarojs/runtime: 3.6.32 => 3.6.32
      @tarojs/runtime-rn: ^3.6.32 => 3.6.32
      @tarojs/shared: 3.6.32 => 3.6.32
      @tarojs/taro: 3.6.32 => 3.6.32
      @tarojs/taro-loader: 3.6.32 => 3.6.32
      @tarojs/taro-rn: ^3.6.32 => 3.6.32
      @tarojs/webpack5-runner: 3.6.32 => 3.6.32
      babel-preset-taro: 3.6.32 => 3.6.32
      eslint-config-taro: 3.6.32 => 3.6.32
      expo: ~47.0.3 => 47.0.14
      react: ^18.1.0 => 18.3.1
      react-native: ^0.70.5 => 0.70.15

**Comment by DU-bai** [comment]
[Vue warn]: Failed to resolve component: IconFont
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Index tid="pages/activity/index?$taroTimestamp=1719749707574" option= {} > 
  at <Anonymous key="pages/activity/index?$taroTimestamp=1719749707574" > 
  at <App>

[WXML Runtime warning] ./base.wxml
 Template `tmpl_0_iconfont` not found.
  2 | <template name="taro_tmpl">
  3 |   <block wx:for="{{root.cn}}" wx:key="sid">
> 4 |     <template is="{{xs.a(0, item.nn, '')}}" data="{{i:item,c:1,l:xs.f('',item.nn)}}" />
    |                  ^
  5 |   </block>
  6 | </template>
  7 |

**Comment by eiinu** [comment]
vue 组件全局注册：
`app.component(组件名, IconFont)`

**Comment by DU-bai** [comment]
> vue 组件全局注册： `app.component(组件名, IconFont)`

已解决 期望文档中补充

**Comment by Yomaris** [comment]
> vue 组件全局注册： `app.component(组件名, IconFont)`

我用 @nutui/icons-react-taro，编译以后没有icon元素，需要咋解决

**Comment by ww85600** [comment]
我的是缺了什么嘛 我的解决不了

**Comment by ww85600** [comment]
> vue 组件全局注册： `app.component(组件名, IconFont)`

未解决啊 还是依然不显示
