### ISSUE TITLE
[suggest]希望能出一个类mobile.ant.design的popover功能

### ISSUE THREAD

**Issue by zhuangxiaohui** [jdf2e/nutui#312]
## 你建议我们做什么？
希望能出一个类mobile.ant.design的popover功能， https://mobile.ant.design/kitchen-sink/components/popover
popover在手机中的使用场景较多，之前写小程序的使用用到过，希望你们团队可以做出来一个，目前的公众号项目中也想使用popover功能，但是nutui框架中没有
![image](https://user-images.githubusercontent.com/5791725/90750320-36176300-e307-11ea-9bd3-eae860d6cfe8.png)
微信
![image](https://user-images.githubusercontent.com/5791725/90750387-50514100-e307-11ea-9a69-0333775974c7.png)
QQAPP
![image](https://user-images.githubusercontent.com/5791725/90750420-59421280-e307-11ea-8f3e-ebc07e716423.png)
支付宝
![image](https://user-images.githubusercontent.com/5791725/90750444-60692080-e307-11ea-89bf-01eaa5830d85.png)

**Comment by richard1015** [comment]
感谢反馈，我们近期处理一下

**Comment by transtone** [comment]
> 感谢反馈，我们近期处理一下

@richard1015 
一年多了，处理的怎么样了？

**Comment by richard1015** [comment]
> > 感谢反馈，我们近期处理一下
> 
> @richard1015
> 一年多了，处理的怎么样了？

3.1.7发布， 当前正在开发中 70%

**Comment by richard1015** [comment]
3.1.7已新增
