### ISSUE TITLE
CalendarCard组件兼容性问题

### ISSUE THREAD

**Issue by zhangkaidi1** [jdf2e/nutui#3121]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.8

### 平台

h5

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbi8vIOaXtumXtOmZkOWItlxuY29uc3QgZGlzYWJsZURheSA9IChkYXkpPT57XG4gICByZXR1cm4gbmV3IERhdGUoYCR7ZGF5LnllYXJ9LSR7ZGF5Lm1vbnRofS0ke2RheS5kYXRlfWApID49IG5ldyBEYXRlKERhdGUubm93KCkpXG59XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgICA8bnV0LWNhbGVuZGFyLWNhcmRcbiAgICAgXHQgdi1tb2RlbD1cImFjdHVhbFZpc2l0RGF0ZVwiIFxuICAgICAgIEBjaGFuZ2U9XCJvbkNoYW5nZVwiICAgICAgICAgICAgICBcbiAgICAgICA6ZGlzYWJsZS1kYXk9XCJkaXNhYmxlRGF5XCJcbiAgICA+PC9udXQtY2FsZW5kYXItY2FyZD5cbjwvdGVtcGxhdGU+In0=

### 重现步骤

vue3工程，引用CalendarCard组件，设置disableDay 属性，移动端ios系统不生效

### 期望的结果是什么？

CalendarCard disableDay 属性，安卓生效，ios生效

### 实际的结果是什么？

CalendarCard disableDay 属性，安卓生效，ios不生效

**Comment by eiinu** [comment]
iOS 下 Date xxxx-xx-xx 不合法
