### ISSUE TITLE
Checkbox Taro 提供的 vue3-NutUI4 模板使用官方提供的全半选例子有问题

### ISSUE THREAD

**Issue by Bbyford** [jdf2e/nutui#3131]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.0.4

### 平台

weapp

### 重现链接

官方 Checkbox 全半选例子

### 重现步骤

利用Taro提供的模板初始化项目并导入官方Checkbox 全半选例子

### 期望的结果是什么？

能够正常半选

### 实际的结果是什么？

无法正常半选，但是将  "@nutui/nutui-taro":版本到"4.3.8"能够正常运行

### 其他补充信息

有没有考虑下更新下官方提供的模板"@nutui/nutui-taro"版本

**Comment by eiinu** [comment]
模板项目中没有 lock 文件，按照正常的逻辑，安装依赖时应该会自动下载最新版本的包才对🤔
需要再排查下模板项目的配置

**Comment by Bbyford** [comment]
> 模板项目中没有 lock 文件，按照正常的逻辑，安装依赖时应该会自动下载最新版本的包才对🤔 需要再排查下模板项目的配置

可能是我项目锁了版本的问题
