### ISSUE TITLE
求助:请问我upload 的组件该怎么对我选择的文件进行操作？

### ISSUE THREAD

**Issue by SuperBug-RhysLiu** [jdf2e/nutui#3132]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

latest

### 平台

weapp

### 重现链接

暂无

### 重现步骤

暂无

### 期望的结果是什么？

我现在没有方法可以操作选择的file ,不管是chooseImage 还是beforeXhrUpload 其实都不符合我想要的预期，我只是想要操作比如taro. chooseImage后success的返回值而已### 

### 实际的结果是什么？

chooseImage 只是单纯的调用事件。。
beforeXhrUpload 我该怎么修改fileItme...?

**Comment by daiwanxing** [comment]
可以监听 `<nut-uploader />` 组件的 `change`  事件拿到 `Taro.chooseImage`  success 回调的返回值

**Comment by SuperBug-RhysLiu** [comment]
> 可以监听 `<nut-uploader />` 组件的 `change` 事件拿到 `Taro.chooseImage` success 回调的返回值
没事了，在小程序里我这样拿不到 file对象的值， 只能拿到一个虚拟内存映射， 我改接口了
