### ISSUE TITLE
[bug]做国际化多语言版本切换时，跟vue-i18n搭配使用，会出错，无法正常使用

### ISSUE THREAD

**Issue by cleack5** [jdf2e/nutui#315]
# main.js文件代码：
```js
import Vue from 'vue';
import NutUI from '@nutui/nutui';
import '@nutui/nutui/dist/nutui.scss';
import VueI18n from 'vue-i18n';

import enUS from '@nutui/nutui/dist/locales/lang/en-US';
import myEnUs from './locales/en/en.json';

import App from './App.vue';

Vue.use(VueI18n);
Vue.locale = () => {};

Vue.use(NutUI);

Vue.config.productionTip = false;

Object.assign(enUS, myEnUs);

const i18nCfg = new VueI18n({
  locale: 'en-US',
  messages: {
    'en-US': enUS,
  },
});

new Vue({
  i18n: i18nCfg,
  render: (h) => h(App),
}).$mount('#app');



```

# App.vue代码

```js
<style scoped></style>
<template>
  <div>
    <nut-buttongroup>
      <nut-button type="light">
        重置
      </nut-button>
      <nut-button @click="test">
        确定
      </nut-button>
    </nut-buttongroup>
  </div>
</template>
<script>
export default {
  data() {
    return {};
  },
  computed: {},
  components: {},
  methods: {
    test() {
      this.$dialog({
        title: '确定删除此订单？',
        content: '删除后将从你的记录里消失，无法找回',
      });
    },
  },
  created() {},
  mounted() {},
};
</script>


```

# 环境信息

- "@nutui/nutui": "^2.2.10"
- "vue-i18n": "^8.21.0"

点击确定按钮就出错：
```
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property '_t' of undefined
    at VueComponent.Vue.$t (vue-i18n.esm.js?a925:196)
    at VueComponent.vueI18nHandler (nutui.js?3822:1892)
    at VueComponent.i18n (nutui.js?3822:1897)
    at VueComponent.nutTranslate (nutui.js?3822:2269)
    at Proxy.dialogvue_type_template_id_a052a778_render (nutui.js?3822:2258)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3548)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4066)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
    at Watcher.run (vue.runtime.esm.js?2b0e:4554)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4310)
```

**Comment by guoxiao158** [comment]
> # main.js文件代码：
> ```js
> import Vue from 'vue';
> import NutUI from '@nutui/nutui';
> import '@nutui/nutui/dist/nutui.scss';
> import VueI18n from 'vue-i18n';
> 
> import enUS from '@nutui/nutui/dist/locales/lang/en-US';
> import myEnUs from './locales/en/en.json';
> 
> import App from './App.vue';
> 
> Vue.use(VueI18n);
> Vue.locale = () => {};
> 
> Vue.use(NutUI);
> 
> Vue.config.productionTip = false;
> 
> Object.assign(enUS, myEnUs);
> 
> const i18nCfg = new VueI18n({
>   locale: 'en-US',
>   messages: {
>     'en-US': enUS,
>   },
> });
> 
> new Vue({
>   i18n: i18nCfg,
>   render: (h) => h(App),
> }).$mount('#app');
> ```
> 
> # App.vue代码
> ```js
> <style scoped></style>
> <template>
>   <div>
>     <nut-buttongroup>
>       <nut-button type="light">
>         重置
>       </nut-button>
>       <nut-button @click="test">
>         确定
>       </nut-button>
>     </nut-buttongroup>
>   </div>
> </template>
> <script>
> export default {
>   data() {
>     return {};
>   },
>   computed: {},
>   components: {},
>   methods: {
>     test() {
>       this.$dialog({
>         title: '确定删除此订单？',
>         content: '删除后将从你的记录里消失，无法找回',
>       });
>     },
>   },
>   created() {},
>   mounted() {},
> };
> </script>
> ```
> 
> # 环境信息
> * "@nutui/nutui": "^2.2.10"
> * "vue-i18n": "^8.21.0"
> 
> 点击确定按钮就出错：
> 
> ```
> vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property '_t' of undefined
>     at VueComponent.Vue.$t (vue-i18n.esm.js?a925:196)
>     at VueComponent.vueI18nHandler (nutui.js?3822:1892)
>     at VueComponent.i18n (nutui.js?3822:1897)
>     at VueComponent.nutTranslate (nutui.js?3822:2269)
>     at Proxy.dialogvue_type_template_id_a052a778_render (nutui.js?3822:2258)
>     at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3548)
>     at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4066)
>     at Watcher.get (vue.runtime.esm.js?2b0e:4479)
>     at Watcher.run (vue.runtime.esm.js?2b0e:4554)
>     at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4310)
> ```

`Vue.use(VueI18n);
Vue.locale = () => {};
// 将语言包进行合并
const messages = {
 en: {
 ...enUS,
 ...enLocale
 },
 zh: {
 ...zhCN,
 ...zhLocale
 }
}

const i18n = new VueI18n({
 locale: 'zh', // 设置默认语言
 messages: messages // 设置资源文件对象
})
//
const app = new Vue({
 el: '#app',
 i18n
})`

具体参考 文章 https://jelly.jd.com/article/5ec4ca4428979a015430ee75  在最后一部分有详细介绍
