### ISSUE TITLE
InfiniteLoading 引入该组件无法使用

### ISSUE THREAD

**Issue by xuhao666** [jdf2e/nutui#3151]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.7

### 平台

h5

### 重现链接

http://10.0.27.64:10086/pages/index/list

### 重现步骤

上面地址随便填的，不然无法提交
热更新直接编译报错
export 'InfiniteLoading' (imported as '__unplugin_components_4') was not found in '@nutui/nutui-taro' (possible exports: ActionSheet, Address, AddressList, Animate, Avatar, AvatarCropper, AvatarGroup, Backtop, Badge, Barrage, Button, Calendar, CalendarCard, Card, Cascader, Category, CategoryPane, Cell, CellGroup, Checkbox, CheckboxGroup, CircleProgress, Col, Collapse, CollapseItem, Comment, ConfigProvider, Countdown, Countup, DatePicker, Dialog, Divider, Drag, Ecard, Elevator, Ellipsis, Empty, FixedNav, Form, FormItem, Grid, GridItem, ImagePreview, Indicator, Input, InputNumber, Invoice, Layout, List, Locale, Menu, MenuItem, Navbar, Noticebar, Notify, NumberKeyboard, Overlay, Pagination, Picker, Popover, Popup, Price, Progress, Radio, RadioGroup, Range, Rate, Row, Searchbar, ShortPassword, SideNavbar, SideNavbarItem, Signature, Skeleton, Sku, Space, Step, Steps, Sticky, SubSideNavbar, Swipe, SwipeGroup, Swiper, SwiperItem, Switch, TabPane, Tabbar, TabbarItem, Table, Tabs, Tag, Textarea, TimeDetail, TimePannel, TimeSelect, Toast, Tour, TrendArrow, Uploader, Watermark, default, install, version)
**发现node_modules包内InfiniteLoading组件没有.mjs文件**重新npm install安装多次，均没有生成.mjs文件

### 期望的结果是什么？

编辑时没有任何报错，组件可以正常使用且在node_modules包内InfiniteLoading组件下面有.mjs文件生成

### 实际的结果是什么？

引入组件直接编译报错
export 'InfiniteLoading' (imported as '__unplugin_components_4') was not found in '@nutui/nutui-taro' (possible exports: ActionSheet, Address, AddressList, Animate, Avatar, AvatarCropper, AvatarGroup, Backtop, Badge, Barrage, Button, Calendar, CalendarCard, Card, Cascader, Category, CategoryPane, Cell, CellGroup, Checkbox, CheckboxGroup, CircleProgress, Col, Collapse, CollapseItem, Comment, ConfigProvider, Countdown, Countup, DatePicker, Dialog, Divider, Drag, Ecard, Elevator, Ellipsis, Empty, FixedNav, Form, FormItem, Grid, GridItem, ImagePreview, Indicator, Input, InputNumber, Invoice, Layout, List, Locale, Menu, MenuItem, Navbar, Noticebar, Notify, NumberKeyboard, Overlay, Pagination, Picker, Popover, Popup, Price, Progress, Radio, RadioGroup, Range, Rate, Row, Searchbar, ShortPassword, SideNavbar, SideNavbarItem, Signature, Skeleton, Sku, Space, Step, Steps, Sticky, SubSideNavbar, Swipe, SwipeGroup, Swiper, SwiperItem, Switch, TabPane, Tabbar, TabbarItem, Table, Tabs, Tag, Textarea, TimeDetail, TimePannel, TimeSelect, Toast, Tour, TrendArrow, Uploader, Watermark, default, install, version)

**Comment by eiinu** [comment]
`@nutui/nutui-taro` 没有提供 InfiniteLoading 组件，建议直接使用 Taro 的 ScrollView 组件替代
