### ISSUE TITLE
自定义tabbar无法使用icons-vue-taro组件

### ISSUE THREAD

**Issue by Swarz** [jdf2e/nutui#3154]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.11

### 平台

weapp

### 重现链接

https://gitee.com/Swarz/examples/tree/master/tabbar

### 重现步骤

仓库中的tabbar项目
yarn后微信打开

### 期望的结果是什么？

自定义tabbar可以使用图标

### 实际的结果是什么？

自定义tabbar图标不显示，nut-tabbar看起来没问题，问题就是使用不了图标

### 环境信息

� Taro v3.6.34

  Taro CLI 3.6.34 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.34 => 3.6.34
      @tarojs/components: 3.6.34 => 3.6.34
      @tarojs/helper: 3.6.34 => 3.6.34
      @tarojs/plugin-framework-vue3: 3.6.34 => 3.6.34
      @tarojs/plugin-html: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-alipay: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-h5: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-jd: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-qq: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-swan: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-tt: 3.6.34 => 3.6.34
      @tarojs/plugin-platform-weapp: 3.6.34 => 3.6.34
      @tarojs/runtime: 3.6.34 => 3.6.34
      @tarojs/shared: 3.6.34 => 3.6.34
      @tarojs/taro: 3.6.34 => 3.6.34
      @tarojs/taro-loader: 3.6.34 => 3.6.34
      @tarojs/webpack5-runner: 3.6.34 => 3.6.34
      babel-preset-taro: 3.6.34 => 3.6.34
      eslint-config-taro: 3.6.34 => 3.6.34

**Comment by eiinu** [comment]
redirect to #2138
