### ISSUE TITLE
textarea 加载缓慢

### ISSUE THREAD

**Issue by ice909** [jdf2e/nutui#3155]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.1.6

### 平台

h5, weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIlxuaW1wb3J0IHsgRG9uZ2RvbmcgfSBmcm9tICdAbnV0dWkvaWNvbnMtdnVlJ1xuY29uc3QgcG9zdGluZ0NvbnRlbnQgPSByZWYoJycpXG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgICA8bnV0LXRleHRhcmVhIHYtbW9kZWw9XCJwb3N0aW5nQ29udGVudFwiIDphdXRvc2l6ZT1cInsgbWF4SGVpZ2h0OiA1MDAsIG1pbkhlaWdodDogMjAwIH1cIiBwbGFjZWhvbGRlcj1cIuivt+i+k+WFpeW4luWtkOWGheWuuVwiXG4gICAgICAgIGxpbWl0LXNob3cgOm1heC1sZW5ndGg9XCI1MDAwMFwiIC8+XG48L3RlbXBsYXRlPiJ9

### 重现步骤

页面渲染时,textarea 渲染缓慢,体验不好
![image](https://github.com/user-attachments/assets/ff42eb9f-d5ea-4a0c-83fc-7406d5f9edbc)

https://github.com/user-attachments/assets/f4cf1f7f-2c1b-4413-9214-7553a54f22ab

### 期望的结果是什么？

textarea 能够和其他组件一样快速加载

### 实际的结果是什么？

加载缓慢

### 环境信息

👽 Taro v3.6.20

  Taro CLI 3.6.20 environment info:
    System:
      OS: Linux 6.6 Deepin 23 23
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 20.14.0 - ~/.config/nvm/versions/node/v20.14.0/bin/node
      npm: 10.7.0 - ~/.config/nvm/versions/node/v20.14.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.20 => 3.6.20 
      @tarojs/components: 3.6.20 => 3.6.20 
      @tarojs/helper: 3.6.20 => 3.6.20 
      @tarojs/plugin-framework-vue3: 3.6.20 => 3.6.20 
      @tarojs/plugin-html: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-alipay: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-h5: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-jd: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-qq: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-swan: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-tt: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-weapp: 3.6.20 => 3.6.20 
      @tarojs/runtime: 3.6.20 => 3.6.20 
      @tarojs/shared: 3.6.20 => 3.6.20 
      @tarojs/taro: 3.6.20 => 3.6.20 
      @tarojs/taro-loader: 3.6.20 => 3.6.20 
      @tarojs/webpack5-runner: 3.6.20 => 3.6.20 
      babel-preset-taro: 3.6.20 => 3.6.20 
      eslint-config-taro: 3.6.20 => 3.6.20 

### 其他补充信息

vue 3.3.4

**Comment by eiinu** [comment]
可以使用 Taro 原生的 Textarea 组件，兼容性更好
https://taro-docs.jd.com/docs/components/forms/textarea

**Comment by ice909** [comment]
@eiinu 这个没得修吗
