### ISSUE TITLE
组件预览demo为什么删掉了？？

### ISSUE THREAD

**Issue by wiiyee** [jdf2e/nutui#3159]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.12

### 平台

h5

### 重现链接

https://nutui.jd.com/h5/vue/4x/index.html#/zh-CN/component/table

### 重现步骤

打开官网，选择组件，右侧没有显示demo

### 期望的结果是什么？

打开官网，选择组件，右侧demo正常展示

### 实际的结果是什么？

打开官网，选择组件，右侧没有显示demo

**Comment by Lance-Lam** [comment]
是不是得等到周一上班了才有人处理😂

**Comment by XBfinal** [comment]
估计周一上班v瑷珲处理吧

**Comment by XBfinal** [comment]
估计周一上班才会处理

**Comment by JessWCL** [comment]
周一上午10:38, 到现在还是没人处理和回应

**Comment by Miles-hxy** [comment]
现在修复了看看
