### ISSUE TITLE
使用taro的vite版本时，配置unplugin-vue-components自动按需引入报错

### ISSUE THREAD

**Issue by ohblue** [jdf2e/nutui#3174]
### NutUI 包名

@nutui/nutui-taro

### NutUI 版本号

4.3.12

### 平台

weapp

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHNob3dUb2FzdCB9IGZyb20gJ0BudXR1aS9udXR1aSdcbmltcG9ydCB7IERvbmdkb25nIH0gZnJvbSAnQG51dHVpL2ljb25zLXZ1ZSdcbmNvbnN0IHNob3cgPSAoKSA9PiB7XG4gIHNob3dUb2FzdC50ZXh0KCdIZWxsbywgTnV0VUkhJylcbn07XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPG51dC1jZWxsIHRpdGxlPVwiQ2xpY2sgdG8gc2hvdyBUb2FzdFwiIGlzLWxpbmsgQGNsaWNrPVwic2hvd1wiPlxuICAgIDx0ZW1wbGF0ZSAjbGluaz5cbiAgICAgIDxEb25nZG9uZyAvPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvbnV0LWNlbGw+XG48L3RlbXBsYXRlPiIsImNvbmZpZy5qcyI6ImltcG9ydCB7IGRlZmluZUNvbmZpZyB9IGZyb20gJ0B0YXJvanMvY2xpJ1xuXG5pbXBvcnQgZGV2Q29uZmlnIGZyb20gJy4vZGV2J1xuaW1wb3J0IHByb2RDb25maWcgZnJvbSAnLi9wcm9kJ1xuXG5pbXBvcnQgQ29tcG9uZW50cyBmcm9tICd1bnBsdWdpbi12dWUtY29tcG9uZW50cy92aXRlJ1xuaW1wb3J0IE51dFVJUmVzb2x2ZXIgZnJvbSAnQG51dHVpL2F1dG8taW1wb3J0LXJlc29sdmVyJztcblxuLy8gaHR0cHM6Ly90YXJvLWRvY3MuamQuY29tL2RvY3MvbmV4dC9jb25maWcjZGVmaW5lY29uZmlnLei+heWKqeWHveaVsFxuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29uZmlnKGFzeW5jIChtZXJnZSwgeyBjb21tYW5kLCBtb2RlIH0pID0+IHtcbiAgY29uc3QgYmFzZUNvbmZpZyA9IHtcbiAgICBwcm9qZWN0TmFtZTogJ21pbmlhcHAnLFxuICAgIGRhdGU6ICcyMDI0LTgtMTcnLFxuICAgIGRlc2lnbldpZHRoOiA3NTAsXG4gICAgZGV2aWNlUmF0aW86IHtcbiAgICAgIDY0MDogMi4zNCAvIDIsXG4gICAgICA3NTA6IDEsXG4gICAgICAzNzU6IDIsXG4gICAgICA4Mjg6IDEuODEgLyAyXG4gICAgfSxcbiAgICBzb3VyY2VSb290OiAnc3JjJyxcbiAgICBvdXRwdXRSb290OiAnZGlzdCcsXG4gICAgcGx1Z2luczogW1xuICAgICAgJ0B0YXJvanMvcGx1Z2luLWh0bWwnLFxuICAgICAgLy8g5byA5ZCvIHVucGx1Z2luIOaPkuS7tu+8jOiHquWKqOaMiemcgOW8leWFpSBOdXRVSSDnu4Tku7ZcbiAgICAgIENvbXBvbmVudHMoe1xuICAgICAgICByZXNvbHZlcnM6IFtOdXRVSVJlc29sdmVyKCldXG4gICAgICB9KSxcbiAgICBdLFxuICAgIGRlZmluZUNvbnN0YW50czoge1xuICAgIH0sXG4gICAgY29weToge1xuICAgICAgcGF0dGVybnM6IFtcbiAgICAgIF0sXG4gICAgICBvcHRpb25zOiB7XG4gICAgICB9XG4gICAgfSxcbiAgICBmcmFtZXdvcms6ICd2dWUzJyxcbiAgICBjb21waWxlcjogJ3ZpdGUnLFxuICAgIG1pbmk6IHtcbiAgICAgIHBvc3Rjc3M6IHtcbiAgICAgICAgcHh0cmFuc2Zvcm06IHtcbiAgICAgICAgICBlbmFibGU6IHRydWUsXG4gICAgICAgICAgY29uZmlnOiB7XG5cbiAgICAgICAgICB9XG4gICAgICAgIH0sXG4gICAgICAgIGNzc01vZHVsZXM6IHtcbiAgICAgICAgICBlbmFibGU6IGZhbHNlLCAvLyDpu5jorqTkuLogZmFsc2XvvIzlpoLpnIDkvb/nlKggY3NzIG1vZHVsZXMg5Yqf6IO977yM5YiZ6K6+5Li6IHRydWVcbiAgICAgICAgICBjb25maWc6IHtcbiAgICAgICAgICAgIG5hbWluZ1BhdHRlcm46ICdtb2R1bGUnLCAvLyDovazmjaLmqKHlvI/vvIzlj5blgLzkuLogZ2xvYmFsL21vZHVsZVxuICAgICAgICAgICAgZ2VuZXJhdGVTY29wZWROYW1lOiAnW25hbWVdX19bbG9jYWxdX19fW2hhc2g6YmFzZTY0OjVdJ1xuICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgfVxuICAgIH0sXG4gICAgaDU6IHtcbiAgICAgIHB1YmxpY1BhdGg6ICcvJyxcbiAgICAgIHN0YXRpY0RpcmVjdG9yeTogJ3N0YXRpYycsXG5cbiAgICAgIG1pbmlDc3NFeHRyYWN0UGx1Z2luT3B0aW9uOiB7XG4gICAgICAgIGlnbm9yZU9yZGVyOiB0cnVlLFxuICAgICAgICBmaWxlbmFtZTogJ2Nzcy9bbmFtZV0uW2hhc2hdLmNzcycsXG4gICAgICAgIGNodW5rRmlsZW5hbWU6ICdjc3MvW25hbWVdLltjaHVua2hhc2hdLmNzcydcbiAgICAgIH0sXG4gICAgICBwb3N0Y3NzOiB7XG4gICAgICAgIGF1dG9wcmVmaXhlcjoge1xuICAgICAgICAgIGVuYWJsZTogdHJ1ZSxcbiAgICAgICAgICBjb25maWc6IHt9XG4gICAgICAgIH0sXG4gICAgICAgIGNzc01vZHVsZXM6IHtcbiAgICAgICAgICBlbmFibGU6IGZhbHNlLCAvLyDpu5jorqTkuLogZmFsc2XvvIzlpoLpnIDkvb/nlKggY3NzIG1vZHVsZXMg5Yqf6IO977yM5YiZ6K6+5Li6IHRydWVcbiAgICAgICAgICBjb25maWc6IHtcbiAgICAgICAgICAgIG5hbWluZ1BhdHRlcm46ICdtb2R1bGUnLCAvLyDovazmjaLmqKHlvI/vvIzlj5blgLzkuLogZ2xvYmFsL21vZHVsZVxuICAgICAgICAgICAgZ2VuZXJhdGVTY29wZWROYW1lOiAnW25hbWVdX19bbG9jYWxdX19fW2hhc2g6YmFzZTY0OjVdJ1xuICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgfVxuICAgIH0sXG4gICAgcm46IHtcbiAgICAgIGFwcE5hbWU6ICd0YXJvRGVtbycsXG4gICAgICBwb3N0Y3NzOiB7XG4gICAgICAgIGNzc01vZHVsZXM6IHtcbiAgICAgICAgICBlbmFibGU6IGZhbHNlLCAvLyDpu5jorqTkuLogZmFsc2XvvIzlpoLpnIDkvb/nlKggY3NzIG1vZHVsZXMg5Yqf6IO977yM5YiZ6K6+5Li6IHRydWVcbiAgICAgICAgfVxuICAgICAgfVxuICAgIH1cbiAgfVxuICBpZiAocHJvY2Vzcy5lbnYuTk9ERV9FTlYgPT09ICdkZXZlbG9wbWVudCcpIHtcbiAgICAvLyDmnKzlnLDlvIDlj5HmnoTlu7rphY3nva7vvIjkuI3mt7fmt4bljovnvKnvvIlcbiAgICByZXR1cm4gbWVyZ2Uoe30sIGJhc2VDb25maWcsIGRldkNvbmZpZylcbiAgfVxuICAvLyDnlJ/kuqfmnoTlu7rphY3nva7vvIjpu5jorqTlvIDlkK/ljovnvKnmt7fmt4bnrYnvvIlcbiAgcmV0dXJuIG1lcmdlKHt9LCBiYXNlQ29uZmlnLCBwcm9kQ29uZmlnKVxufSlcbiJ9

### 重现步骤

在 //config/index.js 中配置：
```
import Components from 'unplugin-vue-components/vite'
import NutUIResolver from '@nutui/auto-import-resolver';
export default defineConfig(async (merge, { command, mode }) => {
  const baseConfig = {
    plugins: [
      '@tarojs/plugin-html',
      // 开启 unplugin 插件，自动按需引入 NutUI 组件
      Components({
        resolvers: [NutUIResolver()]
      }),
    ],
  }
})
```

### 期望的结果是什么？

实现按需引入

### 实际的结果是什么？

Taro 配置有误，请检查！ (/Users/chenm/Projects/miniapp/config/index.js)
  [!] 无法获取远程配置验证文件，将使用本地配置验证文件！
  [✗] plugins.0 的值 {"api":{"findComponent":"__function__","stringifyImport":"__function__"},"configResolved":"__function__","configureServer":"__function__","enforce":"post","name":"unplugin-vue-components","transform":"__function__","transformInclude":"__function__","vite":{"configResolved":"__function__","configureServer":"__function__"},"webpack":"__function__"} 不符合类型要求

### 环境信息

m1 mac

### 其他补充信息

官网上的例子是webpack的，不知道 vite 版本这么配置是否正确？

**Comment by ohblue** [comment]
参考了下taro官方文档自己解决了，写法如下提供给有需要的人：
```
import Components from 'unplugin-vue-components/vite'
import NutUIResolver from '@nutui/auto-import-resolver';
export default defineConfig(async (merge, { command, mode }) => {
  const baseConfig = {
    compiler: {
      'type': 'vite',
      'vitePlugins': [
        // 开启 unplugin 插件，自动按需引入 NutUI 组件
        Components({
          resolvers: [NutUIResolver({taro: true})]
        }),
      ]
    },
  }
})
```

**Comment by enjoy-myLife** [comment]
> 参考了下taro官方文档自己解决了，写法如下提供给有需要的人：
> 
> ```
> import Components from 'unplugin-vue-components/vite'
> import NutUIResolver from '@nutui/auto-import-resolver';
> export default defineConfig(async (merge, { command, mode }) => {
>   const baseConfig = {
>     compiler: {
>       'type': 'vite',
>       'vitePlugins': [
>         // 开启 unplugin 插件，自动按需引入 NutUI 组件
>         Components({
>           resolvers: [NutUIResolver({taro: true})]
>         }),
>       ]
>     },
>   }
> })
> ```

有相关配置嘛，我和你一样的配置，但是直接起不来了，报错taro.defineComponent is not a function，应该是插件没有注册成功

**Comment by zzq0324** [comment]
> > 参考了下taro官方文档自己解决了，写法如下提供给有需要的人：
> > ```
> > import Components from 'unplugin-vue-components/vite'
> > import NutUIResolver from '@nutui/auto-import-resolver';
> > export default defineConfig(async (merge, { command, mode }) => {
> >   const baseConfig = {
> >     compiler: {
> >       'type': 'vite',
> >       'vitePlugins': [
> >         // 开启 unplugin 插件，自动按需引入 NutUI 组件
> >         Components({
> >           resolvers: [NutUIResolver({taro: true})]
> >         }),
> >       ]
> >     },
> >   }
> > })
> > ```
> 
> 有相关配置嘛，我和你一样的配置，但是直接起不来了，报错taro.defineComponent is not a function，应该是插件没有注册成功

我也是报`taro.defineComponent is not a function`，你解决了吗
