### ISSUE TITLE
nut-date-picker 在pc端打开不能移动滚动日期选择 在移动端可以正常滚动日期

### ISSUE THREAD

**Issue by liangliang-prog** [jdf2e/nutui#3181]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

^4.3.11

### 平台

h5

### 重现链接

无

### 重现步骤

<nut-popup v-model:visible="timePicker.show" position="bottom">
            <nut-date-picker title="选择时间" v-model="timePicker.val" :type="timePicker.type" :min-date="timePicker.minDate"
                :max-date="timePicker.maxDate" @confirm="handleTime"
                @cancel="timePicker.show = false" is-show-chinese></nut-date-picker>
        </nut-popup>
在pc端微信打开不能移动滚动日期选择 在移动端可以正常滚动日期

### 期望的结果是什么？

在pc端和移动端都可以滚动日期选择

### 实际的结果是什么？

在pc端不能移动滚动日期选择

### 环境信息

System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 3.78 GB / 15.73 GB
  Binaries:
    Node: 20.1.0 - D:\DevTools\Nodes\node.EXE
    Yarn: 1.22.22 - D:\DevTools\Nodes\yarn.CMD
    npm: 9.6.4 - D:\DevTools\Nodes\npm.CMD
    pnpm: 8.15.7 - D:\DevTools\Nodes\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.105)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @nutui/nutui: ^4.3.11 => 4.3.12

### 其他补充信息

"vue": "^3.4.31","vite": "^5.3.4",

**Comment by liangliang-prog** [comment]
只处理了touch事件，没有对pointer进行处理
![微信图片_20240824175029](https://github.com/user-attachments/assets/b0e234dc-d58a-4a93-ace7-c95d476fec6a)

**Comment by eiinu** [comment]
https://nutui.jd.com/h5/vue/4x/#/zh-CN/guide/advanced

桌面端适配
