### ISSUE TITLE
Picker 选择器在PC的web端不能正常上下滑动

### ISSUE THREAD

**Issue by chineseqw** [jdf2e/nutui#3184]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.12

### 平台

h5

### 重现链接

no

### 重现步骤

<template>
  <nut-picker :columns="columns" title="城市选择" @confirm="confirm" />
</template>
<script setup>
import { ref } from 'vue'
const columns = ref([
  { text: '南京', value: 'Nanjing' },
  { text: '无锡', value: 'Wuxi' },
  { text: '海北', value: 'Haibei' },
  { text: '北京', value: 'Beijing' },
  { text: '连云港', value: 'Lianyungang' },
  { text: '长沙', value: 'Changsha' },
  { text: '武汉', value: 'Wuhan' }
])

const confirm = ({ selectedValue, selectedOptions }) => {
  console.log(selectedValue[0], selectedOptions[0])
}
</script>

### 期望的结果是什么？

Picker 选择器在PC的web端能正常上下滑动

### 实际的结果是什么？

Picker 选择器在PC的web端不能正常上下滑动

### 环境信息

<template>
  <nut-picker :columns="columns" title="城市选择" @confirm="confirm" />
</template>
<script setup>
import { ref } from 'vue'
const columns = ref([
  { text: '南京', value: 'Nanjing' },
  { text: '无锡', value: 'Wuxi' },
  { text: '海北', value: 'Haibei' },
  { text: '北京', value: 'Beijing' },
  { text: '连云港', value: 'Lianyungang' },
  { text: '长沙', value: 'Changsha' },
  { text: '武汉', value: 'Wuhan' }
])

const confirm = ({ selectedValue, selectedOptions }) => {
  console.log(selectedValue[0], selectedOptions[0])
}
</script>

### 其他补充信息

<template>
  <nut-picker :columns="columns" title="城市选择" @confirm="confirm" />
</template>
<script setup>
import { ref } from 'vue'
const columns = ref([
  { text: '南京', value: 'Nanjing' },
  { text: '无锡', value: 'Wuxi' },
  { text: '海北', value: 'Haibei' },
  { text: '北京', value: 'Beijing' },
  { text: '连云港', value: 'Lianyungang' },
  { text: '长沙', value: 'Changsha' },
  { text: '武汉', value: 'Wuhan' }
])

const confirm = ({ selectedValue, selectedOptions }) => {
  console.log(selectedValue[0], selectedOptions[0])
}
</script>

**Comment by eiinu** [comment]
https://nutui.jd.com/h5/vue/4x/#/zh-CN/guide/advanced

桌面端适配
