### ISSUE TITLE
表单校验不通过时边框的红色不一致

### ISSUE THREAD

**Issue by Zhaojjjjjj** [jdf2e/nutui#3187]
### NutUI 包名

@nutui/nutui

### NutUI 版本号

4.3.12

### 平台

h5

### 重现链接

https://nutui.jd.com/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgPGRpdiBjbGFzcz1cInJvdW5kZWQtbWQgYmctd2hpdGUgcHktMlwiPlxuICAgICAgICAgICAgICAgICAgICA8bnV0LWZvcm1cbiAgICAgICAgICAgICAgICAgICAgICAgIHJlZj1cImZvcm1SZWZcIlxuICAgICAgICAgICAgICAgICAgICAgICAgOm1vZGVsLXZhbHVlPVwiZGF0YVwiXG4gICAgICAgICAgICAgICAgICAgICAgICA6cnVsZXM9XCJ7XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgdXNlcm5hbWU6IFt7IHJlcXVpcmVkOiB0cnVlLCBtZXNzYWdlOiAn6K+35aGr5YaZ6LSm5Y+3JyB9XSxcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICBwYXNzd29yZDogW3sgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICfor7floavlhpnlr4bnoIEnIH1dLFxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIHBhc3N3b3JkMjogW3sgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICfor7floavlhpnlr4bnoIEnIH1dLFxuICAgICAgICAgICAgICAgICAgICAgICAgfVwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPG51dC1mb3JtLWl0ZW0gbGFiZWw9XCLotKblj7dcIiBwcm9wPVwidXNlcm5hbWVcIiBsYWJlbC1hbGlnbj1cImxlZnRcIiBsYWJlbC13aWR0aD1cIjUwXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPG51dC1pbnB1dCB2LW1vZGVsPVwiZGF0YS51c2VybmFtZVwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl6LSm5Y+3XCI+PC9udXQtaW5wdXQ+XG4gICAgICAgICAgICAgICAgICAgICAgICA8L251dC1mb3JtLWl0ZW0+XG4gICAgICAgICAgICAgICAgICAgICAgICA8bnV0LWZvcm0taXRlbSBsYWJlbD1cIuWvhueggVwiIHByb3A9XCJwYXNzd29yZFwiIGxhYmVsLWFsaWduPVwibGVmdFwiIGxhYmVsLXdpZHRoPVwiNTBcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bnV0LWlucHV0IHYtbW9kZWw9XCJkYXRhLnBhc3N3b3JkXCIgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXlr4bnoIFcIiB0eXBlPVwicGFzc3dvcmRcIj48L251dC1pbnB1dD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDwvbnV0LWZvcm0taXRlbT5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxudXQtZm9ybS1pdGVtIGxhYmVsPVwi5a+G56CBXCIgcHJvcD1cInBhc3N3b3JkMlwiIGxhYmVsLWFsaWduPVwibGVmdFwiIGxhYmVsLXdpZHRoPVwiNTBcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bnV0LWlucHV0IHYtbW9kZWw9XCJkYXRhLnBhc3N3b3JkMlwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl5a+G56CBXCIgdHlwZT1cInBhc3N3b3JkXCI+PC9udXQtaW5wdXQ+XG4gICAgICAgICAgICAgICAgICAgICAgICA8L251dC1mb3JtLWl0ZW0+XG4gICAgICAgICAgICAgICAgICAgIDwvbnV0LWZvcm0+XG4gICAgICAgICAgICAgICAgPC9kaXY+XG5cbiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPVwibXQtNVwiPlxuICAgICAgICAgICAgICAgICAgICA8bnV0LWJ1dHRvbiB0eXBlPVwiaW5mb1wiIHNpemU9XCJsYXJnZVwiIEBjbGljaz1cImxvZ2luXCI+55m75b2VPC9udXQtYnV0dG9uPlxuICAgICAgICAgICAgICAgIDwvZGl2PlxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuICBpbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuY29uc3QgZm9ybVJlZiA9IHJlZihudWxsKTtcblxubGV0IGRhdGEgPSByZWYoe1xuICAgIHVzZXJuYW1lOiAnJyxcbiAgICBwYXNzd29yZDogJycsXG59KTtcblxuY29uc3QgbG9naW4gPSAoKSA9PiB7XG4gICAgZm9ybVJlZi52YWx1ZS52YWxpZGF0ZSgpLnRoZW4oKHsgdmFsaWQsIGVycm9ycyB9KSA9PiB7XG4gICAgICAgIGlmICh2YWxpZCkge1xuICAgICAgICAgICAgY29uc29sZS5sb2coJ3N1Y2Nlc3M6JywgZm9ybURhdGEpO1xuICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgICAgY29uc29sZS53YXJuKCdlcnJvcjonLCBlcnJvcnMpO1xuICAgICAgICB9XG4gICAgfSk7XG59O1xuPC9zY3JpcHQ+XG5cbiJ9

### 重现步骤

点击提交后，仔细观察最后一项表单的错误提示边框和前面的不同

### 期望的结果是什么？

颜色一致

### 实际的结果是什么？

颜色不一致

**Comment by Miles-hxy** [comment]
对比下官网的demo是正常的，把button放form里面就正常了

**Comment by Zhaojjjjjj** [comment]
> 对比下官网的demo是正常的，把button放form里面就正常了

为什么会出现这样的原因呢
