### ISSUE TITLE
动态改变nut-col的:span值列宽不变，只能静态写死，不灵活

### ISSUE THREAD

**Issue by chix1221** [jdf2e/nutui#32]
动态改变span的值
<nut-col :span="12">

通过修改span后面的值，值变了，列宽不变，只能写死数值！！！

<nut-button @click="test">改变值</nut-button>
<nut-col :span="myValue">
        <div class="flex-content">span:{{this.myValue}}</div>
    </nut-col>

data: function(){
	return {
		myValue: 12
	}
 },

methods: {
        test(){
	  this.myValue+=1;
	}
    }

**Comment by Franslee** [comment]
已安排该组件的作者进一步优化，请留意后续版本

**Comment by chix1221** [comment]
好的 非常感谢！

**Comment by Franslee** [comment]
新版已支持，欢迎体验

**Comment by chix1221** [comment]
亲测没有问题了   谢谢
