### ISSUE TITLE
[bug] （SearchBar 搜索栏）清空操作未清空绑定值

### ISSUE THREAD

**Issue by pycrab** [jdf2e/nutui#321]
## 问题描述

搜索栏输入内容，出现清空按钮，点击清空按钮，页面输入框中确实已清空，但是实际搜索框绑定的值未发生变化。
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
1、输入文本，点击清空
```vue
<nut-searchbar
    v-model="title"
    :hasSearchButton="false"
    placeText="请输入标题搜索"
    @blur="handleQuery"
></nut-searchbar>

handleQuery(val) {
  console.log('回调参数', val)
  console.log('绑定值', this.title)
}
```
2、绑定值title没有被清空
![image](https://user-images.githubusercontent.com/40735921/91531519-7eee9d80-e93f-11ea-93d9-f9ab7b66b34d.png)

## 相关环境信息
- **操作系统**：安卓8.0
- **Node 版本**：12.16.1
- **NutUI 版本**： @nutui/nutui@2.2.7
- **Vue 版本**：2.6.11
- **引用方式**： NPM

**Comment by richard1015** [comment]
@pycrab   辛苦升级最新版本进行，测试一下
