### ISSUE TITLE
[bug]引入pxtorem后存在的组件展示问题

### ISSUE THREAD

**Issue by Jabo2017** [jdf2e/nutui#326]
## 问题描述

nutui中的部分组件以及修饰图标使用的是svg，在引入pxtorem后按官网配置后这部分的展示很不理想

## 复现步骤，具体代码
![效果图](https://user-images.githubusercontent.com/27938777/91924661-e9b82400-ed05-11ea-8450-b4301fd18ea9.png)

**Comment by richard1015** [comment]
pxtorem 如果 按照的是 750 ，建议采用多套转换   nutui为375
