### ISSUE TITLE
请问有组织么？

### ISSUE THREAD

**Issue by mrxu0** [jdf2e/nutui#33]

**Comment by Franslee** [comment]
这里是京东用户体验设计部-前端开发部

**Comment by mrxu0** [comment]
没有建个QQ群或者是微信群的么？

**Comment by mrxu0** [comment]
如果没有。我可不可以创建一个QQ群，在这里发表一下呢？

**Comment by chix1221** [comment]
QQ群：599125181

**Comment by Franslee** [comment]
京东内网禁止上QQ，有问题还是推荐在这里发帖或者联系官方邮箱nutui@jd.com

**Comment by mrxu0** [comment]
哦哦，这个样。有很多初学者问题，不是很值当发帖或者是联系官方邮箱。上面的群是你们官方推荐么？

**Comment by Franslee** [comment]
> 哦哦，这个样。有很多初学者问题，不是很值当发帖或者是联系官方邮箱。上面的群是你们官方推荐么？

非官方的
