### ISSUE TITLE
<nut-icon type="self" :url="require('../assets/money.svg')"></nut-icon> 自定义图标没有生效

### ISSUE THREAD

**Issue by blackmft** [jdf2e/nutui#330]
<nut-icon type="self" :url="require('../assets/money.svg')"></nut-icon>
文档上说这个是自定义的，但是我引入之后，页面上展示效果是这样的
![image](https://user-images.githubusercontent.com/25949474/92125845-0e111f00-ee32-11ea-94c5-079d3f98885c.png)

**Comment by richard1015** [comment]
请参考demo  ，附上 vue-svg-loader

https://github.com/jdf2e/nutui-demo/blob/master/base/vue.config.js
