### ISSUE TITLE
引入Steps组件报错 [bug]

### ISSUE THREAD

**Issue by daughterRui** [jdf2e/nutui#334]
## 问题描述
引入Steps组件报错 
```
Uncaught TypeError: _nutui_nutui_dist_packages_steps_steps_js__WEBPACK_IMPORTED_MODULE_20___default.a.install is not a function
```
[报错图片](https://gt-toolbox.oss-cn-beijing.aliyuncs.com/gt-toolbox/08f54718-3490-4c75-b4b3-0d4b2b82e365.png)
> 

> 

## 复现步骤，具体代码
```
## main.js

import {
  Steps, Dialog
} from '@nutui/nutui';

Dialog.install(Vue);
Steps.install(Vue);
```
Dialog引入是可以正常使用的
但Steps引入却有问题
## 相关环境信息
- **操作系统**：mac
- **Node 版本**：12.18.3
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：2.6.11
- **引用方式**： NPM 按需引入

**Comment by richard1015** [comment]
``` javascript
import { Steps } from '@nutui/nutui';
Steps.Steps.install(Vue);
Steps.Step.install(Vue);
```
