### ISSUE TITLE
关于开发项目引入该组件库后的组件的适配问题 [question]

### ISSUE THREAD

**Issue by daughterRui** [jdf2e/nutui#335]
## 你想知道什么？

你好，我想知道关于开发项目引入该组件库后的组件的适配问题，由于我的项目用了postcss-pxtorem，将px自动转成rem，导致该组件库的组件样式 也px转成 rem了。

就比如拿picker组件来说
在iphone X 上
[示例图](https://gt-toolbox.oss-cn-beijing.aliyuncs.com/gt-toolbox/3e6a7cc4-4bcc-4f5e-9e34-0a25e5eb6f25.png)

在iphone 8 plus 上
[示例图](https://gt-toolbox.oss-cn-beijing.aliyuncs.com/gt-toolbox/9ce076e9-e7b4-4da7-8e71-cc19077e4225.png)

## 描述你考虑过的替代方案

目前我在 post.config.js 文件中将zoom-picker的样式忽略掉
```
'postcss-pxtorem': {
      rootValue: 16,
      propList: ['*'],
      selectorBlackList: ['zoom-picker'],
    },
```
## 其它

无

**Comment by richard1015** [comment]
参考 #271

**Comment by richard1015** [comment]
是否已解决
