### ISSUE TITLE
[bug] 英文环境下，时分秒显示的中文

### ISSUE THREAD

**Issue by JuoJuo** [jdf2e/nutui#337]
## 问题描述
英文环境下，时分秒显示的中文

## 复现步骤，具体代码
import NutUI from '@nutui/nutui';
import enUS from '@nutui/nutui/dist/locales/lang/en-US';
Vue.use(NutUI, {
  locale: 'en-US',
  lang: enUS
});

![image](https://user-images.githubusercontent.com/36804937/93778063-0e921e00-fc58-11ea-8282-5200be0e822d.png)

**Comment by JuoJuo** [comment]
把isShowChinese传为false后，只有数字，没有单位。
凑合用了。

**Comment by richard1015** [comment]
@JuoJuo  后期我们优化一下

**Comment by guoxiao158** [comment]
> 把isShowChinese传为false后，只有数字，没有单位。
> 凑合用了。

暂未对是分秒进行国际化。等待下个版本优化

**Comment by richard1015** [comment]
@Drjingfubo   已修复 v2.2.15
