### ISSUE TITLE
[bug]全量导入nutui时报错：Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by noisyFish** [jdf2e/nutui#339]
## 问题描述

按照文档导入nutui时，页面报错：Cannot read property 'config' of undefined

## 复现步骤，具体代码
引入代码：
import { createApp } from 'vue'
import App from './App.vue'
import NutUI from '@nutui/nutui'
import '@nutui/nutui/dist/nutui.css'

createApp(App).mount('#app')
NutUI.install(createApp)

步骤：执行npm install；执行npm run build；执行npm run serve；

报错显示：
![image](https://user-images.githubusercontent.com/20484886/94387759-af636a80-017d-11eb-84f8-c204f1c07f15.png)
![image](https://user-images.githubusercontent.com/20484886/94388090-98714800-017e-11eb-95b1-622fd33fc8d9.png)
![image](https://user-images.githubusercontent.com/20484886/94388160-c3f43280-017e-11eb-87ae-f88bb79b9b88.png)
（这里提示我install需要两个参数，文档中是一个）

## 相关环境信息
- **操作系统**：Windows10
- **Node 版本**：v12.18.3
- **NutUI 版本**： @nutui/nutui@2.2.11
- **Vue 版本**：@vue/cli 4.5.6
- **引用方式**： NPM

**Comment by richard1015** [comment]
感谢您的反馈，vue3正在开发中，可以先参考 https://github.com/jdf2e/nutui-demo

**Comment by richard1015** [comment]
目前正在vue3开发中，请期待第四季度发布测试版本

**Comment by Tyresee** [comment]
现在这个问题依然存在
