### ISSUE TITLE
按照快速上手里的操作步骤，无法做到按需加载  会报错

### ISSUE THREAD

**Issue by 451761830** [jdf2e/nutui#34]

**Comment by Franslee** [comment]
安装插件了吗？报什么错？

**Comment by 451761830** [comment]
安装了插件
main.js?56d7:11 Uncaught TypeError: _nutui_nutui_dist_packages_dialog_dialog_js__WEBPACK_IMPORTED_MODULE_4___default.a.install is not a function

**Comment by Franslee** [comment]
> 安装了插件
> main.js?56d7:11 Uncaught TypeError: _nutui_nutui_dist_packages_dialog_dialog_js__WEBPACK_IMPORTED_MODULE_4___default.a.install is not a function

这个问题刚刚已经修复，请试试最新版

**Comment by 451761830** [comment]
为什么上拉加载 下拉刷新这样的基础控件都没有

**Comment by Franslee** [comment]
> 为什么上拉加载 下拉刷新这样的基础控件都没有

这个算不上基础控件，不过我们已经开发完，目前正在项目里测试，稍后放出来

**Comment by Franslee** [comment]
> 为什么上拉加载 下拉刷新这样的基础控件都没有
新版已经放出了这个组件 Scroller ，欢迎体验
