### ISSUE TITLE
Vue3.0 support

### ISSUE THREAD

**Issue by jahnli** [jdf2e/nutui#340]
Could you tell me the author , Do you plan to support Vue3.0 and when do you expect to implement it

**Comment by richard1015** [comment]
Currently under development, please look forward to the release test version in Q4

**Comment by jahnli** [comment]
thanks

**Comment by gmars** [comment]
Q4结束了 我看next分支也在更新。大概发布时间是什么时候呢？ @richard1015

**Comment by richard1015** [comment]
> Q4结束了 我看next分支也在更新。大概发布时间是什么时候呢？ @richard1015

3.31
