### ISSUE TITLE
ImagePicker图片选择器，如何清空预览的图片列表？

### ISSUE THREAD

**Issue by FionaXXX** [jdf2e/nutui#346]
## 你想知道什么？

如何清空预览的图片列表？
比如业务场景是：切换页面时想要清空已预览的几张图片，回到无选择的那个初始状态

## 描述你考虑过的替代方案

目前能在JS里把绑定的图片数组imgList清空了，但是对应的DOM仍然存在

## 其它

无

**Comment by szg2008** [comment]
您好，测试版本已修复，请持续关注，预计本周五发布，感谢您的反馈～您的提议和反馈是我们开发的动力～
