### ISSUE TITLE
Tab和Scroller组件做订单列表，切换页签页面滚动距离未清零[bug]

### ISSUE THREAD

**Issue by BLUESKYBUTTERFLY** [jdf2e/nutui#347]
## 问题描述
使用Tab组件和Scroller纵向滚动做订单列表，点击tab标签传值重新获取数据后scroll组件纵向滚动距离未清零

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
<nut-tab
        @tab-switch="tabSwitch"
        contentShow="false"
        class="tab-container"
        :def-index="currentIndex"
      >
        <nut-tab-panel tab-title="全部"> </nut-tab-panel>
        <nut-tab-panel tab-title="待支付"> </nut-tab-panel>
        <nut-tab-panel tab-title="待发货"> </nut-tab-panel>
        <nut-tab-panel tab-title="待收货"> </nut-tab-panel>
        <nut-tab-panel tab-title="已收货"> </nut-tab-panel>
      </nut-tab>
      <order-list-view
        :dataList="orderList"
        class="list-view"
        @loadMore="onLoadMore"
        @pullDown="onPullDown"
        :isLoading="hasLoading"
        :isUnMore="!canLoadMore"
        :currentType="currentType"
        @order-deleted="onOrderDeleted"
      />
scroller封装成公共组件
点击tab标签传参后清空列表数据重新加载，测试发现如果下一个标签页数据为空显示空白组件页面，页面滚动正常；
如果下一个标签页加载有数据，则会保留上一个标签页的滚动距离；单标签页做dialog对话框删除订单操作后清空数据重新加载，页面不会滚动到顶部，再次点击删除订单页面会滚动到底部；
transform: translate3d(0px, -210px, 0px) Y值不为0

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  
- **Vue 版本**：
- **引用方式**：  NPM

**Comment by zhenyulei** [comment]
切换页签后有回调函数，建议在回调函数tab-switch中设置滚动条的距离，比如：Element 的scrollTo(x,y)
