### ISSUE TITLE
ActionSheet组件清除锁定背景滚动方法名称拼写错误

### ISSUE THREAD

**Issue by zjj1991729** [jdf2e/nutui#350]
### 控制台报错截图：
![image](https://user-images.githubusercontent.com/8097125/98917992-0ba10480-2508-11eb-847c-8c2121130512.png)
### 组件源码截图：
![image](https://user-images.githubusercontent.com/8097125/98920009-8834e280-250a-11eb-8a58-9923a2994f75.png)

## 复现步骤，具体代码
actionsheet配置is-lock-bg-scroll属性，选择之后触发报错

## 相关环境信息
- **操作系统**：windows 10
- **Node 版本**：v12.19.0
- **NutUI 版本**： @nutui/nutui@2.2.12
- **Vue 版本**：2.6
- **引用方式**：  CDN

**Comment by richard1015** [comment]
感谢您的反馈，测试版本已修复，明天发版，请持续关注
