### ISSUE TITLE
Notify 组件的Prop属性background背景颜色 设置无效 [bug]

### ISSUE THREAD

**Issue by langyuxiansheng** [jdf2e/nutui#351]
## 问题描述

![image](https://user-images.githubusercontent.com/29669030/99216391-802db900-2810-11eb-8852-eddc0be883b8.png)
把组件设置的背景设置为#ff0，
实际效果
![image](https://user-images.githubusercontent.com/29669030/99216423-92a7f280-2810-11eb-8ae3-ab1145ccfe3d.png)
原因是因为默认值使用了!important 导致优先级太高，无法被覆盖
![image](https://user-images.githubusercontent.com/29669030/99216454-aeab9400-2810-11eb-85b4-b5561d455fbd.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码

   this.$notify.text('复制成功',{background:'#ff0'});

## 相关环境信息
- **操作系统**： window 10
- **Node 版本**： v14.0
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：v2.6
- **引用方式**：  CDN / NPM ？npm 按需加载

**Comment by shenqistart** [comment]
多谢您提出的issue,我们将会在明天发版后解决这个问题（版本号2.2.13）。
