### ISSUE TITLE
设置了上拉加载距离和下拉刷新距离无效的bug stretch[bug]

### ISSUE THREAD

**Issue by langyuxiansheng** [jdf2e/nutui#353]
## 问题描述

设置了上拉加载距离和下拉刷新距离,但是未生效的bug.还是只要20像素的距离就触发了下拉刷新,

源码中的判断貌似是写死了的.并未进行外部设置的props距离判断
```javascript
 if ((!this.isShowLoadMore || this.isFirstPull) && !this.isLoading && updateMove > 20) {
            updateMove = 50;
            clearTimeout(this.timerEmit);
            this.timerEmit = setTimeout(() => {
              this.$emit('pulldown');
            }, time / 2);
          } else {
            this.isFirstPull = true;
            updateMove = 0;
          }
```

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
设置了上拉加载距离和下拉刷新距离,但是未生效

## 复现步骤，具体代码
https://nutui.jd.com/#/scroller

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：12
- **NutUI 版本**： @nutui/nutui@2.x.x 
- **Vue 版本**： 2.6
- **引用方式**：  NPM ？

**Comment by richard1015** [comment]
已修复，请更新最新版本进行测试

**Comment by langyuxiansheng** [comment]
> 已修复，请更新最新版本进行测试

好的，ヾ(◍°∇°◍)ﾉﾞ
