### ISSUE TITLE
[bug] SearchBar无法设置placeholder为空值

### ISSUE THREAD

**Issue by will-17173** [jdf2e/nutui#356]
`:placeholder="placeText || nutTranslate('lang.searchbar.placeText')"`

这个逻辑当placeText为空值时就会显示默认值，但是我就是想要placeholder是空字符串

**Comment by richard1015** [comment]
请先尝试升级到最近版本测试

**Comment by will-17173** [comment]
> 请先尝试升级到最近版本测试

https://github.com/jdf2e/nutui/blob/0176a13a16c389236f217f0ac03d7073cc795902/src/packages/searchbar/searchbar.vue#L9

最新版本还是这样的啊

**Comment by richard1015** [comment]
感谢您的反馈，测试版本已修复，预计明天发布最新版，请持续关注！

**Comment by richard1015** [comment]
已修复，请更新最新版本进行测试
