### ISSUE TITLE
[bug] nut-collapse组件无法渲染

### ISSUE THREAD

**Issue by q13044256742** [jdf2e/nutui#359]
![image](https://user-images.githubusercontent.com/16590810/102186569-c8162d80-3eed-11eb-9638-77eaa46d7eaa.png)
![image](https://user-images.githubusercontent.com/16590810/102186677-ec720a00-3eed-11eb-919a-2b3b9f9b0cc2.png)
![image](https://user-images.githubusercontent.com/16590810/102186705-f6940880-3eed-11eb-83d3-75f54be1cfef.png)

如图所示，直接粘贴官网例子到本地Vue环境下，标签没有被解析

**Comment by q13044256742** [comment]
![image](https://user-images.githubusercontent.com/16590810/102187115-8b970180-3eee-11eb-91f1-0d17fd7c1bcf.png)

**Comment by Ymm0008** [comment]
能提供下您的使用方法吗，是按需加载的吗？ @q13044256742

**Comment by q13044256742** [comment]
> 能提供下您的使用方法吗，是按需加载的吗？ @q13044256742

引用方式为直接在html中引用的下载到本地的js和css文件，如下：
<link href="~/nutui/nutui.min.css" rel="stylesheet" />
<script src="~/nutui/nutui.min.js"></script>
    
我把nut-collapse组件放到了nut-dialog组件里，发现nut-dialog正常生效（被渲染成div），nut-collapse组件还是没有被渲染，还是nut-collapse标签。
然后我发现无论nut-collapse放到哪里，都不能正常渲染。不知为何，目前其他组件都能正常使用，就这个不行。。
我截的图在GitHub我这边加载不出来，不知道你那边能否正常看到，如有需要，可以留个qq发给你复现这个bug的截图

**Comment by q13044256742** [comment]
我好像知道了，我在浏览已经解决的issue里面无意间看到，nut-collapse组件是你们在10-28号新添加的，我看了下我本地下载的版本是08-21，可能是这个导致的。建议在每个(后来新增的)组件后面写上最低支持的版本。

**Comment by Ymm0008** [comment]
好的。感谢反馈，我们尽快完善文档 @q13044256742
