### ISSUE TITLE
tab组件默认值def-index设置后不能自动将对应标题居中[bug]

### ISSUE THREAD

**Issue by Ma-Tao007** [jdf2e/nutui#362]
## 问题描述
在多tab的情况下，默认下标如果是第一页没有展示的tab，那么在页面看不到选中的效果，默认的tab没有居中显示

## 最小可复现仓库
复现地址：http://jsrun.net/TdvKp/edit

## 预期的行为和实际行为
如果当前页面被保存了状态（keepalive）  内容是上次浏览的内容，但是tab却已经回到了最初的状态，tab应该还是保存上次浏览的状态

**Comment by zhenyulei** [comment]
已经联系用户修改问题，待无误后，关闭问题
