### ISSUE TITLE
luckycard 组件如何监听ratio刮开比 触发的事件

### ISSUE THREAD

**Issue by xxGw1997** [jdf2e/nutui#365]
在使用luckycard的时候，想要在用户刮开70%的时候，就执行回调，让刮刮卡是全部刮开状态。但是现在该如何监听ratio的刮开比并且触发 完全刮开刮刮卡的事件

**Comment by richard1015** [comment]
感谢您的反馈，  辛苦@guoxiao158跟进一下

**Comment by guoxiao158** [comment]
请这样使用 
open 为回调函数，ratio为刮开系数。（目前版本支持）
下个版本回优化，当触发回调函数时，自动清空组件的蒙层，展示全部信息

   <nut-luckycard 
        content="1000万"
        @open="opencard"
        ratio="0.2"
    ></nut-luckycard>
