### ISSUE TITLE
[question] swiper中如何使用Scroller

### ISSUE THREAD

**Issue by notbucai** [jdf2e/nutui#366]
横向 swiper  中 放纵向的 scroller 只能触发swiper，不能触发scroller的滚动切换。

想实现如下效果

![image](https://user-images.githubusercontent.com/32786133/103136460-95451400-46fb-11eb-9dee-29829cb5b543.png)

**Comment by richard1015** [comment]
可以直接采用 Infiniteloading 无限加载 配合使用，如有问题可以进一步沟通，我做过这种业务场景
