### ISSUE TITLE
[bug] ActionSheet组件菜单文本显示错位

### ISSUE THREAD

**Issue by q13044256742** [jdf2e/nutui#369]
![image](https://user-images.githubusercontent.com/16590810/103254505-8c389900-49c0-11eb-9d12-5e8cc32622be.png)
如图所示效果，跟官网上的示例不一样。

使用方法如下：
![image](https://user-images.githubusercontent.com/16590810/103254536-abcfc180-49c0-11eb-8b47-e783e5800d36.png)
![image](https://user-images.githubusercontent.com/16590810/103254548-b25e3900-49c0-11eb-87fa-a4693fcc7020.png)

我看了下渲染后的标签，我的是这样的
![image](https://user-images.githubusercontent.com/16590810/103254588-d883d900-49c0-11eb-9675-baa122cefd6f.png)
官网的是这样的：
![image](https://user-images.githubusercontent.com/16590810/103254602-e6d1f500-49c0-11eb-8c2d-cfce3243fdcb.png)

请问一下，我该怎么解决呢？

**Comment by richard1015** [comment]
是否采用了pxtorem插件，请排除 node_modules 文件夹

**Comment by q13044256742** [comment]
> 是否采用了pxtorem插件，请排除 node_modules 文件夹

听不懂啥意思，我是直接引用下载到本地的js文件

**Comment by richard1015** [comment]
可以提供一个在线链接吗
