### ISSUE TITLE
[question]不知道你们有没有感觉nut-scroller不流畅

### ISSUE THREAD

**Issue by notbucai** [jdf2e/nutui#372]
感觉卡顿，没有过渡的动画，不管是快速滑动还是缓慢滑动都是只滚动一点

**Comment by richard1015** [comment]
嗯嗯，目前是这样的，nut-scroller 的实现原理是基于 touch 事件，目前代码中滑动计算逻辑 不是最优的解决方案，
您的场景如果是 滚动加载的话，完全可以采用 Infiniteloading 无限加载组件，可以完美解决您的问题
