### ISSUE TITLE
[bug]nut-circleprogress组件中的进度渲染在微信浏览器及手机浏览中不显示高亮部分

### ISSUE THREAD

**Issue by moqle** [jdf2e/nutui#373]
## 问题描述

nut-circleprogress组件中的进度渲染在微信浏览器及手机浏览中不显示高亮部分，经简单的测试是由于svg的transform="rotate(-90)" 引起的，旋转原点有点问题
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN

**Comment by richard1015** [comment]
您的使用场景 是不是想去调整 起点位置

**Comment by richard1015** [comment]
v2.2.14已修复
