### ISSUE TITLE
[BUG] nut-tab 添加is-scroll不生效

### ISSUE THREAD

**Issue by L2shao** [jdf2e/nutui#374]
` <nut-tab @tab-switch="tabSwitch" :is-scroll="true">
      <nut-tab-panel tab-title="页签1">页签1</nut-tab-panel>
      <nut-tab-panel tab-title="页签2">页签2</nut-tab-panel>
      <nut-tab-panel tab-title="页签3">页签3</nut-tab-panel>
      <nut-tab-panel tab-title="页签4">页签4</nut-tab-panel>
      <nut-tab-panel tab-title="页签5">页签5</nut-tab-panel>
      <nut-tab-panel tab-title="页签6">页签6</nut-tab-panel>
      <nut-tab-panel tab-title="页签7">页签7</nut-tab-panel>
  </nut-tab>`

发现没有滚动效果，

**Comment by richard1015** [comment]
辛苦升级到最新版本

提供复现代码

**Comment by zhenyulei** [comment]
你好 2.x版本中是可以滚动的 
https://codesandbox.io/s/trusting-antonelli-tpjt8?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675

如果是3.x版本中 请将版本升级到最新版本 并且“:is-scroll="true"”改为“scrollType="scroll"，如还问题可以提供最小复现仓库
