### ISSUE TITLE
NutUI 3什么时候发布呢

### ISSUE THREAD

**Issue by gmars** [jdf2e/nutui#375]
## 你想知道什么？

NutUI 3什么时候发布呢？

## 描述你考虑过的替代方案

如果使用nutui@next建议现在使用不？和发布版相比改变会不会很大

## 其它

无

**Comment by richard1015** [comment]
预计Q1底发布测试版本

目前正在开发阶段 不建议使用

**Comment by Leonewu** [comment]
现在还不支持按需

**Comment by richard1015** [comment]
> 现在还不支持按需

月底肯定会支持的

**Comment by lwzhang** [comment]
> > 现在还不支持按需
> 
> 月底肯定会支持的

请问使用 vite 是如何实现按需加载的？

**Comment by richard1015** [comment]
> > > 现在还不支持按需
> > 
> > 
> > 月底肯定会支持的
> 
> 请问使用 vite 是如何实现按需加载的？

现阶段采用的 按需引用，利用内部treeshaking

**Comment by richard1015** [comment]
https://nutui.jd.com/3x/#/
