### ISSUE TITLE
可否在使用swiper组件的代码中设定swiper中的currentPage？

### ISSUE THREAD

**Issue by ZXHHHH123** [jdf2e/nutui#376]
## 你想知道什么？

你好，现在想实现“tab控制swiper的切换”，组件文档中的setPage方法看起来是可以实现所说场景的，但是具体该怎么使用还请详细说明一下

## 描述你考虑过的替代方案

建议通过以props的方式将currentPage传到swiper组件中。

## 其它

无

**Comment by richard1015** [comment]
感谢pr，v2.2.14已修复
