### ISSUE TITLE
webpack打包 多入口场景下如何定制不同的主题

### ISSUE THREAD

**Issue by Azraelj** [jdf2e/nutui#378]
## webpack打包 多入口场景下如何定制不同的主题

现有的在loader中全局引入的方式似乎并不能实现为多个入口分别定制主题

能否为不同的入口定制不同的主题呢，应该如何配置？

**Comment by richard1015** [comment]
这边只提供一下思路给你

1.首先按需定制多套主题 scss文件(看官方文档覆盖变量)
2. webpack 打包时，通过执行的命令不同，来读取 对应的 主题scss文件
