### ISSUE TITLE
Uploader [bug]

### ISSUE THREAD

**Issue by qiyunkai** [jdf2e/nutui#379]
## 问题描述

Uploader 上传组件 连续点击 BUG
Android 手机 有BUG  IOS 手机 暂时没发现

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
Uploader 上传组件  Android 手机 点击两次 只唤起 一次 选择文件 相机 或 图库

## 复现步骤，具体代码
Uploader 上传组件 Android 手机 连续点击两次 会唤起 两次 选择文件 相机 或 图库

## 相关环境信息
- **操作系统**：华为手机 chrome h5页面
- **Node 版本**：>7.6.0
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：^2.5.16
- **引用方式**：  CDN / NPM ？NPM

**Comment by richard1015** [comment]
2.2.14已修复
