### ISSUE TITLE
styles文件下面的variable.scss是怎么引用的？

### ISSUE THREAD

**Issue by mrxu0** [jdf2e/nutui#39]
我在阅读源码的时候发现 styles/variable.scss 和 styles/index.scss 文件基本没有单独引入到packages 下面的组件中。但是每个 packages/*/*.scss (packages/picker/picker.scss) 文件夹都可以使用 styles/variable.scss 里面定义的变量。而其中只有 noticebar.scss、 rate.scss、 searchbar.scss 文件确明确引入了。这是为什么呢？

**Comment by Franslee** [comment]
参见build目录下的webpack.base.conf.js文件：
`{
                        loader: 'sass-loader',
                        options: {
                            data: `@import "./src/styles/index.scss"; `
                        }
                    }`
