### ISSUE TITLE
通过npm安装后的包里不包含ts类型推导文件[bug]

### ISSUE THREAD

**Issue by JerryWu1234** [jdf2e/nutui#392]
## 问题描述
通过npm安装最新版的3.0版本
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
预期
![image](https://user-images.githubusercontent.com/27261522/110195732-61643880-7e7a-11eb-8afc-833dfebd3537.png)

实际
![image](https://user-images.githubusercontent.com/27261522/110195759-95d7f480-7e7a-11eb-9674-0c0bbc65eab4.png)

## 复现步骤，具体代码
通过 npm安装

## 相关环境信息
- **操作系统**：*
- **Node 版本**：*
- **NutUI 版本**： @nutui/nutui@3.0
- **Vue 版本**： vue3.0.5
- **引用方式**：   NPM ？

**Comment by richard1015** [comment]
已修复
