### ISSUE TITLE
为什么用背景做边框，而不直接使用border呢？

### ISSUE THREAD

**Issue by mrxu0** [jdf2e/nutui#41]
`
background: linear-gradient(rgba($dark-color, .5), rgba($dark-color, .5)) bottom, linear-gradient(rgba($dark-color, .5), rgba($dark-color, .5)) top;
background-size: 100% 1px;
background-repeat: no-repeat;
`

我看到 nut-cell-border.scss 文件中有如上代码。用 border 也可以实现为啥这里用了看起来比较麻烦的背景做的边框呢？

**Comment by Franslee** [comment]
这种方式比border更灵活，比如可以轻松实现高分屏1物理像素效果（如果需要的话）：
`background-image: linear-gradient(rgba($dark-color, .5) 0%, rgba($dark-color, .5) 50%, transparent 50%,transparent 100%);`

**Comment by mrxu0** [comment]
搜噶搜噶，受教了！
