### ISSUE TITLE
[bug]扫码体验里面的toast弹出的提示得很久才能消失。会遮挡别的内容。

### ISSUE THREAD

**Issue by Funnyboycode** [jdf2e/nutui#422]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
感谢反馈，我们处理一下
