### ISSUE TITLE
Dialog 组件全局引入

### ISSUE THREAD

**Issue by base-stone** [jdf2e/nutui#435]
![image](https://user-images.githubusercontent.com/13493540/113836327-5f660000-97bf-11eb-8313-f03f27345f01.png)
![image](https://user-images.githubusercontent.com/13493540/113836604-9cca8d80-97bf-11eb-89fa-87db997b9f18.png)

Dialog({
  title: "确定删除此订单？",
  content: "删除后将从你的记录里消失，无法找回"
})
这里多个文件引入 使用 Dialog 都要每次 createApp().use(Dialog)，显得多余
除了这种方式，引入全局引入
$dialog()如何调用

**Comment by richard1015** [comment]
``` javascript
import { getCurrentInstance } from 'vue';

setup(){
  const { proxy } = getCurrentInstance();
  proxy.$dialog({
    title: '基础弹框',
    content: '支持函数调用和组件调用两种方式。'
  });
}

**Comment by base-stone** [comment]
非常好，谢谢了
