### ISSUE TITLE
[question] npm run dev 项目运行不起来~

### ISSUE THREAD

**Issue by zhaoxm469** [jdf2e/nutui#436]
## npm run dev 项目运行不起来~

您好，我把项目拉倒本地以后。安装完依赖 。
使用命令 npm run dev . 自动打开网页后，但是页面什么内容也没有显示 。 
控制台 报错 
![image](https://user-images.githubusercontent.com/26950016/113898114-239e5b00-97fe-11eb-806e-a2be6432370e.png)
![image](https://user-images.githubusercontent.com/26950016/113898156-2b5dff80-97fe-11eb-8e9a-955065d562f7.png)

请问如何解决这个错误呢，让我本地能跑起来这个项目~~

**Comment by richard1015** [comment]
这边测试没问题啊，辛苦尝试 删除依赖重新安装试试

在线测试
https://lavender-jaguar-1q1pp48p.ws-us03.gitpod.io/#/workspace/nutui
