### ISSUE TITLE
修改主题一直编译失败

### ISSUE THREAD

**Issue by kevinlxj** [jdf2e/nutui#44]
修改主题一直编译失败:
style为css时正常，改为scss后，一直编译失败，写不写sass-loader都提示下面的错误:
![image](https://user-images.githubusercontent.com/28834148/54866709-9b81c000-4db2-11e9-85c9-9728d762affe.png)

![image](https://user-images.githubusercontent.com/28834148/54866759-e00d5b80-4db2-11e9-9b8c-afe2b3a0e800.png)

![image](https://user-images.githubusercontent.com/28834148/54866894-f61c1b80-4db4-11e9-923c-794c54323608.png)

**Comment by Franslee** [comment]
我们测试无法复现这个问题。不妨试试我们推荐脚手架 https://github.com/jdf2e/Gaea4

**Comment by Provenr** [comment]
![image](https://user-images.githubusercontent.com/26128964/54983122-25b26a00-4fe7-11e9-85a5-2af7c89e0999.png)
![image](https://user-images.githubusercontent.com/26128964/54983172-3cf15780-4fe7-11e9-80b9-058a658876ba.png)
![image](https://user-images.githubusercontent.com/26128964/54983280-6dd18c80-4fe7-11e9-8457-ad5edf4468c5.png)
![image](https://user-images.githubusercontent.com/26128964/54983296-76c25e00-4fe7-11e9-948e-7b2840ceaeff.png)

添加定制主题时一直编译不过

**Comment by Provenr** [comment]
![image](https://user-images.githubusercontent.com/26128964/54983609-2992bc00-4fe8-11e9-9536-d0a0ae038700.png)

![image](https://user-images.githubusercontent.com/26128964/54983587-213a8100-4fe8-11e9-990e-2dec4c6ee1f5.png)
不引入自定义的scss 文件 ，出现这样的问题

**Comment by kevinlxj** [comment]
自己解决了，好像是忘了安装sass-loader了

**Comment by kevinlxj** [comment]
> 出现这样的问题

跟util.js自带的sass、scss冲突了，我是屏蔽了util.js里面的

**Comment by kevinlxj** [comment]
@Provenr 跟util.js自带的sass、scss冲突了，我是屏蔽了util.js里面的

**Comment by Provenr** [comment]
@kevinlxj 
我把utils 文件的sass,scss屏蔽了，也没生效
