### ISSUE TITLE
[suggest]taro+vue3+nutui的微信小程序开发案例

### ISSUE THREAD

**Issue by richard1015** [jdf2e/nutui#440]
## 你建议我们做什么？

taro+vue3+nutui的微信小程序开发案例

**Comment by richard1015** [comment]
https://github.com/jdf2e/nutui-demo/tree/master/taro

**Comment by hothotaxiao** [comment]
https://github.com/jdf2e/nutui-demo/tree/master/taro
里面的input框还是有
![image](https://user-images.githubusercontent.com/65027150/128799968-a11b437e-253b-46e0-824e-3661dc0ddc0a.png)
请尽快完善一下

**Comment by hothotaxiao** [comment]
![image](https://user-images.githubusercontent.com/65027150/128800124-7ad37a5a-3009-454e-b5df-b517c3840e64.png)
这两个功能也有问题
1.datepicker 点击不出来日期
2.picker 选择器也有这样的问题，有好多警告
bug3.0
