### ISSUE TITLE
tabbar引入后报警

### ISSUE THREAD

**Issue by 13196789316** [jdf2e/nutui#442]
Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead. 
  at <NutTabbarItem icon="setting" > 
  at <NutTabbar onTabSwitch=fn<bound tabSwitch> class="footer" unactive-color="#FFFFFF"  ... > 
  at <App>

**Comment by richard1015** [comment]
@Drjingfubo
