### ISSUE TITLE
[question]不懂就要问，为什么v3使用view 、view-block标签

### ISSUE THREAD

**Issue by skylingfly** [jdf2e/nutui#451]
不懂就要问，为什么v3使用view 、view-block标签， 有什么特别的目的吗？

**Comment by richard1015** [comment]
采用自定义标签 view 进行 taro 转换，方便后期适配  多端小程序

可以理解为，在taro中使用nutui组件库，实现小程序端赋能

**Comment by yuanliang847** [comment]
但是在 Vue 3 里，会控制台里会出现一堆的 warning 报错，这个怎么解决呢？

[Vue warn]: Failed to resolve component: view-block 
  at <NutDatepicker modelValue= Tue May 25 2021 23:27:12 GMT+0800 (中国标准时间) onUpdate:modelValue=fn min-date= Wed Jan 01 2003 00:00:00 GMT+0800 (中国标准时间)  ... > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
