### ISSUE TITLE
[question] 项目贡献如何完成lint？

### ISSUE THREAD

**Issue by CNMathon** [jdf2e/nutui#452]
如果想要给 Nutui 提供代码贡献，想了解项目应该如何 Lint ？

**Comment by CNMathon** [comment]
阅读了源码，暂未发现触发 Eslint 排查的环节

**Comment by skylingfly** [comment]
> 阅读了源码，暂未发现触发 Eslint 排查的环节
了解下husky & lint-staged 多数项目类似配置

https://github.com/jdf2e/nutui/blob/next/.husky/pre-commit

packag
"lint-staged": {
    "*.md": "prettier --write",
    "*.{ts,tsx,js,vue,scss}": "prettier --write"
  },

**Comment by watsonhaw5566** [comment]
lint放到package.json的eslintConfig里面了，你可以看看。

**Comment by richard1015** [comment]
提交时代码时 会自动触发  lint-staged    .prettierrc
