### ISSUE TITLE
[bug]使用Trao3.X+NutUI开发后，H5正常，小程序所有图标不显示

### ISSUE THREAD

**Issue by Baiyuetribe** [jdf2e/nutui#454]
## 问题描述

使用Trao3.X+NutUI开发后，H5正常，小程序所有图标不显示。Trao3.x+TaroUI目前小程序也正常，既然同是京东UI，应该可以自我借鉴下。希望NutUI能支持小程序。
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为

已实现案例：
https://github.com/b2nil/taro-ui-vue3/
上述方案实现了taro-ui+vue3，小程序和H5均正常

## 复现步骤，具体代码
H5表现正常
![image](https://user-images.githubusercontent.com/43716063/116788527-ac967280-aadc-11eb-8a1a-b372e731bb7d.png)
小程序不正常
![image](https://user-images.githubusercontent.com/43716063/116788532-b4eead80-aadc-11eb-8b4b-2b29b16dcf3b.png)

**Comment by richard1015** [comment]
由于Button组件内部图标依赖 Icon ,需使用下方使用方式

``` import { Button,Icon } from '@nutui/nutui-taro';```

下个版本文档将更新
