### ISSUE TITLE
[bug] 安装引入报错

### ISSUE THREAD

**Issue by Xie-chunhua** [jdf2e/nutui#456]
## 问题描述

 通过脚手架创建的vue3.0+ts 项目 

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

createApp(App).use(store).use(router).use(NutUI).mount('#app')

Argument of type 'typeof import("/Users/admin/Documents/vue3/app/node_modules/@nutui/nutui/dist/nutui")' is not assignable to parameter of type 'Plugin_2'.
  Property 'install' is missing in type 'typeof import("/Users/admin/Documents/vue3/app/node_modules/@nutui/nutui/dist/nutui")' but required in type '{ install: PluginInstallFunction; }'.

## 相关环境信息
- **操作系统**：macOS
- **Node 版本**：10.15.3
- **NutUI 版本**："@nutui/nutui": "^3.0.0-beta.14"
- **Vue 版本**：vue": "^3.0.0",
- **引用方式**： YARN

**Comment by richard1015** [comment]
参考这个仓库
https://github.com/jdf2e/nutui-demo
