### ISSUE TITLE
[bug]navbar里面添加的tabs展示不出来

### ISSUE THREAD

**Issue by zyplayer** [jdf2e/nutui#457]
## 问题描述
navbar里面添加的tabs展示不出来

## 最小可复现仓库
https://github.com/zyplayer/nut-ui-debuger

## 预期的行为和实际行为
navbar里面添加的tabs需要能展示出来

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：v12.2.0
- **NutUI 版本**： @nutui/nutui@3.0.0-beta.14
- **Vue 版本**：3.0.5
- **引用方式**： NPM

**Comment by Drjingfubo** [comment]
目前已经可以正常展示

**Comment by Drjingfubo** [comment]
目前已经修复，可以正常展示
