### ISSUE TITLE
[bug]英文单词拼写错误

### ISSUE THREAD

**Issue by SissyC** [jdf2e/nutui#458]
## 问题描述

dialog组件页面中右侧手机预览中英文单词拼写错误
“无弹出动效且关闭时不销毁dislog实例”
页面位置：https://nutui.jd.com/#/dialog
截图：
![image](https://user-images.githubusercontent.com/24885313/118070129-ea966f00-b3d7-11eb-8570-209e4bf93570.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
代码库汇总已修复
