### ISSUE TITLE
toast.loading时没有遮罩吗，这样后面元素还是可以点击，会考虑加上吗

### ISSUE THREAD

**Issue by kevinlxj** [jdf2e/nutui#46]
toast.loading时没有遮罩吗，这样后面元素还是可以点击，会考虑加上吗

**Comment by Franslee** [comment]
感谢反馈，该建议已记录，后续增加这个选项。作为一种临时方案，你可以通过自定义class覆盖部分样式来实现。

**Comment by Franslee** [comment]
新版已经加上此功能，loading类型默认自带遮罩，欢迎体验
