### ISSUE TITLE
[bug] 组件backtop的bottom和right

### ISSUE THREAD

**Issue by guoshuangyang** [jdf2e/nutui#461]
```ts
<nut-backtop :right="100"></nut-backtop>
```
right 设置为 100 时候，距离底部是100 
设置bottom时候才是距离右边100
## 相关环境信息
- **操作系统**：mac for m1
- **Node 版本**：15
- **NutUI 版本**： 3.0.0-@beta.16
- **Vue 版本**： vue3.0 --- ts
- **引用方式**：  npm

**Comment by richard1015** [comment]
https://github.com/guoshuangyang/vue3-ts-vite-tailwindcss  
复现代码仓库

**Comment by richard1015** [comment]
@Drjingfubo  是否已修改

**Comment by Drjingfubo** [comment]
请更新到最新的nutui版本3.1.3，该版本已经修复
