### ISSUE TITLE
[suggest] 关于瀑布流组件的想法

### ISSUE THREAD

**Issue by guoshuangyang** [jdf2e/nutui#466]
## 瀑布流组件的想法

现在很多地方都会用到瀑布流，比如资讯类的展示，商品类的展示，pc端和移动端还是有距离的，移动端只需要考虑等宽两列布局，不像pc端需要等宽不等高多列，等高不等宽多列。。。

如果能够做一个瀑布流组件，我觉得是令人振奋的！！

它能够让很多的工作更加精简。

**Comment by szg2008** [comment]
目前不考虑
