### ISSUE TITLE
为什么 html 标签没有设置字体大小, badge 组件还可以使用 rem 单位呢？

### ISSUE THREAD

**Issue by mrxu0** [jdf2e/nutui#47]
在看 badge 组建的时候发现 html 标签是没有设置字体大小的。 为什么 能够用 rem 单位呢？ 自己想到的一种可能是 html 有默认字体大小。 那这样会不会由于其他的浏览器默认字体大小不一样而导致 rem 单位不准确呢？

**Comment by Franslee** [comment]
组件自带的样式不是rem，部分API允许用户根据自己的环境传带rem单位的值而已。
