### ISSUE TITLE
Datepicker 组件 v-model 值变更，默认选中时间希望也能跟着改变 [suggest]

### ISSUE THREAD

**Issue by geekmanvip** [jdf2e/nutui#470]
## 现在
1. 页面加载后，从接口那边一步获取到默认时间
2. 修改 v-model 对应的变量
3. 用户点击弹框，修改时间，这个时候选中的时间是当前时间

## 期望
1. 如果在动态的修改了时间之后，弹出的时间日期选择里，能够默认选中这个动态的值

**Comment by richard1015** [comment]
哪个版本
2.0？
3.0？
