### ISSUE TITLE
3.0 组件 input 样式[bug]

### ISSUE THREAD

**Issue by yang867381349** [jdf2e/nutui#473]
引入
import NutUI from "@nutui/nutui";
import "@nutui/nutui/dist/style.css";

<nut-input
      v-model="state.val1"
      @change="change"
      @focus="focus"
      @blur="blur"
      label="文本"
    />

<img width="1583" alt="A43C7C19-03C9-42CF-A52B-04A450D5F145" src="https://user-images.githubusercontent.com/20942938/119807255-90d48f80-bf15-11eb-8b7a-b29bbe0132e5.png">

**Comment by yang867381349** [comment]
本人使用的是   
vue-cli4.5.11
vue3.0
element-plus1.0.2-beta.44

**Comment by yang867381349** [comment]
@nutui/nutui3.0.0-beta.16

**Comment by yang867381349** [comment]
"dependencies": {
    "@antv/g6": "^4.2.7",
    "@nutui/nutui": "^3.0.0-beta.14",
    "amfe-flexible": "^2.2.1",
    "axios": "^0.21.1",
    "compression-webpack-plugin": "^5.0.1",
    "core-js": "^3.6.5",
    "echarts": "^5.1.1",
    "element-plus": "^1.0.2-beta.44",
    "postcss-px2rem": "^0.3.0",
    "qs": "^6.9.6",
    "swiper": "^6.5.0",
    "vue": "^3.0.0",
    "vue-router": "^4.0.8",
    "vue3-count-to": "^1.0.9",
    "vuex": "^4.0.1"
  },

**Comment by yang867381349** [comment]
"devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "^4.5.11",
    "@vue/cli-plugin-vuex": "^4.5.11",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0",
    "node-sass": "^4.14.1",
    "sass": "^1.34.0",
    "sass-loader": "^7.3.1",
    "style-resources-loader": "^1.4.1",
    "vue-cli-plugin-style-resources-loader": "~0.1.5"
  },

**Comment by hothotaxiao** [comment]
这个问题解决了吗

**Comment by hothotaxiao** [comment]
我也遇到这个问题，我用的taro+nutUI3, input 样式感觉没有应用过来

**Comment by szg2008** [comment]
已修复
