### ISSUE TITLE
[bug]Can't resolve '../img/bg-cube-act.png' in

### ISSUE THREAD

**Issue by denggp** [jdf2e/nutui#475]
按照官方说明引入项目，目前报错:
 error  in ./node_modules/@nutui/nutui/dist/nutui.css
Syntax Error: ModuleNotFoundError: Module not found: Error: Can't resolve '../img/bg-cube-act.png' in '..........\node_modules\@nutui\nutui\dist'

**Comment by richard1015** [comment]
已修复，请更新 v2.3.1
