### ISSUE TITLE
后端渲染报错

### ISSUE THREAD

**Issue by waitkafuka** [jdf2e/nutui#48]
用nuxt+nutui引入了一个简单的Button，直接报错：  
代码：
``` 
import Button from '@nutui/nutui/dist/packages/button/button.js';  
Button.install(Vue);
```
错误信息：  
```
ReferenceError
window is not defined 
```
看文档说是支持ssr，想问下是我写的有问题吗？

**Comment by Franslee** [comment]
服务端渲染请使用nutui的commonjs版本 nutui.common.js，暂不支持按需加载

**Comment by waitkafuka** [comment]
试了下，是可以的，不过体积有些大。请问随后有这方面的开发计划吗？毕竟移动端对SEO还是有要求的。

**Comment by Franslee** [comment]
> 试了下，是可以的，不过体积有些大。请问随后有这方面的开发计划吗？毕竟移动端对SEO还是有要求的。

我们会针对需求情况做进一步调研的

**Comment by waitkafuka** [comment]
好的，谢谢。

**Comment by main2018** [comment]
@Franslee nutui.common.js 在哪里呀，怎么引入

**Comment by Franslee** [comment]
> @Franslee nutui.common.js 在哪里呀，怎么引入

现在已经不需要引用nutui.common.js文件了，正常使用nutui.js文件即可
