### ISSUE TITLE
Dialog标签式写法 内容无法在手机浏览器现实全，在苹果和安卓机上都测试过

### ISSUE THREAD

**Issue by 451761830** [jdf2e/nutui#51]

**Comment by Franslee** [comment]
请上代码

**Comment by 451761830** [comment]
`<nut-dialog :visible="isShowDialog" @close="isShowDialog=false" textAlign="left" :lockBgScroll="true">
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
      <p>请输入您的邮箱号码（选填）</p>
    </nut-dialog>`

**Comment by 451761830** [comment]
测试一下这个组件是否能用  方便加微信吗  我可以截图给你看

**Comment by 451761830** [comment]
![1](https://user-images.githubusercontent.com/48461152/55125004-42fc4b00-5143-11e9-8779-43b3cafd3ee0.png)
![2](https://user-images.githubusercontent.com/48461152/55125006-455ea500-5143-11e9-8ca7-9ee007bdea34.jpg)
手机和电脑上的展示差异

**Comment by Franslee** [comment]
我们在苹果和安卓机上都未能复现，请提供具体机型和系统版本。

**Comment by 451761830** [comment]
苹果7 系统版本 10.3.2 用了Safari和Uc浏览器验证有问题

**Comment by Franslee** [comment]
找不到这个系统的测试机，不过我用10.3.1的iPhone7测试是正常的。你可以试试官网的demo有没有问题

**Comment by richard1015** [comment]
请升级最新版本进行测试
