### ISSUE TITLE
[bug]button不显示文字 tabbar也是 navbar字体不显示

### ISSUE THREAD

**Issue by hcweb** [jdf2e/nutui#526]
![QQ截图20210628165409](https://user-images.githubusercontent.com/12317944/123608881-c11f8e80-d831-11eb-86c3-e6ebb9187f98.png)
[新建 DOCX 文档.docx](https://github.com/jdf2e/nutui/files/6724862/DOCX.docx)
![QQ截图20210628165632](https://user-images.githubusercontent.com/12317944/123608962-d72d4f00-d831-11eb-88c6-d614ec0b0606.png)

**Comment by richard1015** [comment]
nutui版本 提供一下

**Comment by richard1015** [comment]
参考 https://github.com/jdf2e/nutui-demo
