### ISSUE TITLE
[bug]taro3 vue3 小程序端不支持

### ISSUE THREAD

**Issue by boot-vue** [jdf2e/nutui#527]
## 问题描述
taro3 vue3 小程序项目使用最新版ui 很多组件无法使用

## 最小可复现仓库

[demo](https://github.com/boot-vue/bug)

## 预期的行为和实际行为

ui组件无法正常使用, 大量组件存在异常, 比如`Overlay 遮罩层`

## 复现步骤，具体代码

```bash

git clone git@github.com:boot-vue/bug.git

cd tui_demo

yarn install

yarn dev:weapp

# 微信开发者工具  小程序导入 tui_demo 目录, 编译运行

```

> 其中 src/pages/index/index.vue 用到ui组件

```vue
 <nut-overlay v-model:visible="show" :z-index="2000">
      <div class="wrapper">
        <div class="content">这里是正文</div>
      </div>
    </nut-overlay>
```

## 相关环境信息
- **操作系统**：
- **Node 版本**：14.17
- **NutUI 版本**： @nutui/nutui@3.0.2-taro
- **Vue 版本**： 3
- **引用方式**：   NPM

**Comment by szg2008** [comment]
收到，我们跟进一下

**Comment by MechaGirls** [comment]
我遇到了OverLay无法显示使用
