### ISSUE TITLE
dialog标签中嵌入RadioGroup时 dialog中的lockBgScroll设置不生效 页面还是会滚动

### ISSUE THREAD

**Issue by 451761830** [jdf2e/nutui#53]
![image](https://user-images.githubusercontent.com/48461152/55151921-40711400-518a-11e9-9e79-ff0e0ad4a6b8.png)

**Comment by Franslee** [comment]
请提供机型和系统版本、浏览器

**Comment by richard1015** [comment]
请升级最新版本
