### ISSUE TITLE
[suggest]Uploader组件，啥时候能加个点击图片放大预览的功能

### ISSUE THREAD

**Issue by zhengchenghui** [jdf2e/nutui#532]
强烈建议Uploader组件，能加个点击图片放大预览的功能

**Comment by richard1015** [comment]
明天发布将新增此组件

**Comment by richard1015** [comment]
3.1.7

**Comment by zhengchenghui** [comment]
v3.1.17    Uploader上传组件，还是不能直接点击图片放大预览，需搭配ImagePreview才行

**Comment by xyw1229** [comment]
对呀 3.x 4.x 现在都没有直接点击放大的功能，连Events点击都没有提供。。
