### ISSUE TITLE
[bug]nut-tab   v2.3.3

### ISSUE THREAD

**Issue by GuangHuiGitHub** [jdf2e/nutui#538]
<nut-tab v-bind="containerAttr" v-on="$listeners">
        <nut-tab-panel
          v-for="(item, index) in tabPanelArray"
          :key="JSON.stringify(item) + index"
          :tab-title="handelTitle(item)"
        >
          <div style="width:100%; margin-top:20px; color: rgba(0,0,0,0.3);">
            {{ handelTitle(item) }}
          </div>
        </nut-tab-panel>
      </nut-tab>

无法动态修nut-tab-panel 个数
以及tab-title
也无法动态修改

建议：计算属性，或者监听。
v2.3.3

**Comment by zhenyulei** [comment]
如需要更新页面，请将监听变化的数据传入init-data：

https://codesandbox.io/s/quirky-snyder-24yki?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675
因为直接修改数组中的元素，vue2无法监听到数组的变化，请直接修改数组，详见：

https://cn.vuejs.org/v2/guide/list.html#%E6%95%B0%E7%BB%84%E6%9B%B4%E6%96%B0%E6%A3%80%E6%B5%8B

如有还有问题 请提供最小复现仓库
