### ISSUE TITLE
日期picker，type：datetime

### ISSUE THREAD

**Issue by yehuagao** [jdf2e/nutui#54]
设置默认defaultValue、startDate、endDate；华为手机p10plus自带浏览器，年份滚动拦，显示Fri Mar...等英文月份，并且不能切换其他年份

**Comment by yehuagao** [comment]
![image](https://user-images.githubusercontent.com/23260155/55208023-93dd7380-5217-11e9-8b61-909a126cf1b8.png)

**Comment by irisSong** [comment]
传入的defaultValue、startDate、endDate； 截图发一下

**Comment by yehuagao** [comment]
![image](https://user-images.githubusercontent.com/23260155/55308471-70236300-548d-11e9-801b-366e3218079e.png)

**Comment by richard1015** [comment]
请升级最新版本进行测试
