### ISSUE TITLE
[bug]toast.loading 默认展示时长bug以及文档指引问题

### ISSUE THREAD

**Issue by UzkiS** [jdf2e/nutui#542]
首先上bug，文档中描述

`duration值为 0 时，toast 不会自动消失（loading类型默认为0）`

实际上使用toast.loading时，默认时长依旧为2000，并不是0

然后上文档指引问题
再不看vue2文档直接看vue3版本的时候

方法名 | 说明 | 参数 | 返回值
-- | -- | -- | --
Toast.text | 展示文字提示 | options/message | toast 实例

文档的意思是和我说参数 options/message 二选一，导致如下方式想使用options时并不能成功
```
Toast({
  msg: "test",
  duration:0
})
```
看了Vue2版本的文档之后才知道是
```
Toast("test",{
  duration:0
})
```
所以文档参数描述将`options/message`改为 `message, options`会好一点，能明确告诉别人options和message是分开的两个参数，或者直接增加example会更易于理解一点

**Comment by UzkiS** [comment]
补充一下 cover 在loading时的默认值也和文档描述的不一致

**Comment by richard1015** [comment]
感谢反馈，我们跟进一下

**Comment by Drjingfubo** [comment]
3.1.4文档demo均已更新
