### ISSUE TITLE
[bug]：vue3 + nutui-taro@3.1.1 开发dev:weapp构建成功，小程序预览工具空白，一直处于comping状态，电脑风扇狂转动....（H5没毛病）

### ISSUE THREAD

**Issue by clotee** [jdf2e/nutui#543]
## 复现步骤，具体代码
```
import { createApp } from 'vue'
import store from './store'
import NutUI from "@nutui/nutui-taro";
import "@nutui/nutui-taro/dist/style.css";

import './app.scss'

const App = createApp({
  onShow (options) {
    console.log(options)
  },
  // 入口组件不需要实现 render 方法，即使实现了也会被 taro 所覆盖
})

App.use(store).use(NutUI);

export default App

```

## 相关环境信息
- **操作系统**：mac 11.4
- **Node 版本**：v14.15.3
- **NutUI 版本**： @nutui/nutui-taro@^3.1.1
- **Vue 版本**：^3.0.0
- @tarojs/cli@3.3.0
- **引用方式**：  CDN / NPM ？

**Comment by seatonxx** [comment]
+1

**Comment by Lin-Ya** [comment]
我也出现了这种情况。。实在受不了了才来GitHub看看，想不到也有人遇到这种情况。

**Comment by moor-zhou** [comment]
+1

**Comment by richard1015** [comment]
该问题，与 Taro 团队 紧急处理中 ...

暂时可使用 npm run build:weapp 测试使用

nutui-taro 官方完整小程序 Demo 版 点击以下链接运行尝试

[https://github.com/jdf2e/nutui-demo/tree/master/taro](https://github.com/jdf2e/nutui-demo/tree/master/taro)

**Comment by JakeWoki** [comment]
+1，dev:weapp运行就这样，build:weapp正常

**Comment by weicheng-git** [comment]
+1

**Comment by richard1015** [comment]
已修复    升级依赖包 @tarojs/xxx@3.3.2 以上

**Comment by richard1015** [comment]
参考 https://github.com/jdf2e/nutui-demo/tree/master/taro
