### ISSUE TITLE
DatePicker组件choose方法 会连续调用两次[bug]

### ISSUE THREAD

**Issue by wuyi123321** [jdf2e/nutui#545]
## 问题描述

调用日期选择点击确定后 choose方法执行了两次
代码如下图
https://www.szcapital.com.cn/home/nginx/files/img/2021/7/19/20210719145649452.jpg
用谷歌浏览器调试如下图
https://www.szcapital.com.cn/home/nginx/files/img/2021/7/19/20210719145003185.jpg
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.3.4 
- **Vue 版本**：2.6.1
- **引用方式**：NPM

**Comment by irisSong** [comment]
击确定后 choose方法里面不要修改默认值，修改默认值，会再次触发choose方法，组件支持动态修改默认值
