### ISSUE TITLE
[suggest] Cell 单元格 能否支持通栏布局，取消掉border-radius

### ISSUE THREAD

**Issue by zehuichan** [jdf2e/nutui#547]
如题

**Comment by richard1015** [comment]
通栏当前版本支持
测试环境 已更新 新增参数 round-radius 设置 0即可取消圆角
v3.1.2 发布后更新即可

**Comment by zehuichan** [comment]
@richard1015 thx

**Comment by zehuichan** [comment]
搭配cell-group使用，cell单元格 round-radius 设置 0，外层的cell-group还是有 radius
