### ISSUE TITLE
nutui的TabBar组件，如何与vue-router结合实现路由跳转

### ISSUE THREAD

**Issue by yuzhewo** [jdf2e/nutui#548]
nutui的TabBar组件，如何与vue-router结合实现路由跳转

**Comment by Drjingfubo** [comment]
点击切换时候的tab-switch事件已经暴露出来了哦，可以直接调用它去处理路由跳转

**Comment by Drjingfubo** [comment]
> nutui的TabBar组件，如何与vue-router结合实现语音导航

点击切换时候的tab-switch 已经事件暴露出来了哦，可以直接调用它去处理消息跳转
