### ISSUE TITLE
[bug]taro-vue3项目下组件DatePicker引入报错 找不到组件

### ISSUE THREAD

**Issue by zhangrundong** [jdf2e/nutui#556]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
日期选择器可以正常使用

## 复现步骤，具体代码
![image](https://user-images.githubusercontent.com/16918482/127457084-09512bab-830b-416e-b436-c397b2edf9c6.png)
![image](https://user-images.githubusercontent.com/16918482/127457166-5b12b6f0-86e3-4c92-8db1-26a4ff5af716.png)
![image](https://user-images.githubusercontent.com/16918482/127457233-78ac31e8-a4d1-4881-9fba-9964ec18aa9c.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：>12
- **NutUI 版本**： @nutui/nutui@3.x.x
- **Vue 版本**：vue3
- **引用方式**：  NPM

**Comment by szg2008** [comment]
同问题#553

**Comment by gh1122** [comment]
一样的问题

**Comment by szg2008** [comment]
已修复，更新v3.1.16
