### ISSUE TITLE
nutui-taro 主题色配置无效 [question]

### ISSUE THREAD

**Issue by GilHogan** [jdf2e/nutui#557]
## 你想知道什么？

在taro中主题色如何配置

## 描述你考虑过的替代方案

1. 在项目中新建了一个scss文件，文件内容如下
```scss
  $primary-color: #478EF2;
  $primary-color-end: #496AF2;
```
2. 在config\index.js文件中配置了sass项，[taro的配置参考](https://docs.taro.zone/docs/config-detail#sass)
```js
sass: {
    projectDirectory: path.resolve(__dirname, '..'),
    resource: [
      'src/assets/styles/custom_theme.scss',
    ],
    data: '$primary-color: #478EF2;'
}
```
3. 现象：主题色配置无效
## 其它

  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@nutui/nutui-taro": "^3.0.3",
    "@tarojs/components": "3.3.0",
    "@tarojs/plugin-html": "3.3.0",
    "@tarojs/runtime": "3.3.0",
    "@tarojs/taro": "3.3.0",
    "jsencrypt": "^3.2.0",
    "moment": "^2.29.1",
    "qs": "^6.10.1",
    "vue": "^3.0.0",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/cli": "3.3.0",
    "@tarojs/mini-runner": "3.3.0",
    "@tarojs/webpack-runner": "3.3.0",
    "@types/qs": "^6.9.7",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^2.x",
    "@typescript-eslint/parser": "^2.x",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-preset-taro": "3.3.0",
    "eslint": "^6.8.0",
    "eslint-config-taro": "3.3.0",
    "eslint-plugin-vue": "^7.0.0",
    "stylelint": "9.3.0",
    "typescript": "^3.7.0",
    "vue-loader": "^16.0.0-beta.8"
  }

**Comment by richard1015** [comment]
升级到最新版本  @nutui/nutui-taro@3.1.2
``` js
const path = require('path');
// ......
	sass: {
		resource: [
			path.resolve(__dirname, '..', 'src/assets/styles/custom_theme.scss')
		]
	}
```

我们这边试的没问题

**Comment by HoganGolden** [comment]
> 升级到最新版本 @nutui/nutui-taro@3.1.2
> 
> ```js
> const path = require('path');
> // ......
> 	sass: {
> 		resource: [
> 			path.resolve(__dirname, '..', 'src/assets/styles/custom_theme.scss')
> 		]
> 	}
> ```
> 
> 我们这边试的没问题

我升级了没用啊，你的@tarojs/taro是什么版本

**Comment by GilHogan** [comment]
> 升级到最新版本 @nutui/nutui-taro@3.1.2
> 
> ```js
> const path = require('path');
> // ......
> 	sass: {
> 		resource: [
> 			path.resolve(__dirname, '..', 'src/assets/styles/custom_theme.scss')
> 		]
> 	}
> ```
> 
> 我们这边试的没问题

@richard1015 我升级了没用啊，你的@tarojs/taro是什么版本

**Comment by GilHogan** [comment]
* 我做了一个demo分别上传到了[github](https://github.com/HoganGolden/taro-test.git) 和 [codesandbox](https://codesandbox.io/s/holy-wildflower-rl6lp?file=/config/index.js)

* codesandbox运行截图,可以看到按钮颜色未改变
![codesandbox运行截图](https://raw.githubusercontent.com/HoganGolden/taro-test/master/src/public/1627882292(1).jpg)

**Comment by richard1015** [comment]
参考这个demo   
https://github.com/jdf2e/nutui-demo/tree/master/taro3
taro版本 暂时锁定在 v3.3.0-beta.0

**Comment by GilHogan** [comment]
@richard1015 那个demo拉下来运行就报错，可能是和windows环境有关，没解决
```js
监听文件修改中...

�   Failed to compile.

./node_modules/@nutui/nutui-taro/dist/styles/font/iconfont.css)
Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  a valid source-map is not present (ensure preceding loaders output a source-map)
```
还有 我上面现成的[codesandbox](https://codesandbox.io/s/holy-wildflower-rl6lp?file=/config/index.js)项目，只需要在线就可以运行 不看一下吗

**Comment by richard1015** [comment]
升级 taro 3.3.2 即可， 具体参考

https://github.com/jdf2e/nutui-demo/tree/master/taro3

**Comment by richard1015** [comment]
import "@nutui/nutui-taro/dist/style.css";

> @richard1015 那个demo拉下来运行就报错，可能是和windows环境有关，没解决
> 
> ```js
> 监听文件修改中...
> 
> �   Failed to compile.
> 
> ./node_modules/@nutui/nutui-taro/dist/styles/font/iconfont.css)
> Module build failed (from ./node_modules/resolve-url-loader/index.js):
> Error: resolve-url-loader: error processing CSS
>   a valid source-map is not present (ensure preceding loaders output a source-map)
> ```
> 
> 还有 我上面现成的[codesandbox](https://codesandbox.io/s/holy-wildflower-rl6lp?file=/config/index.js)项目，只需要在线就可以运行 不看一下吗


import "@nutui/nutui-taro/dist/style.css";
改成
import '@nutui/nutui-taro/dist/styles/themes/default.scss';

**Comment by richard1015** [comment]
https://codesandbox.io/s/unruffled-wood-d4tq9?file=/package.json
