### ISSUE TITLE
[bug]3.1.2版本Tab组件H5不能正常工作

### ISSUE THREAD

**Issue by ANDYGE** [jdf2e/nutui#558]
## 问题描述

在h5模式下，显示所有的nut-tab-panel内容，控制台打印如下错误`Failed to resolve component: scroll-view`，另外当tab页签垂直显示的时候，字体变得特别大。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：macos big sur
- **Node 版本**：16.5
- **NutUI 版本**： @nutui/nutui-taro:3.1.2
- **Vue 版本**：^3.0.0
- **引用方式**：  CDN / NPM ？

**Comment by sparrowu93** [comment]
+1

**Comment by ziclee** [comment]
小程序里面需要手动引入Swiper组件就能正常使用

**Comment by sparrowu93** [comment]
这个即使拉demo下来运行也还是会立马复现，官网上面的就没问题，确定是没引入的问题？

**Comment by xiaofuyesnew** [comment]
Taro 3.3.3 Vue 3.2.4 NutUI 3.1.3 问题依然存在，编写样式覆盖`<nut-tab-panel>`中的布局，基本上样式是正确的了， 但点击tabs无法切换内容，Failed to resolve component的除了scroll-view还有swiper和swiper-item。

**Comment by xiaofuyesnew** [comment]
> Taro 3.3.3 Vue 3.2.4 NutUI 3.1.3 问题依然存在，编写样式覆盖`<nut-tab-panel>`中的布局，基本上样式是正确的了， 但点击tabs无法切换内容，Failed to resolve component的除了scroll-view还有swiper和swiper-item。

自己使用基本组件实现了一个一模一样的组件，能完成功能。先用着。

**Comment by szg2008** [comment]
这个组件依赖swiper，正在紧急修复中

**Comment by zhenyulei** [comment]
本组件在H5端，依赖于 TabPanel、Swiper组件，故使用方式为

import { Tab, TabPanel,Swiper } from "@nutui/nutui";

小程序端的话 由于依赖于组件 swiper 正在紧急修复中

**Comment by richard1015** [comment]
已发版3.1.4 ，辛苦大家测试一下

**Comment by 307god** [comment]
```
._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:6875 [Vue warn]: Failed to resolve component: scroll-view 
  at <NutTab key=0 animated-time=500 > 
  at <Index tid="nav/pages/tab/index?$taroTimestamp=1630649586709" > 
  at <App>
```
用的3.1.4
animatedTime也失效了
nut-tab-panel里的动态内容不会更新（放外面就更新了）

**Comment by zhenyulei** [comment]
> ```
> ._node_modules_@vue_runtime-core_dist_runtime-core.esm-bundler.js:6875 [Vue warn]: Failed to resolve component: scroll-view 
>   at <NutTab key=0 animated-time=500 > 
>   at <Index tid="nav/pages/tab/index?$taroTimestamp=1630649586709" > 
>   at <App>
> ```
> 
> 用的3.1.4
> animatedTime也失效了
> nut-tab-panel里的动态内容不会更新（放外面就更新了）

------------

因为小程序依赖swiper组件，而该组件目前兼容性仍有问题，所以tab组件目前只能提供基础的切换功能，待后续swiper组件更新后，在开发所有功能（H5不影响）

**Comment by richard1015** [comment]
新增组件Tabs重构完成，暂时可以使用测试版 [@nutui/nutui-taro@3.1.9-beta.0](https://www.npmjs.com/package/@nutui/nutui-taro/v/3.1.9-beta.0) 
测试版文档 [https://jdf2e.github.io/nutui/#/tabs](https://jdf2e.github.io/nutui/#/tabs)
v3.1.9 发布时间 预计 10.11-10.15

**Comment by richard1015** [comment]
3.1.9 已发布
