### ISSUE TITLE
[suggest功能需求

### ISSUE THREAD

**Issue by strongyc** [jdf2e/nutui#559]
## 你建议我们做什么？
是否可以增加Card和九宫格组件，这两个组件在使用中还是比较频繁，另外，啥时候可以发布React版本，很期待哦

现在...

如果你能...

它将使...

## 其它

无

**Comment by richard1015** [comment]
Card 和 九宫格 可以详细描述一下

比如？

**Comment by richard1015** [comment]
Card 和 九宫格 可以详细描述一下

比如？

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/128203756-d98cfbf5-1910-4a83-905e-5eda6a0230a1.png)

**Comment by yangjisen** [comment]
附议

**Comment by richard1015** [comment]
https://nutui.jd.com/#/grid
