### ISSUE TITLE
[bug]初始化项目报错

### ISSUE THREAD

**Issue by Mis-zhang** [jdf2e/nutui#560]
## 问题描述
创建项目，npm run dev:h5 报错

## 复现步骤，具体代码

![image](https://user-images.githubusercontent.com/29423930/127842677-be7af341-73f7-44bc-b252-5a9f59f6d8eb.png)
![image](https://user-images.githubusercontent.com/29423930/127842784-91165466-51f5-46c9-88ec-252fcc49e31e.png)

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：v12.22.1
- **NutUI 版本**： @nutui/nutui-taro": "^3.0.3 "@tarojs/taro": "3.2.13",
- **Vue 版本**："vue": "^3.0.0",
- **引用方式**：  CDN / NPM ？npm

**Comment by richard1015** [comment]
需使用taro 3.3.1版本

参考 https://github.com/jdf2e/nutui-demo/tree/master/taro
