### ISSUE TITLE
InfiniteLoading 上拉不触发 loadMore[bug]

### ISSUE THREAD

**Issue by GilHogan** [jdf2e/nutui#562]
## 问题描述

InfiniteLoading 上拉不触发 loadMore
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：windows
- **Node 版本**：12.17.0
- **NutUI 版本**： @nutui/nutui-taro": "^3.1.2"
- **Vue 版本**："vue": "^3.0.0"
- **引用方式**：  NPM

**Comment by GilHogan** [comment]
dev:h5  [Vue warn]: Failed to resolve component: scroll-view 
复现代码[link](https://codesandbox.io/s/upbeat-joliot-392lh)

**Comment by richard1015** [comment]
taro场景滚动加载，请直接采用 taro scroll-view

https://taro-docs.jd.com/taro/docs/components/viewContainer/scroll-view
