### ISSUE TITLE
[suggest] uploader 组件 formData 中的 file参数 能否置于 所有key值之后。

### ISSUE THREAD

**Issue by ammaElm** [jdf2e/nutui#566]
## uploader组件 formData 后置 文件二进制信息
采用uploader组件文件上传，文件二进制信息处于信息头，不利于验证信息的校验；使用时需手动删除 fileItem中的file，再通过 formData属性改变顺序上传；file属性默认配置于最后感觉会更优。

**Comment by richard1015** [comment]
感谢反馈

**Comment by richard1015** [comment]
3.1.11已修复
