### ISSUE TITLE
[question]设计稿及尺寸单位如何调整兼容

### ISSUE THREAD

**Issue by yangjisen** [jdf2e/nutui#567]
## 你想知道什么？

```
在 Taro 中尺寸单位建议使用 px、 百分比 %，Taro 默认会对所有单位进行转换。在 Taro 中书写尺寸按照 1:1 的关系来进行书写，即从设计稿上量的长度 100px，那么尺寸书写就是 100px，当转成微信小程序的时候，尺寸将默认转换为 100rpx，当转成 H5 时将默认转换为以 rem 为单位的值。

如果你希望部分 px 单位不被转换成 rpx 或者 rem ，最简单的做法就是在 px 单位中增加一个大写字母，例如 Px 或者 PX 这样，则会被转换插件忽略。

结合过往的开发经验，Taro 默认以 750px 作为换算尺寸标准，如果设计稿不是以 750px 为标准，则需要在项目配置 config/index.js 中进行设置，例如设计稿尺寸是 640px，则需要修改项目配置 config/index.js 中的 designWidth 配置为 640：
```
当以前的老项目使用其他的UI时, 他们的设计稿是按 `750` 进行设计的, 而 nutui 是按 ` 375 ` 进行设计的,  请问该如何与老项目进行兼容逐步替换为 nutui呢 ? 
例子: 使用 taro-ui-vue3

## 描述你考虑过的替代方案

我想...

## 其它

无

**Comment by richard1015** [comment]
参考 taro 文档 ，过滤 nut-
https://taro-docs.jd.com/taro/docs/vant

**Comment by yangjisen** [comment]
> 参考 taro 文档 ，过滤 nut-
> https://taro-docs.jd.com/taro/docs/vant

非常感谢, 问题已解决

**Comment by yangjisen** [comment]
https://github.com/jdf2e/nutui/issues/567#issuecomment-899955443 
https://taro-docs.jd.com/taro/docs/vant
问题得已解决

**Comment by liangdiyuan** [comment]
![image](https://user-images.githubusercontent.com/40358986/209306126-3dc5fe51-72d7-4fff-843e-ce8494c069c0.png)
![image](https://user-images.githubusercontent.com/40358986/209306163-35444920-4928-47fb-acad-b5bf332956b7.png)
为什么按正常配置，在小程序预览样式不对
