### ISSUE TITLE
可以新增一个自定义顶部导航栏组件吗？

### ISSUE THREAD

**Issue by gay5882007** [jdf2e/nutui#570]

**Comment by richard1015** [comment]
参考 https://nutui.jd.com/#/navbar

**Comment by liujiayii** [comment]
> 参考 https://nutui.jd.com/#/navbar

他说的应该是顶部胶囊那一栏

**Comment by richard1015** [comment]
> > 参考 https://nutui.jd.com/#/navbar
> 
> 他说的应该是顶部胶囊那一栏

是否可以贴个图
