### ISSUE TITLE
taro的选择器不能使用 [bug 3.0]

### ISSUE THREAD

**Issue by hollebeijing** [jdf2e/nutui#573]
## 问题描述

自己导Picker进行使用的时候，发现不能显示。
下载taro-ui-vue3 的demo进行编译测试，编译weapp发现依然不能显示。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
https://github.com/b2nil/taro-ui-vue3/

## 预期的行为和实际行为
![image](https://user-images.githubusercontent.com/20790716/129330805-ed3c7efb-8132-49f4-b6cb-22fb670c2a65.png)

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：v14.7.0
- **NutUI 版本**： @nutui/nutui-taro": "^3.0.3
- **Vue 版本**：vue3
- **引用方式**：  NPM ？

**Comment by willove** [comment]
这个问题有好久了，还有swiper也不能用，我感觉上是和vue的版本有关，更新到3.2后 nut-icon 也不能用了

**Comment by szg2008** [comment]
先使用原生picker组件，目前正在紧急修复中

**Comment by MrChen2016-08-27** [comment]
现在还是不能使用3.2吗

**Comment by p930203110** [comment]
我也遇到这个问题，请问下还没有修复么。

**Comment by skksksksks** [comment]
> 先使用原生picker组件，当前正在紧急修复中

这都2022年了，还没修复吗

**Comment by szg2008** [comment]
已经修复，更新到最新版本v3.1.16
