### ISSUE TITLE
NutUI3.0中tab标签组件如何给标签自定义点击事件

### ISSUE THREAD

**Issue by register2019** [jdf2e/nutui#576]
## 你想知道什么？
tab标签组件如何给标签自定义点击事件

**Comment by zhenyulei** [comment]
> ## 你想知道什么？
> tab标签组件如何给标签自定义点击事件

点击组件标签的时候会触发“switch-tab”事件，返回点击的索引值和触发元素，可以在这个事件中处理你的逻辑。
