### ISSUE TITLE
[bug] Cell在Taro小程序时报vue-router注入错误

### ISSUE THREAD

**Issue by carlosyan1807** [jdf2e/nutui#577]
## 问题描述
使用Taro且未使用vue-router时，会warn没有vue-router
cell.taro.vue 有click就够了
其他有关路由的组件比如tabbar如果都import vue-router了可能都有这个warn吧

https://github.com/jdf2e/nutui/blob/b1e811d47247d84be55e8223525cb601ca2ba6c1/src/packages/__VUE/cell/index.taro.vue#L38

[Vue warn]: injection "Symbol([vue-router]: router)" not found. 

墙高了？这两天github贴不上图来

**Comment by richard1015** [comment]
已发版3.1.4 测试一下
