### ISSUE TITLE
countDown 组件这一行代码的意思？

### ISSUE THREAD

**Issue by mrxu0** [jdf2e/nutui#58]
`countdownTimer.restTime = restTime;`

这是 countDown 组件第 147 行代码，没有看懂这个赋值有什么作用？希望能给解答一下，谢谢

**Comment by famanoder** [comment]
这个组件的核心方法是 `restTime`，这个赋值是为了方便导出该方法，进行一些自定义的显示，因为传入剩余的时间戳，通过该方法即可转换为相应的剩余天、时、分、秒。

**Comment by mrxu0** [comment]
哦哦， 这里我把他跟 data 里面的 restTime 给搞混了，以为是多余代码。能方便告知一下在哪里导出了么？我想了解一下具体是怎么用的

**Comment by famanoder** [comment]
```js
countdownTimer.restTime = restTime;
export {restTime};
```
这里就是顺带导出了`restTime`，其他地方需要的话可以用；

**Comment by mrxu0** [comment]
嗯，好的。
