### ISSUE TITLE
升级V3.1.3后，项目跑不起来了，大神们 进来看看怎么解决 。。。

### ISSUE THREAD

**Issue by fssgh** [jdf2e/nutui#581]
## 问题描述
编译时发出的警告：
[vue-cli-service]  WARNING  Compiled with 4 warnings 
[vue-cli-service]  warning  in ./node_modules/@nutui/nutui/dist/nutui.es.js
[vue-cli-service] "export 'createElementBlock' (imported as 'h') was not found in 'vue'
[vue-cli-service]  warning  in ./node_modules/@nutui/nutui/dist/nutui.es.js
[vue-cli-service] "export 'createElementVNode' (imported as 'x') was not found in 'vue'
[vue-cli-service]  warning  in ./node_modules/@nutui/nutui/dist/nutui.es.js
[vue-cli-service] "export 'normalizeClass' (imported as 'f') was not found in 'vue'
[vue-cli-service]  warning  in ./node_modules/@nutui/nutui/dist/nutui.es.js
[vue-cli-service] "export 'normalizeStyle' (imported as 'm') was not found in 'vue'
好像是说 vue中没有上面的几个模块。。。然后项目跑不起来。。。请问是 什么原因，怎么解决？
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@3.1.3
- **Vue 版本**：3.x
- **引用方式**：  CDN / NPM ？

**Comment by willove** [comment]
降回到3.1.2就行了
还有vue 和 @vue/compiler-sfc 不要升级，我感觉3.2之后的版本都有问题，最明显的是icon出不来了，3.1.5正常

**Comment by fssgh** [comment]
降级不是好办法。。。。没有没能用上 @nutui/nutui@3.1.3的处理方案？

**Comment by richard1015** [comment]
@fssgh    请尝试删除package-lock、yarn.lock 文件，删除 node_modules  

重新安装依赖测试一下

**Comment by richard1015** [comment]
具体可参考 https://github.com/jdf2e/nutui-demo/tree/master/vite-ts

**Comment by willove** [comment]
> @fssgh 请尝试删除package-lock、yarn.lock 文件，删除 node_modules
> 
> 重新安装依赖测试一下

感谢，这方法有用，更新vue到最新版，之前 icon不显示的也有了。
