### ISSUE TITLE
微信小程序中使用Tab标签不能显示标签下面的内容

### ISSUE THREAD

**Issue by register2019** [jdf2e/nutui#583]
## 你想知道什么？ 
![003](https://user-images.githubusercontent.com/51252517/129734187-2efb149c-4849-41a3-b197-31ebb70e62ed.PNG)

**Comment by willove** [comment]
这些有个特点，就是包装了原生组件，这些原生组件无法使用，其他比如swiper和picker也不正常，不知道是taro的原因还是什么。我的解决办法就是直接用原生组件去实现，不用nutui的去实现。

**Comment by sparrowu93** [comment]
太拉了，官网实列跑得好好的，结果拉下来一看不是那么回事，心说你刚发布慢慢改查漏补缺，提了个bug出来，老大默默贴了个tag，就没有下文了，也没说什么问题，也没有临时的workaround，版本是一个一个发，问题是一个也没解决

**Comment by richard1015** [comment]
> 太拉了，官网实列跑得好好的，结果拉下来一看不是那么回事，心说你刚发布慢慢改查漏补缺，提了个bug出来，老大默默贴了个tag，就没有下文了，也没说什么问题，也没有临时的workaround，版本是一个一个发，问题是一个也没解决

感谢反馈，目前组件库中，使用Taro原生的均出现此问题，我们尽快修复

**Comment by register2019** [comment]
看来大家都遇到了 我一直以为是我项目的问题

**Comment by nodfe** [comment]
> > 太拉了，官网实列跑得好好的，结果拉下来一看不是那么回事，心说你刚发布慢慢改查漏补缺，提了个bug出来，老大默默贴了个tag，就没有下文了，也没说什么问题，也没有临时的workaround，版本是一个一个发，问题是一个也没解决
> 
> 感谢反馈，目前组件库中，使用Taro原生的均出现此问题，我们尽快修复

请问BUG3.0这些问题解决还需多久，新项目在考虑用Nut

**Comment by b2nil** [comment]
改一下 Taro 版本的编译配置，重新构建打包发版即可，供参考：https://github.com/b2nil/taro-plugin-vue。建议针对小程序和 h5 版本分开编译打包。

**Comment by zhenyulei** [comment]
暂时移除了底层对swiper的依赖 目前基本功能已经可以使用了 请更新到最新版本

**Comment by 307god** [comment]
nut-tab-panel里的数据不会更新
```
<nut-tab>
  <nut-tab-panel tab-title="全部问题">
    {{ 某个动态会变的数据，但是变了之后内容它不更新啊 }}
  </nut-tab-panel>
</nut-tab>
{{ 某个动态会变的数据，但是变了之后内容就更新了 }}
```
版本用的3.1.4， 当前最新

@zhenyulei

**Comment by zhenyulei** [comment]
> nut-tab-panel里的数据不会更新
> 
> ```
> <nut-tab>
>   <nut-tab-panel tab-title="全部问题">
>     {{ 某个动态会变的数据，但是变了之后内容它不更新啊 }}
>   </nut-tab-panel>
> </nut-tab>
> {{ 某个动态会变的数据，但是变了之后内容就更新了 }}
> ```
> 
> 版本用的3.1.4， 当前最新
> 
> @zhenyulei

========
请参考以下示例：

https://codehouse.jd.com/?source=share&type=vue&mainJs=aW1wb3J0IHsgY3JlYXRlQXBwIH0gZnJvbSAidnVlIjsKxyHEGcYXLi9hcHAuzR17IFN3aXBlciwgVGFiLCBCdXR0b27JSEBudXR1aS%2FFBso0zRcvZGlzdC9zdHlsZS5jc3MiOwrpAI8oQXBwKS51c2UoxmTGDFRhYsYJxmwpLm1vdW50KCIjYXBwIik7&appValue=PHRlbXBsYXRlPgogIDxkaXbECCAgPG51dC10YWIgOmFuaW1hdGVkVGltZT0iNTAwIiB2LWlmPSJlZGl0TGlzdC5sZW5ndGggPiAwIsY9yj8tcGFuZWzHFSAgOsQTdGl0bGU9Iml0ZW0uxQwiySB2LWZvcj0iKMQcLCBpbmRleCkgaW4gyGvKKjprZXk9IsUiyBXIfCAgPHAgY2xhc3M9ImNvbnRlbuUAiyI%2Be3sgxXXHFSB9fTwvcMg2PC%2FtALPGF8kV6wEVYnV0dG9uIHR5cGU9InByaW1hcnkiIEBjbGljaz0iY2hhbmdl5QCsPuaUueWPmOaVsOaNrsZKxjzETTwv5QFrPC%2FqAX8KPHNjcmlwdD4KaW1wb3J0IHsgcmVmLCByZWFjdGl2ZSwgdG9SZWZzIH0gZnJvbSAidnVlIjsKZXjFLWRlZmF1bHQgewogIHNldHVwKCnFDCAgY29uc3TpAUMgPclRKFvFICDHKMQB5QGQOiAi5qCH562%2B5LiAIizJHOcBN8we55qE5YaF5a65ySd9yAnZVLqM3FS6jNlUXSk7xQhmdW5jdGlvbiDqAWzpAOwg6QDoWzBd6QHpPSAi5gGM5LqGx1zGS33FBnJldHVybtFCyH%2FKZ8YSfcQ8fSwKfTsKPC%2FoAbM%3D&scssValue=LmJveHsKICAgIC5uYW1lxgvEAWNvbG9yOnJlZMUSfQp9Cg%3D%3D

https://codehouse.jd.com/?source=share&type=vue&mainJs=aW1wb3J0IHsgY3JlYXRlQXBwIH0gZnJvbSAidnVlIjsKxyHEGcYXLi9hcHAuzR17IFN3aXBlcixUYWIsQnV0dG9uyUZAbnV0dWkvxQbKMs0XL2Rpc3Qvc3R5bGUuY3NzIjsK6QCNKEFwcCkudXNlKMZixgxUYWLGCcZsKS5tb3VudCgiI2FwcCIpOw%3D%3D&appValue=PHRlbXBsYXRlPgo8bnV0LXRhYj4KICDIDC1wYW5lbCDECnRpdGxlPSLlhajpg6giCiAgICA%2BPHAgY2xhc3M9ImNvbnRlbsU0Ij57e2ZpcnN0TnVtfX08L3A%2BPC%2FNTwogIN9kvoXku5jmrL7eZ%2Bi%2FmemHjOaYr%2Bmhteetvsk25YaF5a6533nYeeaUtuiOt9950XnGNt953Hm3suWujOaIkN95z3nINt55yRTnAeRidXR0b24gdHlwZT0icHJpbWFyeSIgQGNsaWNrPSJjaGFuZ2VOdW0iPuaUueWPmOaVsOaNrsZFxjvEU%2BoCOAo8c2NyaXB0PgppbXBvcnQgeyByZWYgLCByZWFjdGl2ZSx0b1JlZnMgfSBmcm9tICJ2dWUiOwpleMUtZGVmYXVsdCB7CiAgc2V0dXAoKcUMICBjb25zdCDoAkogPcRWKDApO8UdZnVuY3Rpb24g6QCvKCnGNyAgbGV0IGN1cnLGNshBLnZhbHVlxj4gzxY9yDArMcUgfcUGcmV0dXJu5wCOIMpqLM9ExjPEWn0KfQo8L%2BcBDw%3D%3D&scssValue=LmJveHsKICAgIC5uYW1lxgvEAWNvbG9yOnJlZMUSfQp9Cg%3D%3D

**Comment by 307god** [comment]
```
"dependencies": {
  "@babel/runtime": "^7.7.7",
  "@nutui/nutui-taro": "^3.1.4",
  "@tarojs/components": "3.3.5",
  "@tarojs/runtime": "3.3.5",
  "@tarojs/taro": "3.3.5",
  "dayjs": "^1.10.6",
  "vue": "^3.0.0",
  "vuex": "4.0.2"
},
"devDependencies": {
  "@babel/core": "^7.8.0",
  "@tarojs/mini-runner": "3.3.5",
  "@tarojs/plugin-html": "^3.3.5",
  "@tarojs/webpack-runner": "3.3.5",
  "@types/webpack-env": "^1.13.6",
  "@typescript-eslint/eslint-plugin": "^4.15.1",
  "@typescript-eslint/parser": "^4.15.1",
  "@vue/compiler-sfc": "^3.0.0",
  "babel-preset-taro": "3.3.5",
  "eslint": "^6.8.0",
  "eslint-config-taro": "3.3.5",
  "eslint-plugin-vue": "^7.0.0",
  "stylelint": "9.3.0",
  "typescript": "^4.1.0",
  "vue-loader": "^16.0.0-beta.8"
}
```
我把第二个例子一模一样复制过来跑，一样值改变了，页面上的内容没变。
微信小程序和h5都是这样。
我想知道我的依赖是不是一个合适的版本
@zhenyulei

**Comment by Zigei** [comment]
3.1.5 还是无法使用。  @zhenyulei  官网的例子复制过来跑不了啊。

**Comment by willove** [comment]
感觉 nut-tab-panel 还会有性能问题，和 nut-popup 组件一起用会爆出“Maximum call stack size exceeded” 超出最大调用堆栈大小。

**Comment by richard1015** [comment]
> 感觉 nut-tab-panel 还会有性能问题，和 nut-popup 组件一起用会爆出“Maximum call stack size exceeded” 超出最大调用堆栈大小。
> 3.1.5 还是无法使用。 @zhenyulei 官网的例子复制过来跑不了啊。

使用v3.1.9 新 tabs组件即可
