### ISSUE TITLE
[suggest]针对折叠面板可以支持插槽传自定义标题吗

### ISSUE THREAD

**Issue by MadWeb** [jdf2e/nutui#586]
## 你建议我们做什么？
增加

现在nut-collapse折叠面板不支持插槽传标题

如果你能增加具名插槽传自定义标题内容

它将使折叠面板组件具有更好的扩展性

## 其它

无

**Comment by Ymm0008** [comment]
功能已完善，待下个版本发布，感谢反馈。 @MadWeb
