### ISSUE TITLE
[question] 日期控件不支持月份选择吗

### ISSUE THREAD

**Issue by lebronjs** [jdf2e/nutui#588]
## 你想知道什么？

你好，我想知道 datepicker 是否支持month类型

如果不支持就很尴尬了，项目中需要月份选择器

**Comment by richard1015** [comment]
datepicker picker 组件重构中

**Comment by richard1015** [comment]
Calendar 日历选择 ，新增交互，点击日期快速选择 年月

**Comment by ShawshankLin** [comment]
> Calendar 日历选择 ，新增交互，点击日期快速选择 年月

文档上怎么没看到有这个？

**Comment by holyrong** [comment]
3.1.18版本，还是不能选择月份
