### ISSUE TITLE
[bug]Infiniteloading 组件 PageA调用 切换到PageB,从PageB返回PageA,PageA中上拉加载更多,会调用PageB中上拉刷新方法

### ISSUE THREAD

**Issue by erdezhuang** [jdf2e/nutui#589]
## 问题描述
Infiniteloading 组件 PageA调用 切换到PageB,从PageB返回PageA,PageA中上拉加载更多,会调用PageB中上拉刷新方法

## 相关环境信息
- **操作系统**：     Mac
-  **Taro 版本**：  @Taro@3.3.3
- **NutUI 版本**： @nutui/nutui@3.1.3
- **Vue 版本**：    vue@3.2.4
- **引用方式**：     NPM

**Comment by richard1015** [comment]
使用Taro    https://taro-docs.jd.com/taro/docs/components/viewContainer/scroll-view
