### ISSUE TITLE
2.09版本，引入scss报错

### ISSUE THREAD

**Issue by yehuagao** [jdf2e/nutui#59]
![image](https://user-images.githubusercontent.com/23260155/55311428-787f9c00-5495-11e9-99e4-c9bc9875f45f.png)

**Comment by yehuagao** [comment]
2.0.9版本

**Comment by Franslee** [comment]
`import NutUI from "@nutui/nutui";
import '@nutui/nutui/dist/nutui.scss';`

是这么用的吗？

**Comment by yehuagao** [comment]
是的，同时设置了主题色，
![image](https://user-images.githubusercontent.com/23260155/55379935-31ef7780-5551-11e9-9218-82e56172353e.png)

**Comment by yehuagao** [comment]
报错，注释后，引入scss就可以了，只能手动源文件里改主题色

**Comment by Franslee** [comment]
我这边测试是正常的，可能与你的webpack配置有关，style-loader/css-loader之类的loader有配置吗？

**Comment by yehuagao** [comment]
嗯，谢谢，我看看吧
