### ISSUE TITLE
文档的bug

### ISSUE THREAD

**Issue by NomadBin** [jdf2e/nutui#591]
https://github.com/jdf2e/nutui/blob/8632924ef69b139f1cfed47162ea35eee7504f2e/src/sites/doc/components/Search.vue#L102

上面代码有问题，当输入回车时会报错。因为data中没有$router。 应该使用 vue-router 的 compsition api:
```js
import { useRouter } from 'vue-router';
const router = useRouter();
router.push('your path')
```

**Comment by Drjingfubo** [comment]
感谢，已修复
