### ISSUE TITLE
日历组件Calendar: end-date 设置为今天之前，比如昨天，但是今天的日期还是高亮，能自己指定高亮的日期吗？？

### ISSUE THREAD

**Issue by kevinlxj** [jdf2e/nutui#60]
日历组件: end-date 设置为今天之前，比如昨天，但是今天的日期还是高亮，能自己指定高亮的日期吗？？

**Comment by kevinlxj** [comment]
测试时发现第一次显示当天，如4月1号，取消再点开就正常了，为3月31号，是bug？

**Comment by irisSong** [comment]
输入startDate、endDate、defaultValue 截图一下

**Comment by kevinlxj** [comment]
测试代码如下：
![image](https://user-images.githubusercontent.com/28834148/55380432-bb537980-5552-11e9-9dd2-55666e2fd9c5.png)

以今天为例：
第一次打开显示为4月2号，不是我希望的，如下图,endDate、defaultValue 为2019-04-01，但是currDate 和 defaultDate均为4月2号，导致第一次打开显示为4月2号
![image](https://user-images.githubusercontent.com/28834148/55380194-0faa2980-5552-11e9-90ae-75ffa48fd3eb.png)
关闭后再打开就显示为4月1号，这是我希望的，如下图, 此时currDate 和 defaultDate均为4月1号了，
![image](https://user-images.githubusercontent.com/28834148/55380394-a0810500-5552-11e9-8132-a46865afeb39.png)

**Comment by irisSong** [comment]
defaultValue 改成在created里面赋值可解决

**Comment by yyccQQu** [comment]
添加一点
```
<nut-datepicker
					:is-visible="isVisible"
					type="date"
					title="请选择日期"
					:is-show-chinese="false"
                    startDate="1900-01-01"
                    endDate="2019-04-05"
					@close="switchPicker('isVisible')"
					@choose="setChooseValue"
				></nut-datepicker>
```
![image](https://user-images.githubusercontent.com/32674176/55619053-2951a800-57c2-11e9-8e7c-1668b8208da0.png)

-- 结束日期能否只显示到4月5号

**Comment by yyccQQu** [comment]
> defaultValue 改成在created里面赋值可解决

·在吗

**Comment by richard1015** [comment]
请升级最近版本进行测试
