### ISSUE TITLE
DIalog组件 小程序报错 Object(...) is not a function

### ISSUE THREAD

**Issue by DeerL1o** [jdf2e/nutui#604]
##
 import NutUI from "@nutui/nutui-taro";
import '@nutui/nutui-taro/dist/style.css';

import './app.less'

const App = createApp({
  onShow (options) {},
  // 入口组件不需要实现 render 方法，即使实现了也会被 taro 所覆盖
})
App.use(NutUI)
我已经全局引用了组件，通过template的形式调用是可以的，但是函数的方式会直接报错，Object(...) is not a function
## 
![image](https://user-images.githubusercontent.com/34850028/131255790-b7944a5f-c51d-4c5c-959a-cc7f9da760d6.png)

## 希望能提供有效的解决方案

**Comment by richard1015** [comment]
请尝试删除package-lock、yarn.lock 文件，删除 node_modules

重新安装依赖测试一下

具体demo可以参考  https://github.com/jdf2e/nutui-demo/blob/master/taro/src/feedback/pages/dialog/index.vue

**Comment by DeerL1o** [comment]
@richard1015 demo里的是可以的，函数式调用会报错，小程序不支持nutui函数式写法吗

**Comment by hcw2175** [comment]
+1

```javascript
import { Dialog } from '@nutui/nutui-taro';

export const messenger = {
  success(msg: string) {
    Dialog({
      title: '成功提示',
      content: msg
    });
  }
}
```

然后报错：

```
Unhandled promise rejection TypeError: Object(...) is not a function
```

**Comment by wlchn** [comment]
同样问题，函数式调用会报错

**Comment by wjh0104** [comment]
"@nutui/nutui-taro“ 不支持函数式调用， "@nutui/nutui" 这个库支持函数式调用，官网例子里有明确使用案例。
