### ISSUE TITLE
cell组件没有icon插槽的区域吗

### ISSUE THREAD

**Issue by Pi-char** [jdf2e/nutui#605]
## cell组件没有icon插槽的区域吗

好像只有一个slot:link

**Comment by richard1015** [comment]
目前只有一个 只有一个slot:link
 icon slot 本次发版更新上

**Comment by Pi-char** [comment]
> 目前只有一个 只有一个slot:link
> icon slot 本次发版更新上

thx

**Comment by richard1015** [comment]
已发版3.1.4
