### ISSUE TITLE
DatePicker 日期选择 如何自定义样式

### ISSUE THREAD

**Issue by xuwenliu** [jdf2e/nutui#61]
![image](https://user-images.githubusercontent.com/26993064/55369582-559ac980-5521-11e9-9383-688524078a4d.png)
如图 需要更改字体大小及高度等样式。

**Comment by Franslee** [comment]
可通过增加一个自定义class来实现

**Comment by MeiJunNa** [comment]
> 可通过增加一个自定义class来实现

在哪里增加一个自定义class？`<nut-datepicker
      class = "picker_wrap"
  ></nut-datepicker>`在这上面对该class设置字体大小和颜色，没有生效
