### ISSUE TITLE
checkbox，radio组件目前不支持定制主题吗

### ISSUE THREAD

**Issue by Pi-char** [jdf2e/nutui#613]
## 你想知道什么？

你好，我看了variable.scss里的配置项，似乎没有checkbox，radio选中颜色的配置，目前还不支持吗

**Comment by Pi-char** [comment]
目前可以通过下面这样更改，但总感觉不太好...
.nut-icon-check-checked {
        color: lightblue !important;
}

**Comment by richard1015** [comment]
好的，我们优化一下

**Comment by szg2008** [comment]
已修复，下一版本3.1.4更新

**Comment by richard1015** [comment]
已发版3.1.4
