### ISSUE TITLE
nut-tab-panel 内容超高 使用 overflow-y: auto;在移动设备（手势操作）无法滚动内容。

### ISSUE THREAD

**Issue by fssgh** [jdf2e/nutui#614]
nut-tab-panel 内容超高 使用 overflow-y: auto;在移动设备（手势操作）无法滚动内容。只能用鼠标滚动。。。。
## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@3.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by zhenyulei** [comment]
引用的swiper组件导致的 请修复

**Comment by richard1015** [comment]
新增组件Tabs重构完成，暂时可以使用测试版 [@nutui/nutui-taro@3.1.9-beta.0](https://www.npmjs.com/package/@nutui/nutui-taro/v/3.1.9-beta.0) 
测试版文档 [https://jdf2e.github.io/nutui/#/tabs](https://jdf2e.github.io/nutui/#/tabs)
v3.1.9 发布时间 预计 10.11-10.15

**Comment by richard1015** [comment]
3.1.9 已发布
