### ISSUE TITLE
[bug] NoticeBar 组件在taro小程序环境报警告，并且控制台会卡死

### ISSUE THREAD

**Issue by xueyuheng** [jdf2e/nutui#619]
公告栏组件在使用时会触发以下警告，在使用text属性，弹出一次，使用list属性会一直弹出在控制台，直到控制台卡死
vendors.js?t=wechat&s=1630506767305&v=3cc9687940ef2c207f3ad08f26c661de:9186 
```
[Vue warn]: Failed to resolve component: view-block 
  at <NutNoticebar direction="vertical" list= (4) ["惊喜红包免费领", "爆款准点秒", "买超值优惠", "赢百万京豆"] speed=10  ... > 
  at <NutCol span=16 > 
  at <NutRow> 
  at <NoticeBarForIndex> 
  at <Home tid="pages/index/index?$taroTimestamp=1630507611420" > 
  at <App>
```

**Comment by richard1015** [comment]
taro + nutui  weapp 无法启动问题  ，辛苦先降级nutui 到 3.1.3 版本，这边正在紧急修复，今天发版

**Comment by xueyuheng** [comment]
追加：公告栏组件在使用text属性时 报错
`[渲染层网络层错误]` Failed to load local image resource /pages/index/null 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 
(env: Windows,mp,1.05.2107221; lib: 2.19.2)`

**Comment by siegelioner** [comment]
taro + vue3.0 + nutui weapp 使用noticebar还是出现报错：
[Vue warn]: Failed to resolve component: view-block 
@nutui/nutui-taro 3.1.3、3.1.4、3.1.5都尝试了
