### ISSUE TITLE
[suggest]新增多行输入组件

### ISSUE THREAD

**Issue by HEYAN123** [jdf2e/nutui#621]
## 你建议我们做什么？

输入控件增加多行输入类型，高度随内容换行而自动撑高

效果参考antd mobile TextareaItem组件
https://mobile.ant.design/components/textarea-item-cn/
![image](https://user-images.githubusercontent.com/37286512/131778507-f9975b22-8fbe-40fc-a32b-06d33df6903e.png)

**Comment by Ymm0008** [comment]
功能已补全，感谢反馈。 @HEYAN123
