### ISSUE TITLE
[suggest]可以新增stikcy组件吗？

### ISSUE THREAD

**Issue by transtone** [jdf2e/nutui#627]
## 你建议我们做什么？

和 vant 的 stikcy 组件类似。经常有 tab 标签滚动到顶部置顶的需求。

## 其它
https://vant-contrib.gitee.io/vant/v3/#/zh-CN/sticky

**Comment by szg2008** [comment]
下个版本会发布

**Comment by wandoupeas** [comment]
nutui-taro不支持吗

**Comment by 307god** [comment]
Module not found: Can't resolve '@nutui/nutui-taro/dist/packages/_es/Sticky'

**Comment by 307god** [comment]
https://unpkg.com/browse/@nutui/nutui-taro@3.1.17/dist/packages/_es/ 没有sticky
