### ISSUE TITLE
3.0 input taro [bug]

### ISSUE THREAD

**Issue by 307god** [jdf2e/nutui#628]
## 问题描述

<img width="324" alt="1" src="https://user-images.githubusercontent.com/16452590/132147563-455dbda2-2ddf-4d6a-b17f-b4991bb6a95d.png">

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
input里的内容应该布局一致，但是设置成readonly会导致内容前移

## 复现步骤，具体代码
用的官方demo, https://github.com/jdf2e/nutui-demo/tree/master/taro

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：
- **NutUI 版本**：@nutui/nutui-taro 3.1.5
- **Vue 版本**：vue3
- **引用方式**：  NPM

**Comment by richard1015** [comment]
3.1.7已修复
