### ISSUE TITLE
[question] taro 中 tabbar 在组件切换时 值改变了状态不对怎么解决

### ISSUE THREAD

**Issue by xueyuheng** [jdf2e/nutui#631]
![image](https://user-images.githubusercontent.com/48202935/132166779-e3ea6301-6ace-43fa-bfc6-7c246f2acae6.png)
`<nut-tabbar
      :v-model:visible="active"
      @tab-switch="tabSwitch"
      :bottom="true"
      unactive-color="#7d7e80"
      active-color="#5EAA5F"
    >
      <nut-tabbar-item tab-title="首页" icon="home"></nut-tabbar-item>
      <nut-tabbar-item tab-title="学习" icon="category"></nut-tabbar-item>
      <nut-tabbar-item tab-title="课程" icon="find"></nut-tabbar-item>
      <nut-tabbar-item tab-title="我的" icon="my"></nut-tabbar-item>
    </nut-tabbar>`
`const tabSwitch = (item, index) => {
  let pages = [
    { url: "/pages/index/index" },
    { url: "/pages/study/index" },
    { url: "/pages/courses/index" },
    { url: "/pages/profile/index" }
  ]
  Taro.switchTab(pages[index])
}`
通过switchTab跳转页面没问题，active状态不更新或更新错误
### 环境信息
操作系统：win10
NutUI 版本：@nutui/nutui-taro 3.1.5
Vue 版本：vue3
引用方式： NPM

**Comment by xueyuheng** [comment]
数据是响应式的

**Comment by xueyuheng** [comment]
用vuex可解决此问题

**Comment by 2624431797** [comment]
请问vuex是如何解决的？

**Comment by xueyuheng** [comment]
@2624431797  你拿这个值放在state，通过操作dispatch去改变状态就好了，vue3建议用pinia，我是项目结束了，不想改了

**Comment by 2624431797** [comment]
额 我就是这样整的 没成功才问的
setup(){
 const store = useStore();
 const activeVisible = store.state.app.activeTab;
}

![image](https://user-images.githubusercontent.com/54942617/147048181-9c6a82b3-9669-4e45-9b6d-abd31ac24e5b.png)
在他的方法里dispatch的
const handleSwitchTab = (e) => {
 store.dispatch("TabChange", e.state.active);
 Taro.switchTab({
   url: unref(e).num,
 });
};
是我整的有问题吗

**Comment by xueyuheng** [comment]
你是小程序吗   小程序有onShow 钩子  你放到那个地方试试

**Comment by 2624431797** [comment]
是H5 不是小程序

**Comment by xueyuheng** [comment]
我这边只要做小程序，你再打印调试一下，你可以直接下载源码，去看看啥问题，我再做的时候有好几个组件都是类似这种问题，我都是自己改然后放本地用的

**Comment by 2624431797** [comment]
好的 十分感谢

**Comment by xueyuheng** [comment]
不用谢
