### ISSUE TITLE
[suggest] taro + nut-tab 在使用中状态不更新建议 

### ISSUE THREAD

**Issue by xueyuheng** [jdf2e/nutui#635]
![image](https://user-images.githubusercontent.com/48202935/132302557-28081eb6-3e85-498e-8320-b6433d4ad86b.png)
### 场景： 
首页某个按钮点击 `switchTab` 带参跳转到课程，并且把这个参赋值给` defaultIndex `这个属性，第一次是更新的，第二次就是中是不更新，使用computed属性也没用，发现是源码中缺少对于接受` defaultIndex ` 的监听

### 建议
在路径 `\src\packages\__VUE\tab\index.taro.vue` 106 行
`const activeIndex = ref(props.defaultIndex);`
改为
`let activeIndex = ref(props.defaultIndex);`

并监听`props.defaultIndex` 及时给`activeIndex`赋值

**Comment by zhenyulei** [comment]
你好 感谢反馈 已经修改待下个版本发版后 线上更新
