### ISSUE TITLE
可以增加Sku（商品规格）组件吗

### ISSUE THREAD

**Issue by feelslive** [jdf2e/nutui#64]
可以增加Sku（商品规格）组件吗  谢谢！
![image](https://user-images.githubusercontent.com/20579220/55539778-12dd1b00-56f4-11e9-86a8-ea9533848138.png)

**Comment by ywfwj2008** [comment]
嗯。这个很需要

**Comment by Franslee** [comment]
受限于商品的规格类型众多，这个组件的通用性会受影响，所以该组件需求尚需进一步调研。目前建议使用price/stepper/button/dialog等现有组件组合实现。

**Comment by feelslive** [comment]
> 受限于商品的规格类型众多，这个组件的通用性会受影响，所以该组件需求尚需进一步调研。目前建议使用价格/步进/按钮/对话框等现有组件组合实现。

好的，谢谢，会继续关注！

**Comment by richard1015** [comment]
v3.1.11 已发布 https://nutui.jd.com/#/sku
