### ISSUE TITLE
在tab-panel 内使用nut-cell 等@click事件失效 [bug]

### ISSUE THREAD

**Issue by fssgh** [jdf2e/nutui#640]
在tab-panel 内使用nut-cell 等@click事件失效！！！！！！！
 `<nut-tab-panel :tab-title="校准">
          <div class="my-tab-panel">
            <nut-cell title="校准" is-link @click="JzPwdState.visible = true;"></nut-cell> 
            <nut-shortpassword 
              v-model="JzPwdState.value"
              v-model:visible="JzPwdState.visible"
              :no-button="JzPwdState.noButton"
              :length="JzPwdState.length"
              :error-msg="JzPwdState.errorMsg"
              :tips="JzPwdState.tips"
              @complete="onPwdComplete">
          </nut-shortpassword>
          </div>
        </nut-tab-panel>`

**Comment by richard1015** [comment]
辛苦尝试升级到 3.1.5 测试一下

**Comment by richard1015** [comment]
新增组件Tabs重构完成，暂时可以使用测试版 [@nutui/nutui-taro@3.1.9-beta.0](https://www.npmjs.com/package/@nutui/nutui-taro/v/3.1.9-beta.0) 
测试版文档 [https://jdf2e.github.io/nutui/#/tabs](https://jdf2e.github.io/nutui/#/tabs)
v3.1.9 发布时间 预计 10.11-10.15

**Comment by richard1015** [comment]
3.1.9 已发布
