### ISSUE TITLE
微信小程序button按钮loading和disabled为true时仍可点击且触发事件

### ISSUE THREAD

**Issue by Winniebear2** [jdf2e/nutui#645]
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**："@nutui/nutui-taro": "^3.0.3",
- **Vue 版本**：Vue 3.0.0
- **引用方式**： NPM

**Comment by richard1015** [comment]
我这边测试的没问题， 辛苦升级到 3.1.5进行测试
