### ISSUE TITLE
[suggest] 请求适配webstorm 智能提示

### ISSUE THREAD

**Issue by OneSeven** [jdf2e/nutui#646]
## 你建议我们做什么？

希望能够适配webstorm智能提示
参考：
https://github.com/JetBrains/web-types
https://cdn.jsdelivr.net/npm/vant@3.2.2/vetur/web-types.json 

现在用webstorm开放web还是taro用到nutui体验太差了
## 其它

无

**Comment by richard1015** [comment]
:(  暂时没有精力

**Comment by tolking** [comment]
我之前写过基于md文档生成提示文件的工具，感兴趣可以参考下 [components-helper](https://github.com/tolking/components-helper)

**Comment by hhch** [comment]
既然开发哥哥忙，只能小顶一下了

**Comment by szg2008** [comment]
已支持，6.24发版
