### ISSUE TITLE
微信小程序端Range组件点按修改进度条有些些问题

### ISSUE THREAD

**Issue by Pi-char** [jdf2e/nutui#648]
## 问题描述
当页面存在多个Range组件时，点按默认的是修改最后一个Range组件的进度条，但拖动修改的是当前组件的进度条。
在官方NutUI小程序中也是如此，希望大大们可以看看！！

**Comment by richard1015** [comment]
@zy19940510

**Comment by richard1015** [comment]
3.1.7已修复
