### ISSUE TITLE
[question] message：Error: 代码包大小为 XXX kb，上限为 2048 kb，请删除文件后重试

### ISSUE THREAD

**Issue by 307god** [jdf2e/nutui#649]
## 你想知道什么？

微信开发者工具 预览或者真机调试会报错
message：Error: 代码包大小为 2057 kb，上限为 2048 kb，请删除文件后重试
<img width="510" alt="2" src="https://user-images.githubusercontent.com/16452590/133047352-b8d16538-74fe-4cd6-88ac-a7ca4337574a.png">
<img width="618" alt="3" src="https://user-images.githubusercontent.com/16452590/133047362-f62bf4ca-137a-4536-8ea1-182f7763d296.png">

## 描述你考虑过的替代方案

我已经按需加载了呀， 依赖用的都是当前最新

## 其它

无

**Comment by Pi-char** [comment]
run build之后就行了

**Comment by richard1015** [comment]
npm run build

**Comment by richard1015** [comment]
npm run build:weapp

**Comment by 307god** [comment]
预览或者真机调试，一定要先build，感觉好不方便 o(╥﹏╥)o

**Comment by richard1015** [comment]
> 预览或者真机调试，一定要先build，感觉好不方便 o(╥﹏╥)o

我们尽快优化一下 按需加载问题

**Comment by richard1015** [comment]
v3.1.7-beta.2 可测试，预计9月30日发布 3.1.7正式版

参考文档 按需加载片段 https://nutui.jd.com/#/start

**Comment by richard1015** [comment]
npm run build:weapp --watch 也是可以的

**Comment by richard1015** [comment]
3.1.7已修复，请参考 最新按需加载 使用文档
