### ISSUE TITLE
请问怎么实现微信小程序中获取手机号

### ISSUE THREAD

**Issue by wgcairui** [jdf2e/nutui#650]
在微信中在点击元素上添加  open-type="getPhoneNumber"会唤起授权,事件对象会携带encryptedData,nutui和taro没找到相关操作

**Comment by richard1015** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html

**Comment by wgcairui** [comment]
微信文档我知道,但是nut-button上哪个事件对应bindgetphonenumber="getphonenumber"呢,click事件对象中没有encryptedData,

**Comment by aehyok** [comment]
@wgcairui  我也遇到了这个问题，请问解决了吗？

**Comment by xueyuheng** [comment]
@aehyok @wgcairui  翻阅Taro文档   使用 `<button open-type="getPhoneNumber" @getphonenumber="getPhoneNumber">微信登录</button>` 就能解决问题

**Comment by aehyok** [comment]
@xueyuheng 谢谢，知道了 要用原生的button按钮
