### ISSUE TITLE
nutui-taro3.1.4组件input样式[bug]

### ISSUE THREAD

**Issue by luhualong** [jdf2e/nutui#651]
## 问题描述
taro版本h5input框显示有问题
![image](https://user-images.githubusercontent.com/50528346/133229077-43561847-c3cd-4339-b398-116513421fd5.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
引入
```
import { Input } from '@nutui/nutui-taro';

import '@nutui/nutui-taro/dist/styles/themes/default.scss';
const App = createApp({
  onShow (options) {},
  // 入口组件不需要实现 render 方法，即使实现了也会被 taro 所覆盖
})

App.use(Input)
```

使用
```
     <nut-input

              label="文本"
      />
      <nut-input placeholder="请输入文本"

                 label="文本"
      />

```

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui-taro@3.1.4 
- **Vue 版本**：
- **引用方式**：  NPM

**Comment by richard1015** [comment]
3.1.6已修复

**Comment by luhualong** [comment]
> 3.1.6已修复

已升级 还是显示有问题 期待样式与小程序一致 因为需要做h5与微信小程序的两端
![image](https://user-images.githubusercontent.com/50528346/134316537-272f9952-093b-48db-87a6-926cbba5795f.png)
![image](https://user-images.githubusercontent.com/50528346/134318802-745d6f6a-7fe2-41c2-8ff2-7bdc477da28f.png)
