### ISSUE TITLE
vue3.0 SwiperItem未导出

### ISSUE THREAD

**Issue by gmars** [jdf2e/nutui#652]
## 问题描述
SwiperItem未导出

## 最小可复现仓库
import {Swiper, SwiperItem} from "@nutui/nutui"

"@nutui/nutui": "^3.1.5",

**Comment by richard1015** [comment]
感谢反馈，只是ts没有类型提示，应该是可以直接引用的，我们本周发布v3.1.6修复一下

**Comment by richard1015** [comment]
v3.1.6 已修复

**Comment by yangjisen** [comment]
> v3.1.6 已修复

v3.1.14 swper swperItem 在 ` "@nutui/nutui-taro": "^3.1.14" ` 中仍然无法导出
