### ISSUE TITLE
@tarojs/plugin-html 是否必须使用，根据官网初始的小程序。

### ISSUE THREAD

**Issue by JRainboww** [jdf2e/nutui#656]
## 你想知道什么？

项目 vue3 + taro3 + nutui

你好，我想知道这个项目是否可以不使用 @tarojs/plugin-html 插件。尝试过不使用该插件，当不使用该插件时 tabbar 和 toast中的加载icon不会正常显示。
由于@tarojs/plugin-html 插件对小程序地图<map>标签转译，导致无法渲染地图，而项目中有地图组件的需求。在taro3 的git项目已提issue，但不知何时处理。所以咨询一下这边能否不使用plugin-html。项目已开发一大半。

**Comment by richard1015** [comment]
@tarojs/plugin-html 插件  在vue里面必须要用，  主要功能是将  div p 等标签、  @click 事件  等功能进行磨平， 基本上在 vue 里面必须使用
关于你说的 @tarojs/plugin-html 插件对小程序地图标签转译 ，我们这边和Taro内部 同步一下信息加快 你那个issues的修复

辛苦您发一下 taro issue 对应链接

**Comment by JRainboww** [comment]
感谢回复哈  issue 地址： https://github.com/NervJS/taro/issues/10280

**Comment by richard1015** [comment]
从官网底部  加一下我们微信群，方便及时沟通
