### ISSUE TITLE
[bug] 对 taro 的支持度不是很高

### ISSUE THREAD

**Issue by Zigei** [jdf2e/nutui#658]
3.1.5 当前的这个版本对 现阶段 Taro3 vue3 的支持度不是很友好。

## 问题描述

在 html 上是可以运行的但是 taro 中并没有 i span 之类的标签。
经常会碰到 类似这种问题。

比如 cell 组件添加上 is-link
WXMLRT_$gwx:./base.wxml:template:473:16: Template `tmpl_0_i` not found.  

tab 组件title信息无法渲染。
WXMLRT_$gwx:./base.wxml:template:601:16: Template `tmpl_0_span` not found.

使用 tabber 还会出现
Failed to resolve component: scroll-view  这个问题。

tab 组件无法正常工作。

## 预期的行为和实际行为

修正 Taro v3  中没有的标签
tab 组件可以在 Taro 中正常使用。

## 相关环境信息
- **操作系统**： macOS
- ** Taro版本**: v3.3.7
- **Node 版本**：v14.17.0
- **NutUI 版本**： @nutui/nutui@3.1.5 
- **Vue 版本**：3.2.11
- **引用方式**： NPM

**Comment by paseaf** [comment]
请问楼主解决问题了吗?我也遇到了类似的问题
加上下面这行就会报错
```html
 <nut-inputnumber />
```
错误：
![image](https://user-images.githubusercontent.com/33207565/157268839-3b32052d-5b34-4cd9-ad49-15e0ca6dcd02.png)

- 操作系统： Win 10
- Taro版本: v3.4.2
- Node 版本：v16.14.0
- NutUI 版本： @nutui/nutui-taro@3.1.17
- Vue 版本：3.2.31
- 引用方式： NPM

**Comment by Mng12345** [comment]
这问题怎么就closed了呢
