### ISSUE TITLE
vue cil3 按需引入怎么配置呀

### ISSUE THREAD

**Issue by sym134** [jdf2e/nutui#66]
配置搞不定😢

**Comment by Franslee** [comment]
参考官网快速上手文档按需加载部分即可 http://nutui.jd.com/#/start
如果还不行，请贴出具体错误信息

**Comment by lany9527** [comment]
@Franslee 报错如下：
![image](https://user-images.githubusercontent.com/19483798/67180286-b9c4a280-f40b-11e9-9bd4-c0cb1eef7efa.png)
![image](https://user-images.githubusercontent.com/19483798/67180319-d7920780-f40b-11e9-9bb5-ec37cd00811b.png)
![image](https://user-images.githubusercontent.com/19483798/67180343-e8db1400-f40b-11e9-8f71-66023f8d9041.png)

**Comment by richard1015** [comment]
vue cli3   NutUI 按需加载、 定制化主题 请参考 https://github.com/richard1015/nutui-demo
