### ISSUE TITLE
Vue3.0 Dialog组件不设置content属性

### ISSUE THREAD

**Issue by yangjinjun3** [jdf2e/nutui#660]
## 问题描述
Vue3.0 Dialog组件不设置content属性，dom节点还存在，导致一大片空白

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
期望不设置content属性时，高度自适应。看了下是弹框最小高度导致，可以调整下，默认不要设置太大。

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
min-height 自定义样式调整
