### ISSUE TITLE
2.X版本 Scroller 组件，下拉刷新的“加载中”文案不可动态修改

### ISSUE THREAD

**Issue by jaelam0214** [jdf2e/nutui#662]
## 建议增加一个Prop属性，支持修改2.X版本 Scroller 组件，下拉刷新的“加载中”文案

当做国际化文案或是需要自定义设置，下拉刷新，刷新中的文案时，不能进行修改。
建议增加一个Prop属性，支持修改2.X版本 Scroller 组件，下拉刷新的“加载中”文案

**Comment by richard1015** [comment]
感兴趣的话，可以给我们提个PR ，这个功能不复杂

**Comment by richard1015** [comment]
v2.3.6
