### ISSUE TITLE
[bug] Failed to resolve component: view-block scroll-view 

### ISSUE THREAD

**Issue by JiaYifan** [jdf2e/nutui#669]
## 问题描述
在taro中使用Infiniteloading会有Failed to resolve component: view-block和Failed to resolve component: scroll-view两个warning不断打印

- **NutUI 版本**： "@nutui/nutui-taro": "^3.0.3"
- **Vue 版本**："vue": "^3.0.0"
- **引用方式**：  NPM

**Comment by richard1015** [comment]
Infiniteloading 滚动加载

直接使用 Taro 现有 [ScrollView](https://docs.taro.zone/docs/components/viewContainer/scroll-view) 组件开发 参考文档
