### ISSUE TITLE
Picker 拾取器的年月

### ISSUE THREAD

**Issue by kevinlxj** [jdf2e/nutui#67]
Picker 拾取器的年月选择在chrome浏览器和安卓真机(华为P20)上没问题，但是在苹果(iphone8p)上不仅样式有问题，如图，重叠了，而且卡顿，代码就是官网的demo代码，麻烦看看
![image](https://user-images.githubusercontent.com/28834148/55623881-ce767b80-57d6-11e9-9604-00b11c846946.png)
![image](https://user-images.githubusercontent.com/28834148/55623893-d9311080-57d6-11e9-8685-bf3a3e9ba28e.png)

**Comment by kevinlxj** [comment]
iphone8p的safari和微信自带的浏览器都是这个问题。

**Comment by irisSong** [comment]
请提供一下iphone8p是什么ios几系统哈，暂时在11和12暂未发现这个问题。

**Comment by kevinlxj** [comment]
我是按需加载的，其他按需引入button，toast，dialog样式均是正常的。：
这是chrome网页浏览器的，样式正常：
![image](https://user-images.githubusercontent.com/28834148/55936288-69080c00-5c68-11e9-85da-31223179ae15.png)
这是iphone8p，ios12，safari样式不正常:
![image](https://user-images.githubusercontent.com/28834148/55936388-cac87600-5c68-11e9-890f-edc0155f55ab.png)

我用的vue-cli2 我的代码配置如下：
![image](https://user-images.githubusercontent.com/28834148/55936231-4249d580-5c68-11e9-9b1a-6cd582656534.png)
![image](https://user-images.githubusercontent.com/28834148/55936543-301c6700-5c69-11e9-830a-a6605fe7830a.png)
![image](https://user-images.githubusercontent.com/28834148/55936557-3b6f9280-5c69-11e9-9e18-4f638c890e52.png)
![image](https://user-images.githubusercontent.com/28834148/55936587-50e4bc80-5c69-11e9-9471-ea7398d35b04.png)

以下是完整的、很简单的、能复现的picker demo代码，请测试。
[nutui-picker-demo.zip](https://github.com/jdf2e/nutui/files/3067302/nutui-picker-demo.zip)

**Comment by kevinlxj** [comment]
@irisSong 已详细描述，请查看我的测试demo。

**Comment by kevinlxj** [comment]
@irisSong 你们复现了吧，是个bug不？

**Comment by richard1015** [comment]
请升级最新版本进行测试
