### ISSUE TITLE
[bug]小程序tab组件build完之后多点击几次，整个页面无法操作

### ISSUE THREAD

**Issue by imcq333** [jdf2e/nutui#673]
tab组件小程序环境，dev模式可以正常使用，build完之后tab点击切换4次（如果tab是4个）整个页面都会卡死，无法点击
## 问题描述

官方示例也有这个问题，扫码进入tab标签组件，任意点击4个tab，页面就无法进行操作了
![avatar](https://storage.360buyimg.com/jdc-article/gh_f2231eb941be_258.jpg)
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
预期：tab正常可以点击
实际：tab点击几次后页面无法操作

## 相关环境信息
- **操作系统**：安卓、windows小程序模拟器，ios
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@3.1.6
- **Vue 版本**：vue3
- **引用方式**：  yarn

**Comment by willove** [comment]
这个我遇到过，是报 Maximum call stack size exceeded 了。我的临时解决办法是不在 nut-tab-panel 写实现，而是重新使用多个view通过判断 tabIndex 来控制对应tab的显示

**Comment by richard1015** [comment]
感谢反馈，我们处理一下，小程序微信审核中

**Comment by Zigei** [comment]
@richard1015   这个问题这两天能解决吗？ 我也碰到类似的问题  点击 tab， 屏幕事件就被吃掉了  只能滑动屏幕 无法点击其他元素了。

**Comment by richard1015** [comment]
解决中

**Comment by richard1015** [comment]
新增组件Tabs重构完成，暂时可以使用测试版 [@nutui/nutui-taro@3.1.9-beta.0](https://www.npmjs.com/package/@nutui/nutui-taro/v/3.1.9-beta.0) 
测试版文档 [https://jdf2e.github.io/nutui/#/tabs](https://jdf2e.github.io/nutui/#/tabs)
v3.1.9 发布时间 预计 10.11-10.15

**Comment by richard1015** [comment]
3.1.9 已发布
