### ISSUE TITLE
[bug]taro-vue3项目下组件Divider引入报错 找不到组件 

### ISSUE THREAD

**Issue by 969319036** [jdf2e/nutui#674]
![image](https://user-images.githubusercontent.com/28749572/134273637-7a7c00f6-158f-4959-ad57-f277cdd2cab2.png)
![image](https://user-images.githubusercontent.com/28749572/134273661-e4676be4-9f0f-4969-9042-63c4c598d0b4.png)

操作系统：安卓、windows小程序模拟器，ios
Node 版本：
NutUI 版本： @nutui/nutui@3.1.5
Vue 版本：vue3
引用方式： yarn

**Comment by Gandamar3** [comment]
Leave a comment
