### ISSUE TITLE
在taro里面使用nutui的tab组件，在nut-tab-panel里面嵌套view或者是嵌套text标签，第二个tab内容会把第一个tab内容覆盖

### ISSUE THREAD

**Issue by ziHan9703** [jdf2e/nutui#678]
## 问题描述

在taro里面使用nutui的tab组件，在nut-tab-panel里面嵌套view或者是嵌套text标签，第二个tab内容会把第一个tab内容覆盖
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
<nut-tab>
  <nut-tab-panel tab-title="全部"
    ><text>1</text></nut-tab-panel
  >
  <nut-tab-panel tab-title="待付款"
    ><text>2</text></nut-tab-panel
  >
  <nut-tab-panel tab-title="待收获"
    ><text>3</text></nut-tab-panel
  >
  <nut-tab-panel tab-title="已完成"
    ><text>4</text></nut-tab-panel
  >
</nut-tab>
基础使用tab组件，每个 nut-tab-panel标签里都嵌套view或者是text，写个1，2,3,4，切换就可以复现

## 相关环境信息
- **操作系统**：windows
- **Node 版本**：14
- **NutUI 版本**： 3.1.6
- **Vue 版本**：3
- **引用方式**：  CDN / NPM ？npm

**Comment by richard1015** [comment]
新增组件Tabs重构完成，暂时可以使用测试版 [@nutui/nutui-taro@3.1.9-beta.0](https://www.npmjs.com/package/@nutui/nutui-taro/v/3.1.9-beta.0) 
测试版文档 [https://jdf2e.github.io/nutui/#/tabs](https://jdf2e.github.io/nutui/#/tabs)
v3.1.9 发布时间 预计 10.11-10.15

**Comment by richard1015** [comment]
3.1.9 已发布
