### ISSUE TITLE
在手机设备上运行，短密码组件的值会成倒序[bug]

### ISSUE THREAD

**Issue by fssgh** [jdf2e/nutui#679]
在手机设备上运行，短密码组件的值会成倒序........
## 相关环境信息
- **操作系统**：android
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@3.1.5 
- **Vue 版本**：3
- **引用方式**：  CDN / NPM ？

**Comment by Drjingfubo** [comment]
请提供复现机型及安卓版本

**Comment by fssgh** [comment]
@Drjingfubo @richard1015 已编写重现[codesandbox](https://codesandbox.io/s/nutui3-0-vite-js-forked-x02yz)

**Comment by Drjingfubo** [comment]
请提供复现机型及安卓版本

**Comment by fssgh** [comment]
@Drjingfubo  安卓10（应该所有安卓都会）,荣耀30，苹果不会

**Comment by Drjingfubo** [comment]
加下官网下方微信沟通群吧。这边都没复现到

**Comment by richard1015** [comment]
3.1.7已修复
