### ISSUE TITLE
关于switch和swiper的两个建议

### ISSUE THREAD

**Issue by waitkafuka** [jdf2e/nutui#68]
1. switch功能相对单薄，change事件只返回了isActive参数，不够用呀。页面上有多个switch的时候，很难区分是哪一个？建议返回这个组件的实例，我们可以在实例上绑定一些参数来用。
2. swiper能否加一个在切换过程中实时反映偏移量的参数（不是slideMove）？类似小程序里面的[bindtransition](https://developers.weixin.qq.com/miniprogram/dev/component/swiper.html):
![image](https://user-images.githubusercontent.com/8555018/55767365-277e3200-5aab-11e9-82a2-6a55600ed008.png)
这对于切换时候精确控制一些动画很有好处。

**Comment by Franslee** [comment]
感谢建议，我们会考虑的。

**Comment by zjyau** [comment]
@waitkafuka ，switch 这种场景可以这样
`<div v-for="(item, index) of datalist" :key="index">
<nut-switch @change="itemOnChange($event, item.id)">
</nut-switch>
</div>

 itemOnChange(status, id) {
   //status:ture/false
   //id para
 }`
