### ISSUE TITLE
迫切强烈要求，nutUI出一个表格组件，能翻页或无限下拉刷新，可以配置固定列和操作列！！！！！！

### ISSUE THREAD

**Issue by fujiayang** [jdf2e/nutui#680]
如题，迫切强烈要求，nutUI出一个表格组件，能翻页或无限下拉刷新，可以配置固定列和操作列！！！！！！
很多B端审批、报表、监控类的业务场景中非常需要表格来展示数据和操作数据。
用户需求十分强烈！
民情汹涌！

**Comment by ajuner** [comment]
移动端用表格的场景是不是很少见 😢

**Comment by fujiayang** [comment]
> 移动端用表格的场景是不是很少见 😢
-----------------------------------------------------------------------------------------------------
一点都不少见。B端产品，尤其是财务报表审批、预算审批、数据监控，这类报表和审批一体的业务，非常常见。不要以C端产品的角度来看B端产品。
而且现在移动审批和移动监控越来越多，朋友。

**Comment by richard1015** [comment]
@yangjinjun3 +1
