### ISSUE TITLE
[bug] range error-Taro2.createSelectorQuery is not a function 

### ISSUE THREAD

**Issue by 969319036** [jdf2e/nutui#682]
## 问题描述

Taro2.createSelectorQuery is not a function 

![image](https://user-images.githubusercontent.com/28749572/134650685-f062e3bf-57d9-47f8-9692-07a275854a38.png)

![image](https://user-images.githubusercontent.com/28749572/134650649-f1035403-33d5-4632-bf4c-2ca9972ddda5.png)
![image](https://user-images.githubusercontent.com/28749572/134651049-5cae6b18-9121-42f7-bd05-404be590dd8f.png)

![image](https://user-images.githubusercontent.com/28749572/134651284-12638f99-99f0-4ece-8c4d-18f536c96258.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**： window
- **Node 版本**： v14.17.6
- **NutUI 版本**： "@nutui/nutui-taro": "^3.1.7-beta.0",
- **Vue 版本**："vue": "^3.0.0",
- **引用方式**：  NPM 
- **taro版本**：  "@tarojs/taro": "3.3.7",

**Comment by 969319036** [comment]
Uploader 上传 也有同样问题

**Comment by richard1015** [comment]
好的，感谢反馈，我们跟进一下

**Comment by richard1015** [comment]
@969319036  执行的是 npm run dev:h5 对吗

**Comment by 969319036** [comment]
> @969319036 执行的是 npm run dev:h5 对吗

是的

**Comment by richard1015** [comment]
3.1.7已修复
