### ISSUE TITLE
[bug] Taro中使用 nut-uploader 中 file-list 回显缺少监听展示

### ISSUE THREAD

**Issue by xueyuheng** [jdf2e/nutui#684]
问题：nut-uploader 中 fileList 参数初始化一组数据有用，用接口赋值无效，图片数据回显没效果，源码中缺少对于fileList监听事件的钩子
## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Taro 版本**："@tarojs/taro": "3.3.7",
- **NutUI 版本**： "@nutui/nutui-taro": "^3.1.6",
- **Vue 版本**："vue": "^3.2.9",
- **引用方式**：NPM ？

**Comment by xueyuheng** [comment]
抱歉，时间原因，我再把问题细化一下 并附上代码
**template**
`<nut-uploader
            url
            :maximum="1"
            v-model:file-list="state.file1List"
            @change="handleFileChange($event, 'file1')"
          ></nut-uploader>`
**script  setup**
`
const state = reactive({
    file1List: []
})
`
以上代码是初始化 ok 没有问题 

我引入onMounted钩子  在钩子里执行
`
state.file1List = [{
    url: "…… .png",
    id: 1407,
    name: "41.png"
  }]
`
组件无回显

目前已通过拉取源码，并通过computed属性解决此问题

**Comment by richard1015** [comment]
ok,明天我优化一下

**Comment by richard1015** [comment]
state.file1List.push({ url: "…… .png", id: 1407, name: "41.png" })

**Comment by gyt95** [comment]
不能map只能push

**Comment by erTongWang** [comment]
回显需要以下这些字段
  imageList: res.imageList.map(item => {
                return {
                    ...item,
                    url: domain + '/files/' + item.resourceId,
                    uid: item.id,
                    type: 'image',
                    status: 'success'
                }
            })
