### ISSUE TITLE
关于picker三级联动的问题

### ISSUE THREAD

**Issue by yyccQQu** [jdf2e/nutui#69]
![image](https://user-images.githubusercontent.com/32674176/55770085-47aef080-5aad-11e9-9461-be3f54e8c446.png)
![image](https://user-images.githubusercontent.com/32674176/55770097-539ab280-5aad-11e9-9c51-fe4c19a40e22.png)
第一级有子选项就默认选中第一项是对的。
但是第二级没有子选项就会延用第一级的子选项，只是不对的，建议优化一下，谢谢

**Comment by Franslee** [comment]
收到，感谢反馈

**Comment by yyccQQu** [comment]
补充一下
nut-scroller 内部元素 nut-row等标签及其内部元素无法触发click事件

**Comment by yyccQQu** [comment]
<nut-scroller
	:is-un-more="isUnMore"
	:is-loading="isLoading"
	:type="'vertical'"
	@loadMore="loadMoreVert"
	@pulldown="pulldown"
			>
				<nut-row
					slot="list"
					v-for="(item, index) of listData"
					:key="index"
					class="nut-vert-list-panel thead tbody tableList"
					type="flex"
					justify="space-between"
					flexWrap="nowrap"
				>
					<nut-col class="md-3 cols" @click="abcccccc">
						<div class="flex-content">
							<p class="ptype">这那那这</p>
							<p class="ptype">这那那这</p>
						</div>
					</nut-col>
```
abcccccc时间无法执行

**Comment by yyccQQu** [comment]
<nut-scroller
	:is-un-more="isUnMore"
	:is-loading="isLoading"
	:type="'vertical'"
	@loadMore="loadMoreVert"
	@pulldown="pulldown"
			>
				<nut-row
					slot="list"
					v-for="(item, index) of listData"
					:key="index"
					class="nut-vert-list-panel thead tbody tableList"
					type="flex"
					justify="space-between"
					flexWrap="nowrap"
				>
					<nut-col class="md-3 cols" @click="abcccc">
						<div class="flex-content">
							<p class="ptype">这那那这</p>
							<p class="ptype">这那那这</p>
						</div>
					</nut-col>
```
abcccc事件无法触发

**Comment by irisSong** [comment]
页面demo仅供参考，只为展示提供联动功能，具体使用逻辑需要根据自己的数据结构去写里面内容
