### ISSUE TITLE
[bug]nut-popup与picker-view一起使用样式错乱了

### ISSUE THREAD

**Issue by juliannan** [jdf2e/nutui#690]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
https://github.com/juliannan/demo-taro-picker.git

## 相关环境信息
- **操作系统**：win
- **Node 版本**：12.20.0

**Comment by richard1015** [comment]
picker 正在重构中，预替换小程序原生 picker

**Comment by richard1015** [comment]
https://nutui.jd.com/#/picker-taro
