### ISSUE TITLE
Elevator组件应该支持slot这样用户可以自定义Elevator显示内容

### ISSUE THREAD

**Issue by gmars** [jdf2e/nutui#691]
## 你建议我们做什么？

Elevator组件添加相应的slot这样就可以根据需要来个性化子组件的显示，或者添加左侧icon字段的支持也可以
现在...

如果你能...

它将使...

## 其它

无

**Comment by szg2008** [comment]
感谢反馈，问题已修复，下个版本可支持

**Comment by richard1015** [comment]
3.1.9 已发布
