### ISSUE TITLE
[bug] 引入 nutui 失败

### ISSUE THREAD

**Issue by chenxin9482** [jdf2e/nutui#698]
## 问题描述

nutui全量引入运行时报错

> This dependency was not found:
 @nutui/nutui/dist/style.css in ./src/main.js
To install it, you can run: npm install --save @nutui/nutui/dist/style.css
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

https://github.com/chenxin9482/nut-bug

## 预期的行为和实际行为
预期行为：项目正常运行

## 复现步骤，具体代码
npm run serve

## 相关环境信息
- **操作系统**：Windows 10
- **Node 版本**：14.16.0
- **NutUI 版本**： @nutui/nutui@2.3.5
- **Vue 版本**：2.6.14
- **引用方式**：  npm

**Comment by richard1015** [comment]
参看一下这个

https://github.com/jdf2e/nutui-demo/tree/master/base
