### ISSUE TITLE
[bug] Taro 小程序下 CollapseItem 无法正常展开

### ISSUE THREAD

**Issue by IchenDEV** [jdf2e/nutui#707]
## 问题描述

Taro 小程序下 CollapseItem 无法正常展开，示例小程序中同样存在问题

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

组件库示例:
https://github.com/jdf2e/nutui-demo/tree/master/taro
## 预期的行为和实际行为

点击展开Collapse

## 复现步骤，具体代码
https://github.com/jdf2e/nutui-demo/blob/master/taro/src/feedback/pages/collapse/index.vue

## 相关环境信息
- **操作系统**：macOS 12.0
- **Node 版本**：v15.14.0
- **Taro 版本**：3.3.9
- **NutUI 版本**： @nutui/nutui-taro 3.1.8
- **Vue 版本**：3.2.19
- **引用方式**：  CDN / NPM ？yarn

**Comment by richard1015** [comment]
3.1.9 已发布
