### ISSUE TITLE
[suggest]建议增加一个Gird组件

### ISSUE THREAD

**Issue by strongyc** [jdf2e/nutui#709]
![image](https://user-images.githubusercontent.com/51156342/136317074-19ff8b04-e31b-417a-8338-5a615dc83758.png)
九宫格，在日常使用中频率蛮高的

**Comment by richard1015** [comment]
get

**Comment by yangjisen** [comment]
> get

有进展了么？好几个人都提了这需求，计划什么时候呢？ @richard1015

**Comment by richard1015** [comment]
https://nutui.jd.com/#/grid
