### ISSUE TITLE
建议：picker传入对象时，可以指定显示 对象的某个 key

### ISSUE THREAD

**Issue by cccnoob** [jdf2e/nutui#71]
![1213](https://user-images.githubusercontent.com/21024505/55846765-7b574c80-5b79-11e9-973d-e6b34eb62918.png)

![1336](https://user-images.githubusercontent.com/21024505/55846748-6d093080-5b79-11e9-8c35-0ef53a59b9b9.png)

指定 显示 Text 字段 
![1301](https://user-images.githubusercontent.com/21024505/55846792-8d38ef80-5b79-11e9-9057-57bf69a51661.png)

**Comment by irisSong** [comment]
感谢建议，我们会考虑的。
