### ISSUE TITLE
vue3 taro 支付宝小程序样式上出现问题[bug]

### ISSUE THREAD

**Issue by wzs28150** [jdf2e/nutui#711]
## 问题描述

我用taro的脚手架创建的项目 
![image](https://user-images.githubusercontent.com/21290257/136681006-7f03b7c2-e738-4ce2-84ae-9251f4b0078e.png)
然后
运行时
![image](https://user-images.githubusercontent.com/21290257/136681020-57366f27-9236-4d47-94c5-52d47b0ae2cf.png)
默认app.ts这里的代码编译会报错
![image](https://user-images.githubusercontent.com/21290257/136681052-09a92c25-9240-4ee1-bbc0-f03de78dcb8e.png)
改用全部组件引用
![image](https://user-images.githubusercontent.com/21290257/136681064-30a46fc8-0bed-4f08-8796-253249692394.png)
编译没有问题了但是在编译支付宝小程序的时候页面好像缺少样式的感觉，编译微信小程序 h5都正常
![image](https://user-images.githubusercontent.com/21290257/136680984-7bda0ea8-79ad-4324-ae89-00ab6e2e8818.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：win11
- **Node 版本**：v14.17.1
- **NutUI 版本**： @nutui/nutui-taro ^3.0.3 @tarojs/taro 3.3.9
- **Vue 版本**：^3.0.0
- **引用方式**：  CDN / NPM ？NPM

**Comment by richard1015** [comment]
按需加载报错 按照这个文档配置一下 
https://nutui.jd.com/#/starttaro

**Comment by kl-nevermore** [comment]
钉钉小程序也是如此,基于taro-cli创建
![image](https://user-images.githubusercontent.com/25167742/137260302-d9d15277-c0ec-43b5-b7d2-310fa7a12a87.png)

**Comment by richard1015** [comment]
目前  团队内部只测试了  微信小程序 & H5  其它平台小程序陆续测试中

**Comment by wzs28150** [comment]
> 钉钉小程序也是如此,基于taro-cli创建 ![image](https://user-images.githubusercontent.com/25167742/137260302-d9d15277-c0ec-43b5-b7d2-310fa7a12a87.png)
退回到3.0.2版本就正常了
![image](https://user-images.githubusercontent.com/21290257/137592906-1c45bcc8-2cfb-4788-9ae0-28cb3bbeccab.png)

**Comment by wzs28150** [comment]
> 目前 团队内部只测试了 微信小程序 & H5 其它平台小程序陆续测试中

![image](https://user-images.githubusercontent.com/21290257/137621815-823e1c28-607d-4e14-a3a8-a6c73caac6b9.png)
有这样有一个样式取消了就正常了

**Comment by richard1015** [comment]
@wzs28150   感谢反馈，[v3.1.10-beta.0](https://www.npmjs.com/package/@nutui/nutui-taro/v/3.1.10-beta.0)已修复，可以暂时使用这个版本进行开发
[fix: 修复小程序demo预览在其他多端平台的样式问题](https://github.com/jdf2e/nutui/commit/16790216b547a755626c058fd420fe6c45f4fe37)

**Comment by richard1015** [comment]
v3.1.10 发布
