### ISSUE TITLE
[bug]vue3 调用Tabbar 控制台报错 [Vue warn]

### ISSUE THREAD

**Issue by felix2chow** [jdf2e/nutui#712]
## 问题描述
vue3 调用Tabbar 示例代码 控制台报错
 [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead. 

## 相关环境信息
- **操作系统**：macos 10.14.6 
- **Node 版本**：v14.17.6
- **NutUI 版本**： @nutui/nutui@3.x.x 
- **Vue 版本**：@vue/cli 4.5.13
- **引用方式**：NPM

**Comment by richard1015** [comment]
v3.1.10 发布
