### ISSUE TITLE
[bug]使用taro init创建的项目启动报错

### ISSUE THREAD

**Issue by chareice** [jdf2e/nutui#713]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/1624785/136756355-b5fbf42f-9c98-4c8b-80f4-8c45a36e8b84.png">
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1624785/136756396-c821c8ce-5dff-4876-b2af-82c5a0fa99a0.png">

**Comment by MonchiLin** [comment]
安装：`babel-plugin-import`

然后给 babel.config.js 添加 plugins 部分

```typescript
module.exports = {
	presets: [
		[
			'taro',
			{
				framework: 'vue3',
				ts: true
			}
		]
	],
	plugins: [
		[
			"import",
			{
				"libraryName": "@nutui/nutui",
				"libraryDirectory": "dist/packages/_es",
				"camel2DashComponentName": false
			},
			'nutui3-vue'
		],
		[
			"import",
			{
				"libraryName": "@nutui/nutui-taro",
				"libraryDirectory": "dist/packages/_es",
				"camel2DashComponentName": false
			},
			'nutui3-taro'
		]
	]
}

```

这个糟心的开发体验，本来还想用 taro 开发，还是放弃吧

**Comment by richard1015** [comment]
按需加载引用方式，安装 babel-plugin-import  即可 https://nutui.jd.com/#/starttaro

 taro侧文档，官方文档&初始模板 早期已优化，等待PR合并中。
https://github.com/NervJS/taro-project-templates/pull/46
https://github.com/NervJS/taro/pull/10372
