### ISSUE TITLE
[bug]Vue3 Swipe左滑删除组件，无法上下滑动

### ISSUE THREAD

**Issue by gaojs920426** [jdf2e/nutui#714]
## 问题描述

Swipe左滑删除组件，在触碰到左滑删除组件位置，上下滑动，无法进行上下滑动

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
组件在左滑的时候，出现删除按钮；在上下滑动的时候，可以进行上下滑动

## 复现步骤，具体代码
![image](https://user-images.githubusercontent.com/26408430/136776820-305024fd-6173-4cb2-a396-c06d78f73bd2.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@3.1.8
- **Vue 版本**：Vue3
- **引用方式**：  CDN / NPM ？NPM

**Comment by richard1015** [comment]
3.1.9 已发布
