### ISSUE TITLE
[bug]NutUI中的Layout组件无法正常使用，编译后提示微信开发者工具提示Template `tmpl_0_div` not found.

### ISSUE THREAD

**Issue by AiHaoChen** [jdf2e/nutui#715]
## 问题描述

我在使用taro3 + vue3 + NutUI3按照官方文档的示例时使用Layout组件，发现无法正常使用。

## 复现步骤，具体代码
使用taro-cli工具创建的项目，其中index.vue文件内容如下：
![image](https://user-images.githubusercontent.com/37200516/136824780-a14df616-d9a5-4f7f-89a3-7659bd994850.png)

<template>
  <nut-row :gutter="10">
    <nut-col :span="8">
      <div class="flex-content">span:8</div>
    </nut-col>
    <nut-col :span="8">
      <div class="flex-content flex-content-light">span:8</div>
    </nut-col>
    <nut-col :span="8">
      <div class="flex-content">span:8</div>
    </nut-col>
  </nut-row>
</template>

微信开发者工具提示如下：
![image](https://user-images.githubusercontent.com/37200516/136824936-2389aea5-04e0-42d3-af7f-624bf816f5d0.png)

[WXML Runtime warning] ./base.wxml
 Template `tmpl_0_div` not found.
  203 | 
  204 | <template name="tmpl_2_container">
> 205 |   <template is="{{xs.a(2, i.nn, l)}}" data="{{i:i,cid:2,l:xs.f(l,i.nn)}}" />
      |                ^
  206 | </template>
  207 | 
  208 | <template name="tmpl_3_catch-view">

之前尝试使用按钮组件，正常编译且在微信开发者工具中显示正常。

## 相关环境信息
- **操作系统**：windows10
- **Node 版本**：v12.8.3
- **NutUI 版本**： "@nutui/nutui-taro": "^3.1.8"
- **Vue 版本**：vue3
- **引用方式**：  NPM

**Comment by richard1015** [comment]
检查一下是否采用了，按需加载方式

https://nutui.jd.com/#/starttaro

参考示例 https://github.com/jdf2e/nutui-demo/tree/master/taro

安装：`babel-plugin-import`

然后给 babel.config.js 添加 plugins 部分

```typescript
module.exports = {
	// ...
	plugins: [
		[
			"import",
			{
				"libraryName": "@nutui/nutui",
				"libraryDirectory": "dist/packages/_es",
				"camel2DashComponentName": false
			},
			'nutui3-vue'
		],
		[
			"import",
			{
				"libraryName": "@nutui/nutui-taro",
				"libraryDirectory": "dist/packages/_es",
				"camel2DashComponentName": false
			},
			'nutui3-taro'
		]
	]
}

```

**Comment by AiHaoChen** [comment]
> 检查一下是否采用了，按需加载方式
> 
> https://nutui.jd.com/#/starttaro
> 
> 参考示例 https://github.com/jdf2e/nutui-demo/tree/master/taro
> 
> 安装：`babel-plugin-import`
> 
> 然后给 babel.config.js 添加 plugins 部分
> 
> ```ts
> module.exports = {
> 	// ...
> 	plugins: [
> 		[
> 			"import",
> 			{
> 				"libraryName": "@nutui/nutui",
> 				"libraryDirectory": "dist/packages/_es",
> 				"camel2DashComponentName": false
> 			},
> 			'nutui3-vue'
> 		],
> 		[
> 			"import",
> 			{
> 				"libraryName": "@nutui/nutui-taro",
> 				"libraryDirectory": "dist/packages/_es",
> 				"camel2DashComponentName": false
> 			},
> 			'nutui3-taro'
> 		]
> 	]
> }
> ```

之前是按照示例按需引用的，后来嫌麻烦，改为全局引用了，然后卸载了babel-plugin-import，同时babel.config.js也已经注释掉相关按需引用的代码了。但是现在依然无法全局引用，这是为什么呢？
![image](https://user-images.githubusercontent.com/37200516/136887183-50917eef-a946-4448-8958-f122af5ff140.png)

![image](https://user-images.githubusercontent.com/37200516/136887143-685fadab-aecc-431e-855d-0300df9b20cb.png)
