### ISSUE TITLE
[bug]关于tabbar使用第三方icon，无法显示出图形。

### ISSUE THREAD

**Issue by AiHaoChen** [jdf2e/nutui#718]
## 问题描述
微信小程序，根据官方文档指南使用icon，引用iconfont，使用第三方icon，能在小程序中正常显示。

![image](https://user-images.githubusercontent.com/37200516/137094808-27c97455-c23b-436c-9a53-b035404ae092.png)
![image](https://user-images.githubusercontent.com/37200516/137094875-fd06f5e0-9822-44b3-b6c4-64d608b7c7a2.png)
但是在使用tabbar标签栏时出现了问题，tabbar的item支持icon中的所有图形，但是第三方iconfont中的icon确无法正常显示。

![image](https://user-images.githubusercontent.com/37200516/137095185-38745917-6cb8-4b73-8a57-aa60f253d1ce.png)

![image](https://user-images.githubusercontent.com/37200516/137095212-d09812d0-b62b-4db2-9f3a-45b01f434013.png)
请问tabbar支持第三方icon么，如果支持应该怎么编写？

## 相关环境信息
- **操作系统**：Windows10
- **NutUI 版本**： "@nutui/nutui-taro": "3.1.7"
- **Vue 版本**：Vue3
- **引用方式**：  NPM

**Comment by Drjingfubo** [comment]
tabbar-item的名称入参不是name，是icon，https://nutui.jd.com/#/tabbar
