### ISSUE TITLE
Scroller  里面的某个元素的事件无法触发

### ISSUE THREAD

**Issue by caojf622** [jdf2e/nutui#72]
![image](https://user-images.githubusercontent.com/47477984/55973468-3980f000-5cb8-11e9-99c4-f8dfa5ec0dcb.png)

在Scroller 里面的button无法触发 click事件，外面那个button 怎么无任何影响，是我使用姿势不对吗？

**Comment by irisSong** [comment]
下个版本会放开，可先引入fastclick解决

**Comment by Franslee** [comment]
新版本已支持
