### ISSUE TITLE
[bug]nutui-taro v3.1.8 不存在 tabs，tabpane组件

### ISSUE THREAD

**Issue by DingHui-Li** [jdf2e/nutui#728]
## 问题描述

"@nutui/nutui-taro"”没有导出的成员“Tabs”。你是否指的是“Tab”?

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：  "@nutui/nutui-taro": "^3.1.8",
- **引用方式**： NPM

**Comment by richard1015** [comment]
新增组件Tabs重构完成，暂时可以使用测试版 @nutui/nutui-taro@3.1.9-beta.0
测试版文档 https://jdf2e.github.io/nutui/#/tabs
v3.1.9 发布时间 10.17

**Comment by richard1015** [comment]
3.1.9 已发布

**Comment by xzy-96** [comment]
我这边是 tab 下面还有 tab 就报了
[NutUI] <Tabs> 当前未找到 TabPane 组件元素 , 请检查
(env: Windows,mp,1.06.2208010; lib: 2.17.0)
._node_modules_@nutui_nutui-taro_dist_packages__es_Tabs.js:93

**Comment by xzy-96** [comment]
我的版本是 3.2.1
