### ISSUE TITLE
[suggest]

### ISSUE THREAD

**Issue by xiaosifeng** [jdf2e/nutui#729]
## 你建议我们做什么？

现在 Price 商品价格组件的小数点是必有的

如果能
1. 小数点可以为0（也就是没有小数点后几位）
2. 可以修改单位在前还是后，参数可以自由传入比如说（元/￥/$）

**Comment by p930203110** [comment]
> ## 你建议我们做什么？
> 现在 Price 商品价格组件的小数点是必有的
> 
> 如果能
> 
> 1. 小数点可以为0（也就是没有小数点后几位）
> 2. 可以修改单位在前还是后，参数可以自由传入比如说（元/￥/$）

需求1真的需要啊。
需要2中参数现在已经可以通过symbol来传入，不过现在只能放在前面。
另外还有一个需求没人提么。。金额的font-size没办法设置。

**Comment by ailululu** [comment]
> ## 你建议我们做什么？
> 现在 Price 商品价格组件的小数点是必有的
> 
> 如果能
> 
> 1. 小数点可以为0（也就是没有小数点后几位）
> 2. 可以修改单位在前还是后，参数可以自由传入比如说（元/￥/$）

现在这个功能都实现了，还有其他的建议吗

**Comment by ailululu** [comment]
> 



> > ## 你建议我们做什么？
> > 现在 Price 商品价格组件的小数点是必有的
> > 如果能
> > 
> > 1. 小数点可以为0（也就是没有小数点后几位）
> > 2. 可以修改单位在前还是后，参数可以自由传入比如说（元/￥/$）
> 
> 需求1真的需要啊。 需要2中参数现在已经可以通过symbol来传入，不过现在只能放在前面。 另外还有一个需求没人提么。。金额的font-size没办法设置。

我们提供了3个size可以选择，具体的font-size可以通过样式覆盖来实现；其他的已经实现了，还有其他的建议吗

**Comment by szg2008** [comment]
请更新安装包试试～
