### ISSUE TITLE
[bug] swiper 无法引入使用

### ISSUE THREAD

**Issue by bruceleedrupal** [jdf2e/nutui#730]
https://github.com/jdf2e/nutui-demo/tree/master/taro/src/feedback/pages/swiper
直接测试demo就是错误的

**Comment by richard1015** [comment]
直接使用 Taro 现有 Swiper 组件开发 参考文档 https://docs.taro.zone/docs/components/viewContainer/swiper

**Comment by bruceleedrupal** [comment]
nutui好多组件出现类似无法引入情况，另外例如这个backtop　 https://nutui.jd.com/3x/demo.html#/backtop 　也一样，引入了scroll-view组件也是报错，我想要的是一个正常解决方案，而不是換个taro组件替换

**Comment by yangjisen** [comment]
> nutui好多组件出现类似无法引入情况，另外例如这个backtop　 https://nutui.jd.com/3x/demo.html#/backtop 　也一样，引入了scroll-view组件也是报错，我想要的是一个正常解决方案，而不是換个taro组件替换

楼主是怎么解决的, 我碰到了同样的问题

**Comment by zhuwei** [comment]
直接无视了？我晕，官方还推荐用这个ui
