### ISSUE TITLE
[bug]  返回顶部组件无法载入

### ISSUE THREAD

**Issue by bruceleedrupal** [jdf2e/nutui#733]
https://nutui.jd.com/3x/demo.html#/backtop
nutui好多组件出现类似无法引入情况，引入了scroll-view组件也是报错，我想要的是一个正常解决方案，而不是換个taro组件替换

**Comment by richard1015** [comment]
好多组件无法引入情况  先检查是不是 采用了按需加载的方式，没有配置 babel
https://github.com/jdf2e/nutui/discussions/727

**Comment by richard1015** [comment]
#736  同类问题
