### ISSUE TITLE
[bug]npm仓库上的@nutui/nutui-taro包组件没有分别导出，但源码build的包里组件会分别导出。是不是发布到npm仓库前没有build？

### ISSUE THREAD

**Issue by domsgit** [jdf2e/nutui#735]
## 问题描述

npm仓库上的@nutui/nutui-taro包组件没有分别导出，但源码build的包里组件会分别导出。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
预期的行为：npm仓库上的@nutui/nutui-taro包组件有分别导出，可以通过import { xxx } from '@nutui/nutui-taro'引入。
实际的行为：npm仓库上的@nutui/nutui-taro包组件没有分别导出，但源码build的包里组件会分别导出。

## 复现步骤，具体代码
@nutui/nutui-taro包版本为 3.1.9

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by richard1015** [comment]
刚刚内部测试，发现没有问题
建议检查一下你项目内部   是否配置了按需加载的方式 #727


#### WebPack 构建工具 通过 babel 使用按需加载

[babel-plugin-import](https://github.com/ant-design/babel-plugin-import) 是一款 babel 插件，它会在编译过程中将 import 语句自动转换为按需引入的方式。
##### 安装插件
``` bash
npm install babel-plugin-import --save-dev
```
在 `.babelrc` 或 `babel.config.js` 中添加配置：
``` javascript
{
  // ...
  plugins: [
    [
      "import",
      {
        "libraryName": "@nutui/nutui",
        "libraryDirectory": "dist/packages/_es",
        "camel2DashComponentName": false
      },
      'nutui3-vue'
    ],
    [
      "import",
      {
        "libraryName": "@nutui/nutui-taro",
        "libraryDirectory": "dist/packages/_es",
        "camel2DashComponentName": false
      },
      'nutui3-taro'
    ]
  ]
}
```

**Comment by richard1015** [comment]
参考 demo https://github.com/jdf2e/nutui-demo/tree/master/taro
