### ISSUE TITLE
[bug] infiniteloading无法载入使用

### ISSUE THREAD

**Issue by bruceleedrupal** [jdf2e/nutui#736]
![2021-10-18 13-36-18 的屏幕截图](https://user-images.githubusercontent.com/7478954/137674676-ba94c71b-bac4-4341-ad24-191b9cd6c6e2.png)

**Comment by richard1015** [comment]
直接使用 Taro 现有 ScrollView 组件开发 参考文档
https://docs.taro.zone/docs/components/viewContainer/scroll-view

**Comment by bruceleedrupal** [comment]
nutui已经有现成的用不了，最好是通过配置方面的调整让组件可用，而不是另外找替代组件,这nutui有好几个组件都有类似情况，这种问题应该是能解决的吧

**Comment by richard1015** [comment]
> nutui已经有现成的用不了，最好是通过配置方面的调整让组件可用，而不是另外找替代组件,这nutui有好几个组件都有类似情况，这种问题应该是能解决的吧

嗯，关于nutui 使用 taro原生组件透传这个问题在解决中

**Comment by bruceleedrupal** [comment]
> > nutui已经有现成的用不了，最好是通过配置方面的调整让组件可用，而不是另外找替代组件,这nutui有好几个组件都有类似情况，这种问题应该是能解决的吧
> 
> 嗯，关于nutui 使用 taro原生组件透传这个问题在解决中

@richard1015 希望能早点解决，不然开发很受打击。我给点自己的一点分析判断，希望对解决这问题有点作用。
nutui的组件会调用taro控件和微信小程序的原生组件，如果定义的nutui组件调用的底层组件名称存在的模糊定义那就会出错，譬如这个infiniteloading,调用了scroll-view,但是这scoll-view,即在taro原生控件中有定义，又在微信小程序原生组件中有定定义，所以infinieloading组件就不清楚该如何渲染。
我不清楚这底层该如何配置才能消除这种不确定性，我想这问题解决了，那其他组件的问题应该都能一并解决

**Comment by richard1015** [comment]
@bruceleedrupal   是的，是这个[问题](https://github.com/b2nil/taro-plugin-vue)，目前已有解决方案 开发者在处理
@szg2008

**Comment by szg2008** [comment]
v3.1.16已修复
