### ISSUE TITLE
手动引入报错

### ISSUE THREAD

**Issue by FatDong1** [jdf2e/nutui#74]
报错如下：
`export 'default' (imported as 'nutRate ') was not found in  './assets/common/rate/rate.js'`

引入方式：
```
import Vue from 'vue'
import nutRate from './assets/common/rate/rate.js'
import './assets/common/rate/rate.css'

nutRate.install(Vue)
```

我将打包后的rate.js和rate.css放入common文件夹，然后手动引入，发现报错，麻烦看一下

**Comment by Franslee** [comment]
放入common文件夹后，babel会对其进行处理。在你的webpack配置文件中，配置babel-loader，排除rate.js文件即可

**Comment by FatDong1** [comment]
@Franslee 谢谢。nice！
