### ISSUE TITLE
[question]请问微信小程序做tabbar切换页面是怎么一个思路呢？以京东购物微信小程序为例。

### ISSUE THREAD

**Issue by AiHaoChen** [jdf2e/nutui#741]
## 你想知道什么？
我想知道使用NutUi的tabbar怎么实现正常的页面切换效果的。

以京东购物微信小程序为例，每次进入京东购物的“首页”，首页的下拉栏都会重置，看起来像是redirectTo或者重新加载，或者v-if或者v-show；然后其他，比如“分类”、“附近生活圈”等其他的tabbar不会重新加载。我想知道京东购物微信小程序的tabbar切换思路，我也依此思路实现该功能。

## 描述你考虑过的替代方案
我之前以为实现该功能是tabbar+tabs实现的，但是tabs不能隐藏标签栏，貌似不对。然后我能想到的就是一个页面，使用v-if或者v-show来控制显示；另一个思路就是有多少个tabbar就有多少个页面，使用navigateTo跳转到对应的页面，每个页面下方的tabbar是多个tabbar，使用方法控制tabbar的激活样式。

我想...
请告诉我使用NutUI实现京东购物的tabbar切换效果的大致思路流程。
## 其它

感谢！

**Comment by yangjisen** [comment]
小程序有一个onshow的方法，左每次进入进行初始化选中的tabs?

**Comment by richard1015** [comment]
京东购物微信小程序 用的微信原生组件 https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/extended/weui/tabbar.html

或者自定义 tabbar 都是可以的  https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html
