### ISSUE TITLE
button添加submit类型 [suggest]

### ISSUE THREAD

**Issue by april-zhy** [jdf2e/nutui#743]
## button添加submit类型

button组件没有form-type属性，希望添加，同时添加form组件。微信小程序中，发送订阅消息需要formId，只有form中的submit类型button才能触发

## 其它

无

**Comment by Banzerczhs** [comment]
确实，别的小程序ui组件都实装了form组件，连自家的taroui都有。我看这个问题从19年就开始提出了，为何官方到现在还没有进行实装。

**Comment by richard1015** [comment]
3.1.16 已发布 ，已支持 小程序场景使用
