### ISSUE TITLE
按需加载,定制主题的颜色在dialog上不生效

### ISSUE THREAD

**Issue by haruka0** [jdf2e/nutui#75]
按需加载,定制主题的颜色在dialog上不生效，同时引入的radio生效了，但是dialog的closeBtn还是默认的颜色

**Comment by Franslee** [comment]
改了哪些变量的值？

**Comment by haruka0** [comment]
> 改了哪些变量的值？

primary-color

**Comment by linrufeng** [comment]
建议使用 按需加载方式 的配置方式

**Comment by Franslee** [comment]
dialog主按钮的颜色是渐变色，变量名 $btn-gradient-bg

全部变量参见 https://github.com/jdf2e/nutui/blob/master/src/styles/variable.scss
