### ISSUE TITLE
[bug]Tabs左右布局自定义主题样式问题。

### ISSUE THREAD

**Issue by AiHaoChen** [jdf2e/nutui#760]
## 问题描述

tabs组件使用左右布局方式，已经使用了自定义主题，却发现左右布局的tabs的标题的曲线样式没有改变。
![image](https://user-images.githubusercontent.com/37200516/138322441-838776e6-546d-4da3-a349-51048b7c4594.png)
custom_theme已经定义了。
![image](https://user-images.githubusercontent.com/37200516/138322523-c9e511c3-3ed7-47ac-99e2-f5ba7226419f.png)

最终发现原来左右布局的tabs的标题下划线是一张图片，
![image](https://user-images.githubusercontent.com/37200516/138322741-2844adc8-6c84-4558-a7d9-e4ec9d09e78f.png)
而且无法重定义该图片地址。
在主题定制的CSS配置表variables.scss中，tabs并没有定义该项的配置。
![image](https://user-images.githubusercontent.com/37200516/138323053-88fb97b6-260c-49a4-b77a-a5362e9b3f36.png)
 因此导致了，使用左右布局的tabs标题总会显示橘红色的曲线。

![image](https://user-images.githubusercontent.com/37200516/138323454-bda01345-ddbf-4382-93b4-fec0000c06d0.png)
希望在css配置表中加入vertical布局的tabs的background-image的配置variables.scss。

## 相关环境信息
taro3 + vue3 + NutUIv3.1.9

**Comment by richard1015** [comment]
本周五发版 3.1.10

**Comment by richard1015** [comment]
v3.1.10 发布
