### ISSUE TITLE
InfiniteLoading 无法使用啊，小白请求怎么用？

### ISSUE THREAD

**Issue by xiaoming0827** [jdf2e/nutui#77]
import Infiniteloading from '@nutui/nutui/dist/packages/infiniteloading/infiniteloading.js';
import '@nutui/nutui/dist/packages/infiniteloading/infiniteloading.css';
export default{
    components:{Infiniteloading},
    name:'messageList',
    data () {
        return {
            messageList:[],
            isHasMore: true,
            isLoading: true,

        }
    }

<Infiniteloading
                    @loadmore="onInfinite"
                    :is-show-mod="true"
                    :has-more="isHasMore"
                    :is-loading="isLoading"
                    :threshold="20"
            >
                <div class="message_container" v-for="item in messageList">
                    <div class="message_time">{{moment(item.createTime).format('YYYY-MM-DD HH:MM')}}</div>
                    <div class="message">
                        <p class="message_title">{{item.messageTitle}}</p>
                        <p class="message_text">{{item.messageContent}}</p>
                    </div>
                </div>
            </Infiniteloading>

这样用不对吗？为什么文档上都是nut-infiniteloading

**Comment by irisSong** [comment]
参考http://nutui.jd.com/#/InfiniteLoading页demo

**Comment by xiaoming0827** [comment]
demo写的我实在是看不懂，为什么组件名是nut-infiniteloading带nut-前缀呢，这是直接在HTML中使用的吗？在组件中好像不带吧，不带的话我按照示例引入但是无法触发加载的回调函数，可以给一个codesandbox 示例吗？实在是跑不起来 万分感谢

**Comment by richard1015** [comment]
> demo写的我实在是看不懂，为什么组件名是nut-infiniteloading带nut-前缀呢，这是直接在HTML中使用的吗？在组件中好像不带吧，不带的话我按照示例引入但是无法触发加载的回调函数，可以给一个codesandbox 示例吗？实在是跑不起来 万分感谢

https://github.com/jdf2e/nutui/blob/master/src/packages/infiniteloading/demo.vue
