### ISSUE TITLE
Elevator [bug]

### ISSUE THREAD

**Issue by julianfox0119** [jdf2e/nutui#787]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
点击index正常跳转

## 复现步骤，具体代码
浏览器报这个warning，用的就是taro vue3的脚手架创建的。目前看小程序和H5都报这个warning
![image](https://user-images.githubusercontent.com/4902327/138838025-ad47dcea-cb57-4624-9508-aa978e66ffc0.png)
![image](https://user-images.githubusercontent.com/4902327/138838278-3d75d306-cdc1-4ca5-86d4-64e27d779962.png)

Failed to resolve component: scroll-view
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <NutElevator index-list= (2) [{…}, {…}] height=260 onClickItem=fn<bound clickItem>  ... > 
  at <TaroView> 
  at <TaroView class="index" > 
  at <Index> 
  at <TaroView key=0 class="mobile" > 
  at <Index tid="/pages/index/index" > 
  at <App>

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：12.22.3
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x        ============== 3.1.6
- **Vue 版本**：3.2.14
- **引用方式**：  CDN / NPM ？NPM

**Comment by julianfox0119** [comment]
用的是ts，所以这个是需要额外配置什么么？网上搜了半天也没有个能work的solution。奇怪了。

**Comment by julianfox0119** [comment]
![image](https://user-images.githubusercontent.com/4902327/138845284-20054dcb-8ee6-4ed1-b588-f77d5b73ed02.png)

**Comment by julianfox0119** [comment]
[taro-nutui.zip](https://github.com/jdf2e/nutui/files/7416824/taro-nutui.zip)

**Comment by szg2008** [comment]
v3.1.16已修复，请升级，另外需升级Taro到3.4.x
