### ISSUE TITLE
calendar在多例情况下日期范围选择似乎有点问题

### ISSUE THREAD

**Issue by wangjun521** [jdf2e/nutui#79]
在第一个页面日历假设选择了5月的1号和2号 
在下一页面的的的日历组件去往下拉点时候不会有四月份了
 两个页面各有两个日历组件 不公用 
但当选择了其他日期的情况下是可以下拉出四月份的

**Comment by irisSong** [comment]
是否可以下拉和startDate有关系，不是很明白你说的问题。

**Comment by wangjun521** [comment]
可以给你个线上环境感受下吗? 可能描述不是很直观
 
http://test-web-xgw.shands.cn <http://test-web-xgw.shands.cn/>
测试环境可能有点卡

使用密码登录
账号: 0123456789
密码: 1234567 
首页  => 选择一个月的1号和之后的一个日期 然后在列表也查看日期的时候 往下拉是不会出现上个月份的 (假设选择了五月1号和四号  然后去列表也 打开日历的时候  往下拉是不会出现四月份的)
 麻烦了 万分感谢

**Comment by wangjun521** [comment]
发送了两个gif到您的邮箱 可能更直观一些呢  麻烦了

**Comment by wangjun521** [comment]
录了两个gif 
http://static.shands.cn/app/bug.gif
http://static.shands.cn/app/bug1.gif

**Comment by irisSong** [comment]
查看一下引入的是不是最新版本，替换最新版本测试一下

**Comment by wangjun521** [comment]
更新了 依旧不行呢 我打印了断点  在第二个页面选择了5月1号和2号情况下 往下拉
````
// getMonth 执行了prev的else   
// 此时startData以及curData都是四月份 下面的if根本不会执行
if (!this.startData || Utils.compareDate(`${this.startData[0]}-${this.startData[1]}-01`, `${curData[0]}-${curData[1]}-${curData[2]}`)) {
          this.monthsData.unshift(monthInfo)
        } else {
          this.unLoadPrev = true
        }
````

**Comment by wangjun521** [comment]
确切的说 当有1号的时候就gg了

**Comment by irisSong** [comment]
你查一下你startData值吧，只要右侧大于左侧的yyyy-mm-01就会执行

**Comment by wangjun521** [comment]
startData没有做过更改 就是默认值呢 
````
startDate: {
      type: String,
      default: Utils.getDay(0)
    }

````

**Comment by wangjun521** [comment]
当起始日期选择8月1号 7月1号或6月1号往下拉 可以一直显示到5月 从5月接着下拉就拉不出4月份  但当选择的起始日期没有1号时  从那一个月下拉都可以拉出当前月  总感觉哪个地方的判断出了问题

**Comment by irisSong** [comment]
断点位置改成这样试一下if (!this.startData || !Utils.compareDate(`${curData[0]}-${curData[1]}-${curData[2]}`, `${this.startData[0]}-${this.startData[1]}-01`)) {

**Comment by wangjun521** [comment]
不行的  初始化日历后直接往下拉 curData是undefined 直接报错啦

**Comment by wangjun521** [comment]
往下拉的时候其中报了
````
Cannot read property 'replace' of undefined
````
我打印下看看是哪里错了

**Comment by wangjun521** [comment]
curData 在日历初始化结束后下拉会是undefined 导致报错

**Comment by wangjun521** [comment]
刚单独拉代码做个demo来手动赋值 range的 defaultValue 只要defaultValue[0]选择的有1号 就无法拉出startDate的那个月 您也可以试试  麻烦了

**Comment by irisSong** [comment]
168行 改成这样，我们这边没有初始化下拉undefined问题，请排查一下代码if (!this.startData || !Utils.compareDate(${curData[0]}-${curData[1]}-${curData[2]}, ${this.startData[0]}-${this.startData[1]}-01)) {

**Comment by wangjun521** [comment]
在168行改为您说的那样后 没出现undefined的错误(可能我昨晚哪里出了问题吧) 
您可以试试做这样一个demo
````
// template
<nut-calendar
   :is-visible="showflag"
   :default-value="date"
   type="range"
   :start-date="`2019-04-29`"
   :end-date="`2019-08-31`"
 >
</nut-calendar>

// data
date: ['2019-06-01', '2019-06-03']
````
在这种情况下下拉是可以拉出5月份  但再往下拉四月份就没了 但我的开始日期可是04-29
如果我把date改成`['2019-06-02', '2019-06-03'] `这样往下拉是可以拉出四月份的

**Comment by irisSong** [comment]
改了168行之后，按上面配置demo。是正常的，请仔细检查一下代码。

**Comment by wangjun521** [comment]
嗯嗯 我又仔细检查了一遍 可以了 实在麻烦您了 万分感谢!
