### ISSUE TITLE
[bug]最新发布的 @nutui/nutui-taro 3.1.9里面没有包含 Searchbar组件，但官方文档里却有介绍

### ISSUE THREAD

**Issue by cosmozhu** [jdf2e/nutui#794]
## 问题描述

最新发布的 @nutui/nutui-taro 3.1.9里面没有包含 Searchbar组件，但官方文档里却有介绍
![image](https://user-images.githubusercontent.com/5482940/139024120-fc2ef551-facd-4111-8ca9-74a378527f5c.png)

![image](https://user-images.githubusercontent.com/5482940/139023865-5ec1815c-dd10-4e49-97c1-8009ae05906b.png)

## 相关环境信息
- **NutUI 版本**： @nutui/nutui-taro 3.1.9
- **Vue 版本**：3.2.20
- **引用方式**：  NPM

**Comment by richard1015** [comment]
抱歉，昨天官网更新来着，该组件 会在下个版本  v3.1.10中体现

**Comment by cosmozhu** [comment]
预计v3.1.10什么时间发布

**Comment by richard1015** [comment]
> 预计v3.1.10什么时间发布

本周五
