### ISSUE TITLE
组件库的设计资源sketch有提供下载的计划吗？

### ISSUE THREAD

**Issue by odysseus9451** [jdf2e/nutui#797]
公司想用nutui，但是并没有sketch文件下载，figma的也可以，麻烦问下有在计划中吗

**Comment by richard1015** [comment]
下周官网 资源入口会展示 sketch

**Comment by odysseus9451** [comment]
> 下周官网 资源入口会展示 sketch

好的谢谢

**Comment by richard1015** [comment]
https://nutui.jd.com/#/resource

**Comment by wenbei421** [comment]
> https://nutui.jd.com/#/resource

![image](https://github.com/jdf2e/nutui/assets/6428597/ae3c0240-a9dc-4be9-b0f8-48a72765846e)
设计资源有没有更新计划，现在组件库到4.0了，设计资源文件还是V3版本

**Comment by eiinu** [comment]
> > [nutui.jd.com/#/resource](https://nutui.jd.com/#/resource)
> 
> 设计资源有没有更新计划，现在组件库到4.0了，设计资源文件还是V3版本

短期内没有更新计划
