### ISSUE TITLE
cell组件有click事件吗

### ISSUE THREAD

**Issue by Moonofweisheng** [jdf2e/nutui#81]
想用cell+datetimepicker做时间选择的功能，但是给cell加click事件不生效，下面是代码：

<nut-cell @click="datePickerShow()" :isLink="true" :showIcon="true" desc="请选择日期"></nut-cell>
    <nut-datepicker
      :is-visible="dateShow"
      type="date"
      title="请选择日期"
      defaultValue="1980-06-01"
      startDate="1900-01-01"
      endDate="2019-10-05"
      :is-show-chinese="false"
      @close="switchPicker()"
      @choose="setChooseValue"
    ></nut-datepicker>

**Comment by Franslee** [comment]
可使用原生click事件  @click.native
