### ISSUE TITLE
[bug]DatePicker for Taro

### ISSUE THREAD

**Issue by julianfox0119** [jdf2e/nutui#811]
## 问题描述

![grafik](https://user-images.githubusercontent.com/4902327/140013115-dd0cd7ac-2b0d-4f37-b55c-542dd3a989b8.png)
DatePicker 报warning 渲染不出来，按照官网的例子写的。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
[taro-nutui.zip](https://github.com/jdf2e/nutui/files/7465496/taro-nutui.zip)

## 相关环境信息

    操作系统：win10
    Node 版本：12.22.3
    NutUI 版本： @nutui/nutui@2.x.x or @nutui/nutui-jdl@1.x.x ============== 3.1.6
    Vue 版本：3.2.14
    引用方式： CDN / NPM ？NPM

**Comment by richard1015** [comment]
taro 环境下 使用 https://docs.taro.zone/docs/components/forms/picker
