### ISSUE TITLE
[suggest]Cell组件支持subTitle的插槽

### ISSUE THREAD

**Issue by 297cwrun** [jdf2e/nutui#814]
## 你建议我们做什么？

现在`<nut-cell/>`里的sub-title只能使用字符串，但在比如vant之类的库里，这类组件都支持使用插槽自定义此块内容。现在比如想在sub-title处放一个评分显示也会做起来相当麻烦

## 其它

无

**Comment by richard1015** [comment]
v3.1.10 发布
