### ISSUE TITLE
[bug]在Infiniteloading中使用swipe，ios手机无法在swipe区域对列表进行上下滑动

### ISSUE THREAD

**Issue by jaelam0214** [jdf2e/nutui#818]
## 问题描述
在Infiniteloading中使用swipe，ios手机无法在swipe区域对列表进行上下滑动，只能在swipe间隔处对列表进行上下滑动。安卓手机都能正常交互。

## 预期的行为和实际行为
在Infiniteloading中使用swipe，ios手机能在Infiniteloading内（包含子组件swipe）区域对列表进行正常上下滑动。

## 复现步骤，具体代码
```
<nut-infiniteloading
      v-show="activeTab === 0"
      :use-window="false"
      :is-open-refresh="true"
      :has-more="pageConfig.hasMore"
      @load-more="loadMore"
      @refresh="pullRefresh"
    >
      <nut-swipe
        v-for="(task, taskIndex) in dataList"
        :key="taskIndex"
      >
     </nut-swipe>
</nut-infiniteloading>
```

## 相关环境信息
- **操作系统**：ios
- **Node 版本**：14.x.x
- **NutUI 版本**： @nutui/nutui@3.x.x 
- **Vue 版本**：3.2.x
- **引用方式**：  NPM

**Comment by richard1015** [comment]
升级nutui 到最新版本试一下，
新增参数与
touch-move-prevent-default
touch-move-stop-propagation
