### ISSUE TITLE
小程序图片上传数量限制问题

### ISSUE THREAD

**Issue by AsherSun** [jdf2e/nutui#823]
https://github.com/jdf2e/nutui/blob/adbc026be4ad0baf7dfceaf5e091baf92ce9c49f/src/packages/__VUE/uploader/index.taro.vue#L103-L111

根据文档上描述，数量限制字段是`maximum `，但是上面的代码中使用了`maximize`字段。希望修改下。

我这边提了`PR`之后，好像有提示不能合并到`next`分支，所以自己就关闭了这个`PR`。 https://github.com/jdf2e/nutui/pull/822

**Comment by richard1015** [comment]
可以合并啊，辛苦重新打开一下PR 我合并一下

**Comment by AsherSun** [comment]
好的，已经重新打开了

**Comment by richard1015** [comment]
v3.1.11
