### ISSUE TITLE
[question]ts类型都是空的？

### ISSUE THREAD

**Issue by benny-eu** [jdf2e/nutui#825]
## 你想知道什么？
为什么类型都是空的？
![image](https://user-images.githubusercontent.com/27949351/140875278-0da7774a-ee47-476e-8a0d-caa944b9f95d.png)

## 其它
目前在使用`Volar`，`SFC`没有`props`类型提示。

**Comment by tolking** [comment]
希望优化类型提供更好的代码提示

**Comment by agileago** [comment]
类型定义这么偷懒么？我用tsx写，怎么什么提示都没有，不仅没提示还报错

![image](https://user-images.githubusercontent.com/11799110/147381426-5aab0558-54ce-42c5-95b5-0e602ffcc484.png)
@richard1015

**Comment by agileago** [comment]
https://github.com/haoziqaq/varlet/tree/dev/packages/varlet-ui/types
看看这个怎么做类型的
