### ISSUE TITLE
[bug] 2.x nut-textinput通过代码清空value值，clear-btn不消失

### ISSUE THREAD

**Issue by Zfeiyang** [jdf2e/nutui#826]
## 问题描述
nutui版本 2.3.6，nut-textinput文本框组件，clear-btn属性为true，也就是有清空按钮。
通过代码清空input的值，清空按钮还在。

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
value值置空时，清空按钮消失

## 复现步骤，具体代码
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.3.6/dist/nutui.css">

<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

<script src="https://cdn.jsdelivr.net/npm/@nutui/nutui@2.3.6/dist/nutui.js"></script>
<style>
  .nut-textinput {
    width: 300px;
  }
</style>

<body>
  <div id="app">
    <button @click="emptyHandle">清空</button>

    <nut-textinput v-model="message" label="有清空按钮：" placeholder="请输入内容" :clearBtn="true" :disabled="false" />
    
  </div>
  <script>
    var app = new Vue({
      el: '#app',
      data: {
        message: 'Hello Vue.js!'
      },
      methods: {
        emptyHandle: function () {
          this.message = null;
        }
      }
    })

  </script>
</body>

</html>

## 相关环境信息
- **操作系统**：win 7
- **Node 版本**：12.12.0
- **NutUI 版本**： @nutui/nutui@2.x.x
- **Vue 版本**：2.x
- **引用方式**：  CDN & NPM ？

**Comment by richard1015** [comment]
this.message = '';

这样试试呢

**Comment by Zfeiyang** [comment]
感谢你的回复，结果是相同的，清除按钮依然存在。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jdf2e/nutui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jdf2e/nutui] [bug] 2.x nut-textinput通过代码清空value值，clear-btn不消失 (Issue #826)





 
this.message = '';
 
这样试试呢
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by richard1015** [comment]
v2.3.10已修复
