### ISSUE TITLE
[bug] 微信小程序按需引入Picker组件报错

### ISSUE THREAD

**Issue by koiomi** [jdf2e/nutui#828]
## 问题描述
Hi，我使用Taro脚手架按照官网搭建了脚手架，在微信小程序中开发。
其中Button和Cell组件按需引入正常，但是Picker组件按需引入却报错了.。

![image](https://user-images.githubusercontent.com/30486677/140951490-b44259d6-ecd4-4676-8eb5-637744315fc4.png)

## 预期的行为和实际行为
预期：按需引入正常
实际：Button和Cell组件按需引入正常，但是Picker组件按需引入却报错了
## 复现步骤，具体代码
1.Taro脚手架 初始化项目，按需引入Picker组件

![image](https://user-images.githubusercontent.com/30486677/140951242-444c78ee-c5f9-40fd-989d-57e682002bce.png)

2.控制台报错
![image](https://user-images.githubusercontent.com/30486677/140951024-1a381107-923d-49f1-870a-eddb432d9bcf.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by AsherSun** [comment]
小程序开发，`nutui`文档中建议直接使用`Taro`提供的`Picker`组件开发。详细文档如下：https://github.com/jdf2e/nutui/blob/next/src/packages/__VUE/picker/doc.taro.md

**Comment by lehug** [comment]
那这个picker目前只适合h5？ taro的不支持中间自定义标题呢

**Comment by richard1015** [comment]
3.1.16 已发布 ，已支持 小程序场景使用
