### ISSUE TITLE
[bug]signature组件在“微信小程序”中点确认后保存的图片无法打开查看签名图片

### ISSUE THREAD

**Issue by muitang** [jdf2e/nutui#829]
## 问题描述

signature组件在“微信小程序”中点确认后保存的图片无法打开查看签名图片。
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
src/packages/__VUE/signature/index.taro.vue

原代码：
 const onSave = () => {
      if (!state.canvas) {
        return;
      }
      Taro.canvasToTempFilePath({
        canvas: state.canvas,
        fileType: props.type
      })
        .then((res) => {
          emit('confirm', res.tempFilePath);
        })
        .catch((e) => {
          emit('confirm', e);
        });
    };
修改为：
      const onSave = () => {
        if (!state.canvas) {
          return;
        }
        Taro.createSelectorQuery()
          .select("#spcanvas")
          .fields({
            node: true,
            size: true
          })
          .exec(async (res) => {
            Taro.canvasToTempFilePath({
                canvas: res[0].node,
                fileType: props.type
              })
              .then((res) => {
                emit('confirm', res.tempFilePath);
              })
              .catch((e) => {
                emit('confirm', e);
              });
          });
      };
能正常打开保存的图片
## 复现步骤，具体代码
签名完成后点确认返回的图片路径无法正常打开显示签名内容。

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：
- **NutUI 版本**：@nutui/nutui-taro 3.1.10
- **Vue 版本**：3.0
- **引用方式**： NPM

**Comment by richard1015** [comment]
@muitang   可以提一个PR 我们合并一下 ，下个版本发布
