### ISSUE TITLE
picker和slider在pc端chrome浏览器中选择有问题

### ISSUE THREAD

**Issue by gdyxml2000** [jdf2e/nutui#83]
picker和slider在pc端chrome浏览器中选择有问题
picker弹出框中的子选项不能上下滑动
slider鼠标不能拖动
求解决，这样pc和移动端我只需要开发一套。

**Comment by irisSong** [comment]
部分组件不支持pc端使用

**Comment by RogerWenXin** [comment]
为什么demo中都可以使用，请提供下workaround

**Comment by yoyo837** [comment]
移动端事件体系不同
