### ISSUE TITLE
[bug] 组件库样式文件中出现 * 选择器，小程序不支持，运行报错

### ISSUE THREAD

**Issue by no5no6** [jdf2e/nutui#831]
问题描述
您好，查了之前的 issue 里也提到类似问题 #773 ，我尝试了之前 issue 中提到的解决办法，安装、并在 config/index.js 文件中配置 plugins: ['@tarojs/plugin-html'] 。也不能解决问题。

错误信息
![image](https://user-images.githubusercontent.com/5174886/141279706-3720e38b-66b4-440e-887f-1ef51754272d.png)

尝试了几个版本：
3.1.10 和 3.1.9 都报错。
3.1.8 和3.1.7 不报错

**Comment by no5no6** [comment]
> 问题描述 您好，查了之前的 issue 里也提到类似问题，我尝试了之前 issue 中提到的解决办法，安装、并在 config/index.js 文件中配置 plugins: ['@tarojs/plugin-html'] 。也不能解决问题。
> 
> 错误信息 ![image](https://user-images.githubusercontent.com/5174886/141279706-3720e38b-66b4-440e-887f-1ef51754272d.png)
> 
> 尝试了几个版本： 3.1.10 和 3.1.9 都报错。 3.1.8 和3.1.7 不报错

#773

**Comment by richard1015** [comment]
v3.1.11
