### ISSUE TITLE
[bug] Taro版 Radio组件 label props只定义了String类型导致警告 

### ISSUE THREAD

**Issue by kuonji-arisu** [jdf2e/nutui#833]
## 问题描述
Taro版 Radio组件, 文档注明了label props支持Number, String喝Boolean类型

但查看源码后, 发现该Props的type只定义了String类型, 在使用诸如 :label="0"的写法时, 会导致类型检查警告, 但并不影响使用

版本: 3.1.10

**Comment by richard1015** [comment]
该问题本周已修复，下周一发版即可  74afe5c29bd437071abdb1c7d6ddb791c347e731

**Comment by richard1015** [comment]
v3.1.11
