### ISSUE TITLE
[question] Icon 组件显示不出来，所有用到Icon的地方都空白

### ISSUE THREAD

**Issue by liuweiyibai** [jdf2e/nutui#835]
taro + vue3开发，组件按需加载，在使用Icon组件和button带icon的组件是，icon显示不出来，是我还需要安装其他依赖，还是需要指定 taro相关依赖版本

```json
	"dependencies": {
		"@babel/runtime": "^7.7.7",
		"@nutui/nutui-taro": "^3.1.10",
		"@tarojs/components": "3.3.14",
		"@tarojs/plugin-html": "3.3.9",
		"@tarojs/runtime": "3.3.14",
		"@tarojs/taro": "3.3.14",
		"lodash-es": "^4.17.21",
		"vue": "^3.0.0",
		"vue-router": "^4.0.11",
		"vuex": "^4.0.2"
	},
```

**Comment by richard1015** [comment]
import { Button,Icon } from '@nutui/nutui-taro';

**Comment by richard1015** [comment]
使用的是推荐模板吗？https://nutui.jd.com/#/starttaro
重新按照问题生成一个项目试试呢

**Comment by liuweiyibai** [comment]
刚刚新初始化的项目，windows系统

![image](https://user-images.githubusercontent.com/21965057/141880261-ab3b7d27-9752-4ab1-9c95-3c53834f7dff.png)

我的 app.ts
````ts
import { createApp } from 'vue';
import { Button, Toast, Icon } from '@nutui/nutui-taro';
import '@nutui/nutui-taro/dist/style.css';

import './app.scss';

const App = createApp({
  onShow(options) {},
  // 入口组件不需要实现 render 方法，即使实现了也会被 taro 所覆盖
});

App.use(Icon)
  .use(Toast)
  .use(Button);

export default App;
```

**Comment by richard1015** [comment]
检查一下这个插件是否安装     plugins: ['@tarojs/plugin-html'],

https://github.com/NervJS/taro/discussions/9029

**Comment by liuweiyibai** [comment]
插件安装了，会不会是这个插件版本的问题呢

**Comment by iceDays** [comment]
有没有安装DevTools ?

**Comment by xiaodiqaq** [comment]
有解决吗，遇到了同样的问题
` "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@nutui/nutui-taro": "^3.1.8",
    "@tarojs/components": "3.3.14",
    "@tarojs/plugin-html": "3.3.13",
    "@tarojs/runtime": "3.3.14",
    "@tarojs/taro": "3.3.14",
    "vue": "^3.0.0",
    "vuex": "^4.0.2"
  },`

**Comment by xiaodiqaq** [comment]
有解决吗，遇到了同样的问题

**Comment by tolking** [comment]
@tarojs/plugin-html 的版本应该与其它 `@tarojs/*` 版本保持一致

**Comment by CNMathon** [comment]
遇到相同问题，但存在于`@nutui/nutui`

```ts
import { Icon } from '@nutui/nutui';
```

**Comment by ww85600** [comment]
有解决吗？ 我这里遇到相同问题
