### ISSUE TITLE
[question]figma设计资源或sketch资源2.0版本？

### ISSUE THREAD

**Issue by odysseus9451** [jdf2e/nutui#845]
现有的sketch文件元素编组个人风格太强了，如图
![image](https://user-images.githubusercontent.com/12756682/142964322-6ea28289-4d81-4991-8dd6-3c242574a722.png)
而且为二倍图，字体也是内部字体京东正黑体。
导入到figma里之后使用起来很不方便，所以麻烦问一下figma设计资源或sketch资源2.0版本在日程上吗？

**Comment by ninidesign** [comment]
嗨 同学您好，感谢您提出的问题，为了能满足部分同学对源文件的需求，由于时间仓促先上了一版，对于分组和命名以及symbol都没有一个很好的组织这一点，先向您道歉，NutUI团队是一个开源项目，每个成员都是利用自己的业余时间甚至是自己的周末时间来优化迭代，对于规范上的瑕疵我们会下架整理，请您耐心等待；对于二倍图的问题，公司内部服务的设计团队常用规范是二倍图，我们也没有资源照顾到不同使用习惯的同学，希望您见谅，我们会持续对源文件规范来做更多版本的设计开发~谢谢~
