### ISSUE TITLE
[bug] TextArea组件的rows属性不生效并且TextArea在控制台中减小width后，文本框中文字不能自动换行

### ISSUE THREAD

**Issue by liuhp** [jdf2e/nutui#847]
## 问题描述
1. TextArea组件的rows属性不生效；
2. TextArea组件在控制台中设置宽度后，文本框中的内容不能自动换行，导致里面的文本展示不全（原生textarea也存在此问题）；
控制台修改前图片如下：

![image](https://user-images.githubusercontent.com/30249361/143032958-0d6f1ba0-e13a-4ca0-b605-586e6ad11b58.png)

控制台修改width后：
![image](https://user-images.githubusercontent.com/30249361/143033377-0ea2e385-bffe-4aad-a7e1-65eb20d7221e.png)

## 最小可复现仓库
1. 问题描述1复现（官网例子）：
```javascript
<nut-textarea v-model="value" rows="10" autosize />
```
2. 问题描述2复现：
```javascript
<template>
  <nut-textarea
    class="text-content"
    model-value="textarea很长哈创建错误报告以帮助我们改进。在提问之前可以看下是否为类似的问题 https://github.com/jdf2e/nutui/discussions/categories/q-a If this doesn’t look right, choose a different type."
  />
</template>
<style>
.text-content {
  width: 200px;
}
</style>
```
## 复现步骤，具体代码
1). 问题1直接运行官网例子就可以复现；
2). 问题2复现步骤：
小程序中：
1.在工程中引入上述代码并运行；
2. 打开控制台，减小类名为“text-content”的width，会发现里面的文字有部分被遮挡了；

## 相关环境信息
- **操作系统**：macos
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@3.x.x
- **Vue 版本**：3.x
- **引用方式**：  NPM

**Comment by Ymm0008** [comment]
感谢你的问题反馈。 @liuhp 
1、问题1 ，rows 目前只支持 H5，将来会在文档标注。
2、问题2，目前也只支持H5。
如果特许此功能，可辛苦先尝试wx原生标签试试。
后期会针对以上2个问题进行分析优化，感谢。
