### ISSUE TITLE
[bug]nut-uploader 报错

### ISSUE THREAD

**Issue by Cat-czh** [jdf2e/nutui#853]
v3.1.11
nut-uploader 报错： 全局错误处理 TypeError: Cannot read property 'includes' of undefined
小程序上传后的type是undefined
![image](https://user-images.githubusercontent.com/71885928/143518438-9672f05c-0cb9-4502-b920-6d280d6d9bf3.png)
![image](https://user-images.githubusercontent.com/71885928/143518472-f38a377e-3c53-4c6d-bab4-a70516248eb7.png)

**Comment by AsherSun** [comment]
这个问题已经提交PR了，等待下一个版本发布就可以了
[fix(uploader): 修复小程序端传图后报错问题](https://github.com/jdf2e/nutui/pull/836)

**Comment by cuijianjun** [comment]
@Cat-czh  怎么联系呢 关于upload组件 有个问题想请教一下

**Comment by cuijianjun** [comment]
@Cat-czh
