### ISSUE TITLE
[suggest]请求增加自定义tabbar

### ISSUE THREAD

**Issue by Yaonie-Jie** [jdf2e/nutui#865]
请求增加自定义tabbar,使用场景比较多的
![image](https://user-images.githubusercontent.com/24479437/143822725-36def93d-7e9d-4030-b86b-974f0c0d8c49.png)

**Comment by yekai9527** [comment]
各位大宝贝 这个是基本功能 要怎么做

**Comment by yekai9527** [comment]
用的是taro 需要taro下的自定义tabbar 先行谢过jingfubo了

**Comment by Drjingfubo** [comment]
自定义的直接在nut-tabbar里边写就可以 和item同级
