### ISSUE TITLE
[bug]nutui-taro ImagePreview组件无法加载

### ISSUE THREAD

**Issue by Itswag** [jdf2e/nutui#866]
## 问题描述

缺少ImagePreview模块
Module not found: Can't resolve '@nutui/nutui-taro/dist/packages/_es/ImagePreview' in 'C:\Users\sr\what-to-eat\src'
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
无

## 复现步骤，具体代码
无

## 相关环境信息
- **操作系统**：win11
- **Node 版本**：14.15.1
- **NutUI 版本**： @nutui/nutui-taro: @3.3.12
- **Vue 版本**：3
- **引用方式**：  NPM 
- **Taro cli版本**：  3.3.15

**Comment by richard1015** [comment]
Imagepreview 目前只有3x vue 存在
 Taro场景下，请直接调用原生API
https://docs.taro.zone/docs/apis/media/image/previewImage
