### ISSUE TITLE
是否可以加入Grid 宫格组件

### ISSUE THREAD

**Issue by lihn520** [jdf2e/nutui#869]

**Comment by yangjisen** [comment]
看到这个需求我都帮顶

**Comment by lihn520** [comment]
> 看到这个需求我都帮顶

具大佬透露，v3.1.13版本会有

**Comment by lihn520** [comment]
> 看到这个需求我都帮顶

据群大佬透露，v3.1.13版本会有

**Comment by yangjisen** [comment]
> > 看到这个需求我都帮顶
> 
> 
> 
> 据群大佬透露，v3.1.13版本会有

别骗我啊，我都没看到有pr
