### ISSUE TITLE
countdown组件相关

### ISSUE THREAD

**Issue by YouziXR** [jdf2e/nutui#87]
我单独引入了countdown组件，想要监测倒计时到点的状态，就是倒计时结束的状态，请问有什么好的方法吗？

~~另外我把源码中的`countdown.vue`文件单独down下来作为组件，在另一个vue中引入为啥不行啊，一直提示我没有注册组件这个错误，我确实在`components`里注册了。~~  已解决

**Comment by famanoder** [comment]
感谢反馈，该组件已添加`on-end`事件来检测倒计时结束的状态，请关注后续版本的更新；:smile:

**Comment by YouziXR** [comment]
> 感谢反馈，该组件已添加`on-end`事件来检测倒计时结束的状态，请关注后续版本的更新；😄

👍
