### ISSUE TITLE
Infiniteloading 滚动加载

### ISSUE THREAD

**Issue by aehyok** [jdf2e/nutui#870]
## 滚动加载控件Infiniteloading 
@nutui/nutui-taro版本为3.1.12中

看https://nutui.jd.com/#/infiniteloading 官方文档中目前引用只有
  import { InfiniteLoading } from '@nutui/nutui';

不包括
 import { InfiniteLoading } from '@nutui/nutui-taro';

但是看官网微信小程序二维码中是有这么组件的

## 区别是什么
@nutui/nutui@next 基于Vue3 视觉风格 JD APP 10.0规范 ，只能开发 h5
@nutui/nutui-taro 基于Vue3 视觉风格 JD APP 10.0规范 ，必须基于 taro + vue3 框架 进行开发多端（多端指一套代码 部署多端环境 微信小程序 h5、等第三方小程序）

这两个组件库最终的区别有多少？

**Comment by richard1015** [comment]
3.1.16 已发布 ，已支持 小程序场景使用
