### ISSUE TITLE
picker选择器一些手机上出现了不兼容的样式错乱问题~

### ISSUE THREAD

**Issue by yyccQQu** [jdf2e/nutui#88]
![image](https://user-images.githubusercontent.com/32674176/57053824-b05b4880-6cba-11e9-9a73-43461b1a119d.png)
![image](https://user-images.githubusercontent.com/32674176/57053829-c832cc80-6cba-11e9-98fa-be4860660b93.png)

**Comment by Franslee** [comment]
浏览器里模拟的Nokia N9?

**Comment by yyccQQu** [comment]
> 浏览器里模拟的Nokia N9?

对滴，老哥

**Comment by richard1015** [comment]
请升级最新版本，进行测试
