### ISSUE TITLE
[bug]折叠面板内容动态加载无法自动撑开高度

### ISSUE THREAD

**Issue by wangfpp** [jdf2e/nutui#881]
## 问题描述
```js
<nut-collapse-item :title="title2" :name="2">
    {{content}}
  </nut-collapse-item>
```
折叠面板内容动态加载无法自动撑开高度

## 预期的行为和实际行为
动态界面内容可以支持动态高度

## 相关环境信息
- **操作系统**：
- windows10 
- **Node 版本**：
- V14.6
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@3.1.12
- **Vue 版本**：3.2.22
- **引用方式**：  NPM

**Comment by yanbowe** [comment]
这个高度确实计算的有问题啊，异步加载数据的时候，默认激活状态的面板高度始终为0

**Comment by yanbowe** [comment]
![image](https://user-images.githubusercontent.com/43030980/145344528-5b75d3b0-e876-4632-833a-2aaa5cb01b34.png)
原因就是初始化的时候并没有执行方法，造成高度为0

**Comment by wangfpp** [comment]
我们是点击节点展开的时候需要Request获取数据来填充内容区的 此时高度无法预知
我的们解决方法是获取数据后设置节点的`height: auto`
```js
let index = current_expanded__index;
let list = document.getElementsByClassName('item-expanded');
  for (var i = 0; i < list.length; i++) {
   if (i === index) {
        list[i].nextSibling.style['height'] = 'auto';
        break;
   }
  }
```

**Comment by yanbowe** [comment]
![image](https://user-images.githubusercontent.com/43030980/145356077-1662c4fd-d86e-4091-a13e-91e1c49da280.png)
我是直接class覆盖了，但是动画消失了

**Comment by wangfpp** [comment]
> ![image](https://user-images.githubusercontent.com/43030980/145356077-1662c4fd-d86e-4091-a13e-91e1c49da280.png) 我是直接class覆盖了，但是动画消失了

不行吧 我看有的样式是写在`style`上的外联样式`!important`也不行呀

**Comment by yanbowe** [comment]
> > ![image](https://user-images.githubusercontent.com/43030980/145356077-1662c4fd-d86e-4091-a13e-91e1c49da280.png) 我是直接class覆盖了，但是动画消失了
> 
> 不行吧 我看有的样式是写在`style`上的外联样式`!important`也不行呀

![image](https://user-images.githubusercontent.com/43030980/145365225-fb72516b-5337-465e-afcd-8504b883c421.png)


> > ![image](https://user-images.githubusercontent.com/43030980/145356077-1662c4fd-d86e-4091-a13e-91e1c49da280.png) 我是直接class覆盖了，但是动画消失了
> 
> 不行吧 我看有的样式是写在`style`上的外联样式`!important`也不行呀

![image](https://user-images.githubusercontent.com/43030980/145365226-fcaa89c7-1c10-41bd-94ca-faf24ed16e48.png)
可以的

**Comment by Ymm0008** [comment]
感谢您的反馈，问题已修复，将在下个版本发布。 @wangfpp @yanbowe

**Comment by wangfpp** [comment]
@Ymm0008 感谢  能贴出来修复的commit吗 我们学习下

**Comment by Ymm0008** [comment]
主要增加一个监听方法
```javaScript
watch(
  () => ctx?.slots?.default?.(),
  (vnodes: VNode[]) => {
    setTimeout(() => {
      // 获取高度的方法
    }, 300);
  }
);
```
如果有更好的解决方案，可以发出来一起讨论 @wangfpp 感谢~
