### ISSUE TITLE
[bug] 微信小程序 SearchBar 组件 @search 事件无效

### ISSUE THREAD

**Issue by xjqxz2** [jdf2e/nutui#883]
## 问题描述
当我根据文档尝试使用 <nut-searchbar @search="search">组件时，发现微信小程序不会响应事件

**Comment by 297cwrun** [comment]
你不说我还没发现..

**Comment by emorywang** [comment]
`@search`我也试过是无效的，但是官方文档中的demo是可用的，后来发现改成`@submit`可以触发，怀疑文档中的demo是vue版而不是taro
