### ISSUE TITLE
[suggest] 是否可以在各类弹出层支持微信的page-container组件？

### ISSUE THREAD

**Issue by angeltxwh** [jdf2e/nutui#886]
## 你建议我们做什么？
对各类支持弹出的组件加入page-container嵌套选项，提供一个参数使用户可选是否需要套入微信原生page-container组件

现在...
比如picker/actionsheet/Popup等组件在关闭时必须点击遮罩层或者关闭按钮来关闭

如果你能...
支持page-container组件的话

它将使...
用户在触发返回操作时关闭弹出层而不是返回上一级页面

## 其它

无

**Comment by szg2008** [comment]
https://docs.taro.zone/en/docs/components/viewContainer/page-container 这个目前受限于Taro支持度，暂时无法支持
