### ISSUE TITLE
[bug] collapse v-model的值更新有问题

### ISSUE THREAD

**Issue by jingyuhao1995** [jdf2e/nutui#887]
### **【手风琴模式】**
展开再折叠不能清空v-model的值，还是上次展开的值
### **【非手风琴模式】**
v-model绑定的数组在展开折叠的时候不能双向绑定

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为
**### 和我想象中的v-model不一致，折叠展开都应该改变绑定的值，给绑定的值赋值也应该展开对应面板**

给你们投票了，把组件好好做做，加油

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by Ymm0008** [comment]
@jingyuhao1995  感谢您的反馈，能提供一下复现仓库吗？

**Comment by jingyuhao1995** [comment]
> @jingyuhao1995 感谢您的反馈，能提供一下复现仓库吗？

操作系统：
windows10
Node 版本：
V14.6
NutUI 版本： @nutui/nutui@2.x.x or @nutui/nutui-jdl@3.1.12
Vue 版本：3.2.22
引用方式： NPM

**Comment by szg2008** [comment]
> > @jingyuhao1995 感谢您的反馈，能提供一下复现仓库吗？
> 
> 操作系统： windows10 Node 版本： V14.6 NutUI 版本： @nutui/nutui@2.x.x or @nutui/nutui-jdl@3.1.12 Vue 版本：3.2.22 引用方式： NPM

您好，看您的使用版本，vue3.x对应应该使用nutui3.x，您这里使用的是2.x，请确认一下使用的版本，方便的时候提供一下最小复现仓库，我们好帮助您排查问题，感谢

**Comment by Ymm0008** [comment]
感谢您的反馈，初步定位您使用的是 V2 版本，问题已经修复，将在下个版本发布。  @jingyuhao1995

**Comment by jingyuhao1995** [comment]
> 感谢您的反馈，初步定位您使用的是 V2 版本，问题已经修复，将在下个版本发布。 @jingyuhao1995

我可能没表达明白，就是折叠面板v-model:active的值，在我手动改这个值的同时折叠或者收起对应的面板
