### ISSUE TITLE
nut-collapse 在支付宝小程序中内容高度始终为0[bug]

### ISSUE THREAD

**Issue by yanbowe** [jdf2e/nutui#890]
## 问题描述
nut-collapse 在支付宝小程序中内容高度始终为0，当折叠面板激活时，无法显示内容，在微信小程序中是正常的

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

[github](https://github.com/yanbowe/taro3)
## 预期的行为和实际行为
正常显示内容

## 复现步骤，具体代码
![image](https://user-images.githubusercontent.com/43030980/145177183-f75da9cb-9a44-40ce-8ea0-c5d90e87312a.png)
![image](https://user-images.githubusercontent.com/43030980/145177246-3946fc44-6574-4fa0-b336-332a4e559910.png)

## 相关环境信息
- **操作系统**：windows10
- **Node 版本**：v16.13.0
- **NutUI 版本**： "@nutui/nutui-taro": "^3.1.12", "@tarojs/taro": "^3.3.16",
- **Vue 版本**：3.2.24
- **引用方式**： NPM

**Comment by yanbowe** [comment]
补充： 当折叠面板为fasle时，点击其他面板报错
![image](https://user-images.githubusercontent.com/43030980/145341786-89c6536d-3eba-44be-af4e-d5597d2859cf.png)

**Comment by Ymm0008** [comment]
感谢您的反馈，展示问题已修复，将在下个版本发布。但是某些方法需要依赖Taro实现，某些taro api 暂不支持支付宝小程序，我们将在后期解决。  @yanbowe
