### ISSUE TITLE
[bug]使用CountDown组件，控制台总是输出Vue warn

### ISSUE THREAD

**Issue by Iveon** [jdf2e/nutui#891]
使用CountDown组件，控制台总是输出一下内容：
[Vue warn]: Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop.

控制台还有一个console.log("componentName", componentName)输出
 componentName nut-countdown

**Comment by Iveon** [comment]
CountDown这个不处理，开发阶段一会调试器就崩溃了

下面这个是Checkbox的
[Vue warn]: injection "parent" not found. 
  at <NutCheckbox modelValue=false onUpdate:modelValue=fn icon-size="14" >

**Comment by sumy7** [comment]
发现有个pr在处理CountDown的这个问题

#879
