### ISSUE TITLE
使用tabbar 警告路由出错-如下截图，配置to无法正常调转报router没有push属性

### ISSUE THREAD

**Issue by jandy0414** [jdf2e/nutui#892]
![image](https://user-images.githubusercontent.com/35617197/145324653-7123c405-3c25-49ce-a142-729ad414c91c.png)

![image](https://user-images.githubusercontent.com/35617197/145324671-9d96b71a-fd45-4092-a67f-f0f76cf881c6.png)

**Comment by Drjingfubo** [comment]
请问你有安装vue-router吗？

**Comment by LainNetWork** [comment]
setup里面用useRouter
