### ISSUE TITLE
Taro版本和基础版本的组件上的差别

### ISSUE THREAD

**Issue by bobokingbao** [jdf2e/nutui#904]
## 你想知道什么？
在用Taro3.X版本，UI前端选用的NutUI，在开发过程中发现nutui和nutui-taro在组件上还是有些差别。比如Grid，在taro版本中没有出现。Grid这个组件不知道什么时候能合并到taro版本中。
##建议
对于nutui版本和其他版本的组件上的差别是都可以在发布的时候有个提示。

**Comment by szg2008** [comment]
12.22发布之后就有了
