### ISSUE TITLE
[bug]nut-textarea编译成h5之后会有bug，无法打开页面

### ISSUE THREAD

**Issue by Breeze1114** [jdf2e/nutui#905]
## 问题描述
使用了nut-textarea后，用npm run dev:h5打开页面，会报Object(...) is not a function。
但是如果加上readonly属性就不会报错；
而且用npm run build:h5编译完在服务器上运行也不会报错（在本地nginx运行还是会报错），目前不知道是什么原因
1、在本地nginx运行
![image](https://user-images.githubusercontent.com/46240676/146733199-82fd3cdf-df3e-4e79-a34f-4b4080a5f2a8.png)

2、在本地run dev运行
![image](https://user-images.githubusercontent.com/46240676/146733278-ac9151e2-11b2-4416-a631-9e44d536d993.png)

3、本地代码截图
![image](https://user-images.githubusercontent.com/46240676/146733470-19716d96-dee2-4a6f-9e0f-645b69c14270.png)

4、注释掉代码之后执行页面
![image](https://user-images.githubusercontent.com/46240676/146733611-1d40fce2-e0dc-4189-9b8d-0dbf8da068c6.png)
![image](https://user-images.githubusercontent.com/46240676/146733659-bb2ee533-10b4-40d2-9f81-fd2cabfde373.png)

## 最小可复现仓库
> 
任意h5页面加上nut-textarea组件，然后npm run dev:h5  就可以复现

## 预期的行为和实际行为
预期可以在本地dev运行代码可以正常使用nut-textarea组件

实际运行会报错

## 复现步骤，具体代码
任意h5页面加上nut-textarea组件，然后npm run dev:h5  就可以复现

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：v12.20.0
- **NutUI 版本**： @nutui/nutui@3.1.12 /@nutui/nutui-taro@3.1.12
- **Vue 版本**：3.2.26
- **引用方式**： NPM
- **taro版本**： 3.3.17

**Comment by szg2008** [comment]
本地测试了一下，没有发现您上面的问题，方便的话发个最小复现仓库的链接，我们看一下，🙏

**Comment by Breeze1114** [comment]
> 本地测试了一下，没有发现您上面的问题，方便的话发个最小复现仓库的链接，我们看一下，🙏
不好意思，我加了一个依赖"@vue/shared": "3.2.26",，并且重新安装了依赖包后就没办法重现了
