### ISSUE TITLE
[bug]tabs 在微信小程序里面点击没反应

### ISSUE THREAD

**Issue by gp5251** [jdf2e/nutui#907]
## 问题描述

tabs 在微信小程序里面点击没反应
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by gp5251** [comment]
我试了你们所有的组件，都不响应点击事件，但是你们的示例小程序可以，能否给个git地址我去对比看看？
![image](https://user-images.githubusercontent.com/995572/147126103-7663c712-28a2-4cbf-9146-17fdab803c53.png)

**Comment by szg2008** [comment]
辛苦提供一下最小复现仓库，我们好排查问题，另外您也可以参考https://github.com/jdf2e/nutui-demo/tree/master/taro/src对比一下

**Comment by gp5251** [comment]
请见 https://github.com/gp5251/test_nutui
另外，我把你们demo里的代码都复制过来了，，也是不行，，

**Comment by b2nil** [comment]
@gp5251 @szg2008
这是 `NutUI` Taro 版本的编译问题，和许多报小程序原生标签模板找不到的问题类似， `NutUI` 需要针对 Taro  的特殊性修改一下 `@vitejs/plugin-vue` 的编译配置：
https://github.com/jdf2e/nutui/blob/937ade66d4777d47093eb03a82aaff9d793af477/vite.config.build.taro.vue.ts#L25


以 `nut-button` 这个组件为例，源码点击事件写的是`@click`，按照现在的编译配置，会被编译成 `onClick`，这在小程序中是不会被触发的。因此需要将 `@click` 编译为小程序能够触发的 `onTap` 事件才行，或者直接将源码改为 `@tap`。
https://github.com/jdf2e/nutui/blob/937ade66d4777d47093eb03a82aaff9d793af477/src/packages/__VUE/button/index.taro.vue#L2

**Comment by gp5251** [comment]
有修复计划吗？

**Comment by richard1015** [comment]
@gp5251   @b2nil 
检查一下是否配置了 [@tarojs/plugin-html](https://taro-docs.jd.com/taro/docs/use-h5/)

所有事件都失效，应该是没有配置这个插件，具体可以看一下文档

https://nutui.jd.com/#/starttaro

**Comment by richard1015** [comment]
@b2nil  ，感觉您的反馈，像您之前提的那个问题  例如 button picker 等原生组件 失效问题，目前我们和taro测  也已经沟通，现状解决方案如下
现状： taro 现有编译适配流程是 基于运行时对vue文件进行分析，识别taro原生组件及相关的第三方 div、a、input 等组件  进行标记转换，  我们组件库开发者在使用过程中 已经被编译后了，所以 taro 在运行时中根本识别不到该组件的js文件，也就导致开发者使用 taro 原生组件时，会导致报错
解决方案：
1、 改造 nutui-taro 打包逻辑，打包时，构建出 vue源文件，然后让 taro 在运行时状态，直接识别到vue文件然后走taro的逻辑，但是这个方案我们考虑到，组件内部是vue ts文件，开发者如果一旦不是 ts 环境，就会报错，所以这一方案我们还在进一步考虑
2、 改造 nutui-taro 现有构建逻辑， 将taro 识别 vue  中 原生组件 taro-button、picker 等组件的转换逻辑添加到 nutui 构建层，但是这一方案，我们需要时刻与taro测的逻辑保持同步

目前这两个方案都在 进行中，请大家耐心等待

**Comment by b2nil** [comment]
@richard1015
从用户体验的角度来说，无论是哪个方案，最好先尽快出一个能让用户先顺利使用起来的，别让用户望而却步，后续再去完善 NutUI 团队觉得较好的一个方案。

**Comment by provenceo** [comment]
什么时候可以解决好呢

**Comment by b2nil** [comment]
@Provenceo 
按照上面提到的配置 @tarojs/plugin-html 插件，直接就可以解决点击事件的问题。

**Comment by Provenceo** [comment]
![image](https://user-images.githubusercontent.com/43238325/147715442-37681ab3-0f46-4b58-9de0-83f39ac2ffd9.png)
配置了但是也不行 还不能渲染html标签

**Comment by provenceo** [comment]
> @b2nil 
![image](https://user-images.githubusercontent.com/43238325/147717271-1826761c-ea93-45e8-b4ff-bddaedcdee38.png)
这是什么问题

**Comment by b2nil** [comment]
依赖安装的问题吧，重新安装一下所有依赖，看看 @tarojs/shared 是否存在吧。

**Comment by gp5251** [comment]
> @Provenceo 按照上面提到的配置 @tarojs/plugin-html 插件，直接就可以解决点击事件的问题。

有人试过吗？我这配置了插件，还是不能点击

**Comment by szg2008** [comment]
> > @Provenceo 按照上面提到的配置 @tarojs/plugin-html 插件，直接就可以解决点击事件的问题。
> 
> 有人试过吗？我这配置了插件，还是不能点击

请提供一下复现仓库吧，正常配置之后是可以点击的

**Comment by gp5251** [comment]
> > > @Provenceo 按照上面提到的配置 @tarojs/plugin-html 插件，直接就可以解决点击事件的问题。
> > 
> > 
> > 有人试过吗？我这配置了插件，还是不能点击
> 
> 请提供一下复现仓库吧，正常配置之后是可以点击的

还是原仓库  https://github.com/gp5251/test_nutui

**Comment by Drjingfubo** [comment]
这个仓库下载以后tab是可以点击的,button的点击事件也是可以生效的
![image](https://user-images.githubusercontent.com/50685476/149862232-3741de94-c90f-41a4-bb7d-e84dd80d0786.png)
