### ISSUE TITLE
Icon 组件是否可以应用项目内的png,jpeg等图标文件

### ISSUE THREAD

**Issue by bobokingbao** [jdf2e/nutui#910]
## 你想知道什么？
问题原因：在采用iconfont方案的时候在H5端，和钉钉小程序IDE的调试端
可以正常显示图标，但是一旦放到钉钉真机上测试的时候，所有图标都是空白，因此打算采用以下方式加载图片
`<nut-icon icon="../assets/crm_active.png" text="文字"></nut-grid-item>`
但是图片加载不上。

环境：
Taro v3.3.17
 nutui/nutui-taro 3.1.14

想知道的方案
1：在钉钉真机上测试显示空白，是否有什么解决方案
2：icon直接引用本地图标是否支持，如果支持要什么配置

**Comment by haiweilian** [comment]
- 本地图片加载方式错误：

https://taro-docs.jd.com/taro/docs/static-reference

因为 prop 到了内部实际上是一个动态的变量，webpack 并不会解析成路径，所有打包皆是如此。

这样写

```html
<nut-grid-item :icon="require('../assets/crm_active.png')" text="文字"></nut-grid-item>
```

或者

```js
import crmActive  from  '../assets/crm_active.png'
```

```html
<nut-grid-item :icon="crmActive" text="文字"></nut-grid-item>
```

- iconfont 方案的我倒是没写过钉钉小程序，等作者给看看吧。

**Comment by bobokingbao** [comment]
> * 本地图片加载方式错误：
> 
> https://taro-docs.jd.com/taro/docs/static-reference
> 
> 因为 prop 到了内部实际上是一个动态的变量，webpack 并不会解析成路径，所有打包皆是如此。
> 
> 这样写
> 
> ```
> <nut-grid-item :icon="require('../assets/crm_active.png')" text="文字"></nut-grid-item>
> ```
> 
> 或者
> 
> ```js
> import crmActive  from  '../assets/crm_active.png'
> ```
> 
> ```
> <nut-grid-item :icon="crmActive" text="文字"></nut-grid-item>
> ```
> 
> * iconfont 方案的我倒是没写过钉钉小程序，等作者给看看吧。

按照这个方法可以加载本地的png，svg了真机测试也通过，多谢啦。

借这贴描述下iconfont暂时遇到的问题把：
问题复现步骤：
1：参照：https://nutui.jd.com/#/icon 
                 https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d8d11a391&helptype=code
    以上的两个link，可以获取到如下文件（此时没有选择link中描述的生成**多色图标**的方法）
```
/assets/font/demo.css
/assets/font/demo_index.html
/assets/font/iconfont.css
/assets/font/iconfont.js
/assets/font/iconfont.json
/assets/font/iconfont.ttf
/assets/font/iconfont.woff
/assets/font/iconfont.woff2
```
这个时候在本地H5调式，和钉钉小程序IDE里面调试，以及**真机调试**，都可获取到正常的图标，但是是黑白色的。

2：这次选择link中描述的生成**多色图标**的方法，仍然可以获取到上述css，json，woff等文件（此时的图标都是彩色的）
      这个时候在本地H5调式，和钉钉小程序IDE里面调试，都可获取到正常的图标，并且是彩色的。但是在钉钉小程序IDE的真机调试时，所有的图标都没有正常出现。

有可能时我生成iconfont的方式不正确，或则加载上的问题，等调查后再说
