### ISSUE TITLE
Input Number change触发时机不对[bug]

### ISSUE THREAD

**Issue by Anberm** [jdf2e/nutui#919]
## 问题描述

针对change事件，我们应当遵循先emit  update:modelValue，再emit change的顺序
![image](https://user-images.githubusercontent.com/34148806/147536890-b233b22c-9623-4c1c-907e-6a7523ffde98.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by lonelyWalkor** [comment]
textarea 组件 的 change 事件的触发也存在这个问题

**Comment by Anberm** [comment]
> textarea 组件 的 change 事件的触发也存在这个问题

已补充

**Comment by richard1015** [comment]
fix v3.1.15 a87a43985a626d90369e95c7e18dfc63ed10c295
