### ISSUE TITLE
什么时候可以支持使用iconfont？

### ISSUE THREAD

**Issue by splinfengwang** [jdf2e/nutui#92]
现在的图标貌似都是通过图片进行引入

**Comment by Franslee** [comment]
现在大部分图标使用的是svg。我们认为svg更适合移动端组件库，没有使用iconfont的计划。

**Comment by ilero** [comment]
请问，如何扩展svg呢，我们想用自己的图标

**Comment by yoyo837** [comment]
请reopen这个. 即便不打算支持, 也应该解释一下再关闭.
