### ISSUE TITLE
[bug]popup组件props的closeable动态传值无效

### ISSUE THREAD

**Issue by majoker** [jdf2e/nutui#923]
## 问题描述
popup组件props的closeable动态传值无效
## 最小可复现仓库
https://github.com/jdf2e/nutui-demo.git
复现组件：src/feedback/pages/popup/index.vue)
## 预期的行为和实际行为
期望通过动态给closeable赋值，决定是否展示关闭按钮，实际无法通过属性控制

## 复现步骤，具体代码
```
    <nut-cell
      title="图标位置"
      is-link
      @click="state.showIconPosition = true"
    ></nut-cell>
    <nut-popup
      position="bottom"
      :closeable='state.showIconPosition'
      close-icon-position="top-left"
      :style="{ height: '20%' }"
      v-model:visible="state.showIconPosition"
    ></nut-popup>
```

将上面代码放到demo项目对应的组件就可以复现

## 相关环境信息
- **操作系统**：macos
- **Node 版本**：node14
- **NutUI 版本**： @nutui/nutui@3.1.14  
- **Vue 版本**：vue4
- **引用方式**：   NPM

**Comment by szg2008** [comment]
已支持此功能，v3.1.15版本发布
