### ISSUE TITLE
Switch 开关，size失效[bug]

### ISSUE THREAD

**Issue by Timberwolves-code** [jdf2e/nutui#924]
## 问题描述
Switch 开关，size失效，不能设置 Switch的大小变化

## 相关环境信息
- **操作系统**： Windows 10
- **Node 版本**：v16.13.1
- **NutUI 版本**： @nutui/nutui-taro@3.1.8
- **Vue 版本**： @vue@3.0.0
- **引用方式**：  NPM

**Comment by szg2008** [comment]
size指的是在loading状态下图标的尺寸

**Comment by szg2008** [comment]
已补充文档说明

**Comment by Timberwolves-code** [comment]
好的，谢谢🙏
