### ISSUE TITLE
[bug] taro-vue for weapp nut-dialog 组件 点击 按钮无法关闭 弹窗

### ISSUE THREAD

**Issue by Mo-zixin** [jdf2e/nutui#926]
## 问题描述
taro-vue for weapp nut-dialog 组件 点击 按钮无法关闭 弹窗 
使用变量 打开dialog 后 点击取消 确定按钮 无法关闭 

nut-button 的点击事件 h5 与微信小程序的 点击事件绑定不一样  一个是h5  @click="isLogin"  微信 @tap="onclick"

## 最小可复现仓库(官方示例仓库 )
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
<template>
  <view class="home">
    <nut-dialog
      title="基础弹框"
      content="这是基础弹框。"
      v-model:visible="visible"
    >
  </nut-dialog>
  </view>
</template>

<script>
export default {
  data(){
    return{
      visible:false
    }
  },
  methods:{
    editVisible(){
      this.visible =!this.visible
    }
  }
}
</script>
<style lang="scss">
 
</style>  

## 相关环境信息
   Taro CLI 3.3.19 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 14.18.1 - C:\WindowApps\Professional\nodejs\node.EXE
      Yarn: 1.22.15 - C:\WindowApps\Professional\yarn\bin\yarn.CMD
      npm: 6.14.15 - C:\WindowApps\Professional\nodejs\npm.CMD

 
- **NutUI 版本**：@nutui/nutui-taro@^3.1.8
- **Vue 版本**：3.2.26
- **引用方式**：   NPM

**Comment by richard1015** [comment]
请升级最新版本测试一下，相同问题也可参考 https://github.com/jdf2e/nutui/issues/907

检查一下是否配置了 [@tarojs/plugin-html](https://taro-docs.jd.com/taro/docs/use-h5/)

所有事件都失效，应该是没有配置这个插件，具体可以看一下文档

https://nutui.jd.com/#/starttaro
