### ISSUE TITLE
Nutui 引入SSR项目，出现Element is undefine的错误

### ISSUE THREAD

**Issue by hyphappy011** [jdf2e/nutui#927]
## 问题描述
参考 http://doc.ssr-fc.com/docs/features$started 创建一个vue3 ssr项目。
然后在项目文件夹web/components/layout/App.vue注册nutui. 如下：

`<template>
  <router-view />
</template>

<script lang="ts">
import {getCurrentInstance} from 'vue'
import NutUI from '@nutui/nutui'
import '@nutui/nutui/dist/style.css'
// 在这里可以进行一些全局组件的注册逻辑
export default {
  created() {
    const app = getCurrentInstance()?.appContext.app
    app?.use(NutUI)
  }
}
</script>`

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

https://github.com/zhangyuang/ssr/tree/dev/example/nestjs-vue3-ssr

## 复现步骤，具体代码
在上述项目中的page/index/render.vue 引入nut-button, 如下：

`<template>
  <div>
    <Search />
    <nut-button type="primary">主要按钮</nut-button>
    <nut-button type="info">信息按钮</nut-button>
    <template v-if="indexData">
      <Slider :data="indexData[0].components" />
      <Rectangle :data="indexData[1].components" />
    </template>
    <template v-else>
      <img
        src="https://gw.alicdn.com/tfs/TB1v.zIE7T2gK0jSZPcXXcKkpXa-128-128.gif"
        class="loading"
      />
    </template>
  </div>
</template>

<script lang="ts">
import {defineComponent} from 'vue'
import {mapState} from 'vuex'
import Slider from '@/components/slider/index.vue'
import Rectangle from '@/components/rectangle/index.vue'
import Search from '@/components/search/index.vue'

export default defineComponent({
  components: {
    Slider,
    Rectangle,
    Search
  },
  computed: {
    ...mapState({
      indexData: state => state.indexStore?.data
    })
  }
})
</script>

<style></style>`

然后，yarn run start就会出错。

**我尝试试修改了nut-ui，nutui.umd.js几处代码后能够正常显示：**
**第一处：**
注释2900行处，const _window= window代码
`	function requestAniFrame() {
		/*	const _window = window
			if (typeof _window !== "undefined") {
				return _window.requestAnimationFrame || _window.webkitRequestAnimationFrame || function (callback) {
					_window.setTimeout(callback, 1e3 / 60);
				};
			} else {
				_window = window
				return function (callback) {
					setTimeout(callback, 1e3 / 60);
				};
			}*/
	}
	var requestAniFrame$1 = requestAniFrame();`

**第二处：**
816行处
teleport: {
			type: [String,Element],
			default: "body"
		},
修改为
	teleport: {
			type: [String, String],
			default: "body"
		},

应该是在服务端，无法识别Element，Window这些对象。

**Comment by Drjingfubo** [comment]
暂时没有支持服务端渲染的计划，后续支持后同步到您
