### ISSUE TITLE
[bug] OverLay 中的lock-scroll属性和close-on-click-overlay属性不生效

### ISSUE THREAD

**Issue by provenceo** [jdf2e/nutui#935]
## 问题描述

OverLay 中的lock-scroll属性和close-on-click-overlay属性不生效

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为

无任何效果

## 复现步骤，具体代码

<template>
  <view id="OverLay">
    <nut-overlay :lock-scroll="true" :close-on-click-overlay="false" v-model:visible="OverLayShow" :z-index="2000">
      <div class="wrapper">
        <div class="content">
          <div class="title m-b-30">套餐商品</div>
         </div>
        </div>
      </div>
    </nut-overlay>
  </view>
</template>

<script>
export default {
  name: "OverLay",
  data(){
    return{
      OverLayShow:true
    }
  },
}
</script>

## 相关环境信息
- **操作系统**：win11 x64
- **Node 版本**：14.18.1
- **NutUI 版本**： "@nutui/nutui-taro": "^3.1.14",
- **Vue 版本**： @vue/cli 4.5.15
- **引用方式**：  npm/yarn

**Comment by Provenceo** [comment]
<template>
  <view id="OverLay">
    <nut-overlay :lock-scroll="true" :close-on-click-overlay="false" v-model:visible="OverLayShow" :z-index="2000">
      <div class="wrapper">
        <div class="content">
          <div class="title m-b-30">套餐商品</div>
         </div>
        </div>
      </div>
    </nut-overlay>
  </view>
</template>

<script>
export default {
  name: "OverLay",
  data(){
    return{
      OverLayShow:true
    }
  },
}
</script>

**Comment by provenceo** [comment]
![image](https://user-images.githubusercontent.com/43238325/148735744-71b93814-8d63-4e02-bae6-ca42c511c897.png)

**Comment by szg2008** [comment]
close-on-click-overlay测了一下，属性是生效的。锁定禁止滑动，需要自己拿到外层容器，然后添加style使其禁止。目前组件无法做到

**Comment by provenceo** [comment]
@szg2008 #950 这个麻烦看下呗
