### ISSUE TITLE
[suggest]nut-picker 组件 list-data 不支持对象性数组

### ISSUE THREAD

**Issue by hopefuture** [jdf2e/nutui#938]
nut-picker 组件 list-data 目前只支持字符串数组，如果数组中每一项是对象，则不支持，请问这个有计划支持吗，感谢！！

如 ： 
list-data 设为以下格式是不支持的
```json
[
    {
      text: '苹果',
      value: '1'
    }
  ]
```

**Comment by richard1015** [comment]
2.x 版本吗？  暂无规划，建议您可以，通过js设置成标准的 数组类型
