### ISSUE TITLE
Swiper 组件使用Taro3在微信小程序中无法使用[question]

### ISSUE THREAD

**Issue by cyatom01** [jdf2e/nutui#944]
## Swiper 组件使用Taro3在微信小程序中无法使用

您好，我使用Taro3跨端框架UI框架选用Taro3集成的Nutui ，发现Swiper 组件在微信小程序中无法展示，微信开发工具提示：

**Comment by dtcui** [comment]
采用官方例子运行： 
Template `tmpl_0_swiper` not found.
  347 | 
  348 | <template name="tmpl_2_container">
> 349 |   <template is="{{xs.a(2, i.nn, l)}}" data="{{i:i,cid:2,l:xs.f(l,i.nn)}}" />
      |                ^
  350 | </template>
  351 | 
  352 | <template name="tmpl_3_catch-view">

**Comment by cyatom01** [comment]
Template `tmpl_0_swiper` not found.
  
template name="tmpl_2_container"
template is="{{xs.a(2, i.nn, l)}}" data="{{i:i,cid:2,l:xs.f(l,i.nn)}}"
      |                ^
/template

template name="tmpl_3_catch-view"

**Comment by szg2008** [comment]
优先使用原生swiper，最近正在修复此问题
