### ISSUE TITLE
[bug] ImagePreview  图片预览设置轮播时长无效

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#947]
<nut-imagepreview :show="resData.showPreview" :images="resData.imgData" :content-close="true" :init-no="imageIndex.dot" @close="hideFn" :autoplay="0" />
<img v-for="(image, index) in resData.imgData" :key="image.id" :index="index" :src="image.src" alt="" @click="showFn(index)" />
![image](https://user-images.githubusercontent.com/40783535/149499686-158fbe91-5ec3-4ec6-ad0b-d632e1ef5e8b.png)
autoplay设置为0，还是会自动轮播

**Comment by szg2008** [comment]
我们这边测试没有问题，如果方便，请提供一下最小复现仓库，我们这边好排查
