### ISSUE TITLE
参考 https://nutui.jd.com/#/navbar

### ISSUE THREAD

**Issue by ActingCute** [jdf2e/nutui#948]
参考 https://nutui.jd.com/#/navbar

_Originally posted by @richard1015 in https://github.com/jdf2e/nutui/issues/570#issuecomment-899956493_

slot:tabs vue3版本用不了

**Comment by richard1015** [comment]
navbar组件 春节前   修复发布

**Comment by richard1015** [comment]
3.1.16 已发布
