### ISSUE TITLE
[bug] 在案例中创建多个nut-swipe

### ISSUE THREAD

**Issue by provenceo** [jdf2e/nutui#950]
![image](https://user-images.githubusercontent.com/43238325/149863417-3a3017ca-f4b2-4421-86ee-2b21506f5b85.png)

## 问题描述

例如有三个nut-swipe ，先展开一个，在展开第二个的时候，第一个和第二个同时展开，依次类推
## 最小可复现仓库
在案例中创建多个nut-swipe

## 预期的行为和实际行为
例如有三个nut-swipe ，先展开一个，在展开第二个的时候 关闭第一个，依次类推

## 相关环境信息
- **操作系统**： win11
- **Node 版本**：v14.18.1
- **NutUI 版本**： ^3.1.14
- **Vue 版本**：^3.0.0
- **引用方式**：  CDN / NPM ？ NPM

**Comment by provenceo** [comment]
https://codesandbox.io/s/nutui3-0-vite-js-forked-vr3uu?file=/src/App.vue @richard1015

**Comment by provenceo** [comment]
打开后请刷新内部浏览器

**Comment by richard1015** [comment]
加入我们微信群，咱们实时沟通一下呢，还是没有复现

**Comment by richard1015** [comment]
我理解的你想要的是一个功能，  多个swipe 只能一个展开

**Comment by provenceo** [comment]
是的 只显示一个 现在是可以同时展开多个

**Comment by provenceo** [comment]
你们微信群的二维码发一下呗

**Comment by richard1015** [comment]
> 是的 只显示一个 现在是可以同时展开多个

那你参考咱们文档中 `异步控制` 的代码 去自己写逻辑就可以了， 微信群在官网底部 加入我们 链接上

**Comment by yangzhiganluk** [comment]
> 
我也遇到这个问题了，请问是怎么解决呀
