### ISSUE TITLE
[bug] 移动端页面使用了swiper组件，在该范围内上下滑动不了，只能在swiper区域外才可以上下滑动

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#951]
## 问题描述
在使用了nut-swiper的区域内不能上下滑动，在区域外可上下滑动
![image](https://user-images.githubusercontent.com/40783535/149898779-60fd55c7-3926-4838-a3e1-31cb854c03f9.png)

**Comment by szg2008** [comment]
这么做是为了防止滑动事件冲突

**Comment by szg2008** [comment]
可以通过属性 isPreventDefault 和 isStopPropagation控制。请移步查阅文档。https://nutui.jd.com/#/swiper
