### ISSUE TITLE
tab组件在小程序上全部报错

### ISSUE THREAD

**Issue by shijunti19** [jdf2e/nutui#955]
## 问题描述

![image](https://user-images.githubusercontent.com/5392211/149947145-a0110705-8f98-4a69-a654-a904c3e1d0b1.png)

![image](https://user-images.githubusercontent.com/5392211/149947329-66994b94-fd53-4380-b0ae-a2b192ab8336.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
![image](https://user-images.githubusercontent.com/5392211/149947145-a0110705-8f98-4a69-a654-a904c3e1d0b1.png)
小程序
dev:weapp
## 相关环境信息
 "@nutui/nutui-taro": "^3.1.14",
    "@tarojs/components": "^3.4.0",
    "@tarojs/plugin-html": "^3.4.0",
    "@tarojs/runtime": "^3.4.0",
    "@tarojs/taro": "^3.4.0",
    "vue": "^3.2.26",
    "vue-router": "^4.0.12",
    "vuex": "^4.0.2"

**Comment by shijunti19** [comment]
[
      "@tarojs/plugin-framework-vue3",
      {
        mini: {
          compilerOptions: {
            isCustomElement: tag => tag.includes("scroll-view"),
            whitespace: "preserve"
          }
        }
      }
    ] 导致的

**Comment by shijunti19** [comment]
[
      "@tarojs/plugin-framework-vue3",
      {
        mini: {
          compilerOptions: {
            isCustomElement: tag => tag.includes("scroll-view"),
            whitespace: "preserve"
          }
        }
      }
    ] 导致的

**Comment by emorywang** [comment]
我也发现同样的问题，不过我是用了isCustomElement: tag => tag.includes('ec-canvas'),导致的，所以看起来isCustomElement是真正原因？
