### ISSUE TITLE
[bug]nut-infiniteloading，nut-swiper控制台警告问题

### ISSUE THREAD

**Issue by Github-AZhe** [jdf2e/nutui#957]
Failed to resolve component: scroll-view
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

------------

目前这个问题是优先采取使用原生组件吗？
（使用webpack chain 也没有解决掉）

**Comment by wlchn** [comment]
同样问题InfiniteLoading在h5上提示：
```
[Vue warn]: Failed to resolve component: scroll-view
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

```
版本:     "@nutui/nutui-taro": "^3.1.12"

**Comment by szg2008** [comment]
scroll-view问已修复，升级最新版本以及Taro3.4.x

**Comment by champion0122** [comment]
> scroll-view问已修复，升级最新版本以及Taro3.4.x

```
Failed to resolve component: scroll-view
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```
nutui-taro版本3.1.18. taro版本3.4.4
使用 InfiniteLoading出现该问题

**Comment by holyrong** [comment]
很多组件都有问题：我的环境nutui3.1.18，Taro：3.4.4
DatePicker在year-month模式下，直接就不生效；换成Picker，结果，v-model绑定后，选择第二次后，月份不正确，不绑定就不影响。List组件，根本就加载不了数据，控制台报错：Failed to resolve component: scroll-view
还有很多很多。。。。
@szg2008

**Comment by holyrong** [comment]
很多组件都有问题：我的环境nutui3.1.18，Taro：3.4.4
DatePicker在year-month模式下，直接就不生效；换成Picker，结果，v-model绑定后，选择第二次后，月份不正确，不绑定就不影响。List组件，根本就加载不了数据，控制台报错：Failed to resolve component: scroll-view
还有很多很多。。。。
@szg2008
