### ISSUE TITLE
[bug] 使用menu菜单组件，如果页面内容过长，且滑动一段距离，点击后弹出的内容固定在一个位置

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#958]
## 问题描述
在列表页面使用的menu菜单组件，列表高度超过100vh，滑动一段距离后点击菜单，弹出的内容固定了位置显示
![image](https://user-images.githubusercontent.com/40783535/150060893-c7311fa0-6cb0-4130-b5c6-b81b32553319.png)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

**Comment by yangjinjun3** [comment]
已修复，多谢

**Comment by wangyongxiong** [comment]
重新安装，还是会出现原来的问题

**Comment by szg2008** [comment]
本周发版之后就可以更新了，v3.1.16

**Comment by richard1015** [comment]
3.1.16 已发布
