### ISSUE TITLE
可以单独引入 Toast 吗？

### ISSUE THREAD

**Issue by xushuailing** [jdf2e/nutui#96]
import { Toast } from '@nutui/nutui';
![image](https://user-images.githubusercontent.com/25056086/57612355-48a0d980-75a7-11e9-83fe-819b7c66af1e.png)

**Comment by Franslee** [comment]
可以的，不过这种写法需要安装一个插件。请参考官网快速上手-按需加载部分 http://nutui.jd.com/#/start
