### ISSUE TITLE
[bug]使用nut-elevator/taro抛错

### ISSUE THREAD

**Issue by NiShuiXingZ** [jdf2e/nutui#966]
## 问题描述
在微信小程序运行是会抛一个warning和一个error。TypeError: Cannot read property 'height' of undefined。
![image](https://user-images.githubusercontent.com/4465323/150454837-8756e12b-6d3b-4e22-b00d-0c17fba36073.png)

## 复现步骤，具体代码
1、在app.ts中引入import Elevator并use(Elevator);
![image](https://user-images.githubusercontent.com/4465323/150454535-4b3082bd-f48c-449f-90a7-e38643de5f83.png)
2、在index/index.vue使用nut-elevator;
![image](https://user-images.githubusercontent.com/4465323/150454651-24b0ae3b-d18b-43bb-bb04-b1d745d6a3dc.png)
3、运行dev:weapp;

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：16
- **NutUI 版本**： @nutui/nutui-taro@3.1.14
- **Vue 版本**：3.2.27
- **引用方式**： NPM
- **运行环境**： 微信小程序

**Comment by xyezir** [comment]
解决了？怎么就closed了？
