### ISSUE TITLE
[suggest]能否在“Elevator 电梯楼层”组件中，点击展开后将选中的自动滚动上来显示，而不是要往下拉显示

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#978]
## 你建议我们做什么？

现在...
![image](https://user-images.githubusercontent.com/40783535/150909810-f7de6c65-f371-434d-8fb3-a57a022d9095.png)

如果你能...
将选中的电梯楼层自动滚动上来显示，一目了然看到选中的数据

它将使...
体验会更加优秀

## 其它

无

**Comment by szg2008** [comment]
已经暴露ScrollTo，可自行调用，下版本修复
