### ISSUE TITLE
checkbox 点击label勾选不准确

### ISSUE THREAD

**Issue by dixsonruan** [jdf2e/nutui#98]
js调整html font-size后，直接使用<nut-checkbox></nut-checkbox>组件label继承根元素font-size，label标签被放大，点击不准确
![图片](https://user-images.githubusercontent.com/36290724/57755071-89712d80-7722-11e9-81b1-e9abbeb1e2c5.png)

**Comment by Franslee** [comment]
感谢反馈，我们后续优化
