### ISSUE TITLE
[bug] “CountDown 倒计时”组件，在点击获取验证码的时候，然后给他赋值倒计时时间，不起作用，直接为0

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#982]
## 问题描述
在一个登录页面表单里，需要给获取验证码后倒计时，点击获取验证码后赋值倒计时时间不起作用，直接为0
![image](https://user-images.githubusercontent.com/40783535/151152636-e8241c24-c230-48d1-a190-a11c4a5df3df.png)
![image](https://user-images.githubusercontent.com/40783535/151153059-35f312a0-9ff0-4a2c-b507-480127108e81.png)
![image](https://user-images.githubusercontent.com/40783535/151152934-93501e21-f7bf-4e29-87ef-2cc04334ea70.png)

**Comment by yangxiaolu1993** [comment]
你在这个链接中试试，模拟了一下你描述的场景
https://codehouse.jd.com/?source=share&type=vue&mainJs=Ly9pbXBvcnQgVkNvbnNvbGUgZnJvbSAidmPGDyI7Ci8vdmFyIHbIID0gbmV3yS8oKTsKx0J7IGNyZWF0ZUFwcCB9yEd1xELHIcQZxhcuL2FwcC7NHU51dFVJxx9AbnV0dWkvxQbKIsc2c2Nzc8sVzCwvZGlzdC9zdHlsZS7GJukAkihBcHApLnVzZSjFaSkubW91bnQoIiNhcHAiKTs%3D&appValue=PHRlbXBsYXRlPgogIAk8bnV0LWJ1dHRvbiB0eXBlPSJzdWNjZXNzIiBAY2xpY2s9ImNvdW50RG93biI%2B6aqM6K%2BB56CBPC%2FKOMRIICDFScUrZG93biA6ZW5kLXRpbWU9ImVuZCIgPsYyySE%2BCjwv6gCJCjxzY3JpcHTES2ltcG9ydCB7IHJlZixyZWFjdGl2ZSx0b1JlZnMgfSBmcm9tICd2dWUnOwogIGV4xS1kZWZhdWx0IHvlAItzZXR1cChwcm9wcynHEyAgY29uc3Qg5ACS5ADLID0gyFsoyCIgIGVuZDogJycsxxF9KcRjyj3pAQkgPSAoKT0%2ByDkJyFYuZW5kID0gRGF0ZS5ub3coKSArIDUwICogMTAwMMhVxwhyZXR1cm7pAJ%2FEZMdeyH8gIC4uLuYA%2BCjIYinIRuYAmsRNfQo8L%2BgBPgo%3D&scssValue=
