### ISSUE TITLE
[bug] Layout组件问题

### ISSUE THREAD

**Issue by deajax** [jdf2e/nutui#984]
## 问题描述
1、row组件在使用flex-wrap="wrap"时不生效；
2、row组件在使用: gutter="16"时，first和last会有一个col-gutter属性，强制把padding去掉，此时会造成第一格和最后一个尺寸，与其他col的内容尺寸不同，造成错行问题；

## 最小可复现仓库

https://codesandbox.io/s/stoic-euclid-tqt5n?file=/src/App.vue

## 预期的行为和实际行为
1、
预期 `class="nut-row-flex-wrap"`
实际 `class="nut-row-flex-nowrap" flex-wrap="wrap"`
2、
预期 `<col style="padding-left: 8px; padding-right: 8px;">`
实际 `.nut-col-gutter:first-child { padding-left: 0!important; }`
造成：第一个card width:109px，其他card width:101px

## 复现步骤，具体代码
`<nut-row  type="flex" flex-wrap="wrap">
	<nut-col :span="8" v-for="i in 24" :key="i">
		<nut-card img-url="https://via.placeholder.com/150" title="阳澄湖大闸蟹" price="388" />
	</nut-col>
</nut-row>`

`<nut-row  :gutter="16">
	<nut-col :span="8" v-for="i in 24" :key="i">
		<nut-card img-url="https://via.placeholder.com/150" title="阳澄湖大闸蟹" price="388" />
	</nut-col>
</nut-row>`

## 相关环境信息
- **操作系统**：macos 12.2
- **Node 版本**：v14.16.0
- **NutUI 版本**： @nutui/nutui@3.1.15
- **Vue 版本**：3.0.0
- **引用方式**：  taro

**Comment by Ymm0008** [comment]
问题已修复，将在下个版本发布。 @deajax
