### ISSUE TITLE
[bug]NumberKeyboard组件点击数字键盘按钮无反应,只有弹出和收起起作用

### ISSUE THREAD

**Issue by beijibeijing** [jdf2e/nutui#986]
## 问题描述

NumberKeyboard组件点击数字键盘按钮无反应。
https://nutui.jd.com/#/numberkeyboard 中的各种实例都好使，但是自己使用以及官方中在线调试的都不好使。
点击各种类型示例，键盘可以弹出，但是键盘上各种按键无反应，只有点空白处，键盘会收起。

## 最小可复现仓库
官方文档在线调试都不好使。

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： @nutui/nutui@2.x.x  or @nutui/nutui-jdl@1.x.x
- **Vue 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by Drjingfubo** [comment]
目前在线调试的工具不完善，NumberKeyboard组件需要在H5环境下调用
