### ISSUE TITLE
[bug] 3.1.16版本，“Menu 菜单”点击弹出层后会穿透滚动，还有一种是滚动后点击弹出，底部会有缺口

### ISSUE THREAD

**Issue by wangyongxiong** [jdf2e/nutui#992]
## 问题描述
正常情况
![image](https://user-images.githubusercontent.com/40783535/152918460-422f5e01-1986-42e2-8127-41441e1f9120.png)
穿透滚动后
![image](https://user-images.githubusercontent.com/40783535/152918522-344ee045-a256-4f9f-ba60-38ab1708b98a.png)

第二种情况：先滚动页面后固定菜单位置，点击弹出，底部会有缺口
![image](https://user-images.githubusercontent.com/40783535/152918624-e1f84382-f1de-433c-ab55-d5b870b74fac.png)

**Comment by yangjinjun3** [comment]
感谢反馈，方便提供最小的复现仓库吗？
