### ISSUE TITLE
Tabs 选项卡切换的建议

### ISSUE THREAD

**Issue by wangyuwei314** [jdf2e/nutui#996]
可否添加个手势左右滑动切换功能和粘性布局

**Comment by UphkcRNqmafQWcSSSSSS** [comment]
自己写

**Comment by sherlock-7717** [comment]
同求

**Comment by richard1015** [comment]
粘性吸顶近期可以考虑，手势没时间去处理感兴趣可以PR

**Comment by s4595169** [comment]
非常遗憾

**Comment by 0xA1b** [comment]
> 可否添加个手势左右滑动切换功能和粘性布局

这个团队太垃圾了，菜的一批，手势滑动，他们写不出来，一个ui库的质量水平可以从一些需要滑动交互的组件可以看出来，这个组件团队就是垃圾！
（包括taro-ui-vue3的作者也没写出来，可笑的是文档写了 props可配置<swipeable | 是否支持手势滑动切换内容页>，却连自己的demo都没实现手势滑动😄）

**Comment by Drjingfubo** [comment]
tabs粘性布局3.2.3已发布
